### PR TITLE
Enhance DOI parser to deal with special characters

### LINKED ISSUE #10985: Citation relations should be able to handle strange DOIs.
I queried dblp for "Breitenbücher".

Following entry came out:

```bibtex
@InProceedings{Hahn2018b,
  author    = {Michael Hahn and Uwe Breitenb{\"{u}}cher and Frank Leymann and Vladimir Yussupov},
  booktitle = {On the Move to Meaningful Internet Systems. {OTM} 2018 Conferences - Confederated International Conferences: CoopIS, C{\&}TC, and {ODBASE} 2018, Valletta, Malta, October 22-26, 2018, Proceedings, Part {II}},
  date      = {2018},
  title     = {Transparent Execution of Data Transformations in Data-Aware Service Choreographies},
  doi       = {10.1007/978-3-030-02671-4\_7},
  editor    = {Herv{\'{e}} Panetto and Christophe Debruyne and Henderik A. Proper and Claudio Agostino Ardagna and Dumitru Roman and Robert Meersman},
  pages     = {117--137},
  publisher = {Springer},
  series    = {Lecture Notes in Computer Science},
  url       = {https://doi.org/10.1007/978-3-030-02671-4_7},
  volume    = {11230},
  bibsource = {dblp computer science bibliography, https://dblp.org},
  biburl    = {https://dblp.org/rec/conf/otm/0002BLY18.bib},
  owner     = {koppor11},
}
```

Thus, I have the DOI `10.1007/978-3-030-02671-4\_7`

When activating "Citation Relations", I get

```
Illegal character in path at index 76: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1007/978-3-030-02671-4\_7/references?fields=title,authors,year,citationCount,referenceCount&limit=1000
Error while fetching citing Articles
java.lang.IllegalArgumentException: Illegal character in path at index 76: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1007/978-3-030-02671-4\_7/citations?fields=title,authors,year,citationCount,referenceCount&limit=1000
```

I think, this needs to be fixed at the DOI parsing logic (or at semantic scholar?)

---

This issue is more about code reading and code understanding. The fix itself is probably 3 lines of code and 10 lines of test case.

### PR DESCRIPTION
**Pull request by AbdAlRahmanGad**
Fixes #10985 

Some of the DOI links are not working because it has some special characters in it. 
For example ```10.1007/978-3-030-02671-4\_7``` it has an extra backslash '\\'.
I tried to fix the general problem instead of just the backslashes so I tried to eliminate all [unsafe character](https://www.ietf.org/rfc/rfc1738.txt#:~:text=These%20characters%20are%20%22%7B%22%2C,be%20encoded%20within%20a%20URL.)

In the code I added them to the CHARS_TO_REMOVE regex variable. 
as for '^' I handled it alone because the [formatter](https://github.com/JabRef/jabref/blob/f5efb349da7932c4149b2f9992533ccb1340d8e6/src/main/java/org/jabref/model/entry/identifier/DOI.java#L170) is replacing any ```^ + number``` with the superscript of the the number 
for example: 10^34 -> 10<sup>3</sup>4

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [X] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/model/entry/identifier/DOI.java [hunk 1]
```diff
@@ -167,6 +170,7 @@ public static Optional<DOI> parse(String doi) {
             LatexToUnicodeFormatter formatter = new LatexToUnicodeFormatter();
             String cleanedDOI = doi;
             cleanedDOI = URLDecoder.decode(cleanedDOI, StandardCharsets.UTF_8);
+            cleanedDOI = cleanedDOI.replaceAll("\\^", "");
```
Comment (koppor) [inline src/main/java/org/jabref/model/entry/identifier/DOI.java:173]: Please add a comment:

    // needs to be handled before LatexToUnicode, because otherwise `^` will be treated as conversion superscript

**Review by koppor — CHANGES_REQUESTED** [review]
Thank you. 

Please add a code comment (based on your PR description)

**Review by Siedlerchr — APPROVED** [review]
