### PR TITLE
Fixes #2571 and another unhandled exception

### LINKED ISSUE #2571: Automatic Bug Report-20170220153505
JabRef 4.0.0-dev--snapshot--2017-02-18--master--e36a99e92
Windows 7 6.1 amd64 
Java 1.8.0_102

<details>
<summary>Detail information:</summary>

```
Migrating old preferences.
Opening: G:\abcd\asdfs\xx.bib
runCommand error: Braces don't match.
java.lang.IllegalArgumentException: Braces don't match.
	at org.jabref.logic.bibtex.LatexFieldFormatter.checkBraces(LatexFieldFormatter.java:277)
	at org.jabref.logic.bibtex.LatexFieldFormatter.formatWithoutResolvingStrings(LatexFieldFormatter.java:170)
	at org.jabref.logic.bibtex.LatexFieldFormatter.format(LatexFieldFormatter.java:80)
	at org.jabref.logic.bibtex.BibEntryWriter.writeField(BibEntryWriter.java:152)
	at org.jabref.logic.bibtex.BibEntryWriter.writeRequiredFieldsFirstRemainingFieldsSecond(BibEntryWriter.java:124)
	at org.jabref.logic.bibtex.BibEntryWriter.write(BibEntryWriter.java:53)
	at org.jabref.logic.exporter.BibtexDatabaseWriter.writeEntry(BibtexDatabaseWriter.java:168)
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:198)
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:150)
	at org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:189)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)

```

</details>

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fix two unhandled exceptions:
- StringIndexOutOfBoundsException reported in the [forum](http://discourse.jabref.org/t/jabref-not-opening/476/3), easy fix by https://github.com/JabRef/jabref/compare/fixExcept?expand=1#diff-224c7e1325d710cbdcb0995525549d30R1492
- IllegalArgumentException #2571 Reason was that the writing code threw a IllegalArgumentException when the field content contains unbalanced braces (i.e. `title = {some text containing { }`). However, IllegalArgumentException is a runtime exception and so it was easy to miss that one should catch this exception properly. Fixed by introducing the checked exception InvalidFieldValueException. 
In the longer term, we should probably replace this check completely by the integrity checker.

Rest is a bit of (automatic) code reformat that my IntelliJ now performs for some reason on every commit...

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java [hunk 1]
```diff
@@ -102,9 +102,8 @@ protected void writeString(BibtexString bibtexString, boolean isFirstString, int
                                     .format(bibtexString.getContent(),
                             LatexFieldFormatter.BIBTEX_STRING);
                     getWriter().write(formatted);
-                } catch (IllegalArgumentException ex) {
-                    throw new IllegalArgumentException(
-                            "The # character is not allowed in BibTeX strings unless escaped as in '\\#'.\n" + "Before saving, please edit any strings containing the # character.");
```
Comment (lenhard) [inline src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java]: You are losing the localization message in this replacement.

File: src/main/java/org/jabref/logic/bibtex/LatexFieldFormatter.java [hunk 2]
```diff
@@ -47,16 +42,40 @@ public static LatexFieldFormatter buildIgnoreHashes(LatexFieldFormatterPreferenc
...
+        while ((current = text.indexOf('{', current + 1)) != -1) {
+            left.add(current);
+        }
+        while ((current = text.indexOf('}', current + 1)) != -1) {
+            right.add(current);
+        }
+
+        // Then we throw an exception if the error criteria are met.
+        if (!right.isEmpty() && left.isEmpty()) {
+            throw new InvalidFieldValueException("'}' character ends string prematurely.");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/bibtex/LatexFieldFormatter.java]: As this gets shown to the user (or at least I remember having seen such message when I left the field). wouldn't it be better to describe the message a bit more simpler?

Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/bibtex/LatexFieldFormatter.java]: Done

File: src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java (hunk 1 above)
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/exporter/BibtexDatabaseWriter.java]: The `InvalidFieldValueException` actually contained all the necessary information. Moreover, the text was also partly wrong (since the exception could also occur due to a problem with brackets)

**Comment by tobiasdiez** [comment]
I considered to remove the new exception but in the end decided to keep it. As I outlined above, these checks should be done as integration checks and don't throw an exception. In order to locate these bad checks, I left the exception but marked it as deprecated.
