### PR TITLE
fix loading and storing of XMP Field Exclusions

### LINKED ISSUE #4072: Cannot add exclusions into `XMP-metadata`'s `XMP export privacy settings`
I guess we should
1 fix the exclusions mechanism
2 insert 'file' into default exclusions and enable it by default
3 stop storing files paths in bibtex

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #4072 

@koppor  I am not that into the XMP stuff, are those "fields" I can add there bibtexfields which I can exclude from the export? 
Then it would make sense to have a combobox analogous to the Cleanup panel with all fields

Edit// Decided to add the combobox with all fields

grafik

----

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [x] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I am going to merge this now if no further comments are coming ;)

File: src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java [hunk 1]
```diff
@@ -68,34 +72,22 @@ public XmpPrefsTab(JabRefPreferences prefs) {
...
+                fields.add(tableRow);
             }
         });
         Button delete = new Button("Delete");
-        delete.setPrefSize(80, 20);
-        delete.setOnAction(e-> {
-            if (tableView.getFocusModel() != null && tableView.getFocusModel().getFocusedIndex() != -1) {
-                tableChanged = true;
+        delete.setOnAction(e -> {
+            if ((tableView.getFocusModel() != null) && (tableView.getFocusModel().getFocusedIndex() != -1)) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java]: Why do you use the focus and not selected item ala `tableView.getSelectionModel().getSelectedItem()` ?

File: src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java [hunk 2]
```diff
@@ -107,35 +99,20 @@ public XmpPrefsTab(JabRefPreferences prefs) {
...
      * Load settings from the preferences and initialize the table.
      */
     @Override
     public void setValues() {
-        tableRows.clear();
-        tableRows.addAll(data);
-        privacyFilterCheckBox.setSelected(JabRefPreferences.getInstance().getBoolean(
-                JabRefPreferences.USE_XMP_PRIVACY_FILTER));
+        List<XMPPrivacyFilter> xmpExclusions = prefs.getStringList(JabRefPreferences.XMP_PRIVACY_FILTERS).stream().map(XMPPrivacyFilter::new).collect(Collectors.toList());
+        fields.clear();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java]: I'm not sure, but I thought there is a `setAll` method (instead of clear + addAll)

File: src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java [hunk 3]
```diff
@@ -174,4 +138,30 @@ public boolean validateSettings() {
...
+
+        public void setField(String field) {
+            this.field.set(field);
+        }
+
+        public String getField() {
+            return field.get();
+        }
+
+        public StringProperty fieldName() {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java]: should be `field()`

File: src/test/java/org/jabref/logic/exporter/XmpExporterTest.java [hunk 4]
```diff
@@ -55,10 +57,23 @@ public void exportSingleEntry(@TempDirectory.TempDir Path testFolder) throws Exc
         entry.setField("author", "Alan Turing");
 
         exporter.export(databaseContext, file, encoding, Collections.singletonList(entry));
-
-        List<String> lines = Files.readAllLines(file);
-        assertEquals(15, lines.size());
-        assertEquals("<rdf:li>Alan Turing</rdf:li>", lines.get(4).trim());
+        String actual = Files.readAllLines(file).stream().collect(Collectors.joining("\n")); //we are using \n to join, so we need it in the expected string as well, \n would fail
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/logic/exporter/XmpExporterTest.java]: I don't understand the comment, especially the `\n would fail` part. You can also simply compare the file contents as arrays, then there is no ambiguity concerning line endings.

File: src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java [hunk 5]
```diff
@@ -68,34 +72,22 @@ public XmpPrefsTab(JabRefPreferences prefs) {
...
+                XMPPrivacyFilter tableRow = new XMPPrivacyFilter(bibtexFields.getSelectionModel().getSelectedItem());
+                fields.add(tableRow);
             }
         });
         Button delete = new Button("Delete");
-        delete.setPrefSize(80, 20);
-        delete.setOnAction(e-> {
-            if (tableView.getFocusModel() != null && tableView.getFocusModel().getFocusedIndex() != -1) {
-                tableChanged = true;
+        delete.setOnAction(e -> {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java]: The delete button should be shown in the table per row on hover (e.g. similar to the buttons in the maintable and I guess manage journal abbreviations and/or key bindings)

File: src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java [hunk 6]
```diff
@@ -174,4 +138,30 @@ public boolean validateSettings() {
     public String getTabName() {
         return Localization.lang("XMP-metadata");
     }
+
+    private class XMPPrivacyFilter {
+
+        private final SimpleStringProperty field;
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java]: is it really necessary to make this a property instead of a simple get/set java prop? Moreover, I like the idea of creating a new class for this but would go one step further: use it everywhere (i.e. the properties class should set/get a list of privacy filter).

File: src/test/java/org/jabref/logic/exporter/XmpExporterTest.java (hunk 4 above)
Comment (Siedlerchr) [reply src/test/java/org/jabref/logic/exporter/XmpExporterTest.java]: The comment should have been `\r\n` would fail.
I prefer this equals variant because at least eclipse shows the differences highlighted

File: src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java (hunk 6 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/preferences/XmpPrefsTab.java]: I understand your idea but it is necessary as the cellValueFactory expects an Observable.
Another idea would be to have a converter/PropertyValueFactory. 
 lastNameCol.setCellValueFactory(new PropertyValueFactory<Person,String>("lastName"));

**Comment by Siedlerchr** [comment]
grafik
