### PR TITLE
fixes Tooltips are displayed for empty elements

### LINKED ISSUE #11681: Tooltips are displayed for empty elements
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Debian Linux, i3 wm, JabRef 5.16

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open library, select a group that has so many entries they do not fill the whole window (there must be some empty rows seen)
2. Place the mouse cursor over any of the elements in the empty row
3. A tooltip will appear

jabref

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by mkumar09**
Closes #11681 

In about one to three sentences, describe the changes you have made: what, where, why, ...

I have made the change in ValueTableCellFactory.java in setOnMouseEntered event handler.
The issue demonstrated was that tooltips where visible on hovering beyond the entries list even in empty rows.
I have put a check that if the index of the current row is beyond the size of the items then tooltip is not required.

### Steps to test

Issue_fix_11681

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java [hunk 1]
```diff
@@ -141,7 +141,7 @@ protected void updateItem(T item, boolean empty) {
                     }
 
                     setOnMouseEntered(event -> {
-                        if (tooltip != null) {
+                        if (tooltip != null && getTableRow().getIndex() < getTableView().getItems().size()) {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java]: Lets make this a bit more readable
```suggestion
                        int rowIndex = getTableRow().getIndex();
                        int totalItems = getTableView().getItems().size();
                        if (tooltip != null && rowIndex < totalItems) {
```

Comment (koppor) [reply jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java]: ...and a Java comment why this is necessary (if possible). Meaning: Seeing only this change, I dont get why tooltip is not null for an "invalid" row?

Comment (mkumar09) [reply jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java]: > Lets make this a bit more readable

addressed

Comment (mkumar09) [reply jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java]: > ...and a Java comment why this is necessary (if possible). Meaning: Seeing only this change, I dont get why tooltip is not null for an "invalid" row?

addressed

**Comment by calixtus** [comment]
grafik

**Comment by calixtus** [comment]
Did not work

**Comment by mkumar09** [comment]
> Did not work

I have pushed a fresh revision, Please check the latest binaries. It will work now.

**Review by subhramit — APPROVED** [review]

File: jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java [hunk 2]
```diff
@@ -141,7 +141,11 @@ protected void updateItem(T item, boolean empty) {
                     }
 
                     setOnMouseEntered(event -> {
-                        if (tooltip != null) {
+                        int rowIndex = getTableRow().getIndex();
+                        int totalItems = getTableView().getItems().size();
+                    // The condition ensures that cell is reset to a clean state when it is empty, uninitialized, or detached from a valid table row,
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java]: The indent of the comment is off. Why?

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
@mkumar09 Thank you for working on this. I replaced the Java comment by something more code-related. Now, it is good to go.

**Comment by calixtus** [comment]
Did somebody test it before merging?

**Comment by subhramit** [comment]
> Did somebody test it before merging?

yes

**Comment by koppor** [comment]
> Did somebody test it before merging?

Yes 😅

Even adding and removing entries in the main table.
