### PR TITLE
Fixed missing trigger for linked file operations

### LINKED ISSUE #7525: File renaming functions are greyed out (deactivated) for unclear reasons
JabRef version 5.2, 5.3 and 100.0.0 (commit 0dd4de752) on Linuxmint-20.1 and LinuxMint-19.3.

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

File rename commands are greyed out and not active, and the reason is not clear for the user. Moreover, these commands are inactivated at the moments when they are badly needed!

1. Start the relevant version of the JabRef; 
2. Load some .bib library; the file used for testing is in the .zip below:
[new.zip](https://github.com/JabRef/jabref/files/6134973/new.zip)
3. Populate directory "new/" with some OA PDFs having the same names as in the .bib file;
4. For testing, the following settings were used:
    -- Autolink files: use regular expression `**/[year]_[auth].*\\.[extension]`;
    -- File format pattern: `[year]_[auth]_[firstpage]`;
    -- File directory pattern: `by-author/[authIni1]/[auth]`;
5. Right-click on the file linkage box in the entry editing window;
6. For version 5.2, both "Move to file directory..." are always disabled, but "Rename to a defined pattern" is active and works: 
Screenshot from 2021-03-13 15-37-22
7. In 5.3 and 100.x (the current master tip), the "Rename to a defined..." and "Move to file directory and rename..." are enabled at the beginning, but are disable after the first rename, with now means to reenable them except shutting down the whole JabRef and starting it again. Changing the BibTeX entry (e.g. adding page numbers, that potentially change the "defined name pattern") does not re-enable these fields:
Screenshot from 2021-03-13 15-48-56

Either the commands should be re-enabled after edit, or not disabled at all; otherwise the renaming feature (which I use a lot!) becomes next to unusable...

### PR DESCRIPTION
**Pull request by calixtus**
Fixes #7525

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
I was also looking at this, and got confused why there is a binding to the executable state in the first place. The context menu is created when the user right clicks the file, and then the state doesn't change until the user chooses a an option from the menu. Moreover, the linked file view model should be recreated as soon as the content of the file field changes - so no binding needed since the linkedfile is constant for all practical purposes. What I am missing?

**Comment by calixtus** [comment]
I have no idea, but it works... 😅 

But seriously: The ContextAction command was introduced in the first place to prepare this for a later to be added undo functionality. I tried it also with `BindingsHelper.constantOf()` and directly with `setExecutable()` but this did not show a consistent behaviour, my guess is that something is still cached.

In this state I think it works, but some more investigation surely wouldn't hurt.

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java [hunk 1]
```diff
@@ -281,19 +285,19 @@ public ContextAction(StandardActions command, LinkedFileViewModel linkedFile, Pr
                                 () -> !linkedFile.getFile().isOnlineLink()
                                         && linkedFile.getFile().findIn(databaseContext, preferencesService.getFilePreferences()).isPresent()
                                         && !linkedFile.isGeneratedNameSameAsOriginal(),
-                                linkedFile.getFile().linkProperty());
+                                linkedFile.getFile().linkProperty(), stateManager.getSelectedEntries().get(0).getFieldsObservable());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java:288]: The editor is notified in 
https://github.com/JabRef/jabref/blob/d190268813e7e65b09a744158fcfa65371f5a28d/src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java#L210
about the entry to show. So that's probably a better way to get the entry instead of pushing down the state manager.

**Comment by tobiasdiez** [comment]
Yeah, I'm also afraid that it is actually a cache error and it still shows the context menu for the previous version of the linked file. Hopefully that doesn't lead to more problems, e.g. when the action is performed with respect to the previous version instead of the current one.

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java (hunk 1 above)
Comment (calixtus) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java:288]: bindToEntry does directly bind the linkedFileViewModel right now, but I'll see what I can do.

**Review by tobiasdiez — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
