### PR TITLE
fix groups drag and drop

### LINKED ISSUE #4414: Moving entries bewtween groups doesn't work
Hello
I'm using JabRef 4.3.1 on Windows 10 X64.
I'm trying to reorder my entries on groups.
If I select several entries and using the rightmouse menu choose "Move to group" only the first entry is moved.
If I try to drag it instead of move it it copies it (and duplicate the entries)

### PR DESCRIPTION
**Pull request by Ali96kz**
Fix a bug with drag and drop groups.
Steps to reproduce:
1) select more than groups
2) Move it to another group via drag and drop
Groups not moved into another group if you use drag and drop

### CODE REVIEW

File: src/main/java/org/jabref/gui/groups/GroupTreeView.java [hunk 1]
```diff
@@ -195,20 +195,21 @@ public void initialize() {
...
-                    // Put the group node as content
-                    ClipboardContent content = new ClipboardContent();
-                    content.put(DragAndDropDataFormats.GROUP, selectedItem.getValue().getPath());
-                    dragboard.setContent(content);
-
-                    event.consume();
+                List<String> groupsToMove = new ArrayList<>();
+                for (TreeItem<GroupNodeViewModel> selectedItem : treeTable.getSelectionModel().getSelectedItems()) {
+                    if ((selectedItem != null) && (selectedItem.getValue() != null)) {
+                        // Display the group when dragging
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/groups/GroupTreeView.java]: This comment should come before the `setDragView` call.
