### PR TITLE
Fix unmodifable Set Exception in generating preview

### LINKED ISSUE #9947: Exception when generating preview for unknown entry types (Other)
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

13.1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.  add the following entry
 ```
 @Other{Keeler1998,
  author       = {Keeler, James},
  file         = {:Keeler NMR Lectures.pdf:PDF},
  howpublished = {Online PDF of Lectures},
  note         = {HC},
  owner        = {Frey},
  timestamp    = {2009.11.23},
  title        = {Introduction to NMR},
  url          = {http://www-keeler.ch.cam.ac.uk/lectures/},
  year         = {1998},
}

```
2. Switch back and forth to generate the preview
3. See exception in log and no preview rendered:
```

ROR: Error while generating citation style: java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1077)
	at org.jabref/org.jabref.logic.citationstyle.JabRefItemDataProvider.bibEntryToCSLItemData(JabRefItemDataProvider.java:151)
	at org.jabref/org.jabref.logic.citationstyle.JabRefItemDataProvider.lambda$11(JabRefItemDataProvider.java:191)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.jabref/org.jabref.logic.citationstyle.JabRefItemDataProvider.retrieveItem(JabRefItemDataProvider.java:192)
	at citeproc.java@3.0.0-beta.2/de.undercouch.citeproc.CSL.registerItems(CSL.java:570)
	at citeproc.java@3.0.0-beta.2/de.undercouch.citeproc.CSL.registerCitationItems(CSL.java:720)
	at citeproc.java@3.0.0-beta.2/de.undercouch.citeproc.CSL.registerCitationItems(CSL.java:703)
	at org.jabref/org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(CSLAdapter.java:48)
	at org.jabref/org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(CitationStyleGenerator.java:62)
	at org.jabref/org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(CitationStyleGenerator.java:52)
	at org.jabref/org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(CitationStylePreviewLayout.java:19)
	at org.jabref/org.jabref.gui.preview.PreviewViewer.lambda$5(PreviewViewer.java:255)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:60)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:161)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589) 


```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Add hint in javadoc

Fixes #9947
Fixes https://github.com/JabRef/jabref-issue-melting-pot/issues/183

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

File: src/main/java/org/jabref/model/entry/BibEntry.java [hunk 1]
```diff
@@ -489,7 +489,7 @@ private Optional<String> genericGetFieldOrAlias(Field field, BiFunction<BibEntry
             return date.map(Date::getNormalized);
         }
 
-        if (StandardField.YEAR == field || StandardField.MONTH == field || StandardField.DAY == field) {
+        if ((StandardField.YEAR == field) || (StandardField.MONTH == field) || (StandardField.DAY == field)) {
```
Comment (calixtus) [inline src/main/java/org/jabref/model/entry/BibEntry.java:492]: Honestly, i find those additional brackets more annoying instead of helping.

Comment (Siedlerchr) [reply src/main/java/org/jabref/model/entry/BibEntry.java:492]: feel free to remove them.
