### PR TITLE
Fix bad web search error messages

### LINKED ISSUE #1542: Bad web search error messages
The web search gives inconsistent, wrong or no feedback, when trying to fetch without being connected to the internet. 

Steps to reproduce:

1. Disconnect from the internet
2. Enter something into the web search text field
3. Press fetch 
4. Enjoy flickering windows and exceptions depending on the selected search portal

The error messages should be consistent and tell the user what went wrong.

### PR DESCRIPTION
**Pull request by bartsch-dev**
Fixes #1542

I rewrote the error messages when the fetchers fail (or added them).

### CODE REVIEW

File: src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java [hunk 1]
```diff
@@ -130,83 +121,91 @@ public String getTitle() {
...
+                            Localization.lang("Search %0", getTitle()), JOptionPane.INFORMATION_MESSAGE);
+                    return false;
+                }
 
-                    if (strCount == null) {
-                        frameOP.setStatus(Localization.lang("%0 import canceled", "Medline"));
-                        return false;
+                int numberToFetch = result.count;
+                if (numberToFetch > MedlineFetcher.PACING) {
+                    while (true) {
```
Comment (boceckts) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java]: Please use a variable and just set it to `false` instead of using `break`.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java [hunk 2]
```diff
@@ -284,9 +264,11 @@ public boolean processQuery(String query, ImportInspector dialog, OutputPrinter
             }
 
             return true;
-        } catch (Exception e) {
-            status.setStatus(Localization.lang("Error while fetching from %0", "OAI2"));
-            LOGGER.error("Error while fetching from OAI2", e);
+        } catch (IOException | SAXException | InterruptedException e) {
+            LOGGER.error("Error while fetching from " + getTitle(), e);
```
Comment (boceckts) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java]: For me this this too much generalization, use the same error message for all `IOException`s and maybe `InterruptedException`s for the fetchers, but I think the error message doesn't make sense when an `SAXException` occurs!?

File: CHANGELOG.md [hunk 3]
```diff
@@ -43,6 +43,7 @@ We refer to [GitHub issues](https://github.com/JabRef/jabref/issues) by using `#
 - [#2012](https://github.com/JabRef/jabref/issues/2012) Implemented integrity check for `month` field: Should be an integer or normalized (BibLaTeX), Should be normalized (BibTeX)
 
 ### Fixed
+- Improved error messages when using fetcher
```
Comment (bartsch-dev) [inline CHANGELOG.md]: That's up for debate. Before the error messages didn't work as intended (or didn't work at all).

File: src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java (hunk 2 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java]: Does it have any additional value for the user if they know that is was a SAX exception?
They can't do anything about it.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java (hunk 1 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java]: done

File: src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java [hunk 4]
```diff
@@ -82,14 +83,22 @@ public boolean processQueryGetPreview(String query, FetcherPreviewDialog preview
...
+                status.showMessage(Localization.lang("No entries found for the search string '%0'", query),
+                        Localization.lang("Search %0", getTitle()), JOptionPane.INFORMATION_MESSAGE);
+                return false;
+            }
+
             for (Map.Entry<String, JLabel> linkEntry : citations.entrySet()) {
                 preview.addEntry(linkEntry.getKey(), linkEntry.getValue());
             }
-
             return true;
```
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java]: done

File: src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java [hunk 5]
```diff
@@ -82,14 +83,22 @@ public boolean processQueryGetPreview(String query, FetcherPreviewDialog preview
                 hasRunConfig = true;
             }
             Map<String, JLabel> citations = getCitations(query);
+            if (citations.size() == 0) {
```
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java]: done

File: src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java [hunk 6]
```diff
@@ -157,19 +155,13 @@ public boolean processQueryGetPreview(String query, FetcherPreviewDialog preview
...
-            LOGGER.warn("Problem with ACM fetcher URL", e);
-        } catch (ConnectException e) {
-            status.showMessage(Localization.lang("Could not connect to %0", getTitle()),
-                    Localization.lang("Search %0", getTitle()), JOptionPane.ERROR_MESSAGE);
-            LOGGER.warn("Problem with ACM connection", e);
         } catch (IOException e) {
-            status.showMessage(e.getMessage(),
+            LOGGER.error("Error while fetching from " + getTitle(), e);
+            status.showMessage(Localization.lang("Error while fetching from %0", getTitle()) +"\n"+
+                            Localization.lang("Please try again later and/or check your network connection."),
```
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java]: I exported them into the two main Dialog classes.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java (hunk 2 above)
Comment (boceckts) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java]: In my opinion yes, a `SAXException` won't be resolved by retrying or checking the internet connection.

File: src/main/java/net/sf/jabref/gui/importer/FetcherPreviewDialog.java [hunk 7]
```diff
@@ -302,4 +303,10 @@ public void showMessage(String message, String title, int msgType) {
     public void showMessage(String message) {
         JOptionPane.showMessageDialog(this, message);
     }
+
+    public void showErrorMessage(EntryFetcher fetcher) {
```
Comment (boceckts) [inline src/main/java/net/sf/jabref/gui/importer/FetcherPreviewDialog.java]: I change the interface to `public void showFetchingErrorMessage(String fetcherName)` since you don't need the whole fetcher object and the name is more specific for the fetchers. When creating public utility methods it's also good to have a javadoc comment describing it's functionality as it should also be used by others in the future. Other than that I'm fine with your changes 👍

Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/FetcherPreviewDialog.java]: done

File: src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java (hunk 2 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/OAI2Fetcher.java]: Now the `SAXException` will be shown to the user.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/IdBasedEntryFetcher.java [hunk 8]
```diff
@@ -34,8 +35,8 @@ public boolean processQuery(String query, ImportInspector inspector, OutputPrint
             match.ifPresent(inspector::addEntry);
             return match.isPresent();
         } catch (FetcherException e) {
-            status.setStatus(e.getLocalizedMessage());
-            LOGGER.error("Error while fetching from" + fetcher.getName(), e);
+            LOGGER.error("Error while fetching from " + getTitle(), e);
+            ((ImportInspectionDialog)inspector).showErrorMessage(this.getTitle());
```
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/IdBasedEntryFetcher.java]: You completely ignore the exception details when you call `showErrorMessage`, thus the user gets just a standard message although the FetcherException contains all the necessary details about what went wrong (`e.getLocalizedMessage`)

File: src/main/java/net/sf/jabref/gui/importer/fetcher/SearchBasedEntryFetcher.java [hunk 9]
```diff
@@ -37,8 +38,8 @@ public boolean processQuery(String query, ImportInspector inspector, OutputPrint
             matches.forEach(inspector::addEntry);
             return !matches.isEmpty();
         } catch (FetcherException e) {
-            status.setStatus(e.getLocalizedMessage());
-            LOGGER.error("Error while fetching from" + fetcher.getName(), e);
+            LOGGER.error("Error while fetching from " + getTitle(), e);
+            ((ImportInspectionDialog)inspector).showErrorMessage(this.getTitle());
```
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/SearchBasedEntryFetcher.java]: Same as above: exception information is ignored

File: src/test/java/net/sf/jabref/gui/importer/fetcher/OAI2HandlerFetcherTest.java [hunk 10]
```diff
@@ -122,57 +126,80 @@ public void testFixKey() {
...
+                be = fetcher.importOai2Entry("math.RA/0612188");
+                Assert.assertNotNull(be);
+
+                Assert.assertEquals(Optional.of("math/0612188"), be.getField("eprint"));
+                Assert.assertEquals(Optional.of("On the classification and properties of noncommutative duplicates"),
+                        be.getField("title"));
+                Assert.assertEquals(Optional.of("Javier López Peña and Gabriel Navarro"), be.getField("author"));
+                Assert.assertEquals(Optional.of("2007"), be.getField("year"));
+            } catch (IOException | SAXException e) {
+                LOGGER.error("Test probably failed due internet problems");
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/gui/importer/fetcher/OAI2HandlerFetcherTest.java]: Please don't catch exceptions in tests.

Comment (bartsch-dev) [inline src/test/java/net/sf/jabref/gui/importer/fetcher/OAI2HandlerFetcherTest.java]: Moved them to the method signature.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/IdBasedEntryFetcher.java (hunk 8 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/IdBasedEntryFetcher.java]: I don't know how much additional value the end user has from : `java.net.UnknownHostException: doaj.org`, but I appended the localized message to the dialog nonetheless.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java [hunk 11]
```diff
@@ -157,19 +155,11 @@ public boolean processQueryGetPreview(String query, FetcherPreviewDialog preview
...
-                    Localization.lang("Search %0", getTitle()), JOptionPane.ERROR_MESSAGE);
-            LOGGER.warn("Problem with ACM connection", e);
         } catch (IOException e) {
-            status.showMessage(e.getMessage(),
-                    Localization.lang("Search %0", getTitle()), JOptionPane.ERROR_MESSAGE);
-            LOGGER.warn("Problem with ACM Portal", e);
+            LOGGER.error("Error while fetching from " + getTitle(), e);
+            preview.showErrorMessage(this.getTitle(), e.getLocalizedMessage());
+            return false;
         }
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java]: Why is the return false moved inside the catch?

File: src/main/java/net/sf/jabref/gui/importer/fetcher/DOAJFetcher.java [hunk 12]
```diff
@@ -43,31 +44,26 @@ public boolean processQuery(String query, ImportInspector inspector, OutputPrint
...
-                                .showInputDialog(
-                                        Localization.lang("References found") + ": " + hits + "  "
-                                                + Localization.lang("Number of references to fetch?"),
-                                        Integer.toString(hits));
+            int numberToFetch = jo.getInt("total");
+            if (numberToFetch > 0) {
+                if (numberToFetch > MAX_PER_PAGE) {
+                    boolean numberEntered = false;
+                    do {
+                        String strCount = JOptionPane.showInputDialog(Localization.lang("References found") +": " + numberToFetch + " " +
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/DOAJFetcher.java]: String.Format would look cleaner here, etc, use %1s, %2s for the arguments

File: src/main/java/net/sf/jabref/gui/importer/fetcher/INSPIREFetcher.java [hunk 13]
```diff
@@ -100,25 +100,18 @@ private String constructUrl(String key) {
...
-
-            try (INSPIREBibtexFilterReader reader = new INSPIREBibtexFilterReader(
-                    new InputStreamReader(inputStream, Charset.forName("UTF-8")))) {
+        HttpURLConnection conn = (HttpURLConnection) new URL(url).openConnection();
+        conn.setRequestProperty("User-Agent", "JabRef");
+        InputStream inputStream = conn.getInputStream();
 
-                ParserResult pr = BibtexParser.parse(reader, Globals.prefs.getImportFormatPreferences());
+        try (INSPIREBibtexFilterReader reader = new INSPIREBibtexFilterReader(
+                new InputStreamReader(inputStream, Charset.forName("UTF-8")))) {
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/INSPIREFetcher.java]: StandardCharsets.UTF-8

File: src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java [hunk 14]
```diff
@@ -130,109 +122,106 @@ public String getTitle() {
...
-
-        if (!query.isEmpty()) {
-            frameOP.setStatus(Localization.lang("Fetching Medline by term..."));
+    public boolean processQuery(String query, ImportInspector dialog, OutputPrinter status) {
+        try {
+            shouldContinue = true;
 
-            String searchTerm = toSearchTerm(query);
+            String cleanQuery = query.trim().replace(';', ',');
+            if (cleanQuery.matches("\\d+[,\\d+]*")) {
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java]: Could you please extract that to a Pattern, too?

File: src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java [hunk 15]
```diff
@@ -130,109 +122,106 @@ public String getTitle() {
...
-            }
 
-            for (int i = 0; i < numberToFetch; i += MedlineFetcher.PACING) {
-                if (!shouldContinue) {
-                    break;
+                int numberToFetch = result.count;
+                if (numberToFetch > MedlineFetcher.PACING) {
+                    boolean numberEntered = false;
+                    do {
+                        String strCount = JOptionPane.showInputDialog(Localization.lang("References found") + ": " + numberToFetch + " " +
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java]: Same as above, String.format

File: src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java [hunk 16]
```diff
@@ -130,109 +122,106 @@ public String getTitle() {
...
-                result = getIds(searchTerm, i, noToFetch);
+                    // get the ids from entrez
+                    result = getIds(searchTerm, i, noToFetch);
 
-                List<BibEntry> bibs = fetchMedline(result.ids, frameOP);
-                for (BibEntry entry : bibs) {
-                    iIDialog.addEntry(entry);
+                    List<BibEntry> bibs = fetchMedline(result.ids, status);
+                    for (BibEntry entry : bibs) {
+                        dialog.addEntry(entry);
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java]: I'm just curious, does the dialog object has a method which accepts a Collection/list of BibEntries?
(Not scope of this PR to add one, but would be nice to have such a method

File: src/main/java/net/sf/jabref/gui/importer/fetcher/SpringerFetcher.java [hunk 17]
```diff
@@ -47,16 +48,13 @@ public boolean processQuery(String query, ImportInspector inspector, OutputPrint
...
-                                .showInputDialog(
-                                        Localization.lang("References found") + ": " + hits + "  "
-                                                + Localization.lang("Number of references to fetch?"),
-                                        Integer.toString(hits));
+            int numberToFetch = jo.getJSONArray("result").getJSONObject(0).getInt("total");
+            if (numberToFetch > 0) {
+                if (numberToFetch > MAX_PER_PAGE) {
+                    boolean numberEntered = false;
+                    do {
+                        String strCount = JOptionPane.showInputDialog(Localization.lang("References found") +": "+ numberToFetch + " " +
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/SpringerFetcher.java]: same as earlier

File: src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java (hunk 11 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/ACMPortalFetcher.java]: I like to return immediately in general so I forget that branch.
If someone now breaks out of the try-catch (which shouldn't be done) he is forced to deal with it later down.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/DOAJFetcher.java (hunk 12 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/DOAJFetcher.java]: It would be best to bind the number to the translation, but then it has to be re-translated b/c the number isn't always at the same spot in every language.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java (hunk 16 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java]: No, it does not.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/INSPIREFetcher.java (hunk 13 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/INSPIREFetcher.java]: done

File: src/main/java/net/sf/jabref/gui/importer/fetcher/DOAJFetcher.java (hunk 12 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/DOAJFetcher.java]: In correspondence with @koppor I combined it to a single translation.
For the user it will change nothing.

File: src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java (hunk 15 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/MedlineFetcher.java]: see above

File: src/main/java/net/sf/jabref/gui/importer/fetcher/SpringerFetcher.java (hunk 17 above)
Comment (bartsch-dev) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/SpringerFetcher.java]: see above

**Comment by tobiasdiez** [comment]
@zellerdev currently rewrites the medline fetcher #2066.
Probably the strange error message automatically disappears when the medline fetcher is ported to the new interface.
Thus I think it is ok to merge this PR (and double check before merging #2066).

**Comment by matthiasgeiger** [comment]
Uhm... the change in `GeneralFetcher.java` causes a quite weird exception:

```
Exception in thread "JabRef CachedThreadPool" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.awt.Container.createHierarchyEvents(Container.java:1441)
	at java.awt.Container.createHierarchyEvents(Container.java:1441)
	at java.awt.Container.createHierarchyEvents(Container.java:1441)
	at java.awt.Container.createHierarchyEvents(Container.java:1441)
	at java.awt.Container.createHierarchyEvents(Container.java:1441)
	at java.awt.Dialog.conditionalShow(Dialog.java:953)
	at java.awt.Dialog.show(Dialog.java:1037)
	at java.awt.Component.show(Component.java:1673)
	at java.awt.Component.setVisible(Component.java:1625)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at net.sf.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$171(GeneralFetcher.java:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Occurs on (successful) searches with an internet connection in my branch for #2101 

Has anyone else this problem?

**Comment by matthiasgeiger** [comment]
... and there is another problem: 

The whole UI freezes after some consecutive searches, e.g., using the IEEE fetcher.

@bartsch-dev Can you investigate this issues?

**Comment by bartsch-dev** [comment]
I'll look into it tomorrow evening.

**Comment by matthiasgeiger** [comment]
To get the fetchers back working I just reverted your change in `GeneralFetcher.java` (see 6daa5b5)

Why have you changed it in your PR?

**Comment by bartsch-dev** [comment]
To not show the fetcher dialog if the fetching was not successful.
Now fetcher dialog opens, the error message is on top of that and closes when the error message gets closed.
