### PR TITLE
Replace NormalizeNamesFormatter by AuthorList and so fix #318

### LINKED ISSUE #318: Normalize to Bibtex name format
Rightclick formatter in authors field goes wrong.

Minimal example:
```
Stefan Kolb and J{\"o}rg Lenhard and Guido Wirtz
```
turns out to be
```
Kolb, Stefan and J{\"o}rg Lenhard and Wirtz, Guido
````

but should be

``` 
Kolb, Stefan and Lenhard, J{\"o}rg and Wirtz, Guido
```

- [x] `NameListNormalizer` should be transformed to a Formatter on that occasion.

On another note: is this really THE BibTex name format? This should help with multiple firstnames?!

### PR DESCRIPTION
**Pull request by tobiasdiez**
- Fixes #318 (and refs #950)
- Removes comma as delimiter of author names (in NormalizenamesFormatter).
 The problem is that comma separated authors cannot be distingued from one author in BibTeX format.
 For example `Name, della, first` could be three names separated by commas or if interpreted as valid BibTeX string it is one author with lastname=name, jrpart=della, firstname=first.
- Add colon as delimiter of author names (in AuthorListParser).

Thanks at all, but especially @oscargus, for creating many tests. Made implementing this PR way easier! 

--

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)

### CODE REVIEW

File: src/main/java/net/sf/jabref/model/entry/Author.java [hunk 1]
```diff
@@ -38,20 +38,100 @@
...
     public Author(String first, String firstabbr, String von, String last, String jr) {
-        firstPart = removeStartAndEndBraces(first);
+        firstPart = addDotIfAbbreviation(removeStartAndEndBraces(first));
         firstAbbr = removeStartAndEndBraces(firstabbr);
         vonPart = removeStartAndEndBraces(von);
         lastPart = removeStartAndEndBraces(last);
         jrPart = removeStartAndEndBraces(jr);
     }
 
+    public static String addDotIfAbbreviation(String name) {
```
Comment (oscargus) [inline src/main/java/net/sf/jabref/model/entry/Author.java]: How does this method compare to expandAll (?) in StringUtil? Could that be replaced by this (later) as this seems more competent?

Comment (oscargus) [inline src/main/java/net/sf/jabref/model/entry/Author.java]: Ahh, I know the answer for that... Somehow I didn't see StringUtil in the diff the first time. :-)

File: src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java [hunk 2]
```diff
@@ -313,6 +312,9 @@ public void testExpandAuthorInitialsDoNotAddDot() {
         assertEquals("Moore, O.", StringUtil.expandAuthorInitials("Moore, O."));
         assertEquals("Moore, A. O.", StringUtil.expandAuthorInitials("Moore, A. O."));
         assertEquals("Moore, A.-O.", StringUtil.expandAuthorInitials("Moore, A.-O."));
+        assertEquals("MEmre", StringUtil.expandAuthorInitials("MEmre"));
+        assertEquals("{\\'{E}}douard", StringUtil.expandAuthorInitials("{\\'{E}}douard"));
```
Comment (oscargus) [inline src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java]: Nice additional tests! Will "{\\'{E}}" work? As in a dot is added.

File: src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib6.bib [hunk 3]
```diff
@@ -1,6 +1,6 @@
 @Misc{,
   Title                    = {Correct positioning of percutaneous iliosacral screws with computer-navigated versus fluoroscopically guided surgery in traumatic pelvic ring fractures},
-  Author                   = {Verbeek, Jan MD and Hermans, Erik MD and van Vugt, Arie MD, PhD and Frolke, Jan Paul MD, PhD},
```
Comment (oscargus) [inline src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib6.bib]: Hmm, I'm wondering if it is possible to skip this expansion... Probably we will have to decide on either hardcoding MD (medical doctor) and disappoint people with Marie David as middle names or just live with it.

**Comment by oscargus** [comment]
Looks very nice! :+1:

The MD thing is a bit challenging and either way we will do it wrong for one of the cases. If I were in medicine I would probably prefer not to expand MD (especially).

File: src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java (hunk 2 above)
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java]: No it will not. The dot will be added only if the uppercase letter is followed by a whitespace, dash or tilde. I think it would be to hard to detect all the latex stuff.

File: src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib6.bib (hunk 3 above)
Comment (tobiasdiez) [inline src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib6.bib]: Yeah... you are right it is a bit annoying. But I think the majority of author names does not contain the degree (MD, PHD, ...) of the author or set it up properly as the Jr part.

File: src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java (hunk 2 above)
Comment (oscargus) [inline src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java]: Makes sense. It might be possible to run RemoveLatexFormatter  (or whatever it is called) and do the detection on the stripped string but probably not worth it for such a corner case.

Comment (oscargus) [inline src/test/java/net/sf/jabref/logic/util/strings/StringUtilTest.java]: It might (eventually) make sense to replace expandAuthorInitials with the name formatter. Even though they doesn't do exactly the same thing, if I recall correctly expandAuthorInitials is used in two importers only and it should be OK to possible change the complete formatting of those author fields.

File: src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib6.bib (hunk 3 above)
Comment (oscargus) [inline src/test/resources/net/sf/jabref/importer/fileformat/OvidImporterTestBib6.bib]: Not obvious why they need to brag about their titles in the first place. :-) (And I know that some of you might end up to write Herr Prof. Dr. Ing. Hab. Prof. Dr.)

**Comment by simonharrer** [comment]
LGTM
