### PR TITLE
Fix threading cleanup in performSearch

### LINKED ISSUE #1018: Importing to the correct mode when searching (BibTeX vs biblatex)
Most (all?) of the fetchers will now produce a BibTeX entry. When importing to a BibLaTeX database, this causes some issues, see e.g. #1015. It might make sense to add some mechanism to the search interface such that the correct format is returned. For example, this can be achieved by "search formatters", which will also remove some of the need of explicit cleanup code in the fetchers as well as some of the preference settings.

### LINKED ISSUE #7606: Seaching for bibliographies and importing them triggers uncaught java.lang.IndexOutOfBoundsException
JabRef version 5.2, 5.3, commit badffe9ae in 'master' on LinuxMint-19.3, Linuxmint-20.1  -->

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When search for literature (say in ArXiv) and the importing entries, an uncaught exception is triggered. This behaviour is not always present, but can be reproduced after searching and importing several times in the same session.

1. Start a JabRef session without any databases;
2. Create a new database;
3. Save it under some name (e.g. 'test.bib'); this is essential, otherwise different exception is triggered;
4. Open Groups interface (not clear if this is important, but I had it open during tests; also they are open in screens at #7343)
5. Open Web search interfacel
6. Select arXive (possibly other search source would give the same behaviour);
7. Search for "Minkowski space", receive 20 hits;
8. select them all and import;
9. If the exceeption is not trigegred immediately, repeat the steps 7-8  with other search terms, e.g. "Kilogram definition", "Teaching Temperature", etc.
10. At some stage an exception window pops up:
Screenshot from 2021-04-04 10-04-44

The bug might be related to #7343, but the exception is different (OutOfBounds instead NullPointer), and is not in the Dark mode.

Sometimes there are multiple exceptions happening opening multiple pop-up windows. The fate of JabRef after exception is different – sometimes it freezes and the process needs to be killed, sometimes one can still save the database after closing the exception popup. If JabRef can be closed via it interface, it reports numerous dowload threads still running in the bacground.

More screenshots with sporadic exceptions after the sequence of actions listed here are available in my server:
http://saulius-grazulis.lt/~saulius/JabRef/screenshots/

The log message, copied and pasted from the window, reads:

<details>
  <summary>Log File</summary>
  
  ```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at javafx.base/javafx.collections.ListChangeBuilder.insertUpdate(ListChangeBuilder.java:84)
	at javafx.base/javafx.collections.ListChangeBuilder.nextUpdate(ListChangeBuilder.java:467)
	at javafx.base/javafx.collections.ObservableListBase.nextUpdate(ObservableListBase.java:109)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.access$100(ObservableListWrapper.java:45)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper$1$1.invalidated(ObservableListWrapper.java:72)
	at javafx.base/com.sun.javafx.collections.MapListenerHelper$SingleInvalidation.fireValueChangedEvent(MapListenerHelper.java:125)
	at javafx.base/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.base/com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at javafx.base/com.sun.javafx.collections.ObservableMapWrapper.remove(ObservableMapWrapper.java:185)
	at org.jabref@100.0.0/org.jabref.model.entry.BibEntry.clearField(BibEntry.java:609)
	at org.jabref@100.0.0/org.jabref.model.entry.BibEntry.clearField(BibEntry.java:590)
	at org.jabref@100.0.0/org.jabref.logic.cleanup.ConvertToBibtexCleanup.lambda$cleanup$2(ConvertToBibtexCleanup.java:35)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at org.jabref@100.0.0/org.jabref.logic.cleanup.ConvertToBibtexCleanup.cleanup(ConvertToBibtexCleanup.java:25)
	at org.jabref@100.0.0/org.jabref.logic.importer.ImportCleanup.doPostCleanup(ImportCleanup.java:25)
	at org.jabref@100.0.0/org.jabref.logic.importer.ImportCleanup.lambda$doPostCleanup$0(ImportCleanup.java:36)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
  ```
</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #7606
Fixes #1018 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java [hunk 1]
```diff
@@ -78,10 +82,13 @@ public ImportEntriesViewModel(BackgroundTask<ParserResult> task,
         this.message.bind(task.messageProperty());
 
         task.onSuccess(parserResult -> {
+
             // store the complete parser result (to import groups, ... later on)
             this.parserResult = parserResult;
+
+            List<BibEntry> resultEntries = parserResult.getDatabase().getEntries().stream().map(cleanup::doPostCleanup).collect(Collectors.toList());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java:89]: An idea would be to move this cleanup to the `ImportHandler` for consistency reasons.

File: src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java [hunk 2]
```diff
@@ -52,6 +55,7 @@
     private final PreferencesService preferences;
     private final BibEntryTypesManager entryTypesManager;
 
+    private final ImportCleanup cleanup = new ImportCleanup(BibDatabaseMode.BIBTEX);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java:58]: If one uses the user database, then this would immediately take care of https://github.com/JabRef/jabref/issues/1018 as well, right?

File: src/main/java/org/jabref/logic/importer/fetcher/CompositeSearchBasedFetcher.java [hunk 3]
```diff
@@ -60,7 +60,6 @@ public String getName() {
                            }
                        })
                        .limit(maximumNumberOfReturnedResults)
-                       .map(cleanup::doPostCleanup)
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/importer/fetcher/CompositeSearchBasedFetcher.java:63]: the `cleanup` variable is still declared above but now unused if I'm not mistaken

**Review by tobiasdiez — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java:89]: Is already part of the importHandler for importing external files
https://github.com/JabRef/jabref/blob/bb011c9313367a28990ae213b3920fe6cd10d1dc/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java#L165-L169

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java]: Okay, then I don't get why you added it in the dialog. The `buildImportHandlerThenImportEntries` method uses the import handler to import entries.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java]: Ah thanks, then it can be removed here. Totally overlooked that this is called.

File: src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java [hunk 4]
```diff
@@ -51,6 +52,7 @@
     private final ObservableList<BibEntry> entries;
     private final PreferencesService preferences;
     private final BibEntryTypesManager entryTypesManager;
+    private ImportCleanup cleanup;
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java:55]: This is no longer required now.

**Review by tobiasdiez — APPROVED** [review]
LGTM
