### PR TITLE
Fix UNC path is missing sharename: \\ieee.csl

### LINKED ISSUE #14630: UNC path is missing sharename: \\ieee.csl
### JabRef version

6.0-alpha.3

### Operating system

Windows

### Details on version and operating system

Jabref 6.0.31342 Windows 11

### Checked with the [latest development build](https://builds.jabref.org/main/) (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start JabRef
2. JabRef crashes

### Appendix

...
<details>
I updated to the latest master version and jabref started one time - however, after closing it and opening it again, I just get the error in the log and jabref does not start up.
I'm not even sure where ieee.csl comes from. I looked on my PC and I can only find one in "C:\ProgramData\Docear4Word\Styles\ieee.csl" - but how does JabRef would use that file?
Is there some temp folder I could delete? I already removed `%APPDATA%/../Local/org.jabref`.

<summary>Log File</summary>

```
2025-12-16 15:14:58 [main] org.jabref.logic.search.PostgreServer.<init>()
INFO: Postgres server started, connection port: 32707
2025-12-16 15:14:59 [main] org.jabref.logic.citationstyle.CSLStyleLoader.loadInternalStyles()
INFO: Loaded 2829 CSL styles
2025-12-16 15:14:59 [JavaFX-Launcher] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
WARN: Unsupported JavaFX configuration: classes were loaded from 'module javafx.graphics', isAutomatic: false, isOpen: true
2025-12-16 15:15:01 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2025-12-16 15:15:01 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
2025-12-16 15:15:02 [pool-2-thread-1] org.jabref.logic.ai.ingestion.model.UpdateEmbeddingModelTask.call()
INFO: Downloading embedding model...
2025-12-16 15:15:02 [JavaFX Application Thread] org.jabref.gui.JabRefGUI.start()
ERROR: Error during initialization: java.nio.file.InvalidPathException: UNC path is missing sharename: \\ieee.csl
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:132)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:203)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at org.jabref.jablib/org.jabref.logic.citationstyle.CSLStyleUtils.createCitationStyleFromFile(CSLStyleUtils.java:64)
	at org.jabref/org.jabref.gui.preferences.JabRefGuiPreferences.lambda$getPreviewLayouts$0(JabRefGuiPreferences.java:904)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
	at org.jabref/org.jabref.gui.preferences.JabRefGuiPreferences.getPreviewLayouts(JabRefGuiPreferences.java:921)
	at org.jabref/org.jabref.gui.preferences.JabRefGuiPreferences.getPreviewPreferences(JabRefGuiPreferences.java:862)
	at org.jabref/org.jabref.gui.preview.PreviewPanel.<init>(PreviewPanel.java:60)
	at org.jabref/org.jabref.gui.entryeditor.EntryEditor.<init>(EntryEditor.java:149)
	at org.jabref/org.jabref.gui.frame.JabRefFrame.<init>(JabRefFrame.java:175)
	at org.jabref/org.jabref.gui.JabRefGUI.start(JabRefGUI.java:119)
	at javafx.graphics@25.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$4(LauncherImpl.java:845)
	at javafx.graphics@25.0.1/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$0(PlatformImpl.java:449)
	at javafx.graphics@25.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$0(PlatformImpl.java:424)
	at javafx.graphics@25.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@25.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@25.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$0(WinApplication.java:168)
	at java.base/java.lang.Thread.run(Thread.java:1447)

```

</details>

### PR DESCRIPTION
**Pull request by palukku**
### Related issues and pull requests

Closes #14630

### PR Description

Added an try catch which catches the invalidPathException and return an empty optional.

### Steps to test

image

Add a registry key `cycle/Preview` with `/Customized preview style;////ieee.csl` as the value and start jabref, it should not crash

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [/ I added screenshots in the PR description (if change is visible to the user)
- [/] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [/] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jablib/src/test/java/org/jabref/logic/citationstyle/CSLStyleUtilsTest.java [hunk 1]
```diff
@@ -82,6 +83,12 @@ void parseStyleInfo(String styleName, String expectedTitle, String expectedShort
         assertEquals(expectedUsesHangingIndent, styleInfo.get().usesHangingIndent());
     }
 
+    @Test
+    void createStyleFromFileReturnsEmptyOptionalForInvalidPath() {
+        Optional<CitationStyle> styleInfo = CSLStyleUtils.createCitationStyleFromFile("\\\\\\\\ieee.csl");
+        assertTrue(styleInfo.isEmpty());
```
Comment (Siedlerchr) [inline jablib/src/test/java/org/jabref/logic/citationstyle/CSLStyleUtilsTest.java]: assertEquals

**Review by subhramit — APPROVED** [review]
shrimp disciple approves

**Review by koppor — DISMISSED** [review]

**Review by koppor — APPROVED** [review]
