### PR TITLE
Fix for issue 5804: Rewrite ACM fetcher

### LINKED ISSUE #5804: Rewrite ACM fetcher, because of ACM web site changes
Test query: https://dl.acm.org/exportformats_search.cfm?query=%28%25252Bjabref%2520%25252Barchitectural%2520%25252Bchurn%29&within=owners.owner%3DGUIDE&expformat=bibtex

grafik

Asked on twitter: 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">.<a href="https://twitter.com/TheOfficialACM?ref_src=twsrc%5Etfw">@TheOfficialACM</a> Your exportformats_search.cfm seems to be down. This feature was very useful and widely used in the web. Is it intended that it currently does not work? <a href="https://twitter.com/hashtag/opencitations?src=hash&amp;ref_src=twsrc%5Etfw">#opencitations</a> - example query: <a href="https://t.co/TOf3sgqvL1">https://t.co/TOf3sgqvL1</a></p>&mdash; Oliver Kopp (@koppor) <a href="https://twitter.com/koppor/status/1212520118179311616?ref_src=twsrc%5Etfw">January 1, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### PR DESCRIPTION
**Pull request by Ryyyc**
Fixes #5804 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

<br>

From issue #5804, ACM Fetcher needs to be rewritten, because of ACM website changes.
One solution is to get the DOI from the HTML results of the search page, then use the export interface to get the JSON format data, and finally parse them.

Search API: https://dl.acm.org/action/doSearch?AllField=<query_string\>
Export API: https://dl.acm.org/action/exportCiteProcCitation?targetFile=custom-bibtex&format=bibTex&dois=<doi\>,<doi\>,...

What did I do:
1. Rewrited ACMPortalFetcher, added ACMPortalParser.
2. added Modified ACMPortalFetcherTest and ACMPortalParserTest.

Successfully get data from AMC Fetcher:
ACM-Portal
ACM-Portal-3-imported

### CODE REVIEW

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java [hunk 1]
```diff
@@ -0,0 +1,254 @@
...
+        URIBuilder uriBuilder = new URIBuilder(DOI_URL);
+        uriBuilder.addParameter("targetFile", "custom-bibtex");
+        uriBuilder.addParameter("format", "bibTex");
+        uriBuilder.addParameter("dois", String.join(",", doiList));
+        return uriBuilder.build().toURL();
+    }
+
+    private StandardEntryType typeStrToEnum(String typeStr) {
+        StandardEntryType type;
+        typeStr = typeStr.toLowerCase(Locale.ENGLISH).replace("_", "");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:142]: I think you can simplify this whole EntryType stuff, if you want too look up an enum key by the string value:
StandardEntryType.valueOf(...) 
Or alternatively, use the guava equivalent https://guava.dev/releases/19.0/api/docs/index.html?com/google/common/base/Enums.html

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java [hunk 2]
```diff
@@ -0,0 +1,254 @@
...
+        List<String> doiList = new ArrayList<>();
+        String htmlLine;
+        try (BufferedReader in = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8))) {
+            int cnt = 0;
+            while ((htmlLine = in.readLine()) != null && cnt < MAX_ITEM_CNT_PER_PAGE) {
+                if (ITEM_HTML.equals(htmlLine)) {
+                    Matcher matcher = DIO_HTML_PATTERN.matcher(in.readLine());
+                    if (matcher.find()) {
+                        doiList.add(matcher.group(1));
+                        ++cnt;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:88]: It usually makes no difference if you use a loop to have a normal post increment count https://stackoverflow.com/a/6175339/3450689

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java [hunk 3]
```diff
@@ -0,0 +1,254 @@
...
+import com.google.gson.JsonArray;
+import com.google.gson.JsonElement;
+import com.google.gson.JsonObject;
+import com.google.gson.JsonParser;
+import org.apache.http.client.utils.URIBuilder;
+
+public class ACMPortalParser implements Parser {
+
+    private static final String DOI_URL = "https://dl.acm.org/action/exportCiteProcCitation";
+    private static final Pattern DIO_HTML_PATTERN = Pattern.compile("<input name=\"(.*?)\"");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:41]:
```suggestion
    private static final Pattern DOI_HTML_PATTERN = Pattern.compile("<input name=\"(.*?)\"");
```
possible typo?

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+        expected.setField(StandardField.ABSTRACT, "The open source application JabRef has existed since 2003. In 2015, the developers decided to make an architectural refactoring as continued development was deemed too demanding. The developers also introduced Static Architecture Conformance Checking (SACC) to prevent violations to the intended architecture. Measurements mined from source code repositories such as code churn and code ownership has been linked to several problems, for example fault proneness, security vulnerabilities, code smells, and degraded maintainability. The root cause of such problems can be architectural. To determine the impact of the refactoring of JabRef, we measure the code churn and code ownership before and after the refactoring and find that large files with violations had a significantly higher code churn than large files without violations before the refactoring. After the refactoring, the files that had violations show a more normal code churn. We find no such effect on code ownership. We conclude that files that contain violations detectable by SACC methods are connected to higher than normal code churn.");
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:46]: Abstracts might be copyrighted, so just remove them for the test (e.g set the field to empty or remove it before comparing)

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+    void testParseBibEntry() {
+        assertEquals(searchEntryList.get(0), parser.parseBibEntry(jsonStr));
+    }
+
+    @Test
+    void testNoEntryFound() throws URISyntaxException, IOException, ParseException {
+        CookieHandler.setDefault(new CookieManager());
+        URL url = new URIBuilder("https://dl.acm.org/action/doSearch?AllField=10.1145/3129790.31298").build().toURL();
+        List<BibEntry> bibEntries = parser.parseEntries(new URLDownload(url).asInputStream());
+        assertEquals(new ArrayList<>(), bibEntries);
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:109]:
```suggestion
        assertEquals(Collections.emptyList(), bibEntries);
```

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Overall this looks already good to me, just some mimor changes/improvements

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 1 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:142]: The problem here is that the entry of StandardEntryType uses big camelcase nomenclature, I can't directly use StandardEntryType.valueOf(...), or I need to find a good way from JabRef to deal with big camelcase format and all-caps dashed separation format conversion.

And some types of naming do not match exactly. For example, the API returns PAPER_CONFERENCE corresponding to the CONFERENCE of StandardEntryType.

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 2 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:88]: I'm not sure what you mean, is it like this?
```java
for(int i = 0 ; i < MAX_ITEM_CNT_PER_PAGE; ){
    while ((htmlLine = in.readLine()) != null){
        if (ITEM_HTML.equals(htmlLine)) {
            Matcher matcher = DIO_HTML_PATTERN.matcher(in.readLine());
            if (matcher.find()) {
                doiList.add(matcher.group(1));
                ++i;
                break;
            }
        }
    }
}
```

But for the original while loop, a better implementation is:
```java
while ((htmlLine = in.readLine()) != null) {
    if (ITEM_HTML.equals(htmlLine)) {
        Matcher matcher = DIO_HTML_PATTERN.matcher(in.readLine());
        if (matcher.find()) {
            doiList.add(matcher.group(1));
            ++cnt;
            if (cnt >= MAX_ITEM_CNT_PER_PAGE) {
                break;
            }
        }
    }
}
```

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 3 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:41]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 4 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:46]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 5 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:109]: fixed.

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:88]: No i just meant i++ isntead of ++i

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:145]: Ah I understand, however, you can directly operate on the Enum, there is the possibility to use an EnumSet and you have an Optional, so you don't need to create a new Map with the keys and values 
```java
       Optional<StandardEntryType> foundType  = EnumSet.allOf(StandardEntryType.class).stream().filter(type-> type.getDisplayName().equals(strType)).findAny(); 
```

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 2 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:88]: fixed.
The final effect of i++ and ++i is the same, but their efficiency is different.
However, current compilers can automatically compile a single i++ into ++i.

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 1 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:145]: >   ```java
> Optional<StandardEntryType> foundType  = EnumSet.allOf(StandardEntryType.class).stream().filter(type-> type.getDisplayName().equals(strType)).findAny(); 
> ```
This is invalid if the input string is ARTICLE


New version~
```java
private StandardEntryType typeStrToEnum(String typeStr) {
    StandardEntryType type;
    if ("PAPER_CONFERENCE".equals(typeStr)) {
        type = StandardEntryType.Conference;
    } else {
        String upperUnderscoreTyeStr = CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, typeStr);
        type = Enums.getIfPresent(StandardEntryType.class, upperUnderscoreTyeStr).or(StandardEntryType.Article);
    }
    return type;
}
```

**Review by Siedlerchr — APPROVED** [review]

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 2 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:78]: `i++` is more reable. We do not do "premature optimization" (is this from https://www.amazon.de/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882/ref=asc_df_0132350882/?tag=googshopde-21&linkCode=df0&hvadid=310746693071&hvpos=&hvnetw=g&hvrand=3074721778032343418&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9042238&hvtargid=pla-435472505264&psc=1&th=1&psc=1&tag=&ref=&adgrpid=62150065416&hvpone=&hvptwo=&hvadid=310746693071&hvpos=&hvnetw=g&hvrand=3074721778032343418&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9042238&hvtargid=pla-435472505264?)

File: src/main/java/org/jabref/logic/importer/WebFetchers.java [hunk 6]
```diff
@@ -93,7 +94,7 @@ private WebFetchers() {
         set.add(new MathSciNet(importFormatPreferences));
         set.add(new ZbMATH(importFormatPreferences));
         // see https://github.com/JabRef/jabref/issues/5804
-        // set.add(new ACMPortalFetcher(importFormatPreferences));
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/WebFetchers.java:96]: Just remove the disabled lines

File: src/main/java/org/jabref/logic/importer/fetcher/ACMPortalFetcher.java [hunk 7]
```diff
@@ -38,23 +36,32 @@ public String getName() {
...
-        uriBuilder.addParameter("within", "owners.owner=GUIDE"); // Search within the ACM Guide to Computing Literature (encompasses the ACM Full-Text Collection)
-        uriBuilder.addParameter("expformat", "bibtex"); // BibTeX format
+        uriBuilder.addParameter("AllField", createQueryString(query));
         return uriBuilder.build().toURL();
     }
 
+    /**
+     * Gets an instance of ACMPortalParser.
+     *
+     * @return ACMPortalParser
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/ACMPortalFetcher.java:60]: In case you cannot state something about a return type - please just remove that JavaDoc line

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+        expected.setField(StandardField.DOI, "10.1145/3129790.3129810");
+        expected.setField(StandardField.LOCATION, "Canterbury, United Kingdom");
+        expected.setField(StandardField.ISBN, "9781450352178");
+        expected.setField(StandardField.KEYWORDS, "conformance checking, repository data mining, software architecture");
+        expected.setField(StandardField.PUBLISHER, "Association for Computing Machinery");
+        expected.setField(StandardField.ADDRESS, "New York, NY, USA");
+        expected.setField(StandardField.TITLE, "The relationship of code churn and architectural violations in the open source software JabRef");
+        expected.setField(StandardField.URL, "https://doi.org/10.1145/3129790.3129810");
+        expected.setField(StandardField.PAGETOTAL, "7");
+        expected.setField(StandardField.PAGES, "152–158");
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:58]: If you want, you can replace `expected.setField` by `.withField()` (which is our kind of a builder)

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+        for (BibEntry bibEntry : bibEntries) {
+            bibEntry.clearField(StandardField.ABSTRACT);
+        }
+        assertEquals(Collections.singletonList(searchEntryList), Collections.singletonList(bibEntries));
+    }
+
+    @Test
+    void testParseDoiSearchPage() throws ParseException, IOException {
+        List<String> testDoiList = new LinkedList<>();
+        testDoiList.add(searchDoi);
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:76]:
```suggestion
        List<String> testDoiList = List.of(searchDoi);
```

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+
+        CookieHandler.setDefault(new CookieManager());
+        List<String> doiList = parser.parseDoiSearchPage(new URLDownload(searchUrl).asInputStream());
+        assertEquals(testDoiList, doiList);
+    }
+
+    @Test
+    void testGetBibEntriesFromDoiList() throws FetcherException {
+        List<String> testDoiList = new LinkedList<>();
+        testDoiList.add(searchDoi);
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:86]:
```suggestion
        List<String> testDoiList = List.of(searchDoi);
```

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+        assertEquals(Collections.singletonList(searchEntryList), Collections.singletonList(bibEntries));
+    }
+
+    @Test
+    void testGetUrlFromDoiList() throws MalformedURLException, URISyntaxException {
+        String target = "https://dl.acm.org/action/exportCiteProcCitation?targetFile=custom-bibtex&format=bibTex&dois=10.1145%2F3129790.3129810%2C10.1145%2F3129790.3129811";
+
+        List<String> doiList = new ArrayList<>();
+        doiList.add("10.1145/3129790.3129810");
+        doiList.add("10.1145/3129790.3129811");
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:100]:
```suggestion
        List<String> doiList = List.of("10.1145/3129790.3129810", "10.1145/3129790.3129811");
```

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+
+    @BeforeEach
+    void setUp() throws URISyntaxException, MalformedURLException {
+        parser = new ACMPortalParser();
+        searchUrl = new URIBuilder("https://dl.acm.org/action/doSearch?AllField=" + searchDoi).build().toURL();
+        searchEntryList = new ArrayList<>();
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:38]: Can you try 

```java
  searchEntryList = List.of(new BibEntry(StandardEntryType.Conference)
     .withField(...)
     .withField(...)
  ...;
```

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+    }
+
+    @Test
+    void testParseEntries() throws IOException, ParseException {
+        CookieHandler.setDefault(new CookieManager());
+        List<BibEntry> bibEntries = parser.parseEntries(new URLDownload(searchUrl).asInputStream());
+        for (BibEntry bibEntry : bibEntries) {
+            bibEntry.clearField(StandardField.ABSTRACT);
+        }
+        assertEquals(Collections.singletonList(searchEntryList), Collections.singletonList(bibEntries));
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:70]:
```suggestion
        assertEquals(searchEntryList, bibEntries);
```

File: src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java [hunk 14]
```diff
@@ -1,57 +1,77 @@
...
+        expected.setField(StandardField.TITLE, "The relationship of code churn and architectural violations in the open source software JabRef");
+        expected.setField(StandardField.URL, "https://doi.org/10.1145/3129790.3129810");
+        expected.setField(StandardField.PAGETOTAL, "7");
+        expected.setField(StandardField.PAGES, "152–158");
 
         List<BibEntry> fetchedEntries = fetcher.performSearch("jabref architectural churn");
-        assertEquals(Collections.singletonList(expected), fetchedEntries);
+        BibEntry bibEntry = fetchedEntries.get(0);
+        bibEntry.clearField(StandardField.ABSTRACT);
+        assertEquals(Collections.singletonList(expected), Collections.singletonList(bibEntry));
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java:59]:
```suggestion
        // we clear the abstract due to copyright reasons (JabRef's code should not contain copyrighted abstracts)
        fetchedEntries.get(0).clearField(StandardField.ABSTRACT);
        // check for a) that a single entry is returned and b) that the entry itself is the expected one
        assertEquals(Collections.singletonList(expected), fetchedEntries);
```

**Review by koppor — CHANGES_REQUESTED** [review]
Good job!

Thank you for creating tests!

Small comments on the tests itself.

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java (hunk 2 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:78]: Understand, fixed.

File: src/main/java/org/jabref/logic/importer/fetcher/ACMPortalFetcher.java (hunk 7 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fetcher/ACMPortalFetcher.java:60]: fixed.

File: src/main/java/org/jabref/logic/importer/WebFetchers.java (hunk 6 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/WebFetchers.java:96]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 8 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:58]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 9 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:76]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 10 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:86]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 11 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:100]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 12 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:38]: fixed.

File: src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java (hunk 13 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/ACMPortalParserTest.java:70]: fixed.

File: src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java (hunk 14 above)
Comment (Ryyyc) [reply src/test/java/org/jabref/logic/importer/fetcher/ACMPortalFetcherTest.java:59]: fixed.

**Comment by Ryyyc** [comment]
@Siedlerchr  @koppor Thank you very much for your help and suggestions.
The above problem has been fixed, and I also updated some codes.

File: src/main/java/org/jabref/logic/importer/WebFetchers.java (hunk 6 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/WebFetchers.java:96]: May I ask whether you committed that change?

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java [hunk 15]
```diff
@@ -0,0 +1,241 @@
...
+    public BibEntry parseBibEntry(String jsonStr) {
+        JsonObject jsonObject = JsonParser.parseString(jsonStr).getAsJsonObject();
+        BibEntry bibEntry = new BibEntry();
+        if (jsonObject.has("type")) {
+            bibEntry.setType(typeStrToEnum(jsonObject.get("type").getAsString()));
+        }
+
+        if (jsonObject.has("author")) {
+            JsonArray authors = jsonObject.getAsJsonArray("author");
+            StringBuilder authorStrBuilder = new StringBuilder();
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:159]:
```suggestion
            StringJoiner authors = new StringJoinger(" and ");
```

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java [hunk 16]
```diff
@@ -0,0 +1,241 @@
...
+            int size = authors.size();
+            for (JsonElement author : authors) {
+                JsonObject authorJsonObject = author.getAsJsonObject();
+                authorStrBuilder.append(authorJsonObject.get("given").getAsString()).append(" ")
+                        .append(authorJsonObject.get("family").getAsString());
+                --size;
+                if (size > 0) {
+                    authorStrBuilder.append(" and ");
+                }
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:168]: Please use the magic of Java 8's [StringJoiner](https://docs.oracle.com/javase/8/docs/api/java/util/StringJoiner.html)

```suggestion
                authors.append(
                  authorJsonObject.get("given") + " " + authorJsonObject.get("family")
                );
```

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java [hunk 17]
```diff
@@ -0,0 +1,241 @@
...
+            bibEntry.setField(StandardField.LOCATION, jsonObject.get("event-place").getAsString());
+        }
+
+        if (jsonObject.has("ISBN")) {
+            bibEntry.setField(StandardField.ISBN, jsonObject.get("ISBN").getAsString());
+        }
+
+        if (jsonObject.has("keyword")) {
+            String[] keywords = jsonObject.get("keyword").getAsString().split(", ");
+            String sortedKeywords = Arrays.stream(keywords).sorted().collect(Collectors.joining(", "));
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:210]: Nice that you used `Collectors.joining`.

**Review by koppor — CHANGES_REQUESTED** [review]
Thank you for the quick follow-up.

Some small nitpicks remain 😇

File: src/main/java/org/jabref/logic/importer/WebFetchers.java (hunk 6 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/WebFetchers.java:96]: I have deleted these two lines
```java
// see https://github.com/JabRef/jabref/issues/5804 
// set.add(new ACMPortalFetcher(importFormatPreferences));
```
do you mean I still need to delete this line?
```
// set.add(new GoogleScholar(importFormatPreferences));
```
But this is another Fetcher

Comment (koppor) [reply src/main/java/org/jabref/logic/importer/WebFetchers.java:96]: Sorry, was too late. Everything allright! 🎉

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
Thank you for working on it! This brings JabRef a step forward!
