### PR TITLE
Change default behavior of resolve bibtex strings

### LINKED ISSUE #7010: Markdown comments dissapear on new start when having # chars
JabRef version 5.1--2020-08-30--e023aa0 on Ubuntu 20.04

Hi all!
I am trying to add comments in the comment tab to different entries to get myself an own insight of what I am reading. I've read that from version 5.1 on the markdown style is available. What I am trying to do is create sections in the comment: goal, achievement, method, failure... like this:
#### Goal (#### Goal)
Lorem ipsum dolor sit amet, consectetur adipiscing elit,
#### Achievement (#### Achievement)
Lorem ipsum dolor sit amet, consectetur adipiscing elit,
#### Method (#### Method)
Lorem ipsum dolor sit amet, consectetur adipiscing elit,

I save the changes and everything looks to work correctly but everytime I reopen JabRef the # are gone and so the sections are not longer highlighted.

Goal Lorem ipsum dolor sit amet, consectetur adipiscing elit,
Achievement Lorem ipsum dolor sit amet, consectetur adipiscing elit,
Method Lorem ipsum dolor sit amet, consectetur adipiscing elit,

It is a pain to add the hashes everytime I reopen the software. Do you have any clue how to fix this?

### LINKED ISSUE #7012: Error when adding file containing # to entry with character
JabRef version 5.2--2020-10-13--fdaf25a on Windows 10

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add bibtexentry for https://link.springer.com/book/10.1007%2F978-3-662-53281-2
2. Add file
3.  Apply format pattern: "Filename format pattern": [bibtexkey] - [title:latex_to_unicode:remove_braces_formatter:regex("/|:|,","#")]
4. Restart Jabref
5. When opening from jabref, the file is not found.
6. bilatex source file line looks weird: "file      = {:Hue17 - Leiter} # Halbleiter #{ Supraleiter.pdf:PDF},"

My setup: biblatex, keypattern: "[auth3][shortyear]"

### LINKED ISSUE #8303: Hex encoded character breakes entry
### JabRef version

5.3 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

_No response_

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open _bug-1.bib_ 
2. Change something, e.g., generate a new Bibtex key and save the library
3. The Hex encoded character &#x2013; breaks the abstract field

I was able to track down the bug to the `formatAndResolveStrings` method in the `org.jabref.logic.bibtex.FieldWriter` class where the first encounter of the `#` enforces that the abstract field is closed with a `}`. 

### Appendix

[bug-1.txt](https://github.com/JabRef/jabref/files/7661797/bug-1.txt)
[bug-2.txt](https://github.com/JabRef/jabref/files/7661798/bug-2.txt)

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #7010
Fixes #7012
Fixes #8303

grafik

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Discussion: Invert logic And resolve fields only for the following list:  
Author, BookAuthor, Title, Editor , Journal + JournalTitle + SubTitile etc 
Editor a, b,c  Issue + SubTitle,  MainTitle, MainSubTitle, MainTitleAddon, Publisher, shortAuthor + Editor + Title

File: src/main/java/org/jabref/migrations/PreferencesMigrations.java [hunk 1]
```diff
@@ -290,6 +291,18 @@ private static void addCrossRefRelatedFieldsForAutoComplete(JabRefPreferences pr
         prefs.putStringList(JabRefPreferences.AUTOCOMPLETER_COMPLETE_FIELDS, new ArrayList<>(keys));
     }
 
+    private static void migrateDoNotResolveFields(JabRefPreferences prefs) {
+        Set<String> keys = new LinkedHashSet<>(prefs.getStringList(JabRefPreferences.DO_NOT_RESOLVE_STRINGS_FOR));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/migrations/PreferencesMigrations.java:295]: Migrations are run every time, right? So if someone decides to remove say `url` from the exception list, then this migration would readd upon the next start of JabRef, or not?

Comment (Siedlerchr) [reply src/main/java/org/jabref/migrations/PreferencesMigrations.java:295]: Yes. But ignore this. The whole logic will be inverted.

**Comment by Siedlerchr** [comment]
add field month to string resolving

File: src/main/java/org/jabref/gui/preferences/file/FileTab.fxml [hunk 2]
```diff
@@ -24,12 +24,12 @@
         <Label text="%Do not wrap the following fields when saving"/>
         <TextField fx:id="noWrapFiles" HBox.hgrow="ALWAYS"/>
     </HBox>
-    <RadioButton fx:id="resolveStringsBibTex" text="%Resolve strings for standard BibTeX fields only"
+    <RadioButton fx:id="doNotResolveStrings" text="%Do not resolve BibTeX strings"
```
Comment (koppor) [inline src/main/java/org/jabref/gui/preferences/file/FileTab.fxml:27]: I would work with positive statements only

```suggestion
    <RadioButton fx:id="resolveStrings" text="%Resolve BibTeX strings"
```

And have that activated.

File: src/main/java/org/jabref/gui/preferences/file/FileTab.fxml [hunk 3]
```diff
@@ -24,12 +24,12 @@
...
                  toggleGroup="$stringsResolveToggleGroup"/>
     <HBox alignment="CENTER_LEFT" spacing="10.0">
-        <RadioButton fx:id="resolveStringsAll" text="%Resolve strings for all fields except"
+        <RadioButton fx:id="resolveStrings" text="%Resolve BibTeX strings for the following fields"
```
Comment (koppor) [inline src/main/java/org/jabref/gui/preferences/file/FileTab.fxml:30]:
```suggestion
        <RadioButton fx:id="resolveStringsForFieldsButton" text="%Resolve BibTeX strings for the following fields"
```

File: src/main/java/org/jabref/preferences/JabRefPreferences.java [hunk 4]
```diff
@@ -629,8 +629,8 @@ private JabRefPreferences() {
         defaults.put(CONFIRM_DELETE, Boolean.TRUE);
         defaults.put(DEFAULT_CITATION_KEY_PATTERN, "[auth][year]");
         defaults.put(UNWANTED_CITATION_KEY_CHARACTERS, "-`ʹ:!;?^+");
-        defaults.put(DO_NOT_RESOLVE_STRINGS_FOR, StandardField.URL.getName());
-        defaults.put(RESOLVE_STRINGS_ALL_FIELDS, Boolean.FALSE);
+        defaults.put(RESOLVE_STRINGS_FOR_FIELDS, "author;editor;editora;editorb;editorc;publisher;month;journal;journaltitle;journalsubtitle;subtitle;issuetitle;titleaddon;mainsubtitle;booktitle;shortauthor;shorteditor");
```
Comment (koppor) [inline src/main/java/org/jabref/preferences/JabRefPreferences.java:632]: I checked our help https://docs.jabref.org/advanced/strings#jabrefs-typed-strings

I think, `institution` and `publisher` should be added here, too.

**Review by koppor — CHANGES_REQUESTED** [review]
Some small nitpick regarding the negation - and two additional fields. 😇

File: src/main/java/org/jabref/gui/preferences/file/FileTab.fxml (hunk 3 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/preferences/file/FileTab.fxml:30]: Hm
The idea was to have an option to disable the resolving completely or activate it for the following fields only. See Screenshot. By default its only activated for the fields 
Otherwise we have the same situation as before

File: src/main/java/org/jabref/preferences/JabRefPreferences.java (hunk 4 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:632]: Added institution, publisher is already present

File: src/main/java/org/jabref/gui/preferences/file/FileTab.fxml (hunk 3 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/preferences/file/FileTab.fxml:30]: This comment was only about the naming of the identifier 😇

Comment (koppor) [reply src/main/java/org/jabref/gui/preferences/file/FileTab.fxml:30]: My driving force was that negations should be avoided in the UI. I was thinking of a checkbox for enabling/disabling the feature. When enabled, one can set which fields... I agree, the current implementation is more consistent to our other properties:

grafik

**Comment by koppor** [comment]
I worked on the preferences tab to improve the UI by grouping the preferences for "File" together:

grafik

**Comment by koppor** [comment]
I would now like to add test cases for the fields mentioned in the fixed issues. I know, It's "only" a preference (mocking) thing. However, I would like to have more tests to ensure that nothing breaks if we touch this part of the code at a later time.

**Comment by calixtus** [comment]
Do you want to test the FieldWriter with the mentioned fields in this PR or do you want to test the preferences if they return the right fields? I don't think the latter would be meaningful at all...

Btw., this PR is still a draft...

**Comment by Siedlerchr** [comment]
The FieldWriter has already tests that I modified to use the preferences value with the field month

File: src/test/java/org/jabref/logic/bibtex/FieldWriterTests.java [hunk 5]
```diff
@@ -1,26 +1,25 @@
...
-import static org.mockito.Mockito.mock;
 
 class FieldWriterTests {
 
     private FieldWriter writer;
 
     @BeforeEach
     void setUp() {
-        this.writer = new FieldWriter(mock(FieldWriterPreferences.class, Answers.RETURNS_DEEP_STUBS));
+        FieldWriterPreferences fieldWriterPreferences = new FieldWriterPreferences(false, List.of(StandardField.MONTH), new FieldContentFormatterPreferences());
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/bibtex/FieldWriterTests.java:21]: @koppor  Here is the test for the FieldWriter using the FieldWriterPreferenes with Field Month

Comment (koppor) [reply src/test/java/org/jabref/logic/bibtex/FieldWriterTests.java:21]: Yeah - and I think, we don't have a test for the content written down at https://github.com/JabRef/jabref/issues/7010. Thus, I am thinking of how to include a test for that. Think, I have a bit of a clue. However, I need the comments of https://github.com/JabRef/jabref/pull/8404 to really know where to put the tests to 😋

Comment (Siedlerchr) [reply src/test/java/org/jabref/logic/bibtex/FieldWriterTests.java:21]: I will just add one for comment field in this class

**Comment by Siedlerchr** [comment]
failing fetcher test is grobid

**Comment by koppor** [comment]
I added the BibTeX field content of the three linked issues as tests (verbatimely).

**Comment by Siedlerchr** [comment]
I am not sure if your negation change doesn't break anything

**Comment by koppor** [comment]
Side note: I find `isEnabled` more readable than `!isDisabled`. Pattern "Avoid Negations", page 4, in [Java by Comparison](https://java.by-comparison.com/).

> I am not sure if your negation change doesn't break anything

- Tests run through :) -- In case one has a gut feeling something could break, please provide examples, and I am happy to craft tests.
- I replace the negative clause by positive one and adding `!`.
- All positive parameters (`true`) have been replaced by negative ones (`false`) and vice versa
- "in a distributive lattice, an element has, at most, one complement" (https://math.stackexchange.com/a/3439133/75732)

**Comment by koppor** [comment]
The only thing, I did not touch is the storing in the registry. There, the negegation is still stored.

File: src/main/java/org/jabref/logic/bibtex/FieldWriter.java [hunk 6]
```diff
@@ -163,7 +168,7 @@ private String formatAndResolveStrings(String content, Field field) throws Inval
     }
 
     private boolean shouldResolveStrings(Field field) {
-        if (!preferences.isDoNotResolveStrings()) {
+        if (preferences.isResolveStrings()) {
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/bibtex/FieldWriter.java:171]: shouldResolveStrings?

**Comment by Siedlerchr** [comment]
After looking again at the changes, it looks good and I will merge it now

File: src/main/java/org/jabref/logic/bibtex/FieldWriter.java (hunk 6 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/bibtex/FieldWriter.java:171]: Follow-up PR 😇
