### PR TITLE
Fix macOS cursor shortcuts in BibTeX source editor (#5937)

### LINKED ISSUE #5937: Text cursor movement shortcuts do not work correctly on macOS
JabRef version 
```
JabRef 5.0-beta.409--2020-02-09--6a9c915
Mac OS X 10.14.6 x86_64 
Java 13.0.2
```

On macOS, in a text box, Option-Left/Right moves the insertion point by one word, and Command-Left/Right moves it to the beginning or end of the line. This is the standard behaviour in all apps.

JabRef follows this standard in some text boxes, but not others.  It works in the Title field:

image

But it does not work in the BibTeX source box:

image

This makes it very inconvenient to edit the BibTeX source on a Mac.

Please ensure that the app follows the OS's standard in all textboxes.

### PR DESCRIPTION
**Pull request by AnvitaPrasad**
### Related issues and pull requests

Closes #5937

### PR Description

This PR fixes macOS cursor navigation behavior in the BibTeX source editor so it matches standard macOS text editing. Command+Left/Right now moves to line start/end in that editor as expected. This makes editing BibTeX source on macOS consistent with other text fields and with native app behavior.

### Steps to test

1. Use macOS.
2. Start JabRef from this branch.
3. Open any `.bib` library.
4. Select one entry and open the entry editor.
5. Go to the **Source** tab (BibTeX source editor).
6. Place the cursor in the middle of a long line.
7. Press **Command+Left** and **Command+Right**:
   - Expected: cursor jumps to beginning/end of line.
8. Compare with behavior on `main` branch to confirm the fix.

### Before

https://github.com/user-attachments/assets/06005164-ef12-4133-a7a9-5c079e21eab1

### After

https://github.com/user-attachments/assets/f5805af3-54a1-439b-b761-3dee63012b9d

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [ ] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [ ] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Command left/right works for me, but option left/right which should move the caret to the word, doesn't work for me here on macOS Sequoia 15.7.3 (Macbook pro) but that option doesn't work in text fields either (seems to also not work on main)  
Can you take a look at that or reproduce that as well?
Otherwise just fix the failing tests and add a changelog entry

File: jabgui/src/main/java/org/jabref/gui/keyboard/CodeAreaKeyBindings.java [hunk 1]
```diff
@@ -11,6 +13,10 @@
 public class CodeAreaKeyBindings {
 
     public static void call(CodeArea codeArea, KeyEvent event, KeyBindingRepository keyBindingRepository) {
+        if (handleMacCursorMovementShortcuts(codeArea, event)) {
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline jabgui/src/main/java/org/jabref/gui/keyboard/CodeAreaKeyBindings.java]: The method both calls `event.consume()` and returns `true`, which are two signals for the same thing. Since `event.consume()` is required regardless to stop JavaFX event propagation, the boolean return is redundant. If they ever diverge (e.g. calling `consume()` but forgetting `return true`), you have a bug. Consider changing to `void` and checking `event.isConsumed()` instead as a single source of truth.

File: jabgui/src/main/java/org/jabref/gui/keyboard/CodeAreaKeyBindings.java [hunk 2]
```diff
@@ -107,5 +113,45 @@ public static void call(CodeArea codeArea, KeyEvent event, KeyBindingRepository
...
     }
+
+    private static boolean handleMacCursorMovementShortcuts(CodeArea codeArea, KeyEvent event) {
+        if (!OS.OS_X) {
+            return false;
+        }
+
+        KeyCode code = event.getCode();
+        if ((code != KeyCode.LEFT) && (code != KeyCode.RIGHT)) {
+            return false;
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline jabgui/src/main/java/org/jabref/gui/keyboard/CodeAreaKeyBindings.java]: Suggestion, possibly outside the scope of this PR: Per [Apple's keyboard shortcuts](https://support.apple.com/en-us/102650), standard macOS text editing also includes:
- Command+Up/Down for document start/end
- Option+Up/Down for paragraph start/end
- Shift variants for selection

All needed CodeArea methods exist (`start(policy)`, `end(policy)`, `paragraphStart(policy)`, `paragraphEnd(policy)`).

File: jabgui/src/main/java/org/jabref/gui/keyboard/CodeAreaKeyBindings.java [hunk 3]
```diff
@@ -107,5 +113,45 @@ public static void call(CodeArea codeArea, KeyEvent event, KeyBindingRepository
...
+        }
+
+        NavigationActions.SelectionPolicy policy = event.isShiftDown()
+                ? NavigationActions.SelectionPolicy.EXTEND
+                : NavigationActions.SelectionPolicy.CLEAR;
+
+        boolean optionOnly = event.isAltDown() && !event.isMetaDown() && !event.isControlDown();
+        boolean commandOnly = event.isMetaDown() && !event.isAltDown() && !event.isControlDown();
+
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline jabgui/src/main/java/org/jabref/gui/keyboard/CodeAreaKeyBindings.java:138]: Nice touch. The named booleans `optionOnly` and `commandOnly` document the macOS intent clearly and make the modifier checks readable without needing comments.

**Review by k3KAW8Pnf7mkmdSMPHz27 — COMMENTED** [review]
Tested and working on macOS 26.3. A few suggestions below.

**Comment by AnvitaPrasad** [comment]
@k3KAW8Pnf7mkmdSMPHz27 @Siedlerchr 
Looks like issue was that `JabRefFrame.initKeyBindings()` had an event filter at the frame level that was intercepting alt+LEFT/RIGHT before the CodeArea even saw them. basically it was consuming those keys for BACK/FORWARD navigation before the handler could do anything with it.
What I did was add a check before handling BACK/FORWARD. if a TextInputControl or CodeArea is focused, the frame level handler just skips it. That way the event goes through to the editor and option+left/right works as expected. It also ends up fixing the behavior for regular text fields too.

**Comment by Siedlerchr** [comment]
Ah great that makes my PR then obsolte!

**Comment by Siedlerchr** [comment]
The only thing that doesn't yet work in the CodeArea is paragraph up/down using Option + up/down as @k3KAW8Pnf7mkmdSMPHz27 mentioned, the rest works fine and also fixes the normal text input fields!

**Comment by AnvitaPrasad** [comment]
@Siedlerchr Sorry for the overlap with your PR 😅. 

About the Option + Up/Down. I wasn’t sure if that should be in scope for this PR since #5937 was mainly about left/right navigation.Should I add it here or open a small follow up PR for that?

**Comment by Siedlerchr** [comment]
No worries, your solution is more elegant :) 
Just create a follow up PR
