### PR TITLE
Use regexp to remove non-ASCII characters from DOI and inform user when data for valid DOI does not exist #8127

### LINKED ISSUE #8127: Invalid DOI should not show "Connection error"
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open https://link.springer.com/book/10.1007/978-3-319-47590-5
2. Download PDF ("Download book PDF")
3. Go to page 207
4. Select and copy the DOI:  
  image
5. Open "New entry dialog" and paste DOI:  
  image
6. See the question mark at the end
7. Click "Generate"
8. Result:  
  image

Expected behavior:

- The invalid character at the end should be removed internally
- The DOI data should be fetched

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by mrcstan**
Use single regexp to remove white-space and non-ASCII characters in DOI to fixes #8127. Further inform the user that "No DOI data exists" if DOI is valid and unable to find the article. Works for cases where DOI.findInText does not #8227. For example, the DOI "https : / / doi.org / 10 / gf4gqc" with the quote removed will result in an error not capture by Jabref itself. The reason is that the pattern used by DOI.findInText to extract DOI is not comprehensive. DOI.findInText is only tested in DOITest but not used elsewhere in the source code. However, DOI.parse is used in both DoiFetcher and CompositeIdFetcher, so it is probably better to improve DOI.parse.   

With DOI.findInText:
image

With this PR:
image

With this PR, user is informed that no data exists if the DOI is valid but no data is found online
image

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/model/entry/identifier/DOI.java [hunk 1]
```diff
@@ -88,6 +88,14 @@
     private static final Pattern FIND_SHORT_DOI_SHORTCUT = Pattern.compile(IN_TEXT_SHORT_DOI_SHORTCUT, Pattern.CASE_INSENSITIVE); // eg doi.org/bfrhmx (no "10/")
     private static final Pattern EXACT_SHORT_DOI_PATT = Pattern.compile(SHORT_DOI_EXP_PREFIX + SHORT_DOI_EXP, Pattern.CASE_INSENSITIVE);
     private static final Pattern FIND_SHORT_DOI_PATT = Pattern.compile("(?:https?://[^\\s]+?)?" + FIND_SHORT_DOI_EXP, Pattern.CASE_INSENSITIVE);
+
+    // See https://www.baeldung.com/java-regex-s-splus for explanation of \\s+
+    // See https://stackoverflow.com/questions/3203190/regex-any-ascii-character for the regexp that includes ASCII characters only
+    // Another reference for regexp for ASCII characters: https://howtodoinjava.com/java/regex/java-clean-ascii-text-non-printable-chars/
+    private static final String PARSE_DOI = "[\\s+" // remove white space characters, i.e, \t, \n, \x0B, \f, \r . + is a greedy quantifier
```
Comment (koppor) [inline src/main/java/org/jabref/model/entry/identifier/DOI.java:95]: I would name that `CHARACTERS_TO_REMOVE` to indicate that these should be removed. Currently, it reads that this RegEx is used to read a DOI into memory (semantics of the word "to parse")

**Review by koppor — CHANGES_REQUESTED** [review]
Small comment - other than that: LGTM!

File: src/main/java/org/jabref/model/entry/identifier/DOI.java (hunk 1 above)
Comment (mrcstan) [reply src/main/java/org/jabref/model/entry/identifier/DOI.java]: Thanks for the feedback. I have renamed it as CHARS_TO_REMOVE.

**Review by Siedlerchr — APPROVED** [review]
Thanks, lgtm now!

**Review by koppor — APPROVED** [review]
