### PR TITLE
Increase the network connection timeout and improve error message

### LINKED ISSUE #8653: JabRef opens multiple instances even when Remote operation is enabled
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint 20.1 MATE, JabRef 5.6--2022-04-04--dbf921e

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

0. Read documentation on this feature at https://docs.jabref.org/advanced/remote
1. Open JabRef
2. Under Options -> Preferences, Network, check the "Listen for remote operation on port" box and make sure 6050 is entered.
3. Save the settings, optionally restart the application.
4. Using `netstat -lpnt |grep 6050` confirm that the port is properly opened by the java process
5. Attempt to open an additional copy of JabRef, either by launching the application or by using the browser extension to import a new reference.

Expected behavior: based on the documentation saying "Binding to this port makes it possible for a second JabRef instance to discover that the first one is running. In this case, unless specifically instructed to run in stand-alone mode, the second JabRef instance will pass its command line options through the port to the first JabRef instance, and then **immediately quit.**" (emphasis added).

Actual behavior: When importing from the browser extension, a new instance of JabRef is opened and stays open. When launched from a console, `WARN: Port is blocked: java.net.BindException: Address already in use` is shown in the console of the second JabRef instance, and the application opens and stays open.

### Appendix

...
<details>

<summary>Log File</summary>

```
Apr 07, 2022 2:32:20 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2022-04-07 14:32:21 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: /home/jakkarth/.local/share/ssl/truststore.jks
2022-04-07 14:32:22 [JavaFX Application Thread] org.jabref.logic.remote.server.RemoteListenerServerLifecycle.open()
WARN: Port is blocked: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at java.base/java.net.ServerSocket.<init>(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.remote.server.RemoteListenerServer.<init>(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.remote.server.RemoteListenerServerThread.<init>(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.remote.server.RemoteListenerServerLifecycle.open(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.remote.server.RemoteListenerServerLifecycle.openAndStart(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.JabRefMain.handleMultipleAppInstances(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.JabRefMain.start(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

### PR DESCRIPTION
**Pull request by jakkarth**
In some instances, connecting to an existing JabRef instance may take longer
than the original 200ms timeout. Here we increase that timeout to a full
second. If it takes longer than that to connect to an existing instance,
chances are something else bad is going on.

Additionally, in a case where we attempt a ping but it fails for some reason,
but we're also unable to bind the port to listen ourselves, we give the
user a more informative error message about the potential cause of that
problem, and offer two possible solutions: figure out what other process
is already binding the port, or file a bug if that process happens to be
JabRef (since that would indicate that a 1s timeout isn't sufficient).

Fixes #8653.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/remote/client/RemoteClient.java [hunk 1]
```diff
@@ -18,7 +18,7 @@ public class RemoteClient {
 
     private static final Logger LOGGER = LoggerFactory.getLogger(RemoteClient.class);
 
-    private static final int TIMEOUT = 200;
+    private static final int TIMEOUT = 20000;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/remote/client/RemoteClient.java:21]: Do you have a zero to much here? Now you would have 20s...

Comment (jakkarth) [reply src/main/java/org/jabref/logic/remote/client/RemoteClient.java]: I do, yes! Thanks :)

File: CHANGELOG.md [hunk 2]
```diff
@@ -30,6 +30,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - The Medline/Pubmed search now also supports the [default fields and operators for searching](https://docs.jabref.org/collect/import-using-online-bibliographic-database#search-syntax). [forum#3554](https://discourse.jabref.org/t/native-pubmed-search/3354)
 - We improved group expansion arrow that prevent it from activating group when expanding or collapsing. [#7982](https://github.com/JabRef/jabref/issues/7982), [#3176](https://github.com/JabRef/jabref/issues/3176)
 - When configured SSL certificates changed, JabRef warns the user to restart to apply the configuration.
+- Increased the multi-instance network connection timeout to 1000ms.
```
Comment (Siphalor) [inline CHANGELOG.md:33]: Not sure, but I think it'd be nice to mention the issue here, just to gibe a bit more context :)

**Review by Siphalor — APPROVED** [review]
Looks good - well it isn't that much ^^

As mentioned below, I'd provide a bit more details in the changelog (with a reference to the issue).

File: CHANGELOG.md (hunk 2 above)
Comment (ThiloteE) [reply CHANGELOG.md:33]: Changelogs should be understandable to the average user and be less technical: `We fixed an issue that caused JabRef to open multiple instances when "Remote Operation" is enabled` sounds good to me :-)

File: src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java [hunk 3]
```diff
@@ -43,7 +43,9 @@ public void open(MessageHandler messageHandler, int port, PreferencesService pre
         try {
             result = new RemoteListenerServerThread(messageHandler, port, preferencesService);
         } catch (BindException e) {
-            LOGGER.warn("Port is blocked", e);
+            LOGGER.warn("There was an error opening the configured network port {}. Please ensure there isn't another" +
+                    " application already using that port. If you're sure an existing JabRef instance is running and" +
+                    " using this port, and you see this message, please file a bug.", port);
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java:48]: Thanks for your effort in improving JabRef user experience. Changes look good, except one small nitpick:
The message seems to be a bit too detailed. We could put the third sentence below almost every logger message...
Be aware that the Logger already provides extensive information about the class where the warning has risen etc.
I believe the first two sentences are sufficient about the port in use.

Comment (jakkarth) [reply src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java:48]: I appreciate the feedback! I wanted the message to try to cover both potential cases:

1. Some other application is already using that port, so we can't bind it
2. *JabRef* is already using that port, and the ping timed out even after increasing to 1s

If we remove the third sentence, we lose point number 2. I encountered this issue and the only clue I got was that JabRef couldn't bind the port, nothing about the ping failing. Without the third sentence, a future user who hits the timeout issue will face the same lack of clues that I did. Do you have a suggestion for how we could phrase the message to cover both points? Or do you think that, post change, this scenario is unlikely enough to be encountered that it's better to shorten the message at the expense of that information? I'm happy to remove it if you think that's the better course.

Comment (calixtus) [reply src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java:48]: Sentences are:
1. There was an error opening the configured network port {}.
2. Please ensure there isn't another application already using that port.
3. If you're sure an existing JabRef instance is running and using this port, and you see this message, please file a bug.

The meaning of the first part of sentence three is implicitly covered by the second. I expect the interested user who actually reads the log files to be clever enough to reach out to our support resources. ;-)

Please just remove sentence three...

Comment (calixtus) [reply src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java:48]: i think we should put that in the documentation for troubleshooting

Comment (jakkarth) [reply src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java]: Done :)

**Review by Siedlerchr — APPROVED** [review]

File: src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java (hunk 3 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/remote/server/RemoteListenerServerLifecycle.java]: Where in the documentation can I find it? I checked https://github.com/JabRef/user-documentation/pulls, however I don't find an open (or closed) PR.

**Review by koppor — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thank you very much for your first contribution @jakkarth 🥇  Hope you were not deterred by the "nitpicking" ;) We just want to make sure that messages are understandable for the end user.
