### PR TITLE
Refine error message in URLUtil::create

### LINKED ISSUE #12186: IllegalArgumentException: URI is not absolute
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-05--4705977 Linux 6.1.0-26-amd64 amd64  Java 21.0.5  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I've just been using global search. 

Unfortunately, I can't quite reproduce this issue, although I've had this exception a few times already. It appears to be related to when I use search, the entry list when a group is selected. Also, it seems to happen after JR has been running for a while.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.of(Unknown Source)
	at java.base/java.net.URI.toURL(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.importer.util.FileFieldParser.convert(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$3.computeValue(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.TableCell.updateItem(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.TableCell.indexChanged(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.TableRowSkinBase.updateCells(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.TableRowSkinBase.checkState(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.Control.computePrefHeight(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.prefHeight(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.layout.Region.prefHeight(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.resizeCell(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@23.0.1/javafx.stage.Stage.showAndWait(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.JabRefDialogService.showConfirmationDialogAndWait(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.search.GlobalSearchBar.lambda$initSearchModifierButtons$8(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.ToggleButton.setSelected(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.search.GlobalSearchBar.lambda$initSearchModifierButtons$14(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.SetListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.SetListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.ObservableSetWrapper.callObservers(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.ObservableSetWrapper.remove(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.SearchPreferences.setSearchFlag(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.search.GlobalSearchBar.lambda$initSearchModifierButtons$9(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.ToggleButton.fire(Unknown Source)
	at javafx.controls@23.0.1/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@23.0.1/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

### PR DESCRIPTION
**Pull request by jenilpatel264**
This PR closes #12186

Added comprehensive validation and exception handling to ensure robust URI parsing and conversion to a URL in the create method. This improves reliability and user feedback by explicitly handling malformed or incomplete URI inputs.

### Description
This PR enhances the create method to handle edge cases where the URI is malformed, incomplete, or improperly structured. Previously, certain invalid inputs could lead to unclear exceptions. This implementation improves error clarity and stability.

### Changes
File: src/main/java/org/jabref/logic/util/URLUtil.java

What: Enhanced the create method with multiple validation checks and detailed exception handling.

Why: To ensure that only valid, absolute URIs with proper scheme and host are converted to URLs and to prevent ambiguous or uncaught runtime exceptions.

#### Detailed Explanation
Validation Checks Added:
* Null or Empty Input:
If the input url is null or an empty string (after trimming), a MalformedURLException is thrown with an appropriate message.

* Absolute URI Check:
Ensures the parsed URI is absolute before attempting conversion to a URL.

* Scheme and Host Validation:
Ensures that both the scheme (e.g., http, https) and host are present in the URI.

* Improved Exception Handling:
URISyntaxException: Catches invalid URI syntax and wraps it in a MalformedURLException with a detailed message.

* IllegalArgumentException: Catches improper input such as illegal characters or encoding issues.

* NullPointerException: Safeguards against unexpected null components in the URI.

* Exception: Catches all other unforeseen issues during URI parsing or conversion.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [.] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required) 
- [.] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
please don't always open a new pr this creates noise for us, just push your change to your branch, the pr gets updated automatically

**Comment by koppor** [comment]
Tests are missing - see https://github.com/JabRef/jabref/pull/12800/files for example tests.

File: jablib/src/main/java/org/jabref/logic/util/URLUtil.java [hunk 1]
```diff
@@ -97,7 +97,27 @@ public static boolean isURL(String url) {
...
+            URI parsedUri = new URI(url.trim());
+            if (!parsedUri.isAbsolute()) {
+                throw new MalformedURLException("URI is not absolute: " + url);
+            }
+            if (parsedUri.getScheme() == null || parsedUri.getHost() == null) {
+                throw new MalformedURLException("URI must include both scheme and host: " + url);
+            }
+            return parsedUri.toURL();
+        } catch (URISyntaxException e) {
+            throw new MalformedURLException("Invalid  URI syntax: " + url + " | Error: " + e.getMessage());
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: It shis AI generated?

Please follow logging guidelines at https://devdocs.jabref.org/code-howtos/logging.html

Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: Ah, sorry, I overlooked that all of these are `throw`.

But neverheless, `MalformedURLException` should support nested exceptions, doesn't it?

Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: I would summarize all exceptions into one - with the same text - the exception as parameter

File: jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java [hunk 2]
```diff
@@ -87,4 +87,28 @@ void createUriShouldHandlePipeCharacter() {
...
+        } catch (URISyntaxException e) {
+            throw new MalformedURLException("Invalid  URI syntax: " + input + " | Error: " + e.getMessage());
+        } catch (IllegalArgumentException e) {
+            throw new MalformedURLException("Illegal argument in URI construction: " + input + " | Error: " + e.getMessage());
+        } catch (NullPointerException e) {
+            throw new MalformedURLException("Null value encountered during URI parsing: " + input);
+        } catch (Exception e) {
+            throw new MalformedURLException("Unexpected error while parsing URI: " + input + " | Error: " + e.getMessage());
+        }
+    }
```
Comment (calixtus) [inline jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: What is this?

Comment (jenilpatel264) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: This is test cases for reference.

Comment (calixtus) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: im missing assertThrows(MalformedURLException.class, () -> URLUtil.create(...))

Comment (calixtus) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: The current test is not testing anything. `input` is created in line 93 and is always not null and the assertEquals is testing the URI class.

**Comment by calixtus** [comment]
About the PR description: Do not put your code changes in there. Put it into the code. This is what the git diff in github is for.
Also mind the description for the checkboxes. Check what is applicable, mark as with / or . what is not applicable. Just checking everything is wrong. You did not change the documentation. You did not add screenshots.

File: jablib/src/main/java/org/jabref/logic/util/URLUtil.java [hunk 3]
```diff
@@ -97,7 +97,27 @@ public static boolean isURL(String url) {
      * @throws MalformedURLException if the URL is malformed and cannot be converted to a {@link URL}.
      */
     public static URL create(String url) throws MalformedURLException {
-        return createUri(url).toURL();
+        try {
+            if (url == null || url.trim().isEmpty()) {
+                throw new MalformedURLException("Provided URL is null or empty.");
+            }
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: put this before try

**Comment by jenilpatel264** [comment]
If I put . or /  then the cases will failed, so what is the solution for this.

File: jablib/src/main/java/org/jabref/logic/util/URLUtil.java [hunk 4]
```diff
@@ -97,7 +97,27 @@ public static boolean isURL(String url) {
...
+            return parsedUri.toURL();
+        } catch (URISyntaxException e) {
+            throw new MalformedURLException("Invalid  URI syntax: " + url + " | Error: " + e.getMessage());
+        } catch (IllegalArgumentException e) {
+            throw new MalformedURLException("Illegal argument in URI construction: " + url + " | Error: " + e.getMessage());
+        } catch (NullPointerException e) {
+            throw new MalformedURLException("Null value encountered during URI parsing: " + url);
+        } catch (Exception e) {
+            throw new MalformedURLException("Unexpected error while parsing URI: " + url + " | Error: " + e.getMessage());
+        }
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: Generic catching of "Exception" is not good, it may be also an OutOfMemoryException. This would have nothing to do with user input. Dont catch them.

Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/util/URLUtil.java]:
```suggestion
    if (url == null || url.trim().isEmpty()) {
        throw new IllegalArgumentException("URL must not be null or empty.");
    }

    try {
        URI parsedUri = new URI(url.trim());
        if (!parsedUri.isAbsolute()) {
            throw new MalformedURLException("URI is not absolute: " + url);
        }
        if (parsedUri.getScheme() == null || parsedUri.getHost() == null) {
            throw new MalformedURLException("URI must include both scheme and host: " + url);
        }
        return parsedUri.toURL();
    } catch (URISyntaxException | IllegalArgumentException e) {
        throw new MalformedURLException("Invalid URI: " + url + " | " + e.getMessage());
    }
```

**Review by calixtus — DISMISSED** [review]

File: jablib/src/main/java/org/jabref/logic/util/URLUtil.java (hunk 4 above)
Comment (jenilpatel264) [reply jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: Yes got it , I removed

File: jablib/src/main/java/org/jabref/logic/util/URLUtil.java (hunk 3 above)
Comment (jenilpatel264) [reply jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: sure

File: jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java [hunk 5]
```diff
@@ -1,14 +1,15 @@
...
+import java.net.URL;
 
 import org.jabref.logic.util.URLUtil;
 
 import org.junit.jupiter.api.Test;
 
-import static org.junit.jupiter.api.Assertions.assertEquals;
-import static org.junit.jupiter.api.Assertions.assertFalse;
-import static org.junit.jupiter.api.Assertions.assertTrue;
+import static org.junit.jupiter.api.Assertions.*;
```
[the remark this answers is not in the document]
Comment (calixtus) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: please fix your workspace setup:https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html#step-3-set-up-jabrefs-code-style

[the remark this answers is not in the document]
Comment (jenilpatel264) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: yes I did

[the remark this answers is not in the document]
Comment (koppor) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: > yes I did

Then, please optimize imports to fix this.

**Comment by koppor** [comment]
> If I put . or /  then the cases will failed, so what is the solution for this.

This is the challenge. If it is too hard, choose another issue please

File: jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java [hunk 6]
```diff
@@ -87,4 +88,64 @@ void createUriShouldHandlePipeCharacter() {
...
+    }
+
+    // malformed syntax
+    @Test
+    public void testMalformedSyntax() {
+        MalformedURLException exception = assertThrows(MalformedURLException.class, () -> {
+            URLUtil.create("http://[invalid-url]");
+        });
+        assertTrue(exception.getMessage().contains("Invalid  URI syntax"), " URI syntax error");
+    }
```
Comment (calixtus) [inline jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: The comments on the Tests can be removed, the name of the method is selfdescribing.
If you think that the name is not sufficient, you can use JUnit annotation `@DisplayName` to give them better names. But in general it is enough. Here it is enough imho.
The tests look good.

Comment (jenilpatel264) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: Yes I removed it

File: jablib/src/main/java/org/jabref/logic/util/URLUtil.java [hunk 7]
```diff
@@ -97,7 +97,25 @@ public static boolean isURL(String url) {
...
+                throw new MalformedURLException("URI must include both scheme and host: " + url);
+            }
+            return parsedUri.toURL();
+        } catch (URISyntaxException e) {
+            throw new MalformedURLException("Invalid  URI syntax: " + url + " | Error: " + e.getMessage());
+        } catch (IllegalArgumentException e) {
+            throw new MalformedURLException("Illegal argument in URI construction: " + url + " | Error: " + e.getMessage());
+        } catch (NullPointerException e) {
+            throw new MalformedURLException("Null value encountered during URI parsing: " + url);
+        }
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: This should be fixed by checking for url in the beginning of the method. can now be removed.

Comment (jenilpatel264) [reply jablib/src/main/java/org/jabref/logic/util/URLUtil.java]: yes , I removed this lines of code.

**Review by subhramit — DISMISSED** [review]

File: jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java (hunk 6 above)
Comment (subhramit) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: @jenilpatel264 what we meant was error messages on the tests, not code comments

**Comment by subhramit** [comment]
@jenilpatel264 please try to avoid using AI if you don't know what you are doing. It will not help you learn.

File: jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java [hunk 8]
```diff
@@ -87,4 +92,50 @@ void createUriShouldHandlePipeCharacter() {
         URI uri = URLUtil.createUri(input);
         assertEquals("http://example.com/test%7Cfile", uri.toString());
     }
+
+    @Test
+    public void validUrl() {
+        String input = "http://example.com";
+
+        Assertions.assertDoesNotThrow(() -> {
```
[the remark this answers is not in the document]
Comment (subhramit) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: this does make sense

File: jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java [hunk 9]
```diff
@@ -87,4 +92,49 @@ void createUriShouldHandlePipeCharacter() {
         URI uri = URLUtil.createUri(input);
         assertEquals("http://example.com/test%7Cfile", uri.toString());
     }
+
+    @Test
+    public void validUrl() throws MalformedURLException {
```
[the remark this answers is not in the document]
Comment (subhramit) [reply jablib/src/test/java/org/jabref/logic/net/URLUtilTest.java]: this also makes sense

**Review by subhramit — APPROVED** [review]

**Review by koppor — COMMENTED** [review]
I don't know if this really fixes the issue as when called `www.example.org`. there was another issue where the file field contained a URL without protocol...
