### PR TITLE
Fix failed test on Windows

### LINKED ISSUE #15537: Fix failing Windows tests
Our Windows CI tests are currently failing post the merge of https://github.com/JabRef/jabref/pull/15316
The report can be viewed at https://github.com/JabRef/jabref/actions/runs/24270384479/job/70874031816

The task is to fix these tests, and if there is intentional windows-specific handling involved in the logic, mark the tests enabled only on Windows.

For future, to catch this early during development in future, the Windows-based CI checks have been enabled in https://github.com/JabRef/jabref/pull/15530. The tests were initially disabled because Windows-specific test failures did not come up often, and the tests took a long time (~33min).

### PR DESCRIPTION
**Pull request by pluto-han**
### Related issues and pull requests

Closes #15537

### PR Description
Add linebreak unifier to method in `RelatedWorkInserterTest`.

### Steps to test
On Windows, run test `insertMatchedRelatedWorkAppendsToExistingUserSpecificCommentField` in `RelatedWorkInserterTest`, it should pass now.

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [/] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [/] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jablib/src/test/java/org/jabref/logic/relatedwork/RelatedWorkInserterTest.java [hunk 1]
```diff
@@ -58,7 +58,7 @@ void insertMatchedRelatedWorkAppendsToExistingUserSpecificCommentField() {
         List<RelatedWorkInsertionResult> insertionResults = inserter.insertMatchedRelatedWork(sourceEntry, List.of(matchResult), "koppor");
 
         assertInstanceOf(RelatedWorkInsertionResult.Inserted.class, insertionResults.getFirst());
-        assertEquals("[test]: blahblah" + OS.NEWLINE + OS.NEWLINE + "[LunaOstos_2024]: Colombia is a middle-income country with a population of approximately 50 million.",
+        assertEquals(StringUtil.unifyLineBreaks("[test]: blahblah".stripTrailing(), "\n") + "\n\n" + "[LunaOstos_2024]: Colombia is a middle-income country with a population of approximately 50 million.",
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/relatedwork/RelatedWorkInserterTest.java]: Not sure why double (!) changes

- Use `\n` instead of `OS.NEWLINE`
- Unify linebreaks at tests

I think, the first one is enough to do. 

If BOTH is needed, there should be a comment

**Review by koppor — DISMISSED** [review]

File: jablib/src/test/java/org/jabref/logic/relatedwork/RelatedWorkInserterTest.java (hunk 1 above)
Comment (subhramit) [reply jablib/src/test/java/org/jabref/logic/relatedwork/RelatedWorkInserterTest.java]: I think the confusion arises from a prior discussion https://github.com/JabRef/jabref/pull/15316#discussion_r2943267849

Comment (pluto-han) [reply jablib/src/test/java/org/jabref/logic/relatedwork/RelatedWorkInserterTest.java]: Yes. In https://github.com/JabRef/jabref/pull/15316#discussion_r2943267849, my thought is that we should first normalize the linebreak at the end of the sentence, before adding new linebreaks, so I use `unifyLineBreaks`.

In this test, I think we don't need `unifyLineBreaks` because the sentences contain no linebreaks. But I am not sure if we should also remove `unifyLineBreaks` in `RelatedWorkInserter`.

**Comment by calixtus** [comment]
Move fast, break things, and fix them later.

**Review by calixtus — DISMISSED** [review]

**Comment by subhramit** [comment]
> You ticked that you modified `CHANGELOG.md`, but no new entry was found there.
> 
> If you made changes that are visible to the user, please add a brief description along with the issue number to the `CHANGELOG.md` file. If you did not, please replace the cross (`[x]`) by a slash (`[/]`) to indicate that no `CHANGELOG.md` entry is necessary. More details can be found in our [Developer Documentation about the changelog](https://devdocs.jabref.org/decisions/0007-human-readable-changelog.html).

false alarm

**Comment by subhramit** [comment]
We don't normalize in tests, hence the commit https://github.com/JabRef/jabref/pull/15538/commits/13373033b1a2134fca58d2f98c6a5697add2f474

Edit (for addition to original context) - it might be the case that JavaFX normalizes to `\n` as pointed out in https://github.com/JabRef/jabref/pull/15316#discussion_r2943267849, but there is no harm in keeping the backend logic more general/independent.

**Review by subhramit — APPROVED** [review]

**Comment by pluto-han** [comment]
Sorry for being inactive, just finished the last exam.  

Should I make a follow-up PR to fix problems in https://github.com/JabRef/jabref/pull/15538#discussion_r3075174582?

**Comment by subhramit** [comment]
> We don't normalize in tests, hence the commit [1337303](https://github.com/JabRef/jabref/commit/13373033b1a2134fca58d2f98c6a5697add2f474)
> 
> Edit (for addition to original context) - it might be the case that JavaFX normalizes to `\n` as pointed out in [#15316 (comment)](https://github.com/JabRef/jabref/pull/15316#discussion_r2943267849), but there is no harm in keeping the backend logic more general/independent.

@pluto-han I think the above^ justifies this PR as the fix? Do you have anything else in mind?

**Comment by pluto-han** [comment]
> I think the above^ justifies this PR as the fix? 

Yep I think then we can keep this code.
