### PR TITLE
Fix #3235: remote metadata is updated instead of delete + insert

### LINKED ISSUE #3235: Weird behaviour in PostgreSQL database
JabRef version JabRef-4.0-dev--snapshot--2017-09-20--master--b0489d5b3 on  Windows 10 | Ubuntu 16.04

Steps to reproduce:

1. Connect to a shared database
2. Tick automatically save the library to 
3.  Connect

On a database viewer I was monitoring what was done on the database.
The weird thing I saw was, that when Jabref started to connect all the metadata table was deleted. The first thing restored was the databaseType key. Then gradually the program restored back all the information. This is independent if the file I save to, exists or is a new one.  This does not happen to the ENTRY and FIELD tables. It happens both in WIndows and Ubuntu 16.04.
Since db connection is slow at initializing, if it crashes in the middle metadata information can be lost (I have lost the group information once but I cannot repeat that). Maybe this is what had happened.

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fix for https://github.com/JabRef/jabref/issues/3235. Instead of completely deleting and refiling the metadata table, now an `update` is preformed. I've never touched the SQL code before and didn't tested it, so I appreciate feedback from someone with more experience on this part of the code.

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/main/java/org/jabref/shared/DBMSProcessor.java [hunk 1]
```diff
@@ -527,25 +527,41 @@ public void removeEntry(BibEntry bibEntry) {
...
+                        insertStatement.setString(1, metaEntry.getKey());
+                        insertStatement.setString(2, metaEntry.getValue());
+                        insertStatement.executeUpdate();
+                    } catch (SQLException e) {
+                            LOGGER.error("SQL Error: ", e);
+                    }                    
+                }
             } catch (SQLException e) {
-                LOGGER.error("SQL Error: ", e);
+                    LOGGER.error("SQL Error: ", e);
```
Comment (lenhard) [inline src/main/java/org/jabref/shared/DBMSProcessor.java]: Is there an extra level of indentation here?

Comment (tobiasdiez) [reply src/main/java/org/jabref/shared/DBMSProcessor.java]: Yes, there was an additional indent (I'm using the github editor for these edits since I don't have a proper IDE at the moment).

**Comment by lenhard** [comment]
Since the issue has now already been closed, I'll merge this directly.
