### PR TITLE
ScienceDirect fulltext fetcher missing scidir-pdf link

### LINKED ISSUE #12161: Obtain fulltext from sciencedirect
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

22H2

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When trying to obtain the fulltext from sciencedirect, it does not find it. For example taking this DOI: https://doi.org/10.1016/j.ndteint.2023.102990

I am able to add it to the library, but the fulltext does not resolve, although it is clearly available.

### Appendix

Logs:
2024-11-07 16:22:10 [JavaFX Application Thread] org.jabref.gui.JabRefDialogService.notify()
INFO: Deleted 1 entry(ies)
2024-11-07 16:22:43 [JavaFX Application Thread] org.jabref.gui.JabRefDialogService.notify()
INFO: Looking for full text document...
2024-11-07 16:22:43 [JabRef CachedThreadPool] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
ERROR: Invalid cookie for https://linkinghub.elsevier.com/retrieve/pii/S0963869523002050: 
2024-11-07 16:22:44 [JabRef CachedThreadPool] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
ERROR: Invalid cookie for https://www.sciencedirect.com/science/article/pii/S0963869523002050: 
2024-11-07 16:22:45 [JabRef CachedThreadPool] org.jabref.logic.importer.fetcher.SemanticScholar.findFullText()
INFO: Fulltext PDF found @ SemanticScholar. Link: https://doi.org/10.1016/j.ndteint.2023.102990
2024-11-07 16:22:45 [JavaFX Application Thread] org.jabref.gui.JabRefDialogService.notify()
INFO: No full text document found for entry Cosarinsky2024.

### PR DESCRIPTION
**Pull request by faneeshh**
### Related issues and pull requests

Closes #12161 

### PR Description

The Elsevier API response for a ScienceDirect article can include a direct PDF link alongside the article landing page link (scidir) in its coredata.link array. The fetcher was only reading scidir and discarding scidir-pdf, so it always fell through to Jsoup scraping the article page which frequently fails. This fix reads scidir-pdf when present and returns it directly which skips the scrape entirely. 

### Steps to test

The scidir-pdf link only appears for institutional Elsevier API keys or certain open access articles so manual end to end testing requires an institutional key but the fix could easily be tested by the new unit test though which mocks the API response with a fixture containing all three link types and asserts the PDF URL is returned directly.

`./gradlew :jablib:fetcherTest --tests "org.jabref.logic.importer.fetcher.ScienceDirectTest.findsPdfDirectlyWhenSciDirPdfPresent"`

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [/] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [x] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jablib/src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java [hunk 1]
```diff
@@ -130,8 +134,11 @@ public TrustLevel getTrustLevel() {
         return TrustLevel.PUBLISHER;
     }
 
-    private String getUrlByDoi(String doi) throws UnirestException {
+    private record DoiResolution(String url, boolean isPdfDirect) { }
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java]: I really dont like this tuple-results. Needs special knowledge to be used on the callers side. A blank String could also be misinterpreted.
How about a sealed interface with encoded types? Modern Java allows data-oriented patterns.
```java
sealed interface DoiResolution permits Pdf, ScienceDirect, NotFound {}
record Pdf(String url) implements DoiResolution {}
record ScienceDirect(String url) implements DoiResolution {}
record NotFound() implements DoiResolution {}
```

Comment (faneeshh) [reply jablib/src/main/java/org/jabref/logic/importer/fetcher/ScienceDirect.java]: Hmm fair enough. Should be fine now.
