### PR TITLE
Don't register any database changes to the indexer while dropping a file

### LINKED ISSUE #8182: PDF indexing should be paused when adding a file via drag and drop
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Configure explicit directory for library (refs https://github.com/JabRef/jabref/issues/8179)
2. Drag a PDF file from `c:\temp` 
3. Drop file at an existing entry

Expected behavior:

File is moved and renamed

Current behavior:

At first attempt, an IOException is risen:

```
java.nio.file.FileSystemException: C:\TEMP\xy.pdf -> C:\TEMP\FMC - FMC_ an Approach Towards Architecture Centric System Development.pdf: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird
```

Then, the user can detach the file from the entry and try again. Then, it works.

### Solution propsal

Stop PDF indexing during drop handling. Start indexing again after drop (includes file move!!) is finished

### PR DESCRIPTION
**Pull request by btut**
There was a problem that involved the Indexer and Drag&Drop operations while having auto-file-move/rename enabled.

When dropping a File onto an entry, JabRef links that file to the entry and moves and renames the files according to the set preferences. It was possible for this to happen while the PDFIndexer was running. This could lead to:
- The pdf indexer not finding the file because it was invoked before the path changed
- The move/rename operation to fail because the indexer blocked the PDF

This was solved by not allowing for any files to be added to the indexer during drag&drop operations.

Fixes #8182.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/maintable/MainTable.java [hunk 1]
```diff
@@ -375,20 +381,30 @@ private void handleOnDragDropped(TableRow<BibEntryTableViewModel> row, BibEntryT
...
+                    try {
+                        BibEntry entry = target.getEntry();
+                        switch (event.getTransferMode()) {
+                            case LINK -> {
+                                LOGGER.debug("Mode LINK"); // shift on win or no modifier
+                                importHandler.getLinker().addFilesToEntry(entry, files);
+                            }
+                            case MOVE -> {
+                                LOGGER.debug("Mode MOVE"); // alt on win
+                                libraryTab.getIndexingTaskManager().setBlockingNewTasks(true);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTable.java:393]: Is there a reason why this blocking shouldn't be added directly to the `importHandler` (or linker)?

File: src/main/java/org/jabref/gui/maintable/MainTable.java [hunk 2]
```diff
@@ -375,20 +381,30 @@ private void handleOnDragDropped(TableRow<BibEntryTableViewModel> row, BibEntryT
...
+                                importHandler.getLinker().moveFilesToFileDirAndAddToEntry(entry, files);
+                                libraryTab.getIndexingTaskManager().setBlockingNewTasks(false);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTable.java:395]: Instead of this `setBlockingNewTasks(true/false)` pattern, I would suggest to use the try resource solution: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html, i.e.
```
try (libraryTab.getIndexingTaskManager().blockingNewTasks()) {
   importHandler.getLinker().moveFilesToFileDirAndAddToEntry(entry, files);
}
```
In this way, you make sure that the `setBlockingNewTasks(false)` is always executed, even in case there is a (runtime) exception.

File: src/main/java/org/jabref/gui/maintable/MainTable.java (hunk 1 above)
Comment (btut) [reply src/main/java/org/jabref/gui/maintable/MainTable.java:393]: Not all users of importHandler have access to the IndexingTaskManager unfortunately.

File: src/main/java/org/jabref/gui/maintable/MainTable.java (hunk 2 above)
Comment (btut) [reply src/main/java/org/jabref/gui/maintable/MainTable.java:395]: So if I understand that right I would need to make the blocking() method of IndexingTaskManager return a 'closable', right? I could define that as a lambda that resets the flag.
Or is there a better way you are hinting at?

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/maintable/MainTable.java:395]: That sounds good!

File: src/main/java/org/jabref/gui/maintable/MainTable.java (hunk 1 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/maintable/MainTable.java:393]: Mhh, do you have an example where this occurs? The whole linker/import handler stuff arose from the fact that there were many very similarly-looking code blocks scattered around the code base, that all handled imports in a similar but same way. Was a huge headache, so I would like not to introduce special handling in certain situations again.

File: src/main/java/org/jabref/gui/maintable/MainTable.java (hunk 2 above)
Comment (btut) [reply src/main/java/org/jabref/gui/maintable/MainTable.java]: Tried it and it was easy enough - so I think I got what you meant. Thanks for the hint!

File: src/main/java/org/jabref/gui/maintable/MainTable.java (hunk 1 above)
Comment (btut) [reply src/main/java/org/jabref/gui/maintable/MainTable.java]: Oh, that sounds like a good reason to do it directly in the import handler.
The PreviewPanel was my concern, but I passed it along and made it work.

**Review by tobiasdiez — APPROVED** [review]
Looks good to me, but I didn't deep look so would prefer if someone else also looks over it.

Thanks for your continued work on making the indexing better and better!

File: src/main/java/org/jabref/gui/entryeditor/EntryEditor.java [hunk 3]
```diff
@@ -143,11 +143,11 @@ public EntryEditor(LibraryTab libraryTab, ExternalFileTypes externalFileTypes) {
                 switch (event.getTransferMode()) {
                     case COPY -> {
                         LOGGER.debug("Mode COPY");
-                        fileLinker.copyFilesToFileDirAndAddToEntry(entry, files);
+                        fileLinker.copyFilesToFileDirAndAddToEntry(entry, files, libraryTab.getIndexingTaskManager());
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/entryeditor/EntryEditor.java:146]: Can you somehow inverse the dependency on libraryTab here (maybe injecting it in the constructor) ?

File: src/main/java/org/jabref/gui/maintable/MainTable.java [hunk 4]
```diff
@@ -383,11 +388,11 @@ private void handleOnDragDropped(TableRow<BibEntryTableViewModel> row, BibEntryT
                         }
                         case MOVE -> {
                             LOGGER.debug("Mode MOVE"); // alt on win
-                            importHandler.getLinker().moveFilesToFileDirAndAddToEntry(entry, files);
+                            importHandler.getLinker().moveFilesToFileDirAndAddToEntry(entry, files, libraryTab.getIndexingTaskManager());
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/maintable/MainTable.java:391]: IoC here too?

**Review by calixtus — CHANGES_REQUESTED** [review]
Two comments.

File: src/main/java/org/jabref/gui/maintable/MainTable.java (hunk 4 above)
Comment (btut) [reply src/main/java/org/jabref/gui/maintable/MainTable.java:391]: Having the IndexingTaskManager in ImportHandler would require a lot of refactoring and passing along the IndexingTaskManager in many files. I would really like to avoid that.

Comment (calixtus) [reply src/main/java/org/jabref/gui/maintable/MainTable.java:391]: Ok, I agree, it's probably better to fix the bug now.

But sooner or later we have to deal with that. 😅

**Review by calixtus — APPROVED** [review]

**Comment by btut** [comment]
Great! Before merging I would like to wait for @koppor to confirm the issue is fixed for him as well (as he is on windows).

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
I'm going to merge this now, as it's good to have it in the release

**Comment by btut** [comment]
Certainly won't hurt. If @koppor still has an isse we can open a new Issue.
