### PR TITLE
Fix del/copy/paste key trigger main table action in search bar

### LINKED ISSUE #3067: Del key in search box deletes entry
JabRef 4.0-dev--snapshot--2017-08-02--master--63414b030
Windows 10 10.0 amd64 
Java 1.8.0_66
Steps to reproduce:

1. Type a known author in the search box
2. When the first suggestion comes up, hit enter
3. Now press shift+home to select the entire content of the search box and press del
4. The first bib entry is removed (in addition to the contents of the search box)

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #3067, same reason and fix as in entry editor

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/main/java/org/jabref/gui/search/GlobalSearchBar.java [hunk 1]
```diff
@@ -154,38 +156,31 @@ public void actionPerformed(ActionEvent e) {
 
         EasyBind.subscribe(searchField.textProperty(), searchText -> performSearch());
 
-        /*
-        String endSearch = "endSearch";
-        searchField.getInputMap().put(Globals.getKeyPrefs().getKey(KeyBinding.CLEAR_SEARCH), endSearch);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: Do these keyboard shortcuts now work as expected?
Would be nice if they do otherwise I would prefer to keep the commented-out code.

Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: Ah I thought the commented code ws just obsolete. I will see if I can fix this issue, too

Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: I could not get them to work, so I added a TODO. This also depends on #3076
