### PR TITLE
Fix SSLHandshake Exception by using bypass

### LINKED ISSUE #7616: SSLHandshakeException
JabRef 5.3--2021-03-29--2948e6d
Linux 5.11.11-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 16+8

I asked an entry to download the file https://www.serbski-institut.de/os/dnlarchiv/Kleine_Reihe_27_web.2217.pdf and got this error message.

for SSL certificate issues, I would suggets allow the user to add an exception, like a browser would do?

<details>
  <summary>Log File</summary>
  
  ```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref@5.3.229/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	at org.jabref@5.3.229/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	at org.jabref@5.3.229/org.jabref.gui.externalfiles.FileDownloadTask.call(Unknown Source)
	at org.jabref@5.3.229/org.jabref.gui.externalfiles.FileDownloadTask.call(Unknown Source)
	at org.jabref@5.3.229/org.jabref.gui.util.BackgroundTask$3.call(Unknown Source)
	at org.jabref@5.3.229/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.3.229/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 31 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 36 more

  ```
</details>

### PR DESCRIPTION
**Pull request by Ryyyc**
Fixes #7616 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

File download path: https://www.serbski-institut.de/os/dnlarchiv/Kleine_Reihe_27_web.2217.pdf

<br>

A valid authentication path cannot be found from the site where the downloaded file is located, prompting the user with the option of whether to continue the download.
warning

<br>

The user chooses to cancel the download.
canceled_tip

<br>

The user chooses to download anyway.
download

### CODE REVIEW

**Comment by Siedlerchr** [comment]
You can ignore the fetcher and the mac test. But please have a look at the Checkstyle test. Either click on details at the failing  or you can go to the files changes tab to see the Reviewdog comments

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java [hunk 1]
```diff
@@ -463,7 +470,29 @@ public void download() {
         }
     }
 
+    public boolean checkSSLHandshake(URLDownload urlDownload) {
+        try {
+            urlDownload.canBeReached();
+        } catch (kong.unirest.UnirestException ex) {
+            if (ex.getCause() instanceof javax.net.ssl.SSLHandshakeException) {
+                if (dialogService.showConfirmationDialogAndWait(Localization.lang("Download file"),
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java:478]: Do we really need to ask the user, or should we just bypass ssl verification? For example, firefox downloads the linked pdf without any prompt.

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java [hunk 2]
```diff
@@ -463,7 +470,29 @@ public void download() {
...
+                        Localization.lang("Unable to find valid certification path to requested target(%0), download anyway?",
+                                urlDownload.getSource().toString()))) {
+                    URLDownload.bypassSSLVerification();
+                    return true;
+                } else {
+                    dialogService.showInformationDialogAndWait(Localization.lang("Download file"),
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java:484]: I would use `notify` here, so that the user doesn't need to click "ok" again in the second dialog.

Comment (Ryyyc) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java:484]: Great, I agree with this idea!

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java (hunk 1 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java:478]: I think that bypassing SSL verification should let users know. 
We can add an option in the preferences to allow users to select all downloads to bypass the verification. The advantage of this feature that the user does not need to click on the trusted site every time. The disadvantage is that the code changes may be a bit big.

But I found that JabRef uses `URLDownload.bypassSSLVerification()` directly in some places, such as org.jabref.logic.importer.fetcher.IEEE#getURLForQuery, line 253.

**Comment by Ryyyc** [comment]
The user chooses to cancel the download, use `Notify` instead of `InformationDialog` to prompt the user.

canceled_tip2

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java:478]: I think it's okay to show a dialog here. Should not happen that often.

File: src/main/java/org/jabref/logic/net/URLDownload.java [hunk 3]
```diff
@@ -132,6 +133,20 @@ public void checkServerTrusted(X509Certificate[] chain, String authType) {
         }
     }
 
+    /**
+     *
+     * @param sf trust manager
+     * @param v host verifier
+     */
+    public static void setSSLVerification(SSLSocketFactory sf, HostnameVerifier v) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/net/URLDownload.java:141]:
```suggestion
    public static void setSSLVerification(SSLSocketFactory socketFactory, HostnameVerifier verifier) {
```
Please no single character abbreviations as variable names

**Comment by Siedlerchr** [comment]
Just a minor improvement for the variable naming, otherwise lgtm!

**Comment by Ryyyc** [comment]
@Siedlerchr  @tobiasdiez  Thank you so much for your suggestions and help!

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
We have to thiank you for your contribution @Ryyyc !
