### PR TITLE
Fixes #8787 Decode doi contains masked characters

### LINKED ISSUE #8787: Exception for DOI search in case DOI contains masked characters
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Similar issue to #8786 in case of a DOI search (masked underscore) in DOI.

### Appendix

...
<details>

<summary>Log File</summary>

```
org.jabref.logic.importer.FetcherException: No DOI data exists
	at org.jabref@5.6.60000/org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.mergeentries.FetchAndMergeEntry.lambda$fetchAndMerge$0(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: https://doi.org/10.18726/2018%7B%5Ctextunderscore%7D3
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.net.URLDownload.asString(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.net.URLDownload.asString(Unknown Source)
	... 11 more
Caused by: java.io.FileNotFoundException: https://doi.org/10.18726/2018%7B%5Ctextunderscore%7D3
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	... 13 more
```

</details>

### PR DESCRIPTION
**Pull request by fly-ing-fish**
Fixes #8787

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/cleanup/DoiCleanup.java [hunk 1]
```diff
@@ -14,23 +16,57 @@
...
+ * from
+ * note,
+ * url
+ * or
+ * ee
+ * field
+ * to
+ * the
+ * doi
+ * field.
```
Comment (claell) [inline src/main/java/org/jabref/logic/cleanup/DoiCleanup.java:39]: Something seems to have gone wrong here 😃

Comment (claell) [reply src/main/java/org/jabref/logic/cleanup/DoiCleanup.java:39]: (apparently on most or all comments)

Comment (fly-ing-fish) [reply src/main/java/org/jabref/logic/cleanup/DoiCleanup.java]: The problem above is because of the mistake while configuring format file :relieved: . Thanks for pointing that and the format should be correct now.

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/cleanup/DoiCleanup.java]: Sse here for the codestyle: https://github.com/JabRef/jabref/tree/main/config
The exceptions seem also to be wrapped unnecessarily

**Comment by Siedlerchr** [comment]
```
> MainArchitectureTests > doNotUseLogicInModel FAILED
    java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'no classes that reside in a package 'org.jabref.model..' and are not annotated with @AllowedToUseLogic should depend on classes that reside in a package 'org.jabref.logic..'' was violated (2 times):
    Method <org.jabref.model.entry.identifier.DOI.parse(java.lang.String)> calls constructor <org.jabref.logic.layout.format.LatexToUnicodeFormatter.<init>()> in (DOI.java:165)
    Method <org.jabref.model.entry.identifier.DOI.parse(java.lang.String)> calls method <org.jabref.logic.layout.format.LatexToUnicodeFormatter.format(java.lang.String)> in (DOI.java:168)
        at com.tngt


```

**Comment by fly-ing-fish** [comment]
Seems that it needs other place to use `formatter.format()` to format the gotten doi rather than in `org.jabref.model.entry.identifier.DOI.parse` . But how to integrate this into `DOI.parse` method like mentioned before if formatter can't be used in model? 
image

**Comment by Siedlerchr** [comment]
I've flagged this as devcall, we need to discuss this in more detail in our team from an architecture perspective

**Comment by fly-ing-fish** [comment]
> I've flagged this as devcall, we need to discuss this in more detail in our team from an architecture perspective

Got it. Thanks for your help and support! 🌺🌺

**Comment by koppor** [comment]
DevCall Decision: We allow to use logic  (see comment)

@fly-ing-fish Thank you for your contribution to JabRef!
