### PR TITLE
Fix the representation of season in Biblatex date field.

### LINKED ISSUE #12437: BibLaTeX seasons cause exception on import and export
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 11 24H2 / JabRef 6.0-alpha.65

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Import an entry with date = {1991-21}

### Appendix

BibLaTeX allows seasons following ISO 8601, which are encoded by using 21–24 in the month field.

java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 21

### PR DESCRIPTION
**Pull request by urlyy**
Fixes #12437

### Description
When adding an entry like `@Article{Article, date = {2025-21} }`, the value 21 is interpreted as spring and added to the `yeardivision` entry field, rather than being treated as an out-of-range month and throwing an exception.

For reference:
image

### Demonstration
image

### Existing problems
- Should I use `YearDivision` or `Season` as the class name? The `BibLaTeX` documentation uses `YearDivision`, but it seems that `YearDivision` might also include some other values.
image
- Season does not require a `shortName`, is the `getJabRefFormat` method still necessary?

### TODO
Since I am a beginner in bibliography management and not certain whether my approach is correct, I have only implemented it preliminarily. If you think it is acceptable, I will proceed to finish the following TODO items:
- The handling for the format 2002-21 has been implemented, but the handling for the format 2002-21/2002-23 has not yet been implemented.
image
- Remove the redundant parts in the `Season` class.
- Improve the basic functions of the `Date` class, such as `toString`, `equals`, and `hashCode`

### Mandatory checks
- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/model/entry/Season.java [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+        this.number = number;
+    }
+
+    /**
+     * Find season by number.
+     * If the number is not in the valid range, then an empty Optional is returned.
+     *
+     * @param number 21-24 is valid
+     */
+    public static Optional<Season> getSeasonByNumber(int number) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/model/entry/Season.java:34]: I would like to see tome tests for the whole Season class as well

**Comment by Siedlerchr** [comment]
Very good work! I would like to see some more tests,  but otherwise on the first look it does a good first impression.

File: src/main/java/org/jabref/model/entry/Date.java [hunk 2]
```diff
@@ -347,6 +404,12 @@ public boolean equals(Object o) {
     @Override
     public String toString() {
         String formattedDate = date.toString();
+        if (season != null) {
+            return "Date{" +
+                    "date=" + formattedDate + ", " +
+                    "season=" + season +
+                    '}';
+        }
```
Comment (koppor) [inline src/main/java/org/jabref/model/entry/Date.java:412]: Why a different format then the others?

Isn't there a compact form (similar to ` DateTimeFormatter.ISO_DATE_TIME.format` or other results here?)

Action point: Either use a compact form or add a Java comment that there is no compact form

**Review by koppor — DISMISSED** [review]
Some minor comments.

Please also add a CHANGELOG.md entry

File: src/main/java/org/jabref/model/entry/Date.java [hunk 3]
```diff
@@ -317,6 +366,13 @@ public Optional<Month> getMonth() {
         return get(ChronoField.MONTH_OF_YEAR).flatMap(Month::getMonthByNumber);
     }
 
+    public Optional<Season> getSeason() {
+        if (season == null) {
+            return Optional.empty();
+        }
+        return Optional.of(season);
```
[the remark this answers is not in the document]
Comment (urlyy) [reply src/main/java/org/jabref/model/entry/Date.java]: done

File: src/main/java/org/jabref/model/entry/Date.java (hunk 2 above)
Comment (urlyy) [reply src/main/java/org/jabref/model/entry/Date.java]: The Date standard library does not have any API for handling seasons, so here is no compact form.
I add a Java comment .

**Review by Siedlerchr — APPROVED** [review]
