### PR TITLE
Fix exclude consistency fields 13131

### LINKED ISSUE #13131: Exclude certain fields from Consistency check
JabRef can check for consistency of BibEntries. For the GUI, it is described at https://docs.jabref.org/finding-sorting-and-cleaning-entries/checkconsistency.

This check returns too much inconsistencies. For instance, [comments on entries](https://docs.jabref.org/finding-sorting-and-cleaning-entries/comment-on-an-entry) should not be checked.

## Task

1. Introduce FILTERED_FIELDS at `org.jabref.logic.quality.consistency.BibliographyConsistencyCheck`. It should contain:
    - all fields of org.jabref.model.entry.field.StandardField#AUTOMATIC_FIELDS
    - org.jabref.model.entry.field.StandardField#COMMENT
    - org.jabref.model.entry.field.StandardField#CROSSREF
    - org.jabref.model.entry.field.StandardField#CITES
    - org.jabref.model.entry.field.StandardField#PDF
    - org.jabref.model.entry.field.StandardField#REVIEW
    - org.jabref.model.entry.field.StandardField#SORTKEY
    - org.jabref.model.entry.field.StandardField#SORTNAME
    - org.jabref.model.entry.field.StandardField#TYPE
    - org.jabref.model.entry.field.StandardField#XREF
    - org.jabref.model.entry.field.StandardField#GROUPS
1. Modify `org.jabref.logic.quality.consistency.BibliographyConsistencyCheck#collectEntriesIntoMaps` to filter `entry.getField()` according to FILTERED_FIELDS . Moreover, It should remove all `instance of org.jabref.model.entry.field.SpecialField` and all `instanceof org.jabref.model.entry.field.UserSpecificCommentField`
2. Create tests org.jabref.logic.quality.consistency.BibliographyConsistencyCheckTest

### PR DESCRIPTION
**Pull request by lawmeyian**
Closes #13131

This PR modifies the BibliographyConsistencyCheck to exclude specific fields from consistency checks. Fields such as COMMENT, CROSSREF, and AUTOMATIC_FIELDS, along with any SpecialField or UserSpecificCommentField, are now filtered out to avoid false positives during consistency validation. This improves the relevance of reported issues and aligns the behavior with user expectations.

### Steps to test

1. Open JabRef with a .bib file containing entries with fields such as comment, pdf, sortkey, groups, etc.
2. Go to Quality > Check integrity or use the consistency check dialog.
3. Observe that these excluded fields no longer trigger consistency warnings.
4. Add a custom field not on the exclusion list and verify it is still flagged.
5. Run unit tests in BibliographyConsistencyCheckTest — especially:
      -       filteredFieldsAreIgnored
      -       nonFilteredFieldDifferenceIsDetected
No UI changes were made, so testing is limited to data checks and developer view.

### Mandatory checks
- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java [hunk 1]
```diff
@@ -8,17 +8,62 @@
 import java.util.Map;
 import java.util.SequencedCollection;
 import java.util.Set;
+import java.util.stream.Collectors;
+import java.util.stream.Stream;
 import java.util.function.BiConsumer;
 
+
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java:13]: Checkstyle

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java [hunk 2]
```diff
@@ -8,17 +8,62 @@
...
 public class BibliographyConsistencyCheck {
 
+    // ----------------------------------------------------------------
+    // Fields that we do *not* want to check for consistency:
+    //   – every field in StandardField.AUTOMATIC_FIELDS
+    //   – COMMENT, CROSSREF, CITES, PDF, REVIEW, SORTKEY, SORTNAME, TYPE, XREF, GROUPS
+    //   – plus any SpecialField or UserSpecificCommentField (filtered at runtime)
+    // ----------------------------------------------------------------
+    private static final Set<Field> FILTERED_FIELDS = Stream
+            // start with JabRef’s built‐in AUTOMATIC_FIELDS set
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: Remove this comment, code is self-explanatory

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java [hunk 3]
```diff
@@ -8,17 +8,62 @@
...
 import org.jabref.model.entry.BibEntry;
 import org.jabref.model.entry.field.Field;
+import org.jabref.model.entry.field.SpecialField;
+import org.jabref.model.entry.field.StandardField;
+import org.jabref.model.entry.field.UserSpecificCommentField;
 import org.jabref.model.entry.types.EntryType;
 
 public class BibliographyConsistencyCheck {
 
+    // ----------------------------------------------------------------
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: Use proper Java doc, keep comment style

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java [hunk 4]
```diff
@@ -8,17 +8,62 @@
...
+            .collect(Collectors.toSet());
+
+    /**
+     * Drop any field we don’t want to check.
+     */
+    private static Set<Field> filterFields(Collection<Field> fields) {
+        return fields.stream()
+                     .filter(f -> !FILTERED_FIELDS.contains(f))
+                     .filter(f -> !(f instanceof SpecialField))
+                     .filter(f -> !(f instanceof UserSpecificCommentField))
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: We avoid abbreviations
```suggestion
                     .filter(field -> !FILTERED_FIELDS.contains(field))
                     .filter(field -> !(field instanceof SpecialField))
                     .filter(field -> !(field instanceof UserSpecificCommentField))
```

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java [hunk 5]
```diff
@@ -8,17 +8,62 @@
...
+                            StandardField.XREF,
+                            StandardField.GROUPS
+                    )
+            )
+            .collect(Collectors.toSet());
+
+    /**
+     * Drop any field we don’t want to check.
+     */
+    private static Set<Field> filterFields(Collection<Field> fields) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: Nitpick: Can you use a better method name, hinting at what we are filtering against? "filterFIelds" is a bit generic. Lets consider filterXFields or removeXFields - think what one word can "X" be, based on the logic?
If no such crisp word is possible, you can ignore this suggestion.

Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: Also, we can be more specific here wrt the parameter
```suggestion
    private static Set<Field> filterFields(SequencedSet<Field> fields) {
```

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java [hunk 6]
```diff
@@ -102,4 +106,43 @@ void checkLibraryWithoutIssues(@TempDir Path tempDir) {
...
+                .withField(StandardField.PDF, "other.pdf");
+
+        var result = new BibliographyConsistencyCheck().check(List.of(a, b));
+
+        // Since all differences are in filtered fields, there should be no entries reported:
+        assertTrue(result.entryTypeToResultMap().isEmpty(),
+                "Differences only in filtered fields must be ignored");
+    }
+
+    @SuppressWarnings("checkstyle:RegexpMultiline")
```
Comment (subhramit) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: Do not suppress checkstyle warnings without having a good reason to do so.

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java [hunk 7]
```diff
@@ -102,4 +106,43 @@ void checkLibraryWithoutIssues(@TempDir Path tempDir) {
...
+        BibEntry a = new BibEntry(StandardEntryType.Misc, "a")
+                .withField(StandardField.COMMENT, "note")
+                .withField(StandardField.PDF, "file.pdf")
+                .withField(new UserSpecificCommentField("XYZ"), "foo")
+                .withField(SpecialField.PRIORITY, "high");
+        BibEntry b = new BibEntry(StandardEntryType.Misc, "b")
+                .withField(StandardField.COMMENT, "another note")
+                .withField(StandardField.PDF, "other.pdf");
+
+        var result = new BibliographyConsistencyCheck().check(List.of(a, b));
```
Comment (subhramit) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: Please don't use `var`. At JabRef, we prefer strict types.
Also, did the compiler not complain here? You sent one argument instead of two, so the unit test is failing. Did you run the test before filing the PR?

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java [hunk 8]
```diff
@@ -102,4 +106,43 @@ void checkLibraryWithoutIssues(@TempDir Path tempDir) {
...
+    void nonFilteredFieldDifferenceIsReported() {
+        // Two MISC entries differing in AUTHOR (not filtered)
+        BibEntry withAuthor = new BibEntry(StandardEntryType.Misc, "1")
+                .withField(StandardField.AUTHOR, "Knuth");
+        BibEntry withoutAuthor = new BibEntry(StandardEntryType.Misc, "2");
+
+        var result = new BibliographyConsistencyCheck().check(List.of(withAuthor, withoutAuthor));
+
+        // AUTHOR should be reported as a unique field
+        var typeResult = result.entryTypeToResultMap().get(StandardEntryType.Misc);
```
Comment (subhramit) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: Similar comments regarding `var` and number of arguments here as https://github.com/JabRef/jabref/pull/13305/files#r2140865139.

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java (hunk 6 above)
Comment (lawmeyian) [reply jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: Hi subhramit, 
thank you for your advice. I will fix it.

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java (hunk 2 above)
Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: The issue with AI comments is that if humans and AI both work in the code, it is not ensured if the comments match the implementation if the code is updated.

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java [hunk 9]
```diff
@@ -9,16 +9,47 @@
...
+                            StandardField.TYPE,
+                            StandardField.XREF,
+                            StandardField.GROUPS
+                    )
+            )
+            .collect(Collectors.toSet());
+
+    private static Set<Field> filterExcludedFields(Collection<Field> fields) {
+        return fields.stream()
+                     .filter(field -> !FILTERED_FIELDS.contains(field))
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: Inline the variable. You have multiple filterings below; and these are also filtered.

File: jablib/src/main/resources/csl-styles
Comment (subhramit) [inline jablib/src/main/resources/csl-styles:1]: See https://devdocs.jabref.org/code-howtos/faq.html#submodules

Comment (lawmeyian) [reply jablib/src/main/resources/csl-styles:1]: Hi @subhramit , thank you for your feedback. Could you please review again?

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java (hunk 5 above)
Comment (subhramit) [reply jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: On second thought and some discussion, this can be ignored, it is okay to have flexibility in this case.

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java (hunk 9 above)
Comment (subhramit) [reply jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: Was this resolved? @lawmeyian

Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: at [`c613b02` (#13305)](https://github.com/JabRef/jabref/pull/13305/commits/c613b0295a5251aa2e46e891edbf42e9fd6d5ccc) @calixtus and me worked on (now)

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java [hunk 10]
```diff
@@ -102,4 +106,43 @@ void checkLibraryWithoutIssues(@TempDir Path tempDir) {
...
+        assertNotNull(typeResult);
+        assertTrue(typeResult.fields().contains(StandardField.AUTHOR));
```
[the remark this answers is not in the document]
Comment (koppor) [reply jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: Fixed at [`8205500` (#13305)](https://github.com/JabRef/jabref/pull/13305/commits/82055001ac7e37d0ae359e2681978215568e86a2)

**Review by koppor — APPROVED** [review]

**Review by calixtus — APPROVED** [review]

**Comment by lawmeyian** [comment]
Thank you @subhramit , @calixtus and @koppor for your helpful feedback and support throughout this PR. I really appreciate the time you took to review my code, point out improvements, and guide me through the fixes.
