### PR TITLE
Fix inspire fetcher

### LINKED ISSUE #6229: Fetching from inspire
JabRef version 5.0/5.1 on Windows 10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. select inspire from web search, enter hep-ph/9802379, hit search button
2. get "processing hep-ph/9802379" and nothing comes out.

I don't know how to open error console in Windows but I suspect this problem has something to do with the new inspire beta (and the old inspire is now old.inspirehep.net).

### PR DESCRIPTION
**Pull request by Siedlerchr**
Use application/x-bibtex header
Fixes #6229

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java [hunk 1]
```diff
@@ -59,33 +56,38 @@ public String getName() {
...
     }
 
     @Override
-    public Parser getParser() {
-        // Inspire returns the BibTeX result embedded in HTML
-        // So we extract the BibTeX string from the <pre>bibtex</pre> tags and pass the content to the BibTeX parser
-        return inputStream -> {
-            String response = new BufferedReader(new InputStreamReader(inputStream)).lines().collect(Collectors.joining(OS.NEWLINE));
+    public List<BibEntry> performSearch(String query) throws FetcherException {
+        if (StringUtil.isBlank(query)) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java:65]: Instead of copy-pasting the method, I would extract `new URLDownload(getURLForQuery(query)).asInputStream()` from https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/importer/SearchBasedParserFetcher.java#L58 to a new default method, which you then can overwrite here.

File: src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java [hunk 2]
```diff
@@ -59,33 +56,38 @@ public String getName() {
     @Override
     public URL getURLForQuery(String query) throws URISyntaxException, MalformedURLException, FetcherException {
         URIBuilder uriBuilder = new URIBuilder(INSPIRE_HOST);
-        uriBuilder.addParameter("p", query); // Query
-        //uriBuilder.addParameter("jrec", "1"); // Start index (not needed at the moment)
-        uriBuilder.addParameter("rg", "100"); // Should return up to 100 items (instead of default 25)
-        uriBuilder.addParameter("of", "hx"); // BibTeX format
+        uriBuilder.addParameter("q", query); // Query
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java:59]: there is no paging support (start + size) for the new interface?

File: src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java [hunk 3]
```diff
@@ -1,49 +1,46 @@
...
 
 /**
  * Fetches data from the INSPIRE database.
  *
- * @implNote We just use the normal search interface since it provides direct BibTeX export while the API (http://inspirehep.net/info/hep/api) currently only supports JSON and XML
  */
 public class INSPIREFetcher implements SearchBasedParserFetcher {
 
-    private static final String INSPIRE_HOST = "https://inspirehep.net/search";
+    private static final String INSPIRE_HOST = "https://inspirehep.net/api/literature/";
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java:38]: Could you please include the link to the documentation of the new api as well.

File: src/main/java/org/jabref/logic/openoffice/OOUtil.java [hunk 4]
```diff
@@ -227,7 +227,7 @@ public static void insertTextAtCurrentLocation(XText text, XTextCursor cursor, S
         } */
         if (formatting.contains(Formatting.SUBSCRIPT)) {
             xCursorProps.setPropertyValue(CHAR_ESCAPEMENT,
-                    (byte) -101);
+                    (byte) -33);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/openoffice/OOUtil.java:230]: Is this related to this fix?

File: src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java:59]: The json api has support for it, but when calling with the bibtex header not.

File: src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java (hunk 3 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java:32]: There is not yet any documentation avaiable. I contacted INSPIRE hep team.

File: src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java (hunk 2 above)
Comment (larsgw) [reply src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java:53]: On my end `&size=10&page=2` seems to works fine as of today, not sure about a week ago.

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/fetcher/INSPIREFetcher.java:53]: Indeed, this seems to work. I will create a follow up PR
