### PR TITLE
Fix the F3 shortcut key

### LINKED ISSUE #10938: F3 shortcut inactive after starting Jabref
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

_No response_

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Right after opening Jabref, left-clicking on an entry (to select it) and pressing F3 yields no result.
2. This is solved by right-clicking once to open the contextual menu, and then closing it.
3. Now F3 correctly opens the url.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by priyanshu16095**
### Fixes #10938

- The fix ensures that the F3 shortcut functions as expected without need to open the right click context menu each time.

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by priyanshu16095** [comment]
https://github.com/user-attachments/assets/1b4a6c77-d9f0-4a1d-bc8d-67690a43f795

Now works right after opening JabRef.

File: src/main/java/org/jabref/gui/maintable/MainTable.java [hunk 1]
```diff
@@ -368,6 +373,10 @@ private void setupKeyBindings(KeyBindingRepository keyBindings) {
                          scrollToPreviousMatchCategory();
                         event.consume();
                         break;
+                    case OPEN_URL_OR_DOI:
+                        openUrlAction.execute();
+                        event.consume();
+                        break;
```
Comment (subhramit) [inline src/main/java/org/jabref/gui/maintable/MainTable.java:379]: As a hotfix, this works, but I don't yet see what was causing the bug.
I don't think this should belong to `MainTable`.
@LoayGhreeb @koppor @calixtus should this go to `JabRefFrame` or somewhere else?

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/maintable/MainTable.java:379]: OpenUrlAction lives in Maintable, it belongs to it. so fine

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks again for the many fixes so far!

**Comment by priyanshu16095** [comment]
So happy my first PR got merged. Thanks to the amazing maintainers!
