### PR TITLE
Move generate key option to citation key preference tab

### LINKED ISSUE #10849: When copying an entry with a specified Citationkey into a new .bib file, the citationkey is automatically changed to the [auth][year] format after pasting
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

_No response_

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I copy an entry with a specified Citationkey into a new .bib file, the citationkey is automatically changed to the [auth][year] format after my pasting. 

However, I do not want the citationkey to be automatically altered upon copying. I wish to retain all the original information when copying the entry into a new .bib file. I have tried checking/unchecking "overwrite existing keys" in the preference -> citation key generator, but it doesn't work.

How can I address this issue?

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by priyanshu16095**
### Fixes #10849

This PR moves the "Generate new keys on import" option from the WebSearch tab to the CitationKey Preferences tab.

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

Screenshot (28)

### CODE REVIEW

File: src/test/java/org/jabref/gui/entryeditor/citationrelationtab/CitationsRelationsTabViewModelTest.java [hunk 1]
```diff
@@ -63,7 +63,7 @@ void setUp() {
         when(preferences.getImportFormatPreferences()).thenReturn(importFormatPreferences);
 
         ImporterPreferences importerPreferences = mock(ImporterPreferences.class, Answers.RETURNS_DEEP_STUBS);
-        when(importerPreferences.isGenerateNewKeyOnImport()).thenReturn(false);
+        when(preferences.getCitationKeyPatternPreferences().isGenerateNewKeyOnImport()).thenReturn(false);
```
Comment (subhramit) [inline src/test/java/org/jabref/gui/entryeditor/citationrelationtab/CitationsRelationsTabViewModelTest.java:66]: Mock an instance of `CitationKeyPreferences` using Mockito and then use that. Examples should be present in the class.

**Review by subhramit — CHANGES_REQUESTED** [review]

**Comment by Siedlerchr** [comment]
Good thing, this also refers to this user's post https://discourse.jabref.org/t/jabref-v5-15-is-not-using-the-merged-entry-random-changes-to-bibfile/5403/3?u=siedlerchr

**Comment by subhramit** [comment]
@priyanshu16095 you can keep my requested charges on hold. @calixtus may have some opinions on whether want to shift or keep the preference in the `ImporterPreferences`.

**Comment by calixtus** [comment]
Yes, my concern was that putting that pref option into keyGeneratorPreferences, this would breach the level of abstraction or hierarchy, because the pref option about if to use the keygenerator on import is different of how it is configured. Yet in the UI there is no place where this option would otherwise. So my suggestion would be to leave the pref option codewise in the importerPreferences an put the ui option into the key generator tab.

File: src/main/java/org/jabref/gui/preferences/citationkeypattern/CitationKeyPatternTabViewModel.java [hunk 2]
```diff
@@ -35,16 +38,19 @@ public class CitationKeyPatternTabViewModel implements PreferenceTabViewModel {
             new CitationKeyPatternsPanelItemModel(new CitationKeyPatternsPanelViewModel.DefaultEntryType(), ""));
 
     private final CitationKeyPatternPreferences keyPatternPreferences;
+    private final ImporterPreferences importerPreferences;
 
-    public CitationKeyPatternTabViewModel(CitationKeyPatternPreferences keyPatternPreferences) {
-        this.keyPatternPreferences = keyPatternPreferences;
+    public CitationKeyPatternTabViewModel(CliPreferences preferences) {
+        this.keyPatternPreferences = preferences.getCitationKeyPatternPreferences();
+        this.importerPreferences = preferences.getImporterPreferences();
```
Comment (subhramit) [inline src/main/java/org/jabref/gui/preferences/citationkeypattern/CitationKeyPatternTabViewModel.java:45]: Maintain abstraction - take `CitationKeyPatternPreferences` and `ImporterPreferences` as arguments instead of entire `preferences`.
@calixtus we have to break the consistency in design a bit here, as we keep the preference in importerprefs.
@priyanshu16095 maybe add a comment for the initialization of importerpreferences, based on Carl's comment on the design decision.

**Review by subhramit — CHANGES_REQUESTED** [review]
Quick comments. Also, @priyanshu16095, please no force-pushes!

File: src/main/java/org/jabref/gui/preferences/citationkeypattern/CitationKeyPatternTabViewModel.java [hunk 3]
```diff
@@ -35,16 +37,21 @@ public class CitationKeyPatternTabViewModel implements PreferenceTabViewModel {
             new CitationKeyPatternsPanelItemModel(new CitationKeyPatternsPanelViewModel.DefaultEntryType(), ""));
 
     private final CitationKeyPatternPreferences keyPatternPreferences;
+    private final ImporterPreferences importerPreferences;
 
-    public CitationKeyPatternTabViewModel(CitationKeyPatternPreferences keyPatternPreferences) {
+    public CitationKeyPatternTabViewModel(CitationKeyPatternPreferences keyPatternPreferences, ImporterPreferences importerPreferences) {
         this.keyPatternPreferences = keyPatternPreferences;
+
+        // Defines key generation preference during import.
```
Comment (subhramit) [inline src/main/java/org/jabref/gui/preferences/citationkeypattern/CitationKeyPatternTabViewModel.java:45]: A [javadoc comment at field level](https://www.baeldung.com/javadoc#3-javadoc-at-field-level) is preferable - javadoc is often used in relaying ambiguities/abnormalities/edge cases to the developer. Remove this, and put the lines:
* The preference for if to use the keygenerator on import is different from how it is configured.
* For the UI, there is no better place to put the option than the Citation key generator tab, but shifting the preference to CitationKeypreferences would break the abstraction or hierarchy.
* Hence, we keep the preference in ImporterPrefernces, but in the UI, we initialize it here.
above line 40 (where the field is declared).
Take a look at how `@link` is used to link classes in javadoc.

**Review by subhramit — APPROVED** [review]
I pushed a minor commit (https://github.com/JabRef/jabref/pull/12436/commits/b3d42f1bac48f1d46ac36659ae98cbbf65f1f52c) correcting the class name in the javadoc - IntelliJ will give you a hint whether the class is linked correctly or not by highlighting it in red.
I also shifted the `keyPatternPreferences` declaration above in order, as those are the primary preference options exposed via this view. The edge case comes after that.

Rest lgtm from my side code-wise. Await a second review.

**Comment by subhramit** [comment]
@Siedlerchr @calixtus one of you can take a second look, i think we are near completion here

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
Thanks for your work!
