### PR TITLE
Fix #5939 by creating a mutable list in OpenDatabaseAction

### LINKED ISSUE #5939: Exception when opening library from File History Menu
- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Opening a library from File -> Recent libraries throws an exception.

1. File -> Recent libraries
2. Select a valid one
3. Exception is shown

This is because a immutable SingletonList is created and then passed to OpenDatabaseAction::openFiles

### PR DESCRIPTION
**Pull request by Ka0o0**
This PR fixes the problem when opening a library from the recent libraries menu. fixes #5939 

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Manually tested changed features in running JabRef (always required)

### CODE REVIEW

File: src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java [hunk 1]
```diff
@@ -102,7 +103,7 @@ private Path getInitialDirectory() {
      * @param file the file, may be null or not existing
      */
     public void openFile(Path file, boolean raisePanel) {
-        openFiles(Collections.singletonList(file), raisePanel);
+        openFiles(new ArrayList<>(Collections.singletonList(file)), raisePanel);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java]:
```suggestion
        openFiles(Arrays.asList(file)), raisePanel);
```

Comment (Ka0o0) [reply src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java]: Yeah I actually first had it like this but I changed it because IntelliJ was complaining to use Collections.singletonList instead of Arrays.asList. Changed it now to reflect your suggestion 👍

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java]: Yeah, but seems like Intelilj didn't know that you need a mutable list later on.

**Comment by Siedlerchr** [comment]
Thanks again for your contribution! 👍

**Comment by koppor** [comment]
We tried it locally. Did not fix the issue. We will switch to `List.of()`.
