### PR TITLE
Consistent casing in fieldnames

### LINKED ISSUE #10590: Inconsistent casing of custom field names
### JabRef version

5.11 (latest release)

### Operating system

macOS

### Details on version and operating system

MacOS 13.6 (22G120)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Casing of custom field names is inconsistent in several different ways as described below. I believe these inconsistencies may have been introduced with #9993, at least partly.

#### In the `Details` pane, casing does not respect the bibtex file in contrary to what is declared [in this comment](https://github.com/JabRef/jabref/pull/9993#issuecomment-1586900956)

1. Create a new custom field in the `biblatex source` tab
2. Make the field name upper case, e.g. `Newfield`
3. Save, close and reopen file
4. Observe that in the `Other fields` tab the `newfield` field name is lowercased, as it is in the BibTeX file. In fact, lowercase has been enforced and saved into file!
5. Observe that built-in BibTeX fields such as `Author` or `Title` are always uppercase in the UI and always lowercase in the BibTeX file.

Now, there is a way to make custom fields appear uppercase, but

#### In the `Details pane`, built-in tabs such as `Required fields` or `Optional fields` only partially respect JabRef preferences

1. Go to `Preferences > Entry types` and choose the type of your test BibTeX entry, e.g. "Book"
2. Create a custom field `Newfield` (uppercase) within that entry type, also make one of the existing built-in fields such as `Author` lowercase
3. Export preferences into an `xml` file
4. Quit and start JabRef anew
5. In the `Details pane`, observe that both `Newfield` and `Author` are uppercase, although one would expect `author` to become lowercase
6. In the `xml` file, observe that `author` is lowercase while `Newfield` is uppercase
7. In the `xml` file, observe that built-in field names are all lowercase, while `Newfield` is uppercase. `Newfield` becomes lowercase when done so through preferences.
8. JabRef enforces the built-in field names to appear always uppercase in the UI and always lowercase in files, both `xml` prefs and BibTeX `bib` sources.

#### In the `Details pane`, custom tabs do not respect anything, neither BibTeX source, nor preferences.

1. Go to `Preferences > Entry Editor` and create a custom tab such as `Fields:author;newfield`
2. Observe that no matter what, `author` always appears uppercase and `newfield` always appears lowercase.

### Summary

Currently, it is not possible to have a consistent casing across the Details pane and a BibTeX file:
1. Built-in field names are always lowercase
2. Custom field names can be made both, but not in custom tabs
3. Lowercase is enforced in `bib` files 
4. Lowercase is almost exclusively enforced in `xml` preferences file - only custom fields can be saved uppercase in `jabref-entrytype` fields, though not in `customTabFields` fields.

### Appendix

The below screenshots should illustrate what is written above.

#### `Preferences > Entry types`
Screenshot 2023-10-27 at 15 15 59

#### `Required fields` tab
Screenshot 2023-10-27 at 14 53 20

#### Custom `Fields` tab
Screenshot 2023-10-27 at 14 59 10

#### `biblatex source` tab
Screenshot 2023-10-27 at 14 59 54

### `test.bib` opened in another editor
Screenshot 2023-10-27 at 15 00 40

### PR DESCRIPTION
**Pull request by calixtus**
Fixes #10590 

see attached ADR

### Steps to test

Look at entry editor and preferences for entry types

image  
image image 
image

image

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

### CODE REVIEW

File: jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
+package org.jabref.model.entry.field;
+
+import java.util.StringJoiner;
+
+import org.jabref.model.strings.StringUtil;
+
+public class FieldTextMapper {
+    public static String getDisplayName(Field field) {
+        if (field.isStandardField()) {
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java:9]: Future work is to add make use of  `org.jabref.model.entry.BibEntryTypesManager#isCustomOrModifiedType` here. It is hard, because the parameter has the field only - and the field does not have a reference to its parent.

File: jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+            StandardField standardField = (StandardField) field;
+            return switch (standardField) {
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java:11]: Nice start so that we could customize

`urldate` to `URL date` or even `Date of URL`.

File: jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+            };
+        }
+
+        return field.getName();
+    }
+
+    public static String getDisplayName(OrFields fields) {
+        StringJoiner joiner = new StringJoiner("/");
+        for (Field field : fields.getFields()) {
+            joiner.add(StringUtil.capitalizeFirst(FieldTextMapper.getDisplayName(field)));
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java]: We just need the display  name - no more other configuration.

```suggestion
            joiner.add(FieldTextMapper.getDisplayName(field));
```

File: jablib/src/test/java/org/jabref/model/entry/field/FieldFactoryTest.java [hunk 4]
```diff
@@ -13,14 +13,16 @@
 import static org.junit.jupiter.api.Assertions.assertNotEquals;
 
 class FieldFactoryTest {
+    /// ADR 49: Always use exact casing for UnknownFields, only StandardFields have hardcoded capital first letter as display name
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/model/entry/field/FieldFactoryTest.java]:
```suggestion
    /// @ADR(49)
```

**Review by koppor — DISMISSED** [review]

File: jablib/src/main/java/org/jabref/logic/exporter/OOCalcDatabase.java [hunk 5]
```diff
@@ -146,7 +146,12 @@ private void addTableHeader(Element table, Document document) {
         firstRow.setAttribute("table.style-name", "ro1");
         addTableCell(document, firstRow, "Type");
         for (Field field : toExportFields) {
-            addTableCell(document, firstRow, FieldTextMapper.getDisplayName(field));
+            // Special case for OpenOffice/LibreOffice reporttype
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/exporter/OOCalcDatabase.java]: Can I have the "why" here?

File: jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java [hunk 6]
```diff
@@ -30,6 +30,10 @@ public static String getDisplayName(Field field) {
                 default ->
                         StringUtil.capitalizeFirst(field.getName());
             };
+        } else if (field instanceof InternalField internalField) {
+            if (internalField == InternalField.KEY_FIELD) {
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/model/entry/field/FieldTextMapper.java]: Can this be merged?

```suggestion
        } else if (field == InternalField.KEY_FIELD) {
```

File: jablib/src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java [hunk 7]
```diff
@@ -847,4 +849,31 @@ private BibEntry firstEntryFrom(final String bibContentText) throws JabRefExcept
...
+        String bibtexEntry = """
+                @Article{test,
+                  Author                   = {Foo Bar},
+                  Title                    = {My title},
+                  CustomField              = {Some value}
+                }
+                """.replace("\n", OS.NEWLINE);
+
+        BibEntry entry = firstEntryFrom(bibtexEntry);
+        entry.setField(new UnknownField("CustomField"), "Some other value");
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java]:
```suggestion
        BibEntry entry = firstEntryFrom(bibtexEntry)
            .withField(new UnknownField("CustomField"), "Some other value");
```

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultTxtWriterTest.java [hunk 8]
```diff
@@ -142,7 +142,7 @@ void checkDifferentOutputSymbols(@TempDir Path tempDir) throws IOException {
         assertEquals("""
                 Field Presence Consistency Check Result
 
-                | entry type | citation key | Custom | Pages | Title |
+                | entry type | citation key | custom | Pages | Title |
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultTxtWriterTest.java:145]: Discussion: I think, we should use the field name instead of the display name --> follow-up for someone else :)

**Review by koppor — CHANGES_REQUESTED** [review]

File: jablib/src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java (hunk 7 above)
Comment (calixtus) [reply jablib/src/test/java/org/jabref/logic/bibtex/BibEntryWriterTest.java]: For consistency reasons with the other tests better not.

**Review by koppor — APPROVED** [review]
Thank you for your effort and endurance!!

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
GitHub's UI does something wrong - https://github.com/JabRef/jabref/commit/d741bac51a9e11be0b9c9848df9f7ed51eb295e1 is the right commit

image


This one is NOT in:

image
