### PR TITLE
Context menu appearing on empty library table body

### LINKED ISSUE #15384: Context menu does not close on outside click in empty library view
Steps to reproduce:
1. Open empty library
2. Right click anywhere
3. Context menu opens
4. Click outside

Expected:
Context menu should close

Actual:
Menu stays open unless ESC is pressed or tab is changed

Image

### PR DESCRIPTION
**Pull request by faneeshh**
### Related issues and pull requests

Closes #15384 

### PR Description

When the library is empty, right clicking the table body was triggering the column chooser context menu. This was happening because the placeholder VBox has no context menu handler, so the ContextMenuEvent bubbled up to the MainTable level 
handler which showed the menu unconditionally for any non StackPane target.

### Steps to test

1. Open an empty library
2. Try right clicking on the table body, the context menu shouldn't appear on it anymore.
3. Now try right clicking the header column menu and the context menu should open up and clicking on any other part except the table body should close it.

image

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [/] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [x] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

**Comment by faneeshh** [comment]
So after these changes, the context menu doesn't close after clicking on the table body. If you click anywhere else except the table body it does close. Do you think it is needed to make the Table body area clickable to close the context menu?

File: jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java [hunk 1]
```diff
@@ -55,6 +56,19 @@ public void show(boolean show) {
         });
     }
 
+    private static boolean isColumnHeaderTarget(Object eventTarget) {
+        if (!(eventTarget instanceof Node node)) {
+            return false;
+        }
+        while (node != null) {
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: why a loop?

**Review by calixtus — CHANGES_REQUESTED** [review]

File: jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java [hunk 2]
```diff
@@ -60,13 +59,8 @@ private static boolean isColumnHeaderTarget(Object eventTarget) {
...
         }
-        while (node != null) {
-            if (node instanceof TableColumnHeader) {
-                return true;
-            }
-            node = node.getParent();
-        }
-        return false;
+        return node.getStyleClass().contains("column-header")
+                || (node.getParent() != null && node.getParent().getStyleClass().contains("column-header"));
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: This change is nonsense.
instanceof was just fine

C'mon, use your brain, not an LLM.

Comment (faneeshh) [reply jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: My bad was in a rush so opted for a quick fix... I should have reviewed it. I'll revert to the instanceof and make the requested changes when I get back home.

Comment (Siedlerchr) [reply jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: JabRef is not about getting things done fast. There is no "race" or competition.

Comment (faneeshh) [reply jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: I totally understand that and I promise I would never blindly make AI generated changes. It's just that I was going on a hike for 2-3 days and wouldn't have had access to work on the issue until the weekend. I'm really sorry about it. I always usually take my time reviewing everything precisely, this was a one time mistake and won't happen again.

Comment (calixtus) [reply jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: That is totally ok, quick note about a few days not available, we put the pr on waiting an you have a good time hiking. Just don't make bs commits in a hurry. That's just a waste of your and our time.
As soon as you are back we can finish the pr. Have a good time.

Comment (faneeshh) [reply jabgui/src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: Thank you so much for understanding... I wouldn't wanna waste your guys time on AI generated PRs either. I'm sorry once again. I'll be back in 2 days and get back on it.

**Comment by faneeshh** [comment]
> So after these changes, the context menu doesn't close after clicking on the table body. If you click anywhere else except the table body it does close. Do you think it is needed to make the Table body area clickable to close the context menu?

@calixtus I've updated the method to use instanceof and it checks the target and its immediate parent instead of looping now too. Should I also add this functionality that I discussed above?
