### PR TITLE
Resolve File Creation Issue With Medline/PubMed

### LINKED ISSUE #8455: Systematic Literature Review Cannot create "Medline/PubMed" file on Linux
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Fedora 35 with Gnome 41.3

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start a new systematic literature review
2. Choose "Medline/PubMed" as a database
3. Start the survey

The app will throw an error about the creation of repository structure. Systematic literature review creates (and looks for) files based on the query plus database name (if I understand correctly). It appears that on Linux file names cannot contain `/` whereas in `Medline/PubMed` there is a `/` and it wants to create a file with the database name which is not possible. The issue also persists in the development version 5.6.8-1.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalStateException: Error during creation of repository structure.
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.createBibFile(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.createFetcherResultFile(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.lambda$setUpRepositoryStructure$0(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.setUpRepositoryStructure(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.<init>(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.Crawler.<init>(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.slr.ExistingStudySearchAction.crawl(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.slr.StartNewStudyAction.execute(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.5.60000/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.5.60000/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: /home/user/bibliography/Survey/1611996361 - cancer/Medline/PubMed.bib
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.createFile(Unknown Source)
	... 53 more

```

</details>

### PR DESCRIPTION
**Pull request by addak**
Issue : Due to the Fetcher Name being "Medline/PubMed", File creation fails as Medline is treated as a Directory and since It isn't created, the issue is observable.
Fixes #8455 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by addak** [comment]
A better fix would be to change the name in MedlineFetcher from "Medline/PubMed" to some other appropriate one.
```
 @Override
    public String getName() {
        return "Medline/PubMed";  <--- Change the name
    }
```

**Comment by Siedlerchr** [comment]
The fetcher has been named like that for ages. And there can always be a fetcher with a weird name, so this should be fine,

**Comment by addak** [comment]
@Siedlerchr Please review!

File: src/test/java/org/jabref/logic/crawler/StudyDatabaseToFetcherConverterTest.java [hunk 1]
```diff
@@ -60,9 +60,10 @@ public void getActiveFetcherInstances() throws Exception {
         StudyDatabaseToFetcherConverter converter = new StudyDatabaseToFetcherConverter(studyRepository.getActiveLibraryEntries(), importFormatPreferences);
         List<SearchBasedFetcher> result = converter.getActiveFetchers();
 
-        Assertions.assertEquals(2, result.size());
+        Assertions.assertEquals(3, result.size());
         Assertions.assertEquals(result.get(0).getName(), "Springer");
         Assertions.assertEquals(result.get(1).getName(), "ArXiv");
+        Assertions.assertEquals(result.get(2).getName(), "Medline/PubMed");
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/crawler/StudyDatabaseToFetcherConverterTest.java:66]: In general, it is better you compare two collections directly, this makes it easier to spot differences in case of failure.
e.g. you have on the one hand:
expectedFetcherNames = LIst.of(.......)
actualFetcherNames = result.stream.map(Fetcher::getName).toCollection...
assertEquals(expectedFetcherNames,

File: src/test/java/org/jabref/logic/crawler/CrawlerTest.java [hunk 2]
```diff
@@ -60,6 +60,9 @@ public void testWhetherAllFilesAreCreated() throws Exception {
 
         assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), hashCodeQuantum + " - Quantum", "result.bib")));
         assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), hashCodeCloudComputing + " - Cloud Computing", "result.bib")));
+
+        assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), hashCodeQuantum + " - Quantum", "Medline_PubMed.bib")));
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/crawler/CrawlerTest.java:64]: I wonder if it makes sense to convert this test to a parameterized unit test.

**Review by Siedlerchr — APPROVED** [review]
overall lgtm, just some ideas for improvement.

File: CHANGELOG.md [hunk 3]
```diff
@@ -65,6 +65,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where someone could add a duplicate field in the customize entry type dialog. [#8194](https://github.com/JabRef/jabref/issues/8194)
 - We fixed a typo in the library properties tab: "String constants". There, one can configure [BibTeX string constants](https://docs.jabref.org/advanced/strings).
 - We fixed an issue when writing a non-UTF-8 encoded file: The header is written again. [#8417](https://github.com/JabRef/jabref/issues/8417)
+- We fixed an issue where folder creation during systemic review failed due illegal fetcher name. [#8552](https://github.com/JabRef/jabref/pull/8552)
```
Comment (Siedlerchr) [inline CHANGELOG.md:68]:
```suggestion
- We fixed an issue where folder creation during systemic literature review failed due to an illegal fetcher name. [#8552](https://github.com/JabRef/jabref/pull/8552)
```

**Comment by addak** [comment]
Hi 
Could you please tell me what needs to be properly formatted to resolve the format issue with checkstyle?
```
 @Test
    public void testWhetherAllFilesAreCreated() throws Exception {
        setUp();
        Crawler testCrawler = new Crawler(getPathToStudyDefinitionFile(), gitHandler, generalPreferences, importFormatPreferences, savePreferences, entryTypesManager, new DummyFileUpdateMonitor());

        testCrawler.performCrawl();

        assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), hashCodeQuantum + " - Quantum")));
        assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), hashCodeCloudComputing + " - Cloud Computing")));

        List<String> filesToAssert = List.of("ArXiv.bib", "Springer.bib", "result.bib", "Medline_PubMed.bib");
        filesToAssert.forEach(
                fileName -> {
                    assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), hashCodeQuantum + " - Quantum", fileName)));
                    assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), hashCodeCloudComputing + " - Cloud Computing", fileName)));
                });
        assertTrue(Files.exists(Path.of(tempRepositoryDirectory.toString(), "studyResult.bib")));
    }
```

**Comment by Siedlerchr** [comment]
@addak  The whitepsace was tricky, it was the last element int the list.
