### PR TITLE
Handle regular expressions in global search

### LINKED ISSUE #5349: Search triggers too soon when entering regex
1. Enable regex mode in search.
2. Start typing `F[` 
3. Search triggers and results in regex error:
grafik

Idea would be to only trigger regex search if user stops typing or if focus is left?

### PR DESCRIPTION
**Pull request by CaptainDaVinci**
Fixes #5349

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [X] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by CaptainDaVinci** [comment]
Is this approach good towards fixing the issue?

**Comment by Siedlerchr** [comment]
Yes, this is a good start. It would be really cool if you could use the validation icon stuff like it's done in the entry editor or in the shared database dialog  or in the preferences.

**Comment by CaptainDaVinci** [comment]
2019-10-05-174357_1920x1080_scrot
 The current commit checks for valid regex before setting the active search state, in case of invalid regex a message is shows next to the search bar.

File: src/main/java/org/jabref/gui/search/GlobalSearchBar.java [hunk 1]
```diff
@@ -228,6 +235,16 @@ public void performSearch() {
         stateManager.setSearchQuery(searchQuery);
     }
 
+    private boolean validRegex() {
+        try {
+            Pattern.compile(searchField.getText());
+        } catch (PatternSyntaxException e) {
+            LOGGER.error(e.getMessage());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: Please use `LOGGER.debug` because this error is kind of expected.

File: src/main/java/org/jabref/gui/search/GlobalSearchBar.java [hunk 2]
```diff
@@ -219,6 +221,11 @@ public void performSearch() {
             return;
         }
 
+        if (regularExp.isSelected() && !validRegex()) {
+            currentResults.setText(Localization.lang("Invalid Regex"));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/search/GlobalSearchBar.java]:
```suggestion
            currentResults.setText(Localization.lang("Invalid regular expression"));
```

Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: As @Siedlerchr suggests, it would be nice if you could report the invalid regex to the user directly in the text box. We use the following validation framework for this: https://github.com/sialcasa/mvvmFX/wiki/Validation (the other places where this library is used might give you a good idea how to implement it - sounds more scarier than it actually is)

**Comment by CaptainDaVinci** [comment]
2019-10-15-193434_1920x1080_scrot

The UI is a bit off, I am not sure how to align it and provide a margin.

**Comment by Siedlerchr** [comment]
Thanks for the update. The validator icon is always a bit difficult. 
You can try to style it with css. You can try with ScenicView to identify the property : https://github.com/JonathanGiles/scenic-view

**Comment by Siedlerchr** [comment]
Is this ready now or do you want to check if you can tweak the CSS a bit?

**Comment by CaptainDaVinci** [comment]
I haven't tried tweaking the CSS, yet. I'll try making that change today.

**Comment by CaptainDaVinci** [comment]
I tried making a changed in `gui/Base.css`
```
 .mainToolbar > .container > .search-field {
     -fx-end-margin: 1em;
 }
```
But it didn't change anything. Any pointers on what might be wrong? 
From ScenicView, the parent of .search-field does not have a style class, would that matter?

**Comment by tobiasdiez** [comment]
What are you trying to do exactly?

**Comment by CaptainDaVinci** [comment]
I'm trying to add a margin to the error-icon which appears when an invalid regular expression is entered, the icon is of styleClass label.

**Comment by tobiasdiez** [comment]
Ok, it's always a bit tricky with the css identifiers. First, I would add something like `-fx-background-color: blue; -fx-text-fill: green;` which makes it more evident that the css does apply to the correct element. Then you can play around with the css identifier, maybe `.search-field .label` works (it should apply to every label contained in the `searchfield`. Finally, according to https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#region, the additional space should be added with `-fx-padding: 1em 2em 1em 2em;` (or whatever numbers are fittting). In JavaFX, there is no real `margin` tag as in HTML, so you have to use paddings. Hope that works.

**Comment by CaptainDaVinci** [comment]
Added a right padding to the error icon. But on hovering over the icon, the tool-tip of search field is shown instead of the error message.

2019-10-20-204103_1920x1080_scrot

**Comment by Siedlerchr** [comment]
I think the problem with the tooltip is not that big. You have the message at the right side. So I guess this is not that important
