### PR TITLE
Fix issue in comments Tab

### LINKED ISSUE #10870: Non-editable user comments
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I am unsure of the cause for this, as a peer doesn't seem to have this problem.
1. Open the Comments tab for an entry
2. Add a comment in the bottom text-field labeled as `Comment-<username>`
3. Save the database
4. Notice that the notification about the file being edited outside JabRef appears
5. Proceed to Review the changes and to Merge them
6. Notice duplicated `Comment-<username>` field:
   image
7. Accept the merge
8. Notice in the Comments tab, two text fields appear for the same user with the comment repeated:
   image
9. Close the database (no need to save) and open it again
10. Navigate to the comments for entry where comment was added
11. Notice two comment fields there for the same user, the content only in the second one and not editable:
   image

### Appendix

@Article{ArticleID,

  comment-roc = {Just a test comment},
  comment-roc = {Just a test comment},

}

### PR DESCRIPTION
**Pull request by LoayGhreeb**
Fixes #10870

This issue occurs when the `defaultOwner` contains capital letters. 
For example, if `defaultOwner = Test`, the `userSpecificCommentField.name` will be `comment-Test`, after saving it to the .bib file, it will be written as `comment-test`. As a result, every time the `commentsTab` is opened, it will contain both `comment-Test` and `comment-test` fields.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/entryeditor/CommentsTab.java [hunk 1]
```diff
@@ -80,14 +80,14 @@ protected SequencedSet<Field> determineFieldsToShow(BibEntry entry) {
         comments.add(StandardField.COMMENT);
 
         // Also show comment field of the current user (if enabled in the preferences)
-        if (entry.hasField(userSpecificCommentField) || entryEditorPreferences.shouldShowUserCommentsFields()) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/CommentsTab.java:83]: Can you please explain these changes?

Comment (LoayGhreeb) [reply src/main/java/org/jabref/gui/entryeditor/CommentsTab.java:83]: If an entry has a `userSpecificCommentField` but the `show user comments field` option is disabled in the preferences, it should not be visible

Comment (koppor) [reply src/main/java/org/jabref/gui/entryeditor/CommentsTab.java:83]: It should display existing fields. Only the empty field should not be shown. Therefore the `||`.

Comment (LoayGhreeb) [reply src/main/java/org/jabref/gui/entryeditor/CommentsTab.java:83]: Got it, I will redo this change.

File: src/main/java/org/jabref/gui/entryeditor/CommentsTab.java [hunk 2]
```diff
@@ -80,14 +80,14 @@ protected SequencedSet<Field> determineFieldsToShow(BibEntry entry) {
...
+        if (entryEditorPreferences.shouldShowUserCommentsFields()) {
             comments.add(userSpecificCommentField);
         }
 
         // Show all non-empty comment fields (otherwise, they are completely hidden)
         comments.addAll(entry.getFields().stream()
                 .filter(field -> (field instanceof UserSpecificCommentField && !field.equals(userSpecificCommentField))
-                        || field.getName().toLowerCase().contains("comment"))
+                        && field.getName().toLowerCase().contains("comment"))
```
Comment (koppor) [inline src/main/java/org/jabref/gui/entryeditor/CommentsTab.java:90]: Just remove that. Everything should work nevertheless. Also no duplicates.

**Comment by koppor** [comment]
I could not check the failing ui test `org.jabref.gui.entryeditor.CommentsTabTest`

File: src/main/java/org/jabref/gui/entryeditor/CommentsTab.java [hunk 3]
```diff
@@ -64,7 +64,7 @@ public CommentsTab(PreferencesService preferences,
                 journalAbbreviationRepository,
                 indexingTaskManager
         );
-        this.defaultOwner = preferences.getOwnerPreferences().getDefaultOwner();
+        this.defaultOwner = preferences.getOwnerPreferences().getDefaultOwner().toLowerCase().replaceAll("[^a-z0-9]", "-");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/CommentsTab.java:67]: When using toLowercase etc you should always pass a Locale, usually Locale.Root 
https://mattryall.net/blog/the-infamous-turkish-locale-bug

Comment (LoayGhreeb) [reply src/main/java/org/jabref/gui/entryeditor/CommentsTab.java]: Thanks, I wasn't aware of that. I've updated the code.

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
Code looks good. Did not try fully, but let's see, what users report ^^.
