### PR TITLE
Fix NPE when importing old JabRef preferences

### LINKED ISSUE #14497: Import old jabref preferences fails with npe odel.metadata.UserHostInfo.getUserHostString
```
 org.jabref.migrations.PreferencesMigrations.moveApiKeysToKeyring()
ERROR: Unable to open key store: java.lang.NullPointerException: Cannot invoke "org.jabref.model.metadata.UserHostInfo.getUserHostString()" because "this.userAndHost" is null
	at org.jabref.jablib/org.jabref.logic.preferences.JabRefCliPreferences.getInternalPreferences(JabRefCliPreferences.java:1652)
	at org.jabref/org.jabref.migrations.PreferencesMigrations.moveApiKeysToKeyring(PreferencesMigrations.java:565)
	at org.jabref/org.jabref.migrations.PreferencesMigrations.runMigrations(PreferencesMigrations.java:70)
	at org.jabref/org.jabref.Launcher.main(Launcher.java:90)
```

in jabkit use `preferences import path/toJabRef.xml` and see the exception

Task: Add `if` in appropriate place - or try to set user and host.

Attached [JabRef.xml](https://github.com/user-attachments/files/23881888/JabRef.xml) can be checked-in and used for testing.

### PR DESCRIPTION
**Pull request by pulkitbajaj**
Closes #14497

### Steps to test
1. Download the `JabRef.xml` file provided in issue #14497.
2. Created a temporary JUnit test to reproduce the crash by calling `new JabRefCliPreferences().getInternalPreferences()`.
3. Verified that the test failed with a `NullPointerException` before the fix.
4. Verified that the test passed successfully after applying the fix.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [ ] I added JUnit tests for changes (if applicable)
- [ ] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [ ] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

---
**AI Disclosure:** I used an AI assistant to help analyze the stack trace, understand the root cause (NullPointerException), and draft the reproduction test case. I manually verified the fix and the test results.

### CODE REVIEW

File: jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java [hunk 1]
```diff
@@ -715,6 +714,7 @@ public JabRefCliPreferences() {
         defaults.put(VERSION_IGNORED_UPDATE, "");
         defaults.put(VERSION_CHECK_ENABLED, Boolean.TRUE);
 
+        Localization.setLanguage(getLanguage());
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java:718]: Why this was moved? Why not the comments?

I think, this should be kept as is?!?!?!

Comment (pulkitbajaj) [reply jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java:718]: I moved this to the end of the constructor to ensure that the `defaults` map is fully populated before `getLanguage()` is called. In original version, calling it so early (before initialization was complete) contributed to the NullPointerException/initialization issues we saw.
You are right about the comments-I should have moved them down along with the code. I can move the comments to line 717 to match the code location. Would that resolve the concern?

Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java:718]: Please move the comments, too

Comment (calixtus) [reply jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java:718]: defaults map is to be removed anyways as soon as #14400 is finished, so that issue with a non populated defaults map is probably something that might be a deeper issue - or a non-issue. However, move fast.
