### PR TITLE
Fix for issue 6199: EndNote .xml import to JabRef: PDF links are not imported corrected.

### LINKED ISSUE #6199: EndNote .xml import to JabRef: PDF links are not imported correctly.
JabRef version <JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2>

- [ x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When importing an EndNote library in .xml format into JabRef, the PDF attachment links are not imported into JabRef correctly.

1. I followed instructions under "Importing an EndNote library into JabRef" at https://www.mcgill.ca/library/files/library/jabref_guide_2016.pdf, and exported the EndNote library as an .xml file (attached here as file "My EndNote Library-Converted_xml.txt") . See below snapshot (attached here as file "EndNote Export settings = xml.PNG") showing the export configuration of EndNote version X9.3.1 (Bld 13758).

2. I then imported the EndNote .xml library file into JabRef version 5.0.

3. The EndNote .xml library is imported into JabRef; however, the PDF file attachments are not imported automatically. 

4. It appears this is a bug because JabRef expects the pdf url to be encapsulated in a `style` span as this is the case for the other urls. As a temporary workaround, you can add the <style> ... </style> tag around the filename.pdf (i.e., filename.pdf  --> <style> filename.pdf </style>) yourself for the moment; this should work semi-automatically via a "search and replace" in your favorite text editor. Also, remember to replace the "internal-pdf://" before the filename.pdf with the correct path in your computer (e.g.,  "internal-pdf://path_folder1/filename.pdf"  --> "C:/EndNote/PDFs_Folder/path_folder1/filename.pdf" in Windows, etc.).

EndNote Export settings = xml

[My EndNote Library-Converted_xml.txt](https://github.com/JabRef/jabref/files/4398179/My.EndNote.Library-Converted_xml.txt)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by Aloofwisdom**
Fixes #6199  
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

## Summary of Issue 6199
When users import EndNote type xml to Jabref, it always assumes that urls are warped inside a style tag. However,  some urls may not be wrapped in a style tag and as a result,  Jabref cannot parses them.

## Way to Fix
In the xsd file, I change the the complexType's attribute to `mix="true"`, so that it can accept both vanilla text and subelements. Then I will check whether a style tag exists: if it does, use the text inside it; otherwise, use vanilla text instead.

### CODE REVIEW

File: src/main/java/org/jabref/logic/importer/fileformat/EndnoteXmlImporter.java [hunk 1]
```diff
@@ -260,10 +260,32 @@ private EntryType getType(Record record) {
     }
 
     private Optional<String> getUrlValue(Url url) {
-        return Optional.ofNullable(url)
-                       .map(Url::getStyle)
-                       .map(Style::getContent)
-                       .map(this::clean);
+        Optional<List<Object>> urlContent = Optional.ofNullable(url).map(Url::getContent);
+        List<Object> list = urlContent.orElse(null);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fileformat/EndnoteXmlImporter.java:264]:
```suggestion
        List<Object> list = urlContent.orElse(Collections.emptyList());
```
This has the advantage that you can omit the null check and just check for empty

File: src/main/resources/xjc/endnote/endnote.xsd [hunk 2]
```diff
@@ -668,7 +668,7 @@
         </xs:complexType>
     </xs:element>
     <xs:element name="url">
-        <xs:complexType>
+        <xs:complexType mixed="true">
```
Comment (Siedlerchr) [inline src/main/resources/xjc/endnote/endnote.xsd:671]: Ah cool, did not know about this!

**Review by Siedlerchr — APPROVED** [review]
Just a minor code improvement, but otherwise looks good to me!
That will benefit a lot of users!

File: src/main/java/org/jabref/logic/importer/fileformat/EndnoteXmlImporter.java (hunk 1 above)
Comment (Aloofwisdom) [reply src/main/java/org/jabref/logic/importer/fileformat/EndnoteXmlImporter.java]: Yes, indeed. It can also avoid some underlying mistakes. Already changed.

File: src/main/resources/xjc/endnote/endnote.xsd (hunk 2 above)
Comment (Aloofwisdom) [reply src/main/resources/xjc/endnote/endnote.xsd:671]: Yah, it's funny. I just knew that when I was looking up some relevant docs yesterday.

**Comment by Aloofwisdom** [comment]
> Just a minor code improvement, but otherwise looks good to me!
> That will benefit a lot of users!

I kind of messed up the previous commits. So I have incorporated your suggestion in the latest commit b1c3f75ac122c23161437e89df4fbde6fd90657f, please check.

**Comment by Siedlerchr** [comment]
@Aloofwisdom  please have a look at the checkstyle test. You can also see the comments from reviewdog when you look at the Files changed tab

**Comment by Aloofwisdom** [comment]
> @Aloofwisdom please have a look at the checkstyle test. You can also see the comments from reviewdog when you look at the Files changed tab

I could pass the CheckStyle locally now. Please check again.

File: src/main/resources/xjc/endnote/endnote.xsd (hunk 2 above)
Comment (koppor) [reply src/main/resources/xjc/endnote/endnote.xsd:671]: Does anyone know whether there is a globally updated "endnote.xsd"?

I am of the community believing that schema schecking is a good thing (json schema, xml schema, ...). (Side note: some say that even the schema should be sent along with the message: https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement#)

If a third party releases an schema for their data meaning that data produced by their software can be read in case it conforms to that schema, I would not try to change that schema.

Google lead me to https://forums.zotero.org/discussion/26493/endnote-xml-export-import - however, this his very outdated. Maybe, endnote.xsd is not maintained anymore and we can go ahead to create a fork?

I just wanted to double check.

Comment (Aloofwisdom) [reply src/main/resources/xjc/endnote/endnote.xsd:671]: Do you mean a globally standardized version of "endnote.xsd"? 

I do not know much about it yet. But sending messages with its corresponding schema is indeed reasonable in order to parse the info correctedly.

Comment (Siedlerchr) [reply src/main/resources/xjc/endnote/endnote.xsd:671]: Endnote only has a dtd not an xsd https://support.clarivate.com/Endnote/s/article/EndNote-XML-Document-Type-Definition?language=en_US
Seems like the xsd was somehow generated from an xml file. The xsd has been in JabRef since ages

**Comment by Siedlerchr** [comment]
Thanks a lot for your contribution!
