### PR TITLE
Prevent group expansion arrow from activating group when expanding or collapsing

### LINKED ISSUE #3176: Unexpected behaviour: Groups search - Item assignment
JabRef 4.0-dev--snapshot--2017-08-31--master--54e0994ba
Windows 10 10.0 amd64 
Java 1.8.0_141

Steps to reproduce:

1. Search for an group in your database using the new group search feature.
2. Select an item that is assigned to this group in the main table. The item is now marked in blue.
3. Search for another group in your database (your currently selected item should not belong to this group).
4. Select the other group you just searched for in the groups panel.
5. The item, that previously had been selected in the main table (as indicated by the blue colour and its appearance at the top of the main table items), is no longer selected/visible. Instead the items of the newly selected group are visible.

This behaviour is unexpected, as it does not allow you to quickly assign one item by using the groups search feature (i. e., search group -> select item -> search another group -> assign item to it). Instead you have to assign the group the "old-fashioned" way, i. e. either by drag'n'dropping it to the group of interest OR by using the menu associated with the group OR using both the item and the group search feature.
Just using the groups search feature alone won't do the trick, currently.

### PR DESCRIPTION
**Pull request by LIM0000**
## Proposal solution: Prevent group activation/select when user clicks on group expanding or collapsing arrow
Fixes: #7982 
Fixes #3176 
```
if (event.getButton() == MouseButton.SECONDARY || event.getTarget() instanceof StackPane) {
          // Prevent right-click to select group
          event.consume();
}
```

https://user-images.githubusercontent.com/49628911/167790196-3190698a-dafb-4752-9807-6b790f0f9277.mp4

## Further discussion
It might not be a good idea to only check eventTarget that returns StackPane class, as the group expand arrow is the only column that is using the StackPane class at current JabRef version. Any feedbacks are much appreciated!

## PR Checklist:

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by ThiloteE** [comment]
Fixes #7982
Fixes #3176

@LIM0000 did you know about [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)? :-)

**Comment by calixtus** [comment]
I like the basic idea, I'm just thinking if "instanceof StackPane" is determined enough to prevent other side effects (e.g. the hits badge is a StackPane too)
Maybe you can test on the styleclass "tree-disclosure-node" as well?

**Comment by LIM0000** [comment]
Thank you for your review @calixtus.

I agree that just `instanceof StackPane` is not determined enough. I have fixed this issue in the latest commit by confirming if the targeted StackPane has either `arrow` or `tree-disclosure-node` style class.

The reason that `tree-disclosure-node` included is because StackPane `arrow` style class has a very small clickable area. It will be very tedious to click directly onto the `arrow` icon and prevent activating group.

Clickable area if only include `arrow`


Clickable area (red) if include both `area` and `tree-disclosure-node`

File: src/main/java/org/jabref/gui/groups/GroupTreeView.java [hunk 1]
```diff
@@ -266,7 +266,11 @@ private void initialize() {
                             .map(this::createContextMenuForGroup)
                             .orElse((ContextMenu) null));
             row.addEventFilter(MouseEvent.MOUSE_PRESSED, event -> {
-                if (event.getButton() == MouseButton.SECONDARY || event.getTarget() instanceof StackPane) {
+                if (event.getTarget() instanceof StackPane) {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeView.java]: Use pattern matching to avoid unnecessary casts

if (event.getTarget() instanceof StackPane pane) {

File: src/main/java/org/jabref/gui/groups/GroupTreeView.java [hunk 2]
```diff
@@ -269,6 +269,10 @@ private void initialize() {
                 if (event.getButton() == MouseButton.SECONDARY) {
                     // Prevent right-click to select group
                     event.consume();
+                } else if (event.getTarget() instanceof StackPane pane) {
+                    if (pane.getStyleClass().toString().equals("arrow") || pane.getStyleClass().toString().equals("tree-disclosure-node")) {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeView.java:273]: Maybe it's better to check for contains, because there could also be multiple style classes assigned.

Comment (LIM0000) [reply src/main/java/org/jabref/gui/groups/GroupTreeView.java]: Thanks @calixtus , it has been updated with contains().
Really appreciate your review!

**Comment by Siedlerchr** [comment]
LGTM! Is this fix also for https://github.com/JabRef/jabref/issues/3176  ?

**Review by Siedlerchr — APPROVED** [review]

**Comment by LIM0000** [comment]
Hi @Siedlerchr , I believe that #3176 has also been fixed based on https://github.com/JabRef/jabref/issues/7982#issuecomment-991681611 and https://github.com/JabRef/jabref/issues/7982#issuecomment-899127870.
I have updated CHANGELOG.md file that stated fixes for #7982 and #3176.
Cheers.

**Comment by Siedlerchr** [comment]
Thanks again for your contributions! Superb so far! We really appreciate your engagement

**Comment by credmond** [comment]
Hey @Siedlerchr @LIM0000 

This fix/improvement has been reversed/broken by this commit:

https://github.com/jabref/jabref/commit/bc662cbbdbfe1b448ab872e8a81adada328a6c57

...because the event is being intercepted and consumed, now via an EventHandler (bubbling phase) rather than capture phase, as was previous. So it's too late, the node has already been selected as before.

E.g., row.addEventFilter(MouseEvent.MOUSE_PRESSED ...) is gone with the re-factor in the above link.

**Comment by Siedlerchr** [comment]
Thanks for the hint. Feel free to create a PR with a fix

Cormac Redmond ***@***.***> schrieb am Mo., 24. Juli 2023,
02:03:

**Comment by credmond** [comment]
@Siedlerchr, done: https://github.com/JabRef/jabref/pull/10111
