### PR TITLE
Fix Drag and Drop on empty database

### LINKED ISSUE #6487: Opening BibTex file (doubleclick) from Folder with spaces not working
When double click a BibTeX file in the file browser, then JabRef opens with message “File not found”.
The file opens only through the menu of Jabref: File–> Open…
That happens after the last upgrade.

### PR DESCRIPTION
**Pull request by MootezSaaD**
Fixes #6487
Did as @Siedlerchr mentioned, I have added the drag and drop listeners to jabref's frame.
However, I could not reproduce the first part of the issue (double-clicking on the bib file), it works on my side, that is why I have opened a draft PR.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 1]
```diff
@@ -202,6 +202,31 @@ private void initDragAndDrop() {
                     .filter(node -> node.getStyleClass().contains("tab-header-area"))
                     .findFirst()
                     .orElseThrow();
+            // Add drag and drop listeners to JabRefFrame
+            this.getScene().setOnDragOver(event -> {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/JabRefFrame.java:206]: I think the similar code for the `tabHeaderArea` below can now be removed, since this is handled on the scene level. Right?

Comment (MootezSaaD) [reply src/main/java/org/jabref/gui/JabRefFrame.java:206]: Yes you are right, I have deleted the unnecessary code.

**Comment by MootezSaaD** [comment]
Regarding the other point, when you drop a bib file in an opened db it would add the entries to that db.

File: CHANGELOG.md [hunk 2]
```diff
@@ -69,6 +69,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where the library sort order was lost. [#6091](https://github.com/JabRef/jabref/issues/6091)
 - We fixed an issue where brackets in regular expressions were not working. [6469](https://github.com/JabRef/jabref/pull/6469)
 - We fixed an issue where LaTeX citations for specific commands (\autocites) of biblatex-mla were not recognized. [#6476](https://github.com/JabRef/jabref/issues/6476)
+- We fixed an issue where drag and drop was not working on empty database. []()
```
Comment (Siedlerchr) [inline CHANGELOG.md:72]:
```suggestion
- We fixed an issue where drag and drop was not working on empty database. [#6487](https://github.com/JabRef/jabref/issues/6487)
```

**Comment by koppor** [comment]
Related: https://github.com/JabRef/jabref/issues/121#issuecomment-368215205
