### PR TITLE
Fix disable some actions when no libraries are open

### LINKED ISSUE #11923: Disable some actions when no libraries are open
When no libraries are open in JabRef, some actions remain active but should be disabled, as they depend on an open library to function.

## Actions to disable:
- [ ] File → Save all
  Image
- [ ] Library → New entry from plain text
  Image
- [ ] Global search button
  Image
- [ ] New article button
  Image

### PR DESCRIPTION
**Pull request by lzmmxh**
This PR improves the user interface by disabling certain menu items and toolbar buttons when no library is open.

"Save All" menu item in MainMenu.java is now disabled (greyed out) when there are no open libraries.
"New entry from plain text" menu item in MainMenu.java is now disabled when there are no open libraries.
"Global Search" bar in the main toolbar (MainToolBar.java) is now disabled when there are no open libraries.
"New entry from plain text" button in the main toolbar (MainToolBar.java) is now disabled when there are no open libraries.

## Here's the demo video:
https://github.com/user-attachments/assets/9fb688e5-5dbb-4e20-9f16-b0bf33f691d3

Closes #11923

https://github.com/JabRef/jabref/issues/11923

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by lzmmxh** [comment]
Hi Kopp , I believe t this is the final version. Can I merge it?       (✖﹏✖)

**Comment by Siedlerchr** [comment]
PLEASE KEEP THIS PR OPEN; YOU CAN PUSH CHANGES TO THIS BRANCH AND THE PR WILL BE UPDATED AUTOMATICALLLY

**Review by koppor — APPROVED** [review]
Code looks good. Needs to be trled out.

Maybe automated tests could be done wlth TestFX.

**Comment by koppor** [comment]
> Hi Kopp , I believe t this is the final version. Can I merge it?       (✖﹏✖)

We will review it. If it is OK, we will add to the merge queue. If not OK, you will receive comments and should adress it. Just push to your branch then; the PR will be updated. No need to open a new PR.

**Review by Siedlerchr — APPROVED** [review]
tested ,works fine

File: src/main/java/org/jabref/gui/frame/MainMenu.java [hunk 1]
```diff
@@ -146,13 +147,19 @@ private void createMenu() {
         Menu tools = new Menu(Localization.lang("Tools"));
         Menu help = new Menu(Localization.lang("Help"));
 
+        MenuItem saveAllMenuItem = factory.createMenuItem(StandardActions.SAVE_ALL, new SaveAllAction(frame::getLibraryTabs, preferences, dialogService));
+        saveAllMenuItem.disableProperty().bind(Bindings.isEmpty(stateManager.getOpenDatabases()));
+
+        MenuItem newEntryFromPlainTextMenuItem = factory.createMenuItem(StandardActions.NEW_ENTRY_FROM_PLAIN_TEXT, new PlainCitationParserAction(dialogService));
+        newEntryFromPlainTextMenuItem.disableProperty().bind(Bindings.isEmpty(stateManager.getOpenDatabases()));
+
```
Comment (LoayGhreeb) [inline src/main/java/org/jabref/gui/frame/MainMenu.java:155]: Hello @lzmmxh, thank you for your contribution!

Next time, when you're working on any issue, I recommend taking some time to explore the codebase and look for similar patterns related to what you're working on; especially for "good first issues". These issues are designed to help new contributors get familiar with the code.

If you check the codebase, you'll find similar functionality relevant to this issue. We're asking to disable the "Save All" menu item, and you'll see that the "Save" menu item is already disabled as expected. By looking at how the "Save" option is disabled, you can apply the same approach to this task.

I'm not happy with the changes in this pull request, and they will be reverted in PR #11941.
