### PR TITLE
Fix Intel crash in ThemeManager on macOS

### LINKED ISSUE #13536: JabRef does not start on Intel macs
Known good commit: https://github.com/JabRef/jabref/commit/8b1322545ae7ee34ea9361aa12a46c784d705ab0

This one is also good https://github.com/JabRef/jabref/commit/2c8615ecd81080675272f6c2dfd9285385b03065 (one needs to do some checout magic to get it working)

First bad commit: https://github.com/JabRef/jabref/pull/13386

First reported at https://github.com/Kaan0029/jabref/issues/1

---

Proposal:

Add a catch for a RuntimeException at theme switching - and just log an error. Do not crash complete JabRef.

### PR DESCRIPTION
**Pull request by Kaan0029**
- Add try/catch around themeWindowManager.install() to handle RuntimeException
- Prevents crash when native libraries are incompatible with ARM64 architecture
- Fixes #13536

Closes https://github.com/JabRef/jabref/issues/13536

## Changes
- Added try/catch block around `themeWindowManager.install(scene)` in ThemeManager
- Prevents RuntimeException crash when native libraries are incompatible with ARM64 architecture

## Testing
- [x] Tested on macOS ARM64 - no longer crashes on startup
- [x] Build passes successfully
- [x] Application starts and runs normally

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java [hunk 1]
```diff
@@ -121,7 +121,11 @@ private void applyDarkModeToWindow(Stage stage, boolean darkMode) {
             return;
         }
 
-        themeWindowManager.setDarkModeForWindowFrame(stage, darkMode);
+        try {
+            themeWindowManager.setDarkModeForWindowFrame(stage, darkMode);
```
Comment (Siedlerchr) [inline jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java:126]: Wrap the         this.themeWindowManager = ThemeWindowManagerFactory.create() also in an expcetion blog

File: CHANGELOG.md [hunk 2]
```diff
@@ -75,6 +75,7 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
 - When creating a library, if you drag a PDF file containing only a single column, the dialog will now automatically close. [#13262](https://github.com/JabRef/jabref/issues/13262)
 - We fixed an issue where the tab showing the fulltext search results would appear blank after switching library. [#13241](https://github.com/JabRef/jabref/issues/13241)
 - Enhanced field selection logic in the Merge Entries dialog when fetching from DOI to prefer valid years and entry types. [#12549](https://github.com/JabRef/jabref/issues/12549)
+- We fixed an issue where JabRef crashed on startup on Apple Silicon Macs due to native library compatibility issues in the theme manager. [#13536](https://github.com/JabRef/jabref/issues/13536)
```
Comment (koppor) [inline CHANGELOG.md]: No need; feature was introduced after the last release

File: jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java [hunk 3]
```diff
@@ -73,7 +73,13 @@ public ThemeManager(WorkspacePreferences workspacePreferences,
         this.workspacePreferences = Objects.requireNonNull(workspacePreferences);
         this.fileUpdateMonitor = Objects.requireNonNull(fileUpdateMonitor);
         this.updateRunner = Objects.requireNonNull(updateRunner);
-        this.themeWindowManager = ThemeWindowManagerFactory.create();
+        ThemeWindowManager tempThemeWindowManager = null;
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java]: We do not use "temp" prefix in JabRef. Do without. 

With "this." you have the different scoping.

Maybe do without local variable and in the catch block set to null?

File: jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java [hunk 4]
```diff
@@ -73,7 +73,13 @@ public ThemeManager(WorkspacePreferences workspacePreferences,
...
+        try {
+            tempThemeWindowManager = ThemeWindowManagerFactory.create();
+        } catch (UnsatisfiedLinkError | RuntimeException e) {
+            LOGGER.error("Failed to create ThemeWindowManager (likely due to native library compatibility issues on ARM64)", e);
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java]: Do debug instead of warn

It's Intel and not ARM

**Review by koppor — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 2 above)
Comment (koppor) [reply CHANGELOG.md]: What I mean, remove this!

**Review by koppor — CHANGES_REQUESTED** [review]
Please adress my comments.

**Comment by subhramit** [comment]
> [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)

Why is this ticked if there is no changelog entry (at least at the time of writing this)?

File: jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java [hunk 5]
```diff
@@ -58,7 +58,7 @@ public class ThemeManager {
     private final WorkspacePreferences workspacePreferences;
     private final FileUpdateMonitor fileUpdateMonitor;
     private final Consumer<Runnable> updateRunner;
-    private final ThemeWindowManager themeWindowManager;
+    private ThemeWindowManager themeWindowManager;
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/theme/ThemeManager.java]: Add `@Nullable`; because we don't use `Optionals` in class variables; do we @Siedlerchr

**Comment by koppor** [comment]
Follow-up issue: https://github.com/dukke/FXThemes/issues/14

**Comment by koppor** [comment]
I think, we have a different understanding of "Manually tested" and "fixed"

If I open preferences, I get an exception:

IMG_20250723_134013_883 (Medium)

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
I fixed all the issues

- unnecessary `null`  check - library never returns null (found by ctrl+click on `create` and reading the 20 lines of code there)
- preference opening and changing the mode works.

Since external contributors rely on the issue, I go ahead with merging.
