### PR TITLE
Fix: Keyboard shortcuts cannot be edited in Preferences (closes #14237)

### LINKED ISSUE #14237: Unable to change any keyboard shortcut
### JabRef version

5.15 (latest release)

### Operating system

macOS

### Details on version and operating system

Tahoe 26.0.1 (25A362)

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open Jabref
2. Select File > Preferences > Keyboard shortcuts
3. Select any Entry, e.g. File > Close Library
4. Click on the entry OR Right click on the entry OR double click on the entry
5. Type the key / key combination that you want instead for this action
6. See bug: Nothing happens

### Appendix

I'm not entirely sure how the keybindings are supposed to be customized (see step 5), but I cannot get any alternative keybinding to get registered for any action.
The documentation doesn't help: https://github.com/JabRef/user-documentation/blob/main/en/setup/customkeybindings.md

<summary>Log File</summary>

```
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Column type '' is unknown.
Preferences recorded.
Loaded journal abbreviations from /var/folders/h8/0qhzg4jx4vqcssrpvr04qfvh0000gn/T/jabref-journal17856100271165778619/journal-list.mv
```

</details>

### PR DESCRIPTION
**Pull request by AmandaBalderas20**
Closes #14237

I fixed an issue where keyboard shortcuts could not be edited in:
Preferences → Keyboard shortcuts.

The KeyEvent was being consumed by global application shortcuts before reaching
the shortcut editor in the KeyBindingsTab. As a result, pressing keys did not
update the selected shortcut, and changes were not persisted.

This PR adds:
- A key event filter in KeyBindingsTab to ensure the TreeTableView receives key presses.
- Logic to forward the event to the ViewModel (setNewBindingForCurrent).
- Correct persistence of edited shortcuts by syncing the repository into GuiPreferences.
- An updated JUnit test verifying the binding update behavior.

---

### Steps to test

1. Open JabRef → Preferences → Keyboard shortcuts.
2. Select any shortcut entry (e.g., “Close library”).
3. Press a new key combination (e.g., Ctrl+Shift+L).
4. Click **Save**.
5. Restart JabRef.
6. Verify that:
   - The new shortcut appears in the list.
   - The shortcut works in the application (e.g., Ctrl+Shift+L closes the library).

Screenshots visible changes are not required since UI remains the same.

---

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the MIT license
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (not applicable — UI did not change)
- [x] I described the change in `CHANGELOG.md` 
- [/] I checked the user documentation: no updates required since UI workflow remains identical

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks a lot for your PR, please check the failing tests in KeyBindingsTabModelTest. Maybe they need to be adapted?

**Comment by AmandaBalderas20** [comment]
I validated the functionality by running the tests individually and as a group using the following commands:
```
./gradlew :jabgui:test --tests "org.jabref.gui.preferences.keybindings.KeyBindingViewModelTest"

./gradlew :jabgui:test --tests "org.jabref.gui.preferences.keybindings.KeyBindingViewModelTest.resetToDefault"

./gradlew :jabgui:test --tests "org.jabref.gui.preferences.keybindings.KeyBindingViewModelTest.verifyStoreSettingsWritesChanges"
```
Screenshot 2025-11-17 at 11 56 29 a m

All tests executed successfully. I am not sure if there are other test cases or validation steps that I should do for this area, but everything appears correct.

File: jabgui/src/test/java/org/jabref/gui/preferences/keybindings/KeyBindingViewModelTest.java [hunk 1]
```diff
@@ -50,4 +50,40 @@ void resetToDefault() {
...
+                false
+        );
+
+        viewModel.setNewBindingForCurrent(event);
+
+        viewModel.storeSettings();
+
+        Optional<String> saved = prefsRepo.get(binding);
+        assertTrue(saved.isPresent());
+        assertTrue("ctrl+shift+L".equalsIgnoreCase(saved.get()));
```
Comment (Siedlerchr) [inline jabgui/src/test/java/org/jabref/gui/preferences/keybindings/KeyBindingViewModelTest.java]: Can you make this an assertEquals? This makes it easer to see the diff when tests fails

Comment (Siedlerchr) [reply jabgui/src/test/java/org/jabref/gui/preferences/keybindings/KeyBindingViewModelTest.java]: You can just do assertEquals(Optional.of("...."), saved)

**Comment by Siedlerchr** [comment]
Tess work for me on mac as well.

**Comment by koppor** [comment]
> * [/] I described the change in `CHANGELOG.md` (not applicable — minor behavior fix)

No - you fixed an issue. Please add a line - you can ref the issue there https://github.com/JabRef/jabref/issues/14237

**Review by Siedlerchr — DISMISSED** [review]

**Comment by Siedlerchr** [comment]
KeyBindingsTabModelTest fails. I cannot verfiy it because there is an assumeFalse(OSX) inside, so the tests do not run on mac

**Comment by koppor** [comment]
Locally

```
> Task :jabgui:test
org.jabref.gui.keyboard.KeyBindingsTabModelTest setSingleKeyBindingToDefault() FAILED

  org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
      at app/org.jabref/org.jabref.gui.keyboard.KeyBindingsTabModelTest.setSingleKeyBindingToDefault(KeyBindingsTabModelTest.java:173)

org.jabref.gui.keyboard.KeyBindingsTabModelTest setAllKeyBindingsToDefault() FAILED

  org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
      at app/org.jabref/org.jabref.gui.keyboard.KeyBindingsTabModelTest.setAllKeyBindingsToDefault(KeyBindingsTabModelTest.java:140)
````

Not sure how to proceed

- A: Think why tests could fail and fix the tests/logic
- B: Disable tests - and document why the test could fail
- C: Just disable tests

**Comment by AmandaBalderas20** [comment]
I reviewed it and I think the failing tests in KeyBindingsTabModelTest expect hasChanged to be false after resetting a key binding.
After fixing #14237, changing a binding and then resetting it still counts as a modification, so the correct final value is true.
I can update those two tests to assert true instead of false to match the new behavior. Is that okay?

**Comment by Siedlerchr** [comment]
It would be great if you add this as comment to the test somehow

**Comment by AmandaBalderas20** [comment]
Okay, so I’ll update the tests and add a comment explaining why hasChanged() is now expected to be true after a reset (because of the fix for #14237)

File: jabgui/src/test/java/org/jabref/gui/preferences/keybindings/KeyBindingViewModelTest.java [hunk 2]
```diff
@@ -86,7 +87,6 @@ void verifyStoreSettingsWritesChanges() {
         viewModel.storeSettings();
 
         Optional<String> saved = prefsRepo.get(binding);
-        assertTrue(saved.isPresent());
-        assertTrue("ctrl+shift+L".equalsIgnoreCase(saved.get()));
+        assertEquals(Optional.of("ctrl+shift+L"), saved);
```
Comment (koppor) [inline jabgui/src/test/java/org/jabref/gui/preferences/keybindings/KeyBindingViewModelTest.java]: Thank you for this, too!

**Comment by Scroogeee** [comment]
Does not seem to fix the issue on

JabRef 6.0-alpha.194--2025-11-24--5e08c82
Mac OS X 26.1 aarch64 
Java 24.0.2 
JavaFX 25.0.1+3

New keycombinations are ignored. How are they supposed to be entered?

**Comment by Siedlerchr** [comment]
@Scroogeee 
Might be a bit unintuitive.
Click on the clear icon (the broom), then press your new key combination

**Comment by Scroogeee** [comment]
I did try doing it on JabRef 6.0-PullRequest14057.266--2025-11-28--a581582
Mac OS X 26.1 aarch64 
Java 25.0.1 
JavaFX 25.0.1+3; 
and
JabRef 6.0-alpha.226--2025-11-29--9087e17
Mac OS X 26.1 x86_64 
Java 24.0.2 
JavaFX 25.0.1+3

the broom clears the combination, but the new key combination is ignored

**Comment by Siedlerchr** [comment]
@Scroogeee  Sorry for the late reply. For me it worked. Just maybe a thing, if you want to have a shortcut using command key, you need to press ctrl key instead. It will be automatically mapped to command under the hood

**Comment by koppor** [comment]
> @Scroogeee Sorry for the late reply. For me it worked. Just maybe a thing, if you want to have a shortcut using command key, you need to press ctrl key instead. It will be automatically mapped to command under the hood

Should we add this as hint at the dialog somehow? It is strange that keys are remapped somehow? I assume, this is only the case at JabRef - or is this a general issue happening in all apps?

**Comment by Siedlerchr** [comment]
Yeah somehow at the dialog this would be helpful. 
The key remapping internally is natural. As a Mac user, you don't want to press ctrl + c you press cmd + c but as jabref keybindings are designed for every OS 

https://github.com/JabRef/jabref/blob/518f61f4fc13fa4aed1b750765dc0765b3bc7a90/jabgui/src/main/java/org/jabref/gui/keyboard/KeyBindingRepository.java#L154-L163 


But it seems like javafx supports **shortcut** key for such cases
>  The shortcut modifier is used to represent the modifier key which is used commonly in keyboard shortcuts on the host platform. This is for example control on Windows and meta (command key) on Mac. By using shortcut key modifier developers can create platform independent shortcuts. So the "Shortcut+C" key combination is handled internally as "Ctrl+C" on Windows and "Meta+C" on Mac.

https://openjfx.io/javadoc/24/javafx.graphics/javafx/scene/input/KeyCombination.html

**Comment by Siedlerchr** [comment]
Key remapping is no longer need thanks to javafx shortcuts, folllow up in https://github.com/JabRef/jabref/pull/14684
