### PR TITLE
Fix for issue 9362 part 4 - Global Search window retains size

### LINKED ISSUE #9362: Global Search: Clicking an entry in the search window should lead to a selection in the corresponding library
Issues left:

- [x] Preview in dark theme when no search results is still "white"
   image
- [x] Location of the pin to top button 
    image
- [ ]  When clicking an entry in the search window, it should be marked in the corresponding library (JabRef should focus the library and then select the item in the main table)
- [x] Search dialog has to retain size (-> store size in preferences)
- [ ] ~~Debatable: If the columns such as status or relevant should NOT be shown, because one could theoretically change the value of them in the search window...~~

_Originally posted by @Siedlerchr in https://github.com/JabRef/jabref/issues/8054#issuecomment-985783685_

### PR DESCRIPTION
**Pull request by JawadTUE**
Fixes #9362 
When the global search window is resized and closed (by pressing the close button or the OK button) the window size gets stored in searchPreferences. Upon reopening, the last size is used again.

Global search window opened
sc_9362_1

Global search window resized and closed
sc_9362_2

The window will have the same size the next time it is opened.

Question: does the window have to be placed in the center of the screen when opened? Now it is not the case, but when the window size gets to big and it is reopened, it gets out of the screen. I can fix this as well if you want.

```[tasklist]
### Compulsory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

File: src/main/java/org/jabref/gui/search/GlobalSearchResultDialogViewModel.java [hunk 1]
```diff
@@ -29,4 +35,17 @@ public BibDatabaseContext getSearchDatabaseContext() {
...
+    }
+
+    public int searchWindowWidth() {
+        return this.searchWindowWidth.get();
+    }
+
+    public void updateWindowSize(int height, int width) {
+        searchPreferences.setSearchWindowHeight(height);
+        searchPreferences.setSearchWindowWidth(width);
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/search/GlobalSearchResultDialogViewModel.java:50]: Why don't you directly bind the properties in SearchPreferences to the view? The window size should not be handled in the view model, which must be completly indepentend of the view.

File: src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java [hunk 2]
```diff
@@ -76,5 +77,14 @@ private void initialize() {
                     ? IconTheme.JabRefIcons.KEEP_ON_TOP.getGraphicNode()
                     : IconTheme.JabRefIcons.KEEP_ON_TOP_OFF.getGraphicNode());
         });
+
+        getDialogPane().getScene().getWindow().addEventHandler(WindowEvent.WINDOW_SHOWN, event -> {
+            getDialogPane().setPrefHeight(viewModel.searchWindowHeight());
+            getDialogPane().setPrefWidth(viewModel.searchWindowWidth());
+        });
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java:84]: `bindBidirectional` to SearchPreferences?

Comment (JawadTUE) [reply src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java]: I am not sure what you mean. Could you please elaborate?

File: src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java [hunk 3]
```diff
@@ -76,5 +77,15 @@ private void initialize() {
...
+
+        getDialogPane().getScene().getWindow().addEventHandler(WindowEvent.WINDOW_SHOWN, event -> {
+            getDialogPane().setPrefHeight(preferencesService.getSearchPreferences().getSearchWindowHeight());
+            getDialogPane().setPrefWidth(preferencesService.getSearchPreferences().getSearchWindowWidth());
+        });
+
+        getDialogPane().getScene().getWindow().addEventHandler(WindowEvent.WINDOW_HIDDEN, event -> {
+            preferencesService.getSearchPreferences().setSearchWindowHeight((int) getHeight());
+            preferencesService.getSearchPreferences().setSearchWindowWidth((int) getWidth());
+        });
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java:89]:
```suggestion
        setWidth(preferencesService.getSearchPreferences().getSearchWindowWidth());
        setHeight(preferencesService.getSearchPreferences().getSearchWindowHeight());

        getDialogPane().getScene().getWindow().addEventHandler(WindowEvent.WINDOW_HIDDEN, event -> {
            preferencesService.getSearchPreferences().setSearchWindowHeight(getHeight());
            preferencesService.getSearchPreferences().setSearchWindowWidth(getWidth());
        });
```

Comment (calixtus) [reply src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java:89]: Height and width should be stored as doubles as they are kept by javafx as doubles to avoid casting.

Comment (JawadTUE) [reply src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java]: For some reason, window size is not retained when doing it that way.

Comment (JawadTUE) [reply src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java]: First of all, the `setWidth()` and `setHeight()` do not change the size of the dialog window. This has to be done with `getDialogPane().setPrefHeight()` and `getDialogPane().setPrefWidth()`. 

Also, when setting the size of the window as in the suggestion of @calixtus, it does not actually change the window size. It only works when adding an event handler to the window. This event handler sets the size of the window when the `WINDOW_SHOWN` event occurs, hence when the window is opened. 

My current solution does correctly retain the size of the window.

Comment (calixtus) [reply src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java]: hm... was experimenting a little bit on my machine. must have missed something. good to know you could clear that.

**Review by Siedlerchr — APPROVED** [review]

File: src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java (hunk 3 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/search/GlobalSearchResultDialog.java]: Thanks for the info! I'm fine with the changes now
