### PR TITLE
Readability for citation key patterns

### LINKED ISSUE #3920: latex_to_unicode produces problematic filename
I encountered this when retrieving information for `doi:10.1088/1752-7155/7/1/017106`.
Which retrieves the authors: `Patrik {\v{S}}pan{\v{e}}l and Kseniya Dryahina and David Smith`.

A cleanup/rename pdf gives following filename: `S}pane{l}EtAl/Spanel2013 - A quantitative study.pdf` (note the braces are produced like this) which not only is wrong, but also gives an error: `Could not save file. Error in field 'file': Braces don't match.`

I have directory pattern set to: `[authEtAl:latex_to_unicode]` and file format pattern set to `[bibtexkey] - [shorttitle:latex_to_unicode]`. And bibtex key pattern is: `[auth:latex_to_unicode][year]`.  Also note that the bibtex key doesn't contain any `}`.

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Fixes #3920. 

The issue is that `AuthorList#fixAuthorForAlphabetization` is used to create a `String` representation of authors' names. This can leave unbalanced brackets if a name piece starts with a latex command, as it is not the intended use of the method.

The suggested fix is to resolve latex in the name of an author and then remove any illegal characters in the post-processing (which is dependent on if it is going to be used as a file path or citation key). As Unicode characters are already allowed in the name of an author, this change should not affect users too much. It will, however,
* have slower performance, as all authors are being processed as if they contain latex
* **in almost all cases that contain latex, it will produce different output than the previous solution**

**As always, these are only suggestions. Any comments and criticism are encouraged!**
The "intuition" behind the suggestion is that latex in Strings will always be hard to deal with, and I think most users expect a pattern to resolve to something as similar as possible to what is shown in the main table.

**What remains**
- [x] verify that the `CitationKeyGenerator` does not output Unicode keys
- [x] ~remove the `latex_to_unicode` modifier as it should not be used~
- [x] change access modifiers for methods in `BracketedPattern`, I'd suggest that most should be private or protected
- [x] ~change how arguments are parsed for `auth.../ed...` patterns (readability)~
- [x] add test cases for this issue
- [x] test for character classes in regexp
- [ ] Fix parsing of bracketed patterns
- [ ] Fix the conversion of unicode to characters allowed in bibtex keys in `CitationKeyGenerator`

- [ ] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java [hunk 1]
```diff
@@ -707,102 +707,97 @@ public static String lastAuthorForenameInitials(String authorField) {
...
+     * @param authorList an {@link AuthorList}
+     * @return the initials of all authors' names
      */
-    public static String authorsAlpha(String authorField) {
-        String authors = "";
+    public static String authorsAlpha(AuthorList authorList) {
+        StringBuilder authors = new StringBuilder();
 
-        String fixedAuthors = AuthorList.fixAuthorLastNameOnlyCommas(authorField, false);
+        String[] tokens = authorList.getAuthors().stream().map(Author::getLastOnly).toArray(String[]::new);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java:726]: Can probably be a lost

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java]: Good point. I tried adding what is hopefully some readability improvements as well.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
A test case for this particular issue (where starting brackets can cause a problem) will be added! It is just taking a bit of time since I haven't been able to spend as much time on this as I would have wanted 🙁 
I'd argue that it is motivated to make several methods in `BracketedPattern` private, but then test cases in `CitationKeyGeneratorTest` depends on them being public -> a lot of refactoring.

> For your discussion of the consequences, maybe an [ADR](https://adr.github.io/madr/) could be the proper format.

I should have written most of the pull request in ADR format?

File: src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java [hunk 2]
```diff
@@ -1094,4 +1094,20 @@ void generateKeyWithWithFirstNCharacters() {
 
         assertEquals("newt-2019", generateKey(entry, "[auth4:lower]-[year]"));
     }
+
+    @Test
+    void generateKeyCorrectKeyLengthWithTruncateModifierAndUnicode() {
+        BibEntry bibEntry = new BibEntry();
+        bibEntry.setField(StandardField.AUTHOR, "Gödel, Kurt");
+
+        assertEquals(2, generateKey(bibEntry, "[auth:truncate2").length());
```
Comment (koppor) [inline src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java:1103]: Is there a missing bracket at the end?

```suggestion
        assertEquals(2, generateKey(bibEntry, "[auth:truncate2]").length());
```

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java]: There is indeed. Should the missing bracket generate an error or should I leave it alone?

File: src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java [hunk 3]
```diff
@@ -420,14 +396,50 @@ public static String getFieldValue(BibEntry entry, String value, Character keywo
...
+                    lastName,
+                    author.getJr().map(LatexToUnicodeAdapter::format).orElse(null)
+            );
+        }
+        return authorList;
+    }
+
+    /**
+     * Checks if an author is an institution by verifying that only the last name is present.
+     * @param author the checked author
```
Comment (koppor) [inline src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java:435]: A reformat of the file should add an empty line before, shouldn't it?

File: src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java [hunk 4]
```diff
@@ -54,6 +72,12 @@ void setUp() {
         importFormatPreferences = mock(ImportFormatPreferences.class, Answers.RETURNS_DEEP_STUBS);
     }
 
+    private static BibEntry createABibEntryAuthor(String author) {
+        BibEntry bibEntry = new BibEntry();
+        bibEntry.setField(StandardField.AUTHOR, author);
```
Comment (koppor) [inline src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java:77]:
```suggestion
        return new BibEntry()
          .withField(StandardField.AUTHOR, author);
```

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
The issue of unbalanced brackets is adressed by converting all authors' names to Unicode, however, I'd benefit from a second (and/or third) opinion at this point. Several **cite key** patterns do not work as expected when names containing latex are converted to Unicode,

Example:
`[auth2]` for "Gödel" would result in "Goe".

I extended the workaround that already existed for `authN`,
https://github.com/JabRef/jabref/blob/156d22ef9d65392973a44c88c61ae42672d637fc/src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java#L900-L902
 to several other `auth`/`edt` patterns (and I will update those patterns in the documentation if this solution is acceptable).

An alternative would be to extend the workaround from `authN` to all author/editor patterns, which would give more consistent results (all authors' names will contain replacements for Unicode characters) for files, directories, and cite keys.

The issue where `BracketedPattern` can't use Unicode because of restrictions in `CitationKeyGenerator` can be avoided entirely by preprocessing the BibEntries in CitationKeyGenerator, but I don't feel I can adequately judge the advantages/disadvantages of the different solutions that would accomplish this, so I'd rather leave it to someone else if there are future issues/complaints.

**So the alternatives are,**
1. leave the behaviour as is,
2. replace all Unicode characters for patterns that requires the number of character to be known in advance,
3. replace all Unicode characters in all patterns with authors' names in.

and maybe 4th, I can continue attempting to fix this "properly" (allow unicode in all patterns for `BracketedPattern` and disallow for `CitationKeyGenerator`), but it will result in even more work for a reviewer.

File: src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java [hunk 5]
```diff
@@ -44,6 +45,7 @@
     private static final Logger LOGGER = LoggerFactory.getLogger(BracketedPattern.class);
 
     private static final int CHARS_OF_FIRST = 5;
+    private static final int MAX_ALPHA_AUTHORS = 4;
```
[the remark this answers is not in the document]
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java:48]: I will look into it! I am sure having the comment will make someone's life easier in the future so it should be there in either case, I just weren't paying enough attention.

**Comment by koppor** [comment]
(Thank you for the longer explanation. Now, I begin to understand what your are really adressing. Your PR was full of good code style improvements, which ditracted me to focus on the underlying issue.)

Context for others: The PR addresses the issue that the patterns are used for something diferent than the bibtex key generation ("label pattern"). Documentation at https://docs.jabref.org/setup/bibtexkeypatterns#key-patterns. Our patterns have "magic" built in, such as shortening EACH element to `n` letters. We don't offer a streaming approach as [crush](https://github.com/liljencrantz/crush) does (just linking for presenting an idea; not applicable as solution in this context).

I would expect following behavior:

- (i) when using in the bibtex key generator, the non-ascii characters are converted to a "good" representation (as in your example: Göd -> Goe)
- (ii) when using the pattern in other places, the unicode represation is used.

Reason: Unicode is working in the year 2020. The only exception are BibTeX keys, because the bibtex tooling is not fully UTF8 (biblatex+biber is, but not the more commonly used bibtex tool). Thus, we will have to add a separate handling here.

For case (i), the author stated `:latex_to_unicode`. As you pointed out, the length restriction won't work there.

To achieve the different handling, you already stated the solution:

>  entirely by preprocessing the BibEntries in CitationKeyGenerator

I like that! Then, the  "he workaround that already existed for `authN`" is obsolete

---

Minor issue: Is the example of https://github.com/JabRef/jabref/issues/3920 included in a test case here?

I think, this somehow refs https://github.com/koppor/jabref/issues/392.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> I think, this somehow refs [koppor#392](https://github.com/koppor/jabref/issues/392).

How? 😛 

> Minor issue: Is the example of #3920 included in a test case here?

The example relates to `BracketedPattern`, it is my "solution" of that example that make the consequences for `CitationKeyGenerator` harder to ignore, which is why my discussion is focused on that part.
https://github.com/JabRef/jabref/pull/6706/files#diff-2d88a18eec12a5bc7ee602a1bba56168R271-R277

> 
> > entirely by preprocessing the BibEntries in CitationKeyGenerator
>  

> I like that! Then, the "he workaround that already existed for `authN`" is obsolete

This is (based on my current understanding) non-trivial, which is why I haven't done it and why it would require more time from reviewers if I attempt to implement it. I'll get back with a write-up on why but it'll be somewhat lengthy.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hum, I'll give it a shot and if it is too annoying to review we can just revert it X)

File: src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java (hunk 3 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java:486]: Yes. I had not reformatted the file. I have now done so and tried to address the points where the reformatting is wrong (e.g., use ordered/unordered lists where appropriate instead of the auto-generated `<p>`). I tried fixing some of the additional warnings the file were giving as well.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> ... I have some nitpick comments, ...

Nitpicking is always welcome. I am new enough at this that a nitpicking is still a learning experience 😝 

Tell me if I should focus more on the actual issue, since it was/is tagged as a high priority bug.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I'd like som input on patterns such as `[auth[auth[auth`. Based on [the coding guidelines](https://devdocs.jabref.org/getting-into-the-code/code-howtos#throwing-and-catching-exceptions) I believe they should throw an exception and generate a warning message, is this correct?

This is relevant as "unifying" the parsing of the patterns (I'd like it in one spot, not three) will make it easier to ensure that the `Unicode -> ASCII` conversion use a valid String.

File: src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java [hunk 6]
```diff
@@ -150,229 +172,231 @@ public String expand(BibEntry bibentry, Character keywordDelimiter, BibDatabase
...
+            // If the beginning of a quote is found, append the content
+            switch (token) {
+                case "\"" -> appendQuote(bracketContent, tokenizer);
+                case "]" -> foundClosingBracket = true;
+                default -> bracketContent.append(token);
+            }
+        }
+
+        if (!foundClosingBracket) {
+            LOGGER.warn("Missing closing bracket ']' in '" + pattern + "'");
```
Comment (koppor) [inline src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java:233]:
```suggestion
            LOGGER.warn("Missing closing bracket ']' in '{}'", pattern);
```

File: src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java [hunk 7]
```diff
@@ -150,229 +172,231 @@ public String expand(BibEntry bibentry, Character keywordDelimiter, BibDatabase
...
+        } else if (bracketContent.length() == 0) {
+            LOGGER.warn("Found empty brackets \"[]\" in '" + pattern + "'");
```
Comment (koppor) [inline src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java:235]:
```suggestion
            LOGGER.warn("Found empty brackets \"[]\" in '{}'", pattern);
```

**Review by koppor — CHANGES_REQUESTED** [review]
Seeing the long list of changes, I would suggest to merge this in - and then work on the two remaining open points. - Otherwise, it will get harder and harder to review.

Nevertheless, a short nitpick on the logger.

(Sorry for review delay)

**Comment by koppor** [comment]
Is it possible to fix checkstyle? This does not look good:

> /home/runner/work/jabref/jabref/src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java:9: error: package org.jabref.model.bibtexkeypattern does not exist

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> Seeing the long list of changes, I would suggest to merge this in - and then work on the two remaining open points. - Otherwise, it will get harder and harder to review.

Sorry about that. I didn't really expect to go down this route.

After the merge I'll open up a PR for issue #6892 dealing with parsing. Once that is done I can open a PR for #3920 utilizing the changed parsing, if that is ok?

**Comment by koppor** [comment]
>> Seeing the long list of changes, I would suggest to merge this in - and then work on the two remaining open points. - Otherwise, it will get harder and harder to review. 
> Sorry about that. I didn't really expect to go down this route.

No need to be sorry. I have to thank you that you  keep working on the PR even if much time is spend on the code quality.

> After the merge I'll open up a PR for issue #6892 dealing with parsing.

Year, thank you for that!

> I realized this PR still closes issue #3920. The problem with converting unicode characters is not in the issue tracking system. I can open up a PR for it after #6892 is fixed, if that sounds reasonable?

Sure, step by step.
