### PR TITLE
Fix wrong conversion of unicode chars

### LINKED ISSUE #7387: epsilon symbol in unicode-to-latex not supported
JabRef version 5.1 on MacOs 11.1

If 𝜖 in title of a reference, it is not converted to \epsilon when selecting "cleanup" and "unicode-to-latex"

1. Get reference from doi-fetcher
2. cleanup
3. unicode-to-latex

### PR DESCRIPTION
**Pull request by tmrd993**
Fixes #7387
Fixed the wrong conversion of unicode characters with a codepoint higher than the max value of the primitive type char in the unicode to latex formatter.

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java [hunk 1]
```diff
@@ -760,7 +760,8 @@
             {"64259", "", "ffi"}, // ffi ligature (which LaTeX solves by itself)
             {"64260", "", "ffl"}, // ffl ligature (which LaTeX solves by itself)
             {"119978", "Oscr", "$\\mathcal{O}$"}, // script capital O -- possibly use \mathscr
-            {"119984", "Uscr", "$\\mathcal{U}$"} // script capital U -- possibly use \mathscr
+            {"119984", "Uscr", "$\\mathcal{U}$"}, // script capital U -- possibly use \mathscr
+            {"120598", "", "$\\epsilon}$"} // mathematical italic epsilon U+1D716 -- requires amsmath
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java:764]: I think the closing `}` is too much here.

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
Thanks a lot! Can you please also add a test that verifies that everything is working now.

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks for analyzing the issue and your fix! LGTM!
