### PR TITLE
Fixed validation before typing in new entry dialog #7020

### LINKED ISSUE #7020: Error message before starting new entry from ID
JabRef 5.2-PullRequest7008.168--2020-10-12--67c873b
Windows 10 10.0 amd64 
Java 15

The new entry dialog has always the ID field marked with red corner and red "!". But this error message makes sense only if I push Generate without putting anything in the ID field and without pushing any of the predefined entry types. But in this case the Generate button is correctly disabled. So the message can be removed because signal something that could not happen.

Steps to reproduce:

1. Start JabRef
2. Go to Library > New Entry
3. The following sign appears:
image
The sign remains even if I change the ID Type.

### PR DESCRIPTION
**Pull request by Ali96kz**
Do not show an error message if there is no error
Fixes #7020

### CODE REVIEW

**Comment by Siedlerchr** [comment]
For me this doesn't make any change, because you still have the init of the visualizer in line 178  (at the bottom of initialize)

**Comment by Ali96kz** [comment]
FIxed

File: src/main/java/org/jabref/gui/EntryTypeView.java [hunk 1]
```diff
@@ -79,7 +79,10 @@ public EntryTypeView(LibraryTab libraryTab, DialogService dialogService, Prefere
                   .load()
                   .setAsDialogPane(this);
 
-        ControlHelper.setAction(generateButton, this.getDialogPane(), event -> viewModel.runFetcherWorker());
+        ControlHelper.setAction(generateButton, this.getDialogPane(), event -> {
+            viewModel.runFetcherWorker();
+            visualizer.initVisualization(viewModel.idFieldValidationStatus(), idTextField, true);
+        });
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/EntryTypeView.java:85]: Sorry, but this does not seem to work, since the generate button is disabled by default and the validation does only check if the button isNotBlank.

Comment (Ali96kz) [reply src/main/java/org/jabref/gui/EntryTypeView.java]: Fixed,

**Review by calixtus — APPROVED** [review]
Looks good to me now. Thanks!

**Review by Siedlerchr — APPROVED** [review]

**Comment by calixtus** [comment]
Thanks for your contribution!
