### PR TITLE
Library properties: no change but.. (issue #3562)

### LINKED ISSUE #3562: Library properties: no change but...
After opening the library properties window, if you click directly on OK, the file is shown as modified while no properties was modified by the user.

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists 

JabRef 4.1-dev--snapshot--2017-12-21--master--55abd5e2e
Linux 3.11-2-amd64 amd64 
Java 1.8.0_131

Steps to reproduce:

1. File -> New bibTeX library
2. File -> Save library as...
3. Enter a file name, like test.bib
4. Click on OK
Note that, at this point, the file is not shown as modified (no star in the name tab). Which is ok.
3. File -> Library properties
4. Click on OK  (without modifying any properties)
The file is shown as modified (star in the name tab)

Nothing special in the console.

### PR DESCRIPTION
**Pull request by PJozeph**
When user wanted to lead default Library properties, after clicking OK button even though there was no modification in Library property the bibTeX tab marked as modified. I fixed this bug so no need to  worry about this anymore.  

Fixes #3562 

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/main/java/org/jabref/gui/dbproperties/DatabasePropertiesDialog.java [hunk 1]
```diff
@@ -167,13 +167,42 @@ public void actionPerformed(ActionEvent e) {
...
+        Charset newEncoding = (Charset) encoding.getSelectedItem();
+        boolean saveActionsChanged = fieldFormatterCleanupsPanel.hasChanged();
+        boolean saveOrderConfigChanged = newAndOldOrderCinfigIsSame(getNewSaveOrderConfig(), oldSaveOrderConfig);
+        boolean changed = saveOrderConfigChanged || !newEncoding.equals(oldEncoding)
+                || !oldFileVal.equals(fileDir.getText()) || !oldFileIndvVal.equals(fileDirIndv.getText())
+                || (oldProtectVal != protect.isSelected()) || saveActionsChanged;
+        return changed;
+    }
+
+    private boolean newAndOldOrderCinfigIsSame(SaveOrderConfig newSaveOrderConfig, SaveOrderConfig oldSaveOrderConfig) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/dbproperties/DatabasePropertiesDialog.java]: looks like a typo here -> cinfig -> Config

**Comment by Siedlerchr** [comment]
@JabRef/developers  A second review needs to be done

File: src/main/java/org/jabref/gui/dbproperties/DatabasePropertiesDialog.java [hunk 2]
```diff
@@ -167,13 +167,42 @@ public void actionPerformed(ActionEvent e) {
...
+        boolean saveActionsChanged = fieldFormatterCleanupsPanel.hasChanged();
+        boolean saveOrderConfigChanged = newAndOldOrderConfigIsSame(getNewSaveOrderConfig(), oldSaveOrderConfig);
+        boolean changed = saveOrderConfigChanged || !newEncoding.equals(oldEncoding)
+                || !oldFileVal.equals(fileDir.getText()) || !oldFileIndvVal.equals(fileDirIndv.getText())
+                || (oldProtectVal != protect.isSelected()) || saveActionsChanged;
+        return changed;
+    }
+
+    private boolean newAndOldOrderConfigIsSame(SaveOrderConfig newSaveOrderConfig, SaveOrderConfig oldSaveOrderConfig) {
+        return newSaveOrderConfig.equals(oldSaveOrderConfig) ? false : true;
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/dbproperties/DatabasePropertiesDialog.java]: This is equivalent to `!newSaveOrderConfig.equals(oldSaveOrderConfig)`, right? In this case you can also directly inline this code.

**Comment by tobiasdiez** [comment]
@PJozeph Thanks for the quick follow-up and a Happy New Year!
