### PR TITLE
Fixed deleting Automatic Keyword Group in the UI

### LINKED ISSUE #9778: Impossible to delete an Automatic Keyword Group in the UI
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

Ventura 13.1.1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Dev version JabRef 5.10 dab851639417dede1d08bc139ff5eddb6d95de02 

1.  Create a library with some entries
2. Enable special field priority  (see prefs)
3. Assign some entries the priority 1
4. Create a new Group with Specified keywords -> Field to group by "priority" . Leave name of the group empty
5.  grafik
6. Save
7. Make a right click on the group: Edit shows up twice but no delete

Implementation details:
Check out GroupTreeView.java createContextMenuForGroup

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by brunaoo**
fixes #9778

We fixed an issue preventing the deletion of an Automatic Keyword Group, when the group had no name.

Captura de tela de 2023-05-11 20-29-14

```[tasklist]
### Compulsory checks
- [X] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [ X] Screenshots added in PR description (for UI changes)
- [X] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

File: src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java [hunk 1]
```diff
@@ -659,7 +689,7 @@ public boolean canAddEntriesIn(GroupNodeViewModel groupnode) {
         } else if (group instanceof SearchGroup) {
             return false;
         } else if (group instanceof AutomaticKeywordGroup) {
-            return false;
+            return true;
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java:692]: This does not seem right. Are you sure about this?

**Review by calixtus — DISMISSED** [review]
Great, thanks for the addition. Looks good to me!

File: CHANGELOG.md [hunk 2]
```diff
@@ -91,6 +91,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where the encoding header in a bib file was not respected when the file contained a BOM (Byte Order Mark). [#9926](https://github.com/JabRef/jabref/issues/9926)
 - We fixed an issue where cli help output for import and export format was inconsistent. [koppor#429](https://github.com/koppor/jabref/issues/429)
 - We fixed an issue where no preview could be generated for some entry types and led to an exception [#9947](https://github.com/JabRef/jabref/issues/9947)
+- We fixed an issue is wa delete an Automatic Keyword Group in the UI[#9778](https://github.com/JabRef/jabref/issues/9778)
```
Comment (Siedlerchr) [inline CHANGELOG.md:94]:
```suggestion
- We fixed an issue where an Automatic Keyword Group could not be deleted in the UI. [#9778](https://github.com/JabRef/jabref/issues/9778)
```

**Review by Siedlerchr — DISMISSED** [review]

**Review by Siedlerchr — APPROVED** [review]
