### PR TITLE
Fixed duplicate fields assigned to entry types

### LINKED ISSUE #8194: Duplicate fields assigned to entry types
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 100.0.0 Windows 10 10.0 amd64  Java 16  JavaFX 17.0.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select `Options > Customize entry types` 
2. Select any entry type
3. Add a field that is already added to that entry type
4. It gets added normally (BAD)

Expected: We should ignore the user request or display a warning to tell him that he is trying to add a duplicate field 
- Please note that after restarting `CustomizeEntryTypeView` the duplicate will be gone

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by dimitrisdimos00**
Changed the method addNewField of class CustomEntryTypeDialogViewModel in order to check if the field already exists. Added DialogService field to class CustomEntryTypeDialogViewModel in order to show warning notification to the user. Moreover, passed the existing dialogService field of the class CustomEntryDialogView as a parameter when calling the constructor of the CustomEntryTypeDialogViewModel inside it.
Fixes #8194 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

image

### CODE REVIEW

File: src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java [hunk 1]
```diff
@@ -15,24 +12,19 @@
...
 import org.jabref.logic.l10n.Localization;
 import org.jabref.model.database.BibDatabaseMode;
 import org.jabref.model.entry.BibEntryType;
 import org.jabref.model.entry.BibEntryTypesManager;
-import org.jabref.model.entry.field.BibField;
-import org.jabref.model.entry.field.Field;
-import org.jabref.model.entry.field.FieldFactory;
-import org.jabref.model.entry.field.FieldPriority;
-import org.jabref.model.entry.field.OrFields;
+import org.jabref.model.entry.field.*;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java:20]: There seems to be something wrong with your codestyle here, no star imports allowed
See https://github.com/JabRef/jabref/tree/main/config

File: src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java [hunk 2]
```diff
@@ -126,7 +120,26 @@ public String toString() {
...
         FieldViewModel model = new FieldViewModel(field, true, FieldPriority.IMPORTANT);
-        this.selectedEntryType.getValue().addField(model);
+
+        boolean fieldExists = false;
+
+        // create list with all the entry's fields
+        ObservableList<FieldViewModel> entryFields = this.selectedEntryType.getValue().fields();
+
+        // compare every entry field name with the user field name in order to find out if any of them has the same one. If so, show warning.
+        for (FieldViewModel fieldViewModel : entryFields) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java:130]: This can be simplified
`entryFields.stream().anyMatch(fieldViewModel -> fieldViewModel.fieldName().getValue().equals(...)`
See https://www.baeldung.com/java-8-streams-introduction#1-iterating

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Some small changes Can you also check what happens when you add a duplicate entry type (e.g. add a custom entry type article)?  It  could theoretically be possible, but would not make any sense...

**Comment by Siedlerchr** [comment]
Thanks for your contribution and the explanation of your changes! Very good start! Just some minor things.

**Comment by dimitrisdimos00** [comment]
I am glad to help! Yeah, it is indeed my first contribution to an open source project. The truth is that I found it kind of hard to navigate among the countless project files. However I managed to make it work. Moreover, I tried adding a duplicate entry type and it works. I also implemented the requested changes. Hope it's ok this time!

**Comment by Siedlerchr** [comment]
>I am glad to help! Yeah, it is indeed my first contribution to an open source project. The truth is that I found it kind of hard to navigate among the countless project files. However I managed to make it work. 

Cool :) And a solid first time contribution! 
 We have also a kind of high-level overview (e.g. the relationship between the different packages) and some other useful resources in our devdocs. https://devdocs.jabref.org/getting-into-the-code/high-level-documentation
May I ask how it came that you chose JabRef? 

A little issue is still left:
Please have a look at the checkstyle/reviewdog  (Files changed github) issues. Although these warnings are sometimes nasty, they help us to ensure a uniform code style and to prevent merge conflicts due to formatting changes.

**Comment by dimitrisdimos00** [comment]
Thanks! Ok I will check this out. Well you have a very good guide on seting up everything for newcomers. The most difficult thing for me with projects like this on github is actually setting them up in order to start. In other projects, the instructions are kind of vague and if you encounter an issue in the process, it is very difficult to recover and get going again. In your project, the instructions for setting up Intellij for example were very clear and they had every possible error that might show up. Finally, I like java as a language and wanted to find a project that uses it, so I ended up choosing Jabref.

**Review by Siedlerchr — APPROVED** [review]
codewise lgtm now. I will test your changes and wait for a second maintainer to review your code

File: src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java [hunk 3]
```diff
@@ -126,7 +129,20 @@ public String toString() {
...
+
+        // compare every entry field name with the user field name in order to find out if any of them has the same one.
+        boolean fieldExists = entryFields.stream().anyMatch(fieldViewModel -> fieldViewModel.fieldName().getValue().equals(field.getDisplayName()));
+
+        // if the user field name isn't found inside the list, pass it to the entry as a new one. If that is not the case, show warning.
+        if (!fieldExists) {
+            this.selectedEntryType.getValue().addField(model);
+        } else {
+            dialogService.showWarningDialogAndWait(Localization.lang("Duplicate fields"), Localization.lang("Warning: You added field \"%0\" twice. Only one will be kept.", field.getDisplayName()));
+        }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java:144]: No code-repeating comments. If the name of the variables are chosen well, then the code is self-explaining and you don't need them.

File: src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialogView.java [hunk 4]
```diff
@@ -48,7 +48,8 @@
     private final BibDatabaseMode mode;
     private final BibEntryTypesManager entryTypesManager;
 
-    @FXML private TableView<EntryTypeViewModel> entryTypes;
+    @FXML
+    private TableView<EntryTypeViewModel> entryTypes;
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/customentrytypes/CustomizeEntryTypeDialogView.java:52]: Please try to avoid introducing whitespaces or linebreaks without need.
Keep a consistent code style in the code base.

**Review by calixtus — CHANGES_REQUESTED** [review]
Two style issues.
Thanks for your contribution!

File: src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java (hunk 3 above)
Comment (dimitrisdimos00) [reply src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java:144]: Hello. I deleted the first and last comment and removed as many lines possible. Shall I remove the second comment too? Because I think it is more helpful than the other ones.

Comment (calixtus) [reply src/main/java/org/jabref/gui/customentrytypes/CustomEntryTypeDialogViewModel.java]: No, no comment at all, if it's not really necessary and totally misunderstandable otherwise. The best comment is always the code itself, with meaningful variable names and clean code in 98% you don't need any comment at all.
Whoever works with java nowadays knows how to read streams.

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
Thanks for your contribution!

**Comment by dimitrisdimos00** [comment]
Your welcome!
