### PR TITLE
Store changes in source tab when new entry is selected

### LINKED ISSUE #3086: Changes in Source Tab are not saved correctly without switching to another tab
JabRef version 4.0-beta2 on Debian 9 Stretch AMD64

Steps to reproduce:

1. Add a book entry
2. Add `title`, `author` etc. and save
3. Add `subtitle` and save
4. Switch to another entry
5. Return to the previous entry --> `subtitle` disappeared!!!!

It is very annoying and happens also with other fields.

### PR DESCRIPTION
**Pull request by lenhard**
Fixes #3086 

The problem was that the source tab only stored changes on focus change and this did not happen when you just select a new entry in the main table.

The PR modifies an attribute in the `EntryEditor` (`movingToDifferentEntry`) and turns it into a `BooleanProperty` so that you can bind to it and react to changes.

EDIT: Also fixes a second (unreported) issue: Now the base panel is marked as dirty when you type something in the source tab.

EDIT 2: Fixes also  #3063

Now the Other fields tab is rebuilt whenever an other field is newly added or removed at the BibEntry. This is achieved with the event system and a new subtype of FieldChangedEvent.

- [X] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [X] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [x] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/main/java/org/jabref/gui/entryeditor/EntryEditor.java [hunk 1]
```diff
@@ -202,6 +210,58 @@ public void keyPressed(java.awt.event.KeyEvent e) {
...
+        if (isOtherFieldsTabSelected) {
+            tabbed.getSelectionModel().select(tab);
+        }
+    }
+
+    private void addNewOtherFieldsTabIfNeeded() {
+        OtherFieldsTab tab = new OtherFieldsTab(frame, panel, entryType, this, entry);
+        if (tab.getFields().size() > 0) {
+            // add it at default index, but that is just a guess
+            int defaultIndex = 4;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/EntryEditor.java]: Please add a constant for the magic number

Comment (lenhard) [inline src/main/java/org/jabref/gui/entryeditor/EntryEditor.java]: Done
