### PR TITLE
fixed 'copy key and link'

### LINKED ISSUE #5835: Menu item 'Copy DOI link' no more visible/accessible
JabRef version JabRef 5.0-beta.342--2020-01-15--58709e7 Linux 5.3.0-26-generic amd64 Java 13.0.2 on Ubuntu 19.10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. The "Copy DOI link" (actually the whole context menu for the URL column) is no more visible/accessible in  the entry list
2. Also can't find this menu item under "Copy ..." (where I thought it went after migrating from JR 4 to 5)
3. The menu entry "Copy -> Copy bibtex key and link" does not seem to copy anything to the clipboard. The validation message anyway shows that only the key was copied.

This is probably not a bug but I thought it is tiny enough to include it as an issue.

### PR DESCRIPTION
**Pull request by PremKolar**
'copy key and link' from right-click menu creates a string that is not a url. it includes the url, but it also includes the key.
setHtmlContent() was not appropriate.

Fixes  #5835
https://github.com/JabRef/jabref/issues/5835

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/edit/CopyMoreAction.java [hunk 1]
```diff
@@ -224,7 +224,7 @@ private void copyKeyAndLink() {
             keyAndLink.append(OS.NEWLINE);
         }
 
-        clipBoardManager.setHtmlContent(keyAndLink.toString());
+        clipBoardManager.setContent(keyAndLink.toString());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/edit/CopyMoreAction.java:227]: This really puts the html string into the clipboard, so if you paste it into say notepad you get `<a href="url">key</a>`. Instead, its better to add the html, and in addition also a fallback string of the format `key - url`. In this way, you get the desired behavior also when you paste in applications that do understand html (e.g onenote).

In order for this to work, you probably need to add a second fallback argument to
https://github.com/JabRef/jabref/blob/3db431321186535cc9a05ceae8b1fa580585a9c0/src/main/java/org/jabref/gui/ClipBoardManager.java#L140-L145
which is then added to the ClipboardContent via `putString`.

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
Welcome to JabRef, and thanks a lot for your contribution.

The idea to use `setContent` is the correct one. However, the html content should also be preserved. How this can be done is outlined below.

File: src/main/java/org/jabref/gui/edit/CopyMoreAction.java (hunk 1 above)
Comment (PremKolar) [reply src/main/java/org/jabref/gui/edit/CopyMoreAction.java:227]: Hi @tobiasdiez !
Ah ok that makes sense.. I guess I should have looked deeper into what setHtmlContent() actually does.. I assumed it would be applicable for url's on their own only. So that means, both, setContent() and setHtmlContent() should be called? 
Sorry for my noobness! This was my first open-source contribution ever :D
Can I fix the issue tonight (German time) and commit the changes?
thanks,
Niko

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/edit/CopyMoreAction.java:227]: No worries, you were on the right track. Calling `setContent` and `setHtmlContent` is the right idea, but I suspect that this will push two different clipboard items. Instead, the `setHtmlContent` should be modified as follows:
```
public void setHtmlContent(String html, String fallbackPlain) { 
     final ClipboardContent content = new ClipboardContent(); 
     content.putHtml(html);
     content.putString(fallbackPlain);
     clipboard.setContent(content); 
     setPrimaryClipboardContent(content); 
 }
```
This should add one clipboard item, containing both the html as well as the normal string. (I hope)

Let me know if you encounter any further questions. There is not such a thing as noobness. We all can learn more. And learning in a relaxed environment is one of the main points of open source, so don't worry. Happy coding!

Comment (PremKolar) [reply src/main/java/org/jabref/gui/edit/CopyMoreAction.java:227]: > but I suspect that this will push two different clipboard items.
That was exactly my next thought :)
Ok, I will try..
Thanks for the kind words!

Comment (PremKolar) [reply src/main/java/org/jabref/gui/edit/CopyMoreAction.java]: alright, i hope i did what you meant. I have to say, I still don't understand why copyKeyAndLink() creates html content for the clipboard, but e.g. copyKeyAndTitle() does not?
cheers,
Niko

File: src/main/java/org/jabref/gui/ClipBoardManager.java [hunk 2]
```diff
@@ -144,6 +144,15 @@ public void setHtmlContent(String html) {
         setPrimaryClipboardContent(content);
     }
 
+    //@overload
```
Comment (koppor) [inline src/main/java/org/jabref/gui/ClipBoardManager.java:147]: Please remove the comment

File: src/main/java/org/jabref/gui/edit/CopyMoreAction.java [hunk 3]
```diff
@@ -222,9 +223,11 @@ private void copyKeyAndLink() {
             String url = entry.getField(StandardField.URL).orElse("");
             keyAndLink.append(url.isEmpty() ? key : String.format("<a href=\"%s\">%s</a>", url, key));
             keyAndLink.append(OS.NEWLINE);
+            fallbackString.append(url.isEmpty() ? key : String.format("%s - %s", key, url));
+            fallbackString.append(OS.NEWLINE);
         }
 
-        clipBoardManager.setHtmlContent(keyAndLink.toString());
+        clipBoardManager.setHtmlContent(keyAndLink.toString(),fallbackString.toString());
```
Comment (koppor) [inline src/main/java/org/jabref/gui/edit/CopyMoreAction.java:230]: Please fix checkstyle

```suggestion
        clipBoardManager.setHtmlContent(keyAndLink.toString(), fallbackString.toString());
```

Comment (PremKolar) [reply src/main/java/org/jabref/gui/edit/CopyMoreAction.java]: Hi Koppor,
I implemented your change requests!
One question:
How can check the "checkstyle" myself?

File: CHANGELOG.md [hunk 4]
```diff
@@ -34,12 +34,12 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where the `.sav` file was not deleted upon exiting JabRef. [#6109](https://github.com/JabRef/jabref/issues/6109)
 - We fixed a linked identifier icon inconsistency. [#6705](https://github.com/JabRef/jabref/issues/6705)
 - We fixed the wrong behavior that font size changes are not reflected in dialogs. [#6039](https://github.com/JabRef/jabref/issues/6039)
+- We fixed the failure to Copy citation key and link. [#5835](https://github.com/JabRef/jabref/issues/5835)
 - We fixed an issue where the sort order of the entry table was reset after a restart of JabRef. [#6898](https://github.com/JabRef/jabref/pull/6898)
 - We fixed an issue where no longer a warning was displayed when inserting references into LibreOffice with an invalid "ReferenceParagraphFormat". [#6907](https://github.com/JabRef/jabref/pull/60907).
 
 ### Removed
 
-## [5.1] – 2020-08-30
```
Comment (koppor) [inline CHANGELOG.md:42]: Please do not delete CHANGELOG headers

**Review by koppor — CHANGES_REQUESTED** [review]
I think, there were issues with git. I still have some code comments.

File: src/main/java/org/jabref/gui/ClipBoardManager.java (hunk 2 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/ClipBoardManager.java:147]: Can the old `setHtmlContent` method be removed? If it's still used by other code, it might be a good idea to provide a fallback string in these cases as well. What do you think?

File: CHANGELOG.md (hunk 4 above)
Comment (PremKolar) [reply CHANGELOG.md:42]: Sorry about that! No idea how that happened...

File: src/main/java/org/jabref/gui/ClipBoardManager.java (hunk 2 above)
Comment (PremKolar) [reply src/main/java/org/jabref/gui/ClipBoardManager.java:147]: Hi Tobias,
If I am not mistaken, there is no usage of `setHtmlContent(String html)` anywhere...
Only `setHtmlContent(String html, String fallbackPlain)` is used once on line 230 of `CopyMoreAction.java`.
Should I remove the unused version?

Comment (koppor) [reply src/main/java/org/jabref/gui/ClipBoardManager.java:147]: Yes, just remove the the unused method.

File: CHANGELOG.md (hunk 4 above)
Comment (koppor) [reply CHANGELOG.md:42]: I think, it happend during conflict resolution when merging the master branch: https://github.com/JabRef/jabref/pull/6871/commits/d022875ba0e9e02e16722b73897126c8fd79946b

Could you just re-add the line in another commit?

**Comment by Siedlerchr** [comment]
Codewise looks good. Plase fix the remaining checkstyle errors. Just click on the Details of the failing tests

File: CHANGELOG.md (hunk 4 above)
Comment (calixtus) [reply CHANGELOG.md]: quickfix
