### PR TITLE
Bring back a modified ISBN check and add more tests

### LINKED ISSUE #8885: Duplicate check during import marks articles from collection as possible duplicates
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-06-01--943489e || Linux 5.10.0-14-amd64 amd64 || Java 18.0.1 || JavaFX unknown

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Copy two articles (InCollection) from the same book to a new database
2. The second entry that is copied is marked as possible duplicate although author, title, and citationkey deviate.

### Appendix

Import_erroneous_duplicates

### PR DESCRIPTION
**Pull request by AbdAlRahmanGad**
Closes #8885 

- I placed the modified ISBN check below this statement
https://github.com/JabRef/jabref/blob/6789460795b5f3eaabe960027d851ed08493ad95/src/main/java/org/jabref/logic/database/DuplicateCheck.java#L334
 to ensure that the types are the same first.
 - Added 2 tests.

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [X] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/database/DuplicateCheck.java [hunk 1]
```diff
@@ -337,6 +340,16 @@ public boolean isDuplicate(final BibEntry one, final BibEntry two, final BibData
             return false;
         }
 
+        // In case an ISBN is present, it is a strong indicator that the entries are equal.
+        // Only in InBook, InCollection, or Article the ISBN may be equal and the puplication on different pages (and thus not equal)
+        Optional<ISBN> oneISBN = one.getISBN();
+        Optional<ISBN> twoISBN = two.getISBN();
+        if (oneISBN.isPresent() && twoISBN.isPresent()
+                && !List.of(StandardEntryType.Article, StandardEntryType.InBook, StandardEntryType.InCollection).contains(one.getType())
+                && Objects.equals(oneISBN, twoISBN)) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/database/DuplicateCheck.java:349]: I would flip List.of and `Objects.equals`, because `oneISBN` is checked in line 347 and then the subsequent line 348 is closer. Otherwise, the condition is harder to read, because it switches between ISBN, types, and ISBN.

**Review by koppor — APPROVED** [review]
