### PR TITLE
Fix issue: Auto-linking files with safe character replacements #9267

### LINKED ISSUE #9267: Auto-linking files with safe character replacements
### JabRef version

5.7 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When using characters in the citation key or publication title that are unsafe for the file system (such as e.g. a colon ":"), the automatic file renaming replaces those characters with an underscore.
However, the auto-linking feature does not seem to respect this behaviour. After automatically renaming a file with an unsafe character and unlinking it, it is not being recognized by the auto-linking feature.
Changing the citation key to the "safe" string by manually replacing the colon with an underscore makes JabRef find the file again.

Auto-linking files didn't work at all for me in the development version, so I couldn't actually reproduce the behaviour there.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by Rita-Zhou**
Fixes #9267 

### Short Description
This aims to fix the issue where it is impossible to find the related file when the citation key involves some characters (e.g. `:`) that cannot be contained in the file name. 
We fix this issue by searching the related file with the citation key where its unsafe characters are replaced with underscores `_`. (See [#9267](https://github.com/JabRef/jabref/issues/9267))

### UI changes
- Input a citation key with an unsafe character (colon ":")   
   
313210096_495396219314658_7636164207235418215_n
- Before  
  
312984263_535109675291077_2673210671895727303_n
- After  
  
312436604_797747644827893_4867990044154713722_n
**Note: The user should reopen the library to see the attachment**

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/util/io/CitationKeyBasedFileFinder.java [hunk 1]
```diff
@@ -65,8 +65,13 @@ public List<Path> findAssociatedFiles(BibEntry entry, List<Path> directories, Li
         return result.stream().sorted().collect(Collectors.toList());
     }
 
+    public static String getSafeCiteKey(String citeKey) {
+        // replace the unsafe character with the underscore.
+        return citeKey.replaceAll("[:/*?<>|]", "_");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/util/io/CitationKeyBasedFileFinder.java:70]: You should use the method  FileNameCleaner.cleanFileName because this method is also called when the Filename is  built from the citation key (when you have rename to pattern)

**Review by Siedlerchr — APPROVED** [review]
Thanks, lgtm!

**Comment by Siedlerchr** [comment]
Thank you for the pull request. In future, please use the GitHub syntax Fixes #9304. Otherwise, GitHub does not automatically close the linked issue.

**Comment by Siedlerchr** [comment]
TODO: That looks good so far, but I am unsure atm if it is also necessary to have this for exact matches
Can you add a test case for this as well, if the preference option is "only exact key matches"?

**Comment by xianghao-wang** [comment]
> TODO: That looks good so far, but I am unsure atm if it is also necessary to have this for exact matches Can you add a test case for this as well, if the preference option is "only exact key matches"?

Many thanks, I just now added a test for both "exact" and "startsWith" search.

**Comment by xianghao-wang** [comment]
> > TODO: That looks good so far, but I am unsure atm if it is also necessary to have this for exact matches Can you add a test case for this as well, if the preference option is "only exact key matches"?
> 
> Many thanks, I just now added a test for both "exact" and "startsWith" searches.
> 
> **StartsWith match**: check whether a file name starts with a string and this string's unsafe characters will be converted to _. **Exact match**: check whether a file name exactly matches a string without allowing character replacement.
> 
> A suggestion: I notice there are 3 searches for auto-linking files - 1. start with 2. exact 3. regex. I think it would be better to replace "startwith" with a new search called "fuzzy search" which can match part of the filename intelligently as suggested #9322 .

**Comment by xianghao-wang** [comment]
Sorry for forgetting fix the code style and I just now fixed it.

**Review by calixtus — APPROVED** [review]
Looks good to me!

**Comment by Siedlerchr** [comment]
Thanks again for your PR! 
I am unsure about the exact matching, but would leave it as it for now. If it's still an issue or requested by the users we can do a follow up.

**Review by Siedlerchr — APPROVED** [review]
