### PR TITLE
Fix: Make FileUtil.relativize symlink-aware

### LINKED ISSUE #12995: `FileUtil::relativize` doesn't take symlinks into account
### JabRef version

5.15 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

KDE Neon - based on Ubuntu 24.04

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Look at
https://github.com/JabRef/jabref/blob/af362eaa31f84c14f76e83ac4e9a9327d5cecd20/src/main/java/org/jabref/logic/util/io/FileUtil.java#L261-L263

### Appendix

The effect of this is (among other things?) that when manually linking a PDF file to a bib entry, which is located in the main file directory, it can still end up being added by its full path.

This is because the configured main file directory and/or the path to the selected PDF file can contain symbolic links which make the paths appear different (which causes `FileUtils::relativize` to fail) even though they are not.

It seems that `Path::toRealPath` from Java's standard library could be used for obtaining a canonical path representation that has symlinks resolved.

### PR DESCRIPTION
**Pull request by Muskan244**
Closes #12995 

This PR to make FileUtil.relativize symlink-aware by:
- Updating `FileUtil::relativize` to handle symlinks when resolving relative paths.

- Ensuring files inside symlinked directories are correctly referenced by their relative path.

- Adding unit tests to verify correct behavior with symlinked and regular directories.

- Adding ignored test for symlink escape scenario (/lib/things -> /share/expensive -> /veryprivate).

### Steps to test

- Build JabRef and run the full test suite:
		Gradle: ./gradlew test
Ensure all tests in FileUtilTest related to symlink handling pass without errors.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [/] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [/] Screenshots added in PR description (if change is visible to the user)
- [/] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Muskan244** [comment]
Hi! I’ve pushed the requested changes, and it looks like all checks have passed. Just checking in to see if there's anything more I should do. Thanks again for guiding me through this!

File: jablib/src/test/java/org/jabref/logic/util/io/FileUtilTest.java [hunk 1]
```diff
@@ -448,6 +448,32 @@ public void cTemp() {
         }
     }
 
+    @Test
+    void relativizeHandlesSymlinks(@TempDir Path tempDir) throws IOException {
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/util/io/FileUtilTest.java]: The tests are indpendent. Please separate. Maybe parameterized test?

File: jablib/src/test/java/org/jabref/logic/util/io/FileUtilTest.java [hunk 2]
```diff
@@ -448,6 +448,32 @@ public void cTemp() {
...
+        Files.write(fileInRealDir, "dummy".getBytes(StandardCharsets.UTF_8));
+
+        Path rel = FileUtil.relativize(fileInRealDir, List.of(symlinkDir));
+        assertEquals(Path.of("paper.pdf"), rel, "Should resolve to simple filename when accessed through symlink");
+        Path fileViaSymlink = symlinkDir.resolve("paper.pdf");
+
+        Path rel2 = FileUtil.relativize(fileViaSymlink, List.of(symlinkDir));
+        assertEquals(Path.of("paper.pdf"), rel2, "Should resolve to simple filename for file via symlink-path");
+        Path outsideFile = tempDir.resolve("elsewhere.pdf");
+        Files.write(outsideFile, "foo".getBytes(StandardCharsets.UTF_8));
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/util/io/FileUtilTest.java]: No need for getbytes - IMHO strings can be written directly?

File: jablib/src/test/java/org/jabref/logic/util/io/FileUtilTest.java (hunk 1 above)
Comment (Muskan244) [reply jablib/src/test/java/org/jabref/logic/util/io/FileUtilTest.java]: Replaced the previous grouped symlink test with independent, parameterized tests for clarity and completeness.

**Comment by Muskan244** [comment]
Hi! I’ve pushed the requested changes, and it looks like all checks have passed. Just checking in to see if there's anything more I should do. Thanks again for guiding me through this!

**Comment by Muskan244** [comment]
Could someone please take a look when you have time? Happy to clarify or make any changes if needed. Thanks!

File: jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java [hunk 3]
```diff
@@ -256,15 +256,40 @@ public static Path relativize(Path file, List<Path> directories) {
...
         for (Path directory : directories) {
+            Optional<Path> realDirOpt = tryRealPath(directory);
+
+            if (realFileOpt.isPresent() && realDirOpt.isPresent()) {
+                Path realFile = realFileOpt.get();
+                Path realDir = realDirOpt.get();
+                if (realFile.startsWith(realDir)) {
+                    int nameCountToDrop = realDir.getNameCount();
+                    Path relativePart = realFile.subpath(nameCountToDrop, realFile.getNameCount());
+                    return relativePart;
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java]: Is there a reason why `directory.relativize(file);` is not used?

**Comment by koppor** [comment]
I need to think through more.

File: jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java (hunk 3 above)
Comment (Muskan244) [reply jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java]: I did try using `directory.relativize(file);` at first, but I ran into problems for some of the symlink edge cases. If the canonical path doesn’t match the original directory or file prefix exactly, `relativize` doesn’t always work especially with nested or chained symlinks. That’s why I switched to the current approach, since it seemed to pass those tricky test cases. If there’s a more standard way to handle this, I’d really appreciate any suggestions. Also, should I add comments explaining the logic in the code?

**Comment by Muskan244** [comment]
> I need to think through more.

Hi @koppor, just checking in. Do you think you’ll have time soon to review further? Happy to clarify anything if needed.

File: jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java (hunk 3 above)
Comment (subhramit) [reply jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java]: Hey @Muskan244, comments would be helpful.
We'll get done reviewing this soon.

**Comment by subhramit** [comment]
> Maven: mvn test

Hey @Muskan244, I was going through the steps to test your changes, and wondering where you got this^ from. What's it's significance with respect to JabRef?

File: jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java (hunk 3 above)
Comment (Muskan244) [reply jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java]: Thanks, I'll add the comments explaining the logic of the code.

**Comment by Muskan244** [comment]
> > Maven: mvn test
> 
> Hey @Muskan244, I was going through the steps to test your changes, and wondering where you got this^ from. What's it's significance with respect to JabRef?

Thanks for catching that @subhramit, my mistake! JabRef uses Gradle, not Maven.
I’ll update the PR description to remove the Maven instruction and keep only the Gradle one.

**Comment by koppor** [comment]
Note that there is no test for https://github.com/JabRef/jabref/issues/12995#issuecomment-3065149862 - it would be OK to have it ignored. Not sure how important this is, but it should be noted down somewhere. Maybe a link js enough.

**Comment by Muskan244** [comment]
Hi @koppor, Do you suggest we add this as an ignored test and just link to your comment in #12995, or, try to change FileUtil.relativize to explicitly detect and prevent such escapes? Just want to be sure.

**Comment by koppor** [comment]
> Hi @koppor, Do you suggest we add this as an ignored test and just link to your comment in #12995, or, try to change FileUtil.relativize to explicitly detect and prevent such escapes? Just want to be sure.

The former is enough.

**Comment by koppor** [comment]
I used [RefactoringMiner](https://github.com/tsantalis/RefactoringMiner) to review

The logic diff is as follows

image

---

And test case

image

---

There were some syntax changes; I try to look. Refs https://github.com/JabRef/jabref-koppor/pull/672.

File: jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java (hunk 3 above)
Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java]: Me and ChatGPT share the same oppionion:

image

Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/util/io/FileUtil.java]: If there was an edge case, there should be a JUnit test for this.

**Comment by koppor** [comment]
@Muskan244 Why didn't you add a CHANGELOG.md entry?!

**Comment by koppor** [comment]
Follow-up would be to spleit the parameterized test into seperate test cases - the method producing the arguments is not very readable.

**Comment by Muskan244** [comment]
Thanks! I’ll prepare a follow-up PR for splitting the parameterized test into separate test cases to make it more readable.
