### PR TITLE
Fix Tagsfield in Keyword editor

### LINKED ISSUE #11390: The new tag system ignores hierarchical keywords. Only the parent keyword is shown.
The new tag system ignores hierarchical keywords. Only the parent keyword is shown.

_Originally posted by @andr-groth in https://github.com/JabRef/jabref/issues/10910#issuecomment-2175878088_

### PR DESCRIPTION
**Pull request by calixtus**
Fixes #11390
Follow-up to #10910

The StringConverter seems only to return the parent keyword.

grafik

grafik

### Steps to test

In EntryEditor in source tab add hierarchichal keywords eg "parent > node > child", open general tab and see only parent in keywords, maybe with an assert exception being thrown.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/fieldeditors/KeywordsEditorViewModel.java [hunk 1]
```diff
@@ -60,20 +60,20 @@ public ListProperty<Keyword> keywordListProperty() {
...
                     return "";
                 }
-                return keyword.get();
+                return keyword.toString();
             }
 
             @Override
             public Keyword fromString(String keywordString) {
-                return new Keyword(keywordString);
+                return Keyword.of(keywordString.split(Keyword.DEFAULT_HIERARCHICAL_DELIMITER.toString()));
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/fieldeditors/KeywordsEditorViewModel.java]: Plz move the inner part to `Keyword.ofString(String list)`
