### PR TITLE
Try to fix LibreOffice class loader

### LINKED ISSUE #5261: Linking to Libre/OpenOffice fails because of classloader exception
JabRef version 5.x on Ubuntu 18.04 LTS

- [ x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Manual connect to Libreoffice (Auto connect generates same error)
2. Specify directory for .jar class files: /usr/lib/libreoffice/program/classes (have double-checked that they are actually there)
3. Click OK
4. Error: "Could not connect to running OpenOffice/LibreOffice
(Not all) required OpenOffice jars were found inside the installation path. Searched for [unoil.jar, jurt.jar, juh.jar., ridl.jar] in /opt/openoffice.org3"

Stacktrace: 

java.io.IOException: (Not all) required Open Office Jars were found inside installation path. Searched for [unoil.jar, jurt.jar, juh.jar, ridl.jar] in /opt/openoffice.org3
	at org.jabref.gui.openoffice.OpenOfficePanel.loadOpenOfficeJars(OpenOfficePanel.java:449)
	at org.jabref.gui.openoffice.OpenOfficePanel$2.call(OpenOfficePanel.java:389)
	at org.jabref.gui.openoffice.OpenOfficePanel$2.call(OpenOfficePanel.java:384)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #5261 

After a lot of googling I found some old forum thread in the deep of the open office forums which combined gave the solution.

1. Use sockets instead of pipes (cause jpipe is a dll/lib in the LO dir and cannot be found at class loading
2.  Pass an URL ClassLoader as parent to the Bootstrap method.
https://technology.amis.nl/2006/07/19/getting-started-with-the-openofficeorg-api-part-ii-starting-openofficeorg-with-jars-not-in-the-ooo-install-dir/

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 1]
```diff
@@ -235,30 +233,24 @@ public void selectDocument() throws NoDocumentException, NoSuchElementException,
...
-                LOGGER.error("Error, could not add URL to system classloader", t);
-                cl.close();
-                throw new IOException("Error, could not add URL to system classloader", t);
-            }
-        } else {
-            LOGGER.error("Error occured, URLClassLoader expected but " + loader.getClass()
-                         + " received. Could not continue.");
+    
+        URL[] urls = jarUrls.toArray(new URL[3]);
+        Class<Bootstrap> clazz  = (Class<Bootstrap>) Class.forName("com.sun.star.comp.helper.Bootstrap", true, new ChildFirstClassLoader(urls, null));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: I don't really understand the problem, but doesn't https://stackoverflow.com/a/48323948/873661 work?

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: The problem is that by default java delegate class loading to the parent class loader and so on until the class is found. This results in loading the` org.jabref.thirdparty` module from the module path and not the jars from the libre office program folder. Calling Bootstrap will then result in an error message, no office executable found.

That's why I created a child first class loader. It loads the stuff into the unnamed module aka the class path. But casting the loaded class back fails because it's different now twice in the app...
https://stackoverflow.com/questions/54536895/cannot-be-cast-to-class-because-they-are-in-unnamed-module-of-loader-app#comment96026301_54536895

Child First class loader:
https://medium.com/@isuru89/java-a-child-first-class-loader-cbd9c3d0305

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: The only solution I have to try is to load the jars into the module path or to put our patched module into the libre office program folder.

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Ok, but then why are we trying to load jar files that we already include?

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: We must include them to have the types.
But we need to load them dynamically again from libreoffice program folder because otherwise the soffice.exe can't be found.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Sounds weird, but I debugged through it and had these errors. Of course lO was running

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: @tobiasdiez  This is the problem with the Bootstrap:
https://github.com/LibreOffice/core/blob/330df37c7e2af0564bcd2de1f171bed4befcc074/javaunohelper/com/sun/star/comp/helper/Bootstrap.java#L332-L338

**Comment by Siedlerchr** [comment]
Yippieh! I hacked the Bootsrap mechanism and use now sockets instead of pipes. That works yeahahw!

File: src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java [hunk 2]
```diff
@@ -137,21 +135,8 @@ public OpenOfficePanel(JabRefFrame frame, JabRefPreferences jabRefPreferences, O
...
-                method.invoke(sysloader, anU);
-            }
-        } catch (SecurityException | NoSuchMethodException | IllegalAccessException | IllegalArgumentException |
-                 InvocationTargetException e) {
-            LOGGER.error("Could not add URL to system classloader", e);
-            sysloader.close();
-            throw new IOException("Error, could not add URL to system classloader", e);
-        }
+    private static void addURL(List<URL> jarList) throws IOException, ClassNotFoundException {
+       // Class<?> clazz = Class.forName("com.sun.star.comp.helper.Bootstrap", true, new ChildFirstClassLoader( jarList.toArray(new URL[0]),null ));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java]: can this be removed now?

File: src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java [hunk 3]
```diff
@@ -442,7 +427,7 @@ protected OOBibBase call() throws Exception {
 
     }
 
-    private void loadOpenOfficeJars(Path configurationPath) throws IOException {
+    private List<URL> loadOpenOfficeJars(Path configurationPath) throws IOException {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java]: I guess `findOpenOfficeJars` is now a better name

File: src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java [hunk 4]
```diff
@@ -453,13 +438,15 @@ private void loadOpenOfficeJars(Path configurationPath) throws IOException {
...
     }
 
-    private OOBibBase createBibBase() throws IOException, InvocationTargetException, IllegalAccessException,
-        BootstrapException, CreationException {
+    private OOBibBase createBibBase(List<URL> jarUrls) throws IOException, InvocationTargetException, IllegalAccessException,
+        BootstrapException, CreationException, ClassNotFoundException {
         // Connect
-        return new OOBibBase(ooPrefs.getExecutablePath(), true, dialogService);
+        
+        return new OOBibBase(jarUrls,true, dialogService);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java]: space in arguments

**Comment by Siedlerchr** [comment]
I will open an issue at the libre office repo.
Regarding the submodules: I have no idea why these are in my commit. I tried to "reset" them and re init them but nothing changed.

**Comment by tobiasdiez** [comment]
Ok, please add a changelog entry and then merge!
