### PR TITLE
Use streaming when downloading from DOI

### LINKED ISSUE #14089: URLDownload should include httpResponse in exception
`FetcherException` supports outputting http information on failure: `org.jabref.logic.importer.FetcherException#getLocalizedMessage`

This should be used at `URLDownload` (e.g., `org.jabref.logic.net.URLDownload#asString(java.nio.charset.Charset, java.net.URLConnection)`)

Task:

1. Adapt org.jabref.logic.importer.fetcher.DoiFetcher#performSearchById to use `org.jabref.logic.importer.fileformat.BibtexParser#parseEntries` instead of `singleFromString`
1. Make `asString(Charset encoding, URLConnection connection)` private
2. Adapt all other methods

Note: You can merge `asString(Charset encoding, URLConnection connection)` with `asString(URLConnection connection)` probably.

### PR DESCRIPTION
**Pull request by koppor**
Fixes https://github.com/JabRef/jabref/issues/14089

Was a bit larger than I thought; the DoiFetcher code needed a cleanup. There was also a space inserted. I don't know why this disappeared when reading from the String; maybe there was some automatic trimming. I added `DoiFetcher.http` for easy manual checking of the returned file.

### Steps to test

Just see the fetcher tests passing.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [/] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [/] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

### CODE REVIEW

**Comment by koppor** [comment]
Format fails because formatter does not work with Markdown properly (yet). EAP does.

```diff
--- a/jablib/src/main/java/org/jabref/logic/net/URLDownload.java
+++ b/jablib/src/main/java/org/jabref/logic/net/URLDownload.java
@@ -61,7 +61,7 @@ import org.slf4j.LoggerFactory;
 /// String content = dl.asString(ENCODING);
 /// dl.toFile(Path);              // available in FILE
 /// String contentType = dl.getMimeType();
-/// ```
+///```
 ///
 /// Almost every call to a public method creates a new HTTP connection
 /// (except for {@link #asString(Charset, URLConnection) asString},
```

I filed https://github.com/leventeBajczi/intellij-idea-format/pull/4/files to check whether the latest version works.

File: jablib/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java [hunk 1]
```diff
@@ -235,18 +239,20 @@ public Optional<String> getAgency(DOI doi) throws FetcherException, MalformedURL
         return agency;
     }
 
-    private void setPageCountToArticleId(BibEntry entry, String doiAsString) {
+    private void setPageNumbersBasedOnDoi(BibEntry entry, DOI doi) {
```
Comment (Siedlerchr) [inline jablib/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java:242]: Count and page numbers are two different thing 
E.g total pages

File: jablib/src/main/java/org/jabref/model/entry/BibEntry.java [hunk 2]
```diff
@@ -1268,4 +1268,10 @@ public boolean isEmpty() {
         }
         return StandardField.AUTOMATIC_FIELDS.containsAll(this.getFields());
     }
+
+    /// Trims whitespaces at the beginning of the BibEntry
+    public void trimLeft() {
+        this.parsedSerialization = parsedSerialization.trim(); // we should do "trimLeft", but currently, it is OK as is.
```
Comment (Siedlerchr) [inline jablib/src/main/java/org/jabref/model/entry/BibEntry.java:1274]: Add a test

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Add tests

File: jablib/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java (hunk 1 above)
Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java:242]: GitHub mobile doesn't allow me to expand the code. Will check later if "PAGES" is assigned the line below. I am 99% sure that "PAGES" denotes the page range; and "PAGETOTAL" (or similar) is for the page count.

**Comment by Siedlerchr** [comment]
@jetbrains-junie Create a test for the trimLeft

**Comment by ghost** [comment]
Hey, it’s Junie by JetBrains! I started [processing](https://github.com/JabRef/jabref/actions/runs/19648197862) your request 🚀

**Comment by ghost** [comment]
### ✅ The execution was successful
> ### test(entry): add unit test for BibEntry.trimLeft()
> A unit test was added for the BibEntry.trimLeft() method as requested. The test validates removal of leading whitespace and ensures idempotency and empty string safety. The new test file is jablib/src/test/java/org/jabref/model/entry/BibEntryTrimLeftTest.java.




More information:
* 🔗 [GitHub Action](https://github.com/JabRef/jabref/actions/runs/19648197862)
* 💬 [Report the issue on our Discord and help us improve](https://jb.gg/junie/github)

File: jablib/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java (hunk 1 above)
Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java:242]: Source: biblatex

grafik

**Review by Siedlerchr — APPROVED** [review]
