### PR TITLE
Fix: bibkey generated does not handle diacritics

### LINKED ISSUE #4709: Handling of diacritics in bibtex key generator
JabRef version 4.3.1 on Windows 7.

There are certain diacritics (and other symbols) that produce undesired output when generating bibtex keys. I am using `[auth3][shortyear]` as generation pattern. Examples with first authors' last names and year:

- Müller, 2019 -> Muel19 (4 characters instead of 3 when converting umlaut, i.e. ä, ö, ü)
- Al-Ketan, 2019 -> Al-19 (dash in bibtex key is awkward, should probably be ignored in favor of the next letter and become AlK19)
- D'Alessandro, 2019 -> DA19 (Apostrophe is correctly ignored, but the name is reduced to 2 characters when it should probably be DAl19)

Some other diacritics that I quickly tested (Ç, Â, é) are handled more gracefully, i.e. the corresponding letter without diacritic is used.

1. Use [auth3][shortyear] as pattern for bibtex key generation. 
2. Enter one of the last names mentioned above in the last author field of a new article. Enter any year.
3. Generate bibtex key (CTRL+G)

### PR DESCRIPTION
**Pull request by chelseyong**
Fixes #4709.
Clean up the author value in `BracketedPattern` after it is retrieved from the `BibEntry`.

----

- [ ] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for your contribution. Unfortunately your changes resulted in a lot of failed tests (look at Details of the travis build and then select the failing job) 
Seems like there are some more cases you need to take care of. (I'm not that deep into the bibtexkeygenerator stuff)

**Comment by chelseyong** [comment]
Noted. Is there another approach to handle this?

**Comment by chelseyong** [comment]
Currently facing some issues while writing tests: `mockito` and `jfoenix.controls.JFXSnackbarLayout` cannot be imported, whereas `jfoenix.controls.JFXSnackbar.SnackbarEvent` works fine. 
I updated to jdk8_202 and it doesn't help. Do I need to install other dependencies?

**Comment by Siedlerchr** [comment]
@chelseyong  Try merging the current master in e.g.  (if upstream is the jabref/jabref repo)
```
git fetch upstream 
git merge upstream/master
```
I'm not an intellij user, but executing gradle should be sufficient. 
maybe @halirutan  can tell you more.

**Comment by chelseyong** [comment]
Sorry for the delay, I had some software issues.

Symbol `-` is now removed from key generation.

File: src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java [hunk 1]
```diff
@@ -72,15 +72,15 @@ private static String getAppendix(int number) {
         }
     }
 
-    public static String cleanKey(String key, boolean enforceLegalKey) {
+    public static String filterUnwantedCharacters(String key, boolean enforceLegalKey) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java]: maybe a slightly better name `removeUnwantedCharacters` (filter would imply that the unwanted characters are returned).

File: src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java [hunk 2]
```diff
@@ -26,8 +26,8 @@
      */
     public static final String APPENDIX_CHARACTERS = "abcdefghijklmnopqrstuvwxyz";
     private static final Logger LOGGER = LoggerFactory.getLogger(BibtexKeyGenerator.class);
-    private static final String KEY_ILLEGAL_CHARACTERS = "{}(),\\\"#~^':`";
-    private static final String KEY_UNWANTED_CHARACTERS = "{}(),\\\"";
+    private static final String KEY_ILLEGAL_CHARACTERS = "{}(),\\\"-#~^':`";
```
Comment (koppor) [inline src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java:29]: @chelseyong Do you, by chance, remember why you introduced `-` here? We have issues with that. See https://github.com/JabRef/jabref/issues/6295 for details.

Comment (chelseyong) [reply src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java:29]: I think it is due to a suggestion made in the [issue](https://github.com/JabRef/jabref/issues/4709).
> Al-Ketan, 2019 -> Al-19 (dash in bibtex key is awkward, should probably be ignored in favor of the next letter and become AlK19)

Comment (koppor) [reply src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java:29]: Thank you for your reply. I Think, there was some misunderstanding at https://github.com/JabRef/jabref/issues/4709#issuecomment-468700259

> Well, dash is a **perfectly legal char**

We will fix it at https://github.com/JabRef/jabref/pull/6300
