### PR TITLE
Fix entry preview copy exception

### LINKED ISSUE #4714: Preview copy leads to exception
JabRef version

JabRef 5.0-dev--snapshot--2019-03-03--master--094a0395e
Linux 4.15.0-45-generic amd64 
Java 1.8.0_201

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists```

1. Show an entry preview by selecting an item and pressing F2
2. Select Edit / Copy ... / Copy Preview
3. The "Exception Details" window pops up.
4. Nothing is copied to the buffer.

screenshot from 2019-03-03 11-25-40

<details>
  <summary>Log File</summary>
  
  java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.input.Clipboard.setContent(Clipboard.java:231)
	at org.jabref.gui.ClipBoardManager.setContent(ClipBoardManager.java:53)
	at org.jabref.gui.worker.CitationStyleToClipboardWorker.done(CitationStyleToClipboardWorker.java:188)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #4714

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/worker/CitationStyleToClipboardWorker.java [hunk 1]
```diff
@@ -39,29 +39,33 @@
...
-        this.previewStyle = Globals.prefs.getPreviewPreferences().getPreviewStyle();
+        this.previewStyle = previewPreferences.getPreviewStyle();
         this.outputFormat = outputFormat;
+        this.clipBoardManager = clipBoardManager;
 
-        basePanel.frame().setStatus(Localization.lang("Copying..."));
+        this.dialogService = dialogService;
+        dialogService.notify(Localization.lang("Copying..."));
+
+        BackgroundTask.wrap(this::loadCitationStyles).onFailure(ex -> LOGGER.error("Error while copying citations to the clipboard", ex))
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/worker/CitationStyleToClipboardWorker.java]: I guess you need to also run the background task (i.e call `execute()`). But I don't like the fact that the constructor has the side-effect of running a new thread. Thus, I would propose to let `CitationStyleToClipboardWorker` inherit from `BackgroundTask` and rename `loadCitationStyles` to `call` (so that it overrides the corresponding method in background task). Then the statement above in basepanel would become `new CitationStyleToClipboardWorker(...).executeWith(Globals.taskExecutor)`.

File: src/main/java/org/jabref/gui/worker/CitationStyleToClipboardWorker.java [hunk 2]
```diff
@@ -39,29 +40,38 @@
...
         this.selectedEntries = basePanel.getSelectedEntries();
-        PreviewPreferences previewPreferences = Globals.prefs.getPreviewPreferences();
         this.style = previewPreferences.getPreviewCycle().get(previewPreferences.getPreviewCyclePosition());
-        this.previewStyle = Globals.prefs.getPreviewPreferences().getPreviewStyle();
+        this.previewStyle = previewPreferences.getPreviewStyle();
         this.outputFormat = outputFormat;
+        this.clipBoardManager = clipBoardManager;
+
+        this.dialogService = dialogService;
+        dialogService.notify(Localization.lang("Copying..."));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/worker/CitationStyleToClipboardWorker.java]: The notify should also go into the `copyCitationStyleToClipboard` method.

File: src/main/java/org/jabref/gui/worker/CitationStyleToClipboardWorker.java [hunk 3]
```diff
@@ -39,29 +40,38 @@
...
+    public void copyCitationStyleToClipboard(TaskExecutor taskExecutor) {
+        BackgroundTask.wrap(this::loadCitationStyles)
+                      .onFailure(ex -> LOGGER.error("Error while copying citations to the clipboard", ex))
+                      .onSuccess(this::setClipBoardContent)
+                      .executeWith(taskExecutor);
     }
 
-    @Override
-    protected List<String> doInBackground() throws Exception {
+    private List<String> loadCitationStyles() throws IOException {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/worker/CitationStyleToClipboardWorker.java]: Isn't `generateCitations` a more appropiate name for this method?
