### PR TITLE
Fix for application dialogs opening in wrong displays

### LINKED ISSUE #7272: Application Dialogs Open on Wrong Display
JabRef version 5.2 on Windows 10

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open JabRef on a system with at least two displays
2. Move the application main window to a non-primary display (as far as I can tell, JabRef always opens on the primary display on launch)
3. Perform an activity spawning a dialog (tested: *Help*->*About*, *New entry*, and a few others, but I'm suspecting that it works for all dialogs)
4. The dialog will always appear on the primary display, regardless of the position of the application main window (My suspicion is that the `initOwner(Window)` method is never called when initializing new dialogs. This usually results in the new window appearing on the display the application opened at startup.)

### PR DESCRIPTION
**Pull request by faeludire**
What:
- Fix for issue with application dialogs opening in the wrong display

Why:
- Dialog opens in the display the application opened at startup (usually the primary display), regardless of the current position of the application main window

- This is a draft to discuss the approach taken.

Fixes #7272 

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by tobiasdiez — COMMENTED** [review]
Thanks for your contribution! 
Setting the owner of the sub-dialogs is a good idea, indeed. 

I was thinking about the best way to do this, without too much changes. Here is what I came up with:
- The `DialogService` should be able to get the main stage from https://github.com/JabRef/jabref/blob/020cc975800a65cf2c3466b57ed91aa4502f554c/src/main/java/org/jabref/gui/JabRefDialogService.java#L75 
- Thus, for all dialogs created with the help of the `DialogService` we can easily set the owner.
- The dialogs that are currently shown by invoking `dialog.show()` or `dialog.showAndWait()` need to be shown via https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/JabRefDialogService.java#L267

What do you think?

**Comment by faeludire** [comment]
> Thanks for your contribution!
> Setting the owner of the sub-dialogs is a good idea, indeed.
> 
> I was thinking about the best way to do this, without too much changes. Here is what I came up with:
> 
> * The `DialogService` should be able to get the main stage from https://github.com/JabRef/jabref/blob/020cc975800a65cf2c3466b57ed91aa4502f554c/src/main/java/org/jabref/gui/JabRefDialogService.java#L75
> * Thus, for all dialogs created with the help of the `DialogService` we can easily set the owner.
> * The dialogs that are currently shown by invoking `dialog.show()` or `dialog.showAndWait()` need to be shown via https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/JabRefDialogService.java#L267
> 
> What do you think?

Hi @tobiasdiez, thanks for the comments.

- I agree based on your suggestion; for dialogs created with the help of `DialogService`, owners of such dialogs can easily be set.

- It seems like we might have to consider adding a `Window` object to the `BaseDialog` constructor here:
https://github.com/JabRef/jabref/blob/020cc975800a65cf2c3466b57ed91aa4502f554c/src/main/java/org/jabref/gui/util/BaseDialog.java#L22
That way `initOwner(mainWindow);` can be called within the constructor, for dialogs not created with the help of  `DialogService`, but rather extending `BaseDialog`. 
If not, we need a way to find out what what `Window` creates dialogs that extend `BaseDialog`, eg. `AboutDialogView` in order to set its owner.

**Comment by tobiasdiez** [comment]
> It seems like we might have to consider adding a Window object to the BaseDialog constructor here:

That would work indeed. However, then one needs to pass references of the main stage everywhere (like what you did in the current changes), and that's something I don't really like. Instead, I was proposing to pass references to the `DialogService` and then using something like 
```java
DialogService dialogService = ... coming from somewhere
AboutDialogView aboutDialogView = new AboutDialogView();
dialogService.show(aboutDialogView);
```
to show the dialog with the proper owner (set in the dialogservice class). In this way, only the dialogservice needs to know about the main stage. Moreover, there are already a lot of places that have the dialog service floating around, so hopefully less changes are required.

**Comment by faeludire** [comment]
> ```java
> DialogService dialogService = ... coming from somewhere
> ```

Sounds good, can you explain how dependency inject is handled in this project, I'm unable to correctly inject `DialogSerivce` into `AboutDialogView`, thanks.

**Comment by tobiasdiez** [comment]
You can use `@Inject DialogService dialogService` in `View` classes, e.g here:
https://github.com/JabRef/jabref/blob/c8f7be89ad704065474decb61851e42416caf88d/src/main/java/org/jabref/gui/help/AboutDialogView.java#L23
This is then usually passed to the ViewModel, which uses it to open a dialog.
https://github.com/JabRef/jabref/blob/c8f7be89ad704065474decb61851e42416caf88d/src/main/java/org/jabref/gui/help/AboutDialogView.java#L45
But for our purposes here that's not very helpful as there are almost no dialogs created from other dialogs. For actions, the usual pattern is to pass it as a constructor argument, e.g. https://github.com/JabRef/jabref/blob/4cf2fb06d3d876d2043f65ca0e51c3c4185fd05c/src/main/java/org/jabref/gui/undo/UndoRedoAction.java

**Comment by faeludire** [comment]
What are your thoughts regarding instantiating via the `Injector.instantiateModelOrService()` method.

File: src/main/java/org/jabref/gui/JabRefDialogService.java [hunk 1]
```diff
@@ -69,11 +70,11 @@
     private static final Logger LOGGER = LoggerFactory.getLogger(JabRefDialogService.class);
     private static PreferencesService preferences;
 
-    private final Window mainWindow;
+    private static Window mainWindow;
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/JabRefDialogService.java:73]: Why did you made this a static variable?

File: src/main/java/org/jabref/gui/DialogService.java [hunk 2]
```diff
@@ -272,4 +273,6 @@ boolean showConfirmationDialogWithOptOutAndWait(String title, String content,
      * @return the selected file or an empty {@link Optional} if no file has been selected
      */
     Optional<Path> showFileOpenFromArchiveDialog(Path archivePath) throws IOException;
+
+    void show(BaseDialog<?> aboutDialogView);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/DialogService.java:277]: I would rename it to `showCustomDialog` to be coherent with the above method. Or rename that to `showAndWait`...yeah maybe the later?

Please also rename the argument, and add a bit of documentation.

**Review by tobiasdiez — COMMENTED** [review]
Using the `Injectior` is actually a very good idea!

File: src/main/java/org/jabref/gui/JabRefDialogService.java (hunk 1 above)
Comment (faeludire) [reply src/main/java/org/jabref/gui/JabRefDialogService.java]: This was done because `createDialog()` and `createDialogWithOptOut()` were both static, I've updated both methods to be non-static.

File: src/main/java/org/jabref/gui/DialogService.java (hunk 2 above)
Comment (faeludire) [reply src/main/java/org/jabref/gui/DialogService.java]: > I would rename it to `showCustomDialog` to be coherent with the above method. Or rename that to `showAndWait`...yeah maybe the later?
> 
> Please also rename the argument, and add a bit of documentation.

Decided to go with `showCustomDialog()` as it seems to be more consistent with other methods in that interface.

**Review by tobiasdiez — APPROVED** [review]
Thanks a lot for the quick follow-ups! The code looks good to me!

**Comment by faeludire** [comment]
The added test seems to be failing, I am unable to run the tests locally. Do you have an idea what I might be missing in the test?

**Review by tobiasdiez — COMMENTED** [review]
Testing javafx code is a bit more involved as you have to start the gui interface, see e.g. https://github.com/JabRef/jabref/blob/c8f7be89ad704065474decb61851e42416caf88d/src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java for an example.
To be honest, here it would be fine not to add a test (although it's always good to have tests of course).

**Review by tobiasdiez — APPROVED** [review]
Thanks a lot for your PR! LGTM

**Comment by faeludire** [comment]
> Thanks a lot for your PR! LGTM

Thanks for the help and comments. 👍🏾

**Review by Siedlerchr — APPROVED** [review]
LGTM! 
It would be nice if you add some summary and explanation to our devdocs what to do when creating a new dialog, e.g using dialogService to start 
https://devdocs.jabref.org/getting-into-the-code/code-howtos#javafx

**Comment by Siedlerchr** [comment]
Please have a look at the markdownlint checkstlye output. Then I would be happy to merge

**Comment by koppor** [comment]
This PR causes the about dialog not opening a second time (see https://github.com/JabRef/jabref/issues/7287). Some dialogs can also be opened twice (Customized Entry Types).

@faeludire Could you have a look please?

**Comment by faeludire** [comment]
> This PR causes the about dialog not opening a second time (see #7287). Some dialogs can also be opened twice (Customized Entry Types).
> 
> @faeludire Could you have a look please?

Can you explain what you mean by some dialogs can also be opened twice?
