### PR TITLE
Fix inconsistent search results for date-related queries fixes#12296

### LINKED ISSUE #12296: meaningful search
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-12-11--38576bb Linux 6.11.11-300.fc41.x86_64 amd64  Java 23.0.1  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Given a library with several 2012 entries, in which the date is configured in various ways, e.g. as `date`, `Date`, `year`.
3. Search your library for `Date=2012`
4. Search your library for `date=2012`
5. Search your library for `year=2012`

will all produce different hits.

Sorry, the new search engine makes me typically frustrated.

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by AbdoMostfa2**
### Fix inconsistent search results for date-related queries

This update ensures that searching for different date fields (e.g., year=2012, date=2012, Date=2012) returns consistent results. Previously, these queries produced different results due to variations in field names.

Closes #12296

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ /] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [/] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by AbdoMostfa2** [comment]
@Siedlerchr
I have another solution for this issue: since we treat date the same as year, we could map one to the other in the IndexManager. However, what if the user wants to include both year and date in the BibEntry? Would that be a valid use case?

**Comment by Siedlerchr** [comment]
Jabref treats date and year as alias fields. And some others as well. 
There's a method getFieldOrAlias 
You would need to compare the search with the one in JabRef 5.15 to see how alias fields are treated there. My guess would be if I search for date, if the field exist return that value else the alias

**Comment by koppor** [comment]
1. Download JabREf 5.15 as portable edition at https://github.com/JabRef/jabref/releases/tag/v5.15
2. Disable single instance\
    image
3. Start development version of JabRef and 5.15 in the same time --> you can then check in parallel.

File: src/main/java/org/jabref/logic/search/query/SearchToSqlVisitor.java [hunk 1]
```diff
@@ -228,6 +228,14 @@ private SqlQueryNode getFieldQueryNode(String field, String term, EnumSet<Search
             term = escapeTermForSql(term);
         }
 
+        if (field.equalsIgnoreCase(StandardField.DATE.getName()) || field.equalsIgnoreCase(StandardField.YEAR.getName())) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/search/query/SearchToSqlVisitor.java:231]: I think, this is the wrong approach. `org.jabref.model.entry.EntryConverter#FIELD_ALIASES` needs to be used - maybe all fields "unzipped" into postgres

Maybe, also a "view" in postgres needs to be generated - a `derived_date` covering the date and then the query on the month/day/... go to this view.. The view could offer all fields values pre-calculated.

Comment (AbdoMostfa2) [reply src/main/java/org/jabref/logic/search/query/SearchToSqlVisitor.java]: My initial thought was that the issue was only related to the date and year fields, so my first approach focused on that. After your clarification, I realized the need to handle all date-related fields properly.
I’ve now updated the solution accordingly.

Comment (koppor) [reply src/main/java/org/jabref/logic/search/query/SearchToSqlVisitor.java]: A view can be a next step. A view typically helps to gain performance and reduce memory consumption.

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java [hunk 2]
```diff
@@ -239,7 +242,12 @@ private void addToIndex(BibEntry bibEntry) {
                 }
                 // endregion
             }
-
+            // ensure all date-related fields are indexed.
+            for (Field dateField : dateFields) {
+                Optional<String> resolvedDateValue = bibEntry.getResolvedFieldOrAlias(dateField, this.databaseContext.getDatabase());
+                String dateValue = resolvedDateValue.orElse("");
+                addBatch(preparedStatement, entryId, dateField, dateValue);
```
Comment (koppor) [inline src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:249]: I know, Optionals are hard to learn, please:

Use the methods of java.util.Optional. `ifPresent`.

NOT

```java
Optional<String> resolved = bibEntry.getResolvedFieldOrAlias(...);
String value = resolved.orElse("");
doSomething(value)
```

BUT

```java
Optional<String> resolved = bibEntry.getResolvedFieldOrAlias(...);
resolved.ifPresent(value -> doSomething(value));
```

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java [hunk 3]
```diff
@@ -301,19 +309,45 @@ private void insertField(BibEntry entry, Field field) {
                 FIELD_NAME,
                 FIELD_VALUE_LITERAL,
                 FIELD_VALUE_TRANSFORMED);
+        String insertDateFieldQuery = """
+                INSERT INTO %s ("%s", "%s", "%s", "%s")
+                VALUES (?, ?, ?, ?)
+                ON CONFLICT ("%s", "%s")
```
Comment (koppor) [inline src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:315]: `ON CONFLICT` is not clear to me. Add Java coment

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java [hunk 4]
```diff
@@ -301,19 +309,45 @@ private void insertField(BibEntry entry, Field field) {
...
-            LOGGER.error("Could not add an entry to the index.", e);
+                Optional<String> resolvedFieldLatexFree = entry.getResolvedFieldOrAliasLatexFree(field, this.databaseContext.getDatabase());
+                assert resolvedFieldLatexFree.isPresent();
+                addBatch(preparedStatement, entryId, field, value, resolvedFieldLatexFree.orElse(""));
+                preparedStatement.executeBatch();
+            } catch (SQLException e) {
+                LOGGER.error("Could not add an entry to the index.", e);
+            }
         }
-
```
Comment (koppor) [inline src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:316]: Why empty line removed?

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java [hunk 5]
```diff
@@ -325,7 +359,6 @@ private void insertField(BibEntry entry, Field field) {
                 FIELD_VALUE_TRANSFORMED);
 
         try (PreparedStatement preparedStatement = connection.prepareStatement(insertIntoSplitTable)) {
-            String entryId = entry.getId();
```
Comment (koppor) [inline src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:328]: I don't know why this part of the code is touched. I totally forgot about the use of the split fields. I asked @LoayGhreeb for support at documentaiotn

**Review by koppor — DISMISSED** [review]

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java (hunk 3 above)
Comment (AbdoMostfa2) [reply src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:315]: This handles situations where the user inserts conflicting data, such as date=2025-03-17 and year=2026. In this case, it will overwrite the previously calculated year. Should I ignore this conflict instead?

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java (hunk 5 above)
Comment (AbdoMostfa2) [reply src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:328]: I think the Split Table handles multi-valued fields like keywords or groups. I did not remove it, but the entryId is calculated above.

Comment (koppor) [reply src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:328]: Could you add a Java comment to `org.jabref.model.search.PostgreConstants#getSplitTableSchemaReference` please?

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java (hunk 3 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:315]: Please add Java comment

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java [hunk 6]
```diff
@@ -40,6 +40,7 @@ public class BibFieldsIndexer {
     private static final Logger LOGGER = LoggerFactory.getLogger(BibFieldsIndexer.class);
     private static final LatexToUnicodeFormatter LATEX_TO_UNICODE_FORMATTER = new LatexToUnicodeFormatter();
     private static final Pattern GROUPS_SEPARATOR_REGEX = Pattern.compile("\s*,\s*");
+    private static final Set<Field> DATE_FIELDS = new HashSet<>(Arrays.asList(StandardField.DATE, StandardField.YEAR, StandardField.MONTH, StandardField.DAY));
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:43]:
```suggestion
    private static final Set<Field> DATE_FIELDS = new Set.of(StandardField.DATE, StandardField.YEAR, StandardField.MONTH, StandardField.DAY);
```

File: src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java [hunk 7]
```diff
@@ -215,10 +217,12 @@ private void addToIndex(BibEntry bibEntry) {
...
-                Optional<String> resolvedFieldLatexFree = bibEntry.getResolvedFieldOrAliasLatexFree(field, this.databaseContext.getDatabase());
-                assert resolvedFieldLatexFree.isPresent();
-                addBatch(preparedStatement, entryId, field, value, resolvedFieldLatexFree.orElse(""));
-
+                // Skip indexing of date-related fields separately to ensure proper handling later in the process.
+                if (!DATE_FIELDS.contains(field)) {
+                    Optional<String> resolvedFieldLatexFree = bibEntry.getResolvedFieldOrAliasLatexFree(field, this.databaseContext.getDatabase());
+                    assert resolvedFieldLatexFree.isPresent();
+                    addBatch(preparedStatement, entryId, field, value, resolvedFieldLatexFree.orElse(""));
+                }
```
[the remark this answers is not in the document]
Comment (AbdoMostfa2) [reply src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:225]: I understand the point about using ifPresent() for better Optional handling. However, I deliberately retained the assertion because the comment emphasizes detecting potential flaws.

[the remark this answers is not in the document]
Comment (koppor) [reply src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:225]: Do both. 

Consistency with other code.

We cannot change current tooling easily.

[the remark this answers is not in the document]
Comment (koppor) [reply src/main/java/org/jabref/logic/search/indexing/BibFieldsIndexer.java:225]: You can also use get() and ignore the bot comment. Seems to be best (seeing these two lines only)

**Review by Siedlerchr — APPROVED** [review]
