### PR TITLE
Make entry editor DND behave as specified in settings

### LINKED ISSUE #5546: Link file (without copying) doesn't work
JabRef 5.0.0-dev--2019-10-29----3b6c355ae
Linux 5.0.0-32-generic amd64 
Java 12.0.2

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. open Preferences/Entry Editor
2. set Default drag & drop action to "Link file (without copying)"
3. The file nevertheless is renamed using the bibtex key.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #5546 

The setting only applies to the entry editor. The maintainable is still differentiating between the DND Modifiers as implemented in the linked PR
@koppor  

Refs #3765
----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/entryeditor/EntryEditor.java [hunk 1]
```diff
@@ -137,53 +137,20 @@ public EntryEditor(BasePanel panel, ExternalFileTypes externalFileTypes) {
                 FileDragDropPreferenceType dragDropPreferencesType = preferencesService.getEntryEditorFileLinkPreference();
 
                 if (dragDropPreferencesType == FileDragDropPreferenceType.MOVE) {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/entryeditor/EntryEditor.java]: Can we change this to a `switch` statement?

**Comment by tobiasdiez** [comment]
In my opinion, dnd onto the maintable and the entry editor should behave the same. Otherwise it's really confusing that some operations on the entry editor respect some settings while a similar action on the maintable does not.

**Comment by koppor** [comment]
Agree. Both should behave as outlined above (if possible) 😅

Tobias Diez <notifications@github.com> schrieb am Sa., 2. Nov. 2019, 15:01:

File: src/main/java/org/jabref/gui/entryeditor/EntryEditor.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/entryeditor/EntryEditor.java]: I actually found the old code confusing. If I select the default action to be linking and not moving, I would expect that behavior without pressing some modifier key.
However, if we decide to use modifier keys we should remove this setting from the preferences as the user gets the impression it is ignored. See the report in the linked issue.

My personal opinion would be to remove this modifier stuff at all. I doubt that the normal user is aware of the modifier keys

Checking for the OS does not make any sense, as it for linux depends on the desktop system the user has, and this might be different behaviors or not supporting modifiers

Comment (koppor) [reply src/main/java/org/jabref/gui/entryeditor/EntryEditor.java]: I checked https://github.com/JabRef/jabref/issues/5546. There, it is only talked about WITHOUT modifier keys.

As professional Windows user, I use modifier keys, too. For me, it is OK, if modifiers worked on Windows only and had no effect on other operating systems.

Since no one else seems to know that one can press modifier keys while copying, we can let this in and in a follow-up issue discuss and implement a proper solution.

**Comment by tobiasdiez** [comment]
@koppor why did you merged this although it removes functionality that we both agreed should be kept?! I'll revert since this is not a proper fix in my opinion.

**Comment by koppor** [comment]
I understood your comment wrong: I thought with this PR, they would behave the same. I did not check whether the entry editor supports modifier keys.

One should update https://github.com/koppor/jabref/issues/368 w.r.t. the current behavior of the entry editor.
