### PR TITLE
Fix storing multiline properties for custom fields in custom entry types

### LINKED ISSUE #9609: Custom entry types: Mulitline option not working
@Siedlerchr Hmm.  It works for me too, in @book entries.  But I have a special database (used with Glossaries) that has only two fields.  And that doesn't work.  The setting tick-box just silently unticks itself and the field is never wrapped.  See attached video.

https://user-images.githubusercontent.com/762246/217361905-1f8865be-b40d-4937-889a-00c47ac21c93.mp4

_Originally posted by @wujastyk in https://github.com/JabRef/jabref/issues/5461#issuecomment-1421424894_

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #9609

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by calixtus — APPROVED** [review]

File: src/main/java/org/jabref/model/entry/field/UnknownField.java [hunk 1]
```diff
@@ -47,7 +54,7 @@ public int hashCode() {
     @Override
     public String toString() {
         return "UnknownField{" +
-                "name='" + name + '\'' +
-                '}';
+               "name='" + name + '\'' +
```
Comment (calixtus) [inline src/main/java/org/jabref/model/entry/field/UnknownField.java:57]: one ' is escaped, the other not, because of surrounding double quotes. technically correct, but it hurts my eyes.

Comment (Siedlerchr) [reply src/main/java/org/jabref/model/entry/field/UnknownField.java:57]: Probably auto generated by the IDE(A)
