### PR TITLE
Fix adding files with illegal characters

### LINKED ISSUE #10182: saving destroyed library: error when using a PDF file name with opening "{" or closing "}" ONLY inside file name
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new library
2. Create test PDF file with opening "{" or closing "}" ONLY inside file name
3. Add new library entry
4. Assign this PDF file to the "file" field of the entry
5. Save the library
6. Error occurs:

Opening `{` error:

afbeelding

Closing `}` error:

afbeelding

When you try to open the library file (after closing JabRef), the library file is destroyed somewhere and can't be opened anymore!!!

The following errors occur when opening the library file again

afbeelding

afbeelding

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #10182

Also supported for drag and drop

(The FilenameCleanerTest can be converted to parameterized test, bu this can be an easy student task)

grafik

Display a dialog with auto-renaming option

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by calixtus** [comment]
I suggest rephrasing the right button "Rename and add" and remove the button describing sentences in the dialog text.

File: src/main/java/org/jabref/gui/externalfiles/ExternalFilesEntryLinker.java [hunk 1]
```diff
@@ -102,4 +110,32 @@ public void copyFilesToFileDirAndAddToEntry(BibEntry entry, List<Path> files, In
...
+                        LOGGER.error("Error moving file", ex);
+                        dialogService.showErrorDialogAndWait(ex);
+                    }
+                }
+            } else {
+                validFileNames.add(fileToAdd);
+            }
+        }
+        return validFileNames;
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/externalfiles/ExternalFilesEntryLinker.java:140]: A lot of code duplication to LinkedFilesEditorViewModel, but fine for a hotfix. Maybe an followup PR should clean this up.

**Review by calixtus — APPROVED** [review]
