### PR TITLE
#14058 Fix alphabetical ordering in dropdown

### LINKED ISSUE #14058: Fix alphabetical ordering in dropdown.
1. Start JabRef
2. Open preferences
3. Go to "External programs"
4. Open dropddown "Applications to push entries to"
5. See that "TeXShop" and "VScode" is are not sorted alphabetically

Image

Sort them alphabetically.

### PR DESCRIPTION
**Pull request by am167**
Closes #14058 

This PR fixes #14058 by sorting the APPLICATION list alphabetically. 
I have made the decision to sort the whole list rather than just reorder how applications are inserted into the GUI. Personally I think this is better but happy to revert back to just changing the order of the list.

### Steps to test

1. Start JabRef
2. Open preferences
3. Go to "External programs"
4. Open dropddown "Applications to push entries to"
5. Observe that drop down options are displayed alphabetically ascending

image

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

### CODE REVIEW

**Comment by am167** [comment]
Do I need to make a new PR to resolve [Source branch is other than "main" (pull_request)](https://github.com/JabRef/jabref/actions/runs/18400712860/job/52429098399?pr=14060)?

**Comment by Siedlerchr** [comment]
For the text time please create a new branch but this is okay now.

**Comment by am167** [comment]
Understood, thanks

File: jabgui/src/main/java/org/jabref/gui/push/GuiPushToApplications.java [hunk 1]
```diff
@@ -32,6 +34,8 @@ public static List<GuiPushToApplication> getAllGUIApplications(DialogService dia
                 new GuiPushToTexShop(dialogService, preferences),
                 new GuiPushToVScode(dialogService, preferences)));
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/push/GuiPushToApplications.java]: Please sort these, to make life easier - an intuitive sort ordering is alphabet - maybe release date of apps, but not the point in time being added to JabRef.

Having the additional sorting step is OK - maybe, the display name is different than the class name.

Comment (am167) [reply jabgui/src/main/java/org/jabref/gui/push/GuiPushToApplications.java]: Hi @koppor, I've pushed the changes you requested. Thanks
