### PR TITLE
Sorted list of content selectors

### LINKED ISSUE #3791: No order of items in content selectors
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1

Steps to reproduce:

1. Add a number of entries to JabRef
2. Go to General > Keyword and type
3. You'll see a list of unsorted keywords that make it hard to pick a particular one

jabref4-1_selectors

Alphabetical order would be great.

### PR DESCRIPTION
**Pull request by BJaroszkowski**
List of keywords added in "Manage content selectors" is now always displayed in alphabetic order. Also added tests for ContentSelectorSuggestionProvider and ContentSelectorDialogViewModel classes which include asserting alphabetical order in suggestions affected by content selectors as well.
Fixes #3791.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

mcs_sorted_image

### CODE REVIEW

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java [hunk 1]
```diff
@@ -153,8 +154,8 @@ private void addKeywordIfUnique(Field field, String keywordToAdd) {
 
         List<String> existingKeywords = fieldKeywordsMap.getOrDefault(field, new ArrayList<>());
         existingKeywords.add(keywordToAdd);
+        existingKeywords.sort(Comparator.naturalOrder());
         fieldKeywordsMap.put(field, existingKeywords);
-        keywords.add(keywordToAdd);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java:157]: Can you please explain why this is removed?

**Comment by Siedlerchr** [comment]
Thanks, in general looks good to me, just one question and please have a look at the failing checkstyle test

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java (hunk 1 above)
Comment (BJaroszkowski) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java:157]: On the next line we call `populateKeywords` which clears the `keywords`  and then populates it with keywords from `fieldKeywordsMap`.  Since it makes no difference if we add to `keywords` at this point I simply deleted this line.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java:157]: Ah thanks for the clarification!

**Review by Siedlerchr — APPROVED** [review]

**Review by calixtus — APPROVED** [review]
Looks good to me too. Thanks!
