### PR TITLE
fix ClassCastException during drag-and-drop caused by transient tab state

### LINKED ISSUE #12921: Trying to rearrange the welcome tab causes an exception
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Build date: 2025-04-11

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Disable the setting to "Hide Tab bar when single library is present"
2. Create a library (Or create 2 if you skipped step 1)
3. Click and drag the Welcome tab and move it beside the newly created library
5. Error occurs

image

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by 070jhz**
Closes #12921 

the type-check predicate can behave inconsistently during the interaction, likely a timing/synchronization issue caused by how the UI updates the tab list during drag-and-drop while the filtered list is reacting to changes.
directly mapping over the original tabs list with a lambda that accoutns for possible non-``LibraryTab`` entries solves the issue. this results in ``openDatabaseList`` possibly holding null values but since it is a private member not accessed elsewhere and we bind a filtered version to ``StateManager::openDatabases``, it should not cause any further bugs.

a more robust solution could be implemented with listeners, but it might be overkill ?

### Steps to test

1. Disable the setting to "Hide Tab bar when single library is present"
2. Create a library (Or create 2 if you skipped step 1)
3. Click and drag the Welcome tab and move it beside the newly created library
4. Exception no longer occurs

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [/] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [/] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 1]
```diff
@@ -374,13 +374,15 @@ private void initKeyBindings() {
...
-        // Bind global state
-        FilteredList<Tab> filteredTabs = new FilteredList<>(tabbedPane.getTabs());
-        filteredTabs.setPredicate(LibraryTab.class::isInstance);
-
         // This variable cannot be inlined, since otherwise the list created by EasyBind is being garbage collected
-        openDatabaseList = EasyBind.map(filteredTabs, tab -> ((LibraryTab) tab).getBibDatabaseContext());
-        EasyBind.bindContent(stateManager.getOpenDatabases(), openDatabaseList);
+        openDatabaseList = EasyBind.map(tabbedPane.getTabs(), tab -> {
+            if (tab instanceof LibraryTab) {
+                return ((LibraryTab) tab).getBibDatabaseContext();
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]:
```suggestion
            if (tab instanceof LibraryTab libraryTab) {
                return libraryTab.getBibDatabaseContext();
```

**Comment by koppor** [comment]
This is a JavaFX issue. @Siedlerchr how to report?

Update: Moved to https://github.com/JabRef/jabref/issues/12921#issuecomment-2939649828 as it concerns more the original issue than this work around

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 2]
```diff
@@ -374,13 +374,15 @@ private void initKeyBindings() {
...
-        openDatabaseList = EasyBind.map(filteredTabs, tab -> ((LibraryTab) tab).getBibDatabaseContext());
-        EasyBind.bindContent(stateManager.getOpenDatabases(), openDatabaseList);
+        openDatabaseList = EasyBind.map(tabbedPane.getTabs(), tab -> {
+            if (tab instanceof LibraryTab libraryTab) {
+                return libraryTab.getBibDatabaseContext();
+            } else {
+                return null;
+            }
+        });
+        EasyBind.bindContent(stateManager.getOpenDatabases(), new FilteredList<>(openDatabaseList, Objects::nonNull));
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: I think, the list will be wrong on tab change. Maybe some custom code needs to be placed here? IDK.

**Review by koppor — CHANGES_REQUESTED** [review]
Code nees to be adapted, since the FilteredList is not right at all due to a JavaFX bug.

**Comment by Siedlerchr** [comment]
you can file a bug report https://bugreport.java.com/bugreport/
It will take a while until it is processed
For company you can use JabRef e.V.

**Comment by koppor** [comment]
> you can file a bug report [bugreport.java.com/bugreport](https://bugreport.java.com/bugreport/) 

Submitted a JavaFX error report - internal review ID : 9078592

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java (hunk 2 above)
Comment (070jhz) [reply jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: is there a specific case you had in mind ? i manually tested tab changes (opening, closing, rearranging) and ``openDatabaseList`` seems to accurately reflect the tab state.

**Comment by 070jhz** [comment]
> Code nees to be adapted, since the FilteredList is not right at all due to a JavaFX bug.

exception no longer occurs with no FilteredList usage, with the lists accurately reflecting the state of the tabs. i added some listener code to filter out the nulls from the mapping and keep it in sync with ``stateManager::openDatabaseList``

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 3]
```diff
@@ -374,13 +373,18 @@ private void initKeyBindings() {
...
-        EasyBind.bindContent(stateManager.getOpenDatabases(), openDatabaseList);
+        openDatabaseList = EasyBind.map(tabbedPane.getTabs(), tab -> {
+            if (tab instanceof LibraryTab libraryTab) {
+                return libraryTab.getBibDatabaseContext();
+            } else {
+                return null;
+            }
+        });
+
+        // call compromised until further notice
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: Please add link to something, one can follow

```suggestion
        // call compromised until further notice, See https://github.com/JabRef/jabref-koppor/pull/713 for details.
```

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 4]
```diff
@@ -374,13 +373,18 @@ private void initKeyBindings() {
...
         // This variable cannot be inlined, since otherwise the list created by EasyBind is being garbage collected
-        openDatabaseList = EasyBind.map(filteredTabs, tab -> ((LibraryTab) tab).getBibDatabaseContext());
-        EasyBind.bindContent(stateManager.getOpenDatabases(), openDatabaseList);
+        openDatabaseList = EasyBind.map(tabbedPane.getTabs(), tab -> {
+            if (tab instanceof LibraryTab libraryTab) {
+                return libraryTab.getBibDatabaseContext();
+            } else {
+                return null;
+            }
+        });
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: This can also be commented - or even removed to keep the code clean. -- see below for a proposl saving this. 

You can add a link to https://github.com/JabRef/jabref-koppor/pull/713 and this PR and tell people to check whether https://github.com/JabRef/jabref-koppor/pull/713 was solved and then can bring back the original state before the PR of JabRef's code.

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 5]
```diff
@@ -374,13 +373,18 @@ private void initKeyBindings() {
...
+
+        // call compromised until further notice
+        // EasyBind.bindContent(stateManager.getOpenDatabases(), new FilteredList<>(openDatabaseList));
+        bindContentFiltered(openDatabaseList, stateManager.getOpenDatabases(), Objects::nonNull);
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: You can pass `getTabs()` directly and use `LibraryTab.class::isInstance` can't you?

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 6]
```diff
@@ -454,6 +458,45 @@ private void initBindings() {
...
     }
 
+    private static <T> void bindContentFiltered(ObservableList<T> source, ObservableList<T> target, java.util.function.Predicate<T> filter) {
+        // Initial sync
+        target.setAll(source.stream().filter(filter).toList());
+
+        source.addListener((ListChangeListener<T>) c -> {
+            while (c.next()) {
+                if (c.wasPermutated()) {
+                    // Full reorder pass
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]:
```suggestion
                    // We need a fresh copy as permutation is much harder to mirror
```

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 7]
```diff
@@ -454,6 +458,45 @@ private void initBindings() {
...
+                    for (T removed : c.getRemoved()) {
+                        target.remove(removed);
+                    }
+                }
+
+                if (c.wasAdded()) {
+                    int sourceIndex = c.getFrom();
+                    int targetIndex = 0;
+
+                    for (int i = 0; i < sourceIndex; i++) {
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]:
```suggestion
                    // We need to add at the correct place - therefore, we need to find out the correct position
                    for (int i = 0; i < sourceIndex; i++) {
```

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 8]
```diff
@@ -374,13 +373,18 @@ private void initKeyBindings() {
...
-        EasyBind.bindContent(stateManager.getOpenDatabases(), openDatabaseList);
+        openDatabaseList = EasyBind.map(tabbedPane.getTabs(), tab -> {
+            if (tab instanceof LibraryTab libraryTab) {
+                return libraryTab.getBibDatabaseContext();
+            } else {
+                return null;
+            }
+        });
+
+        // call compromised until further notice, See https://github.com/JabRef/jabref-koppor/pull/713 for details.
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: I cased wrong - new proposal

```suggestion
        // Call compromised until further notice. See https://github.com/JabRef/jabref-koppor/pull/713 for details.
```

File: jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java [hunk 9]
```diff
@@ -454,6 +455,55 @@ private void initBindings() {
         EasyBind.subscribe(preferences.getWorkspacePreferences().hideTabBarProperty(), _ -> updateTabBarVisible());
     }
 
+    private static void bindContentFiltered(ObservableList<Tab> source, ObservableList<BibDatabaseContext> target, java.util.function.Predicate<Tab> filter) {
+        java.util.function.Function<Tab, BibDatabaseContext> tabToContext = tab -> ((LibraryTab) tab).getBibDatabaseContext();
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: Isn't it possible to `import` `Predicate` and `Function`?

Comment (070jhz) [reply jabgui/src/main/java/org/jabref/gui/frame/JabRefFrame.java]: Yes my bad I forgot to change that

**Review by calixtus — APPROVED** [review]

**Review by koppor — APPROVED** [review]
