### PR TITLE
Fix for issue 5850: Journal abbreviations in UTF-8 not recognized

### LINKED ISSUE #5850: Journal abbreviations in UTF-8 not recognized
When running an integrity check, Jabref complains about non-ASCII characters in the journal title. However, changing UTF-8 to ASCII generates the error: "Journal not found in abbreviation list".

Since the journal abbreviation lists are encoded in UTF-8, it would be nice if Jabref recognizes both formats and treats them equally.

### PR DESCRIPTION
**Pull request by MrGhabi**
Fixes #5850

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### Reproduce the issue:
1. New library
2. New article
3. BibeTx source adds the following:
   ```
   @article{杨芙清2005软件工程技术发展思索,
     title={软件工程技术发展思索},
     author={杨芙清},
     journal={软件学报},
     volume={16},
     number={1},
     year={2005},
     publisher={Citeseer}
   }
   ```
4. click "check integrity" 

The main reason for this bug is the check-tools `Check integrity` only accept the charset ASCII. It works well in English citations, but  **jabref** has users across the world and they have different charsets. 

### The screenshot:
1. before:
before

2. after
intigrity-check

### The way to fix:
1. First I find the bug related to the class `ASCIICharacterChecker.java`
2. In this class 
```
boolean asciiOnly = CharMatcher.ascii().matchesAllOf(field.getValue());
```
any non-ASCII encoded characters will be warned.
3. Then I remove the steps in `IntegrityCheck` .

And still, I want to give a warning about non-UTF8 encoded characters.
1. I get the default encoding from the system (Since we need to give a warning when the field cannot be decoded in UTF-8. And this may happen when users' default encoding charset is non-UTF-8)
2. check whether the value of fields(string) can be decoded in UTF-8
3. if not, just give a warning about "Non-UTF-8 encoded found"

To check this, we need first set out the default charset(for example GBK) in the whole environment. 
Then we can get the following warning when using Integrity check:
image

### CODE REVIEW

File: src/main/java/org/jabref/logic/integrity/UTF8Checker.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+public class UTF8Checker implements EntryChecker {
+
+    /**
+     * Detect any non UTF-8 encoded field
+     */
+    @Override
+    public List<IntegrityMessage> check(BibEntry entry) {
+        List<IntegrityMessage> results = new ArrayList<>();
+        for (Map.Entry<Field, String> field : entry.getFieldMap().entrySet()) {
+            Charset charset = Charset.forName(System.getProperty("file.encoding"));
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/integrity/UTF8Checker.java:25]: I would extract this out of the loop, as it doesn't depend on the loop.

File: CHANGELOG.md [hunk 2]
```diff
@@ -76,6 +76,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where opening BibTex file (doubleclick) from Folder with spaces not working. [#6487](https://github.com/JabRef/jabref/issues/6487)
 - We fixed an issue with saving large `.bib` files [#7265](https://github.com/JabRef/jabref/issues/7265)
 - We fixed an issue with very large page numbers [#7590](https://github.com/JabRef/jabref/issues/7590)
+- We fixed an issue where journal abbreviations in UTF-8 not recognized [#5850](https://github.com/JabRef/jabref/issues/5850)
```
Comment (Siedlerchr) [inline CHANGELOG.md:79]:
```suggestion
- We fixed an issue where journal abbreviations in UTF-8 were not recognized [#5850](https://github.com/JabRef/jabref/issues/5850)
```

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Thanks! Looks already good. PLease have a look at the checkstyle issues

File: src/main/java/org/jabref/logic/integrity/UTF8Checker.java (hunk 1 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/logic/integrity/UTF8Checker.java:25]: What's the reason to use `System.getProperty("file.encoding")` and not say the encoding specified in the Library properties?

**Comment by tobiasdiez** [comment]
I might be not up-to-date, but I always thought UTF8 characters are only allowed in biblatex and that bibtex only handles asci characters. Did this change?

File: src/main/java/org/jabref/logic/integrity/UTF8Checker.java (hunk 1 above)
Comment (MrGhabi) [reply src/main/java/org/jabref/logic/integrity/UTF8Checker.java:25]: Since different users have different charsets due to the operating system or the default settings of the computer. And `System.getProperty("file.encoding")` is used get the default charset. If the charset is not UTF-8, we should give a warning about that.
And the reason not to use the Library properties & Database properties: Maybe the user doesn't know the default charset in his computer or he set the charset for jabref, but we should give a warning about that since Non-UTF-8 charset may cause to garbled.

File: CHANGELOG.md (hunk 2 above)
Comment (MrGhabi) [reply CHANGELOG.md:79]: OK, I will change it!

File: src/main/java/org/jabref/logic/integrity/UTF8Checker.java (hunk 1 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/logic/integrity/UTF8Checker.java:25]: Ok thanks for the explanation. 

But doesn't this give a lot of false positives? Say I have my library encoded in Charset A, and my systems default is Charset B. If all characters in my database are properly encoded with Charset A, then I shouldn't get any warnings even though some of the characters may not be encodable in Charset B, right?

But I also have to admit that I do not yet understand the use-case from the user perspective, so maybe I'm missing something obvious.

**Comment by MrGhabi** [comment]
> I might be not up-to-date, but I always thought UTF8 characters are only allowed in biblatex and that bibtex only handles asci characters. Did this change?

Yeah,  some journals and papers use non-ASCII characters as their names.. etc(just as the bib in bibtex I added before). and maybe it is difficult to do with it in jabref. The details are shown in the issue. So I think maybe it is better to trade them equally.

File: src/main/java/org/jabref/logic/integrity/UTF8Checker.java (hunk 1 above)
Comment (MrGhabi) [reply src/main/java/org/jabref/logic/integrity/UTF8Checker.java:25]: I have thought about that. In my test, if one user's default charset is A then his paste-board, his input is all encoded in A.  So when he input something maybe just garbled. Maybe there is an example: https://github.com/JabRef/jabref/issues/7629
So the scenario may be rare. That's the reason I don't choose to get the charset by `Charset charset = bibDatabaseContext.getMetaData().getEncoding().orElse(preferences.getDefaultEncoding());` 

By the way, I have a question about the design. If the bibtex is only allowed in ascii in design, why do we allow the user to save it into different charsets?

**Comment by tobiasdiez** [comment]
I don't really have experience with say Chinese names (as authors or journals) with bibtex. But the only evidence I could find was always suggesting bibLAtex, since bibtex doesn't support UTF8, see e.g. https://tex.stackexchange.com/questions/100092/how-to-include-a-chinese-paper-in-reference-via-bibtex.

So does it make more sense to keep the asci check for bibtex, and add the new utf8 check for biblatex?

**Comment by Siedlerchr** [comment]
I agree with @tobiasdiez  we need the utf8 check for biblatex and the ascii checker for bibtex then.

**Comment by MrGhabi** [comment]
> I don't really have experience with say Chinese names (as authors or journals) with bibtex. But the only evidence I could find was always suggesting bibLAtex, since bibtex doesn't support UTF8, see e.g. https://tex.stackexchange.com/questions/100092/how-to-include-a-chinese-paper-in-reference-via-bibtex.
> 
> So does it make more sense to keep the asci check for bibtex, and add the new utf8 check for biblatex?



> I agree with @tobiasdiez we need the utf8 check for biblatex and the ascii checker for bibtex then.

Good idea！I will refactor my code to meet this need! (After searching more information about bibtex and biblatex, I agree with you~ )

And the check of utf8 for biblatex maybe it's not a bug but an enhancement? (laugh) I will focus on it!

**Comment by MrGhabi** [comment]
Hi Reviewers! I have added the UTF-8 check for biblatex and recovery the ASCII check for bibtex! 
Is there anything I should do to give a better submission?

**Comment by Siedlerchr** [comment]
So far looks good, you only need to add the new localization string the l10 files, see here for more details https://devdocs.jabref.org/getting-into-the-code/code-howtos#using-localization-correctly

**Comment by MrGhabi** [comment]
Hi reviewers！I added this statement to all language packs, but I rely on Google Translate for most of my translations, so please double check it for errors~

**Comment by Siedlerchr** [comment]
You only need to add it to the English file. All otherttranslations are managed by crowdin.

**Comment by MrGhabi** [comment]
> You only need to add it to the English file. All otherttranslations are managed by crowdin.

Emmm, so I need to subtract all the files except the English file, right?

**Comment by MrGhabi** [comment]
I have changed that. Hope everything goes well...

**Review by Siedlerchr — APPROVED** [review]

**Comment by MrGhabi** [comment]
I added the javaDoc for UTFChecker and fix a little problem in my Junit test.

File: src/test/java/org/jabref/logic/integrity/UTF8CheckerTest.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+    @Test
+    void fieldDoesNotAcceptUmlauts() {
+        String defaultCharset = System.getProperty("file.encoding");
+        System.getProperties().put("file.encoding", "GBK");
+        UTF8Checker checker = new UTF8Checker();
+        String NonUTF8 = "";
+        try {
+            NonUTF8 = new String("你好，这条语句使用GBK字符集".getBytes(), "GBK");
+        } catch (Exception e) {
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/integrity/UTF8CheckerTest.java:32]: You can simply remove that catch here and add throws Exception to the test method

Comment (MrGhabi) [reply src/test/java/org/jabref/logic/integrity/UTF8CheckerTest.java:32]: OK！

File: src/main/java/org/jabref/logic/integrity/UTF8Checker.java (hunk 1 above)
Comment (MrGhabi) [reply src/main/java/org/jabref/logic/integrity/UTF8Checker.java]: Hi, reviewer! @tobiasdiez  After thinking for a long time and doing some tests, I think maybe it's better to give 2 kinds of warning:
1. In BibLatex, if the Library charset is not UTF-8, then give a warning `Non-UTF-8 field found.`
2. In both BibLatex and BibTeX, if the System env is not UTF-8, give the warning `Non-UTF-8 env, may cause garbled.`
And I'm eagerly waiting for your suggestions and reply！

File: src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java [hunk 4]
```diff
@@ -145,6 +149,94 @@ void testEntryIsUnchangedAfterChecks() {
...
     }
 
+    /**
+     * testCheckersForBibTex use injection to test the checkers in integrity check of BibTex
+     *
+     * @throws NoSuchFieldException   when using getDeclaredField in integrityCheck.getClass().getDeclaredField("entryCheckers")
+     * @throws IllegalAccessException when using Get method in entryCheckersField.get(integrityCheck)
+     */
+    @Test
+    void testCheckersForBibTex() throws NoSuchFieldException, IllegalAccessException {
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java:159]: These tests are a bit complicated. In addition, it's not useful to test a private fields or methods. https://dzone.com/articles/dont-test-private-methods
You can implicitly test if the function was called. Have a look at the IntegrityCheckTest class
It tests the integrity checker to produce correct results, e.g. it tests that the check is working and produces the correct result.

**Review by Siedlerchr — CHANGES_REQUESTED** [review]

File: src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java (hunk 4 above)
Comment (MrGhabi) [reply src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java:159]: Yeah, and if I directly use the return result to check the IntegrityCheck, It maybe still complicated (since every check I would manage to give an error entry to get the return result set.)! 
So maybe it is better to write the test in the submodel of integrity check to test the checkers? (It means that I will simply remove these 2 tests).
Hope for your reply!

Comment (Siedlerchr) [reply src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java:159]: Yes, just delete the two tetst classes. The UTF8Checkers test is fine.

Comment (MrGhabi) [reply src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java]: OK,  I have removed the unwieldy Junit tests

**Comment by Siedlerchr** [comment]
Thanks a lot for your contribution!
