### PR TITLE
Fix group filter icon in side pane

### LINKED ISSUE #15402: Change icon of group filtering to filter icon
The icon for groups filtering should be a filter (same as upper right icon in the screenshot)

Image

### PR DESCRIPTION
**Pull request by jadegold55**
### Related issues and pull requests

Closes #15402

### PR Description

This changes the groups side pane filter field to use the filter icon instead of the search icon so the UI matches its actual purpose.

### Steps to test

1. Start JabRef.
2. Open the Groups side pane.
3. Verify that the field with the placeholder "Filter groups..." shows a filter icon on the left.
4. Confirm that the Web search field still shows the search icon.

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

Current State: 

image

### CODE REVIEW

File: jabgui/src/test/java/org/jabref/gui/search/SearchTextFieldTest.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    @Test
+    void createUsesRequestedIcon() {
+        KeyBindingRepository keyBindingRepository = Mockito.mock(KeyBindingRepository.class);
+
+        CustomTextField textField = SearchTextField.create(keyBindingRepository, IconTheme.JabRefIcons.FILTER);
+
+        Node leftGraphic = textField.getLeft();
+        assertEquals(IconTheme.JabRefIcons.FILTER.getGraphicNode().toString(), leftGraphic.toString());
+        assertTrue(leftGraphic.getStyleClass().contains("search-field-icon"));
+    }
```
Comment (calixtus) [inline jabgui/src/test/java/org/jabref/gui/search/SearchTextFieldTest.java]: To keep the tests managable, we do not test trivialities.
Especially here you more or less testing javafx and java, not our logic. Test can be removed imho.

Comment (jadegold55) [reply jabgui/src/test/java/org/jabref/gui/search/SearchTextFieldTest.java]: Ok sounds good and thanks for the review/ feedback. Will update it real quick.

Comment (jadegold55) [reply jabgui/src/test/java/org/jabref/gui/search/SearchTextFieldTest.java]: Done!

**Comment by calixtus** [comment]
Changelog entry should be added. Even though the change is minimal, it is user-facing and should be mentioned.
