### PR TITLE
[WIP] Fix for issue 2831

### LINKED ISSUE #2831: Run "Abbreviate journal names" in parallel
JabRef 3.8.2
windows 10 10.0 amd64 
Java 1.8.0_131

As far as I can tell, the "Abbreviate journal names" function in JabRef is currently run serially. While this is fine for smaller databases, it can pose a serious performance problem when dealing with large (>10,000 entries) databases. I propose to run this function in parallel - this should speed up things quite a lot, I guess.

### PR DESCRIPTION
**Pull request by Brainsucker92**
Fixes #2831 

Added new method _executeAndReturn_ to the JabRefExecutorService that allows to run callables that return a value when the computation is completed. Using this method the abbreviations in _AbbreviateAction.java_ should run parallel now.

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 1]
```diff
@@ -53,10 +57,18 @@ public void run() {
...
+            futures.add(result);
+        }
+        
+        for (Future<Boolean> future : futures) {
+            try {
+                if(future.get()) {
+                    count++;
+                }
+            } catch (InterruptedException | ExecutionException e) {
+                // Do nothing.
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Just please add a Logger debug statement here, otherwise underlying eceptions may get swalloed

Comment (Brainsucker92) [reply src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Alright, already done.

**Comment by koppor** [comment]
@Brainsucker92 I added `Fixes #2831` to your PR description. Otherwise, GitHub does not link the issue properly. --> GitHub has no linking functionality in the header

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 2]
```diff
@@ -87,6 +87,20 @@ public boolean executeAndWait(Callable command) {
         }
     }
 
+    /**
+     * This method allows to execute a callable task that provides a return value after the calculation is done.
+     * @param command The task to execute.
+     * @return A Future object that provides the returning value.
+     */
+    public <T> Future<T> executeAndReturn(Callable<T> command) {
+        if (command == null) {
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: Why this? Can't we just put `Objects.requireNonNull(command)`? I think, Item 49 of [Effective Java, 3rd edition](https://www.amazon.de/Effective-Java-Third-Joshua-Bloch/dp/0134685997?tag=jabref-21).

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 3]
```diff
@@ -87,6 +87,20 @@ public boolean executeAndWait(Callable command) {
         }
     }
 
+    /**
+     * This method allows to execute a callable task that provides a return value after the calculation is done.
+     * @param command The task to execute.
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: Empty line before parameter description

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 4]
```diff
@@ -87,6 +87,20 @@ public boolean executeAndWait(Callable command) {
...
+     * @return A Future object that provides the returning value.
+     */
+    public <T> Future<T> executeAndReturn(Callable<T> command) {
+        if (command == null) {
+            LOGGER.debug("Received null as command for execution");
+            return null;
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: `null` should never be used. Use Optionals. (See http://java.by-comparison.com/ and effective java).

In the concrete case, use `Objects.requireNonNull()`.

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 5]
```diff
@@ -54,9 +62,17 @@ public void run() {
...
             };
 
-            boolean result = JabRefExecutorService.INSTANCE.executeAndWait(callable);
-            if (result) {
-                count++;
+            Future<Boolean> result = JabRefExecutorService.INSTANCE.executeAndReturn(callable);
+            futures.add(result);
+        }
+
+        for (Future<Boolean> future : futures) {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Why not `ExecutorService.invokeAll()`? See https://stackoverflow.com/a/1250668/873282.

File: src/main/java/org/jabref/JabRefExecutorService.java (hunk 2 above)
Comment (Brainsucker92) [reply src/main/java/org/jabref/JabRefExecutorService.java]: I did the null check this way because every other method in the class checked for null exactly the same way. In this case we should consider changing all other methods to `Objects.requireNonNull(...)`

Comment (koppor) [reply src/main/java/org/jabref/JabRefExecutorService.java]: Yeah, this is the preferred way. Hope, nothing breaks if this is done at other places. 😇

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 6]
```diff
@@ -89,17 +82,26 @@ public boolean executeAndWait(Callable command) {
...
-            return null;
-        }
+        Objects.requireNonNull(command);
 
         return executorService.submit(command);
     }
+    
+    public void executeAll(Collection<? extends Callable<?>> tasks) {
+        Objects.requireNonNull(tasks);
+
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: Please remove empty line. - only one empty line at most 😇

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 7]
```diff
@@ -89,17 +82,26 @@ public boolean executeAndWait(Callable command) {
...
     }
+    
+    public void executeAll(Collection<? extends Callable<?>> tasks) {
+        Objects.requireNonNull(tasks);
+        
+        
+        try {
+            executorService.invokeAll(tasks);
+        } catch (InterruptedException e) {
+            LOGGER.debug("Invokation has been interrupted during execution.");
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: I would do it at as `info` as it might be interesting for the user.

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java (hunk 5 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Use `executeAll` from above?

**Comment by Brainsucker92** [comment]
Alright, I made a couple of changes. Hopefully everything seems to be better and runs nice and smoothly.

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 8]
```diff
@@ -87,6 +78,29 @@ public boolean executeAndWait(Callable command) {
...
+    
+    public <T> List<Future<T>> executeAll(Collection<Callable<T>> tasks) {
+        Objects.requireNonNull(tasks);
+        List<Future<T>> futures = null; 
+        try {
+            futures =  executorService.invokeAll(tasks);
+        } catch (InterruptedException e) {
+            LOGGER.info("Invokation has been interrupted during execution.");
+        }
+        Objects.requireNonNull(futures);
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: This is asserted by the API. I think, this line can be removed.

Typically `Objects.requireNonNull(...)` is only used at the beginning of a method to check parameters. Not in the middle.

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 9]
```diff
@@ -87,6 +78,29 @@ public boolean executeAndWait(Callable command) {
...
+     * 
+     * @param command The task to execute.
+     * @return A Future object that provides the returning value.
+     */
+    public <T> Future<T> executeAndReturn(Callable<T> command) {
+        Objects.requireNonNull(command);
+        return executorService.submit(command);
+    }
+    
+    public <T> List<Future<T>> executeAll(Collection<Callable<T>> tasks) {
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: According to the discussion at https://stackoverflow.com/a/1250668/873282, all futures should be available. Thus, no need to return something.

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 10]
```diff
@@ -53,10 +63,20 @@ public void run() {
...
+        }
 
-            boolean result = JabRefExecutorService.INSTANCE.executeAndWait(callable);
-            if (result) {
-                count++;
+        // Execute the callables and wait for the results.
+        List<Future<Boolean>> futures = JabRefExecutorService.INSTANCE.executeAll(tasks);
+
+        // Evaluate the results of the callables.
+        for (Future<Boolean> future : futures) {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: According to https://stackoverflow.com/a/1250668/873282, this is not required. See also above.

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 11]
```diff
@@ -87,6 +78,29 @@ public boolean executeAndWait(Callable command) {
...
+        Objects.requireNonNull(tasks);
+        List<Future<T>> futures = null; 
+        try {
+            futures =  executorService.invokeAll(tasks);
+        } catch (InterruptedException e) {
+            LOGGER.info("Invokation has been interrupted during execution.");
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: An empty list should be returned.

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java (hunk 10 above)
Comment (koppor) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: `futures.stream().map(f -> f.get()).countif(...` --> Please try to use Java8's streaming API - if possible. 😇

File: src/main/java/org/jabref/JabRefExecutorService.java (hunk 11 above)
Comment (koppor) [reply src/main/java/org/jabref/JabRefExecutorService.java]: I hope, this goes well 😇

File: src/main/java/org/jabref/JabRefExecutorService.java (hunk 8 above)
Comment (Brainsucker92) [reply src/main/java/org/jabref/JabRefExecutorService.java]: I just wanted to avoid returning null. I'll remove it.

Comment (koppor) [reply src/main/java/org/jabref/JabRefExecutorService.java]: Yeah, totally understandable. I think, that's why `@NonNull` annotations are there for... --> https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm We are currently not using them in JabRef.

Otherwise, the whole could had to be cluttered with `Objects.requireNonNull(...)` statements, because `null` should be avoided in any case. 🔢

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java (hunk 10 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: I checked stackoverflow. It should read `count = futures.stream().filter(f -> f.get()).count();` Shouldn't it?

Comment (Brainsucker92) [reply src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Isn't using a filter handier? Like this:
`futures.stream().filter(...).count()`?

Comment (Brainsucker92) [reply src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Indeed. Using a filter seems to be the better option to me. Only downside of this is, we need to catch  the Exceptions within the filter... but ok, I'll do it that way.

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 12]
```diff
@@ -87,6 +79,28 @@ public boolean executeAndWait(Callable command) {
...
+        Objects.requireNonNull(command);
+        return executorService.submit(command);
+    }
+    
+    public <T> List<Future<T>> executeAll(Collection<Callable<T>> tasks) {
+        Objects.requireNonNull(tasks);
+        List<Future<T>> futures = new ArrayList<>(); 
+        try {
+            futures =  executorService.invokeAll(tasks);
+        } catch (InterruptedException e) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/JabRefExecutorService.java]: Please use `logger.error` and pass the exception as an argument. Btw, Invokation is German not English ;-)

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 13]
```diff
@@ -53,12 +62,24 @@ public void run() {
...
+        // Execute the callables and wait for the results.
+        List<Future<Boolean>> futures = JabRefExecutorService.INSTANCE.executeAll(tasks);
+
+        // Evaluate the results of the callables.
+        long count = futures.stream().filter(f -> {
+            boolean result;
+            try {
+                result = f.get();
+            } catch (InterruptedException | ExecutionException e) {
+                LOGGER.debug("Invokation has been interrupted during execution.");
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: again, pls `LOGGER.error`

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 14]
```diff
@@ -53,12 +62,24 @@ public void run() {
...
-            if (result) {
-                count++;
+        // Execute the callables and wait for the results.
+        List<Future<Boolean>> futures = JabRefExecutorService.INSTANCE.executeAll(tasks);
+
+        // Evaluate the results of the callables.
+        long count = futures.stream().filter(f -> {
+            boolean result;
+            try {
+                result = f.get();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Instead of the try, catch, finally construct it is actually easier to follow the rule "return as soon as possible" and write something like
````java
try {
   return f.get();
} catch (...) {
   Log;
   return false;
}
````

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 15]
```diff
@@ -53,12 +62,24 @@ public void run() {
...
+        }
 
-            boolean result = JabRefExecutorService.INSTANCE.executeAndWait(callable);
-            if (result) {
-                count++;
+        // Execute the callables and wait for the results.
+        List<Future<Boolean>> futures = JabRefExecutorService.INSTANCE.executeAll(tasks);
+
+        // Evaluate the results of the callables.
+        long count = futures.stream().filter(f -> {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: please don't use abbreviations, `future` is better than `f`.

File: src/main/java/org/jabref/JabRefExecutorService.java (hunk 12 above)
Comment (Brainsucker92) [reply src/main/java/org/jabref/JabRefExecutorService.java]: Unfortunately, `Logger` does not provide any `PrintStream` to print the stacktrace as suggested here: https://stackoverflow.com/a/1149712 by using `e.printStackTrace(anyPrintStreamHere)`. So what's there preferred way to print the StackTrace to the LOGGER.error method?

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java (hunk 14 above)
Comment (Brainsucker92) [reply src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: In this case I was looking at this anwser: https://stackoverflow.com/a/17405806 which prefers the way to return at the end of the method. I will change the code as you suggested.

File: src/main/java/org/jabref/JabRefExecutorService.java [hunk 16]
```diff
@@ -87,6 +79,28 @@ public boolean executeAndWait(Callable command) {
...
+        return executorService.submit(command);
+    }
+
+    public <T> List<Future<T>> executeAll(Collection<Callable<T>> tasks) {
+        Objects.requireNonNull(tasks);
+        List<Future<T>> futures = new ArrayList<>();
+        try {
+            futures = executorService.invokeAll(tasks);
+        } catch (InterruptedException exception) {
+            LOGGER.error("Unble to execute tasks", exception);
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefExecutorService.java]: Just to be sure: Do not miss the `return Collections.emptyList();` here.

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 17]
```diff
@@ -53,12 +62,21 @@ public void run() {
...
-            boolean result = JabRefExecutorService.INSTANCE.executeAndWait(callable);
-            if (result) {
-                count++;
+        // Evaluate the results of the callables.
+        long count = futures.stream().filter(future -> {
+            try {
+                return future.get();
+            } catch (InterruptedException | ExecutionException exception) {
+                LOGGER.error("Unable to retrieve value.", exception);
+                return false;
```
Comment (koppor) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: I would not break the loop here, just continue with the next future. If the `return false;` makes sense here, please add a comment why `false` is returned.

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: the return is for the lambda so everything is fine.

File: src/main/java/org/jabref/gui/journals/AbbreviateAction.java [hunk 18]
```diff
@@ -22,6 +28,8 @@
     private String message = "";
     private final boolean iso;
 
+    private static final Logger LOGGER = LoggerFactory.getLogger(AbbreviateAction.class);
```
Comment (koppor) [inline src/main/java/org/jabref/gui/journals/AbbreviateAction.java]: Travis fails becoaseu of checkstyle:

```
:checkstyleMain[ant:checkstyle] [ERROR] /home/travis/build/JabRef/jabref/src/main/java/org/jabref/gui/journals/AbbreviateAction.java:18: 'org.slf4j.Logger' should be separated from previous imports. [ImportOrder]
[ant:checkstyle] [ERROR] /home/travis/build/JabRef/jabref/src/main/java/org/jabref/gui/journals/AbbreviateAction.java:31:5: Static variable definition in wrong order. [DeclarationOrder]
```

Could you please fix that, too? -- Just move it before the other variable declarations.

**Comment by Brainsucker92** [comment]
Actually I thinking if it makes sense to rename the `executeAndReturn` method in the ExecutorService simply to `execute` which overloads the execute method and allows to execute tasks with returning values and without.

**Comment by koppor** [comment]
@Brainsucker92 If I understand correctly, you are searching for a feature not available in Java: https://stackoverflow.com/a/2439798/873282

**Comment by Brainsucker92** [comment]
It will work perfectly, bacause both parameter lists of the functions are differently. This allows to create two methods with different returning values. Just tested it in my IDE and everything is just fine.

**Comment by koppor** [comment]
Sorry, one more thing:

- [ ] Change in CHANGELOG.md described

And, is that possible without huge effort? 😇 

- [ ] Manually tested changed features in running JabRef

**Comment by Brainsucker92** [comment]
For testing the abbreviation I have to have a fairly large sized BibTeX database, which I currently don't have, right? So where to get any random database in order to test these changes?

**Comment by koppor** [comment]
@Brainsucker92 I have to confess that we don't have a huge bibtex file. Could write a generator? 😇 This would help us so much for testing huge databases.

**Comment by Siedlerchr** [comment]
@koppor  We have some script in /scripts/bib-file-generator.rb
Generates 100,000 times the same entry

**Comment by tobiasdiez** [comment]
I think we tortured @Brainsucker92 long enough 😈

**Comment by koppor** [comment]
@brainsucker92 Thank you for the PR, the quick reactions and the patience! We would love to see more PRs from you! Especially your Python skills are interesteing. :innocent: our syncLang.py script needs updates cause of our migration to crowd in...

**Comment by Brainsucker92** [comment]
@koppor Thanks a lot for your appreciation! Of course I'd like to continue contributing to this project in future. Unfortunately, my skills in python are pretty rusty because last time I actively coded in python was back then with py2.5. Thus I don't have that much experience with modern Python3.X programming. But if there are some minor changes to make I'll give it a shot to do so. I had a quck look at syncLang.py and code quality seems to be pretty good in the script.

**Comment by Siedlerchr** [comment]
The sync lang python script is still 2.x because it's executed with jython which does not work with python 3.x (we learned that the hard way... 😯)

**Comment by koppor** [comment]
@Brainsucker92 One has to think into the aims what the script does. I think, it currently does not handle escapes the way as [Crowdin](http://crowdin.com/) does. Maybe, you can run the script and check what it modifies and which errors it reports. See https://github.com/JabRef/jabref/issues/3573#issuecomment-357653588 for a discussion. You can follow up there in case you want to dive into this thing.

**Comment by koppor** [comment]
@Brainsucker92 Could you write a short personal email so that I have your contact data?

**Comment by Brainsucker92** [comment]
@koppor sure, just sent a mail to kopp.dev@gmail.com
