### PR TITLE
Strip invalid prolog when loading CitationStyles

### LINKED ISSUE #3389: [Fatal Error] :1:1: Content is not allowed in prolog.
In version 
```
JabRef 4.1-dev--snapshot--2017-10-31--master--1ebdea452
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```
I get on stderr:
```
[Fatal Error] :1:1: Content is not allowed in prolog.
```

Reproduce:
when simply opening the window by clicking on the menu `Options/Preferences`

```
12:20:10.329 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Create_blank_entry_linking_the_PDF" for locale en
12:20:10.329 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Create_entry_based_on_XMP-metadata" for locale en
12:20:10.329 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Create_entry_based_on_content" for locale en
12:20:10.329 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Only_attach_PDF" for locale en
[Fatal Error] :1:1: Content is not allowed in prolog.
12:20:11.300 [SwingWorker-pool-4-thread-7] ERROR org.jabref.logic.citationstyle.CitationStyle - Error while parsing source
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257) ~[?:1.8.0_152]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_152]
	at org.jabref.logic.citationstyle.CitationStyle.createCitationStyleFromSource(CitationStyle.java:66) [JabRef--master--latest.jar:?]
	at org.jabref.logic.citationstyle.CitationStyle.createCitationStyleFromFile(CitationStyle.java:98) [JabRef--master--latest.jar:?]
	at org.jabref.logic.citationstyle.CitationStyle.discoverCitationStyles(CitationStyle.java:126) [JabRef--master--latest.jar:?]
	at org.jabref.gui.preftabs.PreviewPrefsTab$1.doInBackground(PreviewPrefsTab.java:201) [JabRef--master--latest.jar:?]
	at org.jabref.gui.preftabs.PreviewPrefsTab$1.doInBackground(PreviewPrefsTab.java:198) [JabRef--master--latest.jar:?]
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at javax.swing.SwingWorker.run(SwingWorker.java:334) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[Fatal Error] :1:1: Content is not allowed in prolog.
12:20:11.310 [SwingWorker-pool-4-thread-7] ERROR org.jabref.logic.citationstyle.CitationStyle - Error while parsing source
org.xml.sax.SAXParseException: Content is not allowed in prolog.
```

### PR DESCRIPTION
**Pull request by lenhard**
Fixes #3389 by skipping invalid parts of the prolog of citation styles.

- [X] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [X] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/main/java/org/jabref/logic/citationstyle/CitationStyle.java [hunk 1]
```diff
@@ -71,7 +71,9 @@ private static CitationStyle createCitationStyleFromSource(final String source,
                 String title = ((CharacterData) titleNode.item(0).getFirstChild()).getData();
 
                 return new CitationStyle(filename, title, source);
-            } catch (ParserConfigurationException | SAXException | IOException e) {
+            } catch (SAXException ignore) {
+                // is triggered when a use has not configured CitationStyles -> ignore
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/citationstyle/CitationStyle.java]: Is there no easy way to prevent the exception from being triggered when the user actually does not use citation styles (I suspect these null checks in the beginning should actually serve this job, although they fail obviously). Reason: I think these SAX errors also appears if a user uses a citation style but the parsing fails for some reason. In this case the logged error message is actually helpful.

If there is no easy way to prevent the exception, then I'm fine with merging this PR.

Comment (lenhard) [reply src/main/java/org/jabref/logic/citationstyle/CitationStyle.java]: You are right of course, I should rather track down the origin. The problem lies in the citationstyles. The first line of some of the styles is broken. For example, the style `university-of-york-vancouver.csl` looks like this `?<?xml version="1.0" encoding="utf-8"?>` and is invalid because it starts with a question mark. 

That should be fixed at the end of the citation styles. For now, I have pushed a fix on our side that checks if the first character of the citation style is also the expected `<` and avoids parsing the style if it is not.
