### PR TITLE
Fix menu bar gone on macOS

### LINKED ISSUE #10966: Menu bar at wrong position on Mac OS since commit bec55f8
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

macOS 14.3

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Since commit [bec55f8](https://github.com/JabRef/jabref/commit/bec55f8c42430221838fbd18a91fe652e2408dda) the menu bar is included into the main window instead of the Mac OS menu bar (as before this commit).

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #10966

was introduced in bec55f8c42430221838fbd18a91fe652e2408dda

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/preferences/JabRefPreferences.java [hunk 1]
```diff
@@ -2204,7 +2202,7 @@ public FilePreferences getFilePreferences() {
                 // We choose the data directory, because a ".bak" file should survive cache cleanups
                 getPath(BACKUP_DIRECTORY, OS.getNativeDesktop().getBackupDirectory()),
                 getBoolean(CONFIRM_LINKED_FILE_DELETE),
-                getBoolean(TRASH_INSTEAD_OF_DELETE));
+                getBoolean(TRASH_INSTEAD_OF_DELETE, OS.getNativeDesktop().moveToTrashSupported()));
```
Comment (calixtus) [inline src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: This is wrong. Can this be enabled in the preferences even though it is not supported?

Comment (calixtus) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: Was already wrong before the chris change. 😉 isSupported is logic, not a preferences option.

Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: grafik

Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: https://github.com/JabRef/jabref/blob/cfabd9fc6e0373e7a66b1702091cab1f4ce1a879/src/main/java/org/jabref/gui/preferences/linkedfiles/LinkedFilesTab.java#L67

Comment (koppor) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: Nevertheless, the preference should not be true if it is not supported system-wide. I thought, in https://github.com/JabRef/jabref/pull/10591 I implemented it as: "default = supported by OS" and then "disabled/enabled = supported by OS". 

Maybe an additional line:

```java
if (!OS.getNativeDesktop().moveToTrashSupported()) {
  moveToTrash.setValue(false)
}
```

to ensure that it is both disabled and false if trash is not supported.

**Comment by koppor** [comment]
Failing tests are "only" architecture tests

```
org.jabref.architecture.MainArchitectureTest

  Test nativeDesktopIsRestricted FAILED

  java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'no classes that do not have simple name 'JabRefDesktop' and do not have simple name 'Launcher' and do not have simple name 'DefaultDesktop' and do not have simple name 'OS' and do not have simple name 'Linux' and do not have simple name 'OSX' and do not have simple name 'Windows' and do not have simple name 'JabRefPreferences' and have name not matching '.*Test' should depend on classes that have simple name 'NativeDesktop'' was violated (5 times):
  Constructor <org.jabref.gui.preferences.externalfiletypes.EditExternalFileTypeEntryDialog.<init>(org.jabref.gui.preferences.externalfiletypes.ExternalFileTypeItemViewModel, java.lang.String, javafx.collections.ObservableList)> calls method <org.jabref.gui.desktop.os.NativeDesktop.getApplicationDirectory()> in (EditExternalFileTypeEntryDialog.java:37)
  Method <org.jabref.gui.linkedfile.DeleteFileAction.deleteFileHelper(org.jabref.model.database.BibDatabaseContext, org.jabref.model.entry.LinkedFile)> calls method <org.jabref.gui.desktop.os.NativeDesktop.moveToTrash(java.nio.file.Path)> in (DeleteFileAction.java:194)
  Method <org.jabref.gui.openoffice.DetectOpenOfficeInstallation.selectInstallationPath()> calls method <org.jabref.gui.desktop.os.NativeDesktop.getApplicationDirectory()> in (DetectOpenOfficeInstallation.java:37)
  Method <org.jabref.gui.preferences.linkedfiles.LinkedFilesTab.initialize()> calls method <org.jabref.gui.desktop.os.NativeDesktop.moveToTrashSupported()> in (LinkedFilesTab.java:67)
  Method <org.jabref.model.database.BibDatabaseContext.getFulltextIndexPath()> calls method <org.jabref.gui.desktop.os.NativeDesktop.getFulltextIndexBaseDirectory()> in (BibDatabaseContext.java:247)
```

**Comment by koppor** [comment]
Ah, I think `org.jabref.gui.desktop.JabRefDesktop#moveToTrashSupported` should be called. Not `OS` directly. We do have `JabRefDesktop` as bridge.

File: src/main/java/org/jabref/preferences/JabRefPreferences.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: It was in defaults. but this broke the system menu bar in macOS. This is why i removed it in defaults and just added it as fallback value

File: src/main/java/org/jabref/gui/desktop/JabRefDesktop.java [hunk 2]
```diff
@@ -315,26 +313,5 @@ public static void openBrowserShowPopup(String url, DialogService dialogService,
...
-    }
-
-    public static Path getApplicationDirectory() {
-        return NATIVE_DESKTOP.getApplicationDirectory();
-    }
-
-    public static Path getFulltextIndexBaseDirectory() {
-        return NATIVE_DESKTOP.getFulltextIndexBaseDirectory();
-    }
 }
```
Comment (koppor) [inline src/main/java/org/jabref/gui/desktop/JabRefDesktop.java:316]: Please keep the methods here. `OS.getNativeDesktop()` may only be used by certain classes. See `org.jabref.architecture.MainArchitectureTest#nativeDesktopIsRestricted`.

File: src/main/java/org/jabref/preferences/JabRefPreferences.java [hunk 3]
```diff
@@ -710,7 +709,6 @@ private JabRefPreferences() {
         defaults.put(WARN_BEFORE_OVERWRITING_KEY, Boolean.TRUE);
         defaults.put(CONFIRM_DELETE, Boolean.TRUE);
         defaults.put(CONFIRM_LINKED_FILE_DELETE, Boolean.TRUE);
-        defaults.put(TRASH_INSTEAD_OF_DELETE, JabRefDesktop.moveToTrashSupported());
```
Comment (koppor) [inline src/main/java/org/jabref/preferences/JabRefPreferences.java:713]: Shouldn't there a `true` be put?

OK, what if the OS does not support move to trash?

This were my thoughts. Therefore, I made the default rely on the current OS's capabilities.

File: src/main/java/org/jabref/preferences/JabRefPreferences.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: Which part exactly broke the menu bar? The issue did not show any exception, so I cannot understand the root cause.

**Review by koppor — CHANGES_REQUESTED** [review]
I don't know, how to solve this.

My thoughts:

1. Users should not be required to set any preference on first use.
2. JabRef should not delete data if it can do other way
3. Trashing files instead of deleting files is a way to prevent data loss.
4. Some operating systems do not support trashing
5. Thus, the default for trashing is the OS support for trashing.

Point 5 seemed to cause troubles with OSX. I don't know which troubles. @calixtus says, OS-depended defaults are not OK. I am curious about our ideas how to resolve points 1 to 4 above.

File: src/main/java/org/jabref/preferences/JabRefPreferences.java (hunk 3 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:713]: Exactly this line broke the menu bar!

File: src/main/java/org/jabref/gui/desktop/JabRefDesktop.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java:316]: For me this is a code smell because we essentially have duplicate methods now. Before the mentioned PR we didn't have this architecture check

File: src/main/java/org/jabref/preferences/JabRefPreferences.java (hunk 1 above)
Comment (calixtus) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2205]: My suggestion would be just to make true the default, but it's greyed out in the preferences and where moveToTrash is used, there is an additional check, if this is supported. Check could go to JabRefDesktop#moveToTrash or sthg and then delete instead.

**Review by koppor — APPROVED** [review]
