### PR TITLE
Fix for issue 4682 : Restructuring the side pane structure having additional functionality and merging the remove group menus

### LINKED ISSUE #4682: Groups context menu: Structure remove groups and subgroups
groupmanual

|Description of Issue|Possible Solution|  Warnings |
|:-----------------------------------------:|:-------------------------------------------------:|:---------------:|
| The button for adding groups is often too remote from the list of existing groups and too inconspicuous|Enlarge the button and place it directly below the list of groups|-|
| The right click options for groups are too complicated;<br/>the menu contains functions, that are misplaced there|Add hierarchy to the _Remove group_ items; <br/>Remove items for adding/removing entries|-|

### PR DESCRIPTION
**Pull request by apurvachuri**
Rearrange side pane structure having add button moved to the bottom of the side pane and merging the remove group menus.

Fixes #4682 

Following are the changes that we implemented:

1. Add group functionality
   - Remove '+' button beside filter group tab
   - Add group button at the bottom of the side pane
   - Button dim after adding 10 groups.
   
  Screen Shot 2021-05-08 at 3 08 06 pm
  
  
Screen Shot 2021-05-08 at 3 15 10 pm

2.  Fix the header title in the Add Group/Subgroup Dialog box
Screen Shot 2021-05-08 at 4 03 12 pm

3. Merge 'Remove group' having two options, with or without subgroups
Screen Shot 2021-05-08 at 4 07 34 pm

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/groups/GroupDialogView.java [hunk 1]
```diff
@@ -67,15 +67,19 @@
...
+    public GroupDialogView(DialogService dialogService, BibDatabaseContext currentDatabase, PreferencesService preferencesService, AbstractGroup editedGroup, boolean isGroup) {
+        viewModel = new GroupDialogViewModel(dialogService, currentDatabase, preferencesService, editedGroup, isGroup);
 
         ViewLoader.view(this)
                   .load()
                   .setAsDialogPane(this);
 
         if (editedGroup == null) {
-            this.setTitle(Localization.lang("Add subgroup"));
+            if (isGroup == true) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/groups/GroupDialogView.java:78]:
```suggestion
            if (isGroup) {
```
No need to compare a boolean against "true"

File: src/main/java/org/jabref/gui/groups/GroupDialogView.java [hunk 2]
```diff
@@ -67,15 +67,19 @@
...
+                this.setTitle(Localization.lang("Add group")); // header title
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/groups/GroupDialogView.java:79]: comment can be removed, it should be clear that title is the "header"

File: src/main/java/org/jabref/gui/groups/GroupTree.fxml [hunk 3]
```diff
@@ -39,4 +29,15 @@
             </columnResizePolicy>
         </TreeTableView>
     </center>
+    <bottom>
+        <HBox fx:id="groupBar" alignment="CENTER" spacing="8">
+            <Button fx:id="addNewGroup" onAction="#addNewGroup" styleClass="add-group-button"
+                    text="%Add group" maxWidth="1.7976931348623157E308" HBox.hgrow="ALWAYS">
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/groups/GroupTree.fxml:35]: I think you can remove the maxWidth property

File: src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java [hunk 4]
```diff
@@ -147,13 +147,15 @@ private void onActiveDatabaseChanged(Optional<BibDatabaseContext> newDatabase) {
     /**
      * Opens "New Group Dialog" and add the resulting group to the specified group
      */
-    public void addNewSubgroup(GroupNodeViewModel parent) {
+
+    public void addNewSubgroup(GroupNodeViewModel parent, boolean isGroup) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java:151]: Code style wise you should avoid boolean "flags", they can get confusing. It's better to introduce an enum with the two possible options. That makes it easier to recognize the purpose of the parameter.

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Overall looks already good!
From my side only a few small remarks/suggestions regarding the code style

File: src/main/java/org/jabref/gui/groups/GroupTree.fxml (hunk 3 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/groups/GroupTree.fxml]: You can also assign infinity in the fxml directly maxWidth="Infinity

File: src/main/java/org/jabref/gui/groups/GroupTree.css [hunk 5]
```diff
@@ -116,3 +116,16 @@
...
     -fx-font-size: 2em;
 }
+
+#groupBar .glyph-icon {
+    -fx-font-size: 2em;
+}
+
+.add-group-button {
+    -fx-max-width: Infinity;
+}
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTree.css:126]: This can be done directly in the fxml file.

File: src/main/java/org/jabref/gui/groups/GroupTree.fxml [hunk 6]
```diff
@@ -39,4 +29,15 @@
             </columnResizePolicy>
         </TreeTableView>
     </center>
+    <bottom>
+        <HBox fx:id="groupBar" alignment="CENTER" spacing="8">
+            <Button fx:id="addNewGroup" onAction="#addNewGroup" styleClass="add-group-button"
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTree.fxml:34]:
```suggestion
            <Button fx:id="addNewGroup" onAction="#addNewGroup" maxWidth="Infinity"
```
? (or something close to this)

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java [hunk 7]
```diff
@@ -107,12 +107,14 @@
...
     private final AbstractGroup editedGroup;
+    private final boolean isGroup;
 
-    public GroupDialogViewModel(DialogService dialogService, BibDatabaseContext currentDatabase, PreferencesService preferencesService, AbstractGroup editedGroup) {
+    public GroupDialogViewModel(DialogService dialogService, BibDatabaseContext currentDatabase, PreferencesService preferencesService, AbstractGroup editedGroup, boolean isGroup) {
         this.dialogService = dialogService;
         this.preferencesService = preferencesService;
         this.currentDatabase = currentDatabase;
         this.editedGroup = editedGroup;
+        this.isGroup = isGroup;
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:117]: Is this really necessary? Can't be determined if this group is a subgroup in checking if the editedGroup has a parent other than the root node?

Comment (damassh) [reply src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:117]: We added another variable to identify if it is a group or a subgroup. editGroup doesn't classify whether each one of them.

Comment (damassh) [reply src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:117]: we are currently converting the boolean to enum as per suggested by @Siedlerchr

File: src/main/java/org/jabref/gui/groups/GroupTreeView.java [hunk 8]
```diff
@@ -397,6 +415,21 @@ private void setupClearButtonField(CustomTextField customTextField) {
...
+                        " -fx-padding: 0.5em; -fx-text-fill: -jr-white;");
+            } else {
+                addNewGroup.setStyle("-fx-border-width: 0px; -fx-background-color: -jr-icon-background-active;" +
+                        " -fx-padding: 0.5em; -fx-text-fill: -jr-black;");
+            }
+        } else {
+            addNewGroup.setStyle("-fx-border-width: 0px; -fx-background-color: -jr-theme;" +
+                    " -fx-padding: 0.5em; -fx-text-fill: -jr-white;");
+        }
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeView.java:431]: Instead of hardcoding the css in the java file, please make this a pseudoclass in css, which should be very easy to implement. See `BindingsHelper::includePseudoClassWhen` !

File: src/main/resources/l10n/JabRef_en.properties [hunk 9]
```diff
@@ -1782,7 +1782,7 @@ No\ full\ text\ document\ found\ for\ entry\ %0.=No full text document found for
 Delete\ Entry=Delete Entry
 Next\ library=Next library
 Previous\ library=Previous library
-add\ group=add group
+add\ group=Add group
```
Comment (calixtus) [inline src/main/resources/l10n/JabRef_en.properties:1785]: Translation string must be consistent with english translation.
```suggestion
Add\ group=Add group
```

**Review by calixtus — CHANGES_REQUESTED** [review]
Some small remarks

File: src/main/java/org/jabref/gui/groups/GroupDialogHeader.java [hunk 10]
```diff
@@ -0,0 +1,5 @@
+package org.jabref.gui.groups;
+
+public enum GroupDialogHeader {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupDialogHeader.java:3]: Maybe its just a question of personal preference, but I would suggest to inline this simple enum in GroupDialogView instead of a new file, since the scope of this is extremely limited. Do we have a policy about this @JabRef/developers ?

Comment (cheese7858) [reply src/main/java/org/jabref/gui/groups/GroupDialogHeader.java:3]: Hi @calixtus, since this enum is used in multiple files inside the package, thus the new file is crated. And from some reading i did, it's best practise for enum to be declared in a file of its own if it's public, but again some clarifications from the devs would be much appreciated.

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/groups/GroupDialogHeader.java:3]: I think both work. Since it is only used in connection with the group edit dialog, one could argue that this is the right place. But a new file is also ok in my opinion.

**Comment by damassh** [comment]
> Please look at the failing unit + checkstyle /reviewdog and also change the PR title to a more meaningful name

@Siedlerchr , I am sorry I'm new in checking the unit test. Is it possible if you can point me in the right direction on how to check it? I've clicked the details and directed me to a [https://github.com/JabRef/jabref/pull/7714/checks?check_run_id=2604593213](checker) but not sure how to investigate on the code itself on how to debug it and fix it.

File: src/main/java/org/jabref/gui/groups/GroupTree.fxml (hunk 3 above)
Comment (damassh) [reply src/main/java/org/jabref/gui/groups/GroupTree.fxml]: done thank you.

File: src/main/java/org/jabref/gui/groups/GroupTreeView.java (hunk 8 above)
Comment (damassh) [reply src/main/java/org/jabref/gui/groups/GroupTreeView.java:431]: Hi @calixtus , i've checked this `BindingsHelper::includePseudoClassWhen` needs a parameter of `node` and the css changes should be applied to the nodes whenever a condition is applied. however, in my change, what I'm changing is the color of `Add Group` button whenever the user added 10 groups (doesn't include the count of subgroups) and not the nodes. Any advise is greatly appreciated.

File: src/main/resources/l10n/JabRef_en.properties (hunk 9 above)
Comment (damassh) [reply src/main/resources/l10n/JabRef_en.properties]: fixed

**Comment by calixtus** [comment]
> 
> 
> > Please look at the failing unit + checkstyle /reviewdog and also change the PR title to a more meaningful name
> 
> @Siedlerchr , I am sorry I'm new in checking the unit test. Is it possible if you can point me in the right direction on how to check it? I've clicked the details and directed me to a [https://github.com/JabRef/jabref/pull/7714/checks?check_run_id=2604593213](checker) but not sure how to investigate on the code itself on how to debug it and fix it.

The provided link returns me a 404 😞

**Comment by damassh** [comment]
> > > Please look at the failing unit + checkstyle /reviewdog and also change the PR title to a more meaningful name
> > 
> > 
> > @Siedlerchr , I am sorry I'm new in checking the unit test. Is it possible if you can point me in the right direction on how to check it? I've clicked the details and directed me to a [https://github.com/JabRef/jabref/pull/7714/checks?check_run_id=2604593213](checker) but not sure how to investigate on the code itself on how to debug it and fix it.
> 
> The provided link returns me a 404 😞

This also gives us an error 404 and was about raise it as well. The provided link for `CUSTOM_EXPORTS_NAME_FORMATTER` doesn't exist. @Siedlerchr @tobiasdiez may you help to advise if this is expected? 
Screen Shot 2021-05-20 at 3 47 16 pm

File: CHANGELOG.md [hunk 11]
```diff
@@ -92,6 +95,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where the RFC fetcher is not compatible with the draft [7305](https://github.com/JabRef/jabref/issues/7305)
 
 ### Removed
+- We removed add group button beside the filter group tab. [#4682](https://github.com/JabRef/jabref/issues/4682)
```
[the remark this answers is not in the document]
Comment (apurvachuri) [reply CHANGELOG.md]: Added a l

[the remark this answers is not in the document]
Comment (apurvachuri) [reply CHANGELOG.md]: Added a blank line after the heading "#Removed"

**Comment by calixtus** [comment]
> This also gives us an error 404 and was about raise it as well. The provided link for `CUSTOM_EXPORTS_NAME_FORMATTER` doesn't exist. @Siedlerchr @tobiasdiez may you help to advise if this is expected?
> Screen Shot 2021-05-20 at 3 47 16 pm

The HelpFileTests are unrelated to your changes and are caused bay changes to our help system gitbook. They should be gone after merging the most recent main-branch into your branch an can be ignored.

File: CHANGELOG.md (hunk 11 above)
[the remark this answers is not in the document]
Comment (koppor) [reply CHANGELOG.md]: In this case, Visual Studio Code helps - with following plugin: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

I am not aware of any similar plugin for IntelliJ.

File: src/main/java/org/jabref/gui/groups/GroupTree.css [hunk 12]
```diff
@@ -102,8 +102,18 @@
...
+    -fx-background-color: -jr-theme;
+    -fx-padding: 0.5em;
+    -fx-text-fill: -jr-white;
+}
+
+#addNewGroup:inactive {
+    -fx-border-width: 0px;
+    -fx-background-color: -jr-icon-background-active;
+    -fx-padding: 0.5em;
+    -fx-text-fill:-jr-black;
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTree.css:116]: Hi, does this work with the black theme?

**Review by calixtus — COMMENTED** [review]
Sorry for the delay here, we all were a bit busy the last few weeks.
One quick question on this one, everything else looks good to me.

File: src/main/java/org/jabref/gui/groups/GroupTree.css (hunk 12 above)
Comment (damassh) [reply src/main/java/org/jabref/gui/groups/GroupTree.css:116]: @calixtus, sorry may you help to clarify your question? I am not sure what you mean by dark theme. I only used the colors available in `Base.css`.

Comment (calixtus) [reply src/main/java/org/jabref/gui/groups/GroupTree.css:116]: It would be great if you test your changes with the dark theme (preferences -> appearance -> dark theme)

Comment (damassh) [reply src/main/java/org/jabref/gui/groups/GroupTree.css:116]: @calixtus, per checking dark them works properly on the newly implemented change. Kindly see attached file.
Screen Shot 2021-06-08 at 7 28 36 pm

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
From my side lgtm

**Review by calixtus — APPROVED** [review]
Thank you very much for this contribution. I personally want to add that I really appreciate your Will to stay on this, fix issues with the PR and including our remarks, until the PR can be merged!

Merging now!
