### PR TITLE
Fix crash when scrolling through cited by in Citation relations

### LINKED ISSUE #12410: Memory overflow and operating system freeze due to the "cited by" entry tab from the "Citation relations" scrolling.
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 24.04

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. To reproduce, you can use the article with DOI: 10.1016/j.nimb.2024.165287
2. After adding an article to the library, you need to scroll the slider from "cited by" to the area of ​​articles corresponding to 2018 as in the figure below.
3. 

Image

4. **You need to be careful because you may need to crash due to memory overload.**

### PR DESCRIPTION
**Pull request by GuilhermeRibeiroPereira**
Uses Webview instead of Label and TextFlowLimited
when trying to display right to left text
(like persian or arabic) in BibEntryView. This resolves the issue caused by a javafx bug that causes an exception when rendering wrapped RTL text.
Fixes #12410

Closes #12410
I found out that this crash happens due to a bug in javafx described here: https://bugs.openjdk.org/browse/JDK-8340499?jql=labels%20%3D%20dcsad. There is an entry in the Citation Relation tab (at cited by) for the DOI referred by the user that has text in Persian, which is right to left (RTL), and when trying to display the text, which contains several lines and is wrapped, using labels for the title, authors and journal, the behavior described in the previous link occurs and the program and the OS crash and stop, due to a lot of exception dialogs appearing on the screen. This also happens for the summary, which is a textFlowLimited.

After testing, the bug seems to remain present in more recent versions of javafx, even though the issue has been closed. 

One solution I found was, in BibEntryView.java, to use a WebView that contains only the text for these elements, when they have RTL text, since it has good support for RTL text and does not cause crashes. The downside is that these entries that contain RTL text appear different from the others, which can be seen in the video. It shows that a crash no longer occurs when scrolling through the "cited by" of the article with DOI: 10.1016/j.nimb.2024.165287.

[https://www.youtube.com/watch?v=R-f_hdGdoQ8](url)

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [/] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java [hunk 1]
```diff
@@ -74,4 +77,33 @@ private static IconTheme.JabRefIcons getIcon(EntryType type) {
...
+                    Character.getDirectionality(c) == Character.DIRECTIONALITY_RIGHT_TO_LEFT_OVERRIDE) {
+                return true;
+            }
+        }
+        return false;
+    }
+
+    private static Node createTextNode(String text, String fieldName) {
+        if (isRTL(text)) {
+            WebView webView = new WebView();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java:95]: Creating a WebView is an expensive operation, you should use our WebViewStore to get a pre-allocated one

**Comment by Siedlerchr** [comment]
Please check the submodules changes https://devdocs.jabref.org/code-howtos/faq.html#submodules

**Comment by subhramit** [comment]
@koppor submodule diff check -> [false positive](https://github.com/JabRef/jabref/actions/runs/14216255328/job/39884627747?pr=12877)

File: src/main/resources/csl-styles
Comment (subhramit) [inline src/main/resources/csl-styles:1]: Please revert the submodule changes as per https://devdocs.jabref.org/code-howtos/faq.html#submodules

File: src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java (hunk 1 above)
Comment (HoussemNasri) [reply src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java:95]: Creating a webview for each entry in the citation relations tab to fix a crash in JabRef would crash your whole computer. This is not acceptable even with the WebViewStore. WebView is like a lightweight browser, it allocates a substantial amount of memory. We made it work for entry preview in the entry editor because entries are previewed one by one, so we can reuse the same webview instance for all entries and update the content, we can't do that here.

 We need another solution.

Comment (GuilhermeRibeiroPereira) [reply src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java:95]: Thank you for your feedback, I will try to find another solution then.

File: src/main/resources/csl-styles
Comment (GuilhermeRibeiroPereira) [reply src/main/resources/csl-styles:1]: Thank you for your feedback.
I have reverted the submodule changes. I am currently exploring different alternative solutions to fix the issue, without using WebViews, since they are expensive.

File: src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java (hunk 1 above)
Comment (GuilhermeRibeiroPereira) [reply src/main/java/org/jabref/gui/entryeditor/citationrelationtab/BibEntryView.java:95]: After exploring more, I've implemented a simpler approach that uses Labels and simple Text node for rtl text, but as single-line text with horizontal scrolling, avoiding the wrapping of the text, as you can see in this video:

[fix.webm](https://github.com/user-attachments/assets/64c66869-367a-45d1-9a76-ec191836e086)

Would this be an acceptable compromise? It is not an ideal solution, but it looks like the best solution would be for the JavaFX bug to be fixed. Like this, at least the OS and JabRef don't crash.

**Comment by subhramit** [comment]
@GuilhermeRibeiroPereira you can mark the PR ready for review when done

**Review by Siedlerchr — APPROVED** [review]
works! Thanks for the follow up!
