### PR TITLE
Fix for issue 9091 - store merge entries toolbar configuration

### LINKED ISSUE #9091: Merge entry interface: view options are not saved
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Other (please describe below)

### Details on version and operating system

_No response_

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

In the merge window, `Plain Text `seems to be the default mode. It can be changed to `Show Diff` (with 2 sub-options). But then, these changes are not remembered: back to `Plain text` when the window is re-opened. Selected display mode should be remembered

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by dragos222**
Fixes #9091 
The Merge Entries toolbar configuration now gets saved once the user hits 'Merge entries' button. More specifically, the plainTextOrDiff combo box, diffView combo box, and highlight words/highlight characters values are being stored using the GuiPreferences, and JabRefPreferences objects respectively. The 'Only show changed fields' check box was already handled, therefore I did not change its implementation. 
I have a question regarding the showDiff method from ThreeWayMergeView class: should this method be left the way it is now, or should it get updated so that the user's preferences are loaded when invoking the showDiff method?

image

```[tasklist]
### Compulsory checks
- [X] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [X] Screenshots added in PR description (for UI changes)
- [X] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [X] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by HoussemNasri** [comment]
I couldn't assign @ssrpro to the PR, but so you know he is working on this PR with @dragos222 on the same team.

**Comment by HoussemNasri** [comment]
> should this method be left the way it is now, or should it get updated so that the user's preferences are loaded when invoking the showDiff method?

Stored configuration should be loaded when the UI is created, e.g. at the constructor. Have a look at `ThreeWayMergeView#initializeToolbar`

File: src/main/java/org/jabref/gui/mergeentries/MergeEntriesDialog.java [hunk 1]
```diff
@@ -37,6 +37,7 @@ private void init() {
         this.getDialogPane().getButtonTypes().setAll(ButtonType.CANCEL, replaceEntries);
         this.setResultConverter(buttonType -> {
             if (buttonType.equals(replaceEntries)) {
+                threeWayMergeView.getThreeWayToolbar().saveGuiPreferences();
```
Comment (HoussemNasri) [inline src/main/java/org/jabref/gui/mergeentries/MergeEntriesDialog.java:40]: In OOP, you want to minimize the information objects know about each other. It is called [Information Hiding](https://www.wikiwand.com/en/Information_hiding). In the line above,  `MergeEntriesDialog` doesn't need to access the whole or most of the toolbar object to do its job. It only needs the `saveGuiPreferences` method. So a better design would be to call `threeWayMergeView.saveGuiPreferences()` and delegate the call to the toolbar method.

**Comment by dragos222** [comment]
Thank you for your feedback. The saveGuiPreferences has been delegated to the ThreeWayMergeView object and the MergeEntriesDialog object does not get access to the toolbar object.
The preferences are indeed loaded when the UI gets created. More specifically, these values are loaded in their according combo box/radio button in `ThreeWayMergeToolbar#initialize`.

**Review by Siedlerchr — APPROVED** [review]

File: src/main/java/org/jabref/gui/mergeentries/newmergedialog/toolbar/ThreeWayMergeToolbar.java [hunk 2]
```diff
@@ -176,6 +180,14 @@ public void setOnSelectRightEntryValuesButtonClicked(Runnable onClick) {
         selectRightEntryValuesButton.setOnMouseClicked(e -> onClick.run());
     }
 
+    public void saveGuiPreferences() {
+        preferencesService.getGuiPreferences().setMergePlainTextOrDiff(plainTextOrDiffComboBox.getValue());
```
Comment (HoussemNasri) [inline src/main/java/org/jabref/gui/mergeentries/newmergedialog/toolbar/ThreeWayMergeToolbar.java:184]: When I created the `PlainTextOrDiff` enum type, I thought it would be useful because I can embed the "Plain Text" and "Show Diff" texts in there, and display the labels in UI. In preferences, I think a boolean should suffice. Maybe a boolean property named `shouldShowDiffs`?

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/mergeentries/newmergedialog/toolbar/ThreeWayMergeToolbar.java:184]: This would have the advantage that you can then use bidrectional binding

**Review by HoussemNasri — CHANGES_REQUESTED** [review]
The merge configurations are being saved perfectly in the `MergeEntriesDialog`, however, in the `DuplicateResolverDialog` they are not. This is a complication, because the three-way merge UI is being used in multiple dialogs, so it's not obvious when the user is done with the UI and thus when to save the configuration.

I would start by doing the same changes you did to `MergeEntriesDialog` to the `DuplicateResolverDialog`, but this time, you want to save the configurations on all actions but the "Cancel" one.

Overall, I think you did a good job implementing this. Once the duplicate resolver dialog is updated, I think we can merge.

File: src/main/java/org/jabref/gui/mergeentries/newmergedialog/toolbar/ThreeWayMergeToolbar.java (hunk 2 above)
Comment (dragos222) [reply src/main/java/org/jabref/gui/mergeentries/newmergedialog/toolbar/ThreeWayMergeToolbar.java]: Implemented this for both PlainTextOrDiff and DiffView enums.

**Comment by dragos222** [comment]
The three way merge view toolbar preferences are now saved in `DuplicateResolverDialog` as well, on all actions but the "Cancel" one. There is a failing test, but it's not related to this PR and I notice that it also fails for other PRs.

**Review by HoussemNasri — DISMISSED** [review]
I took the courtesy to adjust some names and restructure the code. 

Also, while using the merge dialog, I expected the configuration to be saved even if I clicked "Cancel", so I changed that for both dialogs.

Thanks again for working on this enhancement. It would significantly improve the merging user experience, especially when resolving duplicates.

**Review by HoussemNasri — APPROVED** [review]
