### PR TITLE
Fix #14821: Hide identifier action buttons when field is empty

### LINKED ISSUE #14821: Eprint field shows an additional action icon/control on the General tab even when no eprint/eprinttype is set
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

ubuntu:22.04

### Checked with the [latest development build](https://builds.jabref.org/main/) (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open JabRef
2. Create a new empty library
3. Create a new Article entry and open the entry editor
4. Go to the General tab
5. Observe the Eprint field row (right side of the field)

### Expected Behavior
- No arXiv/eprint fetch control is shown unless an applicable identifier is present and the eprinttype indicates arXiv (or **the control is clearly disabled/inactive when not applicable**).

### Actual Behavior
- An extra icon/control (e.g., magnifier/fetch action in box 27) is visible next to the Eprint field compared to before, even though no eprint/eprinttype has been entered yet.

### Notes
Reproducible after merging https://github.com/JabRef/jabref/pull/14458 , namely Commit: https://github.com/JabRef/jabref/commit/029afb75f93eda0df9b5c2a2f341641309305635

### Screenshot before
Image

### Screenshot after
Image

### Appendix

Also applies to other magnifier/fetch action icons, which should be clearly disabled/inactive when the input is empty.

### PR DESCRIPTION
**Pull request by abhishek9773**
### **User description**
Closes #14821

### Steps to test
1. welcome screen -> **in start section**  ->(click) **new empty Library**
2. (JabRef Main menu bar) -> (click) Library -> **Add entry** .
3. **Observe Empty State**: Navigate to the **General** tab; verify icons are hidden for empty **DOI/Eprint** fields  .
4. **Trigger Icons**: Type text; icons should appear immediately.
5. **Verify Layout**: Clear text; icons should disappear and layout should expand.
6. For one more field verify ->  Step 3 switch to **Optional fields** -> **ISBN** (Observe step-4,5 behaviour )

### Visual Verification
[Watch the Screencast: UI Visibility Toggle Logic](https://github.com/user-attachments/assets/354996fe-ebd0-4f44-bfb9-57e00a98478b)

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [x] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

LLM USED:  HELPED ME  IN ARCHITECTURAL DECISION AND TEST CASE WRITING  

___

### **PR Type**
Enhancement

___

### **Description**
- Bind identifier action buttons visibility to text field state

- Buttons automatically hide when field is empty, decluttering UI

- Applies to Fetch, Lookup, and Shorten buttons for DOI, Eprint, ISBN fields

- Managed property synced with visibility for proper layout expansion

___

### Diagram Walkthrough

```mermaid
flowchart LR
  textField["Text Field"] -- "isNotEmpty()" --> visibility["Button Visibility"]
  visibility -- "bind" --> managed["Button Managed Property"]
  managed --> buttons["Fetch, Lookup, Shorten Buttons"]
```

<details><summary><h3>File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>IdentifierEditor.java</strong><dd><code>Bind identifier buttons visibility to text field state</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java

<ul><li>Added reactive property bindings for three identifier action buttons<br> <li> Buttons' visibility property bound to <br><code>viewModel.textProperty().isNotEmpty()</code><br> <li> Buttons' managed property bound to their visibility property<br> <li> Ensures buttons hide when field is empty and expand layout accordingly</ul>

</details>

  </td>
  <td><a href="https://github.com/JabRef/jabref/pull/14831/files#diff-27ce9cf30c4c1e6637b854071255c7267cb086b5daf88f948c3eeed17a11b902">+6/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tbody></table>

</details>

___

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java [hunk 1]
```diff
@@ -91,6 +92,20 @@ public IdentifierEditor(Field field,
         textField.initContextMenu(new DefaultMenu(textField), preferences.getKeyBindingRepository());
 
         new EditorValidator(preferences).configureValidation(viewModel.getFieldValidator().getValidationStatus(), textField);
+
+        java.util.stream.Stream.of(fetchInformationByIdentifierButton, lookupIdentifierButton)
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java]: Avoid the whole class-path. Just import and use Stream.of

Comment (abhishek9773) [reply jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java]: Thanks for the feedback. I've updated the code to use a clean Stream import.

Comment (calixtus) [reply jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java]: Was looking from mobile, currently on a trip, a detailed code review will take a few days.

**Comment by subhramit** [comment]
@abhishek9773 thanks for the contribution. 
Next time please also make necessary disclosures as per our [AI usage policy](https://github.com/JabRef/jabref/blob/main/AI_USAGE_POLICY.md) - whatever you have used AI for.

File: CHANGELOG.md [hunk 2]
```diff
@@ -19,6 +19,7 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
 
 ### Fixed
 
+- Fixed redundant action icons showing in empty identifier fields (DOI, Eprint, ISBN) [#14831](https://github.com/JabRef/jabref/pull/14831)
```
Comment (koppor) [inline CHANGELOG.md]: https://github.com/JabRef/jabref/issues/14821

**Comment by abhishek9773** [comment]
Hi @koppor, @subhramit, 
​Thanks for  the guidance on this. I’ve gone ahead and updated the `CHANGELOG.md` with the correct issue number (#14821) and fixed the Stream imports and indentation in IdentifierEditor.java to match the project standards.

​I also wanted to be fully transparent about my use of AI on this PR, as per the project policy. As a new contributor, I’ve been using AI as a tool to ensure my code and test cases actually reach the industry standards expected here. For example, in the `IdentifierEditorTest`, it helped me implement the proper `interact()` and `clickOn()` patterns for JavaFX rather than using less robust manual erasures. It's been a great way for me to learn the codebase faster.

​I sincerely apologize for the 'chaos' with the force-pushes. I was trying to keep the history clean as I learned, but I see now that it triggered the build failures and made your review harder.
​I’m not in a rush to merge- I just want to make sure I’m doing things the right way. Please let me know how I should handle the failing checks from the force-push, and I’ll get on it. Thanks again!

**Comment by subhramit** [comment]
> Hi @koppor, @subhramit,​Thanks for the guidance on this. I’ve gone ahead and updated the `CHANGELOG.md` with the correct issue number (#14821) and fixed the Stream imports and indentation in IdentifierEditor.java to match the project standards.
> 
> ​I also wanted to be fully transparent about my use of AI on this PR, as per the project policy. As a new contributor, I’ve been using AI as a tool to ensure my code and test cases actually reach the industry standards expected here. For example, in the `IdentifierEditorTest`, it helped me implement the proper `interact()` and `clickOn()` patterns for JavaFX rather than using less robust manual erasures. It's been a great way for me to learn the codebase faster.
> 
> ​I sincerely apologize for the 'chaos' with the force-pushes. I was trying to keep the history clean as I learned, but I see now that it triggered the build failures and made your review harder.​I’m not in a rush to merge- I just want to make sure I’m doing things the right way. Please let me know how I should handle the failing checks from the force-push, and I’ll get on it. Thanks again!

Usage of AI to refine code is alright, and thanks for being transparent. However, please try to communicate in your own terms rather than copy pasting LLM responses. Please look at [these guidelines](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md#ai-usage-policy). Since you seem to have understood your changes, you are also expected to write the PR description yourself instead of generating it using an LLM.
As an avid open source community, we prefer to interact organically with people.

**Comment by abhishek9773** [comment]
@subhramit Thank you for pointing me out. from now onwards  I will make sure that I am following  all the points you have  mentioned

File: CHANGELOG.md [hunk 3]
```diff
@@ -20,6 +20,7 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
...
```
Comment (subhramit) [inline CHANGELOG.md]:
```suggestion
- Fixed redundant action icons showing in empty identifier fields (DOI, Eprint, ISBN) [#14821](https://github.com/JabRef/jabref/pull/14821)
```

**Comment by subhramit** [comment]
@abhishek9773 not sure why you clicked on "resolve conversation" without acting on review changes

**Comment by abhishek9773** [comment]
> @abhishek9773 not sure why you clicked on "resolve conversation" without acting on review changes

it was mistake . i made changes to "changelog.md" file but forgot to add those changes during ">git add" and mistakenly assumed i had done so. 
image (1)

image (3)

**Comment by subhramit** [comment]
> > @abhishek9773 not sure why you clicked on "resolve conversation" without acting on review changes
> 
> it was mistake . i made changes to "changelog.md" file but forgot to add those changes during ">git add" and mistakenly assumed i had done so. image (1)
> 
> image (3)

look for this "outdated" label before resolving conversations:
image

File: jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java [hunk 4]
```diff
@@ -91,6 +93,20 @@ public IdentifierEditor(Field field,
         textField.initContextMenu(new DefaultMenu(textField), preferences.getKeyBindingRepository());
 
         new EditorValidator(preferences).configureValidation(viewModel.getFieldValidator().getValidationStatus(), textField);
+
+        Stream.of(fetchInformationByIdentifierButton, lookupIdentifierButton)
+              .forEach(button -> {
+                  button.visibleProperty().bind(viewModel.textProperty().isNotEmpty());
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java:99]: Did someone understand what "lookup" means?

Comment (abhishek9773) [reply jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java:99]: I misunderstood the behavior and took the word “hide” literally. 
I also understand that “lookup” should work even when there is no DOI, by searching online.

I can change the code to disable instead of hide. Is this what you mean?

File: jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java [hunk 5]
```diff
@@ -91,6 +93,20 @@ public IdentifierEditor(Field field,
...
+                  button.managedProperty().bind(button.visibleProperty());
+              });
+
+        shortenDOIButton.managedProperty().bind(shortenDOIButton.visibleProperty());
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java:103]: The code totally overlooked org.jabref.gui.fieldeditors.identifier.BaseIdentifierEditorViewModel#canShortenIdentifier

File: jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java (hunk 4 above)
Comment (koppor) [reply jabgui/src/main/java/org/jabref/gui/fieldeditors/identifier/IdentifierEditor.java:99]: Thank you for the offer. Your past PR needed more than 10 comments of two different maintainers. Still the code did not work. Your code is just hacky - and did not build on existing (!) JavaFX code. Thus, we should save the time of both you and the team. -- In future, please first read around at the code base. The IdentifierEditor is a very nice example to learn about JavaFX bindings and general UI principles in JavaFX. You missed this opportunity.

I already fixed it at https://github.com/JabRef/jabref/pull/14931.
