### PR TITLE
Fixes miss-parsed names in `AutomaticPersonsGroup`

### LINKED ISSUE #5833: "New Group" > "Specified keywords" > "Generate groups for author last names" not working properly
When selecting "New Group" > "Specified keywords" > "Generate groups for author last names", providing any group name, entering "author" in the field "Field to group by" and clicking "OK", then hardly any (or even none) of the generated groups with the authors' last names have entries in it. Most badges have the value 0.

I'm using the latest JabRef 5 master build on Ubuntu 16.04.

image

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Fixes #5833.

This fixes the parsing and matching of authors' last names. It is much slower than the previous solution, and uses more RAM, but I think that is hard/impossible to avoid. However, it is possible that the caching solution can be made smarter, but I leave the decision if it should, to the reviewers 😁 

An alternative solution is moving the caching to `AuthorList`, it will make it easier to modify/improve at a later point in time. ~It will make this PR take quite a bit of more time as I'd like to make `AuthorList` extend `List` in that case. See https://github.com/JabRef/jabref/pull/6552#issuecomment-641377508 for a much longer discussion on that topic.~
Given that the only thing that should be cached are the last names (and always latex-free), perhaps it has more in common with the autocomplete functionality. I have not looked into that.

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] ~Screenshots added in PR description (for UI changes)~
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertFalse;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+
+class AutomaticPersonsGroupTest {
+    @Test
+    void createSubgroupsFromCommaSeparatedLastNames() {
+        BibEntry bibEntry = new BibEntry().withField(StandardField.AUTHOR, "Turing, Alan and Hopper, Grace");
+        var subgroups = new AutomaticPersonsGroup("", GroupHierarchyType.INDEPENDENT, StandardField.AUTHOR).createSubgroups(bibEntry);
+        assertEquals(2, subgroups.size());
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java:17]: It's better to construct a list of expected elements by hand and compare to that. For example, if the code happens to return 3 elements, you now only get a message saying "expected 2 but got 3" - not very helpful. But if you do
`expected = Arrays.asList(new Keywordgroup(...), ...); assertEquals(expected, subgroups)` you get a nice message, showing you which additional group is there.

Comment (tobiasdiez) [inline src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java:17]: It's better to construct a list of expected elements by hand and compare to that. For example, if the code happens to return 3 elements, you now only get a message saying "expected 2 but got 3" - not very helpful. But if you do
`expected = Arrays.asList(new Keywordgroup(...), ...); assertEquals(expected, subgroups)` you get a nice message, showing you which additional group is there.

**Review by tobiasdiez — COMMENTED** [review]
So, what was the problem in the end? It looks like the code is more or less equivalent to the one before, except that now the author parsing and latex2unicode conversion are in a different order (which does make sense!). Is this the only change?

Concerning the caching, I think this is not needed. The parsing of a string to an authorlist is already cached, and getting the last names with latex converted is also cached:
https://github.com/JabRef/jabref/blob/afdb1942c5ec2126e69c92c7f2660459a7bdbeae/src/main/java/org/jabref/model/entry/AuthorList.java#L377
However, this code probably needs to be changed a bit to be usable for our purposes. I would suggest to add a `getLastNameLatexFree` in `Author`, which caches it's result. This method then can be used in the groups parsing, as well as in `AuthorList.getAsLastNamesLatexFree` (there is no need to have an additional cache there again).

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> So, what was the problem in the end? It looks like the code is more or less equivalent to the one before, except that now the author parsing and latex2unicode conversion are in a different order (which does make sense!). Is this the only change?

The other change is that the previous solution relied on the existing `WordKeywordGroup` SearchStrategies which did not parse authors. Hence, "Turing, Allan" ended up attempting to match the group "Turing" with the last name "Turing," (note the `,`). There might be other differences as well but my "contribution" is to use the same code that parses the names for the groups to check if an author matches.
Note that among the test cases it is only `createSubgroupsContainingCommaSeparatedLastNames` that fails without these changes.

Now that I am looking at it again, I'll see if I can extend `KeywordGroup` instead. It should make the changes more readable... 

> Concerning the caching, I think this is not needed. The parsing of a string to an authorlist is already cached, and getting the last names with latex converted is also cached:
> https://github.com/JabRef/jabref/blob/afdb1942c5ec2126e69c92c7f2660459a7bdbeae/src/main/java/org/jabref/model/entry/AuthorList.java#L377
> However, this code probably needs to be changed a bit to be usable for our purposes. I would suggest to add a `getLastNameLatexFree` in `Author`, which caches it's result. This method then can be used in the groups parsing, as well as in `AuthorList.getAsLastNamesLatexFree` (there is no need to have an additional cache there again).

In some cases the `getAsLastNamesLatexFree` contain "and" between the two last authors. Given that a latex-free string is allowed to contain "and" for other reasons (e.g., `{Barnes and Noble}`) I'd rather avoid using a plain `String`.
I don't have an opinion regarding added an `Author#getLastNameLatexFree`. Every time I look at this issue I end up thinking "this should be fixed in `BibEntry#getResolvedFieldOrAliasLatexFree`" in which case the `AUTHOR_CACHE` would cache latexfree `AuthorList`s, but that is in my opinion, a bit of a nightmare to implement.
Should I add the `Author#getLastNameLatexFree` method? At the very least it would allow 
```
.map(Author::getLastNameLatexFree)
```

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I just feel that if the caching for `AuthorList.getAsLastNamesLatexFree` is removed, they all should be removed. I'd guess the `stream`...`Collectors.joining` is fast enough for that.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Just a note... It seems that none of the groups use `BibDatabase` which means they all use `entry.getField` instead of `entry.getResolvedFieldOrAlias`.
I'd argue it would be out of scope for this issue, but it could lead to problems.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I just realized that `AuthorList.getAsLastNamesLatexFree` uses `getLastOnly`, not `getLast`. So I can't reuse that cache easily. I think that for the `AutomaticPersonGroup` it makes sense that the subgroup is named `Neumann` and not `von Neumann`.

File: src/main/java/org/jabref/model/groups/LastNameGroup.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+public class LastNameGroup extends KeywordGroup {
+    public LastNameGroup(String groupName, GroupHierarchyType context, Field searchField, String lastName) {
+        super(groupName, context, searchField, LatexToUnicodeAdapter.format(lastName), true);
+    }
+
+    static List<String> getAsLastNamesLatexFree(Field field, BibEntry bibEntry) {
+        return bibEntry.getField(field)
+                       .map(AuthorList::parse)
+                       .map(AuthorList::getAuthors)
+                       .map(authors ->
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/model/groups/LastNameGroup.java:27]: if you add flatmap already here, it allows to chain everything nicely I think

File: src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+import org.jabref.model.strings.LatexToUnicodeAdapter;
+
+import org.junit.jupiter.api.Test;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+class AutomaticPersonsGroupTest {
+    private static Set<GroupTreeNode> createPersonSubGroupFrom(String... lastNames) {
+        return Arrays.stream(lastNames)
+                     .distinct()
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java:18]: please remove distinct and the latextounicode part here. The tests should be a as stupid as possible, e.g. if you want to test that the code transforms latex to unicode, you better do it by hand.

File: src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+        BibEntry bibEntry = new BibEntry().withField(StandardField.AUTHOR, "Turing, Alan and Hopper, Grace");
+        var subgroups = new AutomaticPersonsGroup("", GroupHierarchyType.INDEPENDENT, StandardField.AUTHOR).createSubgroups(bibEntry);
+        var expectedSubgroups = createPersonSubGroupFrom("Turing", "Hopper");
+        assertEquals(expectedSubgroups, subgroups);
+    }
+
+    @Test
+    void createSubgroupFromLatexAndCheckForUnicodeLastName() {
+        BibEntry bibEntry = new BibEntry().withField(StandardField.AUTHOR, "Kurt G{\\\"{o}}del");
+        BibEntry godelEntry = new BibEntry().withField(StandardField.AUTHOR, "Kurt Gödel");
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java:45]: godelEntry is not used, right? (here and in the following test)

**Comment by tobiasdiez** [comment]
> I just feel that if the caching for AuthorList.getAsLastNamesLatexFree is removed, then all the AuthorList.getAs...LatexFree should be removed. I'd guess the stream...Collectors.joining is fast enough for that.

I completely agree! The `Author` class should be responsible to calculate the latex-free version of names etc, and cache its result. Maybe, the most readable version is a method `Author latexfree()` which returns the complete latex2unicode converted representation of the author, so you can write `author.latexfree().getLast()`. That's something of value even beyond this ticket!
Would also make it pretty easy to cache in a flexible way, e.g. for `getLastOnly`.

>  Every time I look at this issue I end up thinking "this should be fixed in BibEntry#getResolvedFieldOrAliasLatexFree"
That would be indeed a good solution, but is sadly not possible. `{Barnes and Noble} and Author` is sadly different to `Barnes and Noble and Author`. The author specification of bibtex is just a mess, and relies on so many assumptions. The best would be if people would only rely on the explicit name format of biber/biblatex: `AUTHOR = {given=Arnar, family=Vigfusson}`, but that's a very long way to go.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> > I just feel that if the caching for AuthorList.getAsLastNamesLatexFree is removed, then all the AuthorList.getAs...LatexFree should be removed. I'd guess the stream...Collectors.joining is fast enough for that.
> 
> I completely agree! The `Author` class should be responsible to calculate the latex-free version of names etc, and cache its result. Maybe, the most readable version is a method `Author latexfree()` which returns the complete latex2unicode converted representation of the author, so you can write `author.latexfree().getLast()`. That's something of value even beyond this ticket!
> Would also make it pretty easy to cache in a flexible way by having only `Author latexfree` as a cached variable. It's also pretty extensible you get automatic caching for methods like `getLastOnly`.

Perhaps this is the good way out of this... I just have this itch to kill the `Author` class and make it a `Map`, preferably an `EnumMap` (thought that might not be possible)... I might be tunnel-visioning on that 😁 
I'd argue it is out of scope of this issue. Rewriting the `AuthorList#getAs...` would be (one) of the main benefits but it would be quite time consuming. Additionally, if someone wants to track down possible performance bottlenecks, it would be better in its own PR. You think opening up a new PR with `Author.latexFree` (`Author.resolveLatex`?) is the way to go (rather than continuing it here)?

> > Every time I look at this issue I end up thinking "this should be fixed in BibEntry#getResolvedFieldOrAliasLatexFree"
> 
> That would be indeed a good solution, but is sadly not possible. `{Barnes and Noble} and Author` is sadly different to `Barnes and Noble and Author`. The author specification of bibtex is just a mess, and relies on so many assumptions. The best would be if people would only rely on the explicit name format of biber/biblatex: `AUTHOR = {given=Arnar, family=Vigfusson}`, but that's a very long way to go.

In my opinion, that solution is possible. However, it would require changes to the author parser so that delimiters can be reconstructed. The surrounding braces are removed by `Author`, internal braces might be a bigger challenge. It would also tie in to the discussion about the mess outside the bibtex/biber/biblatex definitions of authors, if #2205 is still an issue (I have been eyeing it but not found the time to look at the details).

And thank you for multiple code review on new year as well! 🎆

File: src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java (hunk 4 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java:45]: Nope. I really need to stop ignoring my IDE warnings, at least in code I have written myself. Sorry about that.

File: src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java (hunk 3 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java:18]: This is what I use to generated the expected result.
1. I am using latextounicode part here because I use the last name both as group name and search expression. As it is the expected subgroup they must be the same. (and without latex)
2. The distinct is implied from the set. Given that this is used to generate the expected result, if something messes up in the equality/hashing of the group, it is likelier to be caught by using distinct Strings to create the groups.

That said, if you don't agree I'll change both.

File: src/main/java/org/jabref/model/groups/LastNameGroup.java (hunk 2 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/model/groups/LastNameGroup.java:27]: ... I forgot that `Optional.stream` existed... 🤯

File: src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java (hunk 3 above)
Comment (tobiasdiez) [reply src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java:18]: I think `createPersonSubGroupFrom(`A`, `A`)` should create two groups. It's the responsible of the caller to make sure she passes distinct values. Similar, one should pass `Römer` instead of `R\"omer` if one expect that latex is resolved.
The current test passes if latex2unicode is changed to return always the same string that was put into it. That's not desired.

**Review by tobiasdiez — COMMENTED** [review]
The current changes are fine with me. The author caching of latexfree things can be done in a follow-up PR.

File: src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java (hunk 3 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/model/groups/AutomaticPersonsGroupTest.java]: Unless I have missed something, the tests should now be as stupid as they can be ^^

**Review by tobiasdiez — APPROVED** [review]

File: src/main/java/org/jabref/model/groups/LastNameGroup.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+    }
+
+    @Override
+    public AbstractGroup deepCopy() {
+        return new LastNameGroup(getName(), getHierarchicalContext(), getSearchField(), getSearchExpression());
+    }
+
+    @Override
+    public boolean equals(Object other) {
+        if (super.equals(other)) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/model/groups/LastNameGroup.java:45]: You can easily use instanceof here that should also check for supertypes.
http://www.angelikalanger.com/Articles/JavaSolutions/SecretsOfEquals/Equals.html

And tip: Use Objects.equals(getSearchField, otherGroup.getSearchField)

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/model/groups/LastNameGroup.java:45]: Objects.equals, good catch, I am not sure why I didn't use it.

If I understand you correctly, you'd like a specific check for `LastNameGroup` rather than relying on the `.getClass()` from `AbstractGroup.equals`
https://github.com/JabRef/jabref/blob/10180edf451c79785ec21a406b9bd309fe90ca80/src/main/java/org/jabref/model/groups/AbstractGroup.java#L52-L57
?

Comment (Siedlerchr) [reply src/main/java/org/jabref/model/groups/LastNameGroup.java:45]: if (this instanceof other) was the approach I thought of

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/model/groups/LastNameGroup.java:45]: There were a few things in the article I had not encountered before, and I have made the changes I believe are necessary for a "class hierarchies of value types". (The code is now almost identical to "Listing 4" in the article)

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/model/groups/LastNameGroup.java]: @Siedlerchr are you ok with the current approach?

Comment (tobiasdiez) [reply src/main/java/org/jabref/model/groups/LastNameGroup.java]: (By the way, Intellj can also auto-generate these equals/hash/tostring methods)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
`k3KAW8Pnf7mkmdSMPHz27 dismissed tobiasdiez’s stale review via edd24bd `

Oups. Sorry, I did not know that was a thing. I just wanted to play around with what went wrong with the equality and hashCode (barring my thinking 🤡 ), since it should not hurt to have more "standard" equality and hashCode methods.

**Review by tobiasdiez — APPROVED** [review]
I've also only recently noticed this. I guess it's coming from the recent changes that PRs need to be reviewed before they are merged (that was always a standing requirement, but now github is configured for it is well). @koppor

**Comment by koppor** [comment]
> `k3KAW8Pnf7mkmdSMPHz27 dismissed tobiasdiez’s stale review via edd24bd `

This is some automatic thing. Any change will dismiss a review. We want to be sure that approvals are "done right". The final approver can check whether the changes from the dismissed approval to the current one are OK.

Thus, no worries! 🎉  - And thank you for continuing on working on this.
