### PR TITLE
move check for invalid characters to linked files editor

### LINKED ISSUE #12212: adding file with illegal character does not proceed
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-17--572c823 Linux 6.11.7-300.fc41.x86_64 amd64  Java 23.0.1  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ... I have a pdf with a `?` in the filename. I think that is illegal.
2. ... I attach it to the entry.
3. ... it is displayed :whitecheckmark:
4. JabRef does not allow me to open iot with a double click

I would have expected that JabRef asks me whether it should rename the file (I think that worked in the past).

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #12212

some cleanup

Follow up to https://github.com/JabRef/jabref/pull/11539

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java [hunk 1]
```diff
@@ -253,13 +253,10 @@ private void setUpKeyBindings() {
...
-                    case DELETE_ENTRY:
-                        deleteAttachedFilesWithConfirmation();
-                        event.consume();
-                        break;
-                    default:
-                        // Pass other keys to children
+                // Pass other keys to children
+                if (keyBinding.get() == KeyBinding.DELETE_ENTRY) {
+                    deleteAttachedFilesWithConfirmation();
+                    event.consume();
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java:259]: I know, IntelliJ complains that this should be an if clause, but...
Everywhere a keybinding test has more than one case its a switch, so for consistency reasons I would propose to keep this as a switch, even though it got only one case.

File: src/main/java/org/jabref/gui/linkedfile/LinkedFileEditDialogViewModel.java [hunk 2]
```diff
@@ -86,12 +94,29 @@ public void openBrowseDialog() {
...
+                        Localization.lang("Illegal characters in the file name detected.\nFile will be renamed to \"%0\" and added.", newFilename),
+                        Localization.lang("Rename and add"));
+
+                if (correctButtonPressed) {
+                    Path correctPath = fileToAdd.resolveSibling(newFilename);
+                    try {
+                        Files.move(fileToAdd, correctPath);
+                        link.set(relativize(correctPath));
+                        filePreferences.setWorkingDirectory(correctPath);
+                        setExternalFileTypeByExtension(link.getValueSafe());
```
Comment (HoussemNasri) [inline src/main/java/org/jabref/gui/linkedfile/LinkedFileEditDialogViewModel.java:113]: Can we unit test that this part is executed when it should? We can mock  dialogService.showConfirmationDialogAndWait I think.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/linkedfile/LinkedFileEditDialogViewModel.java:113]: The problem is that this is executed inside the showFileOpenDialog

**Review by calixtus — APPROVED** [review]
