### PR TITLE
Fix maintable not updated when changing entry type

### LINKED ISSUE #5906: Changing entry type does not always work when biblatex source is not shown
I am using the latest JabRef 5 master build:
Java 13.0.2
on Ubuntu 16.04

The value of the entry type field for an entry in the main table is not updating when changing its type by using the dropdown menu of the entry editor. To differentiate this from issue #5905, one can assume, that in the entry editor the tab "biblatex source" is not/never active.

**Steps to reproduce the behavior:**

1. Double click an entry in the main table (with e.g. entry type "Article")
2. Change entry type via the dropdown menu to a different entry type (e.g. entry type "Misc")
3. Do "whatever you want", but don't open the tab "biblatex source" in the entry editor.

_Observation:_ Commonly, the entry type will not change in the main table, even if shortly selecting a different entry in the main table and reselecting the edited one. Sometimes temporarily switching to a different opened library helps, but not always.

Contrarily, other fields in the main table will be updated immediately, when their values get changed.

---

**Subsequent observation (now allows viewing the tab "biblatex source"):**

1. Perform steps 1. and 2. as above.
2. Save library with CTRL+S.
3. Switch to "biblatex source"

_Observation:_ The library has been modifed (indicated with the star symbol "*"), although no change was conduted.

For both cases, I assume it could be some reference problem.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #5906

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

File: src/main/java/org/jabref/model/entry/BibEntry.java [hunk 1]
```diff
@@ -915,7 +915,11 @@ public void setDate(Date date) {
     }
 
     public ObjectBinding<String> getFieldBinding(Field field) {
-        //noinspection unchecked
+        if (field == InternalField.TYPE_HEADER || field == InternalField.OBSOLETE_TYPE_HEADER) {
+            return Bindings.createObjectBinding(() -> {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/model/entry/BibEntry.java]: Please use `EasyBind.map(type, Type::getDisplayName);`
