### PR TITLE
Fix GUI tests

### LINKED ISSUE #5602: Gui tests are broken
All special types of tests (fetcher, database and gui) are currently broken. At least the fetcher tests should be fixed before the release of 5.0.

I would also vote to remove the "allow failure" for these tests (as soon as they are fixed).

### PR DESCRIPTION
**Pull request by koppor**
Fixes #5602, refs #2768.

Wanted to know why our GUI tests are broken. The reason seems to be that we don't pass the preferences objects directly around, but use `Globals.prefs` at more places. Currently, the issue is in `MainTable.java`:

```java
        importHandler = new ImportHandler(
                frame.getDialogService(), database, externalFileTypes,
                Globals.prefs.getFilePreferences(),
                Globals.prefs.getImportFormatPreferences(),
                Globals.prefs.getUpdateFieldPreferences(),
                Globals.getFileUpdateMonitor(),
                undoManager,
                Globals.stateManager);
```

I would propose to convert the constructor of `MainTable` (and `BasePanel`) to a builder pattern (because we have more than three arguments) and add passing of these preferences.

Alternatively, we can mock `Globals.prefs.GetFilePreferences()` etc. This is also OK for me as I accept global objects. However, we had a long discussion that we should get rid off `Globals`.

Is https://github.com/JabRef/jabref/issues/1579 the right issue, where we discussed `Globals.prefs`? I think, the comment at https://github.com/JabRef/jabref/pull/1593#discussion_r71328057 summarizes the discussion.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
+1 for extracting `Globals.prefs` and mocking the relevant data. I don't think a builder pattern is necessary as the relevant classes are rarely initialized and all arguments need to be present anyway.

File: src/main/java/org/jabref/gui/BasePanel.java [hunk 1]
```diff
@@ -145,8 +154,8 @@
     private Optional<DatabaseChangeMonitor> changeMonitor = Optional.empty();
     private JabRefExecutorService executorService;
 
-    public BasePanel(JabRefFrame frame, BasePanelPreferences preferences, BibDatabaseContext bibDatabaseContext, ExternalFileTypes externalFileTypes) {
-        this.preferences = Objects.requireNonNull(preferences);
+    public BasePanel(JabRefFrame frame, BasePanelPreferences basePanelPreferences, BibDatabaseContext bibDatabaseContext, ExternalFileTypes externalFileTypes, GroupViewMode groupViewMode, FilePreferences filePreferences, ImportFormatPreferences importFormatPreferences, UpdateFieldPreferences updateFieldPreferences, FileUpdateMonitor fileUpdateMonitor, StateManager stateManager, Consumer<ColumnPreferences> updateColumnPreferences, Supplier<TimestampPreferences> timestampPreferencesSupplier) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/BasePanel.java]: I think it's better to pass a PreferenceService if you need to store preference options (or get the current preferences at a later moment).

**Comment by koppor** [comment]
I'm not sure whether we should continue with it like that. Should we try
other solutions such as Eclipse Jubula - which are independent from the
concrete code. I see that separate preferences for model and logic makes
sense. For GUI, it is *much* effort... Is it really worth the effort? Do we
need these kinds of tests? Would it make more sense to do black box testing?

Maybe, we should let this task (enable testing by TestFX) be done by
students in a training next year? Seems to be much more work than expected.
I wanted to come up with a quick solution to get it running to have our
tests green.

Tobias Diez <notifications@github.com> schrieb am Do., 26. Dez. 2019, 09:45:

**Comment by tobiasdiez** [comment]
I think GUI tests would be nice to have. It's a good idea to let students extend the code coverage in a forthcoming project (similarly to what we did with the fetcher test suite). However, we should provide a few basic tests that serve as an orientation. With MVVM there shouldn't be any need for UI tests in the traditional sense (TestFX or Jubala or whatever) as one can simply write unit tests for the view model classes. Moreover, the current GUI tests don't add much value in my opinion. 

For me it would be fine to remove all GUI tests that we have currently.

File: src/main/java/org/jabref/gui/BasePanel.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/BasePanel.java]: Oh, yeah. - I wonder why we don't more often use this service in the GUI instead of relying on JabRefPreferences directly.

**Comment by koppor** [comment]
The whole "mess" is only for the BasePanelTest - to fix the other tests was easy. I removed all the "improvements" and made only cosmetic changes.

File: src/main/java/org/jabref/gui/BasePanel.java (hunk 1 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/BasePanel.java]: Because it was introduced only recently.

File: src/main/java/org/jabref/gui/search/rules/describer/ContainsAndRegexBasedSearchRuleDescriber.java [hunk 2]
```diff
@@ -40,6 +40,9 @@ public TextFlow getDescription() {
         }
 
         textList.add(getCaseSensitiveDescription());
+        textList.add(TooltipTextUtil.createText("\n\nHint: To search specific fields only, enter for example:\n"));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/search/rules/describer/ContainsAndRegexBasedSearchRuleDescriber.java]: Shouldn't this be localized?

File: src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java [hunk 3]
```diff
@@ -40,7 +48,16 @@
     public void onStart(Stage stage) {
         area = new CodeArea();
         area.appendText("some example\n text to go here\n across a couple of \n lines....");
-        sourceTab = new SourceTab(new BibDatabaseContext(), new CountingUndoManager(), new LatexFieldFormatterPreferences(), mock(ImportFormatPreferences.class), new DummyFileUpdateMonitor(), mock(DialogService.class), mock(StateManager.class));
+        StateManager stateManager = mock(StateManager.class);
+        when(stateManager.activeSearchQueryProperty()).thenReturn(OptionalObjectProperty.empty());
+        Globals.prefs = mock(JabRefPreferences.class);
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java]: Is it really that complicated to extract the preferences and replace `Globals.prefs` by constructor arguments?

Comment (koppor) [reply src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java]: You're right. Fixed.

File: src/main/java/org/jabref/gui/search/rules/describer/ContainsAndRegexBasedSearchRuleDescriber.java (hunk 2 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/search/rules/describer/ContainsAndRegexBasedSearchRuleDescriber.java]: I translated the hint text - not the query itself. - Was the best thing, I could come up with.
