### PR TITLE
Fix the F4 shortcut key

### LINKED ISSUE #6101: F4 Shortcut not working
JabRef version <5.0> on <!Windows 10 x64>

F4 Shortcut for opening file does not work. (Worked fine in v4.31)
Changing to some different combination like alt+F5 doesn't help.
Opening PDF by clicking works fine.

(in addition: pushing the broom symbol for resetting, but then cancel the procedure when closing the window still saves the setting, probably connected with that issue(?))

### PR DESCRIPTION
**Pull request by priyanshu16095**
### Fixes #6101

The fix ensures that the F4 shortcut functions as expected without need to open the right click context menu each time.

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/maintable/OpenFileAction.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+            if (entries.size() != 1) {
+                dialogService.notify(Localization.lang("This operation requires exactly one item to be selected."));
+                return;
+            }
+
+            BibEntry entry = entries.getFirst();
+
+            if (entry.hasField(StandardField.FILE)) {
+                LinkedFile linkedFile = entry.getFiles().getFirst();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/maintable/OpenFileAction.java:52]: Warning, if no file is attached this will throw a NoSuchElement exception

**Review by Siedlerchr — DISMISSED** [review]

File: src/main/java/org/jabref/gui/maintable/OpenFileAction.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+            if (entries.size() != 1) {
+                dialogService.notify(Localization.lang("This operation requires exactly one item to be selected."));
+                return;
+            }
+
+            BibEntry entry = entries.getFirst();
+
+            if (entry.hasField(StandardField.FILE) && !entry.getFiles().isEmpty()) { 
+                LinkedFile linkedFile = entry.getFiles().getFirst();
```
Comment (subhramit) [inline src/main/java/org/jabref/gui/maintable/OpenFileAction.java:52]: What if there are multiple linked files?

**Review by subhramit — COMMENTED** [review]
I have some questions - 
1. What was causing the bug? Did we investigate why f4 worked in some cases before (but not all)?
2. See review comment

**Review by Siedlerchr — APPROVED** [review]
