### PR TITLE
Fix for Library is marked as unsaved (*) after accepting changes from the file

### LINKED ISSUE #11027: Library is marked as unsaved (*) after accepting changes from the file
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

This is visible when someone edits the file with jabref while you have the same library open. I don't know of a good way to reproduce other than that, maybe by editing the file in a text editor, or having two instances of jabref open (I don't know if easily done).

1. Open any library file with at least one entry
2. Edit the bib file in a text editor, remove one entry (leave a single line between entries to match jabref output format) and save
4. Notice that in the main instance, a notification about changes being made by another program appears.
5. Select Review changes
6. Accept the change
7. Notice that the library appears as modified, even though it should match exactly the contents of the file saved to disk

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by amrithdas**
In the review changes prompt for external changes:
if external changes are accepted -> asterisk removed and save changes prompt will not pop up when closing tab.
if external changes are denied -> asterisk will be present and save changes prompt will pop up when closing tab.
Closes #11027

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/LibraryTab.java [hunk 1]
```diff
@@ -910,7 +910,8 @@ public void resetChangeMonitor() {
                 taskExecutor,
                 dialogService,
                 preferencesService,
-                databaseNotificationPane));
+                databaseNotificationPane,
+                stateManager.activeTabProperty()));
```
Comment (koppor) [inline src/main/java/org/jabref/gui/LibraryTab.java:914]: Pass down the statemanager, not the property itself.

File: src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java [hunk 2]
```diff
@@ -82,10 +86,18 @@ public void acceptChange() {
             selectedChange.accept();
             getVisibleChanges().remove(selectedChange);
         });
+        if (activeTab != null) {
+            activeTab.get().get().updateTabTitle(false);
+            activeTab.get().get().resetChangedProperties();
+        }
```
Comment (koppor) [inline src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java:92]: I think, this is a **single** change.

The issue is about **all** changes. If **all** changes are accepted, there is no change. In case there is a single change denied, then the database should be changed.

In your code, if I deny and then accept, the asterisk is removed even if it should stay.

I think, the logic should go somewhere elese. It feels to deep in this ViewModel. Isn't it?

I think the detection should go into `org.jabref.gui.collab.ExternalChangesResolverViewModel#applyChanges`.

**Review by koppor — CHANGES_REQUESTED** [review]
Your code is too deep.

---

Please lean back and check the behavior of JabRef.

If a user presses "Deny" for all external changes, there is NO asterisk! - Thus, there is some logic for setting the asterisk hidden somehwere. But implemented in the wrong way.

I think, the final coude changes are maybe only 2 lines of code - and not dozens...

File: src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java (hunk 2 above)
Comment (amrithdas) [reply src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java]: logic moved to apply changes

File: src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java [hunk 3]
```diff
@@ -100,8 +102,15 @@ public void acceptMergedChange(DatabaseChange databaseChange) {
     }
 
     public void applyChanges() {
-        changes.stream().filter(DatabaseChange::isAccepted).forEach(change -> change.applyChange(ce));
-        ce.end();
-        undoManager.addEdit(ce);
+        if (changes.stream().noneMatch(change -> !change.isAccepted())) {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java:105]: Isn't it that all changes are accepted? Then, it can be formulated more directly:

```suggestion
        if (changes.stream().allMatch(change -> change.isAccepted())) {
```

File: src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java [hunk 4]
```diff
@@ -100,8 +102,15 @@ public void acceptMergedChange(DatabaseChange databaseChange) {
...
+            changes.stream().filter(DatabaseChange::isAccepted).forEach(change -> change.applyChange(ce));
+            ce.end();
+            undoManager.addEdit(ce);
+            stateManager.activeTabProperty().get().get().updateTabTitle(false);
```
Comment (koppor) [inline src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java:109]: does not work in all cases, because dialog ist also called from BackupUIManager

image

Comment (koppor) [reply src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java:109]: I could not see where the asterisk is really written.

Thus, I propose:

DatabaseChangeMonitor, line 62:

Extract `new DatabaseChangesResolverDialog` to own variable `databaseChangesResolverDialog`.
After `showCustomDialogAndWait`, ask the `databaseChangesResolverDialog` whether there werre changes etc. -- Modify the `setResultConverter` to return something more meaningful than `true` and `false`. maybe a record with `allChangesResolved: boolean` and `allExternalChangesAccepted: boolean`. These can then be used for the subsequent checks and steps.


I am not sure about: Remove the undoManager thing from `viewModel.applyChanges(); (because I think, it makes no sense in a backuip.

**Review by koppor — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java [hunk 5]
```diff
@@ -20,6 +20,8 @@
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
+import static org.jabref.gui.Globals.stateManager;
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java:23]: Globals is deprecated and shall not be used. Please inject the statemanager in the constructor.

File: src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java (hunk 4 above)
Comment (amrithdas) [reply src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java:109]: can you please give some clarity on what cases it will not work?
from what I understand even if BackupUIManager calls it this should work right?
also I didn't get the point of implementing checks after `showCustomDialogAndWait `. is it to stop the file monitoring if changes are resolved and accepted?

Comment (koppor) [reply src/main/java/org/jabref/gui/collab/ExternalChangesResolverViewModel.java:109]: OK, I tried. Deleted entry "Corti_2009". Waited until backup is written. Closed JabRef (no saving). Deleted `.bak-discared` file. Started JabRef. Denied "Deleted entry Corti_2009". Selected Edit/undo. Removed the asterisk, but does not remove the entry itself. Which is kind of OK. (The reason is `BibDatabaseContext originalDatabase = originalParserResult.getDatabaseContext();`) - undo/redo has to be done at `showReviewBackupDialog`. - Future work needs to work on this - and pass the changes from `DatabaseChangesResolverDialog` back so that they can be ported to the library -- or we just accept that undo/redo does not work here ^^

---

The issue is different: In the case of a backup, the dialog displays changes introduced by the backup. If all (!) changes are rejected, there is no change in the file (and no asterisk has to be added). Reason: it is the BACKUP file, not the file on disk. Thus, the logic is different than from the file on disk.

Idea to solve this: Pass the changes from `ExternalChangesResolverViewModel` up to `DatabaseChangesResolverDialog`, where the `EasyBind.subscribe` in initialize stores it into a local variable. (`applyChanges` is removed from `ExternalChangesResolverViewModel`). The `resultConverter` (of `DatabaseChangesResolverDialog`) returns the changes. The caller in `DatabaseChangeMonitor` and `BackupUIManager` can handle appropriately. The code of `applyChanges` from `ExternalChangesResolverViewModel` moves there. I know, that 3 lines of code will be duplicated, but I accept hat. In the case of the Backupmanager, there is no need to `resetChangedProperties()` in the case of no changes - the library is not changed directly after loading.

**Comment by koppor** [comment]
@amrithdas May I ask whether you could find time to continue working on this? Seems to be short before completion?

**Comment by amrithdas** [comment]
@koppor yes I'm almost done with the changes, will upload by weekend.

**Comment by koppor** [comment]
> @koppor yes I'm almost done with the changes, will commit by weekend.

I hope your hard disk (and you) will stay in good health.

In open source projects, you can push early and mark the pull request as draft to indicate you want to do a double check later...

**Comment by koppor** [comment]
@amrithdas Oh, a force-push. Now, all changes are gone 😥. I hope, you will find the changes somewhere. Take your time! -- Side note: I recommend using `gitk` to check the local state versus the remote state. One can follow the tutorial at https://lostechies.com/joshuaflanagan/2010/09/03/use-gitk-to-understand-git/ to get a deeper understanding.

And I feel sorry for causing any pressure. This should be a fun project with learning possibilities 😅.

**Comment by amrithdas** [comment]
@koppor I did force-push to sync the repo, I have committed the latest changes, please have a look.
Haven't tested backup functionality, will check it and update. :smiley:

**Comment by koppor** [comment]
@amrithdas Please also check the automated checks of GitHub. It shows red crosses at CHANGELOG.md and checkstyle. For the first, I assume, you have not seen that JabRef did a release meanwhile and your CHANGELOG.md entry should be moved. Regarding checkstyle, maybe you did not call autoformat - or we have some issues at the IDE configuraiton.

File: src/main/java/org/jabref/gui/dialogs/BackupUIManager.java [hunk 6]
```diff
@@ -91,13 +99,21 @@ private static Optional<ParserResult> showReviewBackupDialog(
                         originalDatabase, "Review Backup"
                 );
                 var allChangesResolved = dialogService.showCustomDialogAndWait(reviewBackupDialog);
-                if (allChangesResolved.isEmpty() || !allChangesResolved.get()) {
-                    // In case not all changes are resolved, start from scratch
-                    return showRestoreBackupDialog(dialogService, originalPath, preferencesService, fileUpdateMonitor);
+                LibraryTab saveState = stateManager.activeTabProperty().get().get();
+                changes.stream().filter(DatabaseChange::isAccepted).forEach(change -> change.applyChange(ce));
+                ce.end();
```
Comment (koppor) [inline src/main/java/org/jabref/gui/dialogs/BackupUIManager.java:104]: Add the CE to the undomanager

```java
undoManager.addEdit(ce);
```

Initialize the ce right before line 103. This variable is more local.

File: src/main/java/org/jabref/gui/dialogs/BackupUIManager.java [hunk 7]
```diff
@@ -91,13 +99,21 @@ private static Optional<ParserResult> showReviewBackupDialog(
...
+                if (allChangesResolved.get()) {
+                    if (reviewBackupDialog.areAllChangesDenied()) {
```
[the remark this answers is not in the document]
Comment (amrithdas) [reply src/main/java/org/jabref/gui/dialogs/BackupUIManager.java:106]: `//Accepting external changes to bib files are handled here else it will mark file as unsaved.`
This comment would be fine right?

**Comment by koppor** [comment]
@amrithdas Please, please, please also check the red crosses here in the GitHub pipeline. There are complains for `CHANGELOG.md`. I think, you need to move your CHANGELOG.md entry, because we released a new version while you were working on the pull request.

**Comment by amrithdas** [comment]
@koppor I have made the requested changes please review.

**Comment by koppor** [comment]
@amrithdas I do not have push rights to your branch. Thus, I will merge and apply my small fixes in `main`.

**Review by koppor — APPROVED** [review]
Looks good now.

I would not use the `final` keyword. I would also position the comments at the right place. I will do that as follow-up

**Comment by amrithdas** [comment]
> Looks good now.
> 
> I would not use the `final` keyword. I would also position the comments at the right place. I will do that as follow-up

Okay great :smiley:

**Comment by koppor** [comment]
> > Looks good now.
> > I would not use the `final` keyword. I would also position the comments at the right place. I will do that as follow-up
> 
> Okay great 😃

Follow-up: https://github.com/JabRef/jabref/commit/3c17a1697785d16039fef045ccc31455d707aaac
