### PR TITLE
Fix saving on network drive under macOS

### LINKED ISSUE #10452: Could not save library
### JabRef version

5.10 (latest release)

### Operating system

macOS

### Details on version and operating system

macOS 12.6

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I add some articles to my new library
2. CMD + S to save the library
3. The following error is returned:
```
org.jabref.logic.exporter.SaveException: Problems saving: java.io.IOException: Operation not supported
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:266)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:215)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.saveAs(SaveDatabaseAction.java:131)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:186)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:75)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveAction.execute(SaveAction.java:41)
	at org.jabref@5.10.60000/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.jabref.merged.module@5.10.60000/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.jabref.merged.module@5.10.60000/org.controlsfx.control.action.Action.handle(Action.java:64)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(GlobalMenuAdapter.java:150)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234)
Caused by: java.io.IOException: Operation not supported
	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:99)
	at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1487)
	at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
	at org.jabref@5.10.60000/org.jabref.logic.exporter.AtomicFileOutputStream.<init>(AtomicFileOutputStream.java:109)
	at org.jabref@5.10.60000/org.jabref.logic.exporter.AtomicFileOutputStream.<init>(AtomicFileOutputStream.java:83)
	at org.jabref@5.10.60000/org.jabref.logic.exporter.AtomicFileWriter.<init>(AtomicFileWriter.java:29)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:243)
	... 28 more


```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #10452

Workaround for https://bugs.openjdk.org/browse/JDK-8167023

Tested under macOS with a windows smb network share

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/exporter/AtomicFileOutputStream.java [hunk 1]
```diff
@@ -106,7 +106,12 @@ public AtomicFileOutputStream(Path path) throws IOException {
         try {
             // Lock files (so that at least not another JabRef instance writes at the same time to the same tmp file)
             if (out instanceof FileOutputStream stream) {
-                temporaryFileLock = stream.getChannel().lock();
+                try {
+                    temporaryFileLock = stream.getChannel().tryLock();
+                } catch (IOException ex) {
+                    LOGGER.warn("Could not acquire file lock. Maybe we are on a network drive?", ex);
```
Comment (koppor) [inline src/main/java/org/jabref/logic/exporter/AtomicFileOutputStream.java:112]:
```suggestion
                    // workaround for https://bugs.openjdk.org/browse/JDK-8167023
                    LOGGER.warn("Could not acquire file lock. Maybe we are on a network drive?", ex);
```

**Review by koppor — CHANGES_REQUESTED** [review]
Looks good - just wanted to add the reason for the try/catch.
