### PR TITLE
Fixed exception about missing custom css file

### LINKED ISSUE #7177: Java Exception when trying to open the preferences with missing custom theme
> `JabRef 5.2--2020-12-09--d1fb9e2`

When trying to open the preferences dialogue a java exception occurs:
`Cannot load org.jabref.gui.preferences.preferencesdialog`

### PR DESCRIPTION
**Pull request by docrjp**
Fixes #7177 "Java Exception when trying to open the preferences with missing custom theme"

After some testing I found that there two main paths that could result in the same failure: the CSS file being missing before application start, and changing the name of the CSS file while the application is running. To resolve the latter, I think the best approach is to check the custom CSS file exists.

This is already done for the Theme as used for most of the application, however the Preview Viewer has it's own CSS URL logic.

Rather than add file checking logic to the Preview Viewer, I have refactored and moved the theme logic of Preview Viewer into Theme, so that all CSS URL logic is encapsulated in that class. I have also put the logic that checks that the URL is valid and filters it to an Optional.empty() into one new method, additionalCssToLoad(), in place of the field of the same name. This ensure that the file existence check is performed in all cases, rather than just at construction of the Theme object.

I have kept the Optional<URL> field so there should be no overhead to this approach for the built in themes, and only the minor and necessary overhead of file existence checking for the custom theme.

For manual testing I checked:

- previews and overall appearance for default theme are correct, after restart
- previews and overall appearance for dark theme are correct, after restart
- previews and overall appearance with a custom theme with a valid name are correct, after restart
- live changes to the custom theme still work, in general and for preview
- rename custom theme so that the configured theme is no longer correct, **before application start**. The preview is no longer themed but there is no error.
- the preview theme is restored when the filename is restored to the configured value, without restarting the application
- Restart. Rename custom theme so that the configured theme is no longer correct, **while application is running**. The preview remains themed (typically sized CSS themes are data URL embedded and so survive file removal).

These tests were run both with the Gradle run task, and on the built binary (rationale: gradle presents the dark theme as a file, while the binary has it built in on a jrt: URL, so the results could be different).

PR tasks:

- [X] Change in CHANGELOG.md described (if applicable)
- [X] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [X] ~~Screenshots added in PR description (for UI changes)~~ (N/A)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/util/Theme.java [hunk 1]
```diff
@@ -47,31 +54,31 @@ public Theme(String path, PreferencesService preferencesService) {
...
-            } else {
-                additionalCssToLoad = Optional.empty();
-                LOGGER.warn("Cannot load css {}", path);
-            }
+            this.cssUrl = Optional.ofNullable(url);
+        }
+    }
+
+    private Optional<URL> additionalCssToLoad() {
+        if (type == Type.CUSTOM && !Files.exists(pathToCss)) {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/util/Theme.java:78]: Can you add some log for the case that the file doesn't exists?

**Review by calixtus — APPROVED** [review]
Hi, thanks for your work already!
I like your changes very much and i think they not only fix a bug, but also contribute to code quality. Just one remark so far.

About testing file changes: I believe that this would take way more effort, and i have absolutely no experience with this sort of checks, but there are some tests for FileUtil.class that work on temp directories that are maybe helpful...

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 1 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:78]: Good shout, I will add that logging and also for malformed URL since both cases previously were covered by some logging.

Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:80]: Logging added.

I've also added a unit test for the Theme class. The installCss() methods are still uncovered: a few interact with JavaFX concrete classes and use Platform.runLater() so would need more effort to mock nicely. Also, I haven't covered error handling of malformed URLs. I hit into a funny thing, that on Windows, colons in paths are always interpreted as drive names. So file path processing fails before we get to URL handling. I think I'll raise a separate issue because this has led me to realise that Windows drive handling is another edge case to deal with.

Still, this gets us to 53% coverage of the Theme class 🎉

Comment (calixtus) [reply src/main/java/org/jabref/gui/util/Theme.java:80]: Take your time, there is no rush.
We are really happy, that you take care of this issue and also care about test coverage.

File: src/main/java/org/jabref/gui/util/Theme.java [hunk 2]
```diff
@@ -33,46 +43,137 @@
 
     public static final String BASE_CSS = "Base.css";
 
+    private static final int MAX_IN_MEMORY_CSS_LENGTH = 48000; // 48 kilobytes. Base theme is 33k, Dark adds < 4k.
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/util/Theme.java:46]: Can you provide a reference to the docs for that facts?

**Review by Siedlerchr — APPROVED** [review]
Thanks for the work and also thanks for adding a test. Is this ready now?

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 2 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:46]: Do you mean, adding to the comment in Theme.java, a reference to how I determined Base.css and Dark.css are 33k and 4k respectively?

Or do you mean, the user guide should document how the Preview handles errors when the CSS is large?

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/util/Theme.java:46]: No, sorry for beein unclear, just a reference to the java spec/javadoc where the limit is defined, in case that changes in the future

Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: No worries! I've enhanced the Javadoc on this field and on the Theme class, and linked it up with references to the files and the jabref documentation for custom themes. Hopefully this is enough to maintain the value? Only other thing I can think to do, is reference it in the Base and Dark CSS files, but I feel that CSS authors shouldn't have to worry about it, as the maximum isn't a hard limit, just a best effort to catch some edge cases in which uncaught exceptions may occur even with file existence checks.

**Comment by docrjp** [comment]
> Thanks for the work and also thanks for adding a test. Is this ready now?

I've justed add some test coverage for theme live reloading, the change to it was minor but this should cover all the changes now. All being well from CI pipeline I will remove the draft status 👍

**Comment by docrjp** [comment]
I get an NPE with the file watching ThemeTest in the github CI pipeline that I don't get when running the test locally, and the only thing I can see on the line with NPE that could do that is closing the WatchService, which functionally looks correct, but perhaps is open to memory consistency issues. So, I've added volatile to the WatchService and I take a local copy to null check before closing. In commit 9d77318184c30f934343b0f9a6760817b0e53976

**Comment by docrjp** [comment]
I've put a condition on that last test I've added, so it only runs on Windows. I'll try to figure out why it is behaving differently in the pipeline without holding up this PR, as it is very likely a test artifact -- it's quite complicated with needing to run up the file watching service and mock the JavaFX Scene.

I've given a final quick manual test after the last commit.

Fetcher Tests fail intermittently with 429 Too Many Requests, probably just because I'm hammering the CI and this is usual. I guess the failing of the AUTHORS is usual for a first contribution, so nothing to worry about.

Only thing that I am unsure of is why the Mac OSX create installer task fails consistently, if that's something I need to fix let me know.

From my perspective, happy for this to be given a final review and merge 👍

**Comment by Siedlerchr** [comment]
@docrjp  The mac os will always fail because it requires some keys/secrets. However, GithubAction does not pass these to forks. Linux and file watching/locking is a complex issue, Linux file system works completely different from windows, e.g. there is no kind of lock for a file.
Fetcher test are another, non-related issue, only relevant if you worked on them.

File: src/test/java/org/jabref/gui/util/ThemeTest.java [hunk 3]
```diff
@@ -0,0 +1,258 @@
...
+        AppearancePreferences appearancePreferences = mock(AppearancePreferences.class);
+        when(this.preferencesMock.getAppearancePreferences()).thenReturn(appearancePreferences);
+        when(appearancePreferences.shouldOverrideDefaultFontSize()).thenReturn(false);
+    }
+
+    @Test
+    public void lightThemeUsedWhenPathIsBlank() {
+        Theme blankTheme = new Theme("", preferencesMock);
+        assertEquals(Theme.Type.LIGHT, blankTheme.getType());
+        blankTheme.additionalStylesheet().ifPresent(location -> fail(
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/gui/util/ThemeTest.java:46]: `assertEquals(Optional.empty(), blankTheme.additionalStylesheet())` should work as well.

File: src/main/java/org/jabref/gui/util/Theme.java [hunk 4]
```diff
@@ -127,11 +260,35 @@ private void addAndWatchForChanges(Scene scene, URL cssFile, FileUpdateMonitor f
...
+    }
+
+    /**
+     * This method allows callers to obtain the theme's additional stylesheet.
+     *
+     * @return called with the stylesheet location if there is an additional stylesheet present and available. The
+     * location will be a local URL. Typically it will be a {@code 'data:'} URL where the CSS is embedded. However for
+     * large themes it can be {@code 'file:'}.
+     */
+    public Optional<String> additionalStylesheet() {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/util/Theme.java:288]: I would rename it to `getAdditionalStylesheet`

File: src/main/java/org/jabref/gui/util/Theme.java [hunk 5]
```diff
@@ -33,45 +46,164 @@
...
+        }
+
+        return cssUrl;
+    }
+
+    /**
+     * Creates a data-embedded URL from a file or resource URL
+     * @param url the URL of the resource to convert into a data: url
+     */
+    private void loadCssToMemory(URL url) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/util/Theme.java:188]: Did you noticed significant performance improvements with this method? I was hoping that JavaFX internally caches the css file anyway.

File: src/main/java/org/jabref/gui/util/Theme.java [hunk 6]
```diff
@@ -33,45 +46,164 @@
...
-    private final Path pathToCss;
-    private final Optional<URL> additionalCssToLoad;
+
+    /* String, Path, and URL formats of the path to the css. These are determined at construction.
+     Path and URL are only set if they are relevant and valid (i.e. no illegal characters).
+     In general, use additionalCssToLoad(), to also ensure file existence checks are performed
+     */
+    private final String cssPathString;
+    @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
+    private final Optional<Path> cssPath;
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/util/Theme.java:87]: The `cssPath` variable is only used in the constructor (and in the `additionalCssToLoad` method, which is also only called in the constructor) if I see this correctly. Thus, I would propose to only keep the `cssPathString` and `cssUrl` variables on the class level.

File: src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker [hunk 7]
```diff
@@ -0,0 +1 @@
+mock-maker-inline
```
Comment (tobiasdiez) [inline src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker:1]: Can you add a comment to this file indicating its purpose (if this is possible).

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
Thanks a lot for your work. This is a very nice improvement. 

A few nitpickings and questions from my side.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 5 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:188]: I think it does internally cache the CSS for Scenes at least, since most things continue to render OK when the CSS file is deleted. Although, if the file is deleted, then some dialog boxes like the About page and the Preferences are not themed. However, previews work differently. Indeed, the Preview Viewer is the only consumer of the getter that exposes the additional stylesheet, everything else uses installCss(). The Preview Viewer uses WebEngine, and that has its own CSS handling quite different from Scene. This is where the bug was -- the preferences dialog would thrown an uncaught exception because it has a preview tab.

Now, because WebEngine works differently and had a bug in how it handled CSS files in jmod files, we already had that the dark theme loaded into memory as a base-64 encoded URL. There was a TODO to remove that when the bug in WebEngine is fixed. However, rather than treating it as a temporary workaround, I have made it useful. By encoding custom themes as well as the dark theme into a URL, the WebEngine is less prone to error when the CSS file is removed.

As the dark theme already did this, I figured it was safe to take this approach and perform OK. However, performance wasn't the main motivator.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 4 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:288]: Will do!

File: src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker (hunk 7 above)
Comment (docrjp) [reply src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker:1]: I will see what is possible. The comment will be something like "This Mockito extension allows us to mock final methods, which are very common in OpenJFX".

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 5 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/util/Theme.java:188]: Thank for the explanation! Since this code is somewhat of a hack (I remember I copy&pasted it from some JavaFX method), I would like to remove it as soon as the jmod issue is fixed (which should be JavaFX 15 or 16). So could you please readd the comment that this should be removed in the future. Thanks

File: src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker (hunk 7 above)
Comment (docrjp) [reply src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker:1]: Interesting.!

At least in earlier Mockito documention it is very clear that exactly one line is expected in this file, which suggesting commenting is not possible. However, it turns out OK to have the comment starting with a '#' character. Double slash causing mockito to fail to initialize as it tries to read the comment as an extension. Commenting out the extension itself with a '#' does what you'd expect -- disables the extension causing the test that requires mocking of a final method to fail.

I might approach the Mockito community and ask them to document this feature, or point me in the right direction if I missed the documentation somehow, as it's very useful to explain what the file does! It would give us peace of mind, if we knew it was fully intended.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 4 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: This has now been done.

By the way -- is there a good way for me to include the diff inline here, without just copying the diff? Is that something you would expect?

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 5 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:197]: TODO added back onto loadCssToMemory() with a lot of detail, to make sure we resolve it without breaking this fix

File: src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker (hunk 7 above)
Comment (docrjp) [reply src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker:2]: Comment added and pushed

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 4 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/util/Theme.java]: You can link to a diff like this, but that's the best I know.

https://github.com/JabRef/jabref/pull/7292/files#diff-949225e5594af6c25bd85b337a78e60bece8ecfbeba42f6c260ed8b92a6a646bR18-R19

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 6 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:87]: I didn't get to this one yet, but it's up next.

I agree I didn't quite like all these class level fields.

Only intention behind it, was to avoid duplicate logging when the path is not valid. File existence can change but for a given file system -- e.g. Windows file system, a path is either valid or not. So, it only needs checking once (when converting path string to a Path object). a realistic example would be trying to put a http:// URL into the box, on a Windows machine. I gave this a go as I was curious as to whether URLs would be accepted. It resulted in an uncaught exception, since on Windows ':' is treated as an indication of a drive letter. http not being a valid drive letter! Hence, catching the invalid path exception and logging it.

So to compare the options in brief:

- Path conversion in constructor and stored in class field: less logging but makes the class more complicated with an unnecessary field for LIGHT and DARK themes
- Path conversion into additionalCssToLoad(): will log invalid path each time a Preview Viewer is created, but avoids a field at class level that is only used for CUSTOM themes

I'm very much inclined to agree, that second option is overall better. But just wanted to run my reasoning past you for the current approach -- what do you think?

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 4 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: Does the job, thanks! 😄

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 6 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/util/Theme.java:87]: Yes, I also like the second one better. In addition, one could add a check in the preference window that the path is correct.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 1 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: Thanks for your feedback @calixtus, should I resolve conversations or do I leave that to reviewers?

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 6 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:87]: Then it's agreed, I will make the change to the Path handling.

I figure to add a separate enhancement issue and PR for user input validation in the preferences dialog, which will follow up on this fault fix nicely.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 1 above)
Comment (calixtus) [reply src/main/java/org/jabref/gui/util/Theme.java]: I'd say: If a remark is resolved, it's resolved...

File: src/test/java/org/jabref/gui/util/ThemeTest.java (hunk 3 above)
Comment (docrjp) [reply src/test/java/org/jabref/gui/util/ThemeTest.java]: Updated to use this assertion

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 6 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: This is now done.

The logging for invalid paths is still just in the constructor, as I realised it was better to convert the URL back to Path in additionalCssToLoad(). It is much cleaner now I think.

One last check I would like to do, is to run all the manual tests again with a linked build, as Gradle presents the dark theme as a file for both the test task and the run task.

I guess I can do this by following this guide: https://github.com/JabRef/jabref/blob/master/docs/advanced-reading/jpackage.md

File: src/main/java/org/jabref/gui/util/Theme.java [hunk 8]
```diff
@@ -127,11 +249,35 @@ private void addAndWatchForChanges(Scene scene, URL cssFile, FileUpdateMonitor f
...
+    /**
+     * Provides the raw, configured custom CSS location. This should be a file system path, but the raw string is
+     * returned even if it is not valid in some way. For this reason, the main use case for this getter is to
+     * storing or display the user preference, rather than to read and use the CSS file.
+     *
+     * @return the raw configured CSS location
+     */
+    public String getCssPathString() {
+        return cssPathString;
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/util/Theme.java:268]: Hi @docrjp , I took a closer look into your changes.

I really did not get why you were removing the Path object in your changes.
The Path object in the `java.nio.file` package is just providing this: a simple Path, which is file system independent by design, not linked to a concrete file, but rather just the Path. Abstraction is a major difference between the old-style java io and the nio package. You can test the validity of the Path with Files.exists().

If you are unsure, whether a syntactically correct path is delivered by the PreferencesService: It should deliver a Path optional. I think this was not implemented before, but this would be a good addition. (I'm still in progress of refactoring JabRefPreferences and its surroundings. If possible, PreferencesService should always deliver high abstraction objects instead of raw strings - see ColumnPreferences for example)

I believe using raw Strings here is unnecessary and somewhat inconvenient.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 6 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: I am having a problem with the jlink step of building the binary for manual testing:

After installing wixtoolset I ran the following from the "Creating a binary and debug it" guide:

./gradlew -PprojVersion="5.0.50013" -PprojVersionInfo="5.0-ci.13--2020-03-05--c8e5924" jpackageImage

I got the following error:

> > Task :jlink FAILED
> The module name specified in 'application.mainModule' (null) has not the expected value (org.jabref).
> Error: Modules org.jabref.merged.module and javafx.web export package javafx.scene.web to module org.jabref

I thought I'd try to figure out the build from the CI pipeline instead, and so ran the jlinkZip task instead, but it fails in the same way.

I've tried JDK 14 and 15 with the same result.

Not sure where to go from here?

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 8 above)
Comment (calixtus) [reply src/main/java/org/jabref/gui/util/Theme.java:268]: Digging even deeper, I realized it's still more complicated.

Currently JabRefPreferences is providing the Theme itself. I'm not yet sure, if it should...

Comment (calixtus) [reply src/main/java/org/jabref/gui/util/Theme.java:268]: I thought a little about this. Besides that our complete theme architecture desires some attention and love, I think that keeping three different references in the class will provoke sooner or later unexpected bugs. The best would probably just to work inside the class with URLs and abolish the Path object, only return it, if asked by the prefs.

Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:268]: I don't like it either! But it is making true on design decisions already in place both upstream and downstream of the getter.

**Every** use of the Path getter was immediately converted to a String i.e. throwing away the abstraction.

The constructor of Theme took a String already, passing in magic values of the path for the LIGHT and DARK themes.

In the case of the LIGHT theme, the magic value is an empty string, and therefore an empty Path, which can never be used to open a regular file at all, it just happens to be OK to have an empty Path on Windows/Linux/Mac file systems. Usually an empty path means "current working directory" -- that has no meaningful relationship to the LIGHT theme.

For the DARK theme, there is also some magic. 'Dark.css' is passed to the constructor, it then works backwards: by detecting that the URL is a resource, it guesses that it is the DARK theme, since this is the only theme at present that is stored in the jar. For a binary build, this will never exist, as even though it happens to be a valid Path, it is is never intended to be used as a file system Path. It implies something that isn't true.

Converting this string always to Path is therefore a misleading abstraction. It really fooled me, when I first came to it.

Related to this, is that I didn't want to second guess how the preference service might interact with the "path" string (as I say, it throws away the high level abstraction). Since there was no check for Path validity before, it might well be assuming that the getter always returns a value which when it converts back to a string, reflects the constructor, Changing that to Optional is will make that no longer be true. That could create new bugs, e.g. the path configuration being "lost", at the surprise of the user. It is a behavioural change to introduce Optional to this getter.

To really use the Path consistently as an abstraction, I'd really have to rip up the Theme class, maybe with a factory pattern and removing these magic constructor values, and also look at changing how the preferences uses Theme. That makes the change much bigger and may better be in a separate PR.

Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:268]: How about this plan:

I will create two new issues, for follow up PRs:

- add more built in themes alongside Dark, e.g. a high contrast Dark theme for enhanced accessibility. In this we will eliminate the magic handling specific to Light and Dark theme, allowing for eaisier extensibility to built in themes
- add validation of user input of custom theme file path. In this we will refactor how the Theme and preference interact in relation to paths.

Between these we should be able to get into a good state. Happy to give theme preferences some love!

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 6 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/util/Theme.java]: The issue comes when you have a local jdk with javafx modules installed. Because jabref also brings into the modules, they are duplicate in the module path and therefore clash. For jlink locally you need to have a jdk without included javafx modules. 
You don't need to run this jlink stuff locally. You can run gradlew run for testing or let the CI build the packages. You can download the artifacts from the CI

Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: Aha! That makes a great deal of sense!

Only reason for testing this way, is Gradle presents the dark theme as a file under sec/main/resources rather than jrt URL. So I want to be sure everything still works with a real world binary.

**Review by tobiasdiez — APPROVED** [review]
LGTM. Thanks for the quick follow-up!

I agree, the current theme class needs to be reworked. As a starting point I would suggest to have a `Theme` interface (with install and getCss methods), one implementation in form of a enum for built-in themes (Dark, Light at the moment) and one implementation for custom themes based on an external file. The current constructor can then go in the preference class providing the correct theme instance based on the string stored in the preferences.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 6 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java]: Thanks that did the trick! Manual tests repeated and all passed, when running via JabRef.bat on a jlink binary.

File: src/main/java/org/jabref/gui/util/Theme.java (hunk 8 above)
Comment (docrjp) [reply src/main/java/org/jabref/gui/util/Theme.java:268]: I have created issues #7322 and #7323 for follow up.

**Comment by calixtus** [comment]
I agree with @tobiasdiez , we should merge this one now, as this is an improvement already, bug has been fixed and especially extracting theme logic out of foreign classes is very good, even though the theme architecture is not perfect, but this goes beyond this PR. Codewise looks good also to me, tests have passed, so i'll merge this.

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
Thank you for your work here and for accepting our commnts about it. I hope you liked working on JabRef. We would be happy if you decide to continue to contribute.

**Comment by docrjp** [comment]
> Thank you for your work here and for accepting our commnts about it. I hope you liked working on JabRef. We would be happy if you decide to continue to contribute.

Absolutely!

Thank you all @Siedlerchr @calixtus @tobiasdiez for your valuable feedback and support, all of it was very much appreciated, it's a great community here!

I will definitely keep contributing. Jabref caught my eye on CodeTriage because I used over 10 years ago as a postgraduate. In private industry since and now wanting to give back, it couldn't be more perfect! 😄
