### PR TITLE
Extended Hints - Alternative to #4971

### LINKED ISSUE #3599: Disable extended help in the search field
JabRef version <4.1> on <Linux 4.4.103-18.41-default amd64, Java 1.8.0_151>

If I start searching a database, an extended help window appears telling me that it would be possible to modify my search expression. This is rather boring when using a large database. Shouldn't there be a way to disable this feature?

Steps to reproduce:

1.   Open an existing database.
2.   Begin typing into the search window.
3.   Unwanted help appears.

### PR DESCRIPTION
**Pull request by calixtus**
fixes #3599 - conflicts with #4971 
I realized, talking about changes without presenting a possible solution is just lame.

What do you think?

Sorry about these ugly commit-msgs. I promise improvement.

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/resources/l10n/JabRef_en.properties [hunk 1]
```diff
@@ -533,6 +533,8 @@ Link=Link
 Listen\ for\ remote\ operation\ on\ port=Listen for remote operation on port
 Load\ and\ Save\ preferences\ from/to\ jabref.xml\ on\ start-up\ (memory\ stick\ mode)=Load and Save preferences from/to jabref.xml on start-up (memory stick mode)
 
+Show\ helpful\ tooltips=Show helpful tooltips
```
Comment (Siedlerchr) [inline src/main/resources/l10n/JabRef_en.properties]: "Show tooltips for advanced search options" would be more clear

Comment (calixtus) [reply src/main/resources/l10n/JabRef_en.properties]: Thanks for your Comment.
My latest Idea was to use this option to enable or disable other tooltips (or even create new ones) as well. In this case, the tooltip in GlobalSearchBar.java is just a proof of concept.

Suggestions where?

Idk if I should add [WIP] to the title.

Comment (Siedlerchr) [reply src/main/resources/l10n/JabRef_en.properties]: Disabling tooltips globally is a bad idea from a UX perspective.

Comment (calixtus) [reply src/main/resources/l10n/JabRef_en.properties]: I did not mean every tooltip. Only those with extended help.

Comment (tobiasdiez) [reply src/main/resources/l10n/JabRef_en.properties]: I kind of like the idea and would go even on step further: provide an option to toggle advanced help on or off (helpful tooltips, suggestions, additional explanation). Can you please phrase the preference option in that way?

Comment (calixtus) [reply src/main/resources/l10n/JabRef_en.properties]: What do you have in mind?
"Show extended hints and explanation."

But im a bit cautious extending it too much, because of what @adessec [pointed out|https://github.com/JabRef/jabref/issues/3599#issuecomment-355511934]. The tooltips etc. are no replacement for the docs.

(The checkbox in the preferences could have a tooltip as well, explaining what it does... just kidding.)

**Comment by calixtus** [comment]
Did some rewording. I'll take a look into the source the next days to identify, what else could be a extended hint.

Suggestions are very welcome.

File: src/main/resources/l10n/JabRef_en.properties (hunk 1 above)
Comment (tobiasdiez) [reply src/main/resources/l10n/JabRef_en.properties]: "Show extended hints and explanation." sounds good to me, and I would agree that we shouldn't push it too much.

File: src/main/java/org/jabref/gui/search/GlobalSearchBar.java [hunk 2]
```diff
@@ -284,11 +285,14 @@ public void updateResults(int matched, TextFlow description, boolean grammarBase
...
-        tooltip.setMaxHeight(10);
-        searchField.setTooltip(tooltip);
+
+        if (Globals.prefs.getBoolean(JabRefPreferences.SHOW_ADVANCED_HINTS)) {
+            Tooltip tooltip = new Tooltip();
+            tooltip.setContentDisplay(ContentDisplay.GRAPHIC_ONLY);
+            tooltip.setGraphic(description);
+            tooltip.setMaxHeight(10);
+            searchField.setTooltip(tooltip);
+        }
```
Comment (davidemdot) [inline src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: Please add these lines of code to prevent the last tooltip from displaying again after the user unchecks this preference. Thanks!

```
        else {
            searchField.setTooltip(null);
        }
```

Comment (davidemdot) [reply src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: tooltip

Comment (calixtus) [reply src/main/java/org/jabref/gui/search/GlobalSearchBar.java]: Thanks for your note.
I was just refactoring this method a little bit, creating a seperate method (updateTooltip), since there is no tooltip (and no hint) at all, when jabref just started. I will pick it up.

**Comment by calixtus** [comment]
Sorry about the force-push. I think i still dont have my git-environment set up right...

However, i tried to comletely seperate the logic about whats in the tooltip and about if it's visible or not, and to avoid unnecessary function calls as well.

About the switchable visibility in the PreferencesDialog: im really not sure if i did this right, because i did not see another proper way to update the visibility. I tested it, it works fine, but is this intended?

**Comment by Siedlerchr** [comment]
>About the switchable visibility in the PreferencesDialog: im really not sure if i did this right, because i did not see another proper way to update the visibility. I tested it, it works fine, but is this intended?

Not sure what you mean but codewise lgtm so far

**Comment by calixtus** [comment]
My question is about the call to "updateAfterPreferenceChanges();" in "storeAllSettings();" i put in. UpdateAfter was always called after resetting or importing any preference, but was not after saving and closing. I inserted the call there, but i don't really understand, if this is really the right place. I fear not. ;-)

File: CHANGELOG.md [hunk 3]
```diff
@@ -64,7 +64,7 @@ We refer to [GitHub issues](https://github.com/JabRef/jabref/issues) by using `#
 - We added an option in the settings to set the default action in JabRef when right clicking on any entry in any database and selecting "Open folder". [#4763](https://github.com/JabRef/jabref/issues/4763)
 - The Medline fetcher now normalizes the author names according to the BibTeX-Standard [#4345](https://github.com/JabRef/jabref/issues/4345)
 - We added an option on the Linked File Viewer to rename the attached file of an entry directly on the JabRef. [#4844](https://github.com/JabRef/jabref/issues/4844)
-
+- We added an option in the preference dialog box that allows user to enable helpful tooltips.
```
Comment (Siedlerchr) [inline CHANGELOG.md]: please add the issue number lilke in the other entries

**Comment by Siedlerchr** [comment]
Ah now I  understand what you mean. Not it does not make sense to add it there, cause it will call setValues on each tab -> setting the values for the controls in all preferences tabs. Only useful after you reseted to default, so that all checkboxes etc show default values or after the import of new prefs so that the gui state reflects the prefs state. 

When you save you don't need to set the values again, cause you already manually changed the gui states of the controls.

**Comment by Siedlerchr** [comment]
Lgtm now! Is this ready now?

**Comment by calixtus** [comment]
Yes, I would say so. 
Although there are only two clues that can be hidden now - it is enough for a proof-of-concept.
Further hints can be added together with other pull requests.
