### PR TITLE
Change open last edited dialgo to javafx

### LINKED ISSUE #3799: OSX: With maintable-beta, JOptionPane for the "load backup file"  on startup does not show up and freezes JabRef
I am sure now that this is indeed a problem. I suspect this issue was introduced after we made JabRef an FX application. Now, the initial confirmation dialog if I want to load a `.sav` bibliography does not show up any longer. The window is not hidden and JabRef goes in a waiting loop that I cannot leave.

I believe the issue here is that we still use Swing for the confirmation dialog in 

```
org.jabref.gui.dialogs.BackupUIManager#showRestoreBackupDialog
```
and in some other places too.

How to reproduce:

- System Mac OS X 10.13.3 x86_64, Java 1.8.0_162, maintable-beta branch
- Leave JabRef dirty once so that you have a `.sav` file for your opened bibliography
- Start JabRef either through the IDE, terminal or by double-clicking on the jar.

This issue does not appear on Linux. I have not tested Windows.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #3799 @halirutan  Have a look if this works for you

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/dialogs/BackupUIManager.java [hunk 1]
```diff
@@ -14,20 +12,27 @@
...
-                new StringBuilder()
-                    .append(Localization.lang("A backup file for '%0' was found.", originalPath.getFileName().toString()))
-                    .append("\n")
-                    .append(Localization.lang("This could indicate that JabRef did not shut down cleanly last time the file was used."))
-                    .append("\n\n")
-                    .append(Localization.lang("Do you want to recover the library from the backup file?")).toString(),
-                Localization.lang("Backup found"), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
-
-        if (answer == 0) {
+    public static void showRestoreBackupDialog(DialogService dlgService, Path originalPath) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/dialogs/BackupUIManager.java]: no abbreviations: `dialogService`
