### PR TITLE
Fix for issue 4629

### LINKED ISSUE #4629: Improve telemetry collection
At the moment, mostly user actions involving dialogs are tracked. It would be nice to include also other interactions (especially button presses and tab changes in the entry editor).

This amounts to adding code similar to the following one in the appropriate places:
https://github.com/JabRef/jabref/blob/b411cfbb1c60af09052e17d1780f1cdb770bc4ef/src/main/java/org/jabref/gui/actions/JabRefAction.java#L36-L39

### PR DESCRIPTION
**Pull request by ffffatgoose**
Fix #4629

----

-  distinguish the user action between menu and button
-  reuse the Acitons class to add enum to the description of user action
图片
图片
图片

### CODE REVIEW

File: src/main/java/org/jabref/gui/actions/JabRefAction.java [hunk 1]
```diff
@@ -38,11 +38,39 @@ public JabRefAction(Action action, Command command, KeyBindingRepository keyBind
         }
     }
 
+    /**
+     * especially for the track execute when the action run the same function but from different source.
+     * @param source is a string contains the source, for example "button"
+     */
+    public JabRefAction(Action action, Command command, KeyBindingRepository keyBindingRepository, String source) {
```
Comment (davidemdot) [inline src/main/java/org/jabref/gui/actions/JabRefAction.java]: To avoid duplicating code, I suggest modifying the previous method (the _old_ one), for example:
```
public JabRefAction(Action action, Command command, KeyBindingRepository keyBindingRepository) {
    this(action, command, keyBindingRepository, null);
}
```

This way, you should check in your `JabRefAction()` method if `source` is `null` for tracking an execution:
```
setEventHandler(event -> {
    command.execute();

    if (source == null) {
        trackExecute(getActionName(action, command));
    } else {
        trackExecute(String.format("%sFrom%s", getActionName(action, command), source));
    }
});
```

You also can use `Strings.isNullOrEmpty(source)`, from the `com.google.common.base.Strings` package. Or even an `Optional<String>` type.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/actions/JabRefAction.java]: We have our own StringIsNullorEmpty methd in org.jabref.model.StringUtil

**Comment by ffffatgoose** [comment]
just change the JabRefAction as your suggestion :)

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 2]
```diff
@@ -1240,6 +1240,12 @@ public EditAction(Actions command) {
             this.command = command;
         }
 
+        @Override
+        public String toString() {
+            // TODO Auto-generated method stub
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/JabRefFrame.java]: Please remove the comment

File: src/main/java/org/jabref/gui/actions/ActionFactory.java [hunk 3]
```diff
@@ -74,7 +74,7 @@ private static Label getAssociatedNode(MenuItem menuItem) {
     }
 
     public MenuItem configureMenuItem(Action action, Command command, MenuItem menuItem) {
-        ActionUtils.configureMenuItem(new JabRefAction(action, command, keyBindingRepository), menuItem);
+        ActionUtils.configureMenuItem(new JabRefAction(action, command, keyBindingRepository, "Menu"), menuItem);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/actions/ActionFactory.java]: Could you please create a new enum for the `Menu` and `Button` constants (I don't like magic strings).

File: src/main/java/org/jabref/gui/actions/Actions.java [hunk 4]
```diff
@@ -3,7 +3,7 @@
 /**
  * Global String constants for GUI actions
  */
-@Deprecated
+//@Deprecated
```
[the remark this answers is not in the document]
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/actions/Actions.java]: Yes, please leave the deprecated statement (and try to avoid using this enum).

File: src/main/java/org/jabref/gui/actions/JabRefAction.java [hunk 5]
```diff
@@ -23,11 +24,23 @@ public JabRefAction(Action action, KeyBindingRepository keyBindingRepository) {
...
         this(action, keyBindingRepository);
 
         setEventHandler(event -> {
             command.execute();
-            trackExecute(getActionName(action, command));
+            if (StringUtil.isNullOrEmpty(source)) {
+                trackExecute(getActionName(action, command));
+            } else {
+                trackExecute(getActionName(action, command) + "From" + source);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/actions/JabRefAction.java]: The ApplicationInsights library that we use supports a special way to submit additional details (which I completely forgot until 5 mins ago): https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#properties
Could you please send the `source` as a property please.
https://github.com/JabRef/jabref/blob/7561724b191e890d8687eeb863bf8f0a59a516e0/src/main/java/org/jabref/gui/JabRefFrame.java#L1016-L1022

File: src/main/java/org/jabref/gui/actions/JabRefAction.java [hunk 6]
```diff
@@ -42,7 +55,15 @@ private String getActionName(Action action, Command command) {
...
-            return command.getClass().getSimpleName();
+            String ans = command.getClass().getSimpleName();
+            if (ans.contains("OldDatabaseCommandWrapper")) {
+                OldDatabaseCommandWrapper tmp = (OldDatabaseCommandWrapper) command;
+                return tmp.getActions().toString();
+            } else if (ans.contains("EditAction")) {
+                return command.toString();
+            } else {
+                return command.getClass().getSimpleName();
+            }
```
Comment (davidemdot) [inline src/main/java/org/jabref/gui/actions/JabRefAction.java]: I have been testing this method and there is a small bug in some `EditAction` cases (it shows `org.jabref.gui.entryeditor.SourceTab$EditAction@56048e40FromMenu`). Due to there are still many classes that use `Actions` and `OldDatabaseCommandWrapper`, it is a bit complicated to deal with all of them, but I think that something like this should work...

```
} else {
    String commandName = command.getClass().getSimpleName();
    if (command instanceof OldDatabaseCommandWrapper || commandName.equals("EditAction")) {
        return action.toString();
    } else {
        return commandName;
    }
}
```
Just a proposal, please adapt it in your own way :"D

**Comment by LinusDietz** [comment]
Hey @ffffatgoose, it would be awesome if you could have a look at the comments and find some time to incorporate them in the PR or discuss them in the comments in case you disagree.

**Comment by ffffatgoose** [comment]
I feel very sorry to delay for so long. I have some question for the class `Actions`. Below are the codes of button creation in the main frame of GUI. As the Javadoc told, `OldDatabaseCommandWrapper` and `Actions` is deprecated, however, they are still in use…… 
https://github.com/JabRef/jabref/blob/9daa645ccb213853b2b42d5f562db60933405114/src/main/java/org/jabref/gui/JabRefFrame.java#L529-L541
The input parameter is in the form of `Actions`, so I reuse the class to return the exact actionname of user action. Waiting for suggestions :D

**Comment by ffffatgoose** [comment]
I feel confused about the checkstyle error……Ask for some help
图片

**Comment by Siedlerchr** [comment]
@ffffatgoose  This is not related to your changes, it's a problem in the master branch. #5182

**Comment by calixtus** [comment]
Hi @ffffatgoose . JabRef is in the middle of converting the gui from the old swing-controls to javafx (see PR #4894 ) and also refactoring the codebase to the MVVM-pattern. This is why Actions, OldCommandWrapper etc. are deprecated, but are still used, since not everything is already refactored. This will take time.
To bring some relief from confusion, the controlsFX-library brings its own Action-Class, which is different from the StandardActions-enum and the deprecated Actions-enum. The mvvmFX-ActionClass includes just the EventHandler, the StandardActions-Enum of JabRef (and the Action-Interface) includes only the information about the action (Text, Icon etc.). Since not everything is converted yet, most of the menuitems still use the OldDatabaseWrapper-Stuff.

About your checkstyle-issue: I was able to reproduce it with the vanilla-sources. I think it has something to do with the gradle-build-script and some recent updates of the junit-library. Would be probably the best to create a new issue in the issuetracker on github.

**Comment by Siedlerchr** [comment]
@ffffatgoose  @calixtus  The checkstyle problem on the master should be gone now

**Comment by ffffatgoose** [comment]
get it~ I only used the class `Actions` in the place that the input parameter is in the form of `Actions`, like this:
https://github.com/ffffatgoose/jabref/blob/92b007ecaf0725932a99d5c30134ba77e53922d8/src/main/java/org/jabref/gui/actions/OldDatabaseCommandWrapper.java#L54-L57
Therefore, I think it's no use to add a new enum for it. Is there and else problem I should solve or it is necessary to change my way to solve this?  TvT

**Comment by Siedlerchr** [comment]
@davidemdot  Could you take a second look if this is ready?

**Comment by stefan-kolb** [comment]
@tobiasdiez Do you think this is fine to merge?

**Comment by tobiasdiez** [comment]
Yes, looks good to me! Thanks again for your contribution!
