### PR TITLE
Respect OS language at NativeDesktop#getDefaultFileChooserDirectory

### LINKED ISSUE #8010: Respect localization for main directory (e.g., `~/Dokkumente`)
### JabRef version

5.3 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

ArchLinux linux-lts

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

~1. Open the `preference~
~2. change any option~
~3. bug shows~
~4. 2021-08-21 18-13-16屏幕截图~

See https://github.com/JabRef/jabref/issues/8010#issuecomment-1531526339

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

### PR DESCRIPTION
**Pull request by koppor**
Fixes #8010 - especially https://github.com/JabRef/jabref/issues/8010#issuecomment-1531526339

In Germany, the default "documents" folder is `~/Dokumente`. Either we mirror all translations in JabRef - or we use `FileSystemView.getFileSystemView().getDefaultDirectory().getPath()`. (Source: https://stackoverflow.com/a/32914568/873282)

---

Follow-up to https://github.com/JabRef/jabref/pull/9835: This PR is now using a branch in JabRef's main repo so that a) there are builds and b) other devs can easily update the code, too.

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Tracked down the implementation:

FileSystemView etc.. returns

        File f = (File)ShellFolder.get("fileChooserDefaultFolder");

        https://github.com/openjdk/jdk/blob/fc76687c2fac39fcbf706c419bfa170b8efa5747/src/java.desktop/share/classes/sun/awt/shell/ShellFolderManager.java#L68-L76 
        
        There is only a shellFolder implementation for windows

File: src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java [hunk 1]
```diff
@@ -35,7 +35,9 @@ public interface NativeDesktop {
      *
      * @return The path to the directory
      */
-     Path getDefaultFileChooserDirectory();
+     default Path getDefaultFileChooserDirectory() {
+         return Path.of(System.getProperty("user.home"), "Documents");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java:39]: We should check if that directory Documents is existing, otherwise I suggest we simply return user.home

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 2]
```diff
@@ -20,6 +21,7 @@
 import org.jabref.gui.util.StreamGobbler;
 import org.jabref.logic.l10n.Localization;
 
+import com.microsoft.applicationinsights.core.dependencies.apachecommons.io.IOUtils;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/desktop/os/Linux.java:24]: This looks like the wrong import

**Comment by koppor** [comment]
This should be tested by someone on Linux. I also enabled the debugger, so please check `log.txt` or the Log window in JabRef.

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 3]
```diff
@@ -182,7 +181,8 @@ public Path getDefaultFileChooserDirectory() {
         // See https://www.freedesktop.org/wiki/Software/xdg-user-dirs/ for details
         try {
             Process process = new ProcessBuilder("xdg-user-dirs", "DOCUMENTS").start();
-            List<String> strings = IOUtils.readLines(process.getInputStream(), StandardCharsets.UTF_8);
+            List<String> strings = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8))
+                    .lines().toList();
             String documentsPath = strings.get(0);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/desktop/os/Linux.java:186]: I would add a check that the list is not empty

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 4]
```diff
@@ -171,9 +172,34 @@ public Path getApplicationDirectory() {
...
-        );
+        String xdgDocumentsDir = System.getenv("XDG_DOCUMENTS_DIR");
+        if (xdgDocumentsDir != null) {
+            return Path.of(xdgDocumentsDir);
+        }
+
+        // Make use of xdg-user-dirs
+        // See https://www.freedesktop.org/wiki/Software/xdg-user-dirs/ for details
+        try {
+            Process process = new ProcessBuilder("xdg-user-dirs", "DOCUMENTS").start();
```
Comment (dermalikmann) [inline src/main/java/org/jabref/gui/desktop/os/Linux.java:183]: the script is called `xdg-user-dir` without the s. Its a mess i know. The ""Toolkit"" is called `-dirs` but the script that you actually run is called `-dir`

Comment (dermalikmann) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:183]: I tested it anyways by coping the script with the modified name into my path, and it successfully puts `/home/<USER>/Dokumente` into the "Main file directory" box.

**Review by Siedlerchr — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
