### PR TITLE
Fixes issue where Unix crashes when inotify is full

### LINKED ISSUE #6073: Uncaught Exception: "You need to start the file monitor before watching files" when opening a file
JabRef Version 5.0--2020-03-06--b6d6b79 on Debian GNU/Linux 10 (buster)
(installed from .deb file)

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

**What happens:**
After a fresh restart jabref works fine. A few days later jabref refuses to open any bib file, producing an error message:
Uncaugh Exception
java.lang.NullPointerException: You need to start the file monitor before watching files 

After the next restart jabref works again.

I tracked this down to a restriction in the number of files that inotify can watch concurrently.

If that number is reached on a system, jabref wont open files anymore.

The default on debian is quite low...

Users may recognize this when they use "tail -f" and it says:
tail: inotify cannot be used, reverting to polling: Too many open files

Here is a blog-post that describes the mechanism and the fix
https://medium.com/@ivanermilov/how-to-fix-inotify-cannot-be-used-reverting-to-polling-too-many-open-files-bb1c1437dbf

**What should happen:**
Jabref should warn me, that it cannot detect changes to my .bib file by other programs
or even also revert to polling as tail does
but open the file anyway

It would be great if the warning would point me to the right solution

1. sudo sysctl -w fs.inotify.max_user_watches=1
2. sudo sysctl -w fs.inotify.max_user_instances=1
3. touch aNotExistingFile
4. tail -f aNotExistingFile &
5. start jabref
6. open a bib-file

<details>
  <summary>Full Backtrace</summary>
  java.lang.NullPointerException: You need to start the file monitor before watching files
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at org.jabref/org.jabref.gui.util.DefaultFileUpdateMonitor.addListenerForFile(Unknown Source)
	at org.jabref/org.jabref.gui.collab.DatabaseChangeMonitor.lambda$new$0(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref/org.jabref.gui.collab.DatabaseChangeMonitor.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.BasePanel.resetChangeMonitorAndChangePane(Unknown Source)
	at org.jabref/org.jabref.gui.BasePanel.setupMainPanel(Unknown Source)
	at org.jabref/org.jabref.gui.BasePanel.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.importer.actions.OpenDatabaseAction.addNewDatabase(Unknown Source)
	at org.jabref/org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openTheFile$1(Unknown Source)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor.lambda$getJavaFXTask$3(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task.setState(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

</details>

### PR DESCRIPTION
**Pull request by cttillman**
Previously, the program was crashing for Unix users when inotify had reached its max file limit. Since the only way to fix this seems to be to close applications or to edit privileged system files, the proposed solution is to notify the user of the issue and give them the option of continuing usage of the application. Fixes #6073

### CODE REVIEW

File: src/main/java/org/jabref/JabRefGUI.java [hunk 1]
```diff
@@ -104,6 +104,13 @@ private void openWindow(Stage mainStage) {
             }
         });
         Platform.runLater(this::openDatabases);
+
+        if(!(Globals.getFileUpdateMonitor().isActive())) {
+            this.getMainFrame().getDialogService()
+                    .showErrorDialogAndWait("Unable to monitor file changes. Please close files " +
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefGUI.java:110]: Please use `Localization.lang`. See https://devdocs.jabref.org/getting-into-the-code/code-howtos#using-localization-correctly.

File: src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java [hunk 2]
```diff
@@ -29,11 +31,14 @@
 
     private final Multimap<Path, FileUpdateListener> listeners = ArrayListMultimap.create(20, 4);
     private WatchService watcher;
+    private Optional<JabRefException> filesystemMonitorFailure;
```
Comment (koppor) [inline src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java:34]: I think, it's OK to store the exception (for future work).

Comment (cttillman) [reply src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java:34]: What do you mean? I am not sure what the code change is that you are requesting.

File: src/main/java/org/jabref/JabRefGUI.java (hunk 1 above)
Comment (cttillman) [reply src/main/java/org/jabref/JabRefGUI.java]: https://github.com/JabRef/user-documentation/pull/286

File: src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java (hunk 2 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java:34]: This was more a comment to a second reviewer.

File: src/main/java/org/jabref/model/util/DummyFileUpdateMonitor.java [hunk 3]
```diff
@@ -9,12 +8,17 @@
  */
 public class DummyFileUpdateMonitor implements FileUpdateMonitor {
     @Override
-    public void addListenerForFile(Path file, FileUpdateListener listener) throws IOException {
+    public void addListenerForFile(Path file, FileUpdateListener listener) {
```
Comment (koppor) [inline src/main/java/org/jabref/model/util/DummyFileUpdateMonitor.java:11]: The exception was removed here, but not in the interface. I think, it should also be removed here (and the JavaDoc be adapted).

With the current implementation, it does not throw an exception if the file does not exist.

File: src/main/java/org/jabref/JabRefGUI.java [hunk 4]
```diff
@@ -104,6 +104,13 @@ private void openWindow(Stage mainStage) {
             }
         });
         Platform.runLater(this::openDatabases);
+
+        if (!(Globals.getFileUpdateMonitor().isActive())) {
+            this.getMainFrame().getDialogService()
+                    .showErrorDialogAndWait(Localization.lang("Unable to monitor file changes. Please close files " +
```
Comment (koppor) [inline src/main/java/org/jabref/JabRefGUI.java:110]: I think, this has to go in one line so that the localization consistency check works. --> We have all keys in `Localiazation_en.properties` and a check checking all `.java` files whether the key set in the property file matches the language keys used in the code.

Comment (Siedlerchr) [reply src/main/java/org/jabref/JabRefGUI.java:110]: Just run LocalizationConsistencyTest under l10n

File: src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java (hunk 2 above)
Comment (cttillman) [reply src/main/java/org/jabref/gui/util/DefaultFileUpdateMonitor.java:34]: https://github.com/JabRef/user-documentation/pull/286

**Comment by koppor** [comment]
Since this is an important fix, it should not be stalled. @cttillman We hope that you'll include other improvements in JabRef, so we want to share knowledge about the coding ideas in JabRef. The localization is a difficult thing here. Would you mind to fix the localization isse?

grafik

File: src/main/java/org/jabref/JabRefGUI.java (hunk 4 above)
Comment (cttillman) [reply src/main/java/org/jabref/JabRefGUI.java:110]: I added this to Localization_en.properties and LocalizationConsistencyTest passes all 49 checks.
