### PR TITLE
Fix that "Rename and move file" throws file not found exception

### LINKED ISSUE #4307: Rename and move file throws file not found exception
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 

Steps to reproduce:

1. Open entry editor, general tab for an entry with linked file (which is not in the default file directory and not named correctly)
2. Right-click file > "Rename and move"
3. After the file is renamed, JabRef complaints that it cannot find the file (and thus it is not moved into the correct folder). 

Probably, JabRef still thinks the file has its old name although it was just renamed.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes #4307. Moreover, I refactored a bit how files are renamed/moved to the default file directory. This should make it easier to reuse the code.

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/externalfiles/LinkedFileHandler.java [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+    private final LinkedFile fileEntry;
+
+    public LinkedFileHandler(LinkedFile fileEntry, BibEntry entry, BibDatabaseContext databaseContext, FilePreferences filePreferences) {
+        this.fileEntry = fileEntry;
+        this.entry = entry;
+        this.databaseContext = Objects.requireNonNull(databaseContext);
+        this.filePreferences = Objects.requireNonNull(filePreferences);
+    }
+
+    public boolean moveToDefaultDirectory() throws IOException {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/externalfiles/LinkedFileHandler.java]: I don't understand why you duplicate the code of the moveFilesCleanup, is not necessary, as the moveFiles cleanup can also work with a single linked file

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/externalfiles/LinkedFileHandler.java]: Ah I see you refactored this out of the cleanup, But you now have a architecture violation from logic to gui

**Comment by tobiasdiez** [comment]
I'll merge this now so that progress on https://github.com/JabRef/jabref/issues/4306 is not blocked.
