### PR TITLE
Fix PDFs rename format pattern to given filename

### LINKED ISSUE #12556: Fix file renaming
1. Start JabRef
2. Check preferences that the citation key pattern for files is `[bibtexkey] - [title]`\
    Image
3. Create new library
4. Save library to folder `main/src/test/resources/pdfs/PdfContentImporter`
5. Drag an drop file  `Bogner2023.pdf` from `main/src/test/resources/pdfs/PdfContentImporter`
6. Go to tab "General"
7. Scroll down to "File"
8. Right click and select"Edit" \
    Image
9. See that filename misses citatoin key\
    Image
10. Select "Quality" > "Cleanup entries"
11. Ensure that "Rename PDFs to given filename format pattern" is checked.
12. Click OK\
    Image
13. In the warning, click "Autogenerate PDF Names"\
    Image
14. Click on "Edit" again. See that citation key is  in:\
    Image

Wish: File should have correct name after import.

Task:

1. Understand what happens at drag and drop
2. Ensure that citaton key generation happens before file name renaming

If 2 is not possible, report back, why.

---

Risen by https://github.com/JabRef/jabref/issues/12540

### PR DESCRIPTION
**Pull request by paudelritij**
Closes #12556 
This pull request addresses an issue in `ImportHandler.java` where the `BibEntry`'s Citation key was not defined before the `handleDropOfFiles` method was called causes missing of citation key in file name.

Added a call to generateKeys() to ensure that the key is generated prior to handling file drop-off.
 
### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [/] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [/] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by subhramit** [comment]
1. Please add a descriptive title (see other PRs)
2. You have ticked the mandatory check regarding changelog entry, but there is no entry added.

File: src/main/java/org/jabref/gui/externalfiles/ImportHandler.java [hunk 1]
```diff
@@ -159,6 +159,7 @@ public List<ImportFilesResultItemViewModel> call() {
                                     entry.clearField(StandardField.FILE);
                                     // Modifiers do not work on macOS: https://bugs.openjdk.org/browse/JDK-8264172
                                     // Similar code as org.jabref.gui.preview.PreviewPanel.PreviewPanel
+                                    generateKeys(Collections.singletonList(entry));
```
Comment (koppor) [inline src/main/java/org/jabref/gui/externalfiles/ImportHandler.java:162]: According to the issue description, the citation key is generated at a later stage, too.

Doe snot respect `org.jabref.logic.importer.ImporterPreferences#shouldGenerateNewKeyOnImport`

**Review by koppor — DISMISSED** [review]
More a quick hack than a real solution. Please go into the code again.

I can understand if that his too difficult; you can unassign yourself and choose another issue.

**Comment by paudelritij** [comment]
Hello @koppor 
1. *ImportHandler::DragDrop* During the file generation process, it appears that the "bibtexkey" is not being included in the filename. Specifically, the fileNamePattern lacks the *[bibtexkey]* placeholder, which is expected in the format *[bibtexkey] - [title]*.
2. In the 'General' section, I observed that the citation key is being generated correctly as 'RESTful2023' for the option to "Rename file on defined path". 
3. Another issue when the `Rename file on defined path` or `Rename files to configured filename format pattern` options are selected in ‘File’ column, the filename is updated accordingly. However, the name displayed in the 'File' box does not reflect this change, remaining as “- Do RESTful API …” in this instance.
4. I would like to understand how `UiTaskExecutor.runInJavaFXThread(() -> importEntries(allEntriesToAdd))` operates in the background. Specifically, I am curious if this process could assist in generating the citation key as expected.

**Comment by koppor** [comment]
> 4\. I would like to understand how `UiTaskExecutor.runInJavaFXThread(() -> importEntries(allEntriesToAdd))` operates in the background. Specifically, I am curious if this process could assist in generating the citation key as expected.

One has to understand the related code.

I asked "gurubase" - the answer is OK for the background thread, but not for including it --> https://gurubase.io/g/jabref/how-does-uitaskexecutor-runinjavafxthread-work

I can try to to think through completely; but then I would implement it for myself. Not sure, if this is the intention.

File: src/main/java/org/jabref/gui/externalfiles/ImportHandler.java [hunk 2]
```diff
@@ -151,12 +151,21 @@ public List<ImportFilesResultItemViewModel> call() {
                                 entriesToAdd.add(createEmptyEntryWithLink(file));
                                 addResultToList(file, false, Localization.lang("No BibTeX was found. An empty entry was created with file link."));
                             } else {
+                                CitationKeyGenerator keyGenerator = new CitationKeyGenerator(
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/externalfiles/ImportHandler.java:154]: this is not needed there is already a method generateKeys in this class

File: src/main/java/org/jabref/gui/externalfiles/ImportHandler.java [hunk 3]
```diff
@@ -151,12 +151,21 @@ public List<ImportFilesResultItemViewModel> call() {
...
+                                        bibDatabaseContext.getDatabase(),
+                                        preferences.getCitationKeyPatternPreferences());
+
                                 pdfEntriesInFile.forEach(entry -> {
                                     if (entry.getFiles().size() > 1) {
                                         LOGGER.warn("Entry has more than one file attached. This is not supported.");
                                         LOGGER.warn("Entry's files: {}", entry.getFiles());
                                     }
                                     entry.clearField(StandardField.FILE);
+                                    if (entry.getCitationKey().isEmpty()) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/externalfiles/ImportHandler.java:166]: just call generateKeys

**Review by Siedlerchr — CHANGES_REQUESTED** [review]

**Comment by Siedlerchr** [comment]
Changelog entry is missing as well

**Comment by paudelritij** [comment]
@Siedlerchr shall I think other way around or the changes made ok?

**Review by Siedlerchr — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
