### PR TITLE
issue(8448): allow URL with + sign in entry tabs

### LINKED ISSUE #8448: URL field replaces '+' character with ' ' (white space) breaking URL
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubunut 21.10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. For an entry go to the General tab.
2. Test this [URL](https://www.chicago.gov/content/dam/city/depts/cdot/Red%20Light%20Cameras/2022/Sutton+Tilahun_Chicago-Camera-Ticket_Exec%20Summary-Final-Jan10.pdf) to see where it should go
3. Enter the above URL into the URL field (in the General tab).
4. Click the (chain icon) link icon for the entry in the reference list.
5. Goes to a 'not found' page.

**You can see the reason - as soon as you enter/paste the URL into the URL field the '+' in the URL is replaced with a white space.**

Full version info:
JabRef 5.5--2022-01-17--27a05c7
Linux 5.13.0-25-generic amd64 
Java 16.0.2 
JavaFX 17.0.1+1

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by alexandre-cremieux**
Fixes  #8448 

* What: Allow the URL fields to accept URL containing + sign.
* Why: Some URLs are changed by JabRef when copy/paste from a navigation bar, making a bib pointing to an false URL.
* How: this is done by replacing all the + sign UTF-8 code by it's escape sequence code %2b. The code is placed in the `CleanupUrlFormatter` in the `org.jabref.logic.formatter.bibtexfields` package. A test with the given case is provided also.

**Note**: please let me know in the PR comments what type of comment you want in `CHANGELOG.md` and if you need a screenshot.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Looks good so far to me. Will give it a test later. For the changelog entry look at the others, the Changelog is directed towards end users so something like: We fixed an issue where a plus sign in the url field in the entry editor was breaking links...

**Review by Siedlerchr — APPROVED** [review]
Thanks!

**Comment by alexandre-cremieux** [comment]
You are welcome. Happy to help.

File: src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java [hunk 1]
```diff
@@ -1,53 +1,88 @@
...
- * Cleanup URL link
+ * Cleanup URL link.
+ * <p>
+ *     Expose string representations URL links clean up logic.
+ * </p>
  */
 public class CleanupUrlFormatter extends Formatter {
 
-    // This regexp find "url=" or "to=" parameter in full link and get text after them
+    /**This regexp find "url=" or "to=" parameter in full link and get text after them*/
```
Comment (koppor) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java:21]: No need to change to JavaDoc comment syntax

File: src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java [hunk 2]
```diff
@@ -1,53 +1,88 @@
...
     private static final Pattern PATTERN_URL = Pattern.compile("(?:url|to)=([^&]*)");
 
+    /**
+     * {@inheritDoc}
+     */
```
Comment (koppor) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java:26]: Quoting from the first comment at https://stackoverflow.com/a/13327668/873282

> You should only use @inheritDoc if you intend to add to the original superclass documentation. If you merely want it to be duplicated, Javadoc will do that already, noting that the superclass documentation applies to the subclass's overridden method because the subclass provided no additional documentation.

So, please remove that JavaDoc

File: src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java [hunk 3]
```diff
@@ -1,53 +1,88 @@
...
     @Override
     public String getName() {
         return Localization.lang("Cleanup URL link");
     }
 
+    /**
+     * {@inheritDoc}
+     */
```
Comment (koppor) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java:34]: Please remove

File: src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java [hunk 4]
```diff
@@ -1,53 +1,88 @@
...
         if (matcher.find()) {
-            toDecode = matcher.group(1);
+            return URLDecoder.decode(matcher.group(1), StandardCharsets.UTF_8);
         }
         return URLDecoder.decode(toDecode, StandardCharsets.UTF_8);
     }
 
+    /**
+     * {@inheritDoc}
+     */
```
Comment (koppor) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java:70]: Please remove

File: src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java [hunk 5]
```diff
@@ -1,53 +1,88 @@
...
     @Override
     public String getDescription() {
-        return Localization.lang("Cleanup URL link by removing special symbols and extracting simple link");
+        return Localization
+                .lang("Cleanup URL link by removing special symbols and extracting simple link");
```
Comment (koppor) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java:74]: Please do not split `Localziation.lang`, because then our localization script won't work.

File: src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java [hunk 6]
```diff
@@ -1,53 +1,88 @@
...
     }
 
+    /**
+     * {@inheritDoc}
+     */
```
Comment (koppor) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/CleanupUrlFormatter.java:79]: Please remove

**Review by koppor — APPROVED** [review]
Thank you for working on this - and also adding a test case.

I have some code formatting comments; other than that: LGTM

**Review by koppor — CHANGES_REQUESTED** [review]
The code formatting issues need to be resolved - I clicked the wrong button - sorry for that! 😇

**Comment by alexandre-cremieux** [comment]
If you can please tell me where I can find the localization script for my understanding ? Thanks

**Comment by Siedlerchr** [comment]
You just have to run the LocalizationConsistencyTest. It will tell you if there are any errors or strings missing/obsolete
See also https://devdocs.jabref.org/getting-into-the-code/code-howtos#using-localization-correctly

**Review by Siedlerchr — APPROVED** [review]
