### PR TITLE
Fix for issue 8396: filter out the empty field

### LINKED ISSUE #8396: Only show deprecated fields tab if they contain values
### JabRef version

5.4 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

The deprecated fields tab is currently shown even though the fields don't contain any values.
In such a case, the tab shouldn't be shown.
image

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by tomlinn**
# Fixes #8396
>  Only show deprecated fields tab if they contain values

### Descripion
Fixes #8396 by filtering out the empty deprecated fields.
The issue was caused because it always returns a valid deprecated field set but didn't check whether is empty or not.

### JabRef version
5.4 (latest release)

### Operating system
Mac OS

### Details on version and operating system
Monterey 12.2.1

Before
Screen Shot 2022-05-10 at 1 38 47 PM
After
Screen Shot 2022-05-10 at 1 37 31 PM

### PR Checklist

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please check the codestyle, see here for how to impot the style https://github.com/JabRef/jabref/tree/main/config

File: src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java [hunk 1]
```diff
@@ -53,7 +54,14 @@ public DeprecatedFieldsTab(BibDatabaseContext databaseContext,
     protected Set<Field> determineFieldsToShow(BibEntry entry) {
         Optional<BibEntryType> entryType = entryTypesManager.enrich(entry.getType(), databaseContext.getMode());
         if (entryType.isPresent()) {
-            return entryType.get().getDeprecatedFields();
+            Set<Field> validDeprecatedFields = new HashSet<>();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java:57]: You can make this a one liner with Streams:

`            return entryType.get().getDeprecatedFields().stream().filter(field->! entry.getField(field).isEmpty()).collect(Collectors.toSet());
`

File: src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java [hunk 2]
```diff
@@ -53,7 +54,14 @@ public DeprecatedFieldsTab(BibDatabaseContext databaseContext,
...
+            for (Field field : entryType.get().getDeprecatedFields()) {
+                Optional<String> fieldValue = entry.getField(field);
+                if (fieldValue.isPresent()) {
+                    validDeprecatedFields.add(field);
+                }
+            }
+            return validDeprecatedFields;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java:64]:
```suggestion
        return entryType.get().getDeprecatedFields().stream().filter(field->! entry.getField(field).isEmpty()).collect(Collectors.toSet());
```

**Comment by Siedlerchr** [comment]
I was so free to replace your solution with a more simple one liner to get that PR in asap.

File: src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java [hunk 3]
```diff
@@ -1,6 +1,7 @@
 package org.jabref.gui.entryeditor;
 
 import java.util.Collections;
+import java.util.HashSet;
 import java.util.Optional;
 import java.util.Set;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java:6]:
```suggestion
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
```

File: src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java [hunk 4]
```diff
@@ -53,7 +54,7 @@ public DeprecatedFieldsTab(BibDatabaseContext databaseContext,
     protected Set<Field> determineFieldsToShow(BibEntry entry) {
         Optional<BibEntryType> entryType = entryTypesManager.enrich(entry.getType(), databaseContext.getMode());
         if (entryType.isPresent()) {
-            return entryType.get().getDeprecatedFields();
+        return entryType.get().getDeprecatedFields().stream().filter(field->! entry.getField(field).isEmpty()).collect(Collectors.toSet());
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java:57]:
```suggestion
            return entryType.get().getDeprecatedFields().stream().filter(field -> !entry.getField(field).isEmpty()).collect(Collectors.toSet());
```
```

**Review by koppor — APPROVED** [review]

File: src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java (hunk 2 above)
Comment (tomlinn) [reply src/main/java/org/jabref/gui/entryeditor/DeprecatedFieldsTab.java]: Cool, that's better! thanks!

**Comment by mlep** [comment]
@tomlinn Thank you for fixing this issue, hence making JabRef a better software! If you are looking for another issue to solve, this one is related to the Deprecated fields: https://github.com/JabRef/jabref/issues/7757
