### PR TITLE
Remove empty customization warning

### LINKED ISSUE #5332: Custom entry import dialog only appears on broken files and is empty with inherited JabRef settings
JabRef version 5.0-dev (commit db96f88 master) on Ubuntu-16.04 x86_64

- [x ] I have tested the latest development version from `* master db96f88 Fix problem with search and switching between libraries (#5326)` from https://github.com/JabRef/jabref.git and the problem persists

If a broken bibtex file that contains correct custom entry types is presented to JabRef, the "Custom Entry type dialogue appears, and it is different depending on whether JabRef settings are created anew or if they are inherited from the different version.

- If the settings are inherited from the 4.0 JabRef version (my setting file is attached 
[jabref-settings-2019-09-19.zip](https://github.com/JabRef/jabref/files/3631771/jabref-settings-2019-09-19.zip)), and a broaken file is opened, an *empty* dialogue window is presented for the custom entry import;

- If the settings are created anew with JabRef 5.0-dev, the broken file causes a dialogue with reasonable content to be displayed;

- If a correct bibtex file is presented (regardless of the settings), the import dialogue is not presented and the settings are silently imported into both old and new settings.

1. Back up your old settings, or remove them if you have a backup:
`mkdir -p ~/wastebasket; if [ -d ~/wastebasket/jabref ]; then ( set -x; rm -rf ~/.java/.userPrefs/org/jabref ); else mv -v ~/.java/.userPrefs/org/jabref ~/wastebasket; fi`
2. Unpack the JabRef settings from JabRef 4.0:
`( cd; unzip ~/jabref-settings-2019-09-19.zip )`
3. Start the new JabRef in the Git working copy:
`build/image/bin/JabRefMain test-entry-types-broken.bib &`
The first dialogue that appears, correctly reports the error in the file; the second, however, looks strange:
Screenshot from 2019-09-19 17-48-04
4. Remove the JabRf setting files:
`rm -rf ~/.java/.userPrefs/org/jabref`
5. Without restoring the old settings, start the 5.0dev JabRef:
`build/image/bin/JabRefMain test-entry-types-broken.bib &`
The first dialogue on startup is again the expected error message, and the second is a reasonably filled "Custom entry types" dialogue:
Screenshot from 2019-09-19 17-52-29
6. If a correct bibtex file is imported:
`build/image/bin/JabRefMain test-entry-types.bib &`
no "Custom entry types" appears, regardless of whether the `~/.java/.userPrefs/org/jabref` directory exists, an if it exists whether it is from JabRef 4.0 or JabRef 5.0.

From the user's perspective, the "Custom entry types" in step 3. seems incorrect, and the behaviour in steps 5. and 6. seems inconsistent; one would expect that the "Custom entry types" dialogue either always appears or is always by-passed.

The mentioned bibtex files with custom entry types are here: 
[test-entry-types.zip](https://github.com/JabRef/jabref/files/3631856/test-entry-types.zip)

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes #5332. Problem was that the dialog was shown whenever the library contained customized entry types, even if the customizations were equal to the customization stored in the global preferences. A bit of refactoring/renaming along the way.

----

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/model/entry/BibEntryTypesManager.java [hunk 1]
```diff
@@ -127,11 +127,22 @@ public boolean isCustomType(EntryType type, BibDatabaseMode mode) {
...
+            return !EntryTypeFactory.isEqualNameAndFieldBased(type, currentlyStoredType.get());
+        }
+    }
+
     /**
      * This class is used to specify entry types for either BIBTEX and BIBLATEX.
      */
     static class InternalEntryTypes {
-        private final SortedSet<BibEntryType> customizedTypes = new TreeSet<>();
+        private final SortedSet<BibEntryType> customOrModifiedType = new TreeSet<>();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/model/entry/BibEntryTypesManager.java]: you might need to pass a comparator here as well

Comment (tobiasdiez) [reply src/main/java/org/jabref/model/entry/BibEntryTypesManager.java]: BibEntryType implements comparable, so no comparator needed
