### PR TITLE
Convert some fields to TextArea

### LINKED ISSUE #11785: Cannot use tab to jump to next field in some single-line fields
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

_No response_

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go into the URL field in the entry editor
2. Press `Tab`.

Empty space is inserted instead of jumping to the next field.

### Appendix

The reason is that https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java is used over https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java in some fields that sholud be normal single-line fields: Url, Identifier, Owner, Issn

### PR DESCRIPTION
**Pull request by juliusalberto**
I have changed some fields from TextArea to TextField in some fields: URL, identifier, owner, and ISSN.
Closes #11785 

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — CHANGES_REQUESTED** [review]
Nice work.

Small comments inside.

Optional follow-ups:

- [ ] <kbd>Tab</kbd> in the last text field in a tab should focus the next tab in the tabs of the entry editor.
- [ ] <kbd>Tab</kbd> in empty text area field should focus the next field
- [ ] Consistency check

---

Consistency check:

There should be an automatic checker (JUnit) test case. JabRef has `org.jabref.model.entry.field.FieldProperty#MULTILINE_TEXT`. All of these fields should be offered as `TextArea`, all others (!) as `TextField`

I think, this is a hard one, but much to learn. 

The "only" way is maybe to use [Refaster template recipes](https://docs.openrewrite.org/authoring-recipes/refaster-recipes) and check if OpenRewrite would change anything.

Maybe, this also does not work and one would need to use [JavaParser](https://javaparser.org/) to check the constructor at `org.jabref.gui.fieldeditors.FieldEditorFX`, whether all `new X` get a `field` passed matching the `X` (`X instanceof TextArea <=> fieldProperties.contains(MULTILINE_TEXT)`)

---

If you can do any of these, I would be happy. Otherwise, I will open follow-up issues. Initally, all of these ideas look hard to implement.

File: src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java [hunk 1]
```diff
@@ -19,6 +20,9 @@
 public class EditorTextField extends TextField implements Initializable, ContextMenuAddable {
 
     private final ContextMenu contextMenu = new ContextMenu();
+    private PasteActionHandler pasteActionHandler = () -> {
+        // Set empty paste behavior by default
```
[the remark this answers is not in the document]
Comment (juliusalberto) [reply src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java]: I've changed the comment to `// No additional paste behavior`

File: src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java [hunk 2]
```diff
@@ -47,4 +51,31 @@ public void initContextMenu(final Supplier<List<MenuItem>> items, KeyBindingRepo
     public void initialize(URL location, ResourceBundle resources) {
         // not needed
     }
+
+    /**
+     * Set pasteActionHandler variable to passed handler
+     *
+     * @param handler an instance of PasteActionHandler that describes paste behavior
+     */
```
[the remark this answers is not in the document]
Comment (juliusalberto) [reply src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java]: I've removed this comment from the code

File: src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java [hunk 3]
```diff
@@ -47,4 +51,31 @@ public void initContextMenu(final Supplier<List<MenuItem>> items, KeyBindingRepo
...
+    public void setPasteActionHandler(PasteActionHandler handler) {
+        Objects.requireNonNull(handler);
+        this.pasteActionHandler = handler;
+    }
+
+    /**
+     * Override javafx TextField method applying TextField.paste() and pasteActionHandler after
+     */
```
[the remark this answers is not in the document]
Comment (juliusalberto) [reply src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java]: I have already removed it from the code

**Comment by juliusalberto** [comment]
> Optional follow-ups:
> 
> * [ ]  Tab in the last text field in a tab should focus the next tab in the tabs of the entry editor.
> * [ ]  Tab in empty text area field should focus the next field
> * [ ]  Consistency check

Hi @koppor, can I do the second one (Tab in empty text area field should focus on the next field)? Thanks! 

Also, I've already made the changes you requested. Let me know if you need anything else.

**Comment by koppor** [comment]
> I'd like to do the first one please (Tab in the last text field in a tab should focus the next tab in the tabs of the entry editor). 

Do you need a seperate issue for that be created?

> One of my friend @yeonissa would like to be assigned with the second one. 

Do you need a seperate issue for that be created?

**Review by koppor — DISMISSED** [review]

**Comment by koppor** [comment]
The changes need a second review and thus this PR awaits a second review.

**Comment by juliusalberto** [comment]
@koppor yes please - can you make separate issues for that? Thanks a lot.

File: src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java [hunk 4]
```diff
@@ -19,6 +20,9 @@
 public class EditorTextField extends TextField implements Initializable, ContextMenuAddable {
 
     private final ContextMenu contextMenu = new ContextMenu();
+    private PasteActionHandler additionalPasteActionHandler = () -> {
+        // No additional paste behavior
+    };
```
Comment (LoayGhreeb) [inline src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java:25]: You don't need to create an interface; you can use `java.lang.Runnable` instead. Please also update in `org.jabref.gui.fieldeditors.EditorTextArea`, or remove it if it's not being used.

Comment (juliusalberto) [reply src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java:25]: i think using Runnable here would be semantically inappropriate, since it's typically used for thread-related tasks. Sticking with a more specific interface or lambda for paste handling keeps the intent clearer.

Comment (InAnYan) [reply src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java:25]: About `Runnable`s. I also thought it's only for threading, but no.

It's a general and accepted way to have a function type that accepts to arguments and returns no type

File: src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java [hunk 5]
```diff
@@ -51,35 +51,35 @@ public static Supplier<List<MenuItem>> getNameMenu(final TextInputControl textIn
...
+            menuItems.addAll(new DefaultMenu(textField).get());
             return menuItems;
         };
     }
 
     /**
      * The default context menu with a specific menu item to cleanup URL.
      *
-     * @param textArea text-area that this menu will be connected to
+     * @param textField text-area that this menu will be connected to
```
Comment (InAnYan) [inline src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java:75]: `text-area` there

**Review by InAnYan — DISMISSED** [review]

File: src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java (hunk 5 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java:75]: The diff shows that `textField` is put in here, thus good or me!

Comment (koppor) [inline src/main/java/org/jabref/gui/fieldeditors/contextmenu/EditorMenus.java:75]:
```suggestion
     * @param textField text field that this menu will be connected to
```

**Review by koppor — APPROVED** [review]

**Review by InAnYan — DISMISSED** [review]

**Comment by koppor** [comment]
> @koppor yes please - can you make separate issues for that? Thanks a lot.

https://github.com/JabRef/jabref/issues/11937 and https://github.com/JabRef/jabref/issues/11938. @juliusalberto Please comment there so that I can assign you (or your colleague)

File: src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java (hunk 4 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java:25]: This is a general code style question. Does one want to have strong typing or not. - Seeing that the setting of this is very generic, I also don't see the need for an additional class type.

    () -> textField.setText(new CleanupUrlFormatter().format(new TrimWhitespaceFormatter().format(textField.getText())))

Just changing to `Runnable` should fix it?

Regarding the intention of runnable:

> Represents an operation that does not return a result.

This is excactly the thing we are looking for here, isn't it?

---

Source of Runnable:

```java
package java.lang;

/**
 * Represents an operation that does not return a result.
 *
 * <p> This is a {@linkplain java.util.function functional interface}
 * whose functional method is {@link #run()}.
 *
 * @author  Arthur van Hoff
 * @see     java.util.concurrent.Callable
 * @since   1.0
 */
@FunctionalInterface
public interface Runnable {
    /**
     * Runs this operation.
     */
    void run();
}
```

**Review by koppor — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java (hunk 4 above)
Comment (juliusalberto) [reply src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java]: I changed it to Runnable in my latest commit. Thanks.

**Review by LoayGhreeb — APPROVED** [review]

**Review by koppor — APPROVED** [review]
