### PR TITLE
Save sort order column of main table

### LINKED ISSUE #3850: Default sorting of entry table is lost
I try to set a default sorting in the options dialog for the entry table, for example, `priority`, `year`, `title`. 
In some case I want to sort the entry table for a quick review/search, for example, to a sorting based on the `bibtexkey` to see all works related to that key.
However, when I click on the column headers, the default sorting criteria in the options is lost (or rather got overwritten) - see before and after screenshots.

I would have expected the following behavior:
* Set a default sorting for the entry table
* On changing the sorting
    * the first click applies the ascending order
    * the second click applies the descending order
    * the third click removes the sorting of that column
* So, after the third click, I expect that the default sorting from the options dialog will be applied again

Would love to hear what others think :-)

Cheers
Michael

---

- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 

Steps to reproduce:

1. Set default sorting options dialog for the entry table
2. Go back to your list of references, click on a column header to change the sort
3. Check the default sorting in the options, they got overwritten

Before: 
image

After:
image

### LINKED ISSUE #4224: Save sort-criteria of maintable across sessions
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.0-dev--snapshot--2018-07-15--master--a44d31668
Windows 7 6.1 amd64 
Java 1.8.0_181

When opening the snapshot, it always opens with some predefined display. I for example rely very much on the timestamp with the latest addition first. Earlier version of Jabref showed me the entry list with the timestamp as the sorting criteria. The newest shapshot does no longer do this and I have always to start by clicking the timestamp e.g. 
Please let keep Jabref the situation in memory, where one has left.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes  #4224
Fixes #3850

I tired to fix the above issue. But I have the problem that the column sort listener is never fired when the sort order is DESCENDING. 

Edit// I also fixed an FX Threading error  when opening a new library (the snackbar output was not onFX Thread)

@tobiasdiez  Any idea if I did sth wrong oder have to set the value somewhere else?

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Sorry no idea, would also need to debug this to see what's going on.

**Comment by Siedlerchr** [comment]
Hm, this is odd. I created a simple test application based on the code here https://code.makery.ch/blog/javafx-8-tableview-sorting-filtering/
and I experience the same behaviour

**Comment by Siedlerchr** [comment]
Apparently the SortOrder alone was not sufficient: https://stackoverflow.com/a/52255643/3450689
It works now

File: src/main/java/org/jabref/gui/maintable/MainTable.java [hunk 1]
```diff
@@ -114,6 +114,12 @@ public MainTable(MainTableDataModel model, JabRefFrame frame,
 
         this.pane.getStylesheets().add(MainTable.class.getResource("MainTable.css").toExternalForm());
 
+        //Set sort order column from preferences, currently only single column suported
+        this.getColumns().forEach(col -> preferences.getColumnPreferences().getSortTypeForColumn(col.getText()).ifPresent(sortType -> {
+            this.getSortOrder().add(col);
```
[the remark this answers is not in the document]
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/maintable/MainTable.java]: Yes, I found it out while testing. The sort oder defines the column which are considered to be sorting. 
The sortType property only has an influence if the column is the sortOrder

File: src/main/java/org/jabref/gui/maintable/MainTable.java [hunk 2]
```diff
@@ -114,6 +114,12 @@ public MainTable(MainTableDataModel model, JabRefFrame frame,
 
         this.pane.getStylesheets().add(MainTable.class.getResource("MainTable.css").toExternalForm());
 
+        //Set sort order column from preferences, currently only single column suported
```
[the remark this answers is not in the document]
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/maintable/MainTable.java]: As I learned from the SO answer, with shift it's possible to add multiple columns to the sort order.
However, currently only one column is stored, e.g. if you have both author DESCENDING and timestamp ASCENDING, it will only store the first one.  Or do we have an elegant solution to store Key-Value Pairs in the preferences? e.g. a list of columns with sort type.

[the remark this answers is not in the document]
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/maintable/MainTable.java]: The standard way is to have to lists, one for the keys and one for the values. In the progress, it would be nice if you would add the corresponding wrapper methods (get/putMap) in `JabRefPreferences` for reuse in the future.

**Comment by Siedlerchr** [comment]
I now managed to save the whole sort oder for multiple columns.

File: src/main/java/org/jabref/preferences/JabRefPreferences.java [hunk 3]
```diff
@@ -1442,8 +1429,6 @@ public SavePreferences loadForExportFromPreferences() {
         if (!saveInOriginalOrder) {
             if (this.getBoolean(JabRefPreferences.EXPORT_IN_SPECIFIED_ORDER)) {
                 saveOrder = this.loadExportSaveOrder();
-            } else {
-                saveOrder = this.loadTableSaveOrder();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/preferences/JabRefPreferences.java]: I suspect this is still needed to allow the user to export entries in the current sort order.

Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java]: I still think the export sort order should be different from the table sort order and I will remove table sort order. But I currently see no easy way to convert the table column sort order to our schema

Comment (tobiasdiez) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java]: I'm fine with removing the "export according to table sorting" feature since it may quickly lead to unexpected exports (although I'm pretty confident that some users rely on this feature). But then please add a changelog entry and check if the documentation needs to be adopted accordingly.

Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java]: I quickly had an idea on how to re implement this which works.
