### PR TITLE
Fix expansion of bracketed expressions in RegExpBasedFileFinder

### LINKED ISSUE #4342: Finding files with non-alphabetical characters in title
JabRef version 4.3.1 on Windows 10 64-bit (I don't have administrative rights to install developer snapshots, e.g. version 5.0)

I like to use regular expression search when linking local files and use the following:
**/.*[title].*\\.[extension]

As far as I know, that should search in the directory and subdirectories of the main file directory for files that contain the title and the proper extension (.pdf). Contain, right? The file name does not need to start with the title.

However, choosing an article in my bibliography and pressing F7 does nothing (status bar simply tells that it finished and found nothing).

What does F7 (Automatically set file links) do? I've tested with many files and get the same result, even when making sure the file name contains no special characters or anything like that.

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
#### Fixes #4342

#4342 contains two issues.
1. The bracketed pattern `[title]` does not refer to the StandardField title, but a "special" pattern intended to give nicer output (this is why dashes don't work, see https://github.com/JabRef/jabref/issues/4342#issuecomment-742722875). It is intended and can be **avoided** by using `[TITLE]`.
2. An expanded bracketed pattern is interpreted as a regexp (which it should not). This is why parenthesizes doesn't work. A pattern that expands into `(abc)` will match `abc`, but not `(abc)`.
 
If the expanded bracketed pattern contains characters that have a special meaning in regexp (such as a parenthesis and brackets), it becomes a problem.
An entry with the title `Regexp from [A-Z]` and the bracketed expression `[TITLE]` would match a file titled `Regexp from B`, but not a file named `Regexp from [A-Z]`.

#### The goal of this PR

Match files whose expanded bracketed pattern includes symbols that can be miss-interpreted.

1. **Regex**: All expanded brackets will match literally,  using `Pattern.quote`. I don't see a reasonable use-case for allowing a bracket to expand into an actual regex.
2. **Cleaned filenames** _In addition_ to matching the regularly expanded brackets, they will also match cleaned file names (it will find files containing both `ACM/IEEE-CS` and `ACM_IEEE-CS`).

**Note**: Regex can still be used outside of the bracketed patterns. (except for character classes, since they will be interpreted as a bracketed pattern)

#### Issues neither addressed in this PR nor the current master
1. Files that get truncated due to length
2. Character classes in the RegExpBasedFileFinder. In the following pattern, `**/.*[title][a-z]+.*\\.[extension]`, `[a-z]` is treated as if it is a bracketed pattern
3. BracketedExpressions are only expanded in the file name, **not in the directory name**.

#### Checklist

- [x] ~Check if parts can be replaced by a glob (<a href="https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)">getPathMatcher</a>)~
- [x] Improve finding and parsing bracketed expressions?
- [x] Fix this particular use case using regexp literals (\Q\E in the regexp)
    - [x] ~Add type-safety to the expanded bracket (return a compiled Pattern when it is supposed to be a RegularExpression)~
- [x] Check that the expanded bracketed expression result in a correct filename, and/or convert it into one. (avoid issues finding JabRef generated filenames 😱 )
    - [x] ~Add test case for an expression that would result in a JabRef corrected filename ("ACM/IEEE-CS Information Technology Curriculum" -> "ACM_IEEE_CS Information Technology Curriculum")~ I don't think this can be done reliably within the scope of this PR
    - [x] ~Make sure a warning appears in the debug log if a filename/dirname is expected to be too long~
    - [x] ~Refactor `FileUtil.createFileNameFromPattern` so the same code is used~ I don't think this can be done reliably within the scope of this PR
- [x] Add JavaDoc, improve variable names and comments 

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required) **The manual test was only performed with the example given in https://github.com/JabRef/jabref/issues/4342#issuecomment-686606696**
- [x] ~Screenshots added in PR description (for UI changes)~
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Is this
https://github.com/JabRef/jabref/blob/4d8e4f0e1782af33e6e95c6ad6990b06d4e37c32/src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java#L43-L49

one of those, don't fix if it isn't broken? As far as I can tell it duplicates the functionality of

https://github.com/JabRef/jabref/blob/4d8e4f0e1782af33e6e95c6ad6990b06d4e37c32/src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java#L166-L175

It is just that the `BracketedPattern` should cover more cases (e.g., regexp modifiers with character classes `[a-z]`).

File: src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java [hunk 1]
```diff
@@ -195,30 +218,14 @@ public static String expandBrackets(String bracketString, BibEntry entry, BibDat
...
-        return resultFiles;
-    }
-
-    private List<Path> collectFilesWithMatcher(Path actualDirectory, BiPredicate<Path, BasicFileAttributes> matcher) {
+        Pattern toMatch = createFileNamePattern(fileParts, extensionRegExp, entry);
+        BiPredicate<Path, BasicFileAttributes> matcher = (path, attributes) -> toMatch.matcher(path.getFileName().toString()).matches();
         try (Stream<Path> pathStream = Files.find(actualDirectory, 1, matcher, FileVisitOption.FOLLOW_LINKS)) {
-            return pathStream.collect(Collectors.toList());
-        } catch (UncheckedIOException | IOException ioe) {
-            return Collections.emptyList();
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java:207]: I did not find a reason why this should return an empty list in #3623. If it does return an empty list, in effect, all checked/unchecked IOErrors are swallowed and only PatternSyntaxException (that are re-thrown as IOExceptions) can occur.

File: src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java [hunk 2]
```diff
@@ -185,27 +201,14 @@ public static String expandBrackets(String bracketString, BibEntry entry, BibDat
...
+            resultFiles.addAll(pathStream.collect(Collectors.toList()));
+        } catch (UncheckedIOException uncheckedIOException) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java:208]: Why is this even an UncheckedIOException? 
If needed, the UncheckedException is just a wrapper for the IOEception. So you could call throw uncheckedException.getCause()

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java:208]: Frankly, I am not sure why an `UncheckedIOException` is caught in this part of the code. I don't have much experience with nio.* but my interpretation of the API is that the `UncheckedIOException` must be caught in the parts of the code that make use of the reference.
I don't know if there are any other potential issues with a lazily loaded file system walk. Based on DirectoryStream and Files.walk I'd guess it could be thrown if depth > 1 and there is a cycle, hence, not in this part of the code unless it is changed.

**Comment by koppor** [comment]
This needs deeper thinking at review. At first gut feeling, `[author] text` should be expaned. This is not possible any more in this PR (see remove tests). Not sure whether we really want that. We need to really read the PR description and the linked issue for a proper feedback.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> This needs deeper thinking at review. At first gut feeling, `[author] text` should be expaned. This is not possible any more in this PR (see remove tests).

This is possible in this PR. I'll review my PR description and see if I can be clearer.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@koppor @Siedlerchr sorry about that. Sometimes it is a bit too easy to tunnel-vision and assume something is "obvious", while forgetting all the assumptions needed to make it obvious. The PR description is updated.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java [hunk 3]
```diff
@@ -143,34 +156,4 @@ void testFindFileNonRecursive() throws Exception {
         // then
         assertTrue(result.isEmpty());
     }
-
-    @Test
-    void testExpandBrackets() {
```
Comment (koppor) [inline src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: We should try to keep these tests. We are discussing at https://github.com/JabRef/jabref/issues/4342#issuecomment-762515082.

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: I'll take another look at it but I am 90% sure they only duplicate the `expandBrackets` of `BracketedPattern`. Perhaps they can be moved there instead.

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: Wait a sec. Just to be perfectly clear. I have not removed this functionality, I am using the equivalent code in `BracketedPattern`.

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: Due to other bugs (mostly with parsing the regex modifier), I am slowly trying to move all parsing of bracketed patterns to `BracketedPattern.java`.

Comment (tobiasdiez) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: It's good to move extensive testing indeed to `BracketedPattern`. However, the should at least one test here to verify that the file finder expands pattern as expected (otherwise you could remove the internal call to bracketedpattern and still all tests would pass).

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java [hunk 4]
```diff
@@ -80,6 +80,19 @@ void testYearAuthFirstPageFindFiles() throws Exception {
                 result);
     }
 
+    @Test
+    void findAssociatedFilesContainingRegexpFromBracketedExpression() throws Exception {
+        var bibEntry = new BibEntry().withField(StandardField.TITLE, "Regexp from [A-Z]");
+
+        var extension = Collections.singletonList("pdf");
+        var directory = Collections.singletonList(Path.of(FILES_DIRECTORY));
+        RegExpBasedFileFinder fileFinder = new RegExpBasedFileFinder("[TITLE]\\\\.[extension]", ',');
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:89]: test

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java [hunk 5]
```diff
@@ -80,6 +80,19 @@ void testYearAuthFirstPageFindFiles() throws Exception {
...
+
+        List<Path> result = fileFinder.findAssociatedFiles(bibEntry, directory, extension);
+        assertEquals(Collections.singletonList(Path.of("src/test/resources/org/jabref/logic/importer/unlinkedFilesTestFolder/Regexp from [A-Z].pdf")),
+                result);
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:93]: Test for bracketed pattern

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 3 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: > However, the should at least one test here to verify that the file finder expands pattern as expected

I intended https://github.com/JabRef/jabref/pull/7338/files/4c2f2c3cba5c8636cd8854a6fc3aa51beb0053a2#r560415435 to cover that scenario. Admittedly, it might make sense to cover more complex cases than this.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 5 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:93]: `GUO ea - INORG CHEM COMMUN 2010 - Ferroelectric Metal Organic Framework (MOF).pdf` should be a problem in the current master. The example is from the zip file in https://github.com/JabRef/jabref/issues/4342#issuecomment-686606696.

File: src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java:207]: Could you add that as comment to `throw`?  That way, the idea is not lost.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 5 above)
Comment (koppor) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:93]: Why is that an issue? - Could you simply add a test case for that filename, too? Better more tests even if they cover the same lines of code. If someone else touches the code later, it might help.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 3 above)
Comment (koppor) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: There is no need to save disk space or test class length. May I ask to either keep these tests (they should be green before and after your fix) or move them to `BracketedPattern`? - Even if they are pretty similar, they form a good regression test to ensure that future code "optimizations" keep the old behavior.

I also think that these tests can also serve as "documentation" of the class `RegExpBasedFileFinder`, even if that class relies to other classes, where documentation is found. I really like that the public interface of the class is tested.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 5 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:93]: > Could you simply add a test case for that filename, too?

Will do.

> Why is that an issue?

Because the RegExpBasedFileFinder interpret(ed) the content of an expanded bracketed pattern as if it is part of a regex. In this case, the title contains `(MOF)` which in regex is a capturing group matching `MOF`, not `(MOF)`.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 3 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: I'll add them to the tests in `BracketedPattern` with a hint/comment that they are from `RegExpBasedFileFinder`.

File: src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java (hunk 1 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/logic/util/io/RegExpBasedFileFinder.java:207]: 👍 
I believe the now added comment is clear regarding what cases an empty list might be returned instead of an exception being thrown.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 3 above)
Comment (tobiasdiez) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:148]: The new tests are way better since they actually test the indented behavior (files are found) instead of an implementation detail (expandBrackets method).

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java [hunk 6]
```diff
@@ -80,6 +80,49 @@ void testYearAuthFirstPageFindFiles() throws Exception {
...
+    @Test
+    void findAssociatedFilesFindCleamedFileFromBracketedExpression() throws Exception {
+        var bibEntry = new BibEntry().withField(StandardField.JOURNAL, "ACM/IEEE-CS");
+
+        var extension = Collections.singletonList("pdf");
+        var directory = Collections.singletonList(Path.of(FILES_DIRECTORY));
+        RegExpBasedFileFinder fileFinder = new RegExpBasedFileFinder("[JOURNAL]\\\\.[extension]", ',');
+
+        List<Path> result = fileFinder.findAssociatedFiles(bibEntry, directory, extension);
+        assertEquals(Collections.singletonList(Path.of("src/test/resources/org/jabref/logic/importer/unlinkedFilesTestFolder/ACM_IEEE-CS.pdf")),
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:105]: I know you didn't started this, but it's bad practice to create (empty) files just for the tests. Its better and easier to use a temporary folder and create the files just for the test: https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
LGTM! I've only one suggestion for the tests, otherwise +1 for merge.

File: src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java (hunk 6 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:105]: I guess I should have known that existed 😬 
I'll look into it tomorrow, I doubt I am the only one that "learns" from the test-files.

Comment (tobiasdiez) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:105]: The TempDir extension is new in Junit5 if I'm not mistaken so it's not surprising that the code is not updated yet. Thanks for looking into it.

Comment (Siedlerchr) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java:105]: You can take a look at the RenamePdfCleanupTest for using this

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/util/io/RegExpBasedFileFinderTests.java]: Thank you both for the links! This should be addressed now.

**Review by tobiasdiez — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
