### PR TITLE
Fix problem with search and switching between libraries

### LINKED ISSUE #4846: Cleared search is redone after switching library
to reproduce:

1. open two libraries
2. search in first one
3. clear search in first
4. switch to second library
5. switch back to first

then in first library the search is restored.

info:
```
JabRef 5.0-dev--snapshot--2019-04-03--master--a273eb1fa
Mac OS X 10.14.3 x86_64 
Java 1.8.0_191
```

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes #4846 by using bindings instead of listeners.

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/BasePanel.java [hunk 1]
```diff
@@ -1054,8 +1054,8 @@ public MainTable getMainTable() {
      *
      * @param currentSearchQuery can be null
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/BasePanel.java]: Adjust the comment or remove it, because you
