### PR TITLE
Fix action helper when no library is open

### LINKED ISSUE #6430: Menu View on empty file => Uncaught exception
JabRef 5.1--2020-05-04--b5599c9
Linux 4.9.0-12-amd64 amd64 
Java 14.0.1

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When clicking on the menu item "View" with an empty library on focus, a message "Uncaught exception" is displayed.

1. Create a new BibTeX library
2. Click on menu View

A window pops-up, displaying the message "Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
Afterwards, To be able to display the menu View on another file, JabRef needs to be re-opened.

Note: All the other menus are working as expected.

<details>
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.collections.ObservableListWrapper.get(Unknown Source)
	at org.jabref/org.jabref.gui.actions.ActionHelper.isFilePresentForSelectedEntry(Unknown Source)
	at org.jabref/org.jabref.gui.documentviewer.ShowDocumentViewerAction.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.JabRefFrame.lambda$createMenu$13(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Menu.setShowing(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Menu.show(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.MenuBarSkin.showMenu(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.MenuBarSkin.showMenu(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.MenuBarSkin.lambda$rebuildUI$27(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
This fixes #6430 an exception when opening the View menu with an empty library

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
A fix using `EasyBind.monadic` similar to the other fix doesn't work? This is I guess the cleanest solution since you don't need to worry about null values anymore. (It's the bindings version of `Optional`)

**Comment by Siedlerchr** [comment]
@tobiasdiez  Thanks for the hint, I refactored it now. Seems to still work. I am not that into those Binding stuff, I am wondering about the  FieldBinding, that seems uncessary now?

File: src/main/java/org/jabref/gui/actions/ActionHelper.java [hunk 1]
```diff
@@ -50,18 +50,23 @@ public static BooleanExpression isAnyFieldSetForSelectedEntry(List<Field> fields
...
-                        return filename.isPresent();
-                    } else {
-                        return false;
-                    }
-                }, stateManager.getSelectedEntries(),
-                stateManager.getSelectedEntries().get(0).getFieldBinding(StandardField.FILE));
+
+        ObservableList<BibEntry> selectedEntries = stateManager.getSelectedEntries();
+        MonadicObservableValue<Boolean> fileIsPresent = EasyBind.monadic(Bindings.valueAt(selectedEntries, 0)).map(entry -> {
+            List<LinkedFile> files = entry.getFiles();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/actions/ActionHelper.java:56]: I think this does not update the status if a file is added to the currently selected entry. For this, the isAnyFieldSetForSelectedEntry method uses `flatMap` instead of `map`.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/actions/ActionHelper.java:56]: I just tested it, it works as well when I add or remove a file to an entry both the context menu and the View menu get updated with the correct status
