### PR TITLE
Fix for issue 6877: Allow users to customize the API Key

### LINKED ISSUE #6877: JabRef should support users entering their own API keys for the lookup services that use API keys
I am running into the same issue as https://github.com/JabRef/jabref/issues/6395 . As per https://github.com/JabRef/jabref/issues/6369#issuecomment-667648423, this is probably Springer rate-limiting JabRef's API key.  If there's no way to permanently fix this problem, I'd suggest adding a dialog box that lets advanced users enter their own API keys, to work around the app-limits.

### PR DESCRIPTION
**Pull request by Ryyyc**
Fixes #6877 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

Changed:
1. Add feature: allows the user to customize the Springer API Key in the customization tab of the preferences and check this key.
2. Update API_URL's protocol of SpringerFetcher to HTTPS.

<br>

Initial default value, do not use custom API key:

preferences-customization-tab

Check success with a valid API key:

successful

Check failed with an invalid API key:

failed

Search using a custom Springer API key:

search-lidar

### CODE REVIEW

**Comment by Ryyyc** [comment]
@calixtus Now I have some difficulties with the preferences, can you give me some help?

I don't know how to get the content of preferences in SpringerFetcher. `org.jabref.gui.Globals` is deprecated, `org.jabref.preferences.JabRefPreferences.getInstance()` is also deprecated, but I have not found a way to replace it.

My current idea is to use the constructor to pass in `org.jabref.preferences.PreferencesService` to construct `org.jabref.logic.importer.fetcher.SpringerFetcher`, which also means that `org.jabref.logic.importer.WebFetchers#getSearchBasedFetchers` needs `PreferencesService`, but its parameter is only `ImportFormatPreferences` and it is dependent on multiple places. 

How should I find the singleton of `org.jabref.preferences.JabRefPreferences`(The only implementation class of `PreferencesService`)?
Should I change the `org.jabref.logic.importer.WebFetchers#getSearchBasedFetchers`'s parameter list or add a member attribute in `WebFetchers`?

File: src/main/java/org/jabref/logic/preferences/SpringerApiKeyPreferences.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package org.jabref.logic.preferences;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/preferences/SpringerApiKeyPreferences.java:1]: I think it makes sense to name this preferences CustomAPIKeyPreferences so it can be expanded to include other fetcher keys as well 
@calixtus  What do you think?

**Comment by Siedlerchr** [comment]
Overall looks good to me, I just think the prefs can be made more generic to hold other custom api keys as well

File: src/main/java/org/jabref/logic/preferences/SpringerApiKeyPreferences.java (hunk 1 above)
Comment (calixtus) [reply src/main/java/org/jabref/logic/preferences/SpringerApiKeyPreferences.java:1]: Me likes it! ;-)

**Comment by Siedlerchr** [comment]
You can simply add the CustomApiKeyPreferences to the ImportFormatPreferences, then you can acess it from the importFormatPreferences and don't need to pass the whole PreferencesService

**Comment by calixtus** [comment]
Do not use ImportFormatPreferences to pass the API keys as this class should be disbanded soon. You can mark it as deprecated if you want.

File: src/main/java/org/jabref/logic/preferences/SpringerApiKeyPreferences.java (hunk 1 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/preferences/SpringerApiKeyPreferences.java]: Now it is **CustomAPIKeyPreferences**, and an attribute `name` is added.

**Comment by Ryyyc** [comment]
> Do not use ImportFormatPreferences to pass the API keys as this class should be disbanded soon. You can mark it as deprecated if you want.

Perhaps **ImportFormatPreferences** can be turned into **CustomPreferences** so that it can carry more user custom content without affecting the original dependencies.

**Comment by Ryyyc** [comment]
The new version of the code allows users to customize more API Keys. Currently, Springer and IEEE are added.

newSpringerEditAPIKey

IEEE-check-connection

Developers can easily add more options here:
https://github.com/Ryyyc/jabref/blob/91cbb1b99492eb6ef2547362bd179f4f00b85693/src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java#L53-L57

Just simply add the name and test URL(remove the value of API key from query parameters) corresponding to the API Key.

**Comment by Ryyyc** [comment]
If the design of ApiKeyItem and ApiKeyPreferences is feasible, I will start to modify and optimize the code.

**Comment by calixtus** [comment]
Just on a first look: why do you want to introduce this class ApiKeyPreferences? This seems to be way more complicated, than it has to be. It looks like you just put another layer around the keys. Just put the get and update and store methods in JabRefPreferences. If you have to, put the API keys into cache on lazy loading.

**Comment by Ryyyc** [comment]
> Just on a first look: why do you want to introduce this class ApiKeyPreferences? This seems to be way more complicated, than it has to be. It looks like you just put another layer around the keys. Just put the get and update and store methods in JabRefPreferences. If you have to, put the API keys into cache on lazy loading.

This makes the logic of management API Key more centralized.

> I like your approach to construct a CustomApiKeyPreferences object for each key. I would just ask to create the list of the available keys not in the viewmodel of the preferences tab, but maybe to return it out of a static method in CustomApiKeyPreferences, maybe called getAvailableKeys, - or - to introduce a new method in the fetcher classes that returns if this fetcher uses a customizable API key and how it is called.

Now the custom API Key is only loaded when the preference tab dialog is opened (CustomizationTabViewModel#setValues()), and cannot be accessed directly through a static method.

<br>

If ApiKeyPreferences is not needed, compare `initApiKeyNameUrl` and `registerApiKey` in CustomizationTabViewModel.

```java
private void initApiKeyNameUrl() {
    // Springer query using the parameter 'q=doi:10.1007/s11276-008-0131-4s=1' will respond faster
    apiKeyNameUrl.put("Springer", "https://api.springernature.com/meta/v1/json?q=doi:10.1007/s11276-008-0131-4s=1&p=1&api_key=");
    apiKeyNameUrl.put("IEEEXplore", "https://ieeexploreapi.ieee.org/api/v1/search/articles?max_records=0&apikey=");
}
```

```java
public static void registerApiKey(String name, String testUrlWithoutApiKey) {
    apiKeyNameUrl.put(name, testUrlWithoutApiKey);
}
```

**Comment by calixtus** [comment]
> This makes the logic of management API Key more centralized.

It is already centralized in the PreferencesService. This class looks in fact like a manager. But I see no need for a manager here.

> Now the custom API Key is only loaded when the preference tab dialog is opened (CustomizationTabViewModel#setValues()), and cannot be accessed directly through a static method.

I don't mean the list of keys, but the list of fetchers, which can use a custom key. This list can be created in a static method.
SetValues doesn't lazy load. It's called right on opening the prefs dialog for every tab. This is not implemented yet.

**Comment by calixtus** [comment]
(Sorry, I edited by accident your comment on my smartphone instead of adding a new one.)

**Comment by tobiasdiez** [comment]
What about introducing a FetcherPreference class, that bundles the stuff used from import preferences (keyword separator) and the customized API-keys? This class can then also have a method `getAPIKey(string fetcherName)` which returns the api key specified by the user, or falls back to `BuildInfo`. Would have the advantage that the fetcher doesn't need to care where the api key are stored resulting an a very flexible design (e.g. it is very easy to add another fetcher for which the api key can be customized in the preferences).

**Comment by Ryyyc** [comment]
> What about introducing a FetcherPreference class, that bundles the stuff used from import preferences (keyword separator) and the customized API-keys? This class can then also have a method `getAPIKey(string fetcherName)` which returns the api key specified by the user, or falls back to `BuildInfo`. Would have the advantage that the fetcher doesn't need to care where the api key are stored resulting an a very flexible design (e.g. it is very easy to add another fetcher for which the api key can be customized in the preferences).

From my understanding, this idea is similar to the above ApiKeyPreferences. The point of view of calixtus is that JabRefPreferences has already done this management work and there is no need to set another layer.

**Comment by Ryyyc** [comment]
> SetValues doesn't lazy load. It's called right on opening the prefs dialog for every tab. This is not implemented yet.

When `org.jabref.gui.preferences.PreferencesDialogView` is initialized, it will call the method **setValues* to load all Tab data, including `CustomizationTab`. Currently, the only way to load data for `CustomizationTabViewModel` is method **setValue**. 
I don't know how to do lazy loading.

**Comment by calixtus** [comment]
Lazy loading is something that goes way beyond this pr and is enough work for a separate one. Implementing lazy loading would in theory mean, that the PreferencesDialogViewModel would have listen to which tab is currently selected and then call the proper setValues method.

**Comment by Ryyyc** [comment]
> Lazy loading is something that goes way beyond this pr and is enough work for a separate one. Implementing lazy loading would in theory mean, that the PreferencesDialogViewModel would have listen to which tab is currently selected and then call the proper setValues method.

Yes, so this should open a new PR for lazy loading tasks

**Comment by calixtus** [comment]
I took a bit of a deeper look into your PR.
Although I like the idea how to change the keys in the prefs dialog very much, the way you store the keys we can not accept, since we really don't want to make the build in keys public. So please remove the getApiKey methods. Instead provide preferences variables which do - if not empty - overwrite the existing build in key in the fetchers.

**Comment by Ryyyc** [comment]
> I took a bit of a deeper look into your PR.
> Although I like the idea how to change the keys in the prefs dialog very much, the way you store the keys we can not accept, since we really don't want to make the build-in keys public. So please remove the getApiKey methods. Instead provide preferences variables which do - if not empty - overwrite the existing build in key in the fetchers.

I don't quite understand what you mean, the getApiKey method is private, it just selects one from the user custom API key (if it exists) and the built-in default key.

**Comment by calixtus** [comment]
Maybe I misunderstood you. :-)

The basic idea should be this:
In JabRefPreferences you keep the keys, which do overwrite build-in keys.
You inject JabRefPreferences as a PreferencesService in the constructor into the fetchers.
In the fetcher you simply check if there is an overwrite-key stored in the preferences, if not, the fetcher uses the build-in key like it does now.

**Comment by Ryyyc** [comment]
> The basic idea should be this:
> In JabRefPreferences you keep the keys, which do overwrite build-in keys.
> You inject JabRefPreferences as a PreferencesService in the constructor into the fetchers.
> In the fetcher you simply check if there is an overwrite-key stored in the preferences, if not, the fetcher uses the build-in key like it does now.

Yes, this is the behavior of the current program.

File: src/main/java/org/jabref/logic/importer/fetcher/IEEE.java [hunk 2]
```diff
@@ -224,12 +226,30 @@ public String getName() {
...
+        JabRefPreferences preferences = null;
+        String apiKey = API_KEY;
+        if (preferences != null) {
+            CustomApiKeyPreferences apiKeyPreferences = preferences.getCustomApiKeyPreferences(getName());
+            if (apiKeyPreferences.isUseCustom()) {
+                apiKey = apiKeyPreferences.getDefaultApiKey();
+            }
+        }
+        return apiKey;
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:245]: ?

File: src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
+package org.jabref.logic.preferences;
+
+public class CustomApiKeyPreferences {
+    private final String name;
+    private boolean useCustom;
+    private String defaultApiKey;
+
+    public CustomApiKeyPreferences(String name, boolean useCustom, String defaultApiKey) {
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java:8]: Why would you keep a defaultApiKey in the preferences? Just throw the logic about defaultApiKey and useCustom away.
Just check in the fetcher, if there is something stored in the preferences and if so, use it. Otherwise use the build-in key in the build info.

Comment (calixtus) [reply src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java:8]: The use custom key stuff would then just be something for the ui in the preferences dialog. The checkbox is activated, if there is a key stored in the preferences. If not, its unchecked. If the preferences are stored, the preferences dialog should check, if the checkbox is checked for use custom, if yes, it should store the user defined key. If not, the key is being thrown away.

Comment (tobiasdiez) [reply src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java:8]: I think you could even go one step further and remove the checkbox. If something is put in the text field it is used as a custom api key.

File: src/main/java/org/jabref/logic/importer/fetcher/IEEE.java (hunk 2 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:245]: I'm sorry to have taken an incorrect name here, defaultApiKey should be renamed to customApiKey.

```
public CustomApiKeyPreferences getCustomApiKeyPreferences(String name) {
    return new CustomApiKeyPreferences(name,
            getBoolean(USE_CUSTOM_API_KEY + name, false),
            get(CUSTOM_API_KEY + name, ""));
}
```
If the API Key is not saved in the preferences, getCustomApiKeyPreferences just returns a default value, in fact, the default value is not saved in the preferences.

One thing that can be modified is that if the API Key requested to save is empty, then clear it

File: src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java (hunk 3 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java:8]: The user can choose not to use the custom API key temporarily, but save it in JabRef, and only need to check the checkbox when reusing it next time.

File: src/main/java/org/jabref/logic/importer/fetcher/IEEE.java (hunk 2 above)
Comment (calixtus) [reply src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:245]: Yes, of course it should store the custom key in the preferences
The preferences and the "default preferences" should not have the default key, which is provided by the build info/GitHub secret.

File: src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java (hunk 3 above)
Comment (calixtus) [reply src/main/java/org/jabref/logic/preferences/CustomApiKeyPreferences.java:8]: Ok, seems fair. Keep the use custom preference.

File: src/main/java/org/jabref/logic/importer/fetcher/IEEE.java (hunk 2 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:245]: The default values are not saved in the preferences.

One question now is how to pass PreferencesService into Fetcher, how about modifying the input parameter ImportFormatPreferences of the getSearchBasedFetchers method to PreferencesService?

Comment (calixtus) [reply src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:245]: > The default values are not saved in the preferences.

So what is `private String defaultApiKey` for? The custom key?

Please get your wording straight. It is impossible to discuss your PR if we continuously talk about different things because your variable names are misleading.

> One question now is how to pass PreferencesService into Fetcher, how about modifying the input parameter ImportFormatPreferences of the getSearchBasedFetchers method to PreferencesService?

This is exactly what I said earlier. https://github.com/JabRef/jabref/pull/7720#issuecomment-835856203 https://github.com/JabRef/jabref/pull/7720#issuecomment-842875913
But don't modify ImportFormatPreferences - replace it with PreferencesService.

Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:245]: I am modifying the variable name, but I want to do PreferencesService related things at the same time.

**Comment by koppor** [comment]
While you are on it @Ryyyc - would it be possible to add a preference for an IEEE key, too?

Refs https://github.com/JabRef/jabref/issues/6376

**Comment by Ryyyc** [comment]
> IEEE-check-connection
> 




> While you are on it @Ryyyc - would it be possible to add a preference for an IEEE key, too?
> 
> Refs #6376

Maybe it is already in the preferences, the name is IEEEXplore, do I need to rename it to IEEE?

**Comment by Ryyyc** [comment]
@calixtus How about this version now? Could you please give some feedback?

File: src/main/java/org/jabref/logic/importer/fetcher/IEEE.java [hunk 4]
```diff
@@ -224,12 +232,28 @@ public String getName() {
         return Optional.of(HelpFile.FETCHER_IEEEXPLORE);
     }
 
+    /**
+     * Gets IEEE api key, use key if it customized it in the preferences, otherwise use the default
+     *
+     * @return IEEE API Key
+     */
+    private String getApiKey() {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:240]: please rename to getIEEApiKey

File: src/main/java/org/jabref/logic/importer/fetcher/IEEE.java [hunk 5]
```diff
@@ -224,12 +232,28 @@ public String getName() {
...
+        String apiKey = API_KEY;
+        if (preferencesService != null) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:242]: You can omit the null check here, that is already covered with Objects.requireNonNull

**Comment by Siedlerchr** [comment]
From my point of view this looks good already

**Comment by Siedlerchr** [comment]
From my point of view this looks good so far. I let @calixtus have the final say

File: src/main/java/org/jabref/logic/importer/fetcher/IEEE.java (hunk 5 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fetcher/IEEE.java:242]: fixed.

**Comment by Ryyyc** [comment]
This PR has been open for a long time, do I need to make any code changes?

**Comment by calixtus** [comment]
We are very sorry for the delay, we are all a bit busy right now and since we work on JabRef in our free time and our top priority in JabRef is right now mentoring our gsoc students, we had to postpone the open prs a little bit. We will review and merge the open prs as soon as we can get into.

**Comment by Ryyyc** [comment]
> We are very sorry for the delay, we are all a bit busy right now and since we work on JabRef in our free time and our top priority in JabRef is right now mentoring our gsoc students, we had to postpone the open prs a little bit. We will review and merge the open prs as soon as we can get into.

Okay, I got it, thank you for your great contribution to JabRef!

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTab.java [hunk 6]
```diff
@@ -26,11 +35,46 @@ public String getTabName() {
         return Localization.lang("Customization");
     }
 
+    /**
+     * Initialize CustomizationTab
+     */
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTab.java:40]: This comment is superfluous

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTab.java [hunk 7]
```diff
@@ -26,11 +35,46 @@ public String getTabName() {
...
+        viewModel.useCustomApiKeyProperty().bind(useCustomApiKeyCheckBox.selectedProperty());
+        useCustomApiKeyText.disableProperty().bind(useCustomApiKeyCheckBox.selectedProperty().not());
+        checkCustomApiKeyButton.disableProperty().bind(useCustomApiKeyCheckBox.selectedProperty().not());
+
+        new ViewModelListCellFactory<CustomApiKeyPreferences>()
+                .withText(CustomApiKeyPreferences::getName)
+                .install(customApiKeyNameComboBox);
+
+        customApiKeyNameComboBox.itemsProperty().bind(viewModel.customApiKeyPrefsProperty());
+        customApiKeyNameComboBox.valueProperty().bindBidirectional(viewModel.selectedCustomApiKeyPrefProperty());
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTab.java:58]: Please avoid abbreviations like Prefs or Pref

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java [hunk 8]
```diff
@@ -23,19 +47,58 @@ public CustomizationTabViewModel(DialogService dialogService, PreferencesService
...
         this.preferencesService = preferencesService;
         this.initialDOIPreferences = preferencesService.getDOIPreferences();
+        initApiKeyNameUrl();
+    }
+
+    private void initApiKeyNameUrl() {
+        // Springer query using the parameter 'q=doi:10.1007/s11276-008-0131-4s=1' will respond faster
+        API_KEY_NAME_URL.put("Springer", "https://api.springernature.com/meta/v1/json?q=doi:10.1007/s11276-008-0131-4s=1&p=1&api_key=");
+        API_KEY_NAME_URL.put("IEEEXplore", "https://ieeexploreapi.ieee.org/api/v1/search/articles?max_records=0&apikey=");
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:57]: Can't those be retrieved directly from the fetchers? (Open-Closed-Principle of clean coding: https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle)

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java [hunk 9]
```diff
@@ -23,19 +47,58 @@ public CustomizationTabViewModel(DialogService dialogService, PreferencesService
...
+     *
+     * @return ArrayList containing Fetcher names
+     */
+    public ArrayList<String> getCustomApiKeyFetchers() {
+        return new ArrayList<>(API_KEY_NAME_URL.keySet());
     }
 
+    /**
+     * Reads user settings when the dialog is opened.
+     */
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:70]: This comment is not specific for that tab, so general comments should go in the abstract class or interface, but not in this class

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java [hunk 10]
```diff
@@ -23,19 +47,58 @@ public CustomizationTabViewModel(DialogService dialogService, PreferencesService
...
+        for (String name : API_KEY_NAME_URL.keySet()) {
+            customApiKeyPreferencesList.add(preferencesService.getCustomApiKeyPreferences(name));
+        }
+        customApiKeyPrefsListProperty.setValue(FXCollections.observableArrayList(customApiKeyPreferencesList));
+        selectedCustomApiKeyPrefProperty.setValue(customApiKeyPreferencesList.get(0));
     }
 
+    /**
+     * Stores user settings when the user presses OK in the Preferences dialog.
+     */
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:87]: Not specific for this tab.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java [hunk 11]
```diff
@@ -23,19 +47,58 @@ public CustomizationTabViewModel(DialogService dialogService, PreferencesService
...
     @Override
     public void storeSettings() {
         preferencesService.storeDOIPreferences(new DOIPreferences(
                 useCustomDOIProperty.getValue(),
                 useCustomDOINameProperty.getValue().trim()));
+        selectedCustomApiKeyPrefProperty.get().useCustom(useCustomApiKeyProperty.get());
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:93]: Maybe better: shouldUseCustomKey(...)

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java [hunk 12]
```diff
@@ -45,4 +108,58 @@ public BooleanProperty useCustomDOIProperty() {
...
+    }
+
+    public void checkCustomApiKey() {
+        final String apiKeyName = selectedCustomApiKeyPrefProperty.get().getName();
+        final String testUrlWithoutApiKey = API_KEY_NAME_URL.get(apiKeyName);
+        final String apiKey = customApiKeyTextProperty.get();
+
+        final String connectionSuccessText = Localization.lang("Connection successful!");
+        final String connectionFailedText = Localization.lang("Connection failed!");
+        final String dialogTitle = Localization.lang("Check %0 API Key Setting", apiKeyName);
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:135]: These strings seem not to be used more than once. You should inline them.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java [hunk 13]
```diff
@@ -45,4 +108,58 @@ public BooleanProperty useCustomDOIProperty() {
...
+            }
+        } else {
+            valid = false;
+        }
+
+        if (valid) {
+            dialogService.showInformationDialogAndWait(dialogTitle, connectionSuccessText);
+        } else {
+            dialogService.showErrorDialogAndWait(dialogTitle, connectionFailedText);
+        }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:162]: On very simple distinctions I would say, that you can use the quick'n'dirty `?` operator. This would mean here:
`dialogService.showInformationDialogAndWait(dialogTitle, valid ? connectionSuccessText : connectionFailedText);`
But i'm not sure about our policy in JabRef right now. Anybody @JabRef/developers ?

File: src/main/java/org/jabref/logic/importer/fetcher/SpringerLink.java [hunk 14]
```diff
@@ -30,6 +32,27 @@
...
+
+    /**
+     * Gets springer api key, use key if it customized it in the preferences, otherwise use the default
+     *
+     * @return Springer API Key
+     */
+    private String getApiKey() {
+        String apiKey = API_KEY;
+        CustomApiKeyPreferences apiKeyPreferences = preferences.getCustomApiKeyPreferences(NAME);
+        if (apiKeyPreferences != null && apiKeyPreferences.isUseCustom()) {
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/importer/fetcher/SpringerLink.java:51]: shouldUseCustom

File: src/main/java/org/jabref/preferences/JabRefPreferences.java [hunk 15]
```diff
@@ -1395,6 +1398,42 @@ public void storeDOIPreferences(DOIPreferences preferences) {
...
+    /**
+     * Removes the value associated with the specified custom api key in this preference node, if any.
+     *
+     * @param name the name of custom api key
+     */
+    @Override
+    public void clearCustomApiKeyPreferences(String name) {
+        prefs.remove(USE_CUSTOM_API_KEY + name);
+        prefs.remove(CUSTOM_API_KEY + name);
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/preferences/JabRefPreferences.java:1435]: I think it's better to store the keys as a list but to make some constant-name-vodoo. Make to lists, one with the names, the second with the keys, maybe the third with the use flag. then create a cache for lazy loading and output the keys for every key when asked.

**Review by calixtus — DISMISSED** [review]
Some nitpicks, some comments, some more serious points.
Thank you already for your great work.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTab.java (hunk 7 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/preferences/customization/CustomizationTab.java:58]: edited.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java (hunk 9 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:70]: deleted.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java (hunk 10 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:87]: deleted.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java (hunk 11 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:93]: fixed.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java (hunk 12 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:135]: fixed.

File: src/main/java/org/jabref/logic/importer/fetcher/SpringerLink.java (hunk 14 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/logic/importer/fetcher/SpringerLink.java:51]: fixed.

File: src/main/java/org/jabref/preferences/JabRefPreferences.java (hunk 15 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:1435]: The value stored in Preferences seems to be only int, long, double, float, boolean, bytearray, String.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java (hunk 8 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:57]: fixed.

File: src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java (hunk 13 above)
Comment (Ryyyc) [reply src/main/java/org/jabref/gui/preferences/customization/CustomizationTabViewModel.java:162]: If the connection test fails, should you use the error dialog or the information dialog?

File: src/main/java/org/jabref/cli/ArgumentProcessor.java [hunk 16]
```diff
@@ -535,7 +535,7 @@ private void regenerateCitationKeys(List<ParserResult> loaded) {
         String engine = split[0];
         String query = split[1];
 
-        Set<SearchBasedFetcher> fetchers = WebFetchers.getSearchBasedFetchers(Globals.prefs.getImportFormatPreferences());
+        Set<SearchBasedFetcher> fetchers = WebFetchers.getSearchBasedFetchers(Globals.prefs);
```
Comment (koppor) [inline src/main/java/org/jabref/cli/ArgumentProcessor.java:538]: @calixtus We should discuss this - on our last devcall, we said, we wanted to keep the preferences objects small. Can't we keep the `ImportFormatPreferences` here?

File: src/main/java/org/jabref/logic/importer/WebFetchers.java [hunk 17]
```diff
@@ -96,11 +98,11 @@ private WebFetchers() {
         set.add(new ACMPortalFetcher());
         // set.add(new GoogleScholar(importFormatPreferences));
         set.add(new DBLPFetcher(importFormatPreferences));
-        set.add(new SpringerFetcher());
+        set.add(new SpringerFetcher(preferencesService));
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/WebFetchers.java:101]: I would pass the `CustomApiKeyPreferences` (`preferenceService.getCustomApiKeyPreferences()`)

File: src/main/java/org/jabref/cli/ArgumentProcessor.java (hunk 16 above)
Comment (calixtus) [reply src/main/java/org/jabref/cli/ArgumentProcessor.java:538]: I was working on this PR yesterday. The problem is, the fetchers are being constructed with the ImportFormatPreferences when combobox with possible fetchers in the sidepane is constructed. If you change the api key afterwards, ImportFormatPreferences is already created and not altered anymore. in that case you would have to restart JabRef everytime you enter a custom api key, if you made a mistake in entering etc. Otherwise by using the preferences service a new api key object is being created on time when needed.
I know, the scope of the preferences service becomes larger, but i wouldn't know any better solution right now.

Comment (Ryyyc) [reply src/main/java/org/jabref/cli/ArgumentProcessor.java]: Timely updates will bring a better user experience, but this is not a frequently used feature, maybe we have to make some compromises.

**Comment by calixtus** [comment]
Two general observations:
- The current design makes some fetchers in the logic package access a static function in the gui package. This should not happen. We probably have to accept that registering keys for some fetchers has to be hardcoded in JabRefPreferences.
- The ImportFormatPreferences are created within the fetchers when the SidePane is created. This means changing the key in the preferences does not have an effect on the ImportFormatPreferences stored in the fetchers, which means JabRef needs to be restarted. Maybe the PreferencesService can be passed through until the performSearch method is called with a fresh instance of ImportFormatPreferences created from the JabRefPreferences.

File: src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java [hunk 18]
```diff
@@ -80,6 +85,21 @@ public String getName() {
         return "SAO/NASA ADS";
     }
 
+    @Override
+    public String getTestUrl() {
+        return null;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fetcher/AstrophysicsDataSystem.java:90]: Make a default method in the interface

File: src/main/java/org/jabref/preferences/JabRefPreferences.java [hunk 19]
```diff
@@ -2831,14 +2827,50 @@ public ImporterPreferences getImporterPreferences() {
...
     }
+
+    private Set<FetcherApiKey> getFetcherKeys() {
+        Set<FetcherApiKey> fetcherApiKeys = new HashSet<>();
+
+        List<String> names = getStringList(FETCHER_CUSTOM_KEY_NAMES);
+        List<String> uses = getStringList(FETCHER_CUSTOM_KEY_USES);
+        List<String> keys = getStringList(FETCHER_CUSTOM_KEYS);
+
+        for (int i = 0; i < names.size(); i++) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/preferences/JabRefPreferences.java:2850]: Why not a normal for each loop?

Comment (Siedlerchr) [reply src/main/java/org/jabref/preferences/JabRefPreferences.java:2850]: Ah okay because of the uses

File: src/main/java/org/jabref/logic/importer/fetcher/CustomizableKeyFetcher.java [hunk 20]
```diff
@@ -0,0 +1,7 @@
+package org.jabref.logic.importer.fetcher;
+
+import org.jabref.logic.importer.WebFetcher;
+
+public interface CustomizableKeyFetcher extends WebFetcher {
+    String getTestUrl();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fetcher/CustomizableKeyFetcher.java:6]: make default

File: src/main/java/org/jabref/gui/preferences/importexport/ImportExportTabViewModel.java [hunk 21]
```diff
@@ -132,4 +157,67 @@ public BooleanProperty grobidEnabledProperty() {
...
+            return;
+        }
+
+        final String apiKey = selectedApiKeyProperty.get().getKey();
+
+        boolean keyValid;
+        if (!apiKey.isEmpty()) {
+            URLDownload urlDownload;
+            try {
+                SSLSocketFactory defaultSslSocketFactory = HttpsURLConnection.getDefaultSSLSocketFactory();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/preferences/importexport/ImportExportTabViewModel.java:201]: Not sure how, but I think this should take the custom SSL store into account

Comment (calixtus) [reply src/main/java/org/jabref/gui/preferences/importexport/ImportExportTabViewModel.java:201]: I am not completely sure, but I strongly believe that SSL is handled by URLDownload or in the DefaultSSlSocketFactory internally. At least I have no place found in our codebase that handles the custom SSL store directly besides the custom SSL preferences. Also the pr that introduced custom SSL certificates did not introduce any custom SSL handling anywhere, but just removed the infamous bypassSSLVerification.

**Comment by koppor** [comment]
@Ryyyc Thank you for your effort. We took the liberty to finalize the PR and include it so that it is available on our next release.
