### PR TITLE
Fix for some Unicode characters in citation keys

### LINKED ISSUE #6583: Bibtex citekey has non-ASCII letters
JabRef version 5.0, MacOS 10.14.16

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I added a citation, and autogenerated a cite key, it contains a non-ASCII letter. 

According to a 7-year old issue:
> The key generator handles accented and other non-ASCII characters by replacement with ASCII characters deemed equivalent. If you have issues where this is not working properly, we'd be happy to look into it.
https://sourceforge.net/p/jabref/bugs/155/

image

```
@InProceedings{bakki2018modèle,
  author = {Aïcha Bakki},
  date   = {2018},
  title  = {Modèle et outil pour soutenir la scénarisation pédagogique de MOOC connectivistes},
  file   = {:/Users/stian/Downloads/Thèse_BAKKI_AICHA_Version_F.pdf:PDF},
  year   = {2018},
}
```

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Fixes #6583 . Some unicode characters can be encoded in multiple ways, and the mapping that `StringUtil#replaceSpecialCharacters` relies on does not contain all cases. The proposed solution uses [NFC](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/text/Normalizer.Form.html#NFC) to re-encode the characters so that these characters can be found.
There exists more information on [Unicode normalization in the Java API](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/text/Normalizer.Form.html#NFC).

My subjective opinion is that most people expect Unicode to work similar to NFC, i.e., if characters looks the same, it is likely that they are equivalent. Hence, if someone debugs issues in the `UNICODE_CHAR_MAP`, they will expect NFC.
A more holistic approach should likely start with the [compatibility equivalence](http://unicode.org/reports/tr15/#Compatibility_Equivalence_Figure), which will require larger changes, and there does not seem to be any bugs/issues that requires these larger changes.

- [x] ~Change in CHANGELOG.md described (if applicable)~
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] ~Screenshots added in PR description (for UI changes)~
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java [hunk 1]
```diff
@@ -1094,4 +1094,12 @@ void generateKeyCorrectKeyLengthWithAuthNofMthAndUnicode() {
 
         assertEquals(4, generateKey(bibEntry, "[auth4_1]").length());
     }
+
+    @Test
+    void generateKeyWithNonNormalizedUnicode() {
+        // https://github.com/JabRef/jabref/issues/6583
```
Comment (calixtus) [inline src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java:1100]: I believe the issue does not need to be linked as the comment, but can be found via git log and blame... @koppor ?

**Review by calixtus — COMMENTED** [review]
Thanks for your work here, one question remaining...

**Review by Siedlerchr — APPROVED** [review]
Thanks, I was not aware of the Normalizhe/Unicode stuff methods. Never heard of them before

File: src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java (hunk 1 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java:1100]: I think you are right on this, I've changed the test cases slightly in the latest commit.
I'd just like to leave a stronger "trail" as this is a patch on the unicode -> Western-* issue. I'll add the caveats to the top part of this PR instead.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr in my opinion it is a mess best avoided if possible X)
I believe NFC is how most people expect Unicode to work (which is why I am using it here), I'll add some more details to the top part of the PR in case someone needs to patch this patch later.

File: src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java (hunk 1 above)
Comment (koppor) [reply src/test/java/org/jabref/logic/citationkeypattern/CitationKeyGeneratorTest.java]: Issue linking should be avoided to have the code self-contained. Larger decisions should go into an ADR. Shorter decisions can go into the code. In case at hand, I just added the issue description as code comment: https://github.com/JabRef/jabref/pull/6938/files#diff-9d2fc955b825e69a852945899b4d62f3

**Review by koppor — APPROVED** [review]
Thank you for the work! LGTM.
