### PR TITLE
Fix bulk imports adding entries to navigation history

### LINKED ISSUE #13878: Remove/prevent "Ghost" navigation history when using importers
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

## Details
During JabCon 2025, we worked on adding some new features and possibly breaking changes. One of these included "[Chronological navigation in libraries](https://github.com/JabRef/jabref/pull/13863)". 
This was essentially an improved "per-tab" version of the same feature which [existed in JabRef 4.x](https://github.com/JabRef/jabref/issues/6352) and was removed in 5.x

### Steps to reproduce the behaviour

1. Open JabRef
2. Open an empty library
3. The navigation (back/forward) buttons should be disabled
4. Bulk-import multiple entries into the library (I imported ~30 entries - I searched for "black hole" via search pre-configured fetcher and imported the first page)
5. See that the navigation buttons are available, and sometimes some sequence of pressing them can take you to certain entries

## Possible hint to solution
When any new entry is added/imported, the maintable selects it via:
https://github.com/JabRef/jabref/blob/e7a5420727d4197585fe4c8037ee10f1ab1a664d/jabgui/src/main/java/org/jabref/gui/LibraryTab.java#L493-L497

to show which entry was last added.
In case of bulk imports, there is no defined order of import (and thus no defined order of selections), and these selections should not be counted in the navigation history.
The challenge will be to track when bulk imports happen and disable the history list updates in such cases.

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by shubhamk0205**
Closes #13878

Prevent bulk import operations from polluting the navigation history. When multiple entries are imported at once, automatic selection changes are now suppressed from being recorded in the navigation history. This ensures that only user-driven navigation actions are tracked, keeping the Back/Forward buttons functional and predictable.

## Steps to test

1. Open JabRef and create a new library
2. Import multiple entries at once (e.g., via File → Import → BibTeX, or drag-and-drop multiple .bib files)
3. After the import completes, verify that:
   - The Back/Forward navigation buttons remain disabled (or show the correct state based on actual user navigation, not the bulk import)
   - Manually selecting different entries adds them to navigation history as expected
   - Using Back/Forward buttons only navigates through entries you actually visited, not entries from the bulk import

**Expected behavior:** Bulk imports should not enable Back/Forward navigation or add entries to navigation history. Only manual entry selections should affect navigation history.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the MIT license
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in CHANGELOG.md in a way that is understandable for the average user (if change is visible to the user)
- [/] I checked the user documentation: Is the information available and up to date? If not, I created an issue at https://github.com/JabRef/user-documentation/issues or, even better, I submitted a pull request updating file(s) in https://github.com/JabRef/user-documentation/tree/main/en.

https://github.com/user-attachments/assets/26915e3d-3ec6-48ec-b6ef-7b53589e74e2

### CODE REVIEW

**Comment by subhramit** [comment]
Please add a video of the fixed functionality.

**Comment by shubhamk0205** [comment]
the jablib unit test is failing for a file i haven't changed 
file - org.jabref.logic.bibtex.comparator.MetaDataDiffTest at line 55

**Comment by shubhamk0205** [comment]
also @subhramit i have added the video please review it .

File: jabgui/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java [hunk 1]
```diff
@@ -341,24 +339,20 @@ public void setAutomaticFields(List<BibEntry> entries) {
...
         if (preferences.getFilePreferences().shouldDownloadLinkedFiles()) {
             entry.getFiles().stream()
                  .filter(LinkedFile::isOnlineLink)
-                 .forEach(linkedFile ->
-                         new LinkedFileViewModel(
-                                 linkedFile,
-                                 entry,
-                                 targetBibDatabaseContext,
-                                 taskExecutor,
-                                 dialogService,
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java:359]: please revert all the unrelated formatting changes throughout the PR.
Also, you can run the respective tests locally to check if they are passing (unit, openrewrite, etc) instead of pushing dummy commits for triggering ci. This causes unnecessary noise to those subscribed to the PR.

**Comment by subhramit** [comment]
@shubhamk0205 you have pushed some commits but on checking files changed, it appears you have not acted on the last review comment. Can you please be a little more mindful and complete them before requesting another review?

**Comment by shubhamk0205** [comment]
hey @koppor , @subhramit 
just wanted to take a follow up on my PR , please let me know if u need any changes in this PR 

-have changed the point of knowledge , now libraryTab decides that is it a bulk import or not instead of importHandler signal .
-have removed unrelated formatting changes .

File: jabgui/src/main/java/org/jabref/gui/NavigationHistory.java [hunk 2]
```diff
@@ -74,4 +79,65 @@ public boolean canGoBack() {
...
+        return suppressionDepth > 0;
+    }
+
+    private void beginSuppression() {
+        suppressionDepth++;
+    }
+
+    private void endSuppression() {
+        if (suppressionDepth > 0) {
+            suppressionDepth--;
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: Hey, can you explain what the crux of `Suppression` as a class is? How exactly did you think of this as a solution?
And what does `suppressionDepth` convey, in simple terms?

It is evident that it works, but we need to brainstorm and ensure that there was no better way to achieve the same thing before going forward with this.

Did you try the two or three solution hints given in the issue? What problems did you face when implementing them?

Comment (shubhamk0205) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: hello @subhramit,
thank you for responding and for the questions.

The main crux of Suppression is that during a bulk import it increases suppressionDepth, which prevents entries from being added to the navigation history. I initially used a boolean flag, but switched to a depth-based approach because a boolean can fail in nested scenarios. For example, if importFile1() internally calls importFile2(), the boolean would be reset after importFile2() finishes, while importFile1() is still running.

As for the other approaches:

Clearing the imported entries afterward felt fragile — for example, if the import crashes midway, adding and then removing entries doesn't make sense .

Disabling auto-selection would break the existing behavior of showing the last imported entry.

Given these trade-offs, disabling history updates during bulk import felt like the most robust option. The main challenge I faced was deciding where this suppression should live architecturally ,  I implemented it as a runWithHistorySuppression() wrapper method in LibraryTab that bulk operation callers use like import handler , drag and drop  .
i am open for making any changes and improving this further , if there’s a cleaner direction

Comment (subhramit) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: > For example, if importFile1() internally calls importFile2(), the boolean would be reset after importFile2() finishes, while importFile1() is still running.

Have you found any concrete examples of that happening in the code?
And if there is, wouldn't switching the boolean flag only at the level of the outermost import call solve it? That is, tracking only the completion of `importFile1()`?

Comment (koppor) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: > where this suppression should live architecturally

History should not suppressed completely, it should "just" be collected into one NamedCompound.

Read on at https://apidia.net/java/OpenJDK/25/?pck=javax.swing.undo&cls=.CompoundEdit for nested undos/redos.

Comment (koppor) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: https://github.com/JabRef/jabref/issues/14686

Comment (koppor) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: Maybe, I mixed it up - this PR is about navigation; I thought, it has a strong relation to undo/redo.

Comment (shubhamk0205) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: > > For example, if importFile1() internally calls importFile2(), the boolean would be reset after importFile2() finishes, while importFile1() is still running.
> 
> Have you found any concrete examples of that happening in the code? And if there is, wouldn't switching the boolean flag only at the level of the outermost import call solve it? That is, tracking only the completion of `importFile1()`?

I checked this and you’re right  @subhramit — in ImportHandler, imports are performed in a loop, not in a recursive way.

 switching the flag only at the outermost level works. A nesting-aware boolean like this would be enough:
```
boolean wasAlreadySuppressed = suppressNavigation;
suppressNavigation = true;
try {
    action.run();
} finally {
    if (!wasAlreadySuppressed) {
        suppressNavigation = false;
    }
}
```
This handles cases where multiple import batches might run sequentially - suppression stays on until all batches complete.

I went with the counter mostly as a defensive choice, but I agree the boolean is simpler and does the job here. Happy to switch to that if you prefer.

Comment (subhramit) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: Please go ahead with it, let us know if you face issues.

Comment (shubhamk0205) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: sure on it !!

**Comment by subhramit** [comment]
@shubhamk0205 https://github.com/JabRef/jabref/pull/14575#discussion_r2617285220
> Also, you can run the respective tests locally to check if they are passing (unit, openrewrite, etc) instead of pushing dummy commits for triggering ci. This causes unnecessary noise to those subscribed to the PR.

Edit - nvm, realized you force-pushed, which recreated the entire commit history.
Please avoid this. If you are having to force-push, there are high chances you are doing something wrong.

**Comment by shubhamk0205** [comment]
> @shubhamk0205 [#14575 (comment)](https://github.com/JabRef/jabref/pull/14575#discussion_r2617285220)
> 
> > Also, you can run the respective tests locally to check if they are passing (unit, openrewrite, etc) instead of pushing dummy commits for triggering ci. This causes unnecessary noise to those subscribed to the PR.
> 
> Edit - nvm, realized you force-pushed, which recreated the entire commit history. Please avoid this. If you are having to force-push, there are high chances you are doing something wrong.

I rebased the branch while syncing with main, which rewrote the commit history and led to the force-push. I understand now why that’s problematic for an active PR.
I’ll avoid rebasing and force-pushing going forward. Thanks for pointing it out. 

CI is currently failing due to the earlier force-push. Would you like me to push a small follow-up commit to re-run it?

**Comment by subhramit** [comment]
> CI is currently failing due to the earlier force-push. Would you like me to push a small follow-up commit to re-run it?

No need to push a dummy commit, as I assume you'll be pushing some more work in upcoming commits anyway (as the current implementation uses both depth as well as what we discussed).

File: jabgui/src/main/java/org/jabref/gui/NavigationHistory.java [hunk 3]
```diff
@@ -74,4 +85,69 @@ public boolean canGoBack() {
...
+        return active ? suppressUpdates() : Suppression.noOp();
+    }
+
+    /**
+     * AutoCloseable guard for suppressing navigation history updates.
+     *
+     * <p>Uses a nesting-aware approach: captures the suppression state when created,
+     * and only restores it if this instance was the one that activated suppression.</p>
+     */
+    public static final class Suppression implements AutoCloseable {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: do we need a separate suppression class anymore? It was made essentially to encapsulate the depth logic right?

Comment (shubhamk0205) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: The class was originally made for the depth logic, but it's still valuable for the boolean approach because each instance stores its own nesting state (`wasAlreadySuppressed`) and ensures automatic cleanup.

if u need any changes do let me know !

**Comment by subhramit** [comment]
> I rebased the branch while syncing with main, which rewrote the commit history and led to the force-push. I understand now why that’s problematic for an active PR.
> I’ll avoid rebasing and force-pushing going forward. Thanks for pointing it out.

Also ref. - [the perils of rebasing](https://gcapes.github.io/git-course/12-rebasing/index.html#warning-the-perils-of-rebasing).

File: jabgui/src/main/java/org/jabref/gui/NavigationHistory.java (hunk 3 above)
Comment (subhramit) [reply jabgui/src/main/java/org/jabref/gui/NavigationHistory.java]: @shubhamk0205 please either decide whether you wish to answer our questions using AI (which we can also do, in which case we would not wait for you) or decide to understand what you are doing and answer yourself.

**Comment by shubhamk0205** [comment]
> > I rebased the branch while syncing with main, which rewrote the commit history and led to the force-push. I understand now why that’s problematic for an active PR.
> > I’ll avoid rebasing and force-pushing going forward. Thanks for pointing it out.
> 
> Also ref. - [the perils of rebasing](https://gcapes.github.io/git-course/12-rebasing/index.html#warning-the-perils-of-rebasing).

I’ve read it  Thanks for the reference , now i totally get it !

**Comment by shubhamk0205** [comment]
hey @koppor ,
just wanted to take a follow up on my PR , is this approach works or we need to change something ?

**Review by koppor — CHANGES_REQUESTED** [review]
Feels like code erosion.

Need to think longer if this is really the right solution.

Things to clarify:

- Live cycle of "NavigationHistory"
- Relation of "NavigationHistory" and imports (are they a back ground task)
- Why is NavigationHistory updated "magically" and why is "setSelectedEntries" called actively?

All of this needs to written down into a documentation - and linked from the code. Currently, the JavaDoc only explains the solution, but not the WHY / alternatives concidered.

File: jabgui/src/main/java/org/jabref/gui/LibraryTab.java [hunk 4]
```diff
@@ -827,14 +827,17 @@ public void insertEntries(final List<BibEntry> entries) {
...
-        importHandler.importCleanedEntries(null, entries);
-        getUndoManager().addEdit(new UndoableInsertEntries(bibDatabaseContext.getDatabase(), entries));
-        markBaseChanged();
-        stateManager.setSelectedEntries(entries);
-        if (preferences.getEntryEditorPreferences().shouldOpenOnNewEntry()) {
-            showAndEdit(entries.getFirst());
-        } else {
-            clearAndSelect(entries.getFirst());
+        // Suppress navigation history during bulk insert to prevent polluting back/forward navigation
+        try (NavigationHistory.Suppression ignored = navigationHistory.suppressUpdatesIf(entries.size() > 1)) {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/LibraryTab.java]: A. Why is this in a try block
B. Why can't this be replaced with an if-condition inside `NavigationHistory` with equivalent logic without all the `Suppression` class complication

**Comment by shubhamk0205** [comment]
Thanks for the feedback @koppor, @subhramit.

I spent some time thinking about this again and I think the current approach has probably become over-engineered.

Looking at the import flow more closely, the issue during bulk imports comes from calling clearAndSelect(entries.getFirst()). That creates a single-entry selection even though the user didn’t actually navigate to that entry. The selection listener then sees entries.size() == 1 and treats it like a normal navigation, so it ends up getting added to the navigation history.

So the real problem seems to be the clearAndSelect() call after a bulk import. It basically simulates a navigation action and pollutes the navigation stack.

Instead of adding suppression logic, a simpler fix would be to only call clearAndSelect() for single-entry imports. For bulk imports (entries.size() > 1), we can just leave all imported entries selected. The listener will then see a multi-entry selection and naturally skip adding anything to the navigation history.

This fixes the issue at the source without touching NavigationHistory or adding extra logic. If this sounds reasonable, I can update the PR in this direction.

**Comment by subhramit** [comment]
> Thanks for the feedback @koppor, @subhramit.
> 
> I spent some time thinking about this again and I think the current approach has probably become over-engineered.
> 
> Looking at the import flow more closely, the issue during bulk imports comes from calling clearAndSelect(entries.getFirst()). That creates a single-entry selection even though the user didn’t actually navigate to that entry. The selection listener then sees entries.size() == 1 and treats it like a normal navigation, so it ends up getting added to the navigation history.
> 
> So the real problem seems to be the clearAndSelect() call after a bulk import. It basically simulates a navigation action and pollutes the navigation stack.
> 
> Instead of adding suppression logic, a simpler fix would be to only call clearAndSelect() for single-entry imports. For bulk imports (entries.size() > 1), we can just leave all imported entries selected. The listener will then see a multi-entry selection and naturally skip adding anything to the navigation history.
> 
> This fixes the issue at the source without touching NavigationHistory or adding extra logic. If this sounds reasonable, I can update the PR in this direction.

Why don't you try it out and see if it works? Since you are relying heavily on AI anyway, experimenting should not take long.

**Comment by shubhamk0205** [comment]
@subhramit @koppor can u provide me some feedback on this

**Comment by subhramit** [comment]
> @subhramit @koppor can u provide me some feedback on this

does it work on your system? a fresh video would be great. I am currently a bit low on time.

**Comment by shubhamk0205** [comment]
> > @subhramit @koppor can u provide me some feedback on this
> 
> does it work on your system? a fresh video would be great. I am currently a bit low on time.

yess this works on my device 

https://github.com/user-attachments/assets/18e75e15-f5bc-46fb-988e-e8481274bec5

File: jabgui/src/main/java/org/jabref/gui/LibraryTab.java [hunk 5]
```diff
@@ -831,10 +850,17 @@ public void insertEntries(final List<BibEntry> entries) {
         getUndoManager().addEdit(new UndoableInsertEntries(bibDatabaseContext.getDatabase(), entries));
         markBaseChanged();
         stateManager.setSelectedEntries(entries);
-        if (preferences.getEntryEditorPreferences().shouldOpenOnNewEntry()) {
-            showAndEdit(entries.getFirst());
-        } else {
-            clearAndSelect(entries.getFirst());
+
+        // Only show/select individual entry for single-entry imports.
+        // For bulk imports (size > 1), leave all entries selected.
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/LibraryTab.java]: This comment is confusing - so selection happens in case of both single and multiple entries?
Where is the code for "leaving all entries selected"? Because it will neither trigger the if nor else case.

The side effect of this can be - check if earlier on bulk import all entries were actually selected, because otherwise now if they are not selected, lets say the user wants to remove all the entries imported just after the import action, they will have to manually select the imported entries again first instead of just clicking delete,

Comment (shubhamk0205) [reply jabgui/src/main/java/org/jabref/gui/LibraryTab.java]: You’re right — my bad. I forgot to update the comment. I’ll fix it to accurately describe skipping clearAndSelect() for bulk imports.

Comment (shubhamk0205) [reply jabgui/src/main/java/org/jabref/gui/LibraryTab.java]: > check if earlier on bulk import all entries were actually selected, because otherwise now if they are not selected, lets say the user wants to remove all the entries imported just after the import action, they will have to manually select the imported entries again first instead of just clicking delete,

i checked this ,on bulk import all the entries were not selected , only the first entry was selected from the bulk import

Comment (subhramit) [reply jabgui/src/main/java/org/jabref/gui/LibraryTab.java]: > You’re right — my bad. I forgot to update the comment. I’ll fix it to accurately describe skipping clearAndSelect() for bulk imports.

This is a final heads up to not use AI to communicate. You will be blacklisted from the project if you don't respect our [guidelines on using AI](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md#ai-usage-policy).

Comment (shubhamk0205) [reply jabgui/src/main/java/org/jabref/gui/LibraryTab.java]: @subhramit i used ai to refine my speech so i can communicate better , but from going forward i will be writing directly here .

**Comment by Siedlerchr** [comment]
[6](https://github.com/JabRef/jabref/actions/runs/21373986928/job/61525481411?pr=14575#step:4:1627)
/home/runner/work/jabref/jabref/jabgui/src/main/java/org/jabref/gui/LibraryTab.java:815: error: unexpected content
    /// @see [Issue #13878](https://github.com/JabRef/jabref/issues/13878)
