### PR TITLE
Fix preview settings not saved due to l10n

### LINKED ISSUE #6447: Changes in entry preview are not saved
JabRef 5.1--2020-05-04--b5599c9
Linux 4.9.0-12-amd64 amd64 
Java 14.0.1

Changes in the entry preview format are accounted for _only_ after restarting.

Note 1:  may seem similar to issue #5464, but the present issue is about _the content_ of the preview.
Note 2: issue is present with "Show preview as tab in entry editor" checked or unchecked.

1. Create a file with the following entry and save it
```
@Article{MyKey,
  author    = {Author1, Surname1 and Author2 Surname2},
  journal   = {The Journal title},
  title     = {The title of the article},
  year      = {2020},
  number    = {12},
  pages     = {1-100},
  volume    = {15},
 }
```
2. Go to Options -> Preferences -> Entry preview
3. Select "Preview" in the column "Selected"
4. Click on the Edit tab
5. Change
`\begin{journal} <em>\format[HTMLChars]{\journal}, </em>\end{journal}`
into
`\begin{journal} <em>\format[HTMLChars]{\journal},HereIsMyChange </em>\end{journal}`
6. Go to the preview Tab.
    ==> The preview is updated accordingly.
7. Click on save
8. Edit the entry
The preview shows: 
Capture du 2020-05-08 15-26-09
   `HereIsMyChange` is not displayed ==> The preview is NOT updated.
8. Close and reopen JabRef
9. Edit the entry
The preview shows: 
Capture du 2020-05-08 15-20-54
     `HereIsMyChange` is displayed  ==> The preview is updated NOW.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Introduce internal name for finding layout
Fixes #6447

The problem was that the getName method returned a l10n name for Custom Preview layout.....

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java [hunk 1]
```diff
@@ -91,8 +91,9 @@ public PreviewTabViewModel(DialogService dialogService, PreferencesService prefe
         initialPreviewPreferences = preferences.getPreviewPreferences();
 
         sourceTextProperty.addListener((observable, oldValue, newValue) -> {
-            if (getCurrentLayout() instanceof TextBasedPreviewLayout) {
-                ((TextBasedPreviewLayout) getCurrentLayout()).setText(sourceTextProperty.getValue().replace("\n", "__NEWLINE__"));
+            var currentLayout = getCurrentLayout();
+            if (currentLayout instanceof TextBasedPreviewLayout) {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java:95]: Does patternmatching with instanceof already work?
```
            if (getCurrentLayout() instanceof TextBasedPreviewLayout currentLayout) {
```

File: src/main/java/org/jabref/logic/layout/TextBasedPreviewLayout.java [hunk 2]
```diff
@@ -54,6 +55,11 @@ public String getText() {
...
     }
 
+    @Override
+    public String getInternalName() {
+        return NAME;
+    }
+
     @Override
     public String getName() {
         return Localization.lang("Customized preview style");
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/layout/TextBasedPreviewLayout.java:65]: I would suggest you use getDisplayName() instead of getName() and getName() instead of getInternalName()

**Review by calixtus — COMMENTED** [review]
One question and one suggestion. 😃

File: src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java:95]: Unfortunately in jdk14 it's still a preview feature.
