### PR TITLE
Fix attach file does not relativize file path

### LINKED ISSUE #4241: added file link has absolute instead of relative path
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.3.1 on Windows 10

Jabref generates an absolute path to file if the relative path would "climb" the directory tree

Steps to reproduce:
0. assume you have a file "C:\foo\file.pdf"
1. set file directory (whether main, general, or user-specific) to "C:\bar"
2. right click on any JabRef entry -> select "Attach file"
3. navigate to and select "C:\foo\file.pdf"
4. The path to file will be stored in absolute format "C:\foo\file.pdf" instead of relative "..\foo\file"

Note that JabRef (at least on Windows) still handles correctly relative paths which include "..\" (or start with "\\") as long as you type them yourselves.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #4241 

Attached files were only made relative before if you hit the browse button

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/filelist/LinkedFilesEditDialogViewModel.java [hunk 1]
```diff
@@ -128,4 +128,12 @@ public LinkedFile getNewLinkedFile() {
         return new LinkedFile(description.getValue(), link.getValue(), monadicSelectedExternalFileType.map(ExternalFileType::toString).getOrElse(""));
     }
 
+    private void relativizeFile() {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/filelist/LinkedFilesEditDialogViewModel.java]: Right now, it is hard to tell from the outside on which path this methods operates. I would thus prefer if `relativizeFile` would accept a path and return the relativized path (probably also rename to `relativize[Path]`). Then in would look like `link.set(relativize(path))`.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/filelist/LinkedFilesEditDialogViewModel.java]: I already had considered this option as well, but seem to forget about it ;)
