### PR TITLE
fix:Libre office reference extension after adding spaces.

### LINKED ISSUE #13559: LibreOffice Writer and JabRef
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I open a "LibreOffice Writer" file
2. I insert a reference with JabRef 
3. I place the cursor at the end of the reference
4. I press the "space button"
=> Problem : The reference is extended, so I can't add more text after the reference

### Appendix

Image

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by tushar-2320**
Closes #13559 

I have added ```Add space after citation``` in settings of open office panel.
screen recording of it is as follows.

https://github.com/user-attachments/assets/a8ff12c1-932f-4cc9-b5a2-15351dbe8783

so now by selecting checkbox we get space after citation.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [/] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by subhramit** [comment]
Please provide an appropriate name and description to your PR, even if draft.

**Comment by subhramit** [comment]
Hey, let me know if you need any help continuing this.

**Comment by tushar-2320** [comment]
Hey I got preferences but i am not able to understand flow how do change the Boolean value from settings @subhramit

**Comment by subhramit** [comment]
> Hey I got preferences but i am not able to understand flow how do change the Boolean value from settings @subhramit

See how the first setting in the screenshot in the issue is set (automatically sync bibliography) for example. That's also a boolean, right?

**Comment by tushar-2320** [comment]
hey @subhramit just check wether I am in right direction or not?

File: jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java [hunk 1]
```diff
@@ -645,6 +645,9 @@ private ContextMenu createSettingsPopup() {
         CheckMenuItem autoSync = new CheckMenuItem(Localization.lang("Automatically sync bibliography when inserting citations"));
         autoSync.selectedProperty().set(openOfficePreferences.getSyncWhenCiting());
 
+        CheckMenuItem smartSpace = new CheckMenuItem(Localization.lang("Add smart space after citation"));
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java]: The space we add before citations are called "smart" because they are aware of if a space already exists.
For the space after, we are just adding it if an option is manually enabled, so change this to 'add space after citations"

File: jablib/src/main/java/org/jabref/logic/openoffice/OpenOfficePreferences.java [hunk 2]
```diff
@@ -38,6 +38,7 @@ public class OpenOfficePreferences {
     private final StringProperty cslBibliographyHeaderFormat;
     private final StringProperty cslBibliographyBodyFormat;
     private final ObservableList<String> externalCslStyles;
+    private final BooleanProperty smartSpaceAfter;
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/OpenOfficePreferences.java]: Have to rename all these variables and methods due to above explanation.

File: jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java [hunk 3]
```diff
@@ -297,7 +297,7 @@ public class JabRefCliPreferences implements CliPreferences {
     public static final String OO_CSL_BIBLIOGRAPHY_TITLE = "cslBibliographyTitle";
     public static final String OO_CSL_BIBLIOGRAPHY_HEADER_FORMAT = "cslBibliographyHeaderFormat";
     public static final String OO_CSL_BIBLIOGRAPHY_BODY_FORMAT = "cslBibliographyBodyFormat";
-
+    public static final String OO_SMART_SPACE_AFTER = "ooSmartSpaceAfter";
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java]: Rename everywhere

**Comment by tushar-panto** [comment]
I tried to make changes around ```CSLCitationooadapter``` property  just check it is this how its done @subhramit .?

**Comment by subhramit** [comment]
> I tried to make changes around `CSLCitationooadapter` property just check it is this how its done @subhramit .?

Unfortunately, that's not the right way. I get your thought process, but you had to use preferences, not ~the injector~ injection via constructor. See, for example, how the current style is obtained in the class from preferences. Since preferences are already imported and initialized in the class, why not use them?

PS - if this explanation is unclear, please do ask for more clarification. The reason I'm not giving you the solution right away is so that you learn something when navigating the codebase as well.
When following an example, try to understand what it is doing rather than just making an equivalent copy-paste.

**Comment by tushar-2320** [comment]
now can you check @subhramit ?

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 4]
```diff
@@ -52,6 +52,7 @@ public class CSLCitationOOAdapter {
 
     private CitationStyle currentStyle;
     private boolean styleChanged;
+    private boolean addSpaceAfter;
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Remove

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 5]
```diff
@@ -61,7 +62,7 @@ public CSLCitationOOAdapter(XTextDocument doc, Supplier<List<BibDatabaseContext>
         this.openOfficePreferences = openOfficePreferences;
 
         OOStyle initialStyle = openOfficePreferences.getCurrentStyle(); // may be a jstyle, can still be used for detecting subsequent style changes in context of CSL
-
+        this.addSpaceAfter = openOfficePreferences.getAddSpaceAfter();
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Remove

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 6]
```diff
@@ -243,8 +244,7 @@ private void insertReferences(XTextCursor cursor, List<BibEntry> entries, OOText
                 preceedingSpaceExists = checkCursor.getString().matches("\\R");
             }
         }
-
-        markManager.insertReferenceIntoOO(entries, document, cursor, ooText, !preceedingSpaceExists, false);
+        markManager.insertReferenceIntoOO(entries, document, cursor, ooText, !preceedingSpaceExists, addSpaceAfter);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Use this
```suggestion
        markManager.insertReferenceIntoOO(entries, document, cursor, ooText, !preceedingSpaceExists, openOfficePreferences.getAddSpaceAfter());
```

Reason: The setting may have changed after the instantiation of the adapter.

**Review by subhramit — CHANGES_REQUESTED** [review]
Few comments on correctness.
After you are done with these, add a changelog entry, move the PR away from draft, mark the mandatory checks, write a description and post a short screen recording of the changes.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java [hunk 7]
```diff
@@ -645,6 +645,10 @@ private ContextMenu createSettingsPopup() {
         CheckMenuItem autoSync = new CheckMenuItem(Localization.lang("Automatically sync bibliography when inserting citations"));
         autoSync.selectedProperty().set(openOfficePreferences.getSyncWhenCiting());
 
+        CheckMenuItem addSpaceAfter = new CheckMenuItem(Localization.lang("Add  space after citation"));
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java]:
```suggestion
        CheckMenuItem addSpaceAfter = new CheckMenuItem(Localization.lang("Add space after citation"));
```

Comment (subhramit) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java]: Also, add the keys to the [localization](https://devdocs.jabref.org/code-howtos/localization.html#:~:text=All%20labeled%20UI%20elements%2C%20descriptions,each%20String%20to%20be%20localized.) `JabRef_en.properties` file (see the failing check).

File: jablib/src/main/resources/l10n/JabRef_en.properties [hunk 8]
```diff
@@ -1170,6 +1170,7 @@ Problem\ during\ separating\ cite\ markers=Problem during separating cite marker
 
 Automatically\ add\ "Cited\ on\ pages..."\ at\ the\ end\ of\ bibliographic\ entries=Automatically add "Cited on pages..." at the end of bibliographic entries
 Automatically\ sync\ bibliography\ when\ inserting\ citations=Automatically sync bibliography when inserting citations
+"Add\ space\ after\ citation"=Add  space after citation
```
Comment (subhramit) [inline jablib/src/main/resources/l10n/JabRef_en.properties]: Why the extra space above and here? You can click commit suggestion in https://github.com/JabRef/jabref/pull/13592/files#r2253606699 and below:
```suggestion
"Add\ space\ after\ citation"=Add space after citation
```

File: jablib/src/main/resources/l10n/JabRef_en.properties [hunk 9]
```diff
@@ -1170,6 +1170,7 @@ Problem\ during\ separating\ cite\ markers=Problem during separating cite marker
 
 Automatically\ add\ "Cited\ on\ pages..."\ at\ the\ end\ of\ bibliographic\ entries=Automatically add "Cited on pages..." at the end of bibliographic entries
 Automatically\ sync\ bibliography\ when\ inserting\ citations=Automatically sync bibliography when inserting citations
+"Add\ space\ after\ citation"=Add space after citation
```
Comment (subhramit) [inline jablib/src/main/resources/l10n/JabRef_en.properties]: Please look at 1. Other example entries. And/or 2. Failing checks by clicking on them to get hints as to which tests are failing. The bot comments already instruct on this.

In this case, you have to remove the quotes. There should be no quotes, unless they are a part of the string itself.
```suggestion
Add\ space\ after\ citation=Add space after citation
```

**Review by subhramit — CHANGES_REQUESTED** [review]

**Comment by tushar-2320** [comment]
@subhramit can you check screen recording?

**Comment by subhramit** [comment]
> @subhramit can you check screen recording?

Yep, that's correct. I tried out myself, works properly.

Mow please add a changelog entry and mark the pr non-draft (ready for review).

File: CHANGELOG.md [hunk 10]
```diff
@@ -11,6 +11,7 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
 
 ### Added
 
+- We added 'Add space after citation' in settings of open office panel. [#13559](https://github.com/JabRef/jabref/issues/13559)
```
Comment (subhramit) [inline CHANGELOG.md]:
```suggestion
- A space is now added by default after citations inserted via the Libre/OpenOffice integration. [#13559](https://github.com/JabRef/jabref/issues/13559)
- We added the option to configure 'Add space after citation' in settings of the Libre/OpenOffice panel. [#13559](https://github.com/JabRef/jabref/issues/13559)
```

**Review by subhramit — APPROVED** [review]
I refined the changelog entry a bit, rest lgtm

**Review by subhramit — APPROVED** [review]

**Comment by tushar-2320** [comment]
Thank you @subhramit for guiding me.
