### PR TITLE
Fix/citation relations doi case insensitive

### LINKED ISSUE #12967: Citation relations tab doesn't work properly!
### JabRef version

 **JabRef 6.0-alpha.493--2025-04-18--224290a**

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 24.04 (64 bit)

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Citation relations are a very useful feature of JabRef, But very often this function does not work correctly.

To make sure of this, you need to take the following steps:

1. For example create the biblatex entry like this:

      ```biblatex
      @Article{Raftari_2015_Self_V_118_N_20_EN,
        author       = {Raftari, B. and Budko, N. V. and Vuik, C.},
        date         = {2015},
        doi          = {10.1063/1.4936201},
        file         = {:2015_Self-consistent_drift-diffusion-reaction_model_[SDMFTEBIWDS]_V_118_N_20_(B_Raftari).pdf:PDF},
        groups       = {eBook, Charging Models, SiO2, Al2O3, GR},
        journal      = {Journal of Applied Physics},
        journaltitle = {Journal of Applied Physics},
        language     = {english},
        number       = {20},
        pages        = {204101},
        status       = {checked},
        title        = {Self-consistent drift-diffusion-reaction model for the electron beam interaction with dielectric samples},
        volume       = {118},
        xmp_metadata = {+},
        availability = {on},
        priority     = {prio2},
        publisher    = {AIP Publishing},
        readstatus   = {skimmed},
      }
      ```

2. In an open Entry, open the **Citation relations** and after download the **Cited by** tab and scroll down to **Numerical simulation of electron beam-induced dielectric charging using advanced computational scheme for solving semilinear reaction-diffusion equation **. After that, add selected entry to the database.

   Next we see that the bib record was added with the **wrong Entry type Misc**, but the original type is InProceedings. Of course this is not the main problem!

3. Reload the JabRef or the entry (Raftari_2015_Self_V_118_N_20_EN) to see the changes in the Citation relations -> Cited By. Now we see that **Pavelchuk's** article that quotes **Raftari** has been added to our library and is highlighted in green. It works correctly!

4. As an example, you just need to change the bookmark type from **Misk** (for just added Entry of the **Pavelchuk**) for example to a book or article and open the **Raftari** Entry again.  Looking through the Citation relations -> Cided By for the **Raftari** Entry, we see that **Pavelchuk's** article has disappeared from those added to the library, although it is actually present in the library.

This is far from the only example when the program does not see already added elements. Especially if they were added not through the Cited By utility but by citation on the articles's website.

Often, simply changing lowercase characters to uppercase in the DOI will produce these results.

### PR DESCRIPTION
**Pull request by Syimyk43**
### Related issues and pull requests

Closes #12967 

### PR Description

The haveSameIdentifier method in DuplicateCheck.java compared identifier fields like DOI using case-sensitive equality. DOIs are case insensitive identifiers, these caused the Citation Relations tab to miss papers that are in the library when their stored DOI differed in letter casing from the fetched result. I changed the way how it checks for equality, equals() with .equalsIgnoreCase() so that DOI comparisons correctly treat two DOIs that differ only in letter casing as the same identifier, as required by the official DOI specification.

### Steps to test

1) Open JabRef and add any entry with a DOI field
2) Add a second unrelated entry with the same DOI but change some letters to uppercase
3) Run Quality then Find duplicates
4) Before fix: the two entries are not detected as duplicates
5) After fix: the two entries are correctly detected as duplicates

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [/] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java [hunk 1]
```diff
@@ -400,6 +400,23 @@ void twoEntriesWithSameDoiButDifferentTypesAreDuplicates() {
         assertTrue(duplicateChecker.isDuplicate(simpleArticle, duplicateWithDifferentType, BibDatabaseMode.BIBTEX));
     }
 
+    @Test
+    void twoEntriesWithSameDoiButDifferentCasingAreDuplicates() {
```
Comment (Siedlerchr) [inline jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java:404]: somehow the formatter complains at this file, please take a look

Comment (Syimyk43) [reply jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java:404]: Thank you for the review @Siedlerchr! Im working on that.

File: jablib/src/main/java/org/jabref/logic/database/DuplicateCheck.java [hunk 2]
```diff
@@ -33,6 +33,7 @@
 
 /// This class contains utility method for duplicate checking of entries.
 public class DuplicateCheck {
+
```
Comment (Siedlerchr) [inline jablib/src/main/java/org/jabref/logic/database/DuplicateCheck.java]: Revert the formatting here! The CI check says that it's the test file!!

File: jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java (hunk 1 above)
Comment (Siedlerchr) [reply jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java:404]: The formatting issue is in the test clase! Please read the failing CI output

Comment (Siedlerchr) [reply jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java:404]: I fixed it now

Comment (Syimyk43) [reply jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java:404]: Thank you for fixing the formatting and for reviewing my PR.

I tried to follow your instruction, but there was a problem, my intelliJ was in auto-format, then I disabled it. However I still had the same problem.
Do you know what is the problem? What should I do to fix it?

Comment (Siedlerchr) [reply jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java:404]: Just follow the instructions how to setup the formatter https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html

Comment (Syimyk43) [reply jablib/src/test/java/org/jabref/logic/database/DuplicateCheckTest.java:404]: Got you, thank you so much!
