### PR TITLE
Fix Normalize pages formatter not replacing dashes

### LINKED ISSUE #7239: Export to MODS format fails (wrong dash in pages field)
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64 
Java 14.0.2

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

This error happens on the v5.2 stable.

1. Export to MODS xml
2. error (see below)

<details>
  <summary>Log File</summary>
  
  ```
  java.lang.NumberFormatException: For input string: "R404–R405"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.math.BigInteger.<init>(Unknown Source)
	at java.base/java.math.BigInteger.<init>(Unknown Source)
	at org.jabref@5.2.60000/org.jabref.logic.exporter.ModsExporter.addPages(Unknown Source)
	at org.jabref@5.2.60000/org.jabref.logic.exporter.ModsExporter.export(Unknown Source)
	at org.jabref@5.2.60000/org.jabref.gui.exporter.ExportCommand.lambda$export$2(Unknown Source)
	at org.jabref@5.2.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.2.60000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.2.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #7239

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java [hunk 1]
```diff
@@ -63,7 +64,8 @@ public String format(String value) {
         // Remove pages prefix
         String cleanValue = value.replace("pp.", "").replace("p.", "");
         // remove unwanted literals including en dash, em dash, and whitespace
-        cleanValue = cleanValue.replaceAll("\u2013|\u2014", "-").replaceAll(REJECT_LITERALS, "");
+        cleanValue = EM_EN_DASH_PATTERN.matcher(cleanValue).replaceAll("-");
+        cleanValue = REJECT_LITERALS_PATTERN.matcher(cleanValue).replaceAll("");
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:68]: I think this may result in unwanted changes. The formatter should only format pages if they are "kind of" in the right format. Now something like `40&50` is changed to `4050`.

File: src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java [hunk 2]
```diff
@@ -63,7 +64,8 @@ public String format(String value) {
         // Remove pages prefix
         String cleanValue = value.replace("pp.", "").replace("p.", "");
         // remove unwanted literals including en dash, em dash, and whitespace
-        cleanValue = cleanValue.replaceAll("\u2013|\u2014", "-").replaceAll(REJECT_LITERALS, "");
+        cleanValue = EM_EN_DASH_PATTERN.matcher(cleanValue).replaceAll("-");
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:67]: I would put this into the `PAGES_DETECT_PATTERN`.

**Review by tobiasdiez — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:67]: No, it makes sense to first replace all occurrences of en/em dashes before using pages detect pattern with a minus.

Comment (mlep) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:67]: @Siedlerchr In BibTeX, an em-dash is ---, and an en-dash is --. Maybe the replacement should enforce this?

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:67]: In pages you can either have a minus or a -- https://www.bibtex.com/f/pages-field/ at least that's what the mods exporter expects

Comment (mlep) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:67]: The URL you give mentions "It is standard to use an en-dash (“--”) to separate a page range." 😉

Comment (tobiasdiez) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:67]: > No, it makes sense to first replace all occurrences of en/em dashes before using pages detect pattern with a minus.

What are the advantages of this approach? I only see that the performance is worse as you apply to regex per string instead of only one.

I also agree with mlep, that `--` is the desired format (and that also the format that the formatter produces). But this already covered by the part `?:-{1,2}` in the regex.

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:67]: I looked a bit into it, the problem is that for the test case R404-R405 the page detect pattern regex does not match anything non-numeric and therefore would return the orginal value.

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java]: I would suggest we weaken the regex to follow the biblatex def: (2.2.1)
>A range is somethingoptionally followed by one or more dashes optionally followed by some non-dash (e.g.5--7).

**Comment by Siedlerchr** [comment]
For devCall: 
```

I would suggest we weaken the regex to follow the biblatex def: (2.2.1)

    A range is something optionally followed by one or more dashes optionally followed by some non-dash (e.g.5--7).


```

File: src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java]: Fixed in the new commit

**Comment by koppor** [comment]
As a follow-up to https://github.com/JabRef/jabref/pull/1013, I added `UnprotectTermsFormatter`. I was not sure about the naming, because it is not an opposite one (https://github.com/JabRef/jabref/issues/920#issuecomment-195779352). `UnfreezeAllWords` was the old proposal.

The discussion continued at https://github.com/JabRef/jabref/issues/920#issuecomment-196747008

File: src/test/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatterTest.java [hunk 3]
```diff
@@ -10,102 +13,76 @@
...
+                // replaceDashWithMinus
+                Arguments.of("R404--R405", "R404–R405"));
     }
 
-    @Test
-    public void formatExample() {
-        assertEquals("1--2", formatter.format(formatter.getExampleInput()));
+    @ParameterizedTest
+    @MethodSource("tests")
+    public void test(String expected, String toFormat) {
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatterTest.java:85]: input -> expected order makes more sense

File: src/main/java/org/jabref/logic/formatter/casechanger/UnprotectTermsFormatter.java [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+            // in case of unbalanced braces, the original text is returned unmodified
+            return text;
+        }
+        return result.toString();
+    }
+
+    @Override
+    public String getDescription() {
+        return Localization.lang(
+                "Removes all {} brackets around words.");
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/formatter/casechanger/UnprotectTermsFormatter.java:46]: add "balanced" ?

File: src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java [hunk 5]
```diff
@@ -63,19 +65,9 @@ public String format(String value) {
...
-                return matcher.replaceFirst(SINGLE_PAGE_REPLACE_PATTERN);
-            } else {
-                return matcher.replaceFirst(PAGES_REPLACE_PATTERN);
-            }
-        }
-        // no replacement
-        return value;
+        value = EM_EN_DASH_PATTERN.matcher(cleanValue).replaceAll("-")
+                                  .replaceAll("[ ]*[-]+[ ]*", "--");
+        return unprotectTermsFormatter.format(value.trim());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:70]: This now formats all kinds of text, e.g. `pages  1-50`, `some-text-with-dashes` and `{A}`. I think this is not desired. I would keep it conservative: it's probably more annoying for users if hand-formatted page numbers are destroyed than if some cases need to be formatted by the user itself.

The biblatex documentation is not specific about the the type of characters that are allowed, and I'm also not sure if `I-X` is correct or `I--X` for roman page numbers.

**Review by tobiasdiez — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java (hunk 5 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java:70]: Result of test-driven-development 😇. I will think more about it now.

**Comment by koppor** [comment]
Regarding the case `pages 1-50`, I was unsure. I opted to also to reformat them.

File: src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java (hunk 5 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/formatter/bibtexfields/NormalizePagesFormatter.java]: > I'm also not sure if `I-X` is correct or `I--X` for roman page numbers.

This reads more as a page range, too. Roman 9 is written IX (and not I-X), isn't it?

**Review by koppor — APPROVED** [review]

**Review by calixtus — APPROVED** [review]
