### PR TITLE
Show Citation style also in entry preview in preferences

### LINKED ISSUE #3849: Preview Pane does not show CSL styles
JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Linux 4.13.0-36-generic amd64 
Java 1.8.0_161

Steps to reproduce:

1. Select Options / Preferences / Entry preview

2. Choose a "Current preview" and move it to the right pane

3. The "preview" pane at the bottom does not show the formatting of the selected preview style.  It always shows the same, namely: 

> <font face="sans-serif"><b><i>\bibtextype</i><a name="\bibtexkey">\begin{bibtexkey} (\bibtexkey)</a>\end{bibtexkey}</b><br>
> \begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\author}<BR>\end{author}
> \begin{editor} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\editor} <i>(\format[IfPlural(Eds.,Ed.)]{\editor})</i><BR>\end{editor}
> \begin{title} \format[HTMLChars]{\title} \end{title}<BR>
> \begin{chapter} \format[HTMLChars]{\chapter}<BR>\end{chapter}
> \begin{journal} <em>\format[HTMLChars]{\journal}, </em>\end{journal}
> \begin{booktitle} <em>\format[HTMLChars]{\booktitle}, </em>\end{booktitle}
> \begin{school} <em>\format[HTMLChars]{\school}, </em>\end{school}
> \begin{institution} <em>\format[HTMLChars]{\institution}, </em>\end{institution}
> \begin{publisher} <em>\format[HTMLChars]{\publisher}, </em>\end{publisher}
> \begin{year}<b>\year</b>\end{year}\begin{volume}<i>, \volume</i>\end{volume}\begin{pages}, \format[FormatPagesForHTML]{\pages} \end{pages}
> \begin{abstract}<BR><BR><b>Abstract: </b> \format[HTMLChars]{\abstract} \end{abstract}
> \begin{review}<BR><BR><b>Review: </b> \format[HTMLChars]{\review} \end{review}</dd>
> <p></p></font>

4. pressing "test" always shows the same formatting, which is not the styling of the selelcted preview format,  See screenshot below.

screenshot from 2018-03-14 10-12-03

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Opening: /home/dom/Dropbox/Projects/HSSA/issue 5.2 rasayana issue/07 Sehnalova/paper/sehnalova.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
```

</details>

### PR DESCRIPTION
**Pull request by eso31**
Fixes [#3849](https://github.com/JabRef/jabref/issues/3849)

It works, now you can have a preview of a selected citation style. I am not sure if it is the correct way of programming it though. Let me now if I should do it in some other way or try a different approach.

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java [hunk 1]
```diff
@@ -126,8 +131,19 @@ private void setupLogic() {
                 DefaultTaskExecutor.runInJavaFXThread(() -> {
 
                     PreviewPanel testPane = new PreviewPanel(null, null, Globals.getKeyPrefs(), Globals.prefs.getPreviewPreferences(), dialogService);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java]: Here null is passed for BasePanel and bibdatabasecontext,

File: src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java [hunk 2]
```diff
@@ -126,8 +131,19 @@ private void setupLogic() {
...
+                    if (chosen.isSelectionEmpty()) {
+                        testPane.setFixedLayout(layout.getText());
+                        testPane.setEntry(TestEntry.getTestEntry());
+                    }
+                    else {
+                        int indexStyle = chosen.getSelectedIndex();
+                        PreviewPreferences p = Globals.prefs.getPreviewPreferences();
+                        p = new PreviewPreferences(p.getPreviewCycle(),indexStyle,p.getPreviewPanelDividerPosition(),p.isPreviewPanelEnabled(), p.getPreviewStyle(),p.getPreviewStyleDefault());
+
+                        testPane = new PreviewPanel(Globals.basePanel, new BibDatabaseContext(), Globals.getKeyPrefs(), p, dialogService);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java]: Do you really need the base panel here? If you look at the line 133 where the PreviewPanel is initialized for the first time, there is null passed for the basePanel and the bibdatabasecontex.   So I assume you don't need the Globals.basepanel hack here.

**Comment by Siedlerchr** [comment]
Thank you very much for your contribution! 👍  If it works without the BasePanel hack, it looks good to me. Our internal standards require a second dev to review your code until it will be merged.

File: src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java (hunk 2 above)
Comment (eso31) [reply src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java]: Yes, I need the basepanel because in the PreviewPanel.java file checks if basePanel is present in order to get the citation otherwise it doesn't work. 

At first I initialized it with null because if no citation style is selected generates a default citation. So that's why I did it that way, the other thing I could try is to write the same logic there without calling the function updateLayout in PreviewPanel but it'll end up with duplicated code. What do you think is the best approach?

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java]: Ah yes, I now did take a closer look at the code here.  Having a dependency on the BasePanel is not nice. Well, but looking at the code and trying out some things I see no other way as the CitationStyleCache is configured on the basePanel.
However, you can use the method here    `JabRefGUI.getMainFrame().getCurrentBasePanel() `. so you don't need that dependency on base panel in globals.

Comment (eso31) [reply src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java]: Thank you, I remove it from Globals and use getCurrentBasePanel instead and it worked.

File: src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java [hunk 3]
```diff
@@ -126,8 +131,19 @@ private void setupLogic() {
...
                     PreviewPanel testPane = new PreviewPanel(null, null, Globals.getKeyPrefs(), Globals.prefs.getPreviewPreferences(), dialogService);
-                    testPane.setFixedLayout(layout.getText());
-                    testPane.setEntry(TestEntry.getTestEntry());
+                    if (chosen.isSelectionEmpty()) {
+                        testPane.setFixedLayout(layout.getText());
+                        testPane.setEntry(TestEntry.getTestEntry());
+                    }
+                    else {
+                        int indexStyle = chosen.getSelectedIndex();
+                        PreviewPreferences p = Globals.prefs.getPreviewPreferences();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java]: Please don't use abbreviations as this makes the code harder to understand: `p -> preferences`.

Comment (eso31) [reply src/main/java/org/jabref/gui/preftabs/PreviewPrefsTab.java]: Sorry about that, I changed it to preferences, and added a changelog entry as well. Thank you.
