### PR TITLE
Fixed year not appearing on citation key for In-* entries due to orphaned crossref links (#9071)

### LINKED ISSUE #9071: citation key generator gives no date in the key for In-* entries
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04, Swaywm 17, JabRef 5.8--2022-08-15--f7648e8 via snap

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

The citation key generator gives no date in the key for In-* entries which get the date value from a crossref.

I need to manually add the date to the entry to get an [Author][Date] citation key.

I would like a way to have the generator pull the [Date] value from the crossref entry.
Something like :
```[Author][Date:From-Mary99]```

which should give the key ```Author99```

related: https://github.com/JabRef/jabref/issues/6294

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by programmer1128**
### Related issues and pull requests

Closes #9071 

### PR Description

Previously, the BibDatabase.citationIndex only updated upon entry creation or deletion, leading to a stale index cache when individual link fields like crossref were edited. This PR intercepts FieldChangedEvent to safely update the index map dynamically whenever a SINGLE_ENTRY_LINK or MULTIPLE_ENTRY_LINK is modified. This ensures the map stays perfectly synced and prevents child crossref links from becoming permanently orphaned when a parent's citation key is later auto-generated. 

### Steps to test

1. Open a new blank JabRef document.
2. Create a new Proceedings entry manually. Set its citation key to TestParent and year to 2026.
3. Create a new InProceedings entry manually and in its crossref field give TestParent.
4. Generate citation key for InProceedings (child) by selecting that entry and pressing ctrl+G or "Generate Citation Key"
5. The new generated citation key for the InProceedings will include the year 2026.
6. Select Proceedings (parent) and generate a citation key for it. 
7. Now observe the InProceeding (child) crossref field change from previous parent key to newly generated key, allowing the year to generate properly and no orphaned crossref links.

### Checklist
- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)

- [x] I manually tested my changes in running JabRef (always required)

- [/] I added JUnit tests for changes (if applicable)

- [x] I added screenshots in the PR description (if change is visible to the user)

- [x] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number

- [x] I described the change in CHANGELOG.md in a way that can be understood by the average user (if change is visible to the user)

- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

JabRefTest

Test Video

https://github.com/user-attachments/assets/a0ff20e5-2970-4fd7-b4f7-7fa012a9c7e7

### CODE REVIEW

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 1]
```diff
@@ -546,6 +546,35 @@ public void unregisterListener(Object listener) {
...
+                }
+            }
+
+            // Add to the new key's set
+            if (newValue != null) {
+                citationIndex.computeIfAbsent(newValue, k -> ConcurrentHashMap.newKeySet()).add(entry);
+            }
+        }
+
+        // After changes, post the event just like before
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: There is no "before" or "after" in a codebase. A person reading will only know the current state.

This is a telltale sign of AI usage. Seems like you did not read our contributing guidelines at all.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: here for after i meant after the checks i made.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: There is also "just like before" at the end of the sentence.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: this part is written by me as i had to restyle to match the styling convention of jabref and then again write tests for the Junit to get accepted in the qodo ai review

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: This discussion is in context of the highlighted comment above, not code style conventions or unit tests.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Hi @subhramit, I apologise for not making my context clear.  I meant for the comments only. In comments line "after" i am implying that after the checks and changes made to the citationIndex concurrent hashmap i post the event to event bus like before when it happened directly. I may have used my wording badly.I apologise for that. But  I have written this code myself.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I have said this in my previous comment as well, not sure if you're paying attention or if you've even read the comment. It ends with "...just like before."
This "before" refers to a previous state of the codebase.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Yes I refered to that for readability.  To show  the changes I made ,so that while comparing it is clearer what changes i made to the code in that method and how the logic handled is different.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I thought it will be better that if i refer to the previous state in my pull request then the mentors will be able to distinguish the changes I made in the method. I truly apologise if I have made any mistake.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: You made a comment just to point out what is "same"? 

These kind of comments are a hallmark of AI. They are neither added by newcomers for readability, nor experienced developers. 

We usually consider honest contributions if you disclose AI usage (at least on being asked), but you are clearly misrepresenting yourself here, which is against our code of conduct.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I am sorry @subhramit . But I am honestly telling the truth. I am not lying about this comment or the code. As I mentioned previously in my gitter chats too, this is my first contribution. i used ai assistant for help. But this code is written by me. I made that comment for the reason i mentioned in my previous comment. I wanted my contribution to be clear and perfect. I apologise for adding such a comment. But I strengthen on the fact, it is written by me. I debugged the code myself using a debugger, recorded the whole process and then formulated the logic for this. I gave those records in the comments section of this issue as well. I am  truly being honest.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Your thought process was - it would be unclear to reviewers that the functionality of an untouched part of code is still the same unless you add a comment stating that the functionality of an untouched part of code is unchanged? 

You've talked about JabRef style/conventions above. If you had even read this class once yourself, or at least the surrounding code, you'd have realized that nobody writes obvious comments like "delete from old key set" or "add to new key set" or refer to history of code. That, however takes time. 
We are really not new to this experience, we've dealt with an uncountable number of pull requests now (and the senior maintainers here even more), and some patterns which you're unaware of, are persistent every time someone uses AI. They may not be obvious to you and it might feel really easy to claim they're intentionally made thinking we won't understand, but that's not really the case. We can see through them.

I've made mistakes like you (which are not even considered mistakes for newcomers), and also use AI during my day to day. Only thing that matters is the honesty and consistency of the human being involved. 

I do not wish to continue this discussion further, so I leave it on other maintainers

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Since you at least tested the changes - we will not reject your contribution and give you another chance. Please be careful henceforth.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 2]
```diff
@@ -546,6 +546,35 @@ public void unregisterListener(Object listener) {
...
+        boolean isLinkedField = field.getProperties().contains(FieldProperty.SINGLE_ENTRY_LINK) ||
+                field.getProperties().contains(FieldProperty.MULTIPLE_ENTRY_LINK);
+
+        if (isLinkedField) {
+            BibEntry entry = event.getBibEntry();
+            String oldValue = event.getOldValue() == null ? "" : event.getOldValue();
+            String newValue = event.getNewValue() == null ? "" : event.getNewValue();
+
+            // Remove from the old key's set
+            if (oldValue != null) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: How can oldvalue ever be null?

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 3]
```diff
@@ -546,6 +546,35 @@ public void unregisterListener(Object listener) {
...
+                if (referenceEntries != null) {
+                    referenceEntries.remove(entry);
+                    if (referenceEntries.isEmpty()) {
+                        citationIndex.remove(oldValue);
+                    }
+                }
+            }
+
+            // Add to the new key's set
+            if (newValue != null) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: How can newvalue ever be null?

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 4]
```diff
@@ -546,6 +546,35 @@ public void unregisterListener(Object listener) {
...
+                citationIndex.computeIfAbsent(newValue, k -> ConcurrentHashMap.newKeySet()).add(entry);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java:573]: Why a concurrent hashmap?

**Review by subhramit — COMMENTED** [review]
Some comments/questions

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 1 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I am being honest @subhramit . I am really serious about this contribution. I went through the other parts of the code in the same class as well. I went through a considerable part of the codebase during the debugging process. I have said in my previous comment that i have taken help of ai assistant to guide me. I mentioned that in my previous gitter chats as well. I have no reason to lie as it would harm my own efforts. I am being honest, that I wrote that part of code myself including that comment line. I used AI to assist me. But the entire code is written by me. I have not copy pasted a single line in that method. I can share my logic report as well as to how i formulated the logic. I humbly appeal to you, please check my code again, I will be happy to explain my thought process for any logic part. I apologise if i overstepped at any point. I hope you will consider my request. Thank you for guiding me, I have learnt a lot from this first contribution and wish to improve further.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: It's fine. You deserve a benefit of doubt, and you shall be given that. 
I have reviewed your code in the next comments, considering your contribution honest. 

Please remove this comment from the code.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Thank you @subhramit for your consideration. I will try to explain your questions in comments with as much clarity as i can. 
Thank you for your guidance. I will remove that comment from the code and commit the changes. If i need to make any other changes, please mention that, i would try to fix them as well.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 2 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: When a child (ex - InProceedings) is added as entry for first time, there is no crossref field attached. This field is not there for the child. So this will be null. When the user types the crossref and saves it, then it is saved with some value.  As the field was empty before, the old value can be null. Now since the citationIndex in BibDatabase.java is initialised as a final ConcurrentHashMap and ConcurrentHashMap does not support null values, there can be a null pointer exception. Hence I added this check. if there is no crossref for a new entry, then it will be seen as empty string to prevent any null pointer exception error.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 3 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: The new value can be null if suddenly a user deletes a crossref field for the child. If there is only 1 crossref entry for a child, and user deletes it, then that field will be removed from the BibEntry object of this entry. Then the new value becomes null. Now as i mentioned in my previous old value comment, the citationIndex in Bibdatabase.java is initialised with a final ConcurrentHashMap. and ConcurrentHashMap does not support null keys. So trying to put a null key will cause null pointer exception. Hence i made the check to keep an empty string for the null value to avoid that error.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 2 above)
Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I understand that you are talking about `getOldValue()`. I inquired about `oldValue`.
You define oldValue as
```java
String oldValue = event.getOldValue() == null ? "" : event.getOldValue();
```
above.
Hence, it can be `""` but never null.
Hence your logic regarding `ConcurrentHashMap` doesn't follow, nor this check `if (oldValue != null)` because it will always be non-null.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 3 above)
Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Similar response as above - what does this check signify?
Did you read your code before submitting?

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 4 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java:573]: I have used a concurrent hashmap here firstly because the citationIndex field itself is initialised as a final ConcurrentHashMap in the BibDatabase.java file.
https://github.com/JabRef/jabref/blob/750e406705758d7a0abbe896cb0997ae79700fde/jablib/src/main/java/org/jabref/model/database/BibDatabase.java#L67

To ensure that the key insertion, update and deletion is thread safe, I followed the same ConcurrentHashMap as done in the class previously.

Also, as I understood, jabref uses javafx for ui. So there is JavaFx ui thread plus many other task threads. Now the change i made is inside a method that is relayEntryChangeEvent(FieldChangedEvent event). This method is called, whenever an event is posted to the eventbus and these events can come from many threads. Now if we use a normal HashMap a thread that posted event to change citationIndex can interfere with the JavaFx thread reading it to show in interface which can cause a ConcurrentModificationException error in java.
So if we use concurrent hashmap then the operations can happen safely with all the threads without the ui thread being interfered.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 2 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Yes the if statement is redundant part. When i first wrote the code i did the check with 

if(oldVaue!=null&&!oldValue.isEmpty())
{
}

But then while checking i realised that i need the empty strings for checking too otherwise the new entry will not be linked. So i removed the isEmpty part and added a ternary operator above. I forgot to remove the redundant if parts for this and the newvalue. I will rectify them the same time when i remove the comment you suggested.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 3 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I mentioned my response in the above comment about my initial code.  This is a screenshot of my earlier code. I have kept the entire process in a word document. i can share it if you want
JabRefCodeFix

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 4 above)
Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java:573]: You are correct about javafx and background threads posting to the eventbus, and `relayEntryChangeEvent` can run off the fx thread while the UI reads the index, so thread-safety does matter here.

However, ConcurrentHashMap doesn't make compound operations atomic. Consider your L562 onwards:
   ```java
   Set<BibEntry> referenceEntries = citationIndex.get(oldValue);
   if (referenceEntries != null) {
       referenceEntries.remove(entry);
       if (referenceEntries.isEmpty()) {
           citationIndex.remove(oldValue);
       }
   }
   ```
Between `isEmpty()` and `remove(oldValue)`, another thread can `computeIfAbsent(oldValue...)` and repopulate the set, the `remove` would then delete a non-empty mapping. However as far as I see, a similar pattern already exists in the code which you probably faithfully followed (in `removeEntryFromIndex`), so for the scope of this PR you can ignore this - and the situation is unlikely to occur during JabRef's practical use.
Just thought of putting this here as the topic of concurrency was raised, so that you can also take this opportunity learn about this more deeply.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 3 above)
Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: See @programmer1128 - it doesn't matter how many preliminary steps you went through before arriving at a final state and submitting a PR as ready for review. The bottom line is that you did not check your final code before submitting - hence we are spending time on this.
We understand - you're a human and this can happen, but as far as the PR review is concerned, the maintainers really don't have time for these endless excuses or knowing the entire history of your process. Please just say "oh I missed this from a previous draft" and just fix it.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 4 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java:573]: Thank you @subhramit for your guidance. I think this is similar to time of check to time of use  condition. I may be wrong. I will keep your advice in mind . Thank you for pointing it out and reviewing my PR thouroughly.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 3 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I apologise for my mistake @subhramit . I will make all the necessary changes that you have suggested, recheck my code and then commit it. Thank you for your thorough review and time to check my code and guide me.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: No issues, Aritra, as blunt my tone may sound, I am keeping in mind that this is your first time - and trying to make you pick up as many things as possible.

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I really appreciate it @subhramit .  I have learnt a lot from this and I am still learning and will continue to do so. It is a really good experience for me. Thank you for taking the time to mentor me.

**Comment by subhramit** [comment]
@LoayTarek5 would you like to review this? Since you delved into the issue a bit, this may be a good opportunity!

**Comment by LoayTarek5** [comment]
> @LoayTarek5 would you like to review this? Since you delved into the issue a bit, this may be a good opportunity!

Sure, i will do it

**Comment by programmer1128** [comment]
Hi @subhramit , I have updated the PR based on your suggestions. I have removed the redundant if checks. While fixing, another test case came to my mind. If the new value is kept empty by user, then the entry will be registered with a crossref of empty value, which is not valid as a empty crossref is not a valid one. Hence I have added a if check for the new value, that checks if the new value is empty or not and accordingly places the entry in the map.

**Comment by calixtus** [comment]
Please note that AI use needs to be disclosed.

**Comment by programmer1128** [comment]
Hi @calixtus, I have taken help of AI assistant to guide me through the open source contribution process, but I have done the entire debugging process myself, with detailed reports at every step as I commented on issue page, guidance from JabRef mentors as well, and the entire code has been written by me myself with my own logic formulation. The code may not have been very clean at the first, but I made changes as per guidance of mentors and then submitted the proper PR. I have learnt a lot from this contribution and I am continuing to learn. I thank the entire community for guiding me towards a proper PR and a better contributor.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 5]
```diff
@@ -546,6 +546,33 @@ public void unregisterListener(Object listener) {
...
+                field.getProperties().contains(FieldProperty.MULTIPLE_ENTRY_LINK);
+
+        if (isLinkedField) {
+            BibEntry entry = event.getBibEntry();
+            String oldValue = event.getOldValue() == null ? "" : event.getOldValue();
+            String newValue = event.getNewValue() == null ? "" : event.getNewValue();
+
+            // Remove from the old key's set
+
+            Set<BibEntry> referenceEntries = citationIndex.get(oldValue);
```
Comment (LoayTarek5) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: MULTIPLE_ENTRY_LINK fields can hold multiple keys in one value, so citationIndex.get(oldValue) misses when oldValue is something like "Key1, Key2".

BibDatabase.java already has forEachCitationKey(), which parses link fields with entry.getEntryLinkList(field, this) and is reused by indexEntry and removeEntryFromIndex, consider using it here too so all link parsing stays in one place

File: jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java [hunk 6]
```diff
@@ -486,4 +486,22 @@ void getIndex() {
...
+        database.insertEntry(parent);
+        database.insertEntry(child);
+
+        // Setting the crossref field after insertion should trigger the FieldChangedEvent
+        // and safely update the citation index without crashing.
+        child.setField(StandardField.CROSSREF, "TestParent");
+
+        // Verify that the database successfully linked the child to the parent
+        assertEquals(Optional.of(parent), database.getReferencedEntry(child));
+    }
```
Comment (LoayTarek5) [inline jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java:506]: The existing crossrefChanged test in KeyChangeListenerTest.java sets the crossref before insertEntry, so it never triggers the stale index, the real bug when crossref is set after insertion

Please add a test that:
inserts parent and child separately, then sets child.crossref after insertion.
renames the parent key --> verifies the child's crossref follows
renames the parent key a second time --> verifies it still follows

**Review by LoayTarek5 — CHANGES_REQUESTED** [review]

**Comment by LoayTarek5** [comment]
OMG 😅, I did not notice that my reviws was Pending, sorry for the delay.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 5 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Hi @LoayTarek5, Thank you for reviewing my code. i though initially that crossref multiple entry fields were stored individually by default in separate strings all containing same child. Thank you for pointing out my mistake. I will try to implemet the logic you suggested using the forEachCitationKey() method and correct my logic and test it with a testcase similar to "key1,key2.." for multiple entry fields.

File: jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java (hunk 6 above)
Comment (programmer1128) [reply jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java:506]: Thank you @LoayTarek5  for this new test case. I will test it with my new correct logic with a new test that will implement the 2 time rename of parent. I will try to record the results and post it here.

**Comment by programmer1128** [comment]
Hi @LoayTarek5 and JabRef Community, I went through the forEachCitationKey() method as you suggested for multiple linked fields parsing logic. As i understood, the function requires a BibEntry object and a Consumer<String> functional interface as argument.
Now in my original logic, i was getting the child entries set linked to a parent from citationKeyIndex map using the get method on the oldValue string and then updating to newValue string. Here since i cannot use a normal string , i have thought to create a dummy BibEntry object with just the multiple entries as a field and then pass it to the method as argument. For the Consumer<String>, since functional interfaces in java accept lambda functions i am thinking about passing my earlier logic as a lambda function to the method.

This is my updated solution as i have thought.
```java
boolean isLinkedField = field.getProperties().contains(FieldProperty.SINGLE_ENTRY_LINK) ||
            field.getProperties().contains(FieldProperty.MULTIPLE_ENTRY_LINK);

    if (isLinkedField) {
        BibEntry entry = event.getBibEntry();
        String oldValue = event.getOldValue() == null ? "" : event.getOldValue();
        String newValue = event.getNewValue() == null ? "" : event.getNewValue();

        //  parse the old string using a temporary dummy BibEntry
        if (!oldValue.trim().isEmpty()) {
            BibEntry oldDummy = new BibEntry(StandardEntryType.Article).withField(field, oldValue);
            
            // using parser with lambda function to remove child from old parent entry
            forEachCitationKey(oldDummy, oldKey -> {
                Set<BibEntry> referenceEntries = citationIndex.get(oldKey);
                if (referenceEntries != null) {
                    referenceEntries.remove(entry);
                    if (referenceEntries.isEmpty()) {
                        citationIndex.remove(oldKey);
                    }
                }
            });
        }

        // parse the new string using a temporary dummy entry
        if (!newValue.trim().isEmpty()) {
            BibEntry newDummy = new BibEntry(StandardEntryType.Article).withField(field, newValue);
            
            // using parser to add child to new parent entries.
            forEachCitationKey(newDummy, newKey -> {
                citationIndex.computeIfAbsent(newKey, k -> ConcurrentHashMap.newKeySet()).add(entry);
            });
        }
    }
    eventBus.post(event);
 ```
 I will try to implement this, and test it out with a multiple linked entry test case. I am also implementing the twice rename of parent test as you suggested. I will make the changes and make  a updated PR soon. 
 If i have made any mistakes or there needs to be any changes made, please tell me that, i will try to fix my logic and submit the corrected code.

**Comment by LoayTarek5** [comment]
Hi @programmer1128, creating dummy BibEntry objects to use forEachCitationKey is overengineered and could cause issues since those dummy entries aren't in the database (forEachCitationKey calls getEntryLinkList which tries to resolve entries).

try to think about a much simpler approach, just split the raw string by comma, handles both SINGLE_ENTRY_LINK (one key, no comma) and MULTIPLE_ENTRY_LINK (comma-separated) correctly, clean, simple, no dummy objects needed

**Comment by programmer1128** [comment]
Hi @LoayTarek5 , Thank you for reviewing my code. Thank you for your approach. I wanted to reuse the forEachCitationKey method and hence went with the dummy object logic. The logic you suggested is much more simpler and elegant. For that i could use a for loop then to parse the keys and then apply the changes like this

```java

for (String rawKey : oldValue.split(",")) {
         String oldKey = rawKey.trim();
         if (!oldKey.isEmpty()) {
               Set<BibEntry> referenceEntries = citationIndex.get(oldKey);
               if (referenceEntries != null) {
                      referenceEntries.remove(entry);
                      if (referenceEntries.isEmpty()) {
                            citationIndex.remove(oldKey);
                        }
               }
         }
}
  ```
  Thank you for your suggestion. I will surely implement it in my code

**Comment by programmer1128** [comment]
Hi Jabref Community, I have updated the relayEntryChangeEvent method to handle the multile entry link fields as well by parsing the keys and updating individual keys and their sets. 
I have also added the previously suggested twice rename of parent test and verified that the test has passed.
I have added an additional test for the multiple entry link field verification too, to verify the changes are working properly.

I have tested out both the updates in the jabref application iteself too, by making the changes in UI as an user would.
I have attached 2 short screen recordings demonstrating my tests.



Twice Rename of Parent Test


https://github.com/user-attachments/assets/54ba3f8b-ff27-40ba-95ab-b9d502195550



Multiple Entry Field Test

https://github.com/user-attachments/assets/17f0bdfc-d9a7-4357-a9b1-9352a40f2371

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 7]
```diff
@@ -546,6 +546,44 @@ public void unregisterListener(Object listener) {
 
     @Subscribe
     private void relayEntryChangeEvent(FieldChangedEvent event) {
```
Comment (LoayTarek5) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: If I were you, i will extract the index update logic into a separate private method 
for ex: "updateCitationIndexForFieldChange(event)" and keep this method 
as just:
    private void relayEntryChangeEvent(FieldChangedEvent event) {
        updateCitationIndexForFieldChange(event);
        eventBus.post(event);
    }

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 8]
```diff
@@ -546,6 +546,44 @@ public void unregisterListener(Object listener) {
...
+            // split the old multiple key string into individual keys and remove the entry from all old keys
+            if (oldValue != null && !oldValue.trim().isEmpty()) {
+                for (String rawKey : oldValue.split(",")) {
+                    String oldKey = rawKey.trim();
+                    if (!oldKey.isEmpty()) {
+                        Set<BibEntry> referenceEntries = citationIndex.get(oldKey);
+                        if (referenceEntries != null) {
+                            // remove entry using unique id to prevent duplicate child entries
+                            // due to changed hashcodes when field in child is changed
+                            referenceEntries.removeIf(e -> e.getId().equals(entry.getId()));
```
Comment (LoayTarek5) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Use `referenceEntries.remove(entry)` to stay consistent with the existing `removeEntryFromIndex` method

File: jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java [hunk 9]
```diff
@@ -486,4 +486,67 @@ void getIndex() {
         assertEquals(1, database.indexOf(entryD));
         assertEquals(-1, database.indexOf(entryA));
     }
+
+    @Test
+    void crossrefChangeUpdatesCitationIndex() {
```
Comment (LoayTarek5) [inline jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java:491]: This test doesn't actually prove the fix, `getReferencedEntry` reads the crossref field and looks up by key, it never touches citationIndex, i think this would pass even without your changes.

**Review by LoayTarek5 — CHANGES_REQUESTED** [review]

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 7 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Hi @LoayTarek5 , Thank you for reviewing my code. I will surely move the index update logic to a separate private method to have a better modularity.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 8 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Hi @LoayTarek5 , I used the removeIf(e -> e.getId().equals(entry.getId())) approach, because while i was debugging , i printed the citationIndex map to see how the keys and their set of children where being stored. There i noticed that when updating the key, the child is not being removed from the old key set.  i diagnosed that since  the internal structure of the child changes when the old key is updated to newkey the hashcode generated by java on the child BibEntry object changes. so it does not match the previous child hashcode and set does not remove it. it stays there as a duplicate entry and the changed child gets added to the newkey set. 
To avoid this i used removeIf to remove a child by matching the unique id that is assigned to an object by jabref automatically during creation.

If i have made any wrong assumptions or mistake, please tell me that, i will try to fix the problem.

File: jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java (hunk 9 above)
Comment (programmer1128) [reply jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java:491]: You are right, I misunderstood what the getReferencedEntry was doing. It did a direct lookup bypassing the citationIndex map. I will update and fix the tests correctly to use the citationIndex map to verify my code. Thank you for suggesting the changes.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 8 above)
Comment (LoayTarek5) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Yeah, good catch, you are right, since BibEntry.hashCode() depends on fields, and the crossref field just changed, the hash is different from when the entry was added to the set removeIf with getId() is the correct approach here

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Thank you @LoayTarek5 for providing the clarity. I am glad i was able to explain my logic. I will use the removeIf with getId() approach in my code, and make the other changes you suggested. Thank you for your suggestions.

**Comment by programmer1128** [comment]
Hi @LoayTarek5 and JabRef Community, I have made the suggested changes in my new commit. 
I have moved the citationIndex update logic to a separate method for better modularity.
I have added citationIndex checks inside the tests to verify my code more strongly.

If i need to make any more changes, please suggest that, I will fix the problems accordingly.
Thank you everyone for your guidance.

**Review by LoayTarek5 — APPROVED** [review]
Solid work @programmer1128 , it looks good to me

**Comment by programmer1128** [comment]
Thanks a lot @LoayTarek5 and JabRef community. It means a lot to me..It has been a great experience and i have learnt a lot from the community. Thank you for your guidance at every step...

**Review by Siedlerchr — DISMISSED** [review]

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 10]
```diff
@@ -544,8 +544,50 @@ public void unregisterListener(Object listener) {
...
+        boolean isLinkedField = field.getProperties().contains(FieldProperty.SINGLE_ENTRY_LINK) ||
+                field.getProperties().contains(FieldProperty.MULTIPLE_ENTRY_LINK);
+
+        if (isLinkedField) {
+            BibEntry entry = event.getBibEntry();
+            String oldValue = event.getOldValue();
+            String newValue = event.getNewValue();
+
+            // split the old multiple key string into individual keys and remove the entry from all old keys
+            if (oldValue != null && !oldValue.trim().isEmpty()) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Use `StringUtil` `isBlank()`

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 11]
```diff
@@ -544,8 +544,50 @@ public void unregisterListener(Object listener) {
...
+                for (String rawKey : oldValue.split(",")) {
+                    String oldKey = rawKey.trim();
+                    if (!oldKey.isEmpty()) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Use `isBlank`

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 12]
```diff
@@ -544,8 +544,50 @@ public void unregisterListener(Object listener) {
...
+                        Set<BibEntry> referenceEntries = citationIndex.get(oldKey);
+                        if (referenceEntries != null) {
+                            // remove entry using unique id to prevent duplicate child entries
+                            // due to changed hashcodes when field in child is changed
+                            referenceEntries.removeIf(e -> e.getId().equals(entry.getId()));
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Avoid abbreviations
```suggestion
                            referenceEntries.removeIf(referenceEntry -> referenceEntry.getId().equals(entry.getId()));
```

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 13]
```diff
@@ -544,8 +544,50 @@ public void unregisterListener(Object listener) {
...
+                            if (referenceEntries.isEmpty()) {
+                                citationIndex.remove(oldKey);
+                            }
+                        }
+                    }
+                }
+            }
+
+            // split the new multiple key string into individual keys and add the entry to all new keys
+            if (newValue != null && !newValue.trim().isEmpty()) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: `isBlank`

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 14]
```diff
@@ -544,8 +544,50 @@ public void unregisterListener(Object listener) {
...
+                for (String rawKey : newValue.split(",")) {
+                    String newKey = rawKey.trim();
+                    if (!newKey.isEmpty()) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: isBlank

**Comment by programmer1128** [comment]
Hi @subhramit , Thank you for reviewing my code and suggesting the changes. I will implement these changes and commit the corrected code.

File: jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java [hunk 15]
```diff
@@ -486,4 +486,70 @@ void getIndex() {
...
+        // setting the crossref field after insertion triggers the FieldChangedEvent
+        child.setField(StandardField.CROSSREF, "TestParent");
+
+        // verify the child was actually added to the citationIndex
+        Set<BibEntry> indexedChildren = database.getEntriesForCitationKey("TestParent");
+        assertTrue(indexedChildren.contains(child), "The citationIndex should contain the child entry under the parent's key");
+    }
+
+    @Test
+    void childCrossrefFollowsParentDoubleRename() {
```
Comment (subhramit) [inline jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java:509]: Split this into two tests - `childIsIndexedUnderEachKeyInCommaSeparatedField` and `changingOneKeyInCommaSeparatedFieldUpdatesIndex`

Comment (programmer1128) [reply jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java:509]: Hi @subhramit , thank you for suggesting the changes. I will split the test into 2 parts and commit the corrected code.

Comment (programmer1128) [reply jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java:509]: Hi @subhramit , I wanted to clarify something about the test. You mentioned the test to be split into childIndexedUnderEachKeyInCommaSeparatedField and changingOneKeyInCommaSeparatedFieldUpdatesIndex. But in the code shown the test shown is childCrossRefFollowsParentDoubleRename which is test for checking if citationIndex updates when parent is renamed twice.
 Are you refering to the next test which is 

childRelatedIndexUpdatesWhenCommaSeparatedFieldChanges test which verifies that the comma separated fields update when any one inside the field changes?
Please guide me on this, so i can make the correct change.

File: jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java [hunk 16]
```diff
@@ -486,4 +486,70 @@ void getIndex() {
...
+        parent.setCitationKey("ParentB");
+        assertTrue(database.getEntriesForCitationKey("ParentB").contains(child), "Child should have moved to the ParentB index set");
+
+        // second rename of parent
+        parent.setCitationKey("ParentC");
+        assertTrue(database.getEntriesForCitationKey("ParentC").contains(child), "Child should have moved to the ParentC index set");
+    }
+
+    @Test
+    void childRelatedIndexUpdatesWhenCommaSeparatedFieldChanges() {
```
Comment (subhramit) [inline jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java]: Reply to https://github.com/JabRef/jabref/pull/15582/changes#r3149824955
Yes, split this one - @programmer1128.
I read all the testcases together but added the comment in the wrong one.

Comment (programmer1128) [reply jablib/src/test/java/org/jabref/model/database/BibDatabaseTest.java]: Thanks a lot @subhramit for clarifying. I will make the suggested changes and commit the corrected code.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 17]
```diff
@@ -544,8 +544,50 @@ public void unregisterListener(Object listener) {
...
+        boolean isLinkedField = field.getProperties().contains(FieldProperty.SINGLE_ENTRY_LINK) ||
+                field.getProperties().contains(FieldProperty.MULTIPLE_ENTRY_LINK);
+
+        if (isLinkedField) {
+            BibEntry entry = event.getBibEntry();
+            String oldValue = event.getOldValue();
+            String newValue = event.getNewValue();
+
+            // split the old multiple key string into individual keys and remove the entry from all old keys
+            if (oldValue != null && !oldValue.isBlank()) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: When a change is suggested, please don't just blindly replace as per your gut feeling. Go into the function `isBlank`, see what it does. If it does the same as `isEmpty()`, a critical thinker would think - then why the need for replacement?
If you go into the function body, you'll find that the null check is already being done there - so the review comments were intended to reduce extra code.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Also, you did not use StringUtil as mentioned in https://github.com/JabRef/jabref/pull/15582#discussion_r3149198718

https://github.com/JabRef/jabref/blob/28e1b592b76f8e68eb496970d6df097e8fd662e8/jablib/src/main/java/org/jabref/logic/util/strings/StringUtil.java#L576-L578

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: I apologise @subhramit , i misunderstood your suggested change. I thought you meant the built in isBlank() method for string class in java and since the built in method does not check the null, i kept the null check.
For the isEmpty() part I thought you have suggested the isBlank() because .trim() creates a new String object in java and to avoid that.
I apologise for my mistakes. I will fix them immediately and commit the corrected code.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Same comments on the other related parts.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java [hunk 18]
```diff
@@ -544,8 +544,50 @@ public void unregisterListener(Object listener) {
...
+                for (String rawKey : oldValue.split(",")) {
+                    String oldKey = rawKey.trim();
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Trim is also no longer needed. See what `isBlank` does by Ctrl+click.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 17 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Thank you @subhramit for providing the code segment. It is a great help. I will fix the code immediately to use this method and then commit the corrected code.
If there is any more change that i need to make, please mention them, i will fix them and commit the proper code.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: No, that is all. Thanks.

File: jablib/src/main/java/org/jabref/model/database/BibDatabase.java (hunk 18 above)
Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Hi @subhramit , I saw what the method does. By using !StringUtil.isBlank(rawKey) i can avoid the new string creation that trim does even for empty invalid strings. 
I just want to clarify, that when the string is not empty and contains characters with leading spaces or spaces at end, then i have to do trim so that the citationIndex can properly match the keys. For that reason, i think i should move the trim part to inside the if statement that trims the rawKey only when it is not empty and checks in citationIndex. Can you please clarify my approach.

Comment (subhramit) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: You can keep the trim where you are using the trimmed version beyond the checks

Comment (programmer1128) [reply jablib/src/main/java/org/jabref/model/database/BibDatabase.java]: Thanks a lot @subhramit for clarifying my approach. I will make the fixes immediately and commit the proper code with the changes you suggested.
Thank you for your guidance.

**Comment by programmer1128** [comment]
Hi @subhramit  and JabRef Community, I have made the suggested changes in my code. I have updated the .isEmpty() to .isBlank() method written in StringUtil.java in jabref/logic and commited the updated code.
If there are any more changes to make, please suggest, I will fix them.

Thank you for your guidance at every step.

**Review by subhramit — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Comment by programmer1128** [comment]
Thanks a lot @subhramit and @Siedlerchr and JabRef Community for approving my pull request. It really means a lot to me. 
Thank you for your guidance at every step. I have learnt a lot from this experience.

I am seeing some binaries install issues on the checks made for the merge. If i can contribute in any manner from my end to resolve this please tell me, i will try to help and fix the checks.
