### PR TITLE
Fix saving triggers metadata changed

### LINKED ISSUE #9159: ignore unnecessary library modification notifications?
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-09-15--853338a Linux 5.19.8-200.fc36.x86_64 amd64  Java 18.0.2.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

change the metadata of the library (within JabRef) and you (at least I) get a library notification message. I do not see how/why this is necessary. Obviously, the metadata changes when I save the library.

### Appendix

...
<details>

[Screencast from 19-09-22 14:51:51.webm](https://user-images.githubusercontent.com/20518297/191021583-75443c86-1cc5-45f2-89d2-f27307bf9b4a.webm)

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #9159

Generate new equals, hashcode for FieldFormatterCleanup and toString methods

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanup.java [hunk 1]
```diff
@@ -105,15 +105,15 @@ public Formatter getFormatter() {
...
-        if (o instanceof FieldFormatterCleanup) {
-            FieldFormatterCleanup that = (FieldFormatterCleanup) o;
-            return Objects.equals(field, that.field) && Objects.equals(formatter, that.formatter);
+        if (!(obj instanceof FieldFormatterCleanup)) {
+            return false;
         }
-        return false;
+        FieldFormatterCleanup other = (FieldFormatterCleanup) obj;
+        return Objects.equals(field, other.field) && Objects.equals(formatter, other.formatter);
     }
```
Comment (koppor) [inline src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanup.java:117]: The new code seems to be the equial to the old one. ^^.

File: src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanups.java [hunk 2]
```diff
@@ -206,4 +206,26 @@ private static Formatter getFormatterFromString(String formatterName) {
...
+            return false;
+        }
+        FieldFormatterCleanups other = (FieldFormatterCleanups) obj;
+        return Objects.equals(actions, other.actions) && (enabled == other.enabled);
+    }
+
+    @Override
+    public String toString() {
+        return "FieldFormatterCleanups [enabled=" + enabled + ", actions=" + actions + "]";
+    }
```
Comment (koppor) [inline src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanups.java:230]: Thank you for putting in the implementations here. I googled and found

> By default, two objects are equal if and only if they are refer to the **same memory location**

**Review by koppor — APPROVED** [review]
LGTM!

To cover cases when new fields are added to the classes, maybe, we should add test cases with deepEquals of AssertJ - https://stackoverflow.com/a/9633089/873282

Note to self: Testing equality by reflection is not an option, as a) it used reflection and b) is less performant: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/EqualsBuilder.html#reflectionAppend-java.lang.Object-java.lang.Object-

File: src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanup.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/cleanup/FieldFormatterCleanup.java:117]: I just used eclipse to regenerate it to have it consistent with others
