### PR TITLE
Fix #1500: Renaming of explicit groups changes entries accordingly

### LINKED ISSUE #1500: Rename a static group: Group entries are not updated accordingly
JabRef-3.4dev--snapshot--2016-04-29--master--694840a
on Windows 10

If you rename a static group, the group entries are not updated accordingly. Their "group" field will still contain the old group name (and NOT the new one).

Steps to reproduce:

1. Rename a static group
2. Articles/group entries won't be updated accordingly and are still assigned to the old (obsolete) group name

(might be related to this one: https://github.com/JabRef/jabref/issues/1434#event-691424400 ?)

### PR DESCRIPTION
**Pull request by tobiasdiez**
Also moved the code responsible for carrying over previous assignments from the gui to logic; add tests for it.

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)

### CODE REVIEW

File: src/main/java/net/sf/jabref/gui/groups/GroupDialog.java [hunk 1]
```diff
@@ -296,27 +280,13 @@ public void actionPerformed(ActionEvent e) {
...
-                        mResultingGroup = m_editedGroup.deepCopy();
-                        mResultingGroup.setName(m_name.getText().trim());
-                        mResultingGroup.setHierarchicalContext(getContext());
-                    } else {
-                        mResultingGroup = new ExplicitGroup(m_name.getText().trim(), getContext());
-                        if (m_editedGroup != null) {
-                            addPreviousEntries();
-                        }
-                    }
+                    mResultingGroup = new ExplicitGroup(m_name.getText().trim(), getContext());
```
Comment (lenhard) [inline src/main/java/net/sf/jabref/gui/groups/GroupDialog.java]: Since you are touching that code anyway: How about refactoring the names here according to Java code conventions? `m_name` -> `mName`. What does the `m` stand for, btw?

File: src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java [hunk 2]
```diff
@@ -55,10 +57,37 @@ public AbstractGroup getGroup() {
...
+     * entries so that they are now matched by the new group.
+     *
+     * @param newGroup the new group (has to be non-null)
+     * @param shouldKeepPreviousAssignments specifies whether previous matched entries should be carried over
+     * @param entriesInDatabase list of entries in the database
+     */
+    public Optional<EntriesGroupChange> setGroup(AbstractGroup newGroup, boolean shouldKeepPreviousAssignments,
+            List<BibEntry> entriesInDatabase) {
+        AbstractGroup oldGroup = getGroup();
+        setGroup(newGroup);
```
Comment (lenhard) [inline src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java]: You marked this method as deprecated above. Why are you still using it in new code?

File: src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java [hunk 3]
```diff
@@ -14,15 +16,23 @@
...
 
     @Before
     public void setUp() throws Exception {
+        entries.clear();
+        entry = new BibEntry();
+        entries.add(entry);
         entries.add(new BibEntry().withField("author", "author1 and author2"));
         entries.add(new BibEntry().withField("author", "author1"));
+
+        Globals.prefs = JabRefPreferences.getInstance();
```
Comment (lenhard) [inline src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java]: Shouldn't the preferences setting go into a `@BeforeClass`-annotated method? Or do you need this for every test?

**Comment by lenhard** [comment]
Only minor remarks. LGTM.

File: src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java (hunk 2 above)
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/logic/groups/GroupTreeNode.java]: Once the other method is no longer used it can be inlined (or at least made private).

File: src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java (hunk 3 above)
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java]: It would also work with @BeforClass but I like to have only one setup method.

File: src/main/java/net/sf/jabref/gui/groups/GroupDialog.java (hunk 1 above)
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/gui/groups/GroupDialog.java]: Done.

File: src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java (hunk 3 above)
Comment (simonharrer) [inline src/test/java/net/sf/jabref/logic/groups/GroupTreeNodeTest.java]: I would use a separate `@BeforeClass` method to distinguish code that is required only once, from code that is required to be executed for every test.

File: src/main/java/net/sf/jabref/gui/groups/GroupDialog.java [hunk 4]
```diff
@@ -77,37 +69,37 @@
...
+    private final TextField kgSearchTerm = new TextField("keywords", "", false);
+    private final JCheckBox kgCaseSensitive = new JCheckBox(Localization.lang("Case sensitive"));
+    private final JCheckBox kgRegExp = new JCheckBox(Localization.lang("regular expression"));
     // for SearchGroup
-    private final JTextField m_sgSearchExpression = new JTextField(GroupDialog.TEXTFIELD_LENGTH);
-    private final JCheckBox m_sgCaseSensitive = new JCheckBox(Localization.lang("Case sensitive"));
-    private final JCheckBox m_sgRegExp = new JCheckBox(Localization.lang("regular expression"));
+    private final JTextField sgSearchExpression = new JTextField(GroupDialog.TEXTFIELD_LENGTH);
+    private final JCheckBox sgCaseSensitive = new JCheckBox(Localization.lang("Case sensitive"));
+    private final JCheckBox sgRegExp = new JCheckBox(Localization.lang("regular expression"));
```
Comment (simonharrer) [inline src/main/java/net/sf/jabref/gui/groups/GroupDialog.java]: what does sg stand for?

**Comment by simonharrer** [comment]
LGTM, just merge after you addressed the minor comments.

File: src/main/java/net/sf/jabref/gui/groups/GroupDialog.java (hunk 4 above)
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/gui/groups/GroupDialog.java]: searchGroup, I would make an exception here for the general rule of no abbreviations since `searchGroupRegualarExpressionCheckBox` is a bit to big ;)

Comment (simonharrer) [inline src/main/java/net/sf/jabref/gui/groups/GroupDialog.java]: Not convinced. As `sg` is not really that common. Why not searchGroupRegExCheckBox?

**Comment by stefan-kolb** [comment]
LGTM :+1:
