### PR TITLE
Fix right clicking on any entry and selecting "Open folder" results in the NullPointer exception

### LINKED ISSUE #4763: "open folder" causes java.lang.NullPointerException: null
JabRef--master--latest.jar (https://builds.jabref.org/master/) as well as version 4.3.1-2 form Arch AUR (https://aur.archlinux.org/packages/jabref/)

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Right clicking on any entry in any database and selecting "Open folder" results in the NullPointer exception below. The setup experiencing this problem is Arch Linux with i3 window manager and without desktop environment. Hence it could be that there is a dependency to some external SW that is not satisfied. This problem exists over multiple version already (~1y) over different Arch machines I operate. My guess is that there is some unknown dependency that I lack on my systems, which causes "open folder" to silently crash. I would be interested in tracking down what exactly is causing that issue. Might be something very obvious to you guys.

1. On Arch Linux + Jabref master latest or Jabref 4.3.1-2 from AUR: open any database where files have associated pdfs in their entires.
2. Right click, "open folder" --> exception below

<details>
  <summary>Log File</summary>
  
  ```
  10:51:41.270 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef CachedThreadPool,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.desktop.os.Linux.openFolderAndSelectFile(Linux.java:54) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.desktop.JabRefDesktop.openFolderAndSelectFile(JabRefDesktop.java:171) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.BasePanel.lambda$null$49(BasePanel.java:348) ~[JabRef--master--latest.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
  ```

Used Java version:
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
</details>

I'm happy to provide further details!

### PR DESCRIPTION
**Pull request by deepakkumar96**
Fixes #4763
The issue was when a user right-clicks an entry and right click "open folder"  then it results in Null Pointer Exception in Linux System.

The main cause for this issue was in the Linux implementation of NativeDesktop(Linux.java#openFolderAndSelectFile), that code looks for 
an environment variable named 'DESKTOP_SESSION' and if this variable is not set in any system then it will result in Null Pointer Exception.

The Fix was to check if 'DESKTOP_SESSION' variable is present or not, if not present then run a default command which will try to open the folder.

Another issue was that if a system does not have a file browser installed then right-clicking on any entry and selecting "open folder" option will not do anything(if there is no file browser installed in the system).

To fix this issue I've added an option in preference setting window to set command or program for default file browser, where a user can explicitly set command or let JefRef use a default behavior like this:

jabref-fix-4763

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [x] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/desktop/JabRefDesktop.java [hunk 1]
```diff
@@ -168,7 +169,38 @@ private static void openExternalFilePlatformIndependent(Optional<ExternalFileTyp
...
+            String absolutePath = fileLink.toAbsolutePath().getParent().toString();
+            String command = Globals.prefs.get(JabRefPreferences.FILE_BROWSER_COMMAND);
+            if (!command.isEmpty()) {
+                command = command.replaceAll("\\s+", " "); // normalize white spaces
+
+                // replace the placeholder if used
+                command = command.replace("%DIR", absolutePath);
+                String[] subcommands = command.split(" ");
+
+                JabRefGUI.getMainFrame().output(Localization.lang("Executing command \"%0\"...", command));
```
Comment (CaptainDaVinci) [inline src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: I think `output` is deprecated, you should instead use `DialogService`.

Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: ok, I'll change this

Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: JabRefDesktop does not have field DialogService field, so should I add a class level filed Or a local variable for DialogService instance?

Comment (CaptainDaVinci) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: `JabRefGUI.getMainFrame().getDialogService()` should work.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: You should pass the DialogService as parameter to the method. You may need to do this at several locations.

Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: Ok thanks, I've replaced that line by this JabRefGUI.getMainFrame().getDialogService().notify()
in my local machine.

File: src/main/java/org/jabref/gui/desktop/JabRefDesktop.java [hunk 2]
```diff
@@ -168,7 +169,38 @@ private static void openExternalFilePlatformIndependent(Optional<ExternalFileTyp
...
     public static void openFolderAndSelectFile(Path fileLink) throws IOException {
-        NATIVE_DESKTOP.openFolderAndSelectFile(fileLink);
+        if (Objects.isNull(fileLink)) {
+            return;
+        }
+        boolean usingDefault = Globals.prefs.getBoolean(JabRefPreferences.USE_DEFAULT_FILE_BROWSER_APPLICATION);
+
+        if(usingDefault) {
+            NATIVE_DESKTOP.openFolderAndSelectFile(fileLink);
+        }else{
```
Comment (CaptainDaVinci) [inline src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: There are certain code style errors, which is resulting in failed tests.

Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: Yes you right, I didn't included checkstyle in my IDE, I'll fix all the checkstyle issues in next commit.

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 3]
```diff
@@ -51,18 +55,18 @@ public void openFileWithApplication(String filePath, String application) throws
...
-        String cmd;
+        String cmd = "xdg-open " + filePath.toAbsolutePath().getParent().toString(); //default command
 
-        if (desktopSession.contains("gnome")) {
-            cmd = "nautilus" + filePath.toString().replace(" ", "\\ ");
-        } else if (desktopSession.contains("kde")) {
-            cmd = "dolphin --select " + filePath.toString().replace(" ", "\\ ");
-        } else {
-            cmd = "xdg-open " + filePath.toAbsolutePath().getParent().toString();
+        if(Objects.nonNull(desktopSession)){
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/desktop/os/Linux.java]: again, just use `desktopSession != null`

File: src/main/java/org/jabref/gui/preferences/ExternalTab.java [hunk 4]
```diff
@@ -208,6 +248,11 @@ private void updateExecuteConsoleButtonAndFieldEnabledState() {
         consoleCommand.setDisable(!executeConsole.isSelected());
     }
 
+    private void updateExecuteFileBrowserButtonAndFieldEnabledState() {
+        fileBrowserButton.setDisable(!executeFileBrowser.isSelected());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/ExternalTab.java]: In JavaFX, you have the option to bind the properties once using `fileBrowserButton.disableProperty().bind(executeFileBrowser.selectedProperty().not()`. Then you don't need to take care of the state update yourself.

File: src/main/java/org/jabref/gui/preferences/ExternalTab.java [hunk 5]
```diff
@@ -187,6 +224,9 @@ public void storeSettings() {
         prefs.putBoolean(JabRefPreferences.USE_DEFAULT_CONSOLE_APPLICATION, defaultConsole.isSelected());
         prefs.put(JabRefPreferences.CONSOLE_COMMAND, consoleCommand.getText());
         prefs.put(JabRefPreferences.ADOBE_ACROBAT_COMMAND, adobeAcrobatReaderPath.getText());
+        prefs.putBoolean(JabRefPreferences.USE_DEFAULT_FILE_BROWSER_APPLICATION, defaultFileBrowser.isSelected());
+        prefs.put(JabRefPreferences.FILE_BROWSER_COMMAND, fileBrowserCommand.getText());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/ExternalTab.java]: Please add a check that the `fileBrowserCommand` is not empty (otherwise keep using the default file browser). Otherwise there will be users which set the command to be empty and then complain that the "Open folder" feature is broken (user can be really creative with such things ;-) ).

File: src/main/java/org/jabref/gui/desktop/JabRefDesktop.java [hunk 6]
```diff
@@ -168,7 +169,38 @@ private static void openExternalFilePlatformIndependent(Optional<ExternalFileTyp
      * @throws IOException
      */
     public static void openFolderAndSelectFile(Path fileLink) throws IOException {
-        NATIVE_DESKTOP.openFolderAndSelectFile(fileLink);
+        if (Objects.isNull(fileLink)) {
```
[the remark this answers is not in the document]
Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: Thanks for this clarification.

File: src/main/java/org/jabref/gui/desktop/JabRefDesktop.java [hunk 7]
```diff
@@ -168,7 +169,38 @@ private static void openExternalFilePlatformIndependent(Optional<ExternalFileTyp
...
+
+                JabRefGUI.getMainFrame().output(Localization.lang("Executing command \"%0\"...", command));
+                LOGGER.info("Executing command \"" + command + "\"...");
+
+                try {
+                    new ProcessBuilder(subcommands).start();
+                } catch (IOException exception) {
+                    LOGGER.error("Open File Browser", exception);
+
+                    JOptionPane.showMessageDialog(null,
```
[the remark this answers is not in the document]
Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: Ok thanks, As I'm new to JabRef codebase I didn't knew how DialogService can be used, I'll make sure that I follow these conventions next time.

**Comment by Siedlerchr** [comment]
Could you please check issue #4802 as well?

**Comment by deepakkumar96** [comment]
@Siedlerchr  Okay, I'll try to fix this issue.

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 8]
```diff
@@ -51,18 +55,18 @@ public void openFileWithApplication(String filePath, String application) throws
 
     @Override
     public void openFolderAndSelectFile(Path filePath) throws IOException {
-        String desktopSession = System.getenv("DESKTOP_SESSION").toLowerCase(Locale.ROOT);
+        String desktopSession = System.getenv("DESKTOP_SESSION");
```
[the remark this answers is not in the document]
Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java]: Ok thanks, I'll make changes here.

File: src/main/java/org/jabref/gui/desktop/JabRefDesktop.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (deepakkumar96) [reply src/main/java/org/jabref/gui/desktop/JabRefDesktop.java]: this code is part of an older commit, in the latest commit I've replaced 'JOptionPane.showMessageDialog..''
with notify() method of DialogService, So now should I also replace notify() with showErrorDialogAndWait() ?
