### PR TITLE
Fixes generated bibtex key and display of institute authors

### LINKED ISSUE #6459: Generated Key contains 'null' when (corporate) author contains several special words after curly braces
JabRef version JabRef 5.0--2020-03-06--2e6f433 on Ubuntu 19.10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists (JabRef 5.1--2020-05-08--40f908f on Ubuntu 19.10).

1. Add the attached reference to a database
2. Check database integrity
3. Get notified of difference ("BibTex key deviates from generated key")
4. Go to mentioned key, click "generate key"
5. The key will now be "nullL2019".

Sample Bibliography
```bibtex
@Online{TSoL2019,
  author    = {{The School of Life}},
  editor    = {Abbot, Jack},
  date      = {2019-10-08},
  title     = {What Is The Secret Of Happiness?},
  url       = {https://youtu.be/sBSwJ6HOBG4},
  urldate   = {2019-11-05},
}
```

<details>
  <summary>Log File</summary>

  No events were generated in the event log, even though I followed procedure according to [the docs](https://docs.jabref.org/general/commandline), and I ran both the `.deb` and Portable versions (the latter I ran with the following options: `./JabRef --console --debug`).

  This was the output on the terminal:

  ```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.

(java:20862): Gdk-WARNING **: 18:01:46.992: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
  ```
</details>

### LINKED ISSUE #6465: Double bracketed author name shows wrong in author/editor column
JabRef 5.1–2020-04-14–e86d415 on Windows 10 10.0 amd64 with Java 14.0.1

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Even if an author name is protected with brackets, it appears only in part in the Author/Editor column.

1. Load the following entry:
```
@WWW{Apple2020,
  author  = {{Apple Inc.}},
  date    = {2020},
  title   = {Eseguire il backup dei file con Time Machine sul Mac},
  url     = {https://support.apple.com/it-ch/guide/mac-help/mh35860/mac},
  urldate = {2020-5-09},
  langid  = {italian},
}
```
2. (optional) Use this entry in a text (Latex or markdown) to verify the text reference and citation are correct
3. In JabRef Author/Editor column, the author is shown as “Inc.” when I expected "Apple Inc."
4.  Same problem for other compound names like {Quote Investigator} that shows “Investigator” and {The LOGO Foundation} that appear as “Foundation”.

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Fixes #6459. Fixes #6465 .

There are two parts of this issue,
1. A null is prepended to an abbreviated BibTeX key.
2. Curly brackets are not respected (in the maintable's author column?).

**1. Fix to the prepended null**
*What is going on?*
`BracketedPattern.generateInstitutionKey` gets called for any author enclosed in curly brackets (e.g., `"{The School of Life}"`). The method expects an institute of technology or university and appends its name to the key (e.g., null if there is no name).

*Why is it going on?*
Academic institutions can have long generated BibTeX keys unless abbreviated, e.g., `"Royal Institute of Technology: The School of Electrical Engineering and Computer Science"`, which `generateInstitutionKey` shortens to `RITEECS`.

*Fix*
Replace a null valued university with an empty string. The drawback is potentially very short BibTeX keys (e.g., `The School of Life` -> `L`).

*What are alternatives?*
1. Regex matching universities and technological institutions, which is hard to implement correctly. On the other hand, the drawback is an unexpected BibTeX key in a corner case. In the case of `The School of Life` would be abbreviated to `SL` instead of `L`.

**2. Fix to the author column**
When the list of authors gets converted to a latex-free version, all curly brackets are removed since the whole string is parsed as latex. When the latex-free string is used to create/fetch an `AuthorList` it will no longer contain any brackets, and the information needed to format the string is gone.

**3. What I think is left to do**
- [x] Find out why `{The School of Life}`  isn't respected in the author field of the GUI
- [x] ~~Attempt to match universities etc. with regex~~ Assume that names that have comma separated parts are universities
- [x] ~~Update `BibtexKeyGeneratorTest` as it makes heavy use of deprecated methods~~ the deprecated methods are essentially convenience methods so they have been moved inside the test file
- [x] See if the readability of `generateInstitutionKey` can be improved
- [x] ~~Change the key generator for institution/corporate names to a Formatter?~~ `generateInstitutionKey` should not be a separate Formatter, it is only called by `normalize`.

and

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
> Find out why {The School of Life} isn't respected in the author field of the GUI

I think it could be that the latex2unicode convert is called for the author field. It kills the extra braces. I had a similar problem in the MSOffice Exporter.  I think I implemented a workaround there.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Ah, nice, thank you! I will take a look!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I believe this is fixable in `BibEntry.getLatexFreeField` by splitting it into BibTeX/LaTeX according to whichever BibTeX version are supported, but the problems are,
1. I can't find which BibTeX version we are supporting in [ADR](https://github.com/JabRef/jabref/tree/master/docs/adr) nor anywhere else
2. `BibEntry.getLatexFreeField` appears to be used both for BibTeX in UTF-8 (e.g., `"{LâTëX}"`) and for fully "expanded" text (e.g., `"LâTëX"`). As those are incompatible perhaps it makes sense to split the method and track down what method wants what?
3. Should I do this?
4. I can attempt to do the same workaround but it doesn't really solve the problem (as I understand it)?

**Comment by Siedlerchr** [comment]
Hi,
thanks for investigating. The underlying problem is the latex2unicode (external library) kills the braces, it has of course no understanding of an author. Refs  #4152 and #6155 
I fear there is no easy solution. We use the Latexfree field method to not have latex code displayed in the main table #6329 
I would treat this as a secondary issue.

Regarding the second issue:
> Replace a null valued university with an empty string. The drawback is potentially very short BibTeX keys (e.g., The School of Life -> L).

What about using a formatter that uses the Capital letters?  e.g. JabRef would then become JR
and orgs with abbreviations e.g. UNO or WHO would stay as is. Similar to the title formatter.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Regarding the first issue, first of all, as you know, I am not a regular contributor to JabRef. If you'd like me to drop this topic for any reason, please say so. I am just hoping that sorting this out will save someone else time in the future, but I don't understand enough of JabRef to know if I have missed something important.

If I understand things correctly, there are currently three different cases relevant to #4337 and #4152.

Assuming we are using the BibTeX format described at [BibTeX.org (special symbols)](http://www.bibtex.org/SpecialSymbols/)
1. Plain BibTeX, e.g., `Kurt {G\"OD}el`: This is the internal representation?
2. BibTeX "with unicode", e.g., `Kurt {GÖD}el`: Exporting to a unicode-aware file format and editing in unicode?
3. Formatted text, e.g., `K. GÖDel`: This is supposed to be displayed to a user or exported to a LaTeX/BibTeX unaware environment.

`BibEntry.getLatexFreeField` handles case 3 while, to the best of my knowledge, no function/method handles case 2.

The issue with case 2 is that LaTeX and BibTeX are two incompatible "languages" (since some reserved words are the same). Therefore, if we are using the format described at [BibTeX.org (format)](http://www.bibtex.org/Format/), the "correct" way of dealing with case 2 using `BibEntry.getLatexFreeField` is to either split out the LaTeX components and "translate" them to unicode separately or to escape the parts that are in BibTeX format.  If I am using the [BibTeX.org format](http://www.bibtex.org/Format/), at least all non-nested curly bracketsl, not preceded by a keyword, should be escaped
* `{JabRef}` -> `\{JabRef\}` 
* `Proceedings of the {IEEE}` -> `Proceedings of the \{IEEE\}`

which is then dealt with correctly in `BibEntry.getLatexFreeField`.

What I was trying to argue is that case 2 and case 3 must be dealt with differently. I can deal with this after issue #6459 if that is of interest?

**However, I just realized that issue #6459 is case 3, and can most likely be solved by changing the order of method calls.** 

Please point out if something is unclear or incomprehensible. I am trying to improve my writing skills, but I am well aware that I have some practice ahead of me. My only excuse is that it is still morning here X)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Regarding the second issue. That does sound better. I can't think of any case where keeping all capitalized letters isn't good and it should be compatible with the current implementation.

**Comment by Siedlerchr** [comment]
>Regarding the first issue, first of all, as you know, I am not a regular contributor to JabRef. If you'd like me to drop this topic for any reason, please say so. I am just hoping that sorting this out will save someone else time in the future, but I am not familiar enough with JabRef to know if I have missed something important.

No problem :) We are happy for every contributor. It's just a complex issue. It's just complicated issue because it involves Corporate authors and Unicode.
I try to provide some background on this: 

**Unicode**:
Originally, bibtex and Latex did not support unicode. That's why you have to use those Latex-Escaping of umlauts and other characters.
Biblatex, the successor of bibtex, supports Unicode, but many journals still require bibtex.
And many citations from online resources still contain Latex-escaping of characters.
Originally JabRef maintained a bidirectional mapping between latex escaped characters and their Unicode equivalent. Some time ago we switched to the [latex2unicode library](https://github.com/tomtung/latex2unicode). 
Of course JavaFX has no idea of latex, therefore having a title or an author encoded in latex must obviously converted to Unicode for display.
e.g. => `Kurt {G\"OD}el` becomes `Kurt Gödel`

**Corporate Authors**:
See the [Biblatex manual](https://mirror.informatik.hs-fulda.de/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf) Section 2.3.3 Corporate Authors and Editors:

>Corporate authors and editors are given in the author or editor field, respectively.Note that they must be wrapped in an extra pair of curly braces to prevent data parsing from treating them as personal names which are to be dissected into their components. 
Example: 
`author= {{National Aeronautics and Space Administration}}`

In JabRef the latex2unicode formatter is called for **every field** and the formatter now receives the `string toConvert = {National Aeronautics and Space Administration}` 
The latex2unicode formatter now kills the curly braces as they could indicate some latex commands and returns `string converted = National Aeronautics and Space Administration`
JabRef now splits the author according to it rules and thinks it's in this case two authors separated by authors. 
The only solution I see is to check if it's a corporate authors, convert it to Unicode and add the braces again. One really difficult edge case is for example  ` author = {\L{}}ukasz Micha\l{}` 
Could be easily interpreted as corporate authors....

I hope my long explanation helps you a bit to understand the problem. Maybe you come up with an idea.

**Comment by rolandog** [comment]
Hello @k3KAW8Pnf7mkmdSMPHz27 , thank you for your work in fixing this issue! And thanks for that informative context @Siedlerchr ; that's a very interesting edge case... I think there could be a test where braces are counted to corroborate that the brace at the very beginning is not closed earlier on (that would be the case where formatting as a Corporate Author would apply, I think).

I have some code in Python that does something related... (though the opposite: it matches the most ancient parenthesis first...); I'll adapt it when I return home.

```python
def par_count2(text: Letters, opener: str = "(", closer: str = ")") -> Numbers:
    """Base algorithm to count matching parentheses.

    Parameters
    ----------
    `text` : `str`
        The string to be parsed against matching opener and closer
    `opener` : `str`
        The character(s) to be considered as the 'opener' of a sequence
    `closer` : `str`
        The character(s) to be considered as the 'end' of a sequence

    Yields
    ------
    `count` : `int`
        A sequence of `int` that are the number of matches for each character

    Examples
    --------
    Here are some base examples of expected output, and actual output.

        ``(((((((((``

        ``123456789``

    >>> [c for c in par_count2("(((((((((")]
    [1, 2, 3, 4, 5, 6, 7, 8, 9]

        ``)))))))))``

        ``123456789``

    >>> [c for c in par_count2(")))))))))")]
    [1, 2, 3, 4, 5, 6, 7, 8, 9]

        ``()()()()()()()()()``

        ``112233445566778899``

    >>> [c for c in par_count2("()()()()()()()()()")]
    [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9]

        ``((((((((()))))))))``

        ``123456789123456789``

    >>> [c for c in par_count2("((((((((()))))))))")]
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

        ``))()())(())``

        ``12334456767``

    >>> [c for c in par_count2("))()())(())")]
    [1, 2, 3, 3, 4, 4, 5, 6, 7, 6, 7]

    ``(A)()(A)()(B)()(A)()(A)``

    ``11122323445156673788949``

    >>> [c for c in par_count2("(A)()(A)()(B)()(A)()(A)")]
    [1, 1, 1, 2, 2, 3, 2, 3, 4, 4, 5, 1, 5, 6, 6, 7, 3, 7, 8, 8, 9, 4, 9]
    """

    # type declarations for local variables
    count: int
    character: str
    pending_from: int
    pending_to: int
    others: Counter[str]

    count = 0
    pending_from = 0
    pending_to = 0
    others = Counter()

    # logging recommends using %s substitutions, instead of f-strings or
    # string interpolation with brackets
    logger = logging.getLogger(__name__)
    logger.debug("About to parse %s with %s and %s", text, opener, closer)

    for character in text:
        if character == closer:
            if pending_from != pending_to:
                pending_from += 1
                yield pending_from
            else:
                count += 1
                pending_from = count
                pending_to = count
                yield count
        elif character == opener:
            count += 1
            pending_to = count
            yield count
        else:
            others.update(character)
            yield others.get(character, 0)

    logger.info("Parsed %s with %s and %s", text, opener, closer)
```

**Comment by Siedlerchr** [comment]
@rolandog  Your hint with the braces gave me the idea and I think we maybe have already a solution for this problem. I can't believe it's been hidden in plain sight 🤦 

This method is used in the BracketedPattern class to define if it's an insituation (corporate author or not) 

https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/strings/StringUtil.java#L418-L446


And the test:
https://github.com/JabRef/jabref/blob/862078a4db316cfd15bd77be68d3d2b010feab3b/src/test/java/org/jabref/model/strings/StringUtilTest.java#L181-L193

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hi @rolandog ! Thank you for the very detailed issue!! It makes things a lot easier :P

I have done a "bad" code update to demonstrate what I think is the issue with displaying names in the maintable (i.e., the order of method calls). @Siedlerchr and @rolandog you are both (of course) most welcome to add any comment/change any code and if there is any way I can make life easier for you do tell. I am currently quite new to Github and my todo-list, notes and links are currently kept in a offline jupyter document and I have no idea how to do it differently X)

@Siedlerchr thank you for the overview and the biblatex manual link. I have been looking for that one o.O
I am going to stay out of the biblatex discussion for now, because I believe `Kurt {G\"OD}el` should be `Kurt GÖDel`. It doesn't mean I am not interested in the issue, just that I have a lot of reading ahead of me, apparently a lot have changed since 1994 and BibTeX 1.0 ;)

**Comment by rolandog** [comment]
@k3KAW8Pnf7mkmdSMPHz27, you're welcome, I'm glad to have helped pinpoint this, and thank you for taking on this issue!

And, that's great @Siedlerchr, I'm happy that it seems that this may not need extreme refactoring; that's a very clever function!

However, I think I found an edge case where `isInCurlyBrackets` may present a false positive in its current form (inspired by the Corporate Author 'Kurt Gödel Society', but instead using 'Łukasz Michał' as part of a Corporate Author name).

I'm not familiar with JabRef's whole codebase, so mismatched braces may be caught earlier on, as per:

https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/logic/bibtex/FieldWriter.java#L41-L74

Here is an example, displayed as a test, where one of the entries would throw an error (the last one):

```java
@Test 
void testIsInCurlyBrackets() {
    /** correct
     * c        : {\L{}}ukasz Micha\l{}
     * brackets : 1  210             10
     * count    : 1  112             22
     */
    assertFalse(StringUtil.isInCurlyBrackets("{\L{}}ukasz Micha\l{}"));

    /** correct
     * c        : {{\L{}}ukasz Micha\l{} Society}
     * brackets : 12  321             21        0
     * count    : 11  111             11        1
     */
    assertTrue(StringUtil.isInCurlyBrackets("{{\L{}}ukasz Micha\l{} Society}"));

    /** mismatched braces, should return false?
     * c        : {{\L{}}ukasz Micha\l{} {Society}
     * brackets : 12  321             21 2       1
     * count    : 11  111             11 1       1
     */
    assertFalse(StringUtil.isInCurlyBrackets("{{\L{}}ukasz Micha\l{} {Society}"));
}

```

In case this isn't filtered by `CheckBraces`, then checking the final value of `brackets == 0` could prevent that edge case:

```java
/** 
 * Checks if the given String has exactly one pair of surrounding curly braces <br> 
 * Strings with escaped characters in curly braces at the beginning and end are respected, too 
 * @param toCheck The string to check 
 * @return True, if the check was succesful. False otherwise. 
 */ 
public static boolean isInCurlyBrackets(String toCheck) { 
    int count = 0; 
    int brackets = 0; 
    if ((toCheck == null) || toCheck.isEmpty()) { 
        return false; 
    } else { 
        if ((toCheck.charAt(0) == '{') && (toCheck.charAt(toCheck.length() - 1) == '}')) { 
            for (char c : toCheck.toCharArray()) { 
                if (c == '{') { 
                    if (brackets == 0) { 
                        count++; 
                    } 
                    brackets++; 
                } else if (c == '}') { 
                    brackets--; 
                } 
            } 
            return count == 1 && brackets == 0; 
        } 
        return false; 
    } 
}
```

**Comment by Siedlerchr** [comment]
@rolandog  Thanks for testing and checking that edge case. Feel free to submit a new PR and in that way you can also fix the workaround I used in the MSbibAuthor for the MS Office exporter 
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/logic/msbib/MSBibConverter.java#L119

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
"Curly brackets are not respected (in the maintable's author column?)." is the same as issue #6465.
Should I leave it alone in this PR or update this one to close both?

**Comment by Siedlerchr** [comment]
Since they are related you can update your PR to close both. Just add it also to the changelog then.

File: src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java [hunk 1]
```diff
@@ -119,17 +123,30 @@ public BibEntry getEntry() {
...
                         break;
                     }
                 }
 
                 String result = content.orElse(null);
                 if (isName) {
-                    return nameFormatter.formatName(result);
+                    String latexFreeBeforeNameFormatter = nameFormatter.formatName(result);
+
+                    String unformattedName = entry.getResolvedFieldOrAlias(anEntry, database).orElse(null);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java:140]: Maybe better to return an empty string instead of null in the orElse part

File: src/main/java/org/jabref/model/entry/AuthorList.java [hunk 2]
```diff
@@ -11,6 +11,8 @@
 import java.util.WeakHashMap;
 import java.util.stream.Collectors;
 
+import org.jabref.model.strings.LatexToUnicodeAdapter;
+
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline src/main/java/org/jabref/model/entry/AuthorList.java:15]: The changes in AuthorList are intended to create a similar behaviour to the already existing `getAsNatBib`. An alternative would be to create the cache as a weakhashmap in `MainTableNameFormatter` (and move the functionality from `model` to `gui` if that is appropriate)

Comment (Siedlerchr) [reply src/main/java/org/jabref/model/entry/AuthorList.java:15]: I think it's reasonable to have it in the AuthorList class.

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/model/entry/AuthorList.java:15]: Good! Then I will start writing test cases for it and see if I can find something that doesn't work :)
Thank you for taking a look at it!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I am having issues finding a case that is supposed to break the method `fixAuthorNatbibLatexFree`. I'll look at it a bit longer before extending the same tests to the other methods but I don't think I will come up with anything.

Other than that, I can't find any tests for `BibEntryTableViewModel` nor `MainTableNameFormatter`. I don't think I should attempt to create any as at least `BibEntryTableViewModel` has gone through quite a bit of changes recently.

**Comment by Siedlerchr** [comment]
If you can't find a case that's breaking the test it's a good sign ;)
Regarding tests for other classes, I think this would be beyond the scope of the PR here.

**Comment by Siedlerchr** [comment]
@k3KAW8Pnf7mkmdSMPHz27  As you now have some more deep insights into the bibtexkeypattern generation now than I, can you maybe help that usere here in the forum? https://discourse.jabref.org/t/help-with-regex-in-key-generation/2115

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Sure, I will look at it. I somehow missed that JabRef has a forum o.O

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
So, what remains are,
1. Preferences no longer updates without restart (e.g., from none to Natbib). That is not within the scope of the PR and I am guessing someone is fixing it already.
2. Weird things happens if you try to escape curly brackets in the author section of required fields. I am guessing the '\' is being protected somewhere. I can open up an issue about it but I don't have time to look at it until the 1th of May.

**Comment by Siedlerchr** [comment]
Thanks already for your contribution and the extensive tests. Just let me know if it's finished so far then we can review it. 

It would be nice if you could open an issue for the two problems, especially that preferences reloading. 
I guess escaping the curly brackets should hopefully be not that common in the author field. More relevant for the title field or so I guess.

File: src/main/java/org/jabref/gui/maintable/MainTableNameFormatter.java [hunk 3]
```diff
@@ -19,6 +19,31 @@
...
     }
 
+    /**
+     * Format a name field for the table, according to user preferences and with latex expressions translated if
+     * possible.
+     *
+     * @param nameToFormat The contents of the name field.
+     * @return The formatted name field.
+     */
+    public String formatNameLatexFree(final String nameToFormat) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTableNameFormatter.java:29]: The old `formatName` method is still used?

File: src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java [hunk 4]
```diff
@@ -41,9 +43,54 @@
...
     private static final int CHARS_OF_FIRST = 5;
-    private static final Pattern REGEX_PATTERN = Pattern.compile(".*\\(\\{([A-Z]+)\\}\\).*");
+
+    /** Matches everything that is not an uppercase ASCII letter */
+    private static final Pattern NOT_CAPITAL_FIRST_CHARACTER = Pattern.compile("[^A-Z]");
+    /** Matches with "({[A-Z]}+)", which should be used to abbreviate the name of an institution */
+    private static final Pattern ABBREVIATIONS = Pattern.compile(".*\\(\\{[A-Z]+}\\).*");
+    /** Matches with "dep"/"dip", case insensitive */
+    private static final Pattern DEPARTMENTS = Pattern.compile("^d[ei]p.*", Pattern.CASE_INSENSITIVE);
+    private enum INSTITUTION {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java:54]: Enum should have normal capitalization, i.e. `Institution`. The same holds true for the enum values

File: src/main/java/org/jabref/model/entry/AuthorList.java [hunk 5]
```diff
@@ -227,6 +233,15 @@ public static String fixAuthorFirstNameFirstCommas(String authors, boolean abbr,
         return AuthorList.parse(authors).getAsFirstLastNames(abbr, oxfordComma);
     }
 
+    /**
+     * This is a convenience method for getAuthorsFirstFirstLatexFree()
+     *
+     * @see AuthorList#getAsFirstLastNames
+     */
+    public static String fixAuthorFirstNameFirstCommasLatexFree(String authors, boolean abbr, boolean oxfordComma) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/model/entry/AuthorList.java:241]: I'm not a big fan of the `fix...` methods (I know you didn't introduced them) and would propose to inline all of them. With a bit of refactoring and extracting `AuthorList.parse(authors)` this shouldn't introduce that much more code elsewhere.

File: src/test/java/org/jabref/model/entry/AuthorListTest.java [hunk 6]
```diff
@@ -31,6 +41,82 @@ public void testFixAuthorNatbib() {
...
+    }
+
+    @Test
+    public void fixAuthorNatbibLatexFreeAuthorWithEscapedBrackets() {
+        assertEquals("Mic}h{ał",
+                AuthorList.fixAuthorNatbibLatexFree("{\\L{}}ukasz Mic\\}h\\{a\\l{}"));
+    }
+
+    @Test
+    public void fixAuthorNatbibLatexFreeInstituteAuthorWithEscapedBrackets() {
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/model/entry/AuthorListTest.java:115]: Thanks for adding so many tests. This is really good. I would propose to split them a bit into two categories: tests for parsing and test for representation. The former should take a string and test against a `AuthorList`. The latter should take a `AuthorList` and test against a string. In this way, problems can be diagnosed more easily as it is clear in which part of the code the problem occurs. 

(I'm aware that the existing tests also often don't adhere to this splitting...that's the problem with legacy code :( )

File: src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java [hunk 7]
```diff
@@ -115,28 +115,27 @@ public BibEntry getEntry() {
...
-                if (isName) {
-                    return nameFormatter.formatName(result);
-                } else {
-                    return result;
+        value = Bindings.createStringBinding(() -> {
+            boolean isName = false;
+
+            Optional<String> content = Optional.empty();
+            for (Field field : fields) {
+                content = entry.getResolvedFieldOrAlias(field, database);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java:125]: This now has the problem that latex code in other fields such as the title is no longer resolved. I think the `isName` check needs to be used before getting the field content.

File: src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java [hunk 8]
```diff
@@ -996,105 +1042,105 @@ void testcrossrefShorttitleInitials() {
...
+    void generateKeyWithShortTitleTitleCaseModifier() {
         BibEntry entry = new BibEntry();
         entry.setField(StandardField.TITLE, "the InTeresting title longer than THREE words");
-        assertEquals("InterestingTitleLonger", BibtexKeyGenerator.generateKey(entry, "shorttitle:titlecase"));
+        assertEquals("InterestingTitleLonger", generateKey(entry, "shorttitle:titlecase"));
     }
 
     @Test
-    void generateKeyWithTitleSentenceCaseModifier() throws Exception {
+    void generateKeyWithTitleSentenceCaseModifier() {
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java:1105]: You can safely ignore the `throws Exception` for tests (although the intellj warnings are there). In fact, it's good practice to add this to test methods so that the tests don't need to change if you add an exception to the method under test.

File: src/main/java/org/jabref/model/entry/AuthorList.java [hunk 9]
```diff
@@ -437,6 +488,17 @@ public String getAsLastNames(boolean oxfordComma) {
         return authorsLastOnly[abbrInt];
     }
 
+    public String getAsLastNamesLatexFree(boolean oxfordComma) {
+        int abbrInt = oxfordComma ? 0 : 1;
```
Comment (calixtus) [inline src/main/java/org/jabref/model/entry/AuthorList.java:492]: We normally try to avoid abbreviations. How ironic... :wink:
But I can see that this particular abbreviation was used before in other places in this class too, so never mind.
If you like, change it in all places in this class, if not, we can probably merge.

File: src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java [hunk 10]
```diff
@@ -879,15 +925,15 @@ void keywordNKeywordsSeparatedBySpace() {
         BibEntry entry = new BibEntry();
         entry.setField(StandardField.KEYWORDS, "w1, w2a w2b, w3");
 
-        String result = BibtexKeyGenerator.generateKey(entry, "keyword1");
+        String result = generateKey(entry, "keyword1");
```
Comment (calixtus) [inline src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java:928]: In other test cases you inline the argument for assertEquals.

File: src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java (hunk 7 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java:125]: > This now has the problem that latex code in other fields such as the title is no longer resolved.

That is not great :P 
I am unable to find where this happens, if you can provide me with an example I can hopefully fix it? I'd guess there is a cached value somewhere that I have missed.
Assuming it is only a caching mistake I should be able to improve the readability before this is merged into the master.

My thoughts regarding the changes were that,
The previous behaviour of these lines were to return a resolved and latex-free name (by the `isName` check) or null. The current behaviour (should be?) to return a resolved and latex-free name or an empty string (""), with lines 133-135 performing the same functionality as the previous `isName` check.

File: src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java (hunk 4 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java:54]: @tobiasdiez  No! In java Enum are all Uppercase see here:
>Because they are constants, the names of an enum type's fields are in uppercase letters.
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html

File: src/main/java/org/jabref/gui/maintable/MainTableNameFormatter.java (hunk 3 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/maintable/MainTableNameFormatter.java:29]: I don't think so.
I have been avoiding removing functionality or methods. As I am very junior, from a Java experience point of view, I was hoping that it would make reviewing and merging my code easier. If it has the opposite effect, I'll try to be more aggressive in adding, removing, and reformatting :P

File: src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java (hunk 4 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/logic/bibtexkeypattern/BracketedPattern.java:54]: Good catch and thanks for the link! Updating INSTITUTION -> Institution and I'll try to add it to my checkstyle.

File: src/test/java/org/jabref/model/entry/AuthorListTest.java (hunk 6 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/model/entry/AuthorListTest.java:115]: If I understand you correctly, all the tests I have added belongs to the latter category.

And, under the assumption that I do understand you correctly, I'll see if I can come up with some tests for the former (parsing) category.

File: src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java (hunk 8 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java:1105]: I don't have an opinion on this issue. I am, unfortunately, currently using Intellij recommendations instead of a brain/experience :P
Would you like me to add it to all methods in `BibtexKeyGeneratorTest` and/or should I keep it in mind for any future changes?

File: src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java (hunk 10 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java:928]: Yes. I don't have much experience with Java programming, therefore I mostly leave the original code unchanged. I try "pushing my luck" with readability "improvements" in `BrackettedPattern.generateInstitutionKey`(lines 1312-1429) as a way to balance improving my own Java programming knowledge without adding too much extra work for reviewers.

AuthorListTest lines 39-41 is another example of where I have left previous code untouched while I'd like to change it to use `assertSame`.

Right now, I view my PRs to JabRef as a balancing act. If I am being too cautious or bold, feel free to tell me. I'd be much happier if I leave JabRef's codebase better of without wasting too much time of reviewers :P

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> I just saw two minor style issues, nitpicks, but nothing important.

I am trying to learn and improve, nitpicking is appreciated and encouraged! :)

File: src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java (hunk 7 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java:125]: Scratch that, I found it.

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java:125]: Hum... I ran into an issue similar to #3356. I'll see if I can fix it/open up an issue on it later.

File: src/main/java/org/jabref/model/entry/AuthorList.java (hunk 9 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/model/entry/AuthorList.java]: I left one abbreviation because I am not really sure what it should be (firstabbr)

Comment (calixtus) [reply src/main/java/org/jabref/model/entry/AuthorList.java]: If in doubt, just name it firstAbbreviation 😆

File: src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java (hunk 8 above)
Comment (tobiasdiez) [reply src/test/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGeneratorTest.java:1095]: It was just a minor remark to keep in mind for the next time.

File: src/test/java/org/jabref/model/entry/AuthorListTest.java (hunk 6 above)
Comment (tobiasdiez) [reply src/test/java/org/jabref/model/entry/AuthorListTest.java]: I think you can easily split the tests you added in these categories. For the parsing, simply parse the new strings `Mu{\\d{h}}ammad al-Khw{\\={a}}rizm{\\={i}}` etc you added and compare them to the hand-created AuthorList (say `MUHAMMAD_ALKHWARIZMI = new AuthorList(...)`%. Then the tests you already added can be converted to operate on `MUHAMMAD_ALKHWARIZMI ` (which is now an AuthorList and no longer the string).

File: src/main/java/org/jabref/gui/maintable/MainTableNameFormatter.java (hunk 3 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/maintable/MainTableNameFormatter.java:29]: Thanks, that's a good approach and indeed makes reviewing easier. However, if you a method is no longer used you can safely remove it.

File: src/test/java/org/jabref/model/entry/AuthorListTest.java (hunk 6 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/test/java/org/jabref/model/entry/AuthorListTest.java]: I have updated with an attempt at implementing this split. However, I am struggling a bit with creating test cases for parsing as I don't know enough about JabRef/BibTeX/BibLaTeX/Biber.

1. In JabRef an author's first name can contain `}` as in `Ku{\}}rt G{\"{o}}del` -> `Ku}rt Gödel`. This doesn't work in any combination* of BibTeX/BibLaTeX/Biber that I have tried.
2. The test case I am trying contains `{` as in `Ku{\{}rt G{\"{o}}del` -> `Ku{rt Gödel` which is not supported by JabRef nor any combination* of BibTeX/BibLaTeX/Biber.

So for now I am limiting the scope to not include escaped latex brackets. It is a very contrived case that is unlikely to happen, and since I don't understand why it doesn't work I probably shouldn't be writing test cases for it :P

With combinations of BibTeX/BibLaTeX/Biber, I mean that I tried BibTeX by itself, BibLaTeX with BibTeX backend, and BibLaTeX with biber backend.

Comment (tobiasdiez) [reply src/test/java/org/jabref/model/entry/AuthorListTest.java]: Sounds good to me. I think an escaped bracket in an author name is indeed very rare!

File: src/main/java/org/jabref/model/entry/AuthorList.java (hunk 9 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/model/entry/AuthorList.java]: > If in doubt, just name it firstAbbreviation 😆

😱

Joke aside. firstAbbreviation is actually an improvement on firstabbr, fair enough 😝

**Comment by calixtus** [comment]
@k3KAW8Pnf7mkmdSMPHz27 Big thanks for your work on this.

I just noticed some latex commands are not cleared in the now-master-build.
Has this been an issue before / is this still an issue with Latex2UnicodeAdapter?

image

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Which file in particular and which settings?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hum... I am not sure what is going on, I'll have a look

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Most of those should be "cleared" and are cleared when I build locally, but that might be something wrong with my setup.

**Comment by Siedlerchr** [comment]
Looks fine for me as well:
grafik

Firstname lastname option and do not abbreviate

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I think I could reproduce @calixtus screenshot in JabRef 5.1--2020-05-28--ffa07cd but right now I seem unable to do so again (and I have tried).

**Comment by Siedlerchr** [comment]
@k3KAW8Pnf7mkmdSMPHz27 If you have "Show names unchanged in the prefs" then no conversion is happening

**Comment by calixtus** [comment]
I see, so the solution would be to change `return nameToFormat` to `return Latex2UnicodeAdapter.format(nameToFormat)` or similar in MainTableNameFormatter...

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@calixtus I thought the intent of that option was to leave the names completely unchanged?
Also, if you change that, don't forget to add a caching

**Comment by calixtus** [comment]
Uh im not going to change anything today 😄 
I was just wondering about that...

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hum... actually that is my bad. JabRef 5.0 does indeed "clear" the latex, even when `Show names unchanged` is set... Should I open up an issue and fix this then?

**Comment by tobiasdiez** [comment]
Yes, it would be nice if you could provide a fix (no need to create an issue before).

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Ok, I apparently don't know how to do this. I created [https://github.com/JabRef/jabref/pull/6552](https://github.com/JabRef/jabref/pull/6552)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Well, thank you all for reviewing this PR, it is very appreciated! ❤️ 🎉 🎈

I'll take the reviews and results to heart, and make sure the next PR will create fewer issues 🤦
