### PR TITLE
fix: make more fields, fomatters, ids and languages sorted by alphabetical order

### LINKED ISSUE #7716: Some more fields in random order
JabRef 5.3--2021-05-08--4f398d8
Linux 4.19.0-16-amd64 amd64 
Java 16.0.1 
JavaFX 16+8

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

I have found some other drop down menus where fields are not sorted (like in issue #7710):
- List of fields (i.e. exact same list as issue #7710):
    - Menu `Library -> Library properties`, in section `Save sort order`: Primary, secondary and tertiary sort criteria.
    - Menu `Options -> Preferences`, in tab `File`, section `Export sort order`: Primary, secondary and tertiary sort criteria.
    - Menu `Options -> Preferences`, in tab XMP metadata: drop-down list of the column `Field name`.

- List of actions:
    - Menu `Library -> Library properties`, in section `Save actions`, drop-down list of the column `Formatter name`.
    - Menu `Quality -> Cleanup actions`, in section `Enable field formatters`, drop-down list of the column `Formatter name`.

- Menu `Library -> New entry...`, drop-down list of `ID type`.

- Menu `Options -> Preferences`, in tab `General`, drop-down list of `Language`.

### PR DESCRIPTION
**Pull request by dateri**
Fixes #7716
We fix that more fields, fomatters, ids and languages sorted by alphabetical order. Solving them by either adding sort to relative property or using a `SortedList` to wrapper the ObservableList.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/EntryTypeViewModel.java [hunk 1]
```diff
@@ -60,6 +61,7 @@ public EntryTypeViewModel(PreferencesService preferences,
         this.dialogService = dialogService;
         this.stateManager = stateManager;
         fetchers.addAll(WebFetchers.getIdBasedFetchers(preferences.getImportFormatPreferences()));
+        fetchers.sort(Comparator.comparing(IdBasedFetcher::getName));
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/EntryTypeViewModel.java:64]: As I said in a comment I don't think it's useful to sort by alphatical order here. DOI fetcher should always be on top because it's the most important one

File: src/main/java/org/jabref/gui/preferences/file/FileTabViewModel.java [hunk 2]
```diff
@@ -84,6 +85,10 @@ public void setValues() {
         secondarySortFieldsProperty.addAll(fieldNames);
         tertiarySortFieldsProperty.addAll(fieldNames);
 
+        primarySortFieldsProperty.sort(Comparator.comparing(Field::getDisplayName));
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/preferences/file/FileTabViewModel.java:88]: Simple solution but not effective. You are essentially doing the same sort 3 times.
I would create: `List<Field> fieldNames = new ArrayList<>(FieldFactory.getCommonFields())`
Then sort it and add it to the properties

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Some minor improvements

File: src/main/java/org/jabref/gui/EntryTypeViewModel.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/EntryTypeViewModel.java:64]: So please revert that

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks for the quick follow up, lgtm to me now. For external contributors a second developer needs to review and approve

**Comment by Siedlerchr** [comment]
Happens from time to time, most often the mac build fails due to notarization somehow not working at apple's side. 
you can then downlod the artifact from the run
https://github.com/JabRef/jabref/actions/runs/829332567
