### PR TITLE
UI: Fix for group icon

### LINKED ISSUE #4129: Replace default group icon by small circle
The current triangle has the disadvantage of being to small to show color and, moreover, can easily be mistaken for the arrow symbol that expands/collapses a group hierarchy. 

Material design icons provide a full circle but this one is slightly to large. 

@halirutan may I assign you this issue since you are our expert in creating custom font-based icons (e.g. a smaller circle or whatever you think is suitable)?

### LINKED ISSUE #7550: Monocolor for icons
JabRef version

JabRef 5.3--2021-03-17--d190268
Linux 5.8.18-050818-generic amd64 
Java 15.0.2 
JavaFX 16+8

on Ubuntu 20.04

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Set either the priority or read status, the icons are mono-color and the same all options, making them indistinguishable visually. (But the status in the source file is correctly set)

### PR DESCRIPTION
**Pull request by mohit038**
Fixes #4129

Replaced the default group play icon by small circle.

Screenshot 2021-03-20 at 4 13 02 PM

I think this also fixes #7550.

Screenshot 2021-03-20 at 4 59 33 PM

Screenshot 2021-03-20 at 5 07 50 PM

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks for your PR. The problem with the default circle is that it is rather big and thus dominates the interface too much (it's pretty hard to read the group label because your eyes are constantly focusing the big colorfull blob in front of it). It would be thus nice if this circle could be scaled down (without scaling other icons, because they get too small otherwise).

**Comment by Siedlerchr** [comment]
Can you check if the color thing fixes #7550 as well?

**Comment by mohit038** [comment]
@tobiasdiez 
Thanks for the suggestion, I think the icon library has been updated and different sizes of circles are already present in the library.
Let me know which one do you prefer.

1. CIRCLE_MEDIUM

Screenshot 2021-03-20 at 6 37 23 PM

2. RECORD
Screenshot 2021-03-20 at 6 56 09 PM

**Comment by mohit038** [comment]
> Can you check if the color thing fixes #7550 as well?
I checked it and also updated the screenshots in https://github.com/JabRef/jabref/pull/7552#issue-597260059.
It fixes all of the issues mentioned in #7550.

**Comment by mohit038** [comment]
> Can you check if the color thing fixes #7550 as well?

I checked it and also updated the screenshots in https://github.com/JabRef/jabref/pull/7552#issue-597260059.
It fixes all of the issues mentioned in #7550.

**Comment by Siedlerchr** [comment]
Cool! For me RECORD looks appropriate

**Comment by tobiasdiez** [comment]
That's awesome. I agree, record looks the best.

File: src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java [hunk 1]
```diff
@@ -41,7 +43,7 @@ public Node getGraphicNode() {
         Ikon icon = icons.get(0);
         FontIcon fontIcon = FontIcon.of(icon);
         fontIcon.getStyleClass().add("glyph-icon");
-        color.ifPresent(fontIcon::setIconColor);
+        color.ifPresent(color -> fontIcon.setStyle(fontIcon.getStyle() + String.format("-fx-fill: %s;", ColorUtil.toRGBCode(color))));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java:46]: Do you know why `setIconColor` doesn't work? Maybe add a short comment so that we will not revert it in the future by accident.

Comment (mohit038) [reply src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java:46]: Sorry, I have no idea.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java:46]: It has something to do with the style class. If you uncomment the line "getStyleClass.add("glyph-icon")" than it works properly. However, then the rest of the icons are black because that property is set in the css (and is obviously different for dark and base.css) and therefore overrides the color of the 'FontIcon". 

So add a comment like:
Override the default color from the css files

**Review by Siedlerchr — APPROVED** [review]

**Comment by tobiasdiez** [comment]
Thanks again!
