### PR TITLE
Make path relative when adding automatically found file

### LINKED ISSUE #3476: automatically added file link has absolute instead of relative path
- [x ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.1-dev--snapshot--2017-11-30--master--d45d7ca38
Linux 3.16.0-38-generic amd64 
Java 1.8.0_151
on Mint 17 (Ubuntu 14.04)

Steps to reproduce:

1. import new entry
2. add file with bibtex key into file directory
3. open new entry in entry editor

I just switched from v4.0 to the latest development version, because Medline import did not work in v4.0 anymore. Unfortunately, now files appear to be added with absolute paths to the library. E.g., I added entry Lake2016 and Jabref now automatically adds the corresponding file as `/home/bitzer/papers/Lake2016.pdf` instead of as `Lake2016.pdf` as before. So I have to manually edit the file link to get the relative path. Is that intended behaviour and how do I get Jabref to automatically add relative links again?

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #3476

----

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/test/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtilTest.java [hunk 1]
```diff
@@ -30,22 +31,25 @@
...
         when(externalFileTypes.getExternalFileTypeSelection()).thenReturn(new TreeSet<>(externalFileTypes.getDefaultExternalFileTypes()));
 
     }
 
     @Test
     public void test() {
         //Due to mocking the externalFileType class, the file extension will not be found
-        List<LinkedFile> expected = Collections.singletonList(new LinkedFile("", file.toString(), ""));
+
+        String relativeFilePath = FileUtil.shortenFileName(file, dirs).toString();
```
Comment (tobiasdiez) [inline src/test/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtilTest.java]: Well, now the test uses the same logic as the method under test. Could you please hard code the expected value. It should be just `CiteKey.pdf`, right?
