### PR TITLE
Fix for #4628 - cant save new content selectors

### LINKED ISSUE #4628: Can't save new content selectors
Current master.
Options -> Manage content selectors
Enter new field and new keyword,
press apply or enter 

Is still a swing dialog.  Refs #3861 

```

17:00.740 [AWT-EventQueue-0] INFO  org.jabref.gui.contentselector.ContentSelectorDialog - Could not apply changes in "Manage content selectors" - java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113) 
```

### PR DESCRIPTION
**Pull request by ricantech**
Fixes #4628
Dialog converted into JavaFX
* old functionalities are preserved
* new validations added:
** error message thrown when dialog invoked but not active connection exists
** remove keyword button is enabled just in case some keyword is selected

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+    private void removeKeyword() {
+        Optional<String> fieldName = getSelectedFieldName();
+        Optional<String> keywordToRemove = getSelectedKeyword();
+        if (fieldName.isPresent() && keywordToRemove.isPresent()) {
+            viewModel.showRemoveKeywordConfirmationDialog(fieldName.get(), keywordToRemove.get());
+        }
+    }
+
+    private void initListView(ListView<String> listViewToInit, Supplier<ObservableList<String>> backingList, ChangeListener<String> onSelectedListener) {
+        listViewToInit.setItems(backingList.get());
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: Better use bindings, so you can get a better separation between the view and the ViewModel.

myListView.itemsProperty().bind(viewModel.backingListProperty);
Same also applies to selectedItemProperty 
Sth like this          `viewModel.seletedItemProperty().bind(listView.getSelectionModel().selectedItemProperty());`


This also removes the need to have the ChangeListener, because the bindings under the hood have the change listener implemented

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+        addKeywordButton.setDisable(newValue == null);
+        viewModel.populateKeywordsFor((newValue));
+    }
+
+    private void onKeywordSelected() {
+        removeKeywordButton.setDisable(!getSelectedKeyword().isPresent());
+    }
+
+    private Optional<String> getSelectedFieldName() {
+        return Optional.of(fieldNamesListView.getSelectionModel()).map(SelectionModel::getSelectedItem);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: This should also be moved to the viewModel

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: And if you change this to a BoooleanProperty in the viewModel, you can directly bind to it:
removeFieldNameButton.disableProperty().bind(viewModel.isSelectedFieldNamePrsent))

public BooleanProperty isSelectedFieldNamePresent{
return  ! selectedItemProperty().getValue().isEmpty() 
}

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+        }
+    }
+
+    private void populateFieldNameKeywordsMapWithExistingValues() {
+        metaData.getContentSelectors().getContentSelectors().forEach(
+                existingContentSelector -> fieldNameKeywordsMap.put(existingContentSelector.getFieldName(), new ArrayList<>(existingContentSelector.getValues()))
+        );
+    }
+
+    ObservableList<String> getFieldNamesBackingList() {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java]: Convert this to a ListProperty<String> fieldNamesProperty()

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+class ContentSelectorDialogViewModel {
+
+    private static final List<String> DEFAULT_FIELD_NAMES = of(FieldName.AUTHOR, FieldName.JOURNAL, FieldName.KEYWORDS, FieldName.PUBLISHER);
+
+    private final MetaData metaData;
+    private final DialogService dialogService;
+    private final BasePanel basePanel;
+    private final Map<String, List<String>> fieldNameKeywordsMap = new HashMap<>();
+
+    private ObservableList<String> fieldNames = FXCollections.observableArrayList();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java]: Convert this to a `LIstProperty<String> fieldNamesProperty = new SimpleListProperty(FXCollections.observableArrayList())`

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+                existingContentSelector -> fieldNameKeywordsMap.put(existingContentSelector.getFieldName(), new ArrayList<>(existingContentSelector.getValues()))
+        );
+    }
+
+    ObservableList<String> getFieldNamesBackingList() {
+        return fieldNames;
+    }
+
+    ObservableList<String> getKeywordsBackingList() {
+        return keywords;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java]: same as above

**Comment by Siedlerchr** [comment]
Additionally, it would be nice if you could add a screenshot  of the converted dialog

**Comment by ricantech** [comment]
@Siedlerchr Hi, thanks for the review.

I hope I was able to incorporate all the changes mentioned above - ListProperty + bindings
Here is the screenshot of converted dialog:
image

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java (hunk 5 above)
Comment (ricantech) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java]: Fixed e4f3ea3

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java (hunk 4 above)
Comment (ricantech) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java]: Fixed e4f3ea3

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java (hunk 3 above)
Comment (ricantech) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogViewModel.java]: Fixed e4f3ea3

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java (hunk 2 above)
Comment (ricantech) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: Fixed 205170c

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java (hunk 1 above)
Comment (ricantech) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: Fixed 205170c

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java [hunk 6]
```diff
@@ -0,0 +1,127 @@
...
+        Optional<String> fieldName = getSelectedFieldName();
+        Optional<String> keywordToRemove = getSelectedKeyword();
+        if (fieldName.isPresent() && keywordToRemove.isPresent()) {
+            viewModel.showRemoveKeywordConfirmationDialog(fieldName.get(), keywordToRemove.get());
+        }
+    }
+
+    private void initListView(ListView<String> listViewToInit, Supplier<ListProperty<String>> backingList) {
+        listViewToInit.itemsProperty().bind(backingList.get());
+        listViewToInit.getSelectionModel().select(FIRST_ELEMENT);
```
[the remark this answers is not in the document]
Comment (ricantech) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: Fixed c00274c

**Comment by ricantech** [comment]
@tobiasdiez Thanks for the review - changes have been made

File: src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java [hunk 7]
```diff
@@ -0,0 +1,125 @@
...
+    private final BasePanel basePanel;
+    private final DialogService dialogService;
+    private final MetaData metaData;
+
+    public ContentSelectorDialogView(JabRefFrame jabRefFrame) {
+        this.setTitle(Localization.lang("Manage content selectors"));
+        this.getDialogPane().setPrefSize(375, 475);
+
+        this.basePanel = jabRefFrame.getCurrentBasePanel();
+        this.dialogService = jabRefFrame.getDialogService();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: I would change the constructor to only accept basePanel as Argument, because you can do the following:
    @Inject private DialogService dialogService;
This automatically injects (passes an instance of it) to the class

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: Just this one change and it looks good to me ;)

Comment (ricantech) [reply src/main/java/org/jabref/gui/contentselector/ContentSelectorDialogView.java]: Good point :) fixed - c32fe6a

**Comment by tobiasdiez** [comment]
Thanks again for your contribution! Looking forward to your next PR ;-)

**Comment by ricantech** [comment]
Thanks guys for super guidance!

**Comment by Siedlerchr** [comment]
@ricantech  We have to thank you for your contribution! We hope you are interested in fixing some other issues as well!
