### PR TITLE
fix: display help when JabKit is started without arguments

### LINKED ISSUE #13622: JabKit should display help when started without any argument
When starting JabKit for example using `jbang run .jbang/JabKitLauncher.java ` it should show the help.

Currently it only shows this and exits:

Image

Instead it should look like this:

Image

### PR DESCRIPTION
**Pull request by pranayh24**
- Add check for empty args array in JabKit.main()
- Show full usage help instead of just banner when no arguments provided
- Fixes issue where JabKit would exit silently without guidance

Fixes #13622

Closes #13622

When JabKit is started without any arguments (e.g., `jbang run .jbang/JabKitLauncher.java`), it now displays the full help message with available commands and options instead of just showing the banner and exiting silently. This provides better user experience by guiding users on how to use the tool.

### Steps to test

1. Navigate to the JabRef repository root directory
2. Run JabKit without any arguments: `jbang run .jbang/JabKitLauncher.java`
3. Verify that the full help message is displayed, showing:
   - JabRef banner with version
   - "JabKit - command line toolkit for JabRef" branding
   - Usage syntax
   - Available commands (convert, fetch, pdf, etc.)
   - Available options (-h, --help, -v, --version, etc.)
4. Test that existing functionality still works by running with arguments: `jbang run .jbang/JabKitLauncher.java --help`

**Before fix:** Only banner displayed, then exits
Screenshot 2025-08-01 230025

**After fix:** Full help message displayed
Screenshot 2025-08-01 230113

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [/] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [/] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (if change is visible to the user)
- [/] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [/] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: jabkit/src/main/java/org/jabref/JabKit.java [hunk 1]
```diff
@@ -85,6 +85,12 @@ public static void main(String[] args) {
                     ArgumentProcessor.getAvailableImportFormats(preferences),
                     ArgumentProcessor.getAvailableExportFormats(preferences),
                     WebFetchers.getSearchBasedFetchers(preferences.getImportFormatPreferences(), preferences.getImporterPreferences()));
+
+            if (args.length == 0) {
+                commandLine.usage(System.out);
+                System.exit(0);
+            }
```
Comment (koppor) [inline jabkit/src/main/java/org/jabref/JabKit.java:86]: Isn't this a bit too late? Why not directly at line 60?

**Review by koppor — CHANGES_REQUESTED** [review]

**Comment by pranayh24** [comment]
Thanks! I've added the fail-fast check for empty arguments. The program now shows help and exits immediately when no args are provided, avoiding the expensive setup you mentioned. This gives users proper guidance instead of just the banner.

File: jabkit/src/main/java/org/jabref/JabKit.java (hunk 1 above)
Comment (pranayh24) [reply jabkit/src/main/java/org/jabref/JabKit.java:86]: Thanks! I've added the fail-fast check for empty arguments. The program now shows help and exits immediately when no args are provided, avoiding the expensive setup you mentioned. This gives users proper guidance instead of just the banner.

**Comment by koppor** [comment]
Maybe, I was wrong with the move to the first line. I saw

    String usageHeader = BuildInfo.JABREF_BANNER.formatted(new BuildInfo().version) + "\n" + JABKIT_BRAND;

The current solution does not output this banner any more, does it?

Maybe, move down again and add a comment that usage help needs the banner information available at that place.

**Comment by pranayh24** [comment]
Thanks for pointing that out, the banner should definitely be shown with the help output.

We could either:

Keep the early check and just init the banner info before showing help, or

Move the check back down where the banner is already set (as you suggested), with a small comment.

Let me know what you’d prefer, happy to go with either!

**Comment by palukku** [comment]
I'd say moving it back down so it is as I would have used the `--help`

File: jabkit/src/main/java/org/jabref/JabKit.java (hunk 1 above)
Comment (subhramit) [reply jabkit/src/main/java/org/jabref/JabKit.java:86]: @pranayh24 Note that using AI to communicate is against our [contributing guidelines](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md#notes-on-ai-usage). Please use your brain to think and your own words to communicate.

**Comment by pranayh24** [comment]
I moved the empty-args help check after setting up the header and footer, so running JabKit without arguments shows the same help as --help.
Also delayed heavy setup until after parsing args and reused a single BuildInfo object instead of creating multiple.

**Review by calixtus — APPROVED** [review]
