### PR TITLE
Check group type before showing dialog in edit group

### LINKED ISSUE #8189: When changing a group color, no dialog should appear
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Edit the properties of a group
2. Change the color
3. Click "OK"
4. Dialog "Change of Grouping Method" appears  
  grafik

Expected behavior: No dialog appears, just the group color should change

Refs https://github.com/JabRef/jabref/issues/7325

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by LIM0000**
## Proposed solution
Fixes #8189 
Create 2 functions `compareGroupType()` and `compareGroupFields()` in `GroupTreeViewModel.java` to compare
1. both `oldGroup` and `newGroup` group types
2. groups' fields/properties between `oldGroup` and `newGroup`

Warning dialog only appears:
- user changes group type (change `Collect by`)
- user modifies any field/property that corresponds to `Collect by`

Warning dialog does not appear if user modifies:
- [ ] user changing the name of a group using explicit selection. --> could be fixed in a follow up pull-request
- [x] Description
- [x] Icon
- [x] Color
- [x] Hierarchical context

## PR checklist:
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java [hunk 1]
```diff
@@ -386,7 +385,9 @@ public void setValues() {
             descriptionProperty.setValue(editedGroup.getDescription().orElse(""));
             iconProperty.setValue(editedGroup.getIconName().orElse(""));
             groupHierarchySelectedProperty.setValue(editedGroup.getHierarchicalContext());
+            typeExplicitProperty.setValue(true);
 
+            /*
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:390]: Is this all obsolete?

Comment (LIM0000) [reply src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java]: Hi @Siedlerchr , this is outdated.
I have changed my solution to fix this issue.

**Comment by Siedlerchr** [comment]
Current problem: The dialog does not come up, changes are not stored

**Comment by ThiloteE** [comment]
:+1:

**Comment by Siedlerchr** [comment]
TODO: Investigate reassignment of entries to groups under certain conditions.

**Comment by Siedlerchr** [comment]
TODO: When we change the groups name we need to check if the new name already exists. If yes then show dialog, else continue and assign all entries to new group and unassign them from the old group.

File: src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java [hunk 2]
```diff
@@ -182,61 +185,163 @@ private void writeGroupChangesToMetaData() {
...
+     * Check if it is necessary to show a group modified, reassign entry dialog <br>
+     * Group name change is handled separately
+     *
+     * @param oldGroup Original Group
+     * @param newGroup Edited group
+     * @return true if just trivial modifications (e.g. color or description) or the relevant group properties are equal, false otherwise
+     */
+    boolean onlyMinorChanges(AbstractGroup oldGroup, AbstractGroup newGroup) {
+        // we need to use getclass here because we have different subclass inheritance e.g. ExplicitGroup is a subclass of WordKeyWordGroup
+        if (oldGroup.getClass() == WordKeywordGroup.class) {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java:202]: is there no way to solve this by using instanceof and pattern matching?

File: src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java [hunk 3]
```diff
@@ -182,61 +185,163 @@ private void writeGroupChangesToMetaData() {
...
+                    // This is ugly but we have no proper update mechanism in place to propagate the changes, so redraw everything
+                    refresh();
+                    return;
+                }
+
+                if (groupTypeEqual && onlyMinorChanges(oldGroup.getGroupNode().getGroup(), group)) {
+                    oldGroup.getGroupNode().setGroup(
+                                     group,
+                                     true,
+                                     true, // TODO Not sure
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java:293]: ?

File: src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java [hunk 4]
```diff
@@ -182,61 +185,163 @@ private void writeGroupChangesToMetaData() {
...
-                        content,
-                        keepAssignments,
-                        removeAssignments,
-                        cancel);
-                //        WarnAssignmentSideEffects.warnAssignmentSideEffects(newGroup, panel.frame());
+                                                                                                       Localization.lang("Change of Grouping Method"),
+                                                                                                       content,
+                                                                                                       keepAssignments,
+                                                                                                       removeAssignments,
+                                                                                                       cancel);
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java:317]: whitespaces... still eclipse config hurting.

File: src/test/java/org/jabref/gui/groups/GroupTreeViewModelTest.java [hunk 5]
```diff
@@ -39,12 +45,13 @@ void setUp() {
...
         when(preferencesService.getGroupsPreferences()).thenReturn(new GroupsPreferences(
-                GroupViewMode.UNION,
-                true,
-                true,
-                new SimpleObjectProperty<>(',')
-        ));
+                                                                                         GroupViewMode.UNION,
+                                                                                         true,
+                                                                                         true,
+                                                                                         new SimpleObjectProperty<>(',')));
```
Comment (calixtus) [inline src/test/java/org/jabref/gui/groups/GroupTreeViewModelTest.java:54]: whitespaces

**Comment by Siedlerchr** [comment]
I merge now.
