### PR TITLE
Fix: Usage of "Copy to" option preference

### LINKED ISSUE #12500: "Copy To" option does not follow the preferences
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

There is a bug in the 'Copy To' option. Even after setting it to include cross-referenced entries in the dialog box, it does not include them the next time.

1. Copy an entry using the Copy To option.
2. When prompted, choose to include the cross-referenced entries and select "Do not ask again".
3. Copy another entry again using the Copy To option.

https://github.com/user-attachments/assets/34b18fcf-ecae-4250-95ec-21c7f71ead3e

### PR DESCRIPTION
**Pull request by priyanshu16095**
### Fixes #12500

This fix ensures that the "Copy to" option follows the chosen preference correctly.

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

https://github.com/user-attachments/assets/93a6dde8-776a-4b80-94df-4f779d10843c

### CODE REVIEW

File: src/main/java/org/jabref/gui/edit/CopyTo.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public void execute() {
             }
         }
 
-        if (includeCrossReferences) {
+        if (copyToPreferences.getShouldIncludeCrossReferences()) {
```
Comment (subhramit) [inline src/main/java/org/jabref/gui/edit/CopyTo.java:62]: I'm having a bit of trouble understanding this due to the naming.
What does the field `includeCrossReferences` do?
And why is it's state different from `copyToPreferences.getShouldIncludeCrossReferences()`?

**Review by subhramit — COMMENTED** [review]
I didn't go through this thoroughly before so trying to gather context:

https://github.com/JabRef/jabref/blob/19df622d4a0a057d5d3cedaaf4677527612de8e7/src/main/java/org/jabref/gui/edit/CopyTo.java#L48-L64

Correct me if I'm wrong, the preference is independent of entries, and if the preference is enabled, we should check for cross references in entries. Why then are we setting the preference for each entry with a cross reference (with each iteration)?

**Comment by subhramit** [comment]
The unit tests also need to be looked at.

**Comment by subhramit** [comment]
> @subhramit At that time, I tried it in a way that if the user had selected multiple entries, it would individually ask for confirmation for each entry that had cross-referenced entries.

I would not say that's a good way to do it - especially if a user is working with a large number of entries.

> I will try to improve this, in the same PR.

🚀

Change the title as well to "Improve Copy to option + fix usage of preference" or something if you plan to do that. A separate PR is also fine, up to you.

**Review by Siedlerchr — DISMISSED** [review]

**Comment by Siedlerchr** [comment]
Please chekc the failing unit tests, otherwise it looks good

**Comment by Siedlerchr** [comment]
Is this ready now?

**Review by Siedlerchr — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Review by koppor — APPROVED** [review]
Looked at it. OK. Next time, add some Java Comment -> the "break" took me 30 seconds to understand without any comment.
