### PR TITLE
Fix issue 9863 - Change Tab selection order

### LINKED ISSUE #9863: Change tab selection order
## Problem
Hard to navigate groups via keyboard because long tab selection sequence and no key binding to focus on groups.

## Solution
Change tab selection order in a common way (e.g., windows explorer or mozilla thunderbird)

```[tasklist]
### Tasks
- [ ] When entry table is focused press `shift` + `tab` to focus on groups
- [ ] When groups are focused press `tab` to focus on entry table
```

## Context
[https://discourse.jabref.org/t/key-binding-to-focus-groups-interface/3803](https://discourse.jabref.org/t/key-binding-to-focus-groups-interface/3803)

### PR DESCRIPTION
**Pull request by YifeiShi99**
Fixes #9863

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 1]
```diff
@@ -320,6 +320,10 @@ private void initKeyBindings() {
                         getCurrentLibraryTab().getMainTable().requestFocus();
                         event.consume();
                         break;
+                    case FOCUS_GROUP_LIST:
+                        this.stateManager.getGroupTree().requestFocus();
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/JabRefFrame.java:324]: Why a call to the state manager? Jabref frame is the topmost ui Element. It should be no problem to navigate through the children to find the grouptreeview and focus on it.

File: src/main/java/org/jabref/gui/keyboard/KeyBinding.java [hunk 2]
```diff
@@ -55,7 +55,8 @@ public enum KeyBinding {
     FILE_LIST_EDITOR_MOVE_ENTRY_DOWN("File list editor, move entry down", Localization.lang("File list editor, move entry down"), "ctrl+DOWN", KeyBindingCategory.VIEW),
     FILE_LIST_EDITOR_MOVE_ENTRY_UP("File list editor, move entry up", Localization.lang("File list editor, move entry up"), "ctrl+UP", KeyBindingCategory.VIEW),
     FIND_UNLINKED_FILES("Search for unlinked local files", Localization.lang("Search for unlinked local files"), "shift+F7", KeyBindingCategory.QUALITY),
-    FOCUS_ENTRY_TABLE("Focus entry table", Localization.lang("Focus entry table"), "alt+1", KeyBindingCategory.VIEW),
+    FOCUS_ENTRY_TABLE("Focus entry table", Localization.lang("Focus entry table"), "TAB", KeyBindingCategory.VIEW),
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/keyboard/KeyBinding.java:58]: Why did you change this?

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 3]
```diff
@@ -321,7 +322,7 @@ private void initKeyBindings() {
                         event.consume();
                         break;
                     case FOCUS_GROUP_LIST:
-                        this.stateManager.getGroupTree().requestFocus();
+                        getGroupTreeView().getGroupTree().requestFocus();
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/JabRefFrame.java:325]: Instead of exposing the whole API of the tree view I would suggest just to add a request focus method to the API of the sidepane component, which itself then calls the requestfocus of it's child.

Comment (YifeiShi99) [reply src/main/java/org/jabref/gui/JabRefFrame.java]: added request focus method in sidepane component

File: src/main/java/org/jabref/gui/keyboard/KeyBinding.java (hunk 2 above)
Comment (YifeiShi99) [reply src/main/java/org/jabref/gui/keyboard/KeyBinding.java:58]: this is changed to match the Tasks of focusing on entry table after pressing tab from the pull request #9863

File: src/main/java/org/jabref/gui/groups/GroupTreeView.java [hunk 4]
```diff
@@ -609,4 +609,9 @@ public void execute() {
             }
         }
     }
+
+    /**
+     * Focus on GroupTree
+     */
+    public void requestFocusGroupTree() { groupTree.requestFocus(); }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupTreeView.java:616]: Please fix the checkstyle issue

File: src/main/java/org/jabref/gui/sidepane/SidePaneComponent.java [hunk 5]
```diff
@@ -71,4 +72,13 @@ private Node createHeaderView() {
...
         this.buttonContainer.getChildren().add(position, button);
     }
+
+    public void requestFocus() {
+        for (Node child : getChildren()) {
+            if (child instanceof GroupTreeView) {
+                ((GroupTreeView) child).requestFocusGroupTree();
+                break;
+            }
+        }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/sidepane/SidePaneComponent.java:82]: Casting can be omitted by the new pattern matching feature of java
```suggestion
        for (Node child : getChildren()) {
            if (child instanceof GroupTreeView groupTreeView) {
                groupTreeView.requestFocusGroupTree();
                break;
            }
        }
```

File: src/main/java/org/jabref/gui/groups/GroupTreeView.java (hunk 4 above)
Comment (YifeiShi99) [reply src/main/java/org/jabref/gui/groups/GroupTreeView.java]: checkstyle issue fixed

File: src/main/java/org/jabref/gui/sidepane/SidePaneComponent.java (hunk 5 above)
Comment (YifeiShi99) [reply src/main/java/org/jabref/gui/sidepane/SidePaneComponent.java]: casting has been replaced by pattern matching

File: src/main/java/org/jabref/gui/keyboard/KeyBinding.java (hunk 2 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/keyboard/KeyBinding.java:58]: Is it still possible to navigate away from the entry table? I would see tab as cycling though different ui components: Main menu entries, groups, main table, entry editor, ...

It should be possible to focus these elements using quick shortcut. Alr+1 was such a shortcut.

**Review by koppor — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/gui/keyboard/KeyBinding.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/keyboard/KeyBinding.java:58]: I think there is a bit of a misunderstanding of the issue:
Tab and Shift Tab are coming from the operating system and mean:
Tab: Forward navigation between controls
Shift + Tab: Backwards navigation between controls 

The guy means: If you have the entry editor open, pressing shift + tab should navigate to the group. And if your focus is on the group; Navigation with tab should go forward to the 
 But I think this might be difficult. It depends on the order of the Nodes in the javafx scencegraph. Focus model etc.
I would rather add two extra shortcuts (like you did), but with separate shortcuts: like alt+1 or alt+2

Comment (YifeiShi99) [reply src/main/java/org/jabref/gui/keyboard/KeyBinding.java:58]: Hi Siedlerchr, we can use alt + 1 to focus on the entry table (like before) and alt + 2 to focus on the group list

Comment (koppor) [reply src/main/java/org/jabref/gui/keyboard/KeyBinding.java]: I think the reporter @DvP17 at https://github.com/JabRef/jabref/issues/9863 really meant a proper <kbd>Tab</kdb> cycling order. I agree, however, that this is very difficult to implement. A workaround using Alt+1 and Alt+2 is OK for me.

Note that the hotkey system was revised at https://github.com/JabRef/jabref/pull/1525. Updated at https://github.com/JabRef/jabref/pull/1605.

| Keys - new | Keys - old | Function |
| --- | --- | --- |
| F7 | alt + f | Automatically set file links |
| F8 | ctrl + shift + F7 | Cleanup entries |
| alt + 1 | ctrl + shift + E | Focus entry table |
| alt + 2 | ctrl + F9 | Toggle entry/preview editor |
| alt + 3 | ctrl + shift + G | Toggle groups |
| alt + 4 | F5 | web search |
| alt + 0 | - | Open Openoffice/LibreOffice connection |
| ctrl + shift + F7 | ctrl + f4 | Synchronize file links |
| ctrl + shift R | - | Technical report |
| - | alt + P | Print entry preview |
| - | ctrl + alt + T | Hide/show toolbar |
| - | ctrl+P | Edit preamble |

Maybe, we should think about propr key binding defaults. Alt+Number is used for both toggle and focus in the implementation of 2016.

Comment (koppor) [reply src/main/java/org/jabref/gui/keyboard/KeyBinding.java]: Note that we have a blog article on a revised hotkey system in 2016: https://blog.jabref.org/2016/08/15/HotkeyRevision/

**Comment by Siedlerchr** [comment]
DevCall: Decision: Remove unused Preamble Store Change  key binding
Reuse default keybinding alt + s to focus on the group

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
Thank you for your contribution. We would be happy to see more contributions from your side.
