### PR TITLE
Fix entry gets deleted after aux import

### LINKED ISSUE #6405: Entry is missing after sublibrary is generated from aux file
JabRef version 5.0 on Windows 10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. The test package is available at https://github.com/xx256xx/test, including a tex file, the original bib **my.bib**, a aux file **report.aux**.
2. I attempt to generate a sub library using **report.aux** from **my.bib**. 
3. In Jabref window, the sub library succeeds to generate the sub library. See jabref
4. However, this entry is not found in the saved bib file ( you can check it at my repo, named by **sub.bib**). jabref2
5. If I fill in the "date" field and save again, the resultant bib is correct.

No log available.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Set changed flag on clone also for Misc entry type, because otherwise it equals the default entry type and no change is triggered which results in the entry not beeing written to the database on save
Fixes  #6405

Simplify gui code

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/model/entry/BibEntry.java [hunk 1]
```diff
@@ -603,10 +604,15 @@ public boolean allFieldsPresent(Collection<OrFields> fields, BibDatabase databas
     /**
      * Returns a clone of this entry. Useful for copying.
      * This will set a new ID for the cloned entry to be able to distinguish both copies.
+     * Ensures that the changed flag is set when the entry type equals the default entry type Misc
      */
     @Override
     public Object clone() {
         BibEntry clone = new BibEntry(type.getValue());
+        if (StandardEntryType.Misc.equals(type.getValue())) {
+            clone.changed = true;
```
Comment (koppor) [inline src/main/java/org/jabref/model/entry/BibEntry.java:613]: I would doubt that this fixed the issue for the other types. -- When the entry type is Article, the clone is unchanged, too. Thus, no serialization written

File: src/main/java/org/jabref/model/entry/BibEntry.java [hunk 2]
```diff
@@ -603,10 +604,15 @@ public boolean allFieldsPresent(Collection<OrFields> fields, BibDatabase databas
...
+        }
+
         clone.fields = FXCollections.observableMap(new ConcurrentHashMap<>(fields));
         return clone;
```
Comment (koppor) [inline src/main/java/org/jabref/model/entry/BibEntry.java:617]: Isn't it possible to clone the serializatio, too. Then, the issue should be fixed?

File: src/main/java/org/jabref/model/entry/BibEntry.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/model/entry/BibEntry.java:613]: New BibEntryType(entryType) always calls setType() and thus:
The default value for field.get is the default entry type misc.

https://github.com/JabRef/jabref/blob/7cc57474b7aa991ef6ea148d4030d4bb68ee69bf/src/main/java/org/jabref/model/entry/BibEntry.java#L360-L371

Comment (Siedlerchr) [reply src/main/java/org/jabref/model/entry/BibEntry.java:613]: For all other non default entry types the change flat is correclty set that was what this issue made so special.

File: src/main/java/org/jabref/model/entry/BibEntry.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/model/entry/BibEntry.java:617]: The issue is already fixed with the changed = true. But I added it as well now

File: CHANGELOG.md [hunk 3]
```diff
@@ -97,6 +97,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue with the creation of a group of cited entries. Now the file path to an aux file gets validated. [#6585](https://github.com/JabRef/jabref/issues/6585)
 - We fixed an issue on Linux systems where the application would crash upon inotify failure. Now, the user is prompted with a warning, and given the choice to continue the session. [#6073](https://github.com/JabRef/jabref/issues/6073)
 - We moved the search modifier buttons into the search bar, as they were not accessible, if autocompletion was disabled. [#6625](https://github.com/JabRef/jabref/issues/6625)
+- We fixed an entry where entries with the entry type Misc from an imported aux file would not be saved correctly to the bib file on disk [#6405](https://github.com/JabRef/jabref/issues/6405)
```
Comment (tobiasdiez) [inline CHANGELOG.md:100]:
```suggestion
- We fixed an issue where entries with the entry type Misc from an imported aux file would not be saved correctly to the bib file on disk [#6405](https://github.com/JabRef/jabref/issues/6405)
```

File: src/main/java/org/jabref/model/entry/BibEntry.java (hunk 1 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/model/entry/BibEntry.java:613]: I wouldn't update the `changed` flag. The clone method should really clone the original entry, without any modifications (otherwise its not a clone).

However, the aux importer should set the changed flag of all entries (regardless of type), so that they get properly reformatted when writing them to disc (i.e. not using the parsed serialization of the original bib file).

Comment (Siedlerchr) [reply src/main/java/org/jabref/model/entry/BibEntry.java:613]: Well, the clone method implicitly sets the changed flags for all entry types except the default entry type. 
The aux importer has nothing to do with this changed or serialization stuff. It's only relevant for saving the newly created library.  I don't see any reason to add this logic to the AuxImporter
Only the BibTexParser does it.

**Comment by koppor** [comment]
@calixtus and me implemented all required changes.

**Comment by Siedlerchr** [comment]
Manually tested the changes again, All good. Merge now
