### PR TITLE
Fix default import format pattern

### LINKED ISSUE #4724: Wrong default filename format pattern
JabRef 5.0-dev--snapshot--2019-03-06--master--ddd12aec4

The default file format patterns given in the Preferences->Import drop down menu are `bibtexkey` and `bibtexkey - title`, however this leads to files being named literally `bibtexkey.pdf`. The correct options should be `[bibtexkey]` and `[bibtexkey] - [title]` -- then the renaming (and moving) of files works in the cleanup entries.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Remove Display Array
Add migration
Fixes #4724

----

- [ ] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/migrations/PreferencesMigrations.java [hunk 1]
```diff
@@ -237,10 +237,16 @@ static void upgradeImportFileAndDirePatterns(JabRefPreferences prefs, Preference
...
             String[] newStylePatterns = new String[] {"[bibtexkey]",
-                                                      "[bibtexkey] - [fulltitle]"};
+                                                      "[bibtexkey] - [title]"};
+
+            String[] oldDisplayStylePattern = new String[] {"bibtexkey", "bibtexkey - title",};
+
             for (int i = 0; i < oldStylePatterns.length; i++) {
                 migrateFileImportPattern(oldStylePatterns[i], newStylePatterns[i], prefs, mainPrefsNode);
             }
+            for (int i = 0; i < oldDisplayStylePattern.length; i++) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/migrations/PreferencesMigrations.java]: Do we really need a migration here? As this bug was introduced in 5.0 I doubt that many users are affected...

Comment (Siedlerchr) [reply src/main/java/org/jabref/migrations/PreferencesMigrations.java]: It looks weird as it will display a wrong value in the field next to the combobox (then selectable)
