### PR TITLE
Fixed #1245

### LINKED ISSUE #1245: Jstyle files - improper handling of quotation marks
JabRef version 3.3 on Windows 10

Steps to reproduce:

1. .Use the Citation file below/ rename to .jstyle
[test.txt](https://github.com/JabRef/jabref/files/226348/test.txt)

2. Have a look at:
BracketBefore=""
BracketAfter=""

They are defined with quoutation marks according to the example at: http://jabref.sourceforge.net/OOPlugin-jabref.php 

2. create an empty LO document and cite some entries
3. The following happens: ""DOE 1998""...

Expected was an entry without "brackets" before and after: DOE 1998
I know, the expected behavior can be triggered by the following code:
BracketBefore=
BracketAfter=

but for other cases quotation marks are needed, leaving me with inconsistent property definitions

### PR DESCRIPTION
**Pull request by oscargus**
This should fix #1245 so that it is possible to set empty strings is jstyle-files as `key=""`

### CODE REVIEW

**Comment by tobiasdiez** [comment]
LGTM but can you please add a test for the fix.

**Comment by oscargus** [comment]
Yes, but not right now. Good point!

**Comment by stefan-kolb** [comment]
Could you please add a test for it so we can merge this in :smile: ? We already closed the related issue.

**Comment by oscargus** [comment]
Done! Will merge when I see that the tests pass.

File: src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java [hunk 1]
```diff
@@ -494,4 +494,26 @@ public void testCompareToNotEqual() throws IOException {
         assertTrue(style1.compareTo(style2) > 0);
         assertFalse(style2.compareTo(style1) > 0);
     }
+
+
+    public void test1245AndOxfordComma() throws URISyntaxException, IOException {
```
Comment (stefan-kolb) [inline src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java]: Dont call it 1234 please :smile:

Comment (oscargus) [inline src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java]: Yeah, I do not really know what it checks. ;-) (But I'll figure something out.)

Comment (stefan-kolb) [inline src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java]: Something with empty strings as values?! maybe the oxford comma is even a separate test case?

Comment (oscargus) [inline src/test/java/net/sf/jabref/logic/openoffice/OOBibStyleTest.java]: I was considering a separate test case, but it would (could) look exactly the same, so I thought it made more sense to have both in one.
