### PR TITLE
Validates the file path of a TexGroup and fixes Texgroup's "Library has been modified by another program"

### LINKED ISSUE #6420: Creating or editing a group of cited entries triggers "Library has been modified by another program." whenever saving the library subsequently
Tested with the latest JabRef development version (master branch) on Ubuntu 16.04

<ins>Steps to reproduce the behavior (creating group):</ins>

1. Save current library (only needed, if the library is indicated as modified)
2. Create a group of cited entries with an attached `*.aux` file
    -  Side note: even without attaching an existing `*.aux` file and leaving this field empty allows reproducing it as well
3. The library has been modified, indicated by the star character (*) in the tab of the main table
4. Save library

*Observation:*

**After saving the library, the message "Library has been modified by another program." shows up, asking either to choose "Dismiss changes" or "Review changes". When such a group has been created (or updated), then this message appears whenever the library is changed and gets saved.**

<ins>Steps to reproduce the behavior (editing group):</ins>

After restarting JabRef and opening the previously opened library the aforementioned issue does not arise until one does the following (or one repeats the steps above):

1. Save current library (only needed, if the library is indicated as modified)
2. Edit an existing group of cited entries
3. Click "OK" to save the changes in the dialog for editing an existing group of cited entries (no changes need to be made in the dialog)
4. A dialog appears, asking "Assign the original group's entries to this group?"
4.1. Either click "Cancel" or "OK" (it does not matter)
5. The library has been modified, indicated by the star character (*) in the tab of the main table
6. Save library

*Observation:*

**After saving the library, the same issue as described above arises.**

<ins>Remark:</ins>

As stated in #6394, groups of cited entries also have another issue.

<ins>Removal of issue:</ins>

1. Delete the group of cited entries or change the group type to something different than "Cited entries".

*Observation:*

The issue vanishes.

### LINKED ISSUE #6585: Exceptions occur when starting JabRef with an opened library which contains a group of cited entries
Exceptions occur when starting JabRef with an opened library which contains a group of cited entries and subsequently the group's content will not be reloaded on startup.

Will be partially fixed by #6584.

### PR DESCRIPTION
**Pull request by systemoperator**
Fixes #6420.
Fixes #6585.

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java [hunk 1]
```diff
@@ -117,103 +119,113 @@ public GroupDialogViewModel(DialogService dialogService, BibDatabaseContext curr
...
+                                                                                                            Localization.lang("Search term is empty."))));
+
+        texGroupFilePathValidator = new FunctionBasedValidator<>(
+                                                                 texGroupFilePathProperty,
+                                                                 input -> {
+                                                                     if (StringUtil.isNullOrEmpty(input)) {
+                                                                         return false;
+                                                                     } else if (input.trim().length() == 0) {
+                                                                         return false;
+                                                                     }
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:224]: I think this check can be reduced to `StringUtil.isBlank()`.

File: src/main/java/org/jabref/logic/importer/util/MetaDataParser.java [hunk 2]
```diff
@@ -49,61 +51,55 @@ public MetaData parse(MetaData metaData, Map<String, String> data, Character key
         List<String> defaultCiteKeyPattern = new ArrayList<>();
         Map<EntryType, List<String>> nonDefaultCiteKeyPatterns = new HashMap<>();
 
-        for (Map.Entry<String, String> entry : data.entrySet()) {
+        // process GROUPSTREE and GROUPSTREE_LEGACY at the very end (otherwise it can happen that not all dependent data are set)
+        Stream<Map.Entry<String, String>> stream = data.entrySet().stream().filter(entry -> !entry.getKey().equals(MetaData.GROUPSTREE) && !entry.getKey().equals(MetaData.GROUPSTREE_LEGACY));
+        Stream<Map.Entry<String, String>> streamTail = data.entrySet().stream().filter(entry -> entry.getKey().equals(MetaData.GROUPSTREE) || entry.getKey().equals(MetaData.GROUPSTREE_LEGACY));
+        stream = Stream.concat(stream, streamTail);
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:57]: Can you please use more meaningful variable names? Like `entrySetStream` and `groupsTreeStream` or similar.

File: CHANGELOG.md [hunk 3]
```diff
@@ -83,6 +83,8 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where "null" appeared in generated BibTeX keys. [#6459](https://github.com/JabRef/jabref/issues/6459)
 - We fixed an issue where the authors' names were incorrectly displayed in the authors' column when they were bracketed. [#6465](https://github.com/JabRef/jabref/issues/6465) [#6459](https://github.com/JabRef/jabref/issues/6459)
 - We fixed an issue where importing certain unlinked files would result in an exception [#5815](https://github.com/JabRef/jabref/issues/5815)
+- We fixed an issue with creating a group of cited entries, which wrongly triggered that the library had been changed externally. [#6420](https://github.com/JabRef/jabref/issues/6420)
```
Comment (calixtus) [inline CHANGELOG.md:86]: The english here sounds a bit rough. I myself often use deepl.com to produce texts, since english isn't my mother tongue. There's no shame in that. 😉

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java [hunk 4]
```diff
@@ -212,8 +214,27 @@ private void setupValidation() {
...
+                        return false;
+                    } else if ((input.length() < 4) || !input.substring(input.length() - 4).toLowerCase().equals(".aux")) {
+                        return false;
+                    } else {
+                        Path path = preferencesService.getWorkingDir();
+                        File texFile = new File(path.toString(), input);
+                        if (!texFile.exists() || !texFile.isFile()) {
+                            return false;
+                        }
+                        return true;
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:234]: Have you tried `FileUtil.find()` here?

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java [hunk 5]
```diff
@@ -212,8 +214,27 @@ private void setupValidation() {
...
+                        Localization.lang("Search term is empty."))));
+
+        texGroupFilePathValidator = new FunctionBasedValidator<>(
+                texGroupFilePathProperty,
+                input -> {
+                    if (StringUtil.isNullOrEmpty(input)) {
+                        return false;
+                    } else if (input.trim().length() == 0) {
+                        return false;
+                    } else if ((input.length() < 4) || !input.substring(input.length() - 4).toLowerCase().equals(".aux")) {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:226]: This can probably abbreviated with `FileUtil.getFileExtension()`

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java (hunk 4 above)
Comment (systemoperator) [reply src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:232]: I'm not sure, whether this is a good idea. I intended to explicitly check the provided file, without searching other locations. :thinking:

**Comment by systemoperator** [comment]
I don't know where to put `import org.apache.logging.log4j.core.util.FileUtils;`. Wherever I put it, checkstyle fails.

**Comment by Siedlerchr** [comment]
@systemoperator  We have our own FileUtil class in model or logic, beware of the import.

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java (hunk 4 above)
Comment (systemoperator) [reply src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java]: I have adapted it.

**Comment by calixtus** [comment]
Checkstyle is failing because of now unused import io.file.

**Comment by systemoperator** [comment]
Apparently, this PR also fixes #6394. At least I could not reproduce it so far. I will test it onwards.

File: src/main/java/org/jabref/logic/importer/util/MetaDataParser.java [hunk 6]
```diff
@@ -49,61 +51,55 @@ public MetaData parse(MetaData metaData, Map<String, String> data, Character key
         List<String> defaultCiteKeyPattern = new ArrayList<>();
         Map<EntryType, List<String>> nonDefaultCiteKeyPatterns = new HashMap<>();
 
-        for (Map.Entry<String, String> entry : data.entrySet()) {
+        // process GROUPSTREE and GROUPSTREE_LEGACY at the very end (otherwise it can happen that not all dependent data are set)
+        Stream<Map.Entry<String, String>> entrySetStream = data.entrySet().stream().filter(entry -> !entry.getKey().equals(MetaData.GROUPSTREE) && !entry.getKey().equals(MetaData.GROUPSTREE_LEGACY));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:55]: I think sorting the entries as described here https://stackoverflow.com/a/30286728/873661 is a bit more readable.

File: src/main/java/org/jabref/logic/importer/util/MetaDataParser.java [hunk 7]
```diff
@@ -49,61 +51,55 @@ public MetaData parse(MetaData metaData, Map<String, String> data, Character key
...
+        Stream<Map.Entry<String, String>> entrySetStreamTail = data.entrySet().stream().filter(entry -> entry.getKey().equals(MetaData.GROUPSTREE) || entry.getKey().equals(MetaData.GROUPSTREE_LEGACY));
+        entrySetStream = Stream.concat(entrySetStream, entrySetStreamTail);
+
+        Iterator<Map.Entry<String, String>> entryIterator = entrySetStream.iterator();
+
+        while (entryIterator.hasNext()) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:61]: A more "streamy" way is using the `stream.foreach(...)` method.

Comment (systemoperator) [reply src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:61]: In the loop exceptions may be thrown. It's slightly complicated to throw them back within a lambda expression (at least for me).

**Comment by systemoperator** [comment]
> Just to make sure that I understand the changes correctly: the issue is fixed by parsing the groups last?
Yes, because the groups access data which need to be defined beforehand. Depending on the sequence in the of the entry set, this may work once but not every time.

File: src/main/java/org/jabref/logic/importer/util/MetaDataParser.java (hunk 7 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:61]: ok, good argument. I think first using `collect` to get an ordinary list and then using foreach is still slightly better.

File: src/main/java/org/jabref/logic/importer/util/MetaDataParser.java [hunk 8]
```diff
@@ -49,68 +52,62 @@ public MetaData parse(MetaData metaData, Map<String, String> data, Character key
         List<String> defaultCiteKeyPattern = new ArrayList<>();
         Map<EntryType, List<String>> nonDefaultCiteKeyPatterns = new HashMap<>();
 
-        for (Map.Entry<String, String> entry : data.entrySet()) {
+        // process groups (GROUPSTREE and GROUPSTREE_LEGACY) at the very end (otherwise it can happen that not all dependent data are set)
+        Stream<Map.Entry<String, String>> entrySetStream = data.entrySet().stream().sorted(groupsLast());
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:56]: Just an idea: Can creating streams theoretically be omitted by using `List.copyof(data.entrySet()).sort(groupsLast())` ?

**Comment by systemoperator** [comment]
Now without stream.^^

Any suggestion how to test the case mentioned by @tobiasdiez?

**Comment by tobiasdiez** [comment]
The code looks good to me! For the test, it should be similar to the following:
https://github.com/JabRef/jabref/blob/7cc57474b7aa991ef6ea148d4030d4bb68ee69bf/src/test/java/org/jabref/logic/importer/fileformat/BibtexParserTest.java#L1369-L1389

Create the string by hand (with groups before the other setting that makes troubles) and then verify that the groups in the parsed metadata has the valid data.

**Comment by systemoperator** [comment]
The test was a bit tricky (access real file, relative, user name, hostname, ...), but it works now.

File: src/main/java/org/jabref/logic/importer/util/MetaDataParser.java [hunk 9]
```diff
@@ -49,68 +50,63 @@ public MetaData parse(MetaData metaData, Map<String, String> data, Character key
...
-                case MetaData.FILE_DIRECTORY:
-                    metaData.setDefaultFileDirectory(getSingleItem(value));
-                    break;
-                case MetaData.SAVE_ORDER_CONFIG:
-                    metaData.setSaveOrderConfig(SaveOrderConfig.parse(value));
-                    break;
-                default:
-                    // Keep meta data items that we do not know in the file
-                    metaData.putUnknownMetaDataItem(entry.getKey(), value);
+            } else if (entry.getKey().equals(MetaData.SAVE_ACTIONS)) {
```
[the remark this answers is not in the document]
Comment (calixtus) [reply src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:74]: This is still a huge p.i.t.a.
Checkstyle really needs to keep up, people start getting tired of these workarounds.
Some background information, if you are interested: https://github.com/checkstyle/checkstyle/issues/6615

[the remark this answers is not in the document]
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:74]: The key problem is here that switch cases are not executed in order. That's the reason for the if else

[the remark this answers is not in the document]
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:74]: In the concrete case here, it is **always** checked for `entry.getKey()`. Please check the diff:

grafik

The wrong order was at that diff - completely unrelated to my proposal!

grafik

[the remark this answers is not in the document]
Comment (systemoperator) [reply src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:74]: Yes, the `switch` statement could be reintroduced (and simplified). Before this fix, the code was structured really confusing and looked error-prone. So I decided to create this consistent and simplified version, which I find quite acceptable.

[the remark this answers is not in the document]
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/util/MetaDataParser.java:74]: I meant only for the lower part; not with the xxxx continue statements. Just for the endless chain of `else if (entry.getKey().equeals(MetaData.X))` chains, where only `X` is different from the checks.

There is ALWAYS `entry.getKey()` compared from line 75 to line 92 (or did I see something wrong?).

This is just a matter of taste. Maybe, I'll just do it and open another PR to have the discussions there. Should not be a show stopper for us now.

File: src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java [hunk 10]
```diff
@@ -212,8 +214,24 @@ private void setupValidation() {
...
-                        Localization.lang("Search term is empty.")
-                )));
+                        Localization.lang("Search term is empty."))));
+
+        texGroupFilePathValidator = new FunctionBasedValidator<>(
+                texGroupFilePathProperty,
+                input -> {
+                    if (StringUtil.isBlank(input)) {
+                        return false;
+                    } else {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java:224]: @stefan-kolb Would review here: "Fail fast". Not endless nested if/else statements, but just exit early.

Therefore, I proposed:

```java
if (StringUtil.isBlank(input)) {
  return false;
}
```

Think, I will start another PR with this and the other code style thing and we can have the discussion there --> we need to get this fix in soon.
