### PR TITLE
Fix #15397 invisible delete area for internal CSL styles

### LINKED ISSUE #15397: Remove invisible delete button for internal CSL styles
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 6.0-alpha.147--2026-03-17--d7c59e3 Windows 10 10.0 amd64  Java 25.0.2  JavaFX 26+27

### Checked with the [latest development build](https://builds.jabref.org/main/) (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour
1. Connect to OO/LO document
2. Select Style

Image

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by Francis-Lee-210**
### Related issues and pull requests

Closes #15397

### PR Description

This fixes the invisible delete area shown for internal CSL styles in the OpenOffice/LibreOffice style selection dialog.

The delete cell is now explicitly cleared for empty rows and internal styles, so internal CSL styles no longer show a visible or invisible delete area. External CSL styles still show the delete button and remain deletable.

### Steps to test

1. Open JabRef and connect to an OpenOffice/LibreOffice document.
2. Open the OpenOffice/LibreOffice panel and click **Select style**.
3. In **CSL Styles**, verify that internal CSL styles no longer show a visible or invisible delete area.
4. Import an external `.csl` style.
5. Verify that the external style still shows the delete button and can still be deleted.

#### Comparison screenshots
- Before:
Before

- After - Internal  CSL styles:
After-Internal

- After - External  CSL styles:
After-External

#### Library screenshot:
截屏2026-03-24 20 02 08

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/openoffice/StyleSelectDialogView.java [hunk 1]
```diff
@@ -141,17 +143,26 @@ private void setupCslStylesTab() {
...
-                    }
-                })
-                .withTooltip(_ -> Localization.lang("Remove style"))
-                .install(cslDeleteColumn);
+                CSLStyleSelectViewModel style = getTableRow().getItem();
+                setGraphic(IconTheme.JabRefIcons.DELETE_ENTRY.getGraphicNode());
+                setTooltip(new Tooltip(Localization.lang("Remove style")));
+                setOnMouseClicked(_ -> viewModel.deleteCslStyle(style.getLayout().citationStyle()));
+            }
+        });
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/openoffice/StyleSelectDialogView.java]: Please use our ValueTableCellFactory.

Comment (Francis-Lee-210) [reply jabgui/src/main/java/org/jabref/gui/openoffice/StyleSelectDialogView.java]: I updated the implementation to use ValueTableCellFactory, re-tested it locally, and pushed the change.

I also noticed that the Validate requirement coverage check keeps getting cancelled/timing out. Do I need to do anything on my side for that, or is it a CI/workflow issue?

**Comment by subhramit** [comment]
@Francis-Lee-210 please update the screenshots after your most recent change

**Comment by pluto-han** [comment]
Just tried out this PR, found one problem:
1. Add .csl file
2. "Remove style" does not remove the file from the UI immediately, unless users reopen the dialog

https://github.com/user-attachments/assets/ad1c6049-89cc-4870-a13f-61991c665af0

**Comment by pluto-han** [comment]
> Just tried out this PR, found one problem:

But the problem seems not related to this change.

**Comment by subhramit** [comment]
> Just tried out this PR, found one problem:
> 
> 1. Add .csl file
> 2. "Remove style" does not remove the file from the UI immediately, unless users reopen the dialog

Is the problem there on the `main` branch as well? Or just this PR?

**Comment by pluto-han** [comment]
> Is the problem there on the `main` branch as well? Or just this PR?

It exists in the `main` branch as well. An error shows up when removing the "removed" csl file again.
image

**Comment by subhramit** [comment]
> > Is the problem there on the `main` branch as well? Or just this PR?
> 
> It exists in the `main` branch as well. An error shows up when removing the "removed" csl file again. 

Good finding - create an issue

**Comment by calixtus** [comment]
Please address qodo comments

**Comment by Francis-Lee-210** [comment]
> Please address qodo comments

It looks like the failing job is guard-reviewers, and the error says the workflow cannot find ./.github/actions/pr-gate. From the log, this seems to be a workflow-side issue rather than a problem in the patch itself. Please let me know if you’d like me to do anything on my side.

Addressed the qodo comments in the latest commit.

- Cleared stale tooltips for reused CSL delete cells
- Restricted deletion to primary click only
- Consumed delete-cell clicks so they do not trigger the row double-click selection behavior

Manually verified that external custom CSL styles remain deletable, internal styles show no delete icon/tooltip, and normal row double-click selection still works outside the delete cell.
External-delete buttom
Internal-no delete buttom

File: jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java [hunk 2]
```diff
@@ -127,14 +127,15 @@ protected void updateItem(T item, boolean empty) {
                     }
                     if (toTooltip != null) {
                         String tooltipText = toTooltip.apply(rowItem, item);
+                        Tooltip cellTooltip = null;
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java:130]: why rename `tooltip` to `celltooltip`

**Comment by calixtus** [comment]
Failing guard reviewers check can be ignored

**Comment by calixtus** [comment]
Interesting comment by copilot. should be addressed.

File: jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java (hunk 2 above)
Comment (Francis-Lee-210) [reply jabgui/src/main/java/org/jabref/gui/util/ValueTableCellFactory.java:130]: wants to makes it clear this is the tooltip object to apply to this cell, not the factory field.

**Comment by Francis-Lee-210** [comment]
> Interesting comment by copilot. should be addressed.

Addressed the latest Copilot comment in the newest commit. I changed the CSL delete-cell handling so clicks in the empty delete column of internal styles are no longer swallowed.

I also noticed that the current row-click handling, checks for double-clicks via `event.getClickCount() == 2`, but it does not distinguish mouse buttons(left; right; middle). Is that intentional, or would you consider it bug?
