### PR TITLE
Changed encoding used by IntegrityCheck

### LINKED ISSUE #8022: Valid utf-8 title flagged as non utf-8 by check integrity
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.4--2021-08-21--644e48d Windows 10 10.0 amd64  Java 16.0.2  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Load the attached database (two entries) as biblatex after verifying that is indeed utf-8
2. Run Quality -> check integrity
3. Atmatzidou2016 entry: "title" flagged as "not utf-8 field found" (but the quote after students is utf-8)
4. RosaZipitria2018: entries "booktitle" and "author" flagged as "not utf-8 field found" (but the quote after CSERC and the í in Zipitría are utf-8)

To be honest, I tried only in the development version.

```
@Article{Atmatzidou2016,
  author       = {Soumela Atmatzidou and Stavros Demetriadis},
  date         = {2016-01},
  journaltitle = {Robotics and Autonomous Systems},
  title        = {Advancing students’ computational thinking skills through educational robotics: A study on age and gender relevant differences},
  doi          = {10.1016/j.robot.2015.10.008},
  pages        = {661--670},
  volume       = {75},
  langid       = {english},
  publisher    = {Elsevier {BV}},
}

@InProceedings{RosaZipitria2018,
  author    = {Sylvia {da Rosa Zipitría}},
  booktitle = {Proceedings of the 7th Computer Science Education Research Conference ({CSERC}’18)},
  date      = {2018-10},
  title     = {{Piaget and Computational Thinking}},
  doi       = {10.1145/3289406.3289412},
  location  = {Saint-Petersburg, Russia},
  publisher = {{ACM} Press},
  langid    = {english},
}
```

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Fixes #8022.

Previous method used `System.getProperty("file.encoding")` to get the current character encoding).
Changed to use,

1. `bibDatabaseContext.getMetaData().getEncoding()`
2. `preferencesService.getGeneralPreferences().getDefaultEncoding()`

**Todo**:

1. ~I don't think it can distinguish GBK from UTF-8~

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] ~Tests created for changes (if applicable)~
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] ~Screenshots added in PR description (for UI changes)~
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

Refs issue https://github.com/JabRef/jabref/issues/5850 and PR https://github.com/JabRef/jabref/pull/7639

### CODE REVIEW

File: src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java [hunk 1]
```diff
@@ -40,8 +40,7 @@ public IntegrityCheckAction(JabRefFrame frame, StateManager stateManager, TaskEx
     public void execute() {
         BibDatabaseContext database = stateManager.getActiveDatabase().orElseThrow(() -> new NullPointerException("Database null"));
         IntegrityCheck check = new IntegrityCheck(database,
-                Globals.prefs.getFilePreferences(),
-                Globals.prefs.getCitationKeyPatternPreferences(),
+                Globals.prefs,
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java:43]: You can pass the PreferencesService also in the constructor

Comment (calixtus) [reply src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java:43]: If you already inject prefs in the constructor, could you also try to get rid of JabRefFrame in the constructor? Maybe you have to inject DialogService and StateManager too in the constructor. But im not sure why the IntegrityCheckDialog needs the libraryTab... If its just for the UndoManager... well... that one could be injected too. 😁

Comment (calixtus) [reply src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java:43]: I just checked... that would be a major refactor. Not worth it in this PR.

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java:43]: > You can pass the PreferencesService also in the constructor

I don't think I understand 😛 
Do you mean passing `preferencesService.getGeneralPreferences().getDefaultEncoding()` instead of merging them?
Or are you saying `Globals.prefs.getEntryEditorPreferences().shouldAllowIntegerEditionBibtex()` can be included merged as well?

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java:43]: I am assuming the first one to decrease coupling.

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java:43]: > that would be a major refactor. Not worth it in this PR.

Not sure I understand you. I think we can make it more specific than requiring a JabRef frame. We only need the current `LibraryTab.editEntryAndFocusField` but I am not sure if that changes all that much.

Comment (calixtus) [reply src/main/java/org/jabref/gui/integrity/IntegrityCheckAction.java:43]: Yes, it would be about loose coupling. I just think it's more important to merge a quick fix for a bug early, as well as to focus on one thing only in this pr and create a separate pr for the refactor, if that one would exceed the amount of lines changed too much.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I should be able to test it in a running version of JabRef on Windows latest Monday.

**Review by Siedlerchr — APPROVED** [review]

**Review by calixtus — APPROVED** [review]
