### PR TITLE
Fix linux file opening by using Process Builder

### LINKED ISSUE #8679: "open directory" for attached file does not work
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-04-15--f13ada0 Linux 5.13.0-39-generic amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select an entry
2. Go to the "General" tab
3. Select an attached PDF file
4. Right click to open context menu
5. select "open folder" (or ctrl-shift-O)
6. nothing happens.

More or less the same as  #8093, but in a different context.

### Appendix

_No response_

### LINKED ISSUE #8849: "open folder" does not select the attached file(s) of the entry
JabRef 5.7--2022-05-23--117bb1c
Linux 5.17.9-300.fc36.x86_64 amd64 
Java 18.0.1 
JavaFX *unknown*

the folder opens now.

However, when opening, it does not select the file of the entry. That, however, would be very helpful, given, at least in my case, users might have many pdfs etc linked to entries.

_Originally posted by @ilippert in https://github.com/JabRef/jabref/issues/8093#issuecomment-1136922593_

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #8679 
Fixes #8849 

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Terminal opening works, but it doesn't openin the folder, althought directly executing the following command works:
`gnome-terminal --working-directory="/home/xxx/xxxxxr/00 xxxx xxx xx"


`

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 1]
```diff
@@ -89,41 +90,61 @@ public void openFileWithApplication(String filePath, String application) throws
...
             } else if (desktopSession.contains("mate")) {
-                cmd = "caja --select " + filePath.toString().replace(" ", "\\ ");
+                cmd = "caja --select";
             } else if (desktopSession.contains("cinnamon")) {
-                cmd = "nemo --select " + filePath.toString().replace(" ", "\\ ");
+                cmd = "nemo"; // Although nemo is based on nautilus it does not support --select, it directly highlights the file
             }
         }
-        Runtime.getRuntime().exec(cmd);
+        ProcessBuilder processBuilder = new ProcessBuilder(cmd, filePath.toAbsolutePath().toString());
```
Comment (btut) [inline src/main/java/org/jabref/gui/desktop/os/Linux.java:107]: This does not work for me (arch Linux with Kde plasma).
```suggestion
        Runtime.getRuntime().exec(cmd + " " + filePath.toString().replace(" ", "\\ "));
```
works, but I guess there is a reason you changed to ProcessBuilder.

Comment (btut) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:107]: Also, are whitespaces the only thing that we have to worry about when passing the file parameter?

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 2]
```diff
@@ -89,41 +90,61 @@ public void openFileWithApplication(String filePath, String application) throws
     public void openFolderAndSelectFile(Path filePath) throws IOException {
         String desktopSession = System.getenv("DESKTOP_SESSION");
 
-        String cmd = "xdg-open " + filePath.toAbsolutePath().getParent().toString(); // default command
+        String cmd = "xdg-open"; // default command
 
         if (desktopSession != null) {
             desktopSession = desktopSession.toLowerCase(Locale.ROOT);
             if (desktopSession.contains("gnome")) {
```
Comment (btut) [inline src/main/java/org/jabref/gui/desktop/os/Linux.java:97]: Does not happen often, but often enough: people may run a certain desktop environment, but replaced the default file manager. This would break then.
Also, we cannot check for all possible DEs and may fail to open a file in a nice way even though we know the parameters for the file manager because we don't know the DE. I for example run qtile and have dolphin installed. This check would not cover that scenario.
Instead, could we just try all the file-managers that we know one by one and only stop when one does not return an error?

**Review by btut — COMMENTED** [review]
Is there a particular reason you want to change to ProcessBuilder?

File: src/main/java/org/jabref/gui/desktop/os/Linux.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:97]: Runtime.exec is offically deprecated and they recommend using ProcessBuilder.
The only thing we can do and check if the error stream is not empty and then try the next one...

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ProcessBuilder.html

File: src/main/java/org/jabref/gui/desktop/os/Linux.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:107]: https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Runtime.html#exec(java.lang.String,java.lang.String%5B%5D)

>Deprecated.
This method is error-prone and should not be used, the corresponding method [exec(String[], String[])](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Runtime.html#exec(java.lang.String%5B%5D,java.lang.String%5B%5D)) or [ProcessBuilder](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/ProcessBuilder.html) should be used instead. The command string is broken into tokens using only whitespace characters. For an argument with an embedded space, such as a filename, this can cause problems as the token does not include the full filename.

**Comment by btut** [comment]
Sorry for not giving credit, I somehow screwed up the co-authored-by.

**Comment by ThiloteE** [comment]
@btut Ok, I did a short test after you did the split: Linux Mint Cinnamon 20.3 with Nemo filemanager on first glance works perfectly :-)

File: src/main/java/org/jabref/gui/desktop/os/Linux.java [hunk 3]
```diff
@@ -89,41 +90,62 @@ public void openFileWithApplication(String filePath, String application) throws
...
+        JabRefExecutorService.INSTANCE.execute(streamGobblerError);
     }
 
     @Override
     public void openConsole(String absolutePath) throws IOException {
-        Runtime runtime = Runtime.getRuntime();
-        Process p = runtime.exec("readlink /etc/alternatives/x-terminal-emulator");
-        BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
-
-        String emulatorName = reader.readLine();
```
Comment (btut) [inline src/main/java/org/jabref/gui/desktop/os/Linux.java:115]: I get null here. I think /etc/alternatives is a Debian thing.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:115]: Maybe if (Files.exists(/etc/alternatives...) ?

Comment (btut) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:115]: Yes, but what if it does not exist? What terminal emulator do we choose then?

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:115]: Turns out there is no real solution, just checking multiple places https://superuser.com/a/1461079

Comment (btut) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:115]: So how do we proceed? Leave it as is? Show an alert message that we cannot determine a TE?
Do you think this is a feature that many people use?

**Comment by ilippert** [comment]
as per https://github.com/JabRef/jabref/issues/8849#issuecomment-1143620337: the fix works on Fedora's default Gnome, too.

File: src/main/java/org/jabref/gui/desktop/os/Linux.java (hunk 3 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/desktop/os/Linux.java:115]: Show an alert message. Unable to open terminal. I doubt many use this
