### PR TITLE
Fix online link detection in entry editor

### LINKED ISSUE #8510: unknown trigger for MalformedURLException and possible 'file' field disappearance from some entries
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

jabref_5.6-1_amd64.deb on Ubuntu 21.10 x86_64 with GNOME 40.5

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Version info:
- JabRef 5.6--2022-02-18--4fee3c4
- Linux 5.13.0-28-generic amd64 
- Java 17.0.2 
- JavaFX 17.0.2-ea+3

Details:
I'm trying to track the error, but I may need some help.  If anyone more knowledgeable with the internals of JabRef can point me in a direction to try to trigger this error in a reproducible manner.

Context:
- I already had two complete entries in the DB with their corresponding files (with the auto-generated filenames, and 'file' fields properly set) in the database.
- It may have been that, after upgrading to the latest stable release (from,... I want to say... 5.1?) or beta release (to report an unrelated bug) that the 'file' field from the entries disappeared (maybe when performing a cleanup or integrity check, and I didn't notice).  I don't know if this has anything to do with the MalformedURLException, but it's also an issue.
- The entries didn't have a 'url' field pointing to a PDF, but those URLs were found and somehow suggested when performing the cleanup or integrity checks (in the logs) at least on the beta version.
- If I go to the 'General' tab for the specific entries, I see a hyperlink icon that suggests on its tool-tip that "This file was found automatically. Do you want to link it to this entry".  I linked the files to each entry without a problem.

Some observations:
- Let's call this 'Entry 1':
  - 'url' in source: `https://www.ipcc.ch/report/ar4/wg1/`
  - 'url' in exception: `https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf`
- 'Entry 2':
  - 'url' in source: `https://www.ipcc.ch/report/ar4/wg1/changes-in-atmospheric-constituents-and-radiative-forcing/`
  - 'url' in exception: `https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf`

As you can see, the backslash could explain the 'no protocol' message.

See appendix for BibTex source (without the file fields), and for Log File excerpt

### Appendix

<details>

<summary>BibTex Source</summary>

```
@InBook{Forster2007,
  author           = {Forster, Piers and Ramaswamy, V. and Artaxo, Paulo and Berntsen, Terje and Betts, Richard and Fahey, David W. and Haywood, James and Lean, Judith and Lowe, David C. and Myhre, Gunnar and Nganga, John and Prinn, Ronald and Raga, Graciela and Michael, Schulz and {Van Dorland}, R.},
  booktitle        = {Climate Change 2007 - The Physical Science Basis. Contribution of Working Group I to the Fourth Assessment Report of the Intergovernmental Panel on Climate Change},
  date             = {2007-09-10},
  title            = {Changes in Atmospheric Constituents and in Radiative Forcing},
  bookauthor       = {{Intergovernmental Panel on Climate Change}},
  chapter          = {2},
  editor           = {Solomon, Susan and Qin, Dahe and Manning, Martin and Chen, Zhenlin and Marquis, Melinda and Averyt, Kristen and Tignor, Melinda M. B. and Miller, Henry Le{R}oy},
  location         = {Cambridge, United Kingdom and New York, NY, USA},
  pages            = {129-234},
  publisher        = {Cambridge University Press},
  url              = {https://www.ipcc.ch/report/ar4/wg1/changes-in-atmospheric-constituents-and-radiative-forcing/},
  urldate          = {2020-08-17},
  abstract         = {Radiative forcing (RF) is a concept used for quantitative comparisons of the strength of different human and natural agents in causing climate change. Climate model studies since the Working Group I Third Assessment Report (TAR; IPCC, 2001) give medium confidence that the equilibrium global mean temperature response to a given RF is approximately the same (to within 25\%) for most drivers of climate change.
For the first time, the combined RF for all anthropogenic agents is derived. Estimates are also made for the first time of the separate RF components associated with the emissions of each agent.
The combined anthropogenic RF is estimated to be +1.6 [–1.0, +0.8] $W/m^{–2}$ , indicating that, since 1750, it is extremely likely that humans have exerted a substantial warming influence on climate. This RF estimate is likely to be at least five times greater than that due to solar irradiance changes. For the period 1950 to 2005, it is exceptionally unlikely that the combined natural RF (solar irradiance plus volcanic aerosol) has had a warming influence comparable to that of the combined anthropogenic RF.
Increasing concentrations of the long-lived greenhouse gases (carbon dioxide ($CO_2$), methane ($CH_4$), nitrous oxide ($N_{2}O$), halocarbons and sulphur hexafluoride ($SF_6$); hereinafter LLGHGs) have led to a combined RF of +2.63 [$\pm 0.26$] $W/m^{–2}$. Their RF has a high level of scientific understanding. The 9\% increase in this RF since the TAR is the result of concentration changes since 1998.},
  file             = {:Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF},
  keywords         = {climate change, global warming, climate, science},
  modificationdate = {2020-08-17T00:00:00},
  owner            = {rolandog},
  pagetotal        = {996},
  year             = {2007},
}

@Book{IPCC2007,
  author           = {{Intergovernmental Panel on Climate Change}},
  date             = {2007-09-10},
  title            = {Climate Change 2007 - The Physical Science Basis},
  editor           = {Solomon, Susan and Qin, Dahe and Manning, Martin and Chen, Zhenlin and Marquis, Melinda and Averyt, Kristen and Tignor, Melinda M. B. and Miller, Henry Le{R}oy},
  location         = {Cambridge, United Kingdom and New York, NY, USA},
  pagetotal        = {996},
  publisher        = {Cambridge University Press},
  subtitle         = {Contribution of Working Group I to the Fourth Assessment Report of the Intergovernmental Panel on Climate Change},
  url              = {https://www.ipcc.ch/report/ar4/wg1/},
  urldate          = {2020-08-17},
  abstract         = {This Working Group I contribution to the IPCC's Fourth Assessment Report (AR4) provides a comprehensive assessment of the physical science of climate change and continues to broaden the view of that science, following on from previous Working Group I assessments. The results presented here are based on the extensive scientific literature that has become available since completion of the IPCC's Third Assessment Report, together with expanded data sets, new analyses, and more sophisticated climate modelling capabilities.},
  file             = {:IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF},
  keywords         = {climate change, global warming, climate, science},
  modificationdate = {2020-08-17T00:00:00},
  owner            = {rolandog},
  year             = {2007},
}
```

</details>

<details>

<summary>Log File</summary>

```
invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.addToIndex(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.LibraryTab$IndexUpdateListener.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.LibraryTab.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.JabRefFrame.addTab(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.JabRefFrame.addParserResult(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.JabRefGUI.openDatabases(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.addToIndex(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.LibraryTab$IndexUpdateListener.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.LibraryTab.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.JabRefFrame.addTab(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.JabRefFrame.addParserResult(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.JabRefGUI.openDatabases(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$3.computeValue(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.TableCell.updateItem(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.TableCell.indexChanged(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.TableRowSkinBase.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.IntegerPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.IntegerPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.scrollPixels(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow$1.handle(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow$1.handle(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.Scene.processGestureEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.Scene$ScenePeerListener.scrollEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollEvent$5(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollEvent$6(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleScrollEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.View.notifyScroll(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$3.computeValue(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.TableCell.updateItem(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.TableCell.indexChanged(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.TableRowSkinBase.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.IntegerPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.beans.property.IntegerPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow.scrollPixels(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow$1.handle(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.control.skin.VirtualFlow$1.handle(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.Scene.processGestureEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.scene.Scene$ScenePeerListener.scrollEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollEvent$5(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollEvent$6(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleScrollEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.View.notifyScroll(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.47/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FileChecker.checkValue(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FieldChecker.check(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.IntegrityCheck.checkEntry(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FileChecker.checkValue(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FieldChecker.check(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.IntegrityCheck.checkEntry(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FileChecker.checkValue(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FieldChecker.check(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.IntegrityCheck.checkEntry(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FileChecker.checkValue(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.FieldChecker.check(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.integrity.IntegrityCheck.checkEntry(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Doing a cleanup for 265 entries...
invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.RelativePathsCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.RenamePdfCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.UpgradePdfPsToFileCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.MoveFilesCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.FileLinksCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :Forster2007 - Changes in Atmospheric Constituents and in Radiative Forcing.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-chapter2-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.LibraryTab$IndexUpdateListener.listen(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.database.BibDatabase.relayEntryChangeEvent(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.FileLinksCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Index path for /home/rolandog/Documents/references/rg-references.bib is /home/rolandog/.local/share/JabRef/0.5a
Index path for /home/rolandog/Documents/references/rg-references.bib is /home/rolandog/.local/share/JabRef/0.5a
invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.RelativePathsCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.RenamePdfCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.UpgradePdfPsToFileCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.MoveFilesCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.FileLinksCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :IPCC2007 - Climate Change 2007 the Physical Science Basis.pdf:PDF;:https\://www.ipcc.ch/site/assets/uploads/2018/05/ar4_wg1_full_report-1.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.LibraryTab$IndexUpdateListener.listen(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.database.BibDatabase.relayEntryChangeEvent(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.6.47/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.FileLinksCleanup.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.logic.cleanup.CleanupWorker.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.doCleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.6.47/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.47/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Index path for /home/rolandog/Documents/references/rg-references.bib is /home/rolandog/.local/share/JabRef/0.5a
Index path for /home/rolandog/Documents/references/rg-references.bib is /home/rolandog/.local/share/JabRef/0.5a
4 entries needed a clean up
```

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #8510 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/importer/util/FileFieldParser.java [hunk 1]
```diff
@@ -22,7 +22,7 @@
             return files;
         }
 
-        if (LinkedFile.isOnlineLink(value.trim())) {
+        if (!value.trim().startsWith(":") && LinkedFile.isOnlineLink(value.trim())) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/util/FileFieldParser.java:25]: I think, `isOnlineLink` should be fixed. The file field can contain a description. In case the description is `This is an awesome/somesome file`, the method will still break.

Maybe, we should work on a more intuitive file field - see https://github.com/JabRef/jabref/issues/98 for a discussion.

**Review by koppor — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/logic/importer/util/FileFieldParser.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/util/FileFieldParser.java:25]: This method is only handling the edge case for non valid file links See #7948  for the PR and #7882 for the original issue

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/util/FileFieldParser.java:25]: See also the tests

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/util/FileFieldParser.java:25]: I switched to a regex with the condition to only match at the beginning. The contains www was a culprit

Comment (calixtus) [reply src/main/java/org/jabref/logic/importer/util/FileFieldParser.java:25]: I believe this was originally chose for performance reasons. Can we somehow benchmark this?

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/util/FileFieldParser.java:25]: The regex is compiled, I doubt it will be a huge problem.

**Comment by Siedlerchr** [comment]
i would like to merge this, as this is otherwise fails for a lot of users

File: src/main/java/org/jabref/logic/importer/util/FileFieldParser.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/util/FileFieldParser.java:25]: Can we remove the `!value.trim().startsWith(":")?  part?

It should be working without that check.

**Comment by Siedlerchr** [comment]
Fix olly's checkstyle...
