### PR TITLE
9817 adding HTTP Status Exception check to Grobid Citation Fetcher

### LINKED ISSUE #9817: Improve error handling on GROBID server connection issues - 503 Service unaviable
### JabRef version

5.9 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

_No response_

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Fresh install of 5.9 version
2. Click "New entry from plain text"
3. Paste and push "Add to current library" example from docs: 
```
O. Kopp, A. Armbruster, und O. Zimmermann, "Markdown Architectural Decision Records: Format and Tool Support", in 10th ZEUS Workshop, 2018.
```
4. Receive 0 entries were parsed

Nothing in the logs when run with **--debug** flag.
I've opened Wireshark and traced the connection to **http://grobid.jabref.org:8070/** and it's throwing 503 error, but that error is not correctly handled by JabRef.

The expected behaviour would be to show the message on the screen that the service is not available or it's unable to parse the file because XYZ instead of just 0 entries were parsed which would suggest something wrong with the format you've sent.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by mtheiley**
Fixes #9817

Hi all, I am part of the university group that was assigned this issue.

I tried to re-create this issue with failing to connect to http://grobid.jabref.org:8070/, however currently it is up and running fine. So instead I tried to re-create the issue by connecting to https://httpstat.us/503 which always gives a 503 error code when attempting to connect.

It looks like JSoup throws an HttpStatusException when the status code is not 200 OK https://jsoup.org/apidocs/org/jsoup/HttpStatusException.html

I have tried adding an additional catch statement in the try catch within GrobitCitationFetcher.java and this seems to be working. When we don't get 200 OK it will display the error after 0 entries are passed. This should hopefully catch all status related errors now including the 503 status. I have attached a copy of the error code being displayed in the GUI.

I originally posted this solution on the issue [9817](https://github.com/JabRef/jabref/issues/9817) I have made some changes based on recommendations made there. I was recommended to change the RuntimeExceptions to FetcherExceptions for my changes, however I was just basing my changes on the existing SocketTimeoutException below. Should both of these be changed to FetcherExceptions?

Other members of my team are currently looking into wire mock tool as suggested.

Please let us know what you think we are eager to hear your feedback.

Connection Failure

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Yes please change all to Fetcher Exceptions. If all is correct they will be caught by the caller and displayed in a friendly way to the user

**Comment by mtheiley** [comment]
> Yes please change all to Fetcher Exceptions. If all is correct they will be caught by the caller and displayed in a friendly way to the user

Hi, I have tried to change these to Fetcher Exceptions, but I think I understand why these were originally left as runtime exceptions. The function parseUsingGrobid is passed into a Arrays.stream.map(this::parseUsingGrobid). When I change the runtime exceptions to Fetcher Exceptions I am getting an error on the line .map(this::parseUsingGrobid) saying that FetcherException is unhandled. I believe this is because we are giving .map() a reference to the function that it will call internally, since map can't catch / handle a FetcherException this is what is causing the problem.

I found a post on stack overflow discussing a similar problem. I believe using runtime exceptions is a workaround for this problem as it leaves the exception unchecked.  https://stackoverflow.com/questions/19757300/java-8-lambda-streams-filter-by-method-with-exception 

The Array.stream.map(this::parseUsingGrobid) is surrounded by a try catch that catches runtime exceptions.

**Comment by Siedlerchr** [comment]
I think for the moment we can keep the runtime exception.

**Comment by mtheiley** [comment]
@koppor I have got faux-pas working and now this::parseUsingGrobid is wrapped inside a throwingFunction() which seems to fix the issue.

**Review by Siedlerchr — DISMISSED** [review]

File: src/main/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcher.java [hunk 1]
```diff
@@ -67,7 +74,7 @@ public List<BibEntry> performSearch(String searchQuery) throws FetcherException
             collect = Arrays.stream(searchQuery.split("\\r\\r+|\\n\\n+|\\r\\n(\\r\\n)+"))
                             .map(String::trim)
                             .filter(str -> !str.isBlank())
-                            .map(this::parseUsingGrobid)
+                            .map(FauxPas.throwingFunction(this::parseUsingGrobid))
                             .flatMap(Optional::stream)
                             .collect(Collectors.toList());
         } catch (RuntimeException e) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcher.java:80]: Is this still necessary? I think, this block can be removed!

Comment (mtheiley) [reply src/main/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcher.java]: @koppor I have removed the try/catch block checking for runtime exceptions since we are just using FetcherExceptions now

**Review by Siedlerchr — APPROVED** [review]
