### PR TITLE
Fixes Jabref#7660 Unable to download some arXiv links if the "eprint" field is missing

### LINKED ISSUE #7660: Unable to download some arXiv links if the "eprint" field is missing
JabRef version 5.3 developmental portable JAR 

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

I am unable to automatically download some arXiv links if the "eprint" field is missing. For example, this BibTeX reference works:

```
@Article{booth_bayes-trex_2020,
  author        = {Serena Booth and Yilun Zhou and Ankit Shah and Julie Shah},
  journal       = {arXiv:2002.10248v4 [cs]},
  title         = {Bayes-TrEx: a Bayesian Sampling Approach to Model Transparency by Example},
  year          = {2020},
  month         = dec,
  archiveprefix = {arXiv},
  eprint        = {2002.10248},
  url           = {http://arxiv.org/abs/2002.10248v4},
}
```

but this one doesn't:

```
@Article{booth_bayes-trex_2020,
  author        = {Serena Booth and Yilun Zhou and Ankit Shah and Julie Shah},
  journal       = {arXiv:2002.10248v4 [cs]},
  title         = {Bayes-TrEx: a Bayesian Sampling Approach to Model Transparency by Example},
  year          = {2020},
  month         = dec,
  archiveprefix = {arXiv},
  url           = {http://arxiv.org/abs/2002.10248v4},
}
```

with the only thing different is the eprint field.

Interestingly this doesn't always happen; most of the time JabRef can fetch the arXiv PDF correctly without the eprint field, but for some reason JabRef fails to get other arXiv PDFs like the one above. I suspect it's a formatting issue similar to Issue #7633. It's not always consistent, but it feels like paper titles with colons appear to trigger this behavior more than others.

Perhaps it can be set when the url field is provided that JabRef could use that as a fallback to download the PDF..

### PR DESCRIPTION
**Pull request by JavuesZhang**
Fixes #7660
## Brief summary
1. Run EprintCleanup on a copy of the entry the ArXiv fetcher is fetching before getting arXiv id from the eprint field;
2. Add two test method. One finds full text with title containing colon and journal, while another finds full text with title containing colon and url.

## Problem
When finding full text, this BibTeX reference works:
```
@Article{booth_bayes-trex_2020,
  author        = {Serena Booth and Yilun Zhou and Ankit Shah and Julie Shah},
  journal       = {arXiv:2002.10248v4 [cs]},
  title         = {Bayes-TrEx: a Bayesian Sampling Approach to Model Transparency by Example},
  year          = {2020},
  month         = dec,
  archiveprefix = {arXiv},
  eprint        = {2002.10248},
  url           = {http://arxiv.org/abs/2002.10248v4},
}
```

But when `eprint` field is missing, no full text will be found:
```
@Article{booth_bayes-trex_2020,
  author        = {Serena Booth and Yilun Zhou and Ankit Shah and Julie Shah},
  journal       = {arXiv:2002.10248v4 [cs]},
  title         = {Bayes-TrEx: a Bayesian Sampling Approach to Model Transparency by Example},
  year          = {2020},
  month         = dec,
  archiveprefix = {arXiv},
  url           = {http://arxiv.org/abs/2002.10248v4},
}
```

## Solution
Since the title contains colon and arXiv uses colon to represent key and value, the title may be recognized mistakenly. So use other fields to get the eprint field to avoid this problem. Thanks to the advice from @tobiasdiez .

## Screenshots
After fix:

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by tobiasdiez — APPROVED** [review]
Wow that was quick 🚀 . Code looks good to me! Thanks for your contribution.

File: src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java [hunk 1]
```diff
@@ -116,6 +118,9 @@ public TrustLevel getTrustLevel() {
     }
 
     private List<ArXivEntry> searchForEntries(BibEntry entry) throws FetcherException {
+        entry = (BibEntry) entry.clone();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java:121]: Why do you clone the entry?

**Comment by JavuesZhang** [comment]
> Wow that was quick 🚀 . Code looks good to me! Thanks for your contribution.

It is your advice that makes me efficient!  At the beginning I try to ignore colons in title to solve this problem but it seems not so good.

File: src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java (hunk 1 above)
Comment (JavuesZhang) [reply src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java:121]: If we do clean up on the original entry, its fields will be changed but I think we needn't change fields here because it is just a search.

**Review by Siedlerchr — APPROVED** [review]
Thanks for the quick fix!
