### PR TITLE
Remove download when html file

### LINKED ISSUE #10149: "Download linked file" option creates an html file instead of downloading the pdf on Windows 10.
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

"Download Linked File" option on JabRef 5.4 works fine within the same corporate firewalled network environment and on the same Windows 10 computer.

1. Download and unzip JabRef 5.10 portable within a corporate firewall environment on Windows 10 computer, post install details as follows.
JabRef 5.10--2023-08-07--3d197a9
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19

(NOTE: Same issue is also observed in admin install of JabRef version as follows.
JabRef 5.10--2023-07-18--34ac6d1
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19)

2. Import SSL certificate within Preferences->Network. Use the custom proxy option within Preferences->Network.

3. Verify internet connectivity using the button in Preferences->Network. Confirmed that it works.

4. Go to Jabref WebSearch, choose ArXiv for searching. Search for "https://arxiv.org/abs/2307.14043".
5. Select "Download linked file" option in resulting search result and import the entry into bib file.

RESULT: The entry is imported but an empty html file is created instead of downloading actual pdf from ArXiv website.

### Appendix

<details>
<summary>Screenshot of erroneous file download</summary>

image

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #10149

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java [hunk 1]
```diff
@@ -164,19 +166,22 @@ private void onSuccess(Path targetDirectory, Path destination) {
...
         }
-
         // Notify in bar when the file type is HTML.
         if (isHtml) {
-            dialogService.notify(Localization.lang("Downloaded website as an HTML file."));
-            LOGGER.debug("Downloaded website {} as an HTML file at {}", linkedFile.getLink(), destination);
+            dialogService.notify(Localization.lang("Download was a HTML file. Not adding it."));
+            List<LinkedFile> newFiles = new ArrayList<>(entry.getFiles());
+            newFiles.remove(linkedFile);
+            entry.setFiles(newFiles);
```
Comment (koppor) [inline src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java:179]: I am not sure about this one if there are multiple files attached and only one leads to HTML. Need to see the full source.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/linkedfile/DownloadLinkedFileAction.java:179]: I'm only removing the current linked File from he current download.
I am getting all  existing files from the entry and just remove the current one
To trigger change detection I have to reassign the list

**Review by koppor — APPROVED** [review]
