### PR TITLE
Fix exception when merging entries

### LINKED ISSUE #5169: Exception when merging entries
Hello, I am on Fedora 30, running Jabref Snap Edge

1. Select two items
2. Open Merge entries dialogue.
3. Click Merge entries.
4. Watch Exception thrown.

<details>
  <summary>Log File</summary>
  
  ```
1:06:21.749 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: Index: 5, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_222]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_222]
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89) ~[jfxrt.jar:?]
	at javafx.collections.FXCollections$SynchronizedList.get(FXCollections.java:1085) ~[jfxrt.jar:?]
	at javafx.collections.FXCollections$UnmodifiableObservableListImpl.get(FXCollections.java:936) ~[jfxrt.jar:?]
	at org.jabref.gui.util.MappedList.sourceChanged(MappedList.java:67) ~[JabRef-5.0-dev.jar:?]
	at javafx.collections.transformation.TransformationList.lambda$getListener$1(TransformationList.java:106) ~[jfxrt.jar:?]
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73) ~[jfxrt.jar:?]
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233) ~[jfxrt.jar:?]
	at org.jabref.gui.util.UiThreadList.lambda$sourceChanged$934(UiThreadList.java:15) ~[JabRef-5.0-dev.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
  ```
</details>

### PR DESCRIPTION
**Pull request by tobiasdiez**
The problem was that `sourceChanged` was invoked asynchronous and thus the information in the change event could be obsolete if another thread changed the underlying list in the meantime. Solution: run `sourceChanged` on the JavaFX thread but synchronously.
Fixes #5169.

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/util/UiThreadList.java [hunk 1]
```diff
@@ -1,18 +1,38 @@
...
 class UiThreadList<T> extends TransformationList<T, T> {
+    private static final Logger LOGGER = LoggerFactory.getLogger(UiThreadList.class);
     public UiThreadList(ObservableList<? extends T> source) {
         super(source);
     }
 
     @Override
     protected void sourceChanged(ListChangeListener.Change<? extends T> change) {
-        Platform.runLater(() -> fireChange(change));
+        if (Platform.isFxApplicationThread()) {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/util/UiThreadList.java]: Oh, wow. This reads like an ugly hack. Good, that this works...

Would be nice if some comments were added:

- Why can it happen that this method is called inside and outside the FxApplication thread?
- Why can the `fireChange` method be run directly in the case of inside the FxApplication?
- Why is `CountDownLatch` used and not something more different (it is used as Boolean flag)?

**Comment by koppor** [comment]
I merged to keep things moving. However, it would be nice if my code questions would lead no another PR adding comments on the code.
