### PR TITLE
Fix issue where "Close library" menu item is not disabled correctly

### LINKED ISSUE #10948: Uncaught exception when closing a library that does not exists
### JabRef version

5.12 (latest release)

### Operating system

macOS

### Details on version and operating system

Sonoma 14.2.1

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open JabRef
2. Do not create or open a library
3. Press cmd + w (ctrl + w) or File -> Close library

Screenshot 2024-02-29 at 11 45 44

### Appendix

Screenshot 2024-02-29 at 11 46 00

<details>

<summary>Log File</summary>

```
ERROR: Uncaught exception occurred in Thread[#29,JavaFX Application Thread,5,system]: java.lang.NullPointerException: Cannot invoke "org.jabref.gui.LibraryTab.requestClose()" because "libraryTab" is null
```

</details>

### PR DESCRIPTION
**Pull request by martinctl**
Fixed a bug that allowed you to click on the `File -> Close library` menu item even if no library was open. When the button was pressed in this situation, the following error was uncaught.

image

This PR prevents the `closeCurrentTab` method from calling `closeTab` with `null` as a parameter, and disables the menu item (and its associated shortcut) when there is no library tab open.

https://github.com/JabRef/jabref/assets/91327170/75c48182-c5f3-4e37-b3b2-788abb0f9ee2

Closes #10948

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 1]
```diff
@@ -752,7 +752,11 @@ private boolean closeTabs() {
     }
 
     public boolean closeCurrentTab() {
-        return closeTab(getCurrentLibraryTab());
+        LibraryTab currentTab = getCurrentLibraryTab();
+        if (currentTab == null) {
+            return false;
+        }
+        return closeTab(currentTab);
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/JabRefFrame.java:759]: I would suggest moving this check on null to CloseDatabaseAction#execute, then this will be consistent with other actions and we keep the view (yes i know, right now according to the mvvm pattern, jabrefframe is still way off a pure view, but it gets there eventually).

**Review by calixtus — CHANGES_REQUESTED** [review]
Hi, thanks for your interest in JabRef and Open Source programming.
The changes you made look really good and i think codewise they are already pretty good. I just have a suggestion of placement of the null check.

File: src/main/java/org/jabref/gui/JabRefFrame.java (hunk 1 above)
Comment (martinctl) [reply src/main/java/org/jabref/gui/JabRefFrame.java:759]: That makes sense. But in this case, do you suggest to call the `getCurrentLibraryTab` on `tabContainer` before calling `closeCurrentTab` ? That would make two calls to `getCurrentLibraryTab`.
Or maybe I should implement a method `getTabCount` to know if there is at least one tab.

Comment (calixtus) [reply src/main/java/org/jabref/gui/JabRefFrame.java:759]: No, just return from the execute method (fail fast) with a log message if the the library tab and the currently opened tab is null.

File: CHANGELOG.md [hunk 2]
```diff
@@ -52,8 +52,10 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
 - We fixed an issue where the CrossRef field did not work if autocompletion was disabled [#8145](https://github.com/JabRef/jabref/issues/8145)
 - We fixed an issue where exporting`@electronic` and `@online` entry types to the Office XMl would duplicate the field `title`  [#10807](https://github.com/JabRef/jabref/issues/10807)
 - We fixed an issue where the `CommentsTab` was not properly formatted when the `defaultOwner` contained capital or special letters. [#10870](https://github.com/JabRef/jabref/issues/10870)
+- We fixed an issue where the `File -> Close library` menu item was not disabled when no library was open. [#10948](https://github.com/JabRef/jabref/issues/10948)
 - We fixed an issue where the Document Viewer would show the PDF in only half the window when maximized. [#10934](https://github.com/JabRef/jabref/issues/10934)
 
+
```
Comment (koppor) [inline CHANGELOG.md:58]: For the next PR: Please no additional empty lines in CHANGELOG.md. This will lead to merge conflicts.

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 3]
```diff
@@ -1059,22 +1059,27 @@ static protected class CloseDatabaseAction extends SimpleCommand {
...
-            this(tabContainer, null);
+        public CloseDatabaseAction(LibraryTabContainer tabContainer, StateManager stateManager) {
+            this(tabContainer, null, stateManager);
         }
 
         @Override
         public void execute() {
             Platform.runLater(() -> {
                 if (libraryTab == null) {
+                    if (tabContainer.getCurrentLibraryTab() == null) {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/JabRefFrame.java:1079]: I think, this code will never be reached, but good to be defensive.

**Review by koppor — APPROVED** [review]
Tried out, looks good:

image

**Review by calixtus — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
