### PR TITLE
Fix dark mode in {} of Citation Relations tab of the entry editor

### LINKED ISSUE #13599: Fix darkmode in {} of Citation Relations tab of the entry editor
### JabRef version

6.0-alpha2

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add an entry to your library.
2. Open the entry editor by double clicking on the entry.
3. Switch to the Citation Relations tab.
4. The `{}` symbol shows the bibtex source. The dialog looks horrible in dark mode and needs a fix:
Image

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by ankamde**
Closes #13599

Fix dark mode in {} of Citation Relations tab of the entry editor.

### Steps to test

1. Switch to dark mode.
2. Open sample entry and go to Citation Relations tab.
3. Click on {} BibTeX source button.
image

4. Dialog shows content of the BibTeX source in the dark mode.
image

5. Switch back to the Light theme.
image

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [/] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java [hunk 1]
```diff
@@ -342,24 +341,24 @@ private String getSourceString(BibEntry entry, BibDatabaseMode type, FieldPrefer
     }
 
     private void showEntrySourceDialog(BibEntry entry) {
-        CodeArea ca = new CodeArea();
+        TextArea area = new TextArea();
```
Comment (Siedlerchr) [inline jabgui/src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java]: This is the wrong approach, we use CodeArea for BibTex also in the EntryEditor and this should be used here. Instead you need to fix/add a css defintion. 
See (SourceTab,)

Comment (ankamde) [reply jabgui/src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java]: Done. Please have a look. I hope this css definition is not to broad.

**Review by Siedlerchr — APPROVED** [review]
