### PR TITLE
Fix NPE and not on FX Thread in PreviewPrefs Tabs

### LINKED ISSUE #4570: #4365 is back: preview copy fails
JabRef 5.0-dev--snapshot--2019-01-05--master--d281ece4b
Linux 4.15.0-43-generic amd64
Java 1.8.0_191

The

null
null
null
null
null
null
null
null
null
null
null
null
null
null

behaviour reported on 9 December is back. :-(

As before, selecting the preview and copying it with ctrl+C does put an un-tagged copy into the buffer correctly. But ctrl+shft+C isn't working properly, either from the mouse right-click, the dropdown edit menu or by key presses.

### LINKED ISSUE #4621: Remove Preview Style from the right list results in Divide by zero exception
Current master

Move all styles from the right to the left, including "Preview". 
The following error comes up.

A solution would be to disable the cell or to prevent it from moving. 
```
14:48:45.633 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main] - java.lang.ArithmeticException: / by zero
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:90)
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:82)
	at org.jabref.gui.preferences.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:264)
	at org.jabref.gui.preferences.PreviewPrefsTab.lambda$3(PreviewPrefsTab.java:97) 
```

### LINKED ISSUE #4622: Reset preferences throws not on FX Thread exception multiple times
current master (2019-01-28)

To FIX: Replace the Swing Worker with a Background Task.
```

	at org.jabref.gui.preferences.PreviewPrefsTab$1.done(PreviewPrefsTab.java:239)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
```

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204)
	at com.sun.javafx.scene.control.skin.ListCellSkin.handleControlPropertyChanged(ListCellSkin.java:49)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.scene.control.Labeled.setText(Labeled.java:145)
	at com.sun.javafx.scene.control.skin.ListViewSkin$2.updateItem(ListViewSkin.java:319)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
	at javafx.scene.control.ListCell.lambda$new$160(ListCell.java:167)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.jabref.gui.preferences.PreviewPrefsTab$1.done(PreviewPrefsTab.java:239)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### PR DESCRIPTION
**Pull request by Siedlerchr**
Remove obsolete swing stuff
Create proper javafx binding

Fixes #4621
Fixes #4622 
Fixes #4570

I fixed and tuned the copypreview stuff.
Copy Preview copies the HTML formatted stuff for usage in email:

grafik

grafik

Purified text for non html:
```
Incollection (Akerkar:)
 Akerkar, R.

 Processing Big Data for Emergency Management 


 Smart Technologies for Emergency Response and Disaster Management, 


 IGI Global, 
, 144-166 



```

When all styles get removed from the right side, the default "Preview" style is added back again to prevent divide by zero exception

Fix another issue where the Preview style is not set correctly

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java [hunk 1]
```diff
@@ -61,25 +57,24 @@
...
-            if (chosen.getSelectionModel().getSelectedIndices().isEmpty()) {
-                btnLeft.setDisable(true);
-                btnDown.setDisable(true);
-                btnUp.setDisable(true);
-            }
-        });
 
-        available.getSelectionModel().selectedItemProperty().addListener(
-                e -> btnRight.setDisable(available.getSelectionModel().getSelectedIndices().isEmpty()));
+        btnLeft.disableProperty().bind(Bindings.isEmpty(chosen.getSelectionModel().getSelectedItems()));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java]: I think you can define a binding `nothingSelected = Bindings.isEmpty(chosen.getSelectionModel().getSelectedItems())` and then reuse it.

File: src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java [hunk 2]
```diff
@@ -61,25 +57,24 @@
...
     private final DialogService dialogService;
     private final ExternalFileTypes externalFileTypes;
+    private final TaskExecutor taskExecutor;
+
+    private Task<List<CitationStyle>> citationDiscovery;
 
     public PreviewPrefsTab(DialogService dialogService, ExternalFileTypes externalFileTypes) {
         this.dialogService = dialogService;
         this.externalFileTypes = externalFileTypes;
+        this.taskExecutor = Globals.TASK_EXECUTOR;
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java]: Can you please push-out this Global dependency as far as possible.

File: src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java [hunk 3]
```diff
@@ -122,41 +117,34 @@ private void setupLogic() {
...
-                    }
-                    else {
-                        int indexStyle = chosen.getSelectionModel().getSelectedIndex();
-                        PreviewPreferences preferences = Globals.prefs.getPreviewPreferences();
-                        preferences = new PreviewPreferences(preferences.getPreviewCycle(),indexStyle,preferences.getPreviewPanelDividerPosition(),preferences.isPreviewPanelEnabled(), preferences.getPreviewStyle(),preferences.getPreviewStyleDefault());
-
-                        testPane = new PreviewPanel(JabRefGUI.getMainFrame().getCurrentBasePanel(), new BibDatabaseContext(), Globals.getKeyPrefs(), preferences, dialogService, externalFileTypes);
-                        testPane.setEntry(TestEntry.getTestEntry());
-                        testPane.updateLayout(preferences);
-                    }
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java]: remove empty line?

File: src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java [hunk 4]
```diff
@@ -180,8 +168,10 @@ private void setupGui() {
         gridPane.add(btnDefault, 3, 6);
         layout.setPrefSize(600, 300);
         gridPane.add(scrollPane, 1, 9);
+
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java]: remove empty line?

File: src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java [hunk 5]
```diff
@@ -212,46 +202,38 @@ public void setValues() {
...
 
-        btnLeft.setDisable(!chosen.getSelectionModel().getSelectedItems().isEmpty());
-        btnRight.setDisable(available.getSelectionModel().getSelectedIndices().isEmpty());
-        btnUp.setDisable(!chosen.getSelectionModel().getSelectedIndices().isEmpty());
-        btnDown.setDisable(!chosen.getSelectionModel().getSelectedIndices().isEmpty());
-
-        if (discoverCitationStyleWorker != null) {
-            discoverCitationStyleWorker.cancel(true);
+        if (citationDiscovery != null) {
+            citationDiscovery.cancel();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java]: The cancel is useless here. It just sets the task `isCanceled` to true but doesn't really abort the task. You need to implement it manually in the `call` method (e.g. in a for loop check if the task is canceled before you proceed with the next iteration). Since this is not really easy to implement here (because the cost-intensive call is living in `CitationStyle`), I would vote to use a BackgroundTask here,  make `citationDiscovery` a variable instead of a class-global field (or completely get rid of it) and remove the `cancel` part.

File: src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java [hunk 6]
```diff
@@ -212,46 +202,38 @@ public void setValues() {
...
-        discoverCitationStyleWorker.execute();
+
+        citationDiscovery.setOnSucceeded(value -> {
+            citationDiscovery.getValue().stream()
+                             .filter(style -> !previewPreferences.getPreviewCycle().contains(style.getFilePath()))
+                             .sorted(Comparator.comparing(CitationStyle::getTitle))
+                             .forEach(availableModel::add);
+        });
+
+        citationDiscovery.setOnFailed(value -> LOGGER.error("something went wrong while adding the discovered CitationStyles to the list ", citationDiscovery.getException()));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/PreviewPrefsTab.java]: Please also show an error dialog.

**Comment by Siedlerchr** [comment]
Fixed all remainig issues
