### PR TITLE
Fix group filter to use OR semantics for space separated terms

### LINKED ISSUE #12721: Group search should be OR - not AND
Image

Serach ANY match.

Task: 

- Investigate if `Search.g4` can be used here, too
- Implement using that grammar here

Refs https://github.com/JabRef/jabref/issues/10209 somehow

### PR DESCRIPTION
**Pull request by NishantDG-SST**
### Related issues and pull requests

Closes #12721

### PR Description

The group filter in the side pane previously required ALL typed words to appear in a group name, so typing machine learning would hide "Deep Learning" even though it contains "learning". This fix changes the behavior to OR-any matching word is enough. It reuses the existing Search.g4 ANTLR grammar for parsing So explicit AND, OR, NOT, and parentheses also work in the filter box.

### Steps to test

1. Open any library in JabRef
2. Open the Groups pane (View → Groups)
3. Create these subgroups under "All Entries": "Machine Learning", "Deep Learning", "Neural Networks", "Computer Vision", "Reinforcement Learning"
Screenshot 2026-03-17 at 12 25 41 AM

4. Type "deep learning" in the Filter groups box → all three groups containing "Learning" should appear

Before
Screenshot 2026-03-17 at 12 24 26 AM

After 
Screenshot 2026-03-17 at 12 47 08 AM

5. Type "machine vision" → "Machine Learning" and "Computer Vision" should appear

Before

Screenshot 2026-03-17 at 12 25 35 AM

After

Screenshot 2026-03-17 at 12 47 34 AM

6. Type "NOT learning" → subgroups with "Learning" should not appear
Screenshot 2026-03-17 at 2 52 24 AM

7. Type "machine AND learning" → only "Machine Learning" should appear
Screenshot 2026-03-17 at 12 52 25 AM

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

Screenshot 2026-03-17 at 2 47 51 AM

### AI Usage

> I used copilot suggesstion code (https://github.com/JabRef/jabref/pull/15350#discussion_r2943111997) in GroupNameFilterVisitor.java,  I reviewed the suggested fix, tested it locally, and verified it solves the issue without side effects.
> I used ai to write the steps to reciprocate the steps to test more clearly in pr description
> I used Copilot for suggestions related to spaceImpliesOr,parenthesesWithNotWork,complexExpressionWithNotLearning test cases. I reviewed the suggested cases, and no code was generated by AI.

### CODE REVIEW

File: jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+        assertFalse(matches("Computer Vision", "(deep OR neural) NOT vision"));
+        assertFalse(matches("Machine Learning", "(deep OR neural) NOT vision"));
+    }
+
+    @Test
+    void complexExpressionWithNotLearning() {
+        assertTrue(matches("Computer Vision", "(machine OR computer) NOT learning"));
+        assertFalse(matches("Machine Learning", "(machine OR computer) NOT learning"));
+        assertFalse(matches("Neural Networks", "(machine OR computer) NOT learning"));
+    }
```
Comment (koppor) [inline jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java]: Parameterized tests

File: jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+import org.jabref.search.SearchBaseVisitor;
+import org.jabref.search.SearchParser;
+
+/// Evaluates a Search.g4 parse tree against a group display name string.
+///
+/// Key behavioral difference from {@link SearchQueryVisitor}:
+/// {@code visitImplicitAndExpression} uses OR semantics (anyMatch) instead of AND,
+/// so space-separated bare terms like "machine learning" match any group containing
+/// either word. Explicit AND/OR/NOT and parentheses work as expected.
+
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java]: why empty line?

File: jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+public class GroupNameFilterVisitor extends SearchBaseVisitor<Boolean> {
+
+    private final String groupName;
+
+    public GroupNameFilterVisitor(String groupName) {
+        this.groupName = groupName.toLowerCase(Locale.ROOT);
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java:23]: Why? State reason?

Maybe user friendlyness

File: jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+        return visit(ctx.andExpression());
+    }
+
+    @Override
+    public Boolean visitComparisonExpression(SearchParser.ComparisonExpressionContext ctx) {
+        return visit(ctx.comparison());
+    }
+
+    @Override
+    public Boolean visitComparison(SearchParser.ComparisonContext ctx) {
```
[the remark this answers is not in the document]
Comment (koppor) [reply jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java:73]: I like this comment

Either adress or add a comment

File: CHANGELOG.md [hunk 5]
```diff
@@ -36,6 +36,7 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
 
 ### Fixed
 
+- We fixed the group filter to use OR semantics for space-separated terms, so typing "machine learning" now shows all groups containing either word instead of requiring both. [#12721](https://github.com/JabRef/jabref/issues/12721)
```
Comment (koppor) [inline CHANGELOG.md]: Can your implementation do more?

**Review by koppor — DISMISSED** [review]

File: jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java (hunk 3 above)
Comment (NDGCodes) [reply jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java:23]: I kept it consistent with the previous containsIgnoreCase behavior I can add a comment here like 
// Lowercase for case-insensitive matching

File: jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (NDGCodes) [reply jablib/src/main/java/org/jabref/logic/search/query/GroupNameFilterVisitor.java:73]: ok Im addressing this

File: jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java (hunk 1 above)
Comment (NDGCodes) [reply jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java]: ok i'll convert to parameterized test

File: CHANGELOG.md (hunk 5 above)
Comment (NDGCodes) [reply CHANGELOG.md]: Yes, I have added them now

**Comment by subhramit** [comment]
Please add disclosures on wherever AI has been used in this PR.

File: jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+        if (query == null || query.isBlank()) {
+            return true;
+        }
+        try {
+            var ctx = SearchQuery.getStartContext(query);
+            return new GroupNameFilterVisitor(groupName).visit(ctx);
+        } catch (org.antlr.v4.runtime.misc.ParseCancellationException e) {
+            return groupName.toLowerCase().contains(query.toLowerCase());
+        }
+    }
```
Comment (subhramit) [inline jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java]: There should be no additional handling or business logic in tests

File: jabgui/src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java [hunk 7]
```diff
@@ -109,7 +113,17 @@ public GroupTreeViewModel(@NonNull StateManager stateManager,
...
         // Set-up bindings
-        filterPredicate.bind(EasyBind.map(filterText, text -> group -> group.isMatchedBy(text)));
+        filterPredicate.bind(EasyBind.map(filterText, text -> {
+            if (StringUtil.isBlank(text)) {
+                return group -> true;
+            }
+            try {
+                SearchParser.StartContext ctx = SearchQuery.getStartContext(text);
+                return group -> new GroupNameFilterVisitor(group.getDisplayName()).visit(ctx);
+            } catch (org.antlr.v4.runtime.misc.ParseCancellationException e) {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java]: Why was import not used?

File: jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java [hunk 8]
```diff
@@ -11,15 +10,7 @@
...
-        if (query == null || query.isBlank()) {
-            return true;
-        }
-        try {
-            var ctx = SearchQuery.getStartContext(query);
-            return new GroupNameFilterVisitor(groupName).visit(ctx);
-        } catch (org.antlr.v4.runtime.misc.ParseCancellationException e) {
-            return groupName.toLowerCase().contains(query.toLowerCase());
-        }
+        return GroupNameFilterVisitor.matches(groupName, query);
```
Comment (subhramit) [inline jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java]: Why is this method wrapper needed anymore?

**Comment by subhramit** [comment]
> Please add disclosures on wherever AI has been used in this PR.

.

File: jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java (hunk 8 above)
Comment (NDGCodes) [reply jabgui/src/test/java/org/jabref/gui/groups/GroupNodeViewModelFilterTest.java]: ok i'll remove it

**Comment by subhramit** [comment]
> > Please add disclosures on wherever AI has been used in this PR.
> 
> .

AI seems to have been used in the code, changelog as well as PR description.
Please be honest to not violate our code of conduct.

**Comment by NDGCodes** [comment]
@subhramit I have added wherever Ai has been use in the pr, I didnt use ai to write the changelog . I can rewrite the steps to test if necessary.
