### PR TITLE
Try to relocate listener binding

### LINKED ISSUE #9221: Toolbar is greyed out when adding a new library and no others were opened before
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

_No response_

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start JabRef 
2. Close any open libraries
3. Close JabRef
4. Start JabRef
5. Create a new empty library
6. Toolbar is greyed out, you cannot enter a new entry

grafik

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by koppor**
Tries to fixes #9221

However, 

- the number of groups is not updated any more.
- the "changed" marker is not appearing correctly any more.

---

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/LibraryTab.java [hunk 1]
```diff
@@ -247,6 +239,7 @@ public void feedData(BibDatabaseContext bibDatabaseContext) {
         cleanUp();
 
         this.bibDatabaseContext = Objects.requireNonNull(bibDatabaseContext);
+        stateManager.setActiveDatabase(bibDatabaseContext);
```
Comment (HoussemNasri) [inline src/main/java/org/jabref/gui/LibraryTab.java:242]: Context: The side pane is bound to the activeDatabaseProperty.

When an existing library is opened, a library tab will be added instantly with a loading animation. Then, the activeDatabaseProperty will be updated because a new tab was added and selected. The problem is at that time, the bibDatabaseContext has no entries because they are still loading. What I did here is set the REAL bibDatabaseContext as active after all entries are loaded.

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 2]
```diff
@@ -659,6 +659,15 @@ public void init() {
         Platform.runLater(() -> stateManager.focusOwnerProperty().bind(
                 EasyBind.map(mainStage.getScene().focusOwnerProperty(), Optional::ofNullable)));
 
+        EasyBind.subscribe(tabbedPane.getSelectionModel().selectedItemProperty(), selectedTab -> {
```
Comment (HoussemNasri) [inline src/main/java/org/jabref/gui/JabRefFrame.java:662]: Here, I used `EasyBind#subscribe` instead of binding because a bound value cannot be set, but I'm setting it in another place. See the other comment.

**Comment by HoussemNasri** [comment]
There is still an issue where the count does not update when adding empty entries. IMHO, this is not important and is out of scoop for this pr.
Current behavior:
- Adding the first empty entry to a new library increases the count to one.
- Adding more empty entries does not change the count; it remains at 1.
- When you enter content into the entry, the count starts to update.

**Comment by Siedlerchr** [comment]
Does this work now or is there anything else that needs to be done/checked?

**Comment by HoussemNasri** [comment]
Aside from the toolbar being enabled again, I have made changes to update the entry count when a library is opened asynchronously. However, empty entries are still not counted until they are filled with data or when JabRef is restarted.

File: src/main/java/org/jabref/gui/LibraryTab.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/LibraryTab.java:242]: Please put it as Java Comment? 😇

Comment (HoussemNasri) [reply src/main/java/org/jabref/gui/LibraryTab.java:246]: Thank you for pointing that out. I rephrased it a bit to fit better in a comment, but it should have the same meaning.

**Comment by Siedlerchr** [comment]
I would like to merge this as it already is a huge step forward. A Changelog entry would be needed
