### PR TITLE
Fix for issue custom api key always saved even on cancel

### LINKED ISSUE #11925: Web search preferences "Custom API key" table modifications not discarded
When making changes to the "Custom API key" table in the Web search tab of the preferences, the changes are always saved even when I click **Cancel**.

Steps to Reproduce:
1. Open JabRef Preferences.
2. Navigate to the Web Search tab.
3. Make any modifications in the Custom API key table.
4. Click Cancel to close the Preferences window.
5. Reopen the Preferences and navigate back to the Web Search tab.
6. Observe that the modifications are still present.

Expected Behavior:
Clicking Cancel should discard any changes made to the Custom API Key table.

Actual Behavior:
Changes to the Custom API Key table are saved.

Image

### PR DESCRIPTION
**Pull request by u7663394**
This PR fixes an issue where changes made to the "Custom API key" table in the Web Search tab of the preferences are always saved, even when the user clicks Cancel.

Fix Implemented:
Modified the `WebSearchTabViewModel` class:
- Removed the unnecessary `editableApiKeys` property.
- Changed `apiKeys` from a `ListProperty` to an `ObservableList`.
- Initialized `apiKeys` with a deep copy of the preferences' API keys in `setValues()`.
- Ensured that changes are only saved back to the preferences in `storeSettings()`.
- Simplified the code by eliminating redundant property declarations and assignments.

Closes #11925 

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

Made changes in api key and press **Cancel**:
Make change

Discard now: 
Discard

### CODE REVIEW

File: src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java [hunk 1]
```diff
@@ -69,6 +69,9 @@ public class WebSearchTabViewModel implements PreferenceTabViewModel {
     private final FilePreferences filePreferences;
     private final ImportFormatPreferences importFormatPreferences;
 
+    // Added temporary property to store changes made in the UI
+    private final ListProperty<FetcherApiKey> tempApiKeys = new SimpleListProperty<>(FXCollections.observableArrayList());
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:73]: I wouldn't call it tempSthg because the lifecycle of this variable is the same as the whole dialog or tab. Please reword it.

**Review by calixtus — CHANGES_REQUESTED** [review]
One nitpick, otherwise looks good to me

File: src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java [hunk 2]
```diff
@@ -138,7 +141,15 @@ public void setValues() {
...
-        apiKeys.setValue(FXCollections.observableArrayList(preferences.getImporterPreferences().getApiKeys()));
+        // Initialize tempApiKeys with a deep copy of the actual API Keys, so changes in the UI do not directly affect the actual settings
+        tempApiKeys.set(FXCollections.observableArrayList(
+                preferences.getImporterPreferences().getApiKeys().stream()
+                           .map(apiKey -> new FetcherApiKey(apiKey.getName(), apiKey.shouldUse(), apiKey.getKey()))
+                           .collect(Collectors.toList())
+        ));
+        // Set the UI-bound apiKeys property to tempApiKeys
+        apiKeys.set(tempApiKeys);
+
```
Comment (LoayGhreeb) [inline src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:152]: You can do this directly on the `apiKeys` list without the need for `tempApiKeys`. 

Also, change the `apiKeys` list to an `ObservableList` instead of a `ListProperty`.

**Review by LoayGhreeb — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java [hunk 3]
```diff
@@ -154,6 +165,10 @@ public void setValues() {
 
     @Override
     public void storeSettings() {
+        // Save changes from tempApiKeys back to the actual settings
+        preferences.getImporterPreferences().getApiKeys().clear();
+        preferences.getImporterPreferences().getApiKeys().addAll(apiKeys);
+
```
[the remark this answers is not in the document]
Comment (calixtus) [reply src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java]: Loay 'Eagleeyes' Ghreeb

File: src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java (hunk 2 above)
Comment (u7663394) [reply src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java]: Thank you for the feedback. I have simplified the code by directly working with the `apiKeys`.

I have also changed `apiKeys` from a `ListProperty` to an `ObservableList`  and deleted redundant code about saving perfermance.

I have edited and updated PR Description above. Thank you!

File: src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java [hunk 4]
```diff
@@ -56,7 +56,8 @@ public class WebSearchTabViewModel implements PreferenceTabViewModel {
     private final BooleanProperty grobidEnabledProperty = new SimpleBooleanProperty();
     private final StringProperty grobidURLProperty = new SimpleStringProperty("");
 
-    private final ListProperty<FetcherApiKey> apiKeys = new SimpleListProperty<>();
+    // ObservableList to store API keys for editing in the UI
```
Comment (LoayGhreeb) [inline src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:59]: Remove the comment

File: src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java [hunk 5]
```diff
@@ -138,7 +139,11 @@ public void setValues() {
         grobidEnabledProperty.setValue(grobidPreferences.isGrobidEnabled());
         grobidURLProperty.setValue(grobidPreferences.getGrobidURL());
 
-        apiKeys.setValue(FXCollections.observableArrayList(preferences.getImporterPreferences().getApiKeys()));
+        // Initialize apiKeys with a deep copy of the actual API Keys
```
Comment (LoayGhreeb) [inline src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:142]: Remove the comment

File: src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java [hunk 6]
```diff
@@ -138,7 +139,11 @@ public void setValues() {
...
+        apiKeys.setAll(preferences.getImporterPreferences().getApiKeys().stream()
+                                  .map(apiKey -> new FetcherApiKey(apiKey.getName(), apiKey.shouldUse(), apiKey.getKey()))
+                                  .collect(Collectors.toList()));
```
Comment (LoayGhreeb) [inline src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:145]: Can be simplified 
```suggestion
                                  .toList());
```

Comment (calixtus) [reply src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:145]: Careful, Collectors.toList() creates a new mutable array lust, .toList() an immutable one.

Comment (u7663394) [reply src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:145]: OKay, so I reckon we'll continue using .`collect(Collectors.toList())` to obtain a mutable list, since apiKeys needs to be mutable to allow modifications in the UI ? 

I am a bit unsure about it.

Comment (LoayGhreeb) [reply src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java:145]: Yes, we need an immutable list here.

**Review by LoayGhreeb — APPROVED** [review]

**Comment by calixtus** [comment]
Please test it once more to make sure that to list stuff is now done right. 😅

**Comment by u7663394** [comment]
> Please test it once more to make sure that to list stuff is now done right. 😅

Sure, I have tested both versions, and they both work properly. Both support the normal operation of save and cancel.

**Review by calixtus — APPROVED** [review]
