### PR TITLE
Fix jstyle was invalid with default section at the start

### LINKED ISSUE #6303: "you must select a valid style file" problem
Hi! Jabref is a very promising tool. Thank you for the developing!

My environment is Windows 10 x64.

My software is JabRef-5.0-portable_windows.zip (jabref portable version for Windows ). I've also tested the JabRef-5.1-portable_windows.zip (14-04-2020)  with the same result.

When i try to load any style file i always get the message "you must select a valid style file".

I have tried the _American_Mineralogist.jstyle_ and _BJAST.jstyle_ files.  i have downloaded this .jstyle files from [https://github.com/JabRef/jstyles.jabref.org](https://github.com/JabRef/jstyles.jabref.org)

I have test the UTF-8 encoding with notepad++ 

Any idea?

Thanks in advance!!

DJuego

jabref_style

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #6303
Adapted the error message to give a hint what is probably missing.

I also noticed a problem in eclipse when executing the L10n test. It was missing an add-opens

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java [hunk 1]
```diff
@@ -71,7 +71,7 @@ public void addStyleFile() {
                 styles.setAll(loadStyles());
                 selectedItem.setValue(getStyleOrDefault(stylePath));
             } else {
-                dialogService.showErrorDialogAndWait(Localization.lang("Invalid style selected"), Localization.lang("You must select a valid style file."));
+                dialogService.showErrorDialogAndWait(Localization.lang("Invalid style selected"), Localization.lang("You must select a valid style file. Your style is probably missing a line for the type \"default\"."));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java:74]: Is it possible to get more information (than a boolean) about why a style file is not valid? I guess the missing `default` may only be one of many reasons and so far the error message is not really helpful in diagnosing the problem.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java:74]: This is more or less the only reason. The other is that if you have no sections defined.
Other things (Layout parsing etc) are already handled with exceptions 
https://github.com/JabRef/jabref/blob/940ef9d3be3f3877035fbcf3da6b637b53944c40/src/main/java/org/jabref/logic/openoffice/OOBibStyle.java#L327-L331
