### PR TITLE
Fix selecting custom export for copy to clipboard with uppercase file ext

### LINKED ISSUE #6285: Copy -> Export to Clipboard: Custom exports not a
JabRef 5.0--2020-03-06--2e6f433 (Portable)
Windows 10 10.0 amd64 
Java 13.0.2

I have several Custom Exports defined, and they word as intended via File -> Export.
However, when right-clicking on an entry in the entry table, and going for "Copy..." -> Export to clipboard,  the Custom Exports are not visible. This worked fine in earlier JabRef versions (e.g  3.4.1)

Screengrab below: the red part shows default export formats to choose from, but the Custom Exports are not available in the pull-down menu.

Untitled

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #6285

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java [hunk 1]
```diff
@@ -34,21 +35,24 @@
     private static final Logger LOGGER = LoggerFactory.getLogger(ExportToClipboardAction.class);
 
     // Only text based exporters can be used
-    private static final List<String> SUPPORTED_FILETYPES = Arrays.asList("txt", "rtf", "rdf", "xml", "html", "htm", "csv", "ris");
+    private static final Set<String> SUPPORTED_FILETYPES = Set.of("txt", "rtf", "rdf", "xml", "html", "htm", "csv", "ris");
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java:38]: Suggestion: convert this field to `Set<FileType>` then you don't need to compare extensions and it's a bit more readable as well.

File: src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java [hunk 2]
```diff
@@ -74,12 +78,13 @@ public void execute() {
...
-                Localization.lang("Export"), defaultChoice, exporters);
+                                                                                    Localization.lang("Export"), defaultChoice, exporters);
 
         selectedExporter.ifPresent(exporter -> BackgroundTask.wrap(() -> exportToClipboard(exporter))
-                                                                .onSuccess(this::setContentToClipboard)
-                                                                .onFailure(ex -> { /* swallow as already logged */ })
-                                                                .executeWith(Globals.TASK_EXECUTOR));
+                                                             .onSuccess(this::setContentToClipboard)
+                                                             .onFailure(ex -> {
+                                                                 /* swallow as already logged */ })
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java:86]: Instead of rethrowing the exception below, I would add logging + displaying to the user here.

File: src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java:38]: As I doubted it already, it's not possible to compare, because when you create a new TemplateExporter, the FileExtension is created dynamically using newFileType.
And if I compare the Enums directly I would be comparing apples and oranges.

https://github.com/JabRef/jabref/blob/c25b639d82d551e8c2e527ae76f7c53fc4735d90/src/main/java/org/jabref/logic/util/StandardFileType.java#L54-L60

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java:40]: Ok, but that's more a shortcoming of this method than a real problem. 
It should be possible to first lookup if the StandardFileType contains a type with matching extensions (similar to the following):
https://github.com/JabRef/jabref/blob/b5002e041d587ffb997e946f55daa9f8bdb438d4/src/main/java/org/jabref/model/entry/field/InternalField.java#L38-L42
and if not return a `UnknownFileType` that implements a proper equals 
https://github.com/JabRef/jabref/blob/b5002e041d587ffb997e946f55daa9f8bdb438d4/src/main/java/org/jabref/model/entry/field/UnknownField.java#L30-L45

Definitely a bit more complex then your solution, but should be a bit more future-proof.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java]: Thanks for the hint, applied a similar approach now for the FileTypes

File: src/main/java/org/jabref/logic/util/StandardFileType.java [hunk 3]
```diff
@@ -51,12 +54,13 @@
...
-        for (int i = 0; i < extensions.length; i++) {
-            if (extensions[i].contains(".")) {
-                extensions[i] = extensions[i].substring(extensions[i].indexOf('.') + 1);
-            }
-        }
-        return () -> Arrays.asList(extensions);
+    public static FileType fromExtensions(String... extensions) {
+        var exts = Arrays.asList(extensions);
+
+        return OptionalUtil.orElse(Arrays.stream(StandardFileType.values())
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/util/StandardFileType.java:60]: I think `OptionalUtil.orElse` is no longer needed, as Java has now its own `orElse` method.

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/util/StandardFileType.java:60]: @tobiasdiez  Yes, but it did not work with the type inference, it expected a type of StandardFileType in the orElse part and created a compile error when 
Therefore I had to use our util method:
https://stackoverflow.com/a/54238663

Please wait with merging I think I still need to convert the extensions to lower case before
