### PR TITLE
"Embedded BibTeX pdf" export fix

### LINKED ISSUE #10101: PDF export embedded bibtex not working
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.File -> Export All entries
2. embedded bibtex (pdf)
3. No file is saved where you have chosen to save it

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by atdushi**
Fixes #10101

If no existing document is selected for exporting "Embedded BibTeX pdf" JabRef will now create a new PDF file with a sample text and the metadata.

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]

File: src/main/java/org/jabref/logic/exporter/EmbeddedBibFilePdfExporter.java [hunk 1]
```diff
@@ -61,6 +65,24 @@ public void export(BibDatabaseContext databaseContext, Path file, List<BibEntry>
...
+                try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
+                    contentStream.beginText();
+                    contentStream.newLineAtOffset(25, 500);
+                    contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
+                    contentStream.showText("This PDF was created by JabRef. It demonstrates the embedding of BibTeX data in PDF files. Please open the file metadata view of your PDF viewer to see the attached files.");
+                    contentStream.endText();
+                }
+                document.save(file.toString());
+            } catch (IOException e) {
+                throw new Exception("Error creating PDF", e);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/exporter/EmbeddedBibFilePdfExporter.java:82]: Please do not throw a generic exception here, just log it

**Review by Siedlerchr — APPROVED** [review]

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/pull/10361.

**Review by koppor — APPROVED** [review]
