### PR TITLE
Fixed an issue where a new entry is not shown in the library if a filter/search is active

### LINKED ISSUE #6297: Creating an new entry should clean up the filter
When I filter the entries and open a new entry,
for example a TechReport,
the list of entries does not show the new entry.

Therefore I recommend:
  Creating a new entry should clean up the filter
because I prefer that a new entry is also immediately
reflected in the list of entries.

If the current behaviour is a feature,
please provide a possiblity to switch this feature on and off.

Thanks.

JabRef 5-0 2020-03-06
MacOS 10.15.4
Java 13.0.2

### PR DESCRIPTION
**Pull request by nsmt09**
Fixes #6297 

I used the existing endSearch method of GlobalSearchbar to clear the search if a new entry is added.

Probably the solution is quite quick and dirty and I am not sure if it fits to your architecture and if I added it at the the right spot in the code.

I would be happy about feedback and advice for the future! 

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date?

### CODE REVIEW

File: src/main/java/org/jabref/gui/EntryTypeView.java [hunk 1]
```diff
@@ -188,6 +188,7 @@ private void focusTextField(Event event) {
     private void setEntryTypeForReturnAndClose(Optional<BibEntryType> entryType) {
         type = entryType.map(BibEntryType::getType).orElse(null);
         viewModel.stopFetching();
+        this.basePanel.frame().getGlobalSearchBar().endSearch();
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/EntryTypeView.java:191]: A better solution would be to Inject the StateManager and call 
`clearSearchQuery`

**Comment by Siedlerchr** [comment]
@nsmt09  It would be really cool if you could change this so we can merge your PR.

**Comment by nsmt09** [comment]
> @nsmt09 It would be really cool if you could change this so we can merge your PR.

Sorry I was really busy the last weeks
I adjusted the fix like you recommended by injecting the StateManager and using clearSearchQuery
