### PR TITLE
Fix for multiple error messages in messed up source editor

### LINKED ISSUE #5820: Error when messing up bibtex
Hello,
Here is a deadlock error which happened to me while pasting a bibtex entry next to en existing one. A warning appears as shown in the picture but the user cannot close it as it keeps reopening. I had to search the JabRef process in Linux and kill it.

This happened for version5.0 beta 1 in Linux.
Regards,
Cristian

Screenshot_2020-01-07_11-36-41

### PR DESCRIPTION
**Pull request by calixtus**
Fixes #5820

JabRef created a new instance of CodeArea everytime an entry was selected and bound multiple listeners to the CodeArea and to the ValidationStatus in bindToEntry. Refactored it a little bit, so the CodeArea stays persistent and the error messages are only displayed once.

Did some minor refactorings to the other Validators and to modules.info too, to avoid warning messages from the IDE, and fixed a minor mistake from a previous PR in dark.css. 

No screenshot, as there is no visual change.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for the fix. I don't know exactly what , but I remember we had issues with the code area when going up and down in the main table with an open entry editor. And also when importing?. I know that there was a reason why it was created new every time. 
Maybe @tobiasdiez remembers

File: src/main/java/org/jabref/gui/entryeditor/SourceTab.java [hunk 1]
```diff
@@ -64,15 +63,17 @@
...
     private final ImportFormatPreferences importFormatPreferences;
     private final FileUpdateMonitor fileMonitor;
     private final DialogService dialogService;
     private final StateManager stateManager;
     private Optional<Pattern> searchHighlightPattern = Optional.empty();
-    private CodeArea codeArea;
+    private final CodeArea codeArea;
     private KeyBindingRepository keyBindingRepository;
 
+    private BibEntry boundEntry;
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/entryeditor/SourceTab.java]: The parent `EntryEditorTab` already defines `currentEntry`, which seems to be what you want.

File: src/main/java/org/jabref/gui/entryeditor/SourceTab.java [hunk 2]
```diff
@@ -201,30 +218,13 @@ public boolean shouldShow(BibEntry entry) {
...
-                storeSource(entry, codeArea.textProperty().getValue());
-            }
-        }, fields -> {
+        if (boundEntry != null) {
+            storeSource(boundEntry, codeArea.textProperty().getValue());
+        }
+
+        this.boundEntry = entry;
+
+        if (entry != null) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/entryeditor/SourceTab.java]: Why did you removed the binding `fields -> code area`? If the entry changes (e.g. cleanup actions or "generate bibtex key" or set special fields like ranked/printed/...), then these changes should be reflected in the source tab, too.

Comment (calixtus) [reply src/main/java/org/jabref/gui/entryeditor/SourceTab.java]: This was part of the fix to the CodeArea problem, @Siedlerchr mentioned. Selecting another entry copied the content of the sourcetab into the new selected entry, so it duplicated your old one and removed the selected one. But I did not think of the binding to the other fields. 🤦‍♂ 
I'm going to take a look into this tonight.

File: src/main/java/org/jabref/gui/entryeditor/SourceTab.java (hunk 1 above)
Comment (calixtus) [reply src/main/java/org/jabref/gui/entryeditor/SourceTab.java]: changed the Name to previousEntry. Part of the fix for the recreated CodeArea. JabRef needs to keep the previous entry to store it, because the focus event is fired after the new entry is loaded.

File: src/main/java/org/jabref/gui/entryeditor/SourceTab.java (hunk 2 above)
Comment (calixtus) [reply src/main/java/org/jabref/gui/entryeditor/SourceTab.java]: Fixed it.

**Comment by calixtus** [comment]
This should do the trick now. Apparently JavaFX fires the focus event after loading the next entry and registering a listener does not mean, it is also run.

What I don't understand is the failing GUI test. It fails somehow during setting the test up trying to call getSourceString with an empty BibEntry.
It does not fail with a real entry open in JabRef, but only with the test. Should I modify the test?

**Comment by tobiasdiez** [comment]
I guess the test fails as `currentEntry` is null in https://github.com/JabRef/jabref/pull/5823/files#diff-e6eac13930d81c3c9c3ddc47d1b354a9R223

You can change https://github.com/JabRef/jabref/blob/master/src/test/java/org/jabref/gui/entryeditor/SourceTabTest.java#L81 to `notifyAboutFocus`.
