### PR TITLE
Fixing journal abbreviation roundtrip

### LINKED ISSUE #9370: Entry editor: Toggle journal abbreviation roundtrip does not work
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

mac os 11.7 big sur

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.  Create a new article, set journal or journaltitle to  `Comm. Pure Appl. Math.`
2.  Click on the Toggle abbreviation button next to the field
grafik
 
4. A dotless abbreviation is now in the field (Medline abbrev)
5. The field now shows `Comm Pure Appl Math`
6. Click again on the Toggle abbrevation button.
7. Nothing happens

=> Here the full journal name should be visible

## Hints on the code

For anyone looking into this:
The problem is that both methods [isKnownName](https://github.com/JabRef/jabref/blob/a1f2d5181ce1d99674c30bbd4894158f9b3d1437/buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationRepository.java#L50)
 and https://github.com/JabRef/jabref/blob/a1f2d5181ce1d99674c30bbd4894158f9b3d1437/buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationRepository.java#L77

do not consider a dotless abbreviation.

Solution could be to replace spaces with dots before checking. 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by K5qu4r3d**
Fixes #9370 as well as added a test case for dot-less abbreviations.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java [hunk 1]
```diff
@@ -67,7 +69,30 @@ public boolean isAbbreviatedName(String journalName) {
...
         return customAbbreviations.stream().anyMatch(abbreviation -> isMatchedAbbreviated(journal, abbreviation))
-                || abbreviationToFull.containsKey(journal);
+                || abbreviationToFull.containsKey(journal) || findDottedAbbrFromDotless(journal).length() > 0;
+    }
+
+    public String findDottedAbbrFromDotless(String journalName) {
+        String foundKey = "";
+
+        // check for a dot-less abbreviation
+        if (!Pattern.compile("\\.").matcher(journalName).find()) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java:79]: If you use Pattern.compile it's usually a good idea to store the pattern as a static final variable e.g. 
`final static Pattern DOT = Pattern.compile("\\."); `

File: src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java [hunk 2]
```diff
@@ -67,7 +69,30 @@ public boolean isAbbreviatedName(String journalName) {
...
+            // use dot-less abbr to find full name using regex
+            String[] journalSplit = journalName.split(" ");
+
+            for (int i = 0; i < journalSplit.length; i++) {
+                String word = journalSplit[i] + "[\\.\\s]*";
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java:84]: See my comment above,

**Review by Siedlerchr — COMMENTED** [review]
This is very cool! Overall I think this could be a valid way. LIke that you created a test!
I only have some minor comments so far

File: src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java (hunk 2 above)
Comment (K5qu4r3d) [reply src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java:84]: I'm not sure what you mean.

Did you mean to point out line 91 where it has `Pattern.compile(joined).matcher(s).find()`?

I don't believe I can move `Pattern.compile(joined)` to a static variable since it depends on `String joined = String.join("", journalSplit);` right above it.

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java:84]: Ah then I misread that line.

File: src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java (hunk 1 above)
Comment (K5qu4r3d) [reply src/main/java/org/jabref/logic/journals/JournalAbbreviationRepository.java]: Static variable has been set up.

**Review by calixtus — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
Thanks for the PR LGTM to me
