### PR TITLE
Fix for issue #4652: Add Find Unlinked Files Filter based on Date

### LINKED ISSUE #4652: Find NEW files (PDFs - based on date)
I asked for this in the JabRev Forum and Christoph encouraged me to make an suggestion for an improvement for the ‘Find unlinked files’ function. My problem is that this shows all unlinked files without showing the date of the file-creation / -change, or what would be even better, allows not to restrict on new (1 day, 1 week, …) files. As I have - due to historic reason - quite a lot of unlinked files I cannot use this functionality as it is implemented so far. 

- Maybe a very first easy step toward would be to show the file creation date for the found unlinked files. 
- A second step would be a sorting of the files by date 
- And as final step a selection rule like the already available one 'Select file type' maybe named 'Select by date of last change' would be very handy.

Best regards Wolfgang

### PR DESCRIPTION
**Pull request by gdrosos**
Hello everyone, we made 3 additions to the Find Unlinked Files Function as following:
* Firstly, for each file  we showed to the relevant Dialog near its name the date of the last modification.

* Secondly, we added a Date-based Filter to show only specific files based on the date of the last modification.

<p>

</p>

Finally, we made it possible to sort the files based on the date of the last modification. 

</p>

For future steps, we plan to:
1. Address the potential requested changes by the reviewers.
2. Add Unit Tests to the created code where applicable.

Fixes #4652

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Thanks for the good work 👍  ! Looks overall good to me, just a few minor improvements

File: src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+                .sorted(Comparator.comparingLong(x -> FileFilterUtils.getFileTime(x)
+                        .atZone(ZoneId.systemDefault())
+                        .toInstant()
+                        .toEpochMilli()))
+                .collect(Collectors.toList());
+    }
+
+    public List<Path> sortByDateDescending(List<Path> files) {
+        return files.stream()
+                .sorted(Comparator.comparingLong(x -> -FileFilterUtils.getFileTime(x)
```
[the remark this answers is not in the document]
Comment (gdrosos) [reply src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java:84]: Hello @Siedlerchr, thanks for the feedback! I think on this example we cannot replace the lambda with a method reference because from the method getFileTime the atZone method is called.
Thanks in advance.

Screenshot_452

[the remark this answers is not in the document]
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java:84]: Ah okay, thanks, seems I overlooked that.  Then just please use a more meaningful name for the lambda parameter

File: src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java [hunk 2]
```diff
@@ -90,9 +95,21 @@ public UnlinkedFilesDialogViewModel(DialogService dialogService, ExternalFileTyp
...
+            new FileExtensionViewModel(StandardFileType.ANY_FILE, externalFileTypes),
+            new FileExtensionViewModel(StandardFileType.BIBTEX_DB, externalFileTypes),
+            new FileExtensionViewModel(StandardFileType.PDF, externalFileTypes));
+
+        this.dateFilterList = FXCollections.observableArrayList(
+            new ExternalFilesDateViewModel(DateRange.ALL_TIME.getDateRange()),
+            new ExternalFilesDateViewModel(DateRange.YEAR.getDateRange()),
+            new ExternalFilesDateViewModel(DateRange.MONTH.getDateRange()),
+            new ExternalFilesDateViewModel(DateRange.WEEK.getDateRange()),
+            new ExternalFilesDateViewModel(DateRange.DAY.getDateRange()));
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java:107]: Work with Enums, not Strings!
Then you can use `DateRange.values()`

File: src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java [hunk 3]
```diff
@@ -90,9 +95,21 @@ public UnlinkedFilesDialogViewModel(DialogService dialogService, ExternalFileTyp
...
+
+        this.fileSortList = FXCollections.observableArrayList(
+            new FileSortViewModel(ExternalFileSorter.DEFAULT.getSorter()),
+            new FileSortViewModel(ExternalFileSorter.DATE_ASCENDING.getSorter()),
+            new FileSortViewModel(ExternalFileSorter.DATE_DESCENDING.getSorter()));
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java:112]: Same here: `ExternalFileSorter.values()`

**Review by calixtus — CHANGES_REQUESTED** [review]
Thanks for your work so far and your great ideas how to improve this dialog. However, I got some remarks that should be addressed. Thanks!

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java [hunk 4]
```diff
@@ -1,16 +1,121 @@
...
+    }
+
+    @Test
+    public void testSortByDateAscending() {
+        ArrayList<String> actuals = new ArrayList<String>();
+        ArrayList<Path> sortedPaths = fileFilterUtils.sortByDateAscending(files);
+        for (Path path : sortedPaths) {
+            actuals.add(path.)
+        }
+        assertThat(files, is(expectedSortByDateAscending));
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java]: At JabRef we once decided not to use the hamcarest matchers. Therefore, please use an assertEquals.
assertEquals also works on lists or other complex objects

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java [hunk 5]
```diff
@@ -1,16 +1,121 @@
...
+        firstFile.delete();
+        secondFile.delete();
+        thirdFile.delete();
+        fourthFile.delete();
+        directory.delete();
+    }
+
+    @Test
+    public void testSortByDateAscending() {
+        ArrayList<String> actuals = new ArrayList<String>();
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java]: Code against Interfaces,  not implementations  https://medium.com/javarevisited/oop-good-practices-coding-to-the-interface-baea84fd60d3 
Therefore, the Left side should always be the most "abstract" type (or an interface)

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Some code style improvements for the tests

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java (hunk 5 above)
Comment (gdrosos) [reply src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java]: Hello @Siedlerchr thanks for the quick response, those tests are under construction and we mistakenly commited them ahead of time. We plan to commit them when they are ready, but thanks for the help we will include your suggestions.

**Comment by gdrosos** [comment]
> Thanks for your work so far and your great ideas how to improve this dialog. However, I got some remarks that should be addressed. Thanks!
Thanks @calixtus  for the feedback, we adapted the code in order to use Enums directly instead of Strings.

**Comment by gdrosos** [comment]
Hello @Siedlerchr thanks for the very quick response! Those tests are under construction and we mistakenly commited them half-done. We plan to commit them when they are ready, but thanks for the help, we will include your suggestions. Sorry for the trouble.

**Comment by gdrosos** [comment]
Hello @Siedlerchr and @calixtus , me and @gliargovas have finished addressing the requested changes, feel free to review them whenever you can. Thanks in advance.

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java [hunk 6]
```diff
@@ -0,0 +1,207 @@
...
+            Path thirdPath = Path.of(dirPath.concat("/thirdFile.pdf"));
+            Path fourthPath = Path.of(dirPath.concat("/fourthFile.pdf"));
+    
+            Files.createFile(firstPath);
+            Files.createFile(secondPath);
+            Files.createFile(thirdPath);
+            Files.createFile(fourthPath);
+
+            // change the files last edited times.
+            File firstFile = new File(firstPath.toString());
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java:93]: use the nio method so you don't the 
 https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createFile(java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...)

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java [hunk 7]
```diff
@@ -0,0 +1,207 @@
...
+            File fourthFile = new File(fourthPath.toString());
+    
+            ZoneId zoneId = ZoneId.systemDefault();
+    
+            LocalDateTime firstDate = LocalDateTime.of(2021, 1, 10, 0, 0, 0, 0);
+            LocalDateTime secondDate = LocalDateTime.of(2021, 1, 5, 0, 0, 0, 0);
+            LocalDateTime thirdDate = LocalDateTime.of(2021, 1, 1, 0, 0, 0, 0);
+            LocalDateTime fourthDate = LocalDateTime.of(2021, 1, 2, 0, 0, 0, 0);
+    
+            firstFile.setLastModified(firstDate.atZone(zoneId).toEpochSecond());
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java:105]: https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#setLastModifiedTime-java.nio.file.Path-java.nio.file.attribute.FileTime-

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java [hunk 8]
```diff
@@ -0,0 +1,207 @@
...
+
+        private List<Path> files = new ArrayList<Path>();
+        private List<String> expectedSortByDateAscending = new ArrayList<String>();
+        private List<String> expectedSortByDateDescending = new ArrayList<String>();
+        private List<String> wrongOrder = new ArrayList<String>();
+
+        /* Initialize the directory and files used in the sorting tests, and change their last edited dates. */
+        @BeforeEach
+        public void setUp() throws Exception {
+            String dirPath = "src/test/resources/unlinkedFiles";
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java:77]: Better use a temporary File directory https://www.baeldung.com/junit-5-temporary-directory#1-tempdir-as-a-method-parameter this has the advantage that the dir is automaticaly cleaned

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java [hunk 9]
```diff
@@ -0,0 +1,207 @@
...
+            }
+            actualsList.toArray(actuals);
+            expectedSortByDateAscending.toArray(expecteds);
+            assertArrayEquals(actuals, expecteds);
+        }
+
+        @Test
+        public void sortByDateAscendingNegativeTest() {
+            List<String> actualsList = new ArrayList<String>();
+            List<Path> sortedPaths = fileFilterUtils.sortByDateAscending(files);
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java:168]: Why not use a stream here? So you don't need to create arrrays
streams().map(Path::toString).collectors(Collection.toList())

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java [hunk 10]
```diff
@@ -0,0 +1,207 @@
...
+            String[] expecteds = new String[4];
+            String[] actuals = new String[4];
+            for (Path path : sortedPaths) {
+                actualsList.add(path.toString());
+            }
+            actualsList.toArray(actuals);
+            wrongOrder.toArray(expecteds);
+            assertFalse(Arrays.equals(actuals, expecteds));
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java:176]: use `assertNotEquals(expeted,actual)`

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
some optimizations for the test code, otherwise lgtm

**Review by calixtus — CHANGES_REQUESTED** [review]
4 issues I saw to make the changes more simple.

**Comment by gliargovas** [comment]
Hello @Siedlerchr and @calixtus , we have addressed your suggestions. We are open to any further remarks.

File: src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java [hunk 11]
```diff
@@ -90,9 +95,21 @@ public UnlinkedFilesDialogViewModel(DialogService dialogService, ExternalFileTyp
...
+            new FileExtensionViewModel(StandardFileType.ANY_FILE, externalFileTypes),
+            new FileExtensionViewModel(StandardFileType.BIBTEX_DB, externalFileTypes),
+            new FileExtensionViewModel(StandardFileType.PDF, externalFileTypes));
+
+        this.dateFilterList = FXCollections.observableArrayList(
+            DateRange.ALL_TIME,
+            DateRange.YEAR,
+            DateRange.MONTH,
+            DateRange.WEEK,
+            DateRange.DAY);
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java:107]:
```suggestion
        this.dateFilterList = FXCollections.observableArrayList(DateRange.values());
```

File: src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java [hunk 12]
```diff
@@ -90,9 +95,21 @@ public UnlinkedFilesDialogViewModel(DialogService dialogService, ExternalFileTyp
...
+
+        this.fileSortList = FXCollections.observableArrayList(
+            ExternalFileSorter.DEFAULT,
+            ExternalFileSorter.DATE_ASCENDING,
+            ExternalFileSorter.DATE_DESCENDING);
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesDialogViewModel.java:112]:
```suggestion
        this.fileSortList = FXCollections.observableArrayList(ExternalFileSorter.values());
```

**Review by calixtus — COMMENTED** [review]
Some more small ideas

**Comment by gdrosos** [comment]
> Some more small ideas

Thanks @calixtus  for the quick response, we commited your suggestions and we rearranged the sequence of DateTime Enums in order to have the correct order when the values() method is called

File: src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java [hunk 13]
```diff
@@ -0,0 +1,111 @@
...
+    /* Returns the last edited time of a file as LocalDateTime. */
+    public static LocalDateTime getFileTime(Path path) {
+        FileTime lastEditedTime = null;
+        try {
+            lastEditedTime = Files.getLastModifiedTime(path);
+        } catch (IOException e) {
+            LOGGER.error("Could not retrieve file time", e);
+        }
+        LocalDateTime localDateTime = lastEditedTime
+                .toInstant()
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java:29]: IntelliJ complains here, that toInstant may throw a NPE. This seems possible, since you don't return when a IOException occurs. Is that something we should think about?

**Review by calixtus — APPROVED** [review]
Looks good to me now. Thanks!

**Comment by gdrosos** [comment]
> Looks good to me now. Thanks!

Thank you very much, so maybe we need to place the code in a try catch block to handle the NPE? Also we don't know how to pass the gtihub action check regarding the creation of the installer and portable version for macOS. Thanks in advance.

File: src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java (hunk 13 above)
Comment (gdrosos) [reply src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java:29]: Thank you very much @calixtus , so maybe we need to place the code in a try catch-block to handle the NPE?

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java (hunk 6 above)
Comment (gdrosos) [reply src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java]: Hello @Siedlerchr we tried to resolve this issue on this commit: a495c1647800be62cc7d4c18f9f2d94097d05950

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
LGTM as well! You can ignore the mac, the action doesn't work on forks because it requires access to some secrets (and that are not avaiable on forks)

File: src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java (hunk 7 above)
Comment (gdrosos) [reply src/test/java/org/jabref/gui/externalfiles/FileFilterUtilsTest.java]: > LGTM as well! You can ignore the mac, the action doesn't work on forks because it requires access to some secrets (and that are not avaiable on forks)

Thank you very much, so the main thing left now is to deal with the NPE @calixtus  mentioned. We can either handle it separately or include the code in the above try catch block  so that the NPE will never be triggered

**Comment by gdrosos** [comment]
> LGTM as well! You can ignore the mac, the action doesn't work on forks because it requires access to some secrets (and that are not avaiable on forks)

Thank you very much, so the main thing left now is to deal with the NPE @calixtus  mentioned. We can either handle it separately or include the code in the above try catch block  so that the NPE will never be triggered

File: src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java (hunk 13 above)
Comment (calixtus) [reply src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java:29]: Well, there must be a value returned from this method... Which one, if getLastModifiedTime fails?
Today? null?

Comment (gdrosos) [reply src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java:29]: Yes, sorry you are right, we will return LocalDateTime.now() when an IOException occurs

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
As soon as the tests are green, we can merge. Thanks!

**Comment by gdrosos** [comment]
Guys me and @gliargovas  want to thank you very much for the cooperation and the help you offered us to deal with this issue, everything was great. We are more than happy to be part of this Community!

**Comment by calixtus** [comment]
You're welcome. We really appreciate your work you put in JabRef.

**Comment by Siedlerchr** [comment]
I can only fully agree with @calixtus, this was excellent work! We hope to see more from you in the future! :)
