### PR TITLE
Fix preview style configuration

### LINKED ISSUE #4609: Preview not configurable
JJabRef 5.0-dev--snapshot--2019-01-23--master--c6a1fcbe3
Windows 7 6.1 amd64 
Java 1.8.0_201

- [+ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open jabref and select an entry in the maintable
2. press ALT-2 twotimes to show entry preview
3. Goto OPTIONS->PREFERENCES->ENTRY PREVIEW 
4. Select e.g. BIOLOGICA and view it in TEST
5. double click BIOLOGICA and 
6. surprisingly you are back to the default preview 

Screenshot of the desired preview
grafik

Screenshot of the default preview
grafik

<details>
  <summary>Log File</summary>
  Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20171208VS5.0.bib
Can only load style files: Preview
Can only load style files: Preview
Can only load style files: Preview
Can only load style files: Preview
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by chelseyong**
Fixes #4609.
User mentioned that after pressing one of the styles and saving it, the style is not updated.
To change the preview style, he has to move the selected style to the right column before pressing "Save".

Selecting styles in the right column can be previewed in the test panel. However, the style of bibEntry is not updated after pressing `Test`. To rectify this, the citation style is updated in Preferences.
To ensure preview style configuration is saved, the chosen preview style is also saved in the Preferences.

Note that if preview style (at the left column) is selected, the configuration will not be saved.

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Code looks good from my side as well. Could you please test if the error I encountered is also resolved with your code #4621  ?

**Comment by chelseyong** [comment]
@Siedlerchr That error is not resolved in my PR. Do you want me to fix it?

File: src/main/java/org/jabref/gui/PreviewPanel.java [hunk 1]
```diff
@@ -299,6 +301,9 @@ public void update() {
                                                         .doLayout(entry, databaseContext.getDatabase())));
             setPreviewLabel(sb.toString());
         } else if (basePanel.isPresent() && bibEntry.isPresent()) {
+            if (citationStyle != null && previewStyle != defaultPreviewStyle) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/PreviewPanel.java]: Codacy noted that you use == for object comparison.
should be ! a.equals(b)

**Comment by Siedlerchr** [comment]
@chelseyong  Okay, thanks for the info. If you want you could do this in another PR.

**Comment by Siedlerchr** [comment]
Thanks again for your contribution!
