### PR TITLE
Fixes and Extends BibliographyConsistencyCheck.check to Handle Custom Entry Types

### LINKED ISSUE #13794: Support customized entry types in BibliographyConsistencyCheck
(This is a follow-up to #13584)

We have a library consistency check for checking whether fields in a set of entries are set/unset consistently. Currently, this is aware of the difference of BibTeX and BibLaTeX, but not [Custom Entry Types](https://docs.jabref.org/setup/customentrytypes) 

⚠ This is a good excercise to learn test-driven development and using a data model. This issue cannot be solved with an AI. You really have to think though BibTeX and BibLaTeX for yourself! Take this issue only if you are willing to invest significant time. ⚠

Example entry - from https://dblp.org/rec/journals/sqj/IftikharBAK25.html

```bibtex
@article{DBLP:journals/sqj/IftikharBAK25,
  author       = {Umar Iftikhar and
                  J{\"{u}}rgen B{\"{o}}rstler and
                  Nauman Bin Ali and
                  Oliver Kopp},
  title        = {Supporting the identification of prevalent quality issues in code
                  changes by analyzing reviewers' feedback},
  journal      = {Softw. Qual. J.},
  volume       = {33},
  number       = {2},
  pages        = {22},
  year         = {2025},
  url          = {https://doi.org/10.1007/s11219-025-09720-9},
  doi          = {10.1007/S11219-025-09720-9},
  timestamp    = {Mon, 12 May 2025 21:02:32 +0200},
  biburl       = {https://dblp.org/rec/journals/sqj/IftikharBAK25.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}
```

It contains `bibourl` and `bibsource`

One could make these two fields required.

```bibtex
@article{withBibSource,
  journal      = {Softw. Qual. J.},
  bibsource = {2025}
}

@article{withoutBibSource,
  journal      = {Softw. Qual. J.},
}
```

With the existing consistency check, `bibsource` is reported as `unknown`. If the entry type `article` is modified to have this as optional field, it is reported as optional.

## Task

- Modify `org.jabref.logic.quality.consistency.BibliographyConsistencyCheck` to use `org.jabref.model.entry.BibEntryTypesManager` instead of org.jabref.model.entry.types.BiblatexEntryTypeDefinitions#ALL

## Hints

- Do test-driven development. Start at`org.jabref.logic.quality.consistency.BibliographyConsistencyCheckTest`. Do not modify existing tests; add new ones.
- Look into `org.jabref.model.entry.BibEntryTypesManagerTest` for how to mock `BibEntryTypesManager`.
- Do not get confused with "library" and "database". User-facing we talk about "library", inside the code, we use "database", but mean "library".

### PR DESCRIPTION
**Pull request by Hrishi-Baskaran**
### **User description**
Closes #13794

The current implementation of BibliographyConsistencyCheck.check is only aware of standard entry types of both BibTex and BibLaTex. The current implementation is not able to handle scenarios where the user defines a custom bibliography entry type. In this PR, BibliographyConsistencyCheck.check will be modified to handle consistency checks involving custom entry types in addition to new unit tests to cover the check for a variety of mocked custom entry types.

This PR also fixes a bug with the check function. The check function was also intended to check if required fields for a given type were set - returning entries that didn't have required fields set as inconsistencies. This was not mentioned in the javadoc but attempted anyway. Even then, the implementation was incorrect. In this PR, the implementation is updated to correctly determine if required fields are set. The Javadoc is also updated to explicitly mention this.

### Steps to test

One can test this feature by running the tests in
BibliographyConsistencyCheckTest

In a live application, one can test this feature by going to Quality -> Check Consistency on a database. Ideally test on a database with custom entry types or with entry types that don't have required fields set to see the new update.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [x] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

___

### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Consistency check now supports custom entry types and fields

- Fixed required fields detection to properly handle OrFields constraints

- Integrated BibEntryTypesManager throughout consistency check pipeline

- Updated all callers to pass BibEntryTypesManager parameter

- Enhanced test coverage with custom type scenarios

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["BibliographyConsistencyCheck"] -->|uses| B["BibEntryTypesManager"]
  B -->|retrieves| C["Entry Type Definitions"]
  C -->|includes| D["Standard Types"]
  C -->|includes| E["Custom Types"]
  A -->|validates| F["Required Fields"]
  F -->|handles| G["OrFields Constraints"]
  A -->|detects| H["Field Inconsistencies"]
```

<details><summary><h3>File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement, bug fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td><strong>BibliographyConsistencyCheck.java</strong><dd><code>Core consistency check refactored for custom types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-72370ff3854216f72af92bd9037b16ec26257efb4fc057a596ab1d5b79427bac">+21/-24</a>&nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td><strong>BibliographyConsistencyCheckTest.java</strong><dd><code>Comprehensive tests for custom entry types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-94f45121c423b4c0c7571ccb76a7f40e23bcef1b6966003bbdf6d1a1d4f7cb75">+303/-10</a></td>

</tr>

<tr>
  <td><strong>BibliographyConsistencyCheckResultCsvWriterTest.java</strong><dd><code>Updated CSV writer tests with required fields</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-641c831afa366f64368ec5c237c128d3fd3506f92ecc2c4d4a8125e23219849d">+15/-5</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>BibliographyConsistencyCheckResultTxtWriterTest.java</strong><dd><code>Updated TXT writer tests with required fields</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-cb76678982120b769f5f34382d893e82ab46e4805abde542736d5ec26e891c92">+20/-8</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
  <td><strong>ConsistencyCheckAction.java</strong><dd><code>Pass BibEntryTypesManager to consistency check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-1b46713ccfa86a11ee5ea9a4e03b335425b8e5a8981b26fdb5bfb1fc32b3c544">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>ConsistencyCheckDialogViewModel.java</strong><dd><code>Use display name for entry types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-73f06a1d153250b9083a1877c40a7e8e4d5fac4c9b3fb66becfbd739bc6aa674">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>JabRefGUI.java</strong><dd><code>Initialize LanguageServerController with entry types manager</code></dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-cc1abdac0d023898dff67c651cc28d6f97e79a018e49624deb463cba929388f7">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>CheckConsistency.java</strong><dd><code>Pass BibEntryTypesManager to consistency check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-d3050a72d09ad6b3c585cb60f5d8e92bb6b9d7539ff23103b86c8c01391e247c">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>LspClientHandler.java</strong><dd><code>Accept BibEntryTypesManager in constructor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-7ae491a6a1f24b0b04fa1391e3af8bcab1323fad97acfa2fb2698e36817e1cf6">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>LspLauncher.java</strong><dd><code>Thread LSP launcher with entry types manager</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-64b11223427c56145fb19b9d9f5726d5701fdd4cb030f465631704d4b218f5f5">+6/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>LanguageServerController.java</strong><dd><code>Store and propagate BibEntryTypesManager</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-aed4e8ecebf2424316c532f69e05222b9fb6b14d89b18a78e6dbc4e05a2c97c1">+5/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>LspConsistencyCheck.java</strong><dd><code>Accept BibEntryTypesManager parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-c110a4b72509335ad7887b409cde4794a3d04d1011494ae242c7f7d0f1a1c492">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>LspDiagnosticHandler.java</strong><dd><code>Store and use BibEntryTypesManager for diagnostics</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-b8765e6206a63ea0851b6223f4128dca3fe64fd0c78c41a84ebe3bb93ccc4700">+5/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td><strong>CHANGELOG.md</strong><dd><code>Document consistency check enhancements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/JabRef/jabref/pull/14257/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr></tbody></table>

</details>

___

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please ensure the automatic check are green, otherwise no human will review it

**Comment by Hrishi-Baskaran** [comment]
> Please ensure the automatic check are green, otherwise no human will review it

Thanks for telling me about this. I will update this on Friday.

File: jabgui/src/main/java/org/jabref/gui/consistency/ConsistencyCheckAction.java [hunk 1]
```diff
@@ -31,6 +32,7 @@ public class ConsistencyCheckAction extends SimpleCommand {
     private final GuiPreferences preferences;
     private final BibEntryTypesManager entryTypesManager;
     private final UiTaskExecutor taskExecutor;
+    @Inject private BibEntryTypesManager bibEntryTypesManager;
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/consistency/ConsistencyCheckAction.java]: We don't inject - we pass by constructor

File: jabkit/src/main/java/org/jabref/toolkit/cli/CheckConsistency.java [hunk 2]
```diff
@@ -65,7 +66,7 @@ public Integer call() {
         BibDatabaseContext databaseContext = parserResult.get().getDatabaseContext();
 
         BibliographyConsistencyCheck consistencyCheck = new BibliographyConsistencyCheck();
-        BibliographyConsistencyCheck.Result result = consistencyCheck.check(databaseContext, (count, total) -> {
+        BibliographyConsistencyCheck.Result result = consistencyCheck.check(databaseContext, new BibEntryTypesManager(), (count, total) -> {
```
Comment (koppor) [inline jabkit/src/main/java/org/jabref/toolkit/cli/CheckConsistency.java]: Refactor this as variable to follow the style of Jabef

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java [hunk 3]
```diff
@@ -102,22 +101,17 @@ public record EntryTypeResult(Collection<Field> fields, SequencedCollection<BibE
      *
      * @implNote This class does not implement {@link org.jabref.logic.integrity.DatabaseChecker}, because it returns a list of {@link org.jabref.logic.integrity.IntegrityMessage}, which are too fine-grained.
      */
-    public Result check(BibDatabaseContext bibContext, BiConsumer<Integer, Integer> entriesGroupingProgress) {
+    public Result check(BibDatabaseContext bibContext, BibEntryTypesManager bibEntryTypesManager, BiConsumer<Integer, Integer> entriesGroupingProgress) {
         // collects fields existing in any entry, scoped by entry type
         Map<EntryType, Set<Field>> entryTypeToFieldsInAnyEntryMap = new HashMap<>();
-        // collects fields existing in all entries, scoped by entry type
+        // collects fields existing in all entries, scoped by entry typed
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: Typo - please undo

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultCsvWriterTest.java [hunk 4]
```diff
@@ -42,7 +43,7 @@ void checkSimpleLibrary(@TempDir Path tempDir) throws IOException {
         database.insertEntry(second);
 
         BibDatabaseContext bibContext = new BibDatabaseContext(database);
-        BibliographyConsistencyCheck.Result result = new BibliographyConsistencyCheck().check(bibContext, (count, total) -> {
+        BibliographyConsistencyCheck.Result result = new BibliographyConsistencyCheck().check(bibContext, new BibEntryTypesManager(), (count, total) -> {
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultCsvWriterTest.java]: Make this a variable in the test - and reuse it.

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java [hunk 5]
```diff
@@ -9,20 +9,30 @@
...
 
 import static org.junit.jupiter.api.Assertions.assertEquals;
 
 class BibliographyConsistencyCheckTest {
 
+    private BibEntryTypesManager entryTypesManager;
+
+    @BeforeEach
+    void setUp() {
+        // TODO: add some custom entry types for this manager and test with it
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: Yes, please :) - The issue description at https://github.com/JabRef/jabref/issues/13794 should provide you with one.

File: jabgui/src/main/java/org/jabref/gui/consistency/ConsistencyCheckAction.java (hunk 1 above)
Comment (Hrishi-Baskaran) [reply jabgui/src/main/java/org/jabref/gui/consistency/ConsistencyCheckAction.java]: update:
https://github.com/JabRef/jabref/pull/14257/files#diff-1b46713ccfa86a11ee5ea9a4e03b335425b8e5a8981b26fdb5bfb1fc32b3c544L32

File: jabkit/src/main/java/org/jabref/toolkit/cli/CheckConsistency.java (hunk 2 above)
Comment (Hrishi-Baskaran) [reply jabkit/src/main/java/org/jabref/toolkit/cli/CheckConsistency.java]: view update:
https://github.com/JabRef/jabref/pull/14257/files#diff-d3050a72d09ad6b3c585cb60f5d8e92bb6b9d7539ff23103b86c8c01391e247cR69-R70

Also just curious: should I be constructing a new BibEntryTypesManager here like I've done? This basically prevents the user from using custom types when using the cli consistency check. How might we let users specify a entry types manager from the cli? Or maybe I'm missing something and this isn't what we want to do.

File: jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java (hunk 3 above)
Comment (Hrishi-Baskaran) [reply jablib/src/main/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheck.java]: update:
https://github.com/JabRef/jabref/pull/14257/files#diff-72370ff3854216f72af92bd9037b16ec26257efb4fc057a596ab1d5b79427bacL108

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java (hunk 5 above)
Comment (Hrishi-Baskaran) [reply jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: added two new unit tests:
https://github.com/JabRef/jabref/pull/14257/files#diff-94f45121c423b4c0c7571ccb76a7f40e23bcef1b6966003bbdf6d1a1d4f7cb75R33-R135

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultCsvWriterTest.java (hunk 4 above)
Comment (Hrishi-Baskaran) [reply jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultCsvWriterTest.java]: update:
https://github.com/JabRef/jabref/pull/14257/files#diff-641c831afa366f64368ec5c237c128d3fd3506f92ecc2c4d4a8125e23219849dR39-R62

I also made the mocked BibEntryTypesManager for this test file have some custom and unknown types (similar to what I did for BibliographyConsistencyCheckTest.java). But for this file, I don't use the custom and unknown types. Should I add some unit tests that use these, or remove these types for the mocked BibEntryTypesManager of the CSV test file?

File: jabls/src/main/java/org/jabref/languageserver/util/LspDiagnosticHandler.java [hunk 6]
```diff
@@ -88,7 +89,7 @@ private List<Diagnostic> computeDiagnostics(String content, String uri) {
         }
 
         if (clientHandler.getSettings().isConsistencyCheck()) {
-            consistencyDiagnosticsCache.put(uri, lspConsistencyCheck.check(parserResult));
```
Comment (koppor) [inline jabls/src/main/java/org/jabref/languageserver/util/LspDiagnosticHandler.java:91]: Should be passed via constructor

**Comment by Hrishi-Baskaran** [comment]
Hello I'm very sorry about being inactive. I was going through a lot of other work I had to do and was planning on contributing again this weekend. Would it be possible to re-open this PR?

File: jabkit/src/main/java/org/jabref/toolkit/commands/CheckConsistency.java [hunk 7]
```diff
@@ -65,7 +66,8 @@ public Integer call() {
         BibDatabaseContext databaseContext = parserResult.get().getDatabaseContext();
 
         BibliographyConsistencyCheck consistencyCheck = new BibliographyConsistencyCheck();
-        BibliographyConsistencyCheck.Result result = consistencyCheck.check(databaseContext, (count, total) -> {
+        BibEntryTypesManager bibEntryTypesManager = new BibEntryTypesManager();
```
Comment (koppor) [inline jabkit/src/main/java/org/jabref/toolkit/commands/CheckConsistency.java]: No - pass this via constructor. See for instance `org.jabref.gui.frame.SendAsStandardEmailAction#SendAsStandardEmailAction`.

File: jabls/src/main/java/org/jabref/languageserver/util/LspDiagnosticHandler.java [hunk 8]
```diff
@@ -88,7 +89,8 @@ private List<Diagnostic> computeDiagnostics(String content, String uri) {
...
+            BibEntryTypesManager bibEntryTypesManager = new BibEntryTypesManager();
```
Comment (koppor) [inline jabls/src/main/java/org/jabref/languageserver/util/LspDiagnosticHandler.java]: bibEntryTypesManager should be passed via the constructor.

Comment (Hrishi-Baskaran) [reply jabls/src/main/java/org/jabref/languageserver/util/LspDiagnosticHandler.java]: This should be handled now

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultCsvWriterTest.java [hunk 9]
```diff
@@ -27,8 +36,30 @@
 
 class BibliographyConsistencyCheckResultCsvWriterTest {
 
+    private static final EntryType UNKNOWN_TYPE = new UnknownEntryType("unknownType");
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckResultCsvWriterTest.java]: This is an unused variable. Remove it.

File: jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java [hunk 10]
```diff
@@ -9,20 +9,130 @@
...
 
+import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
 import org.junit.jupiter.api.io.TempDir;
 
 import static org.junit.jupiter.api.Assertions.assertEquals;
 
 class BibliographyConsistencyCheckTest {
 
+    private static final EntryType UNKNOWN_TYPE = new UnknownEntryType("unknownType");
```
Comment (koppor) [inline jablib/src/test/java/org/jabref/logic/quality/consistency/BibliographyConsistencyCheckTest.java]: This is an unused variable. Remove it.

Side track: It would be a "brainfuck" to make a type known which says by itself "unkown".

The custom type is better

**Comment by koppor** [comment]
@Hrishi-Baskaran Thank you for coming back and working on this.

Question: Why did you not add a test case for the bib entry given in the issue description?

image

Reason: It would be good to have a test case for a real world example. DBLP is a very large bib data provider.

**Comment by Hrishi-Baskaran** [comment]
@koppor excellent suggestion to recommend using the example in the issue description. That idea just went over my mind. I just have a question about how to implement it.

It seems like to simulate the example, I need to add a new `BibEntryType` with type `StandardEntryType.Article` with custom `BibField`s for `biburl` and `bibsource`. This will create an overwritten article type to match that in the issue description. My problem is that I'm unsure about which type to use for the `field` property of the custom `BibField`s.

I think that `org.jabref.model.entry.field.UnknownField` is a good candidate. But I hesitate because of its name. I was expecting something named "CustomField," or similar. Would you reccommend I use `UnknownField` for biburl and bibsource?

**Comment by koppor** [comment]
> I think that `org.jabref.model.entry.field.UnknownField` is a good candidate. But I hesitate because of its name. I was expecting something named "CustomField," or similar. Would you reccommend I use `UnknownField` for biburl and bibsource?

Yes, please `UnknownField`.

**Comment by Hrishi-Baskaran** [comment]
Thanks for fixing those remaining conflicts and merging the PR, you were such a great help during the entire process. I'll be ready to take on any user report issues about this, so please keep me in the loop.
