### PR TITLE
Searching with Postgres

### LINKED ISSUE #10490: Quick search by first author name within the library  using "^"
It would be very helpful to have a feature that allows to quickly search by first author name (or CitationKey).
That would help especially for large libraries, as the current standard search scans all the available information and can be slow.

For example in ADS (https://ui.adsabs.harvard.edu/) one can do it by using the `^` symbol before the first author name.

image

### LINKED ISSUE #11798: search for key does not always work
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.16--2024-09-17--ed0e90e Linux 6.10.10-200.fc40.x86_64 amd64  Java 21.0.2  JavaFX 23+29

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Given a library that contains inter alia entries with the keys  `Law:2009The` and `acker1990hierarchies`

I am puzzled:

1. search for `Law:2009The`
2. does not deliver results

However

1. search for `acker1990hierarchies` 
2. does deliver results

why is that?

### Appendix

_No response_

### LINKED ISSUE #11823: Unexpected behaviour of the new search feature
### JabRef version

JabRef 5.16--2024-09-20--5ac788c

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint/Debian

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open database with an entry A containing the string "xyz-abc" (choose as appropriate)
2. Search for _xyz AND abc_
3. Entry A does not appear in the results although it should (it did before the search feature update).
4. Entry A will appear in the search results when using _xyz abc_ (which in Lucene implies an OR used).

Hope anybody can reproduce this issue. I found the issue when looking for strings in the "comments" field but I tested that the issue should occur with the title field and perhaps other fields as well. **The issue does not occur when using "xyz abc", so it seems the new search now expects strings to occur as substrings in separate words.** I'm using search groups a lot and found that behavior today only because some entries where missing after the search-group migration.

**Update:** It also seems that the new search **does not recognise** string occurrences in the **keywords** anymore.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by LoayGhreeb**
Closes #11823
Closes #11798
Closes #10490

Resolves https://discourse.jabref.org/t/citations-missing-in-action-in-jabref-5-16/4525/11

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by InAnYan** [comment]
I have couple of questions:

1. Is the Postgres **server** one for every library?
2. One library - one **DB**?
3. What is the schema of the DB? If you can explain it shortly.
4. Where the Postgres data is stored? (Somwhere local to user, alongside BIB)

I was thinking if I can use this Postgres service as a vector database for my AI features

File: src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java [hunk 1]
```diff
@@ -0,0 +1,209 @@
...
+
+    public void updateOnStart(BackgroundTask<?> task) {
+        addToIndex(databaseContext.getDatabase().getEntries(), task);
+    }
+
+    public void addToIndex(Collection<BibEntry> entries, BackgroundTask<?> task) {
+        task.setTitle(Localization.lang("Indexing bib fields for %0", libraryName));
+        int i = 1;
+        long startTime = System.currentTimeMillis();
+        LOGGER.debug("Adding {} entries to index", entries.size());
```
Comment (InAnYan) [inline src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java:90]: When I was working on my AI features, we used file(s) for each mention of linked files.

Maybe in your case it can be entry(ies)?

File: src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java [hunk 2]
```diff
@@ -0,0 +1,209 @@
...
+
+    public void close() {
+        HeadlessExecutorService.INSTANCE.execute(this::closeIndex);
+    }
+
+    public void closeAndWait() {
+        HeadlessExecutorService.INSTANCE.executeAndWait(this::closeIndex);
+    }
+
+    private void closeIndex() {
```
Comment (InAnYan) [inline src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java:198]: How does this method work?

Does it mean that any time I exit JabRef, all indexes are deleted. And when I open JabRef again, I reindex the library again?

File: external-libraries.md [hunk 3]
```diff
@@ -699,8 +706,12 @@ License: BSD-3-Clause
 3. (on WSL) `sed 's/[^a-z]*//' < build/reports/project/dependencies.txt | sed "s/\(.*\) .*/\1/" | grep -v "\->" | sort | uniq > build/dependencies-for-external-libraries.txt`
 
 ```text
+ai.djl.huggingface:tokenizers:0.29.0
```
Comment (koppor) [inline external-libraries.md:709]: please add all of them above or do not commit this part of the file...

File: src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java (hunk 1 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java:90]: > Maybe in your case it can be entry(ies)?

This gets a little inconvenient to read, but nitpick - it's debug log anyway so both work, if you want to go with strict uniformity.

File: src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java (hunk 2 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java:198]: Yes. Currently for the prototype.

Maybe, it was because of unique ids etc.

Maybe, index needs only to be rebuild if .bib file changed on disk during non-usage of JabRef. (e.g., a user has used notepad++ to modify it)

File: src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/search/indexing/PostgreIndexer.java:90]: > This gets a little inconvenient to read, but nitpick

We decided for that to enable more easy covering of Arabic... Full Arabic is hard. See https://phrase.com/blog/posts/pluralization/

---


    zero → “لم نزرع أي شجرة حتى الآن”
    one → “لقد زرعنا شجرة ١ حتى الآن”
    two → “لقد زرعنا شجرتين ٢ حتى الآن”
    few → “لقد زرعنا ٣ شجرات حتى الآن”
    many → “لقد زرعنا ١١ شجرة حتى الآن”
    other → “لقد زرعنا ١٠٠ شجرة حتى الآن”

---

File: external-libraries.md (hunk 3 above)
Comment (koppor) [reply external-libraries.md]: I fixed it.

**Comment by koppor** [comment]
> I have couple of questions:
> 
>     1. Is the Postgres **server** one for every library?

1 for running JabRef

>     2. One library - one **DB**?

One table per library. We kept it very simple for the search.

>     3. What is the schema of the DB? If you can explain it shortly.

Very simple - just one table

                    CREATE TABLE IF NOT EXISTS "%s" (
                        %s TEXT NOT NULL,
                        %s TEXT NOT NULL,
                        %s TEXT,
                        PRIMARY KEY (%s, %s)
                    )
                    """.formatted(tableName,
                    PostgreConstants.ENTRY_ID,
                    PostgreConstants.FIELD_NAME,
                    PostgreConstants.FIELD_VALUE,
                    PostgreConstants.ENTRY_ID,
                    PostgreConstants.FIELD_NAME));

Feel free to create other tables :)

>     4. Where the Postgres data is stored? (Somwhere local to user, alongside BIB)

In the AppData directory. Even "temp". Thus, very fragile ^^. Not sure if one can change it.

Reason for the fragile setting: The solution we are using is intended for **testing**. The java-german channel said: WTF, please use DuckDB. But we could not manage to get DuckDB up and running that fast. Moreover, Postgres has more plugins for speed. And third, we also support Postgres for remote storage.

You could also think of hooking into the remote postgres. Meaning: Advanced features only work with a remote postgres. (Although I like using the local postgres database. Keeps complexity for the user to a minimum. Only 500 MB additional storage is needed...)

**Comment by InAnYan** [comment]
@LoayGhreeb, hi! Chris has found a problem with my AI functionality, when a new instance of JabRef is opened when another is running (https://github.com/JabRef/jabref-issue-melting-pot/issues/575, also https://github.com/JabRef/jabref/pull/11844#pullrequestreview-2335402508).

The reason of this problem, is that we used MVStore as an "embedded database", and it doesn't allow to open two MVStores on the same file.

I was wondering, will your search functionality work correctly if there are two or more JabRef instances running?

And if it will work, then how? Will they use the same DB or different?

**Comment by LoayGhreeb** [comment]
> I was wondering, will your search functionality work correctly if there are two or more JabRef instances running?
> 
> And if it will work, then how? Will they use the same DB or different?

It will work because each instance creates a new embedded Postgres server with a different port (see [EmbeddedPostgres#detectPort](https://github.com/zonkyio/embedded-postgres/blob/2f830bf48e7fc894bbfc2451212701704bfe6ebc/src/main/java/io/zonky/test/db/postgres/embedded/EmbeddedPostgres.java#L220-L231)).
I think if a local server is used, one option is to create a new database for each instance but will require an identifier for each instance to be used as the database name. Alternatively, the same database can be used, with each library attempting to create a table, if table creation fails, a number can be appended (e.g., libraryName + i) and retry until successful.

I had a similar issue before with Lucene. The bib fields index is stored in memory because it had to be rebuilt each time, so having multiple instances isn't a problem, but the linked files index is stored on disk and will be used in read-only mode if another instance opens the same library. In this case, the index is used only for searching and doesn’t allow updates.

**Comment by InAnYan** [comment]
@LoayGhreeb thanks for answer!

Can I ask one more question? Is it possible to save DB information to disk and restore it later?

**Comment by LoayGhreeb** [comment]
> Is it possible to save DB information to disk and restore it later?

Yes, you can. You can set the data directory during server setup using [EmbeddedPostgres#setDataDirectory](https://github.com/zonkyio/embedded-postgres/blob/2f830bf48e7fc894bbfc2451212701704bfe6ebc/src/main/java/io/zonky/test/db/postgres/embedded/EmbeddedPostgres.java#L522), and disable data directory cleaning by setting [EmbeddedPostgres#setCleanDataDirectory](https://github.com/zonkyio/embedded-postgres/blob/2f830bf48e7fc894bbfc2451212701704bfe6ebc/src/main/java/io/zonky/test/db/postgres/embedded/EmbeddedPostgres.java#L517) to `false`.

File: src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java [hunk 4]
```diff
@@ -24,11 +23,17 @@ public class SearchGroupsMigrationAction implements GUIPostOpenAction {
     // We cannot have this constant in `Version.java` because of recursion errors
     // Thus, we keep it here, because it is (currently) used only in the context of groups migration.
     public static final Version VERSION_6_0_ALPHA = Version.parse("6.0-alpha");
+    public static final Version VERSION_6_0_ALPHA_1 = Version.parse("6.0-alpha_1");
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java:26]: there has been no alpha release yet, its all just CI build yet. So i doubt its correct to introduce another ALPHA iteration step here... @koppor ?

Comment (LoayGhreeb) [reply src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java:26]: We kept the old version and introduced a new one to ask users who tested the alpha version and migrated their search syntax to Lucene to revert to their backup, as there is no migration from Lucene back to the old syntax.

Comment (calixtus) [reply src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java:26]: ok i see. But we should do this now for our power users but remove / streamline it before the real alpha release or so. Otherweise everything will be overpolluted with these horrible migration heuristics

File: src/main/resources/l10n/JabRef_en.properties [hunk 5]
```diff
@@ -271,6 +271,7 @@ Each\ line\ must\ be\ of\ the\ following\ form\:\ \'tab\:field1;field2;...;field
 
 Search\ groups\ migration\ of\ %0=Search groups migration of %0
 The\ search\ groups\ syntax\ is\ outdated.\ Do\ you\ want\ to\ migrate\ to\ the\ new\ syntax?=The search groups syntax is outdated. Do you want to migrate to the new syntax?
+The\ search\ groups\ syntax\ has\ been\ reverted\ to\ the\ old\ one.\ Please\ use\ the\ backup\ you\ made\ before\ migrating\ to\ 6.0-alpha. = The search groups syntax has been reverted to the old one. Please use the backup you made before migrating to 6.0-alpha.
```
Comment (koppor) [inline src/main/resources/l10n/JabRef_en.properties:274]: No need for translation. We will remove this after 6.0 release. It is OK to have it untranslated in JabRef.

File: src/main/java/org/jabref/model/search/query/SearchQuery.java [hunk 6]
```diff
@@ -148,14 +124,12 @@ public EnumSet<SearchFlags> getSearchFlags() {
...
-            return Collections.singletonList(query);
+            return Collections.singletonList(searchExpression);
         }
         if (!isValid()) {
             return List.of();
         }
-        return Arrays.stream(QueryTermExtractor.getTerms(parsedQuery))
-                     .map(WeightedTerm::getTerm)
-                     .toList();
+        return List.of();
```
Comment (koppor) [inline src/main/java/org/jabref/model/search/query/SearchQuery.java:132]: Is the whole method needed? If it always returns the empty list, it can be removed?

File: src/main/java/org/jabref/model/entry/field/FieldFactory.java [hunk 7]
```diff
@@ -55,7 +55,7 @@ public static String serializeOrFieldsList(Set<OrFields> fields) {
      * Checks whether the given field contains LaTeX code or something else
      */
     public static boolean isLatexField(Field field) {
-        return Collections.disjoint(field.getProperties(), Set.of(FieldProperty.VERBATIM, FieldProperty.MARKDOWN));
```
Comment (koppor) [inline src/main/java/org/jabref/model/entry/field/FieldFactory.java:58]: Please also add `SINGLE_ENTR_LINK`.

File: src/main/java/org/jabref/model/entry/BibEntry.java [hunk 8]
```diff
@@ -483,6 +483,7 @@ public Optional<String> getFieldLatexFree(Field field) {
         } else {
             Optional<String> fieldValue = getField(field);
             if (fieldValue.isPresent()) {
+                // TODO: To we need FieldFactory.isLaTeXField(field) here to filter?
```
Comment (koppor) [inline src/main/java/org/jabref/model/entry/BibEntry.java:486]:
```suggestion
                // TODO: Do we need FieldFactory.isLaTeXField(field) here to filter?
```

File: src/main/java/org/jabref/logic/search/SearchPreferences.java [hunk 9]
```diff
@@ -11,6 +11,7 @@
 import javafx.collections.FXCollections;
 import javafx.collections.ObservableSet;
 
+import org.jabref.model.search.SearchDisplayMode;
```
Comment (koppor) [inline src/main/java/org/jabref/logic/search/SearchPreferences.java:14]: This import is unnecessary?

File: src/main/java/org/jabref/gui/preferences/table/TableTabViewModel.java [hunk 10]
```diff
@@ -123,7 +123,6 @@ public void setValues() {
 
         availableColumnsProperty.clear();
         availableColumnsProperty.addAll(
-                new MainTableColumnModel(MainTableColumnModel.Type.MATCH_SCORE),
```
Comment (koppor) [inline src/main/java/org/jabref/gui/preferences/table/TableTabViewModel.java:126]: Its a bit a pity that we loose this uncertain matches. But OK to loose if we get matches at all 🤣🤣. -- Maybe also worth noting in the report and/or blog post.

File: src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java (hunk 4 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java:26]: Will be streamlined in the beta version. If the format is kept, we will rewrite `6.0-alpha_1`to `6.0-beta` in the beta version and to `6.0` in the final release and drop reading capabilities for `-alpha_1`.

**Comment by calixtus** [comment]
Well, we did not even release aloha, why are we already talking about beta, if the it will be a feature of the alpha release?

**Comment by koppor** [comment]
> Well, we did not even release aloha, why are we already talking about beta, if the it will be a feature of the alpha release?

Because Software Engineering also discusses the future - and imagines the different cases in the future.  😅

**Comment by xiaojie2008** [comment]
@LoayGhreeb @koppor Hello,

I was just assigned to work on Issue #11428: "Auto-Completion in search bar not working until switching tabs" last night. I noticed that the search functionality is currently being refactored (Issue #11803). In this context, should I continue addressing Issue #11428, or will the refactoring resolve the auto-completion problem once completed?

Thank you for your guidance!

**Comment by LoayGhreeb** [comment]
> I was just assigned to work on Issue #11428: "Auto-Completion in search bar not working until switching tabs" last night. I noticed that the search functionality is currently being refactored (Issue #11803). In this context, should I continue addressing Issue #11428, or will the refactoring resolve the auto-completion problem once completed?
> 
> Thank you for your guidance!

You can continue working on #11428. This PR won’t affect the auto-completion classes, so you should be able to address the issue without any conflicts.

**Comment by xiaojie2008** [comment]
> > I was just assigned to work on Issue #11428: "Auto-Completion in search bar not working until switching tabs" last night. I noticed that the search functionality is currently being refactored (Issue #11803). In this context, should I continue addressing Issue #11428, or will the refactoring resolve the auto-completion problem once completed?
> > Thank you for your guidance!
> 
> You can continue working on #11428. This PR won’t affect the auto-completion classes, so you should be able to address the issue without any conflicts.

Thank you for your response. I will continue working on #11428 based on JabRef version 5.13 without pulling in the code from #11803, since you mentioned that this PR does not impact the auto-completion functionality. This allows me to focus on addressing the current auto-completion issue without introducing unnecessary complexity or potential conflicts by pulling a draft PR. If there are any updates or if you need me to test anything on the newer version, please let me know.

File: src/main/java/org/jabref/gui/entryeditor/SourceTab.java [hunk 11]
```diff
@@ -233,7 +217,12 @@ private void updateCodeArea() {
 
             codeArea.clear();
             try {
-                codeArea.appendText(getSourceString(currentEntry, mode, fieldPreferences));
+                String sourceText = getSourceString(currentEntry, mode, fieldPreferences);
+                LOGGER.info("sourceText length: {}", sourceText.length());
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/entryeditor/SourceTab.java:221]: make this debug, info is too much noise

Comment (LoayGhreeb) [reply src/main/java/org/jabref/gui/entryeditor/SourceTab.java:221]: I will change it, it was only for debugging

File: src/test/java/org/jabref/logic/search/query/LuceneQueryParserTest.java [hunk 12]
```diff
@@ -1,40 +0,0 @@
...
-        return Stream.of(
-                // unicode
-                Arguments.of("any:preissinger", "preißinger"),
-                Arguments.of("any:jesus", "jesús"),
-                Arguments.of("any:breitenbucher", "breitenbücher"),
-
-                // latex
-                Arguments.of("any:preissinger", "\"prei{\\\\ss}inger\""),
-                Arguments.of("any:jesus", "\"jes{\\\\'{u}}s\""),
-                Arguments.of("any:breitenbucher", "\"breitenb{\\\\\\\"{u}}cher\""),
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/LuceneQueryParserTest.java]: We should move these tests to somewhere else. Didn't find that in the new code.

Test cases should use `Lübeck` as test. (City name in Germany).

Lübeck, Lubeck, Luebeck, L\"{u}beck

File: src/test/java/org/jabref/logic/search/query/SearchQueryExtractorConversionTest.java [hunk 13]
```diff
@@ -0,0 +1,37 @@
...
+import org.junit.jupiter.params.provider.MethodSource;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+public class SearchQueryExtractorConversionTest {
+    public static Stream<Arguments> testSearchConversion() {
+        return Stream.of(
+                Arguments.of(Set.of("term"), "term"),
+                Arguments.of(Set.of("regex.*term"), "regex.*term"),
+                Arguments.of(Set.of("term"), "any = term"),
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryExtractorConversionTest.java:19]: According to https://docs.jabref.org/finding-sorting-and-cleaning-entries/search#pseudo-fields, it is `anyfield`, not just `any`. I think, we shoud keep `anyfield`. At least as synonym.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java [hunk 14]
```diff
@@ -10,64 +12,55 @@
...
+                Arguments.of("(-content:/.+/) (-annotations:/.+/)", "any !=~ .+"),
+                Arguments.of("(-content:/.+/) (-annotations:/.+/)", "groups !=~ .+ AND any !=~ .+")
         );
     }
 
     @ParameterizedTest
     @MethodSource
-    void transformationRegularExpression(String expected, String query) {
-        String result = SearchQueryConversion.searchToLucene(query);
+    void testSearchConversion(String expected, String searchExpression) {
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java:62]: No test names should begin with `test`. - https://docs.openrewrite.org/recipes/java/testing/cleanup/removetestprefix -- I am not sure why OpenRewrite didn't catch this.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java [hunk 15]
```diff
@@ -10,64 +12,55 @@
 
 class SearchQueryLuceneConversionTest {
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java:13]: Is this really lucene? Isn't it Postgres?

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java [hunk 16]
```diff
@@ -10,64 +12,55 @@
...
-                Arguments.of("any:chocolate", "chocolate"),
+                Arguments.of("content:term annotations:term", "term"),
+                Arguments.of("content:term annotations:term", "any = term"),
+                Arguments.of("content:term annotations:term", "any CONTAINS term"),
+                Arguments.of("content:term annotations:term", "any MATCHES term"),
+                Arguments.of("content:term annotations:term", "any =! term"),
+                Arguments.of("content:term annotations:term", "any == term"),
+                Arguments.of("content:term annotations:term", "any ==! term"),
 
-                Arguments.of("title:chocolate", "title=chocolate"),
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: I am better in reading concrete names. I somehow miss these basic tests in the new code. (image proceccsing below as kept, but not these ones)

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java [hunk 17]
```diff
@@ -10,64 +12,55 @@
...
 
-                // not converted, because wrong syntax for JabRef 5.x
-                // Arguments.of("( author:miller OR title:\"image processing\" OR keywords:\"image processing\" ) AND NOT author:brown AND NOT author:blue", "(author = miller or title|keywords = \"image processing\") and not author = brown and != author = blue"),
+                Arguments.of("(-content:term) (-annotations:term)", "any != term"),
+                Arguments.of("(-content:term) (-annotations:term)", "any !== term"),
+                Arguments.of("(-content:term) (-annotations:term)", "any !=! term"),
+                Arguments.of("(-content:\"two term\") (-annotations:\"two term\")", "any != \"two terms\""),
+                Arguments.of("+(-content:imag) +(-annotations:process)", "content != image AND annotations != processing"),
 
-                // String with a space
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: You can keep this comment, because it is not that easy to read the intention of these group of tests.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java [hunk 18]
```diff
@@ -10,64 +12,55 @@
...
-                Arguments.of("title:image\\ processing AND author:smith", "title = \"image processing\" AND author= smith"),
+                Arguments.of("MatchNoDocsQuery(\"\")", "title = image"),
+                Arguments.of("content:\"imag process\" annotations:\"imag process\"", "\"image processing\" AND author = smith"),
+                Arguments.of("+(content:imag annotations:imag) +(content:process annotations:process)", "image AND (title = term OR processing)"),
+                Arguments.of("(content:imag annotations:imag) (content:process annotations:process)", "image OR (title = term OR processing)"),
+                Arguments.of("MatchNoDocsQuery(\"\")", "title = \"image processing\" AND author = smith"),
 
-                // We renamed fields
-                Arguments.of("any:somecontent", "anyfield = somecontent"),
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: This should be kept? -- Not sure about the current state of discussion `any` versus `anyfield`.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java [hunk 19]
```diff
@@ -10,64 +12,55 @@
...
-    @ParameterizedTest
-    @MethodSource
-    void transformationNormal(String expected, String query) {
-        String result = SearchQueryConversion.searchToLucene(query);
-        assertEquals(expected, result);
-    }
-
-    public static Stream<Arguments> transformationRegularExpression() {
-        return Stream.of(
-                Arguments.of("any:* AND -groups:/.+/", "groups != .+"),
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: Can this test be kept somehouw? I think, it checks for set groups, which is an impotant use case.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java [hunk 20]
```diff
@@ -10,64 +12,55 @@
...
-                Arguments.of("( any:* AND -groups:/.+/ ) AND ( any:* AND -readstatus:/.+/ )", "groups != .+ and readstatus != .+"),
```
Comment (koppor) [inline src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: This should also be kept: non-empty group and set read-status

File: src/main/resources/l10n/JabRef_en.properties [hunk 21]
```diff
@@ -810,14 +808,15 @@ Character\ encoding\ '%0'\ is\ not\ supported.=Character encoding '%0' is not su
...
-Match\ score=Match score
 Scroll\ to\ previous\ match\ category=Scroll to previous match category
 Scroll\ to\ next\ match\ category=Scroll to next match category
 Search=Search
 Search...=Search...
 Searching...=Searching...
 Finished\ Searching=Finished Searching
 Search\ expression=Search expression
+This\ only\ affects\ unfielded\ terms.\ For\ using\ RegEx\ in\ a\ fielded\ term,\ use\ \=~\ operator=This only affects unfielded terms. For using RegEx in a fielded term, use =~ operator
+This\ only\ affects\ unfielded\ terms.\ For\ using\ case-sensitive\ in\ a\ fielded\ term,\ use\ \=!\ operator=This only affects unfielded terms. For using case-sensitive in a fielded term, use =! operator
```
Comment (LoayGhreeb) [inline src/main/resources/l10n/JabRef_en.properties:819]:
```suggestion
This\ only\ affects\ unfielded\ terms.\ For\ using\ RegEx\ in\ a\ fielded\ term,\ use\ \=~\ operator=This only affects unfielded terms. For using RegEx in a fielded term, use =~ operator.
This\ only\ affects\ unfielded\ terms.\ For\ using\ case-sensitive\ in\ a\ fielded\ term,\ use\ \=!\ operator=This only affects unfielded terms. For using case-sensitive in a fielded term, use =! operator.
```

File: src/main/resources/l10n/JabRef_en.properties [hunk 22]
```diff
@@ -844,7 +843,7 @@ Clear\ search=Clear search
 Search\ document\ identifier\ online=Search document identifier online
 Search\ for\ unlinked\ local\ files=Search for unlinked local files
 Search\ full\ text\ documents\ online=Search full text documents online
-Hint\:\n\nTo\ search\ all\ fields\ for\ <b>Smith</b>,\ enter\:\n<tt>smith</tt>\n\nTo\ search\ the\ field\ <b>author</b>\ for\ <b>Smith</b>\ and\ the\ field\ <b>title</b>\ for\ <b>electrical</b>,\ enter\:\n<tt>author\:Smith\ AND\ title\:electrical</tt>=Hint:\n\nTo search all fields for <b>Smith</b>, enter:\n<tt>smith</tt>\n\nTo search the field <b>author</b> for <b>Smith</b> and the field <b>title</b> for <b>electrical</b>, enter:\n<tt>author:Smith AND title:electrical</tt>
+Hint\:\n\nTo\ search\ all\ fields\ for\ <b>Smith</b>,\ enter\:\n<tt>smith</tt>\n\nTo\ search\ the\ field\ <b>author</b>\ for\ <b>Smith</b>\ and\ the\ field\ <b>title</b>\ for\ <b>electrical</b>,\ enter\:\n<tt>author\=\ Smith\ AND\ title\=\ electrical</tt>=Hint:\n\nTo search all fields for <b>Smith</b>, enter:\n<tt>smith</tt>\n\nTo search the field <b>author</b> for <b>Smith</b> and the field <b>title</b> for <b>electrical</b>, enter:\n<tt>author= Smith AND title= electrical</tt>
```
Comment (LoayGhreeb) [inline src/main/resources/l10n/JabRef_en.properties:846]:
```suggestion
Hint\:\n\nTo\ search\ all\ fields\ for\ <b>Smith</b>,\ enter\:\n<tt>smith</tt>\n\nTo\ search\ the\ field\ <b>author</b>\ for\ <b>Smith</b>\ and\ the\ field\ <b>title</b>\ for\ <b>electrical</b>,\ enter\:\n<tt>author\=Smith\ AND\ title\=electrical</tt>=Hint:\n\nTo search all fields for <b>Smith</b>, enter:\n<tt>smith</tt>\n\nTo search the field <b>author</b> for <b>Smith</b> and the field <b>title</b> for <b>electrical</b>, enter:\n<tt>author=Smith AND title=electrical</tt>
```

File: src/test/java/org/jabref/logic/search/query/SearchQueryExtractorConversionTest.java (hunk 13 above)
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/query/SearchQueryExtractorConversionTest.java:19]: Both of them are working see https://github.com/JabRef/jabref/blob/c7baf048e4056a292e37e720dd1a481810a2a6c2/src/main/java/org/jabref/logic/search/query/SearchToSqlVisitor.java#L201

**Comment by koppor** [comment]
Also think about if/when to handle chinese characters (https://github.com/JabRef/jabref/issues/9605). Does a user input pinyin?

**Comment by koppor** [comment]
It might be that for our Cli application, we need to fire up postgres on some cases --> follow-up issue (to really think about the cases where we need it and how we could conditionally fire it up)

**Comment by koppor** [comment]
I merged main. Should be OK.

However, I cannot search for words separated by space

image

**Comment by LoayGhreeb** [comment]
> Also think about if/when to handle chinese characters (#9605). Does a user input pinyin?

Currently, searching with Chinese characters will work. If we want to support pinyin, it will be a follow-up. As discussed before, we want to implement normalization based on language, creating new columns for each language and possibly using Lucene's NormalizationFilter classes or finding other libraries for this purpose.

---

> It might be that for our Cli application, we need to fire up postgres on some cases --> follow-up issue (to really think about the cases where we need it and how we could conditionally fire it up)

Yes, we have [Export matching entries](https://docs.jabref.org/advanced/commandline#export-matching-entries-m-field-searchterm-outputfile-file-exportformat) from the command line. It should index the library and export the matches. Implemented  in `org.jabref.logic.search.DatabaseSearcher`

---

> I merged main. Should be OK.
> 
> However, I cannot search for words separated by space

I see, and the parser throws an exception in that case. I will try to fix this before merging. I also added a comment on the parser test https://github.com/JabRef/jabref/blob/df2e12b6a55bcb360ff09301b99bec2178f5ef02/src/test/java/org/jabref/logic/search/query/SearchQuerySQLConversionTest.java#L661-L662

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java (hunk 19 above)
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: > Can this test be kept somehouw? I think, it checks for set groups, which is an impotant use case.

I kept the test, but the query used for Lucene searches in linked files only. The query `groups != .+` will be converted to `org.apache.lucene.search.MatchNoDocsQuery`. The only searchable fields in linked files are `content` and `annotations`; any other fields will be ignored and converted to `MatchNoDocsQuery`. Queries without a specified field or using fields like `any` or `anyfield` will search in both `content` and `annotations`.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java (hunk 20 above)
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: > This should also be kept: non-empty group and set read-status

This is only for searching linked files using Lucene. The searchable fields in linked files are `content` and `annotations`. Searching in bib fields is handled by SQL queries. I will add those test cases to `org.jabref.logic.search.query.SearchQuerySQLConversionTest`.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java (hunk 18 above)
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java]: > This should be kept? -- Not sure about the current state of discussion `any` versus `anyfield`.

See https://github.com/JabRef/jabref/pull/11803#discussion_r1798130861

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java (hunk 15 above)
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java:13]: > Is this really lucene? Isn't it Postgres?

SQL queries tested in [`SearchQuerySQLConversionTest.java`](https://github.com/JabRef/jabref/blob/postgresql/src/test/java/org/jabref/logic/search/query/SearchQuerySQLConversionTest.java).

 Lucene is used for searching in linked files.

File: src/main/java/org/jabref/logic/search/query/SearchQueryExtractorVisitor.java [hunk 23]
```diff
@@ -0,0 +1,65 @@
...
+
+    @Override
+    public Set<String> visitStart(SearchParser.StartContext ctx) {
+        visit(ctx.expression());
+        return searchTerms;
+    }
+
+    @Override
+    public Set<String> visitUnaryExpression(SearchParser.UnaryExpressionContext ctx) {
+        isNegated = !isNegated;
```
[the remark this answers is not in the document]
Comment (LoayGhreeb) [reply src/main/java/org/jabref/logic/search/query/SearchQueryExtractorVisitor.java:22]: > I miss a test for this class. Currently, it reads strange. (If the test is src/test/java/org/jabref/logic/search/query/SearchQueryExtractorConversionTest.java, link it in JavaDoc of this class`)

Yes, the test is in [`org.jabref.logic.search.query.SearchQueryExtractorConversionTest`](https://github.com/JabRef/jabref/blob/postgresql/src/test/java/org/jabref/logic/search/query/SearchQueryExtractorConversionTest.java), but I forgot to add the JavaDoc link.

> Maybe, one does not need the variable
> `isNegated` at all. The checks in `visitComparison` read fine.

The `isNegated` variable, is necessary to handle the unary `NOT` operator, it differs from the `!=` operator.

The `isNegated = !isNegated` logic covers cases like `NOT (NOT term)`, where the `term` should be included in the search terms in such cases.

File: src/test/java/org/jabref/logic/search/DatabaseSearcherWithBibFilesTest.java [hunk 24]
```diff
@@ -81,62 +83,58 @@ private BibDatabaseContext initializeDatabaseFromPath(String testFile) throws Ex
...
-                Arguments.of(List.of(MINIMAL_SENTENCE_CASE, MINIMAL_ALL_UPPER_CASE, MINIMAL_MIXED_CASE), "test-library-with-attached-files.bib", "comma", EnumSet.of(SearchFlags.FULLTEXT)),
-
-                // TODO: PDF search does not support case sensitive search (yet)
-                // Arguments.of(List.of(minimalAllUpperCase, minimalMixedCase), "test-library-with-attached-files.bib", "THIS", EnumSet.of(SearchFlags.FULLTEXT, SearchFlags.CASE_SENSITIVE)),
-                // Arguments.of(List.of(minimalAllUpperCase), "test-library-with-attached-files.bib", "THIS is a short sentence, comma included.", EnumSet.of(SearchFlags.FULLTEXT, SearchFlags.CASE_SENSITIVE)),
-                // Arguments.of(List.of(minimalSentenceCase, minimalAllUpperCase, minimalMixedCase), "test-library-with-attached-files.bib", "comma", EnumSet.of(SearchFlags.FULLTEXT, SearchFlags.CASE_SENSITIVE)),
-                // Arguments.of(List.of(minimalNoteAllUpperCase), "test-library-with-attached-files.bib", "THIS IS A SHORT SENTENCE, COMMA INCLUDED.", EnumSet.of(SearchFlags.FULLTEXT, SearchFlags.CASE_SENSITIVE)),
```
[the remark this answers is not in the document]
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/DatabaseSearcherWithBibFilesTest.java:121]: > This is still a TODO, isn't it? - I didn't see it covered in the added test cases

I think these test cases should be removed, as Lucene doesn't support case-sensitive searches. The tests are for linked files, not bib fields.

File: src/test/java/org/jabref/logic/search/DatabaseSearcherWithBibFilesTest.java [hunk 25]
```diff
@@ -81,62 +83,58 @@ private BibDatabaseContext initializeDatabaseFromPath(String testFile) throws Ex
...
-
-                Arguments.of(List.of(), "test-library-with-attached-files.bib", "NotExisting", EnumSet.of(SearchFlags.FULLTEXT)),
-                Arguments.of(List.of(MINIMAL_NOTE_SENTENCE_CASE, MINIMAL_NOTE_ALL_UPPER_CASE, MINIMAL_NOTE_MIXED_CASE), "test-library-with-attached-files.bib", "world", EnumSet.of(SearchFlags.FULLTEXT)),
-                Arguments.of(List.of(MINIMAL_NOTE_SENTENCE_CASE, MINIMAL_NOTE_ALL_UPPER_CASE, MINIMAL_NOTE_MIXED_CASE), "test-library-with-attached-files.bib", "Hello World", EnumSet.of(SearchFlags.FULLTEXT))
-
-                // TODO: PDF search does not support case sensitive search (yet)
-                // Arguments.of(List.of(minimalNoteAllUpperCase), "test-library-with-attached-files.bib", "HELLO WORLD", EnumSet.of(SearchFlags.FULLTEXT, SearchFlags.CASE_SENSITIVE)),
-                // Arguments.of(List.of(), "test-library-with-attached-files.bib", "NotExisting", EnumSet.of(SearchFlags.FULLTEXT, SearchFlags.CASE_SENSITIVE))
```
[the remark this answers is not in the document]
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/DatabaseSearcherWithBibFilesTest.java:129]: > This is still a TODO, isn't it? - I didn't see it covered in the added test cases

I think these test cases should be removed, as Lucene doesn't support case-sensitive searches. The tests are for linked files, not bib fields.

File: src/test/java/org/jabref/logic/search/query/LuceneQueryParserTest.java (hunk 12 above)
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/query/LuceneQueryParserTest.java]: > We should move these tests to somewhere else. Didn't find that in the new code.

The bib fields queries are tested in [`src/test/java/org/jabref/logic/search/query/SearchQuerySQLConversionTest.java`](https://github.com/JabRef/jabref/blob/postgresql/src/test/java/org/jabref/logic/search/query/SearchQuerySQLConversionTest.java). I will add these tests there.

> Test cases should use `Lübeck` as test. (City name in Germany).
> 
> Lübeck, Lubeck, Luebeck, L"{u}beck

Only searching with `Lübeck` will work; `Lubeck` and `Luebeck` will not find the entry. This normalization should be done during indexing based on the language. The last term, `L"{u}beck`, will not work because the parser throws an exception due to the `"` character.

File: src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java (hunk 14 above)
Comment (LoayGhreeb) [reply src/test/java/org/jabref/logic/search/query/SearchQueryLuceneConversionTest.java:62]: `testSearchConversion` begin with `test` 😅

File: src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java [hunk 26]
```diff
@@ -24,11 +23,17 @@ public class SearchGroupsMigrationAction implements GUIPostOpenAction {
...
-    public boolean isActionNecessary(ParserResult parserResult, CliPreferences preferences) {
-        if (parserResult.getMetaData().getGroupSearchSyntaxVersion().isPresent()) {
-            // Currently the presence of any version is enough to know that no migration is necessary
+    public boolean isActionNecessary(ParserResult parserResult, DialogService dialogService, CliPreferences preferences) {
+        Optional<Version> currentVersion = parserResult.getMetaData().getGroupSearchSyntaxVersion();
+        if (currentVersion.isPresent()) {
+            if (currentVersion.get().equals(VERSION_6_0_ALPHA)) {
+                // TODO: This text will only be shown after releasing 6.0-alpha and then removed
+                dialogService.showErrorDialogAndWait("Search groups migration of " + parserResult.getPath().map(Path::toString).orElse(""),
+                        "The search groups syntax has been reverted to the old one. Please use the backup you made before migrating to 6.0-alpha.");
```
Comment (koppor) [inline src/main/java/org/jabref/gui/importer/actions/SearchGroupsMigrationAction.java:35]:
```suggestion
                        "The search groups syntax has been reverted to the old one. Please use the backup you made before using 6.0-alpha.");
```

**Review by koppor — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Yeah finally!

**Comment by calixtus** [comment]
Yay!

**Comment by koppor** [comment]
Follow-up to https://github.com/JabRef/jabref/pull/11542
