### PR TITLE
Refresh fulltext search results when database change

### LINKED ISSUE #13241: Search results tab is blank after switching library
### JabRef version

Latest development branch build (please note build date below)

### Operating system

MacOS

### Details on version and operating system

MacOS Sequoia 15.0 

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Do a fulltext search in a library
2. Switch to another db/library
3. Switch back to the first library and check the search results tab 

Turning off and on the fulltext flag again will make the results appear correctly. 

Doing a sort of "hack" where we reset the flag (if it is active) every-time a library is switched seems to prevent the issue, like this :
`        stateManager.activeDatabaseProperty().addListener((_, _, _) -> {
            if (preferences.getSearchPreferences().isFulltext()) {
                Platform.runLater(this::resetFulltextFlag);
            } else {
                content.getChildren().clear();
            }
        });    
`

But it's just an hack and also seems to create problems with threads concurrency (I can post a video of this behavior as well if needed).

### Appendix

https://github.com/user-attachments/assets/5a5df74f-3396-439b-b01d-aed8903144c8

No errors in the log.

### PR DESCRIPTION
**Pull request by ZodGaz**
Closes #13241

We found out the issue was that the `searchResults` in the `FullTextResultsTab` would be empty after switching databases, making the tab appear blank. This happened because the listener (and consequently other listeners) on the `SearchQuery` inside `MainTableDataModel` wasn't firing since it didn't detect a different query (`oldValue == newValue`).

As other maintainers suggested, we could have fixed this by emptying the query and then refilling it, but that risked thread-concurrency issues and breaking functions relying on `SearchQuery` not being empty. Another solution was toggling the fulltext flag when switching databases, but that caused extra loading times and weird UI behavior.

The solution I went with: just remove the `FULLTEXT` flag from the `searchQuery`'s flag list. This triggers the search refresh. No need to manually re-add the flag because the UI listeners will put it back automatically in the same event cycle. Yeah it's a workaround, but it's cheaper and faster than a full investigation and major refactoring.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by koppor** [comment]
Related PR: https://github.com/JabRef/jabref/pull/11268

File: jabgui/src/main/java/org/jabref/gui/maintable/MainTableDataModel.java [hunk 1]
```diff
@@ -109,6 +110,17 @@ private void updateSearchMatches(Optional<SearchQuery> query) {
         }).onSuccess(result -> FilteredListProxy.refilterListReflection(entriesFiltered)).executeWith(taskExecutor);
     }
 
+//  We need to call this when the database is switched during a fulltext search since
+//  the listener on the searchQueryProperty will not fire if the query doesn't change
+//  (this causes searchResults in FullTextResultsTab to be empty)
+//  https://github.com/JabRef/jabref/issues/13241
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/maintable/MainTableDataModel.java]: Please fix the indnet.

Use Three slashes for JavaDOC method comments.
