### PR TITLE
Custom DOI base address fix

### LINKED ISSUE #7337: Custom web address for accessing articles through DOI
When I click on the `Open` button next to the DOI of an entry it opens a web browser to the address `https://doi.org/[DOI]`, which then redirects to the article website. In order to access articles in subscription-based journals, my institution has a shortcut that involves modifying the address to the doi site (e.g. for my institution it is `https://doi-org.ezproxy.lib.uts.edu.au/[DOI]`). It would be great if the address used to access the articles through the DOI could be modified in the preferences.

### PR DESCRIPTION
**Pull request by BJaroszkowski**
As mentioned in 
Fixes #7337 the option to choose custom DOI base address did not propagate to `LibraryTab` and this PR aims to solve exactly that. In the process I refactored `LinkedIdentifierColumn` so that it uses `OpenUrlAction` as well.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/maintable/OpenUrlAction.java [hunk 1]
```diff
@@ -62,11 +67,28 @@ public void execute() {
...
+                        JabRefDesktop.openExternalViewer(databaseContext, link.get(), field);
+                    }
                 } catch (IOException e) {
                     dialogService.showErrorDialogAndWait(Localization.lang("Unable to open link."), e);
                 }
             }
         });
     }
+
+    private void openCustomDOI(String link) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/maintable/OpenUrlAction.java:82]: I saw that this method is a duplicate of the one in the Entry Editor. To avoid code duplication, I think it could be useful to extract this method to  a static method in JabRefDesktop and then call that.  You would need to pass the prefs as parameter then

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
Thanks for the quick follow up, just an idea for

**Review by Siedlerchr — APPROVED** [review]
Thanks for the quick follow up! Looks good to me!
