### PR TITLE
Tell google explicitly to send UTF-8 and always use UTF-8

### LINKED ISSUE #1762: Google Scholar: Preview with wrong encoding
JabRef 3.6dev--snapshot--2016-08-16--master--257ba21 windows 10 10.0 amd64 Java 1.8.0_101

Steps to reproduce:

1. Web search interface
2. Google Scholar
3. Fetch
4. Preview with wrong encoding

scholar

### PR DESCRIPTION
**Pull request by matthiasgeiger**
Fixes #1762 and #1694

Use `&oe=utf-8` to tell google to deliver content in UTF-8 - more over explicitly use UTF-8 in the JabRef code instead of beeing dependent on the prefs.

- ~~[ ] Change in CHANGELOG.md described~~ - has been introduced in dev version
- [x] Manually tested changed features in running JabRef

### CODE REVIEW

File: src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java [hunk 1]
```diff
@@ -176,10 +176,10 @@ public void stopFetching() {
 
     private static void runConfig() throws IOException {
         try {
-            new URLDownload("http://scholar.google.com").downloadToString(Globals.prefs.getDefaultEncoding());
+            new URLDownload("http://scholar.google.com").downloadToString(StandardCharsets.UTF_8);
             //save("setting.html", ud.getStringContent());
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/gui/importer/fetcher/GoogleScholarFetcher.java]: Remove that outcommented line

**Comment by Siedlerchr** [comment]
LGTM :+1:

**Comment by matthiasgeiger** [comment]
#1694 is not working yet... I'll try to fix this, too.

**Comment by Siedlerchr** [comment]
I was just asking for it. I already digged into it, see details in the issue. The preview was okay, but not the bibtex getting request somehow.

**Comment by matthiasgeiger** [comment]
Same problem - same solution: `...&oe=utf-8`

**Comment by oscargus** [comment]
Code looks good! I'm not going to mention `URLBuilder` and `unirest`...

**Comment by stefan-kolb** [comment]
LGTM :+1: Can we add a test to ensure this behavior?

**Comment by matthiasgeiger** [comment]
I'll add a test using the entry from #1694 next week 😉

**Comment by matthiasgeiger** [comment]
For the record: this is currently not really testable due to the mixture of UI and logic code in the current state of implementation
