### PR TITLE
Fix invisible notification message

### LINKED ISSUE #8761: blank popup
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-05-03--46a4edf Linux 5.13.0-40-generic amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Save
2. blank popup.  I don't know what it is saying.  The library seems to be saved okay. 

image

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by HoussemNasri**
Fix #8761 

The notification bar appeared blank because the title and the button's text had the same color as the background. I updated the CSS style to use a lighter color and restyled the overall look and feel of the notification bar.

I also changed the notification message and duration for when the library is successfully exported to match with Typora. I did this because I think Typora has a good user experience.

## Light Theme
light

## Dark Theme
dark

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/exporter/ExportCommand.java [hunk 1]
```diff
@@ -136,16 +136,16 @@ private void export(Path file, FileChooser.ExtensionFilter selectedExtensionFilt
...
+                            List.of(new Action(Localization.lang("Reveal in File Explorer"), event -> {
                                 try {
                                     JabRefDesktop.openFolderAndSelectFile(file, preferences);
                                 } catch (IOException e) {
                                     LOGGER.error("Could not open export folder.", e);
                                 }
                                 notificationPane.hide();
                             })),
-                            Duration.seconds(5));
+                            Duration.seconds(10));
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/exporter/ExportCommand.java:148]: For the export I would not increase the time, 5 seconds  is enough

Comment (HoussemNasri) [reply src/main/java/org/jabref/gui/exporter/ExportCommand.java]: Done

**Review by calixtus — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
Thanks again for the quick follow up and the fix!
