### PR TITLE
fix IEE fetcher

### LINKED ISSUE #4997: IEEXplore Online Fetcher not working
Online fetcher not generating results. Problem started 3 weeks back, prior to that it was working perfect. In the beginning, the error was shown as internet connection issue. After updating the JabRef with latest version, the search keeps processing, with no result. The internet is connected with proxy hostname and authentication already given in the preferences.
screen

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #4997 

add exception dialog on import fail

Check if we have keywords field present in json

----

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java [hunk 1]
```diff
@@ -84,19 +87,21 @@ public StringProperty queryProperty() {
...
+           dialogService.notify(Localization.lang("Please open or start a new library before searching"));
             return;
         }
 
         SearchBasedFetcher activeFetcher = getSelectedFetcher();
 
         BackgroundTask<List<BibEntry>> task = BackgroundTask.wrap(() -> activeFetcher.performSearch(getQuery().trim()))
                                                             .withInitialMessage(Localization.lang("Processing %0", getQuery()));
+        
+        task.onFailure(ex->dialogService.showErrorDialogAndWait(ex));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java]: add spaceing around `->`
