### PR TITLE
Fix tooltip display for multiple linked files

### LINKED ISSUE #12470: Tooltip Only Displays the First Linked File When Hovering
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

_No response_

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When hovering over the "Linked Files" tab for an entry with multiple linked files, the tooltip only displays the first attached file instead of listing all linked files.

Image

Steps to Reproduce

- create a new entry.

- Attach multiple files to the entry ensure filenames are distinct for clarity.

- Hover over the "Linked Files" tab in the entry editor.

Expected Behavior
The tooltip should display all linked files, not just the first one,

### PR DESCRIPTION
**Pull request by patriciagam**
Ensures that when hovering over the "Linked Files" tab, the tooltip displays all linked files instead of just the first one. This fix resolves the issue where only the first linked file was shown.

The logic in createFileTooltip was updated to generate a single string containing the paths of all linked files.

An early return was added at the beginning to handle cases where no files are linked, improving efficiency. The text for the "Open file" action was also adjusted: it now displays "Open file" when there is only one linked file and "Open files..." when there are multiple. The phrase "Open files..." was chosen because it was the only plural form available in the translation files, as neither "Open files" nor "Open files %0" were present. This ensures consistency across different languages without requiring changes to existing translations.

The images below illustrate the updated behavior of the "Open file" action.

#### Case: Single linked file

single_file

#### Case: Multiple linked files  

multiple_files

Fixes #12470

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/maintable/columns/FileColumn.java [hunk 1]
```diff
@@ -138,10 +138,20 @@ private void setCommonSettings() {
...
-            return Localization.lang("Open file %0", linkedFiles.getFirst().getLink());
+        if (linkedFiles.isEmpty()) {
+            return null;
+        }
+
+        StringBuilder sb = new StringBuilder();
+
+        for (LinkedFile linkedFile : linkedFiles) {
+            sb.append("\n").append(linkedFile.getLink());
+        }
```
Comment (koppor) [inline src/main/java/org/jabref/gui/maintable/columns/FileColumn.java:149]: Please use StringJoiner instead of StringBuilder (more modern - automatically adds `\n` if used correctly)

File: src/main/java/org/jabref/gui/maintable/columns/FileColumn.java [hunk 2]
```diff
@@ -138,10 +138,20 @@ private void setCommonSettings() {
...
+
+        if (linkedFiles.size() == 1) {
+            return Localization.lang("Open file %0", sb.toString());
```
Comment (koppor) [inline src/main/java/org/jabref/gui/maintable/columns/FileColumn.java:152]: When using StringJoiner, there is no newline at the beginning, which is good.

File: src/main/java/org/jabref/gui/maintable/columns/FileColumn.java [hunk 3]
```diff
@@ -138,10 +138,20 @@ private void setCommonSettings() {
...
         }
-        return null;
+        return Localization.lang("Open files...") + sb.toString();
```
Comment (koppor) [inline src/main/java/org/jabref/gui/maintable/columns/FileColumn.java:154]: Please add `\n\n` inbetween for a nice content.

**Review by koppor — CHANGES_REQUESTED** [review]

**Comment by patriciagam** [comment]
Thank you for your feedback!
I've implemented the changes you suggested. Please let me know if there's anything else that needs adjusting.

File: src/main/java/org/jabref/gui/maintable/columns/FileColumn.java [hunk 4]
```diff
@@ -138,10 +139,20 @@ private void setCommonSettings() {
...
-            return Localization.lang("Open file %0", linkedFiles.getFirst().getLink());
+        if (linkedFiles.isEmpty()) {
+            return null;
+        }
+
+        StringJoiner joiner = new StringJoiner("\n");
+
+        for (LinkedFile linkedFile : linkedFiles) {
+            joiner.add(linkedFile.getLink());
+        }
```
Comment (koppor) [inline src/main/java/org/jabref/gui/maintable/columns/FileColumn.java:150]: Can you convert that to stream. At the end `Collectors.joining("\n")`  - even more modern java then.

File: src/main/java/org/jabref/gui/maintable/columns/FileColumn.java [hunk 5]
```diff
@@ -138,10 +139,20 @@ private void setCommonSettings() {
...
+
+        if (linkedFiles.size() == 1) {
+            return Localization.lang("Open file %0", joiner.toString());
         }
-        return null;
+        return Localization.lang("Open files...") + "\n\n" + joiner.toString();
```
Comment (koppor) [inline src/main/java/org/jabref/gui/maintable/columns/FileColumn.java:155]: Wrong wording...

Hover:

grafik

Click:

grafik

Just remvoe `Localization.lang("Open files...")` - only the `joiner.toString` (with the fix above: the `fileString`)

**Review by koppor — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/gui/maintable/columns/FileColumn.java (hunk 5 above)
Comment (patriciagam) [reply src/main/java/org/jabref/gui/maintable/columns/FileColumn.java:155]: Just to confirm, when there are multiple files,  I should only show the file paths without any additional text and when there is only one file,  I should keep the current format. Am I understanding correctly?

Comment (koppor) [reply src/main/java/org/jabref/gui/maintable/columns/FileColumn.java:155]: Thank you for checking back!

Yes, you understood correctly.

**Comment by patriciagam** [comment]
Changing the return type to Optional might involve modifying the withTooltip method, which is used in several places across the code, or using a lambda expression that ensures an empty string is returned if the Optional is empty. Given these constraints, returning an empty string might be a simpler option. I’m open to any alternative suggestions you might have.

**Comment by koppor** [comment]
> Changing the return type to Optional might involve modifying the withTooltip method, which is used in several places across the code, or using a lambda expression that ensures an empty string is returned if the Optional is empty. Given these constraints, returning an empty string might be a simpler option. I’m open to any alternative suggestions you might have.

Its OK to keep null there.

**Review by Siedlerchr — APPROVED** [review]

**Review by koppor — APPROVED** [review]
