### PR TITLE
Fix icon color

### LINKED ISSUE #7853: Icons in Entry Edit Window not visible in Dark Mode
JabRef version 5.3--2021-06-27--aa60dd6 on Windows 10

I have tested the latest development version from http://builds.jabref.org/main and the problem persists

The icons in the entry edit window are frequently too dark to be visible in dark mode. A bright color would be better suited

1. change to dark mode
2. edit an entry
3. view icons

Screenshot 2021-06-28 132651

### PR DESCRIPTION
**Pull request by calixtus**
grafik
grafik
grafik
grafik grafik

Fixes #7853
Closes #7953

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Unfortunately, this affects colored group icons: 
image

Current behaviour:
image

**Comment by calixtus** [comment]
Fixed it:
grafik

File: src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java [hunk 1]
```diff
@@ -46,7 +46,8 @@ public Node getGraphicNode() {
 
 //      Override the default color from the css files
         color.ifPresent(color -> fontIcon.setStyle(fontIcon.getStyle() +
-                String.format("-fx-fill: %s;", ColorUtil.toRGBCode(color))));
+                String.format("-fx-fill: %s;", ColorUtil.toRGBCode(color)) +
+                String.format("-fx-icon-color: %s;", ColorUtil.toRGBCode(color))));
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/icon/InternalMaterialDesignIcon.java:50]: Ah that's it!

**Review by Siedlerchr — APPROVED** [review]
