### PR TITLE
Fix pdf content importer exception if DOI is empty

### LINKED ISSUE #7203: PdfContentImporter: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
### JabRef Version

```
JabRef 5.2--2020-12-14--e9be339
Windows 10 10.0 amd64 
Java 14.0.2
```

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

### Summary

JabRef PDF Importer crashes attempting to process a PDF file

 * PDF Source: [21Lucy Anna Smith MSc Thesis 2015.pdf](https://github.com/JabRef/jabref/files/5713479/21Lucy.Anna.Smith.MSc.Thesis.2015.pdf)

### Additional Details (if relevent, obtained via Adobe  Acrobat)

 * PDF Producer: GPL Ghostscript 8.70 
 * PDF Version: 1.3 (Acrobat 4.x)
 * Tagged PDF: No

### Steps to Reproduce

1. `Lookup` -> `Search for unlinked local files`
2. Select PDF file attached to this issue -> `Import`

<details>
  <summary>Log File</summary>
  
  ```
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.base/java.lang.StringLatin1.charAt(Unknown Source)
	at java.base/java.lang.String.charAt(Unknown Source)
	at org.jabref@5.2.343/org.jabref.logic.importer.fileformat.PdfContentImporter.getEntryFromPDFContent(Unknown Source)
	at org.jabref@5.2.343/org.jabref.logic.importer.fileformat.PdfContentImporter.importDatabase(Unknown Source)
	at org.jabref@5.2.343/org.jabref.logic.externalfiles.ExternalFilesContentImporter.importPDFContent(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.externalfiles.ImportHandler.importAsNewEntries(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.externalfiles.FindUnlinkedFilesDialog.startImport(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.externalfiles.FindUnlinkedFilesDialog.lambda$initialize$8(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.control.Dialog.setResultAndClose(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.control.DialogPane.lambda$createButton$3(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.externalfiles.FindUnlinkedFilesAction.execute(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.2.343/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.343/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #7203 

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — APPROVED** [review]

File: src/test/java/org/jabref/logic/importer/fileformat/PdfContentImporterTest.java [hunk 1]
```diff
@@ -88,4 +88,26 @@ void testParsingEditorWithoutPagesorSeriesInformation() {
 
         assertEquals(Optional.of(entry), importer.getEntryFromPDFContent(firstPageContents, "\n"));
     }
+
+    @Test
+    void testParsingWithoutActualDOINumber() {
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/fileformat/PdfContentImporterTest.java:93]: Even with a test case. Thank you!

Comment (koobs) [reply src/test/java/org/jabref/logic/importer/fileformat/PdfContentImporterTest.java:93]: ❤️
