### PR TITLE
Fix attach file action from contextmenu

### LINKED ISSUE #3080: Automatic Bug Report - 20170806233800 Unable to attach file
Unable to attach file using 4.0_v_2.9.2.r7151.b7743c4d7
JabRef 4.0-dev
Linux 4.12.4-1-arch amd64 
Java 1.8.0_144

Steps to reproduce:

1. Open jabref
2. ...Select/right click entry in library
3. ...Select "Attach file", navigate to and select a .pdf file
4. At this stage, the correct file path appears in the pop-up box and can be opened
5 Click "OK" - no icon in entry list, and no change in .bib file
<details>
<summary>Detail information:</summary>

```
There seem to be problems with OpenJDK and the default GTK Look&Feel. Using Metal L&F instead. Change to another L&F with caution.
Opening: /home/ian/my_db.bib
runCommand error: null
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.jabref.model.entry.BibEntry.addFile(BibEntry.java:833)
	at org.jabref.gui.filelist.AttachFileAction.action(AttachFileAction.java:35)
	at org.jabref.gui.BasePanel.runCommand(BasePanel.java:1027)
	at org.jabref.gui.menus.RightClickMenu$GeneralAction.actionPerformed(RightClickMenu.java:312)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Return new ArrayList instead of unmodiefable emptyList()

Fixes #3080 

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
@tobiasdiez  Well, the problem is that the current code always returns an immutable list. 
I see no reason why the LInkedFileList should be immutable
```
    public Optional<FieldChange> addFile(LinkedFile file) {
        List<LinkedFile> linkedFiles = getFiles(); //This was originally breaking because of immutable 
        linkedFiles.add(file);
        return setFiles(linkedFiles);
    }
```

File: src/main/java/org/jabref/model/entry/FileFieldParser.java [hunk 1]
```diff
@@ -1,59 +1,58 @@
...
-import java.util.Collections;
 import java.util.List;
 
 public class FileFieldParser {
-    public static List<LinkedFile> parse(String value) {
-        if ((value == null) || value.trim().isEmpty()) {
-            return Collections.emptyList();
-        }
 
+    public static List<LinkedFile> parse(String value) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/model/entry/FileFieldParser.java]: This method is called in many different places

Comment (tobiasdiez) [inline src/main/java/org/jabref/model/entry/FileFieldParser.java]: Returning a mutable list here is ok, since the method is static anyway and thus you don't have the problem that a mutable list exposes the internal state of the object to the outside world.
However, `getFiles` is not static and only used once...

As I said above, I have no well-founded knowledge about these matters but probably there a established conventions that we should follow here.

Comment (lenhard) [inline src/main/java/org/jabref/model/entry/FileFieldParser.java]: It's fine in this case, because the value of the file field is only stored as a String in `BibEntry`. On calling `getFiles` the String is converted into a list, but this list is not stored in `BibEntry`, so it's not possible to compromise its internal state.

You could call this a "defensive copy", which is fine.

**Comment by lenhard** [comment]
@tobiasdiez There is no hard Java convention regarding these aspects. You can make the caller fail or you can give him a new list. The only thing that matters is that the internal state of `BibEntry` is not changed that way.

I don't have a strong opinion as to which solution we should adapt here. Regardless of which one we choose, we should probably document it in code.

**Comment by lenhard** [comment]
@Siedlerchr can you expand the JavaDoc comment of `BibEntry.getFiles()` so that it explains that the returned list is a defensive copy and changes to this list will have no effect on the entry?

With this documentation, the PR can be merged.

File: src/main/java/org/jabref/model/entry/FileFieldParser.java [hunk 2]
```diff
@@ -1,59 +1,58 @@
...
-                escaped = true;
-                continue;
-            }
-            // Check if we are entering an XML special character construct such
-            // as "&#44;", because we need to know in order to ignore the semicolon.
-            else if (!escaped && (c == '&') && !inXmlChar) {
-                sb.append(c);
-                if ((value.length() > (i + 1)) && (value.charAt(i + 1) == '#')) {
-                    inXmlChar = true;
+        if ((value != null) && !value.trim().isEmpty()) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/model/entry/FileFieldParser.java]: I like the previous structure more (early return instead of big if), which was also more inline with typical [coding conventions](https://softwareengineering.stackexchange.com/questions/18454/should-i-return-from-a-function-early-or-use-an-if-statement).

Comment (Siedlerchr) [inline src/main/java/org/jabref/model/entry/FileFieldParser.java]: done
