### PR TITLE
Switch colors of search icon for the two search modes

### LINKED ISSUE #3870: Magnifier changes colors wrong
JabRef offers two search modes: normal search and the grammar based ("advanced") search. See https://help.jabref.org/en/Search#search-modes.

In JabRef 3.6, the initial search was the normal search. This changed in JabRef 3.7 somehow. This seems to be wrong.

Action points:

1. Dig into the change made between JabRef 3.6 and 3.7
2. Find out whether the change is right or wrong. Current assumption: It was wrong
3. Take appropriate action.

Refs https://github.com/JabRef/jabref/issues/3535 and the fix https://github.com/JabRef/jabref/pull/3708

### PR DESCRIPTION
**Pull request by lenhard**
Fixes #3870

----

- [X] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [X] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by koppor** [comment]
Grammar-based search is the advanced search. So, the magnifier should be cyan, when following search string is active:

    author=kolb and author=kopp

Taking examples from the documentation (https://help.jabref.org/en/Search#search-modes)

All of these are advanced, but they are not recognized as such:

    title|keywords = "image processing"

    (author = miller or title|keywords = "image processing") and not author = brown

Following is normal mode:

    progress “marine aquaculture”progress “marine aquaculture”

This is now with cyan. This is wrong.

Following is normal mode:

    progress

Correctly recognized as normal mode.

**Comment by stefan-kolb** [comment]
If so, the whole detection is wrong?!

**Comment by koppor** [comment]
Only the beginning of the detection is somehow wrong. For complex terms it is right, but for single words, it is wrong. See the examples above. Maybe, we changed something when going from JabRef 3.6 to 3.7.

**Comment by lenhard** [comment]
Or maybe the detection never was entirely correct. If I have a lot of time on my hands, I might have a look at the detection algorithm. Otherwise we can close this PR and / or remove the coloring of the the search icon again. After all, what is the point of changing its color if the circumstances are incorrect?

**Comment by tobiasdiez** [comment]
@lenhard If you indeed have time to look at the search algorithm, please replace it completely ;-) https://github.com/JabRef/jabref/issues/1975

**Comment by koppor** [comment]
It worked in 3.6 and no one noticed that it broke at 3.7. So, the point is
to keep the idea and to fix it... The idea in other words: make users aware
of the feature and that the search might not work if the grammar based
search was intended, but not matched (typo in query)

Am 22.03.2018 19:53 schrieb "Jörg Lenhard" <notifications@github.com>:

Or maybe the detection never was entirely correct. If I have a lot of time
on my hands, I might have a look at the detection algorithm. Otherwise we
can close this PR and / or remove the coloring of the the search icon
again. After all, what is the point of changing its color if the
circumstances are incorrect?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/pull/3871#issuecomment-375419286>, or mute
the thread

**Comment by stefan-kolb** [comment]
Actually there should be tests for it then, as this is not a UI feature but the detection is logic based...

**Comment by lenhard** [comment]
Did we update the antlr stuff after v3.6? Because the query "progress" actually is a valid grammar-based query that compiles with our antlr code. That's the reason for the "wrong" coloring. 

I have now added code that checks if a query consists only of word / whitespace characters and/or digits and uses a normal contains-based query for that. Thus, grammar-based searches are only executed when special symbols are used ALTHOUGH our grammar is more powerfull than that. The terms mentioned by @koppor above are now colored as expected. @koppor: I hope this limitation is what is wanted. Please do some testing to see if this matches your expectations.

File: src/main/java/org/jabref/logic/search/SearchQuery.java [hunk 1]
```diff
@@ -85,7 +85,7 @@ private String getLocalizedRegularExpressionDescription() {
     }
 
     public boolean isGrammarBasedSearch() {
-        return rule instanceof GrammarBasedSearchRule;
+        return rule instanceof GrammarBasedSearchRule || rule instanceof RegexBasedSearchRule;
```
Comment (koppor) [inline src/main/java/org/jabref/logic/search/SearchQuery.java]: Should regex really be treated as grammar-based search? I would not treat it like that, because regex search is orthogonal to grammar-based search. One can activate it in addition.

File: src/main/java/org/jabref/model/search/rules/SearchRules.java [hunk 2]
```diff
@@ -2,16 +2,20 @@
...
     }
 
+    private static final Pattern simpleExpression = Pattern.compile("(\\w|\\d|\\s)*");
+
     /**
      * Returns the appropriate search rule that fits best to the given parameter.
      */
     public static SearchRule getSearchRuleByQuery(String query, boolean caseSensitive, boolean regex) {
-        if (StringUtil.isBlank(query)) {
+        if (isSimpleQuery(query)) {
```
Comment (koppor) [inline src/main/java/org/jabref/model/search/rules/SearchRules.java]: Reads good!

File: src/main/java/org/jabref/model/search/rules/SearchRules.java [hunk 3]
```diff
@@ -25,6 +29,10 @@ public static SearchRule getSearchRuleByQuery(String query, boolean caseSensitiv
         }
     }
 
+    private static boolean isSimpleQuery(String query) {
+        return StringUtil.isBlank(query) || simpleExpression.matcher(query).matches();
```
Comment (koppor) [inline src/main/java/org/jabref/model/search/rules/SearchRules.java]: Do you really need both? The current regex has a star (`*`) at the end, which means zero (`0`) ore more matches. So, the empty string should match, too.

File: src/main/java/org/jabref/logic/search/SearchQuery.java (hunk 1 above)
Comment (lenhard) [reply src/main/java/org/jabref/logic/search/SearchQuery.java]: At least in the documentation: https://help.jabref.org/en/Search#search-modes they are listed under the heading of "advanced search". But I can easily change that of course.

Comment (koppor) [reply src/main/java/org/jabref/logic/search/SearchQuery.java]: I updated the help accordingly to also reflect that regular expressions are orthogonal. 😇 

Could you additionally add a comment there that this is the "Advanced Search" described in the help? I know, this contradicts [DDD](https://en.wikipedia.org/wiki/Domain-driven_design), but I think, it is OK in this place.

**Comment by koppor** [comment]
Not what I expect:

`j` - OK:

grafik

`jö` - not OK:

grafik

Minor issue:

When I clear the field using Ctrl+A and then Delete (after an advanced search), the marker is still advanced:

grafik

Otherwise: LGTM :)

File: src/main/java/org/jabref/logic/search/SearchQuery.java (hunk 1 above)
Comment (lenhard) [reply src/main/java/org/jabref/logic/search/SearchQuery.java]: Ok, I adapted the code accordingly.

File: src/main/java/org/jabref/model/search/rules/SearchRules.java (hunk 3 above)
Comment (lenhard) [reply src/main/java/org/jabref/model/search/rules/SearchRules.java]: Good suggestion, that sounds reasonable. I removed the StringUtil dependency and as far as I can see there is no difference in the search.

**Comment by lenhard** [comment]
Thanks for the comments @koppor 

I fixed all the glitches you described and this PR should now be ready.
