### PR TITLE
Fix storing of custom jstyles

### LINKED ISSUE #6170: Imported open office jstyle files disappear when re-starting JabRef (Windows10)
Hello JabRef team,

JabRef version 5.1 23 March 2020 on Windows 10 Intel i7 x86_64 Java 1.8.0_241

- [x] I have tested the latest development version (5.1) from http://builds.jabref.org/master/ and the problem persists

1. ... load style file (select style file -> add style file)
2. ... work with your own style file
3. ...save work and close JabRef
4. ... open JabRef: added style files are missing (just the 2 internal default style files remain)

Complimentary bug:
1. ... load style file (select style file -> add style file)
2. ... work with your own style file
3. ...save work and close JabRef
4. ... open JabRef: added style files are missing (just the 2 internal default style files remain)
5. ... reload a custom style file: sometimes they are not working anymore

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #6170
Rename method for internalStyle

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

File: src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java [hunk 1]
```diff
@@ -121,6 +121,9 @@ public void viewStyle(StyleSelectItemViewModel item) {
     }
 
     public void storePrefs() {
+
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java:124]: delete empty line

File: src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java [hunk 2]
```diff
@@ -121,6 +121,9 @@ public void viewStyle(StyleSelectItemViewModel item) {
...
+        List<String> externalStyles = styles.stream().filter(style -> !style.internalStyleProperty().get()).map(this::toOOBibStyle).map(OOBibStyle::getPath).collect(Collectors.toList());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java:125]: Instead of `internalStyleProperty().get()` use `OOBibStyle.isInternalStyle`?

File: src/main/java/org/jabref/logic/openoffice/StyleLoader.java [hunk 3]
```diff
@@ -44,6 +44,7 @@ public StyleLoader(OpenOfficePreferences preferences, LayoutFormatterPreferences
         loadExternalStyles();
     }
 
+
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/openoffice/StyleLoader.java:47]: remove empty line
