### PR TITLE
Fix warning display issue for entering a title made of two words

### LINKED ISSUE #5832: Title made of two sentences: Capitalization is OK, but warning is displayed
JabRef 5.0-beta.342--2020-01-15--58709e7
Linux 4.9.0-11-amd64 amd64 
Java 13.0.2

When a title is made of two sentences, it is fine to capitalize the first letter of the second sentence. Currently, such title triggers a warning about this capitalization.

1.Create an entry
2. As title input "A title made of two sentences. This is the second sentence"

The warning message (with the triangular yellow icon) is displayed because of the capitalization of the word "This".

### PR DESCRIPTION
**Pull request by eetian**
Hello! This PR fixes the issue that a warning is displayed when users enter a title made of two sentences in the entry editor. fixes #5832 

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 1]
```diff
@@ -48,13 +48,18 @@ public TitleChecker(BibDatabaseContext databaseContext) {
             valueOnlySpacesWithinCurlyBraces = matcher.replaceAll("");
         }
 
-        boolean hasCapitalLettersThatBibtexWillConvertToSmallerOnes = HAS_CAPITAL_LETTERS
-                .test(valueOnlySpacesWithinCurlyBraces);
-
-        if (hasCapitalLettersThatBibtexWillConvertToSmallerOnes) {
-            return Optional.of(Localization.lang("capital letters are not masked using curly brackets {}"));
+        // Delimiters are . ! ? ; :
+        String[] delimitedStr = valueOnlySpacesWithinCurlyBraces.split("(\\.|\\!|\\?|\\;|\\:)");
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]: Try to avoid abbreviations. E.g. use `String[] delimitedString` or `splitString` instead.
Can you make this `"(\\.|\\!|\\?|\\;|\\:)"` this a constant and put it to the the declarations of the class?

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 2]
```diff
@@ -48,13 +48,18 @@ public TitleChecker(BibDatabaseContext databaseContext) {
...
+        for (String subStr : delimitedStr) {
+            subStr = subStr.trim();
+            if (subStr.length() > 0) {
+                subStr = subStr.substring(1);
+            }
+            boolean hasCapitalLettersThatBibtexWillConvertToSmallerOnes = HAS_CAPITAL_LETTERS.test(subStr);
+            if (hasCapitalLettersThatBibtexWillConvertToSmallerOnes) {
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]: I believe, as `hasCapitalLettersThatBibtexWillConvertToSmallerOnes` is not reused, it can be inlined in the `if` predicate and still be meaningful. 😉

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java (hunk 1 above)
Comment (eetian) [reply src/main/java/org/jabref/logic/integrity/TitleChecker.java]: Thank you for your review. I have made changes based on your suggestion.

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java (hunk 2 above)
Comment (eetian) [reply src/main/java/org/jabref/logic/integrity/TitleChecker.java]: I also changed this :)

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 3]
```diff
@@ -22,10 +23,12 @@ public TitleChecker(BibDatabaseContext databaseContext) {
 
     /**
      * Algorithm:
-     * - remove trailing whitespaces
-     * - ignore first letter as this can always be written in caps
      * - remove everything that is in brackets
-     * - check if at least one capital letter is in the title
+     * - split the title into subTitles based on the delimiters
+     * - for each subTitle:
```
Comment (koppor) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]:
```suggestion
     * - for each sub title:
```

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 4]
```diff
@@ -22,10 +23,12 @@ public TitleChecker(BibDatabaseContext databaseContext) {
 
     /**
      * Algorithm:
-     * - remove trailing whitespaces
-     * - ignore first letter as this can always be written in caps
      * - remove everything that is in brackets
-     * - check if at least one capital letter is in the title
+     * - split the title into subTitles based on the delimiters
```
Comment (koppor) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]:
```suggestion
     * - split the title into sub titles based on the delimiters (defined in the local variable DELIMITERS, currently . ! ? ; :)
```

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 5]
```diff
@@ -22,10 +23,12 @@ public TitleChecker(BibDatabaseContext databaseContext) {
...
+     * - for each subTitle:
+     * -    remove trailing whitespaces
+     * -    ignore first letter as this can always be written in caps
+     * -    check if at least one capital letter is in the title
```
Comment (koppor) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]:
```suggestion
     * -    check if at least one capital letter is in the sub title
```

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 6]
```diff
@@ -48,11 +49,16 @@ public TitleChecker(BibDatabaseContext databaseContext) {
             valueOnlySpacesWithinCurlyBraces = matcher.replaceAll("");
         }
 
-        boolean hasCapitalLettersThatBibtexWillConvertToSmallerOnes = HAS_CAPITAL_LETTERS
-                .test(valueOnlySpacesWithinCurlyBraces);
-
-        if (hasCapitalLettersThatBibtexWillConvertToSmallerOnes) {
-            return Optional.of(Localization.lang("capital letters are not masked using curly brackets {}"));
+        // Delimiters are . ! ? ; :
```
Comment (koppor) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]: This line can be removed - I would assume that coders know that <kbd>Ctrl</kbd> + click on "DELIMITERS" leads to the definition of the variable.

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 7]
```diff
@@ -48,11 +49,16 @@ public TitleChecker(BibDatabaseContext databaseContext) {
...
+        String[] splitTitle = valueOnlySpacesWithinCurlyBraces.split(DELIMITERS);
+        for (String subTitle : splitTitle) {
+            subTitle = subTitle.trim();
+            if (subTitle.length() > 0) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]:
```suggestion
            if (!subTitle.isEmpty()) {
```

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 8]
```diff
@@ -48,11 +49,16 @@ public TitleChecker(BibDatabaseContext databaseContext) {
...
+                subTitle = subTitle.substring(1);
+            }
+            if (HAS_CAPITAL_LETTERS.test(subTitle)) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]: Please move this before the `}`. In this case, `subTitle` could be `0` characters long and thus no test is necessary

**Comment by eetian** [comment]
Hi @koppor, thank you for your review! I have made changes to the code. I found that there is an existing test, which is testTitleChecks() in IntegrityCheckTest.java, for this functionality. So I added test cases for the title with delimiters there. Please let me know if there is anything else I need to take care of. Happy to make a contribution.

File: CHANGELOG.md [hunk 9]
```diff
@@ -56,6 +56,7 @@ Note that this project **does not** adhere to [Semantic Versioning](http://semve
 - We fixed an issue where the group and the link column were not updated after changing the entry in the main table. [#5985](https://github.com/JabRef/jabref/issues/5985)
 - We fixed an issue where reordering the groups was not possible after inserting an article. [#6008](https://github.com/JabRef/jabref/issues/6008)
 - We fixed an issue where citation styles except the default "Preview" could not be used. [#56220](https://github.com/JabRef/jabref/issues/5622)
+- We fixed an issue where warning is displayed when title is made of two sentences. [#5832](https://github.com/JabRef/jabref/issues/5832)
```
Comment (Siedlerchr) [inline CHANGELOG.md]:
```suggestion
- We fixed an issue where a warning was displayed when the title content is made up of two sentences. [#5832](https://github.com/JabRef/jabref/issues/5832)
```

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java [hunk 10]
```diff
@@ -12,6 +12,7 @@
 public class TitleChecker implements ValueChecker {
 
     private static final Pattern INSIDE_CURLY_BRAKETS = Pattern.compile("\\{[^}\\{]*\\}");
+    private static final String DELIMITERS = "(\\.|\\!|\\?|\\;|\\:)";
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/integrity/TitleChecker.java]: as this is a regex, too, you should create a Pattern analogous to the other ones and then call the split method on the pattern. The Pattern.compile is more efficient when the regex is used multiple times

File: src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java [hunk 11]
```diff
@@ -194,6 +205,19 @@ void testTitleChecks() {
         assertCorrect(withMode(createContext(StandardField.TITLE, "This is a {Title}"), BibDatabaseMode.BIBLATEX));
         assertCorrect(withMode(createContext(StandardField.TITLE, "{C}urrent {C}hronicle"), BibDatabaseMode.BIBLATEX));
         assertCorrect(withMode(createContext(StandardField.TITLE, "{A Model-Driven Approach for Monitoring {ebBP} BusinessTransactions}"), BibDatabaseMode.BIBLATEX));
+        assertCorrect(withMode(createContext(StandardField.TITLE, "This is a sub title 1: This is a sub title 2"), BibDatabaseMode.BIBLATEX));
```
Comment (koppor) [inline src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java]: It is good to have tests here. These are more a end-to-end-test. Would you mind to add separate tests to `TitleCheckerTest.java`. In IntelliJ, you can create this file using Ctrl+Shift+T (and pressing Enter in the dialog). It would really help to have the tests for the TitleChecker in a dedicated class, which helps to focus on the implementation. -- This should be very easy to do, but will help future work on the title checker (maybe in one, two years) to ensure that the functionality is still correct.

**Comment by koppor** [comment]
@eetian We are in "nitpicking" mode 😇. It might cost more time to refine the code. To provide some background: The JabRef team decided to improve the code quality. Thus, we aim for all code being a model for Java coders to learn how things work. See https://devdocs.jabref.org/development-strategy for details. Thus, we kindly ask you to include our feedback. Please do not hesitate to contact us in case you have any question.

File: CHANGELOG.md (hunk 9 above)
Comment (eetian) [reply CHANGELOG.md]: Hi @Siedlerchr, thank you for the check! I changed it.

File: src/main/java/org/jabref/logic/integrity/TitleChecker.java (hunk 10 above)
Comment (eetian) [reply src/main/java/org/jabref/logic/integrity/TitleChecker.java]: Thanks for pointing out this. Good to learn! I changed it.

File: src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java (hunk 11 above)
Comment (eetian) [reply src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java]: Thank you for your explanation! As suggested, I have added separate tests for titles having delimiters in the new file. Those method names may not be perfect. If there is a better way to rename it, please let me know.

**Comment by koppor** [comment]
@eetian Thank you for keeping working on it. Good to go now!
