### PR TITLE
Fix: Unable to remove multiline property from field

### LINKED ISSUE #11897: Entry types preferences: Unable to remove multiline property from field
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Other (please describe below)

### Details on version and operating system

OS independent

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Custom entry types 
I changed the "Author" field to multiline for the "Article" entry type in preferences.

Image

After restarting JabRef, the "Author" field became multiline for all entry types, even though it should only apply to "Article".

Now, when I try to change the "Author" field back to a single line by unchecking the option and restarting, nothing happens. To remove the multiline setting, I have to update it for all entry types.

>  Does Reset to default work?

No, it doesn’t. It only resets the selected entry type, the "Article", but the "Author" field is still marked as multiline in other entry types. So, when saving, it remains multiline because of those other types.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by pluto-han**
### Related issues and pull requests
Closes #11897 

### PR Description
Based on the work in https://github.com/JabRef/jabref/pull/12040 from @PressJump, I added the resetMultilineFieldsToDefault() method. This method sets MULTILINE_TEXT property of each standard field and nonWrappableFields to default.

### Steps to test
1. Change the "Author", "Volume", "Number" fields to multiline for the "Article" entry type in preferences. 
image

2. Save preferenc and restart jabref. The "Author" field became multiline for all entry types as it is global.

3. Untick "Author" field and save. "Author" field for all entry types is removed.
image

4. Click "reset to default". Multiline properties(In this case, "Volume" and "Number") from all fields are removed.
image

 
### Checklist
- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [x] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

**Comment by koppor** [comment]
Related PR: https://github.com/JabRef/jabref/pull/11230

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java [hunk 1]
```diff
@@ -49,6 +51,11 @@ public class CustomEntryTypesTabViewModel implements PreferenceTabViewModel {
     private final StringProperty newFieldToAdd = new SimpleStringProperty("");
     private final ObservableList<EntryTypeViewModel> entryTypesWithFields = FXCollections.observableArrayList(extractor -> new Observable[] {extractor.entryType(), extractor.fields()});
     private final List<BibEntryType> entryTypesToDelete = new ArrayList<>();
+    private final Set<StandardField> DEFAULT_MULTILINE_FIELDS = Set.of(
```
Comment (Siedlerchr) [inline jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java]: I suggest move this into StandardFields as a static variable so it's more easily adaptable.

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java [hunk 2]
```diff
@@ -218,4 +225,30 @@ public ValidationStatus entryTypeValidationStatus() {
...
+            if (DEFAULT_MULTILINE_FIELDS.contains(field)) {
+                field.getProperties().add(FieldProperty.MULTILINE_TEXT);
+            } else {
+                field.getProperties().remove(FieldProperty.MULTILINE_TEXT);
+            }
+        }
+    }
+
+    private List<Field> getDefaultNonWrappableFields() {
+        Object defaultNonWrappableFields = preferences.getDefaults().get(JabRefCliPreferences.NON_WRAPPABLE_FIELDS);
```
Comment (Siedlerchr) [inline jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java]: @calixtus  Is there a better option to get a default value of a specifci preference?

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java (hunk 1 above)
Comment (pluto-han) [reply jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java]: Thank you for your review. I have set it as a static variable

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java (hunk 2 above)
Comment (calixtus) [reply jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java]: Conversion to new preferences must be continued in JabRefCliPreferences following the example for JabRefGuiPreferences (see https://github.com/JabRef/jabref/issues/14400 ).

Direct access to JabRefCliPreferences is not acceptable anymore.

File: jabgui/src/test/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModelTest.java [hunk 3]
```diff
@@ -39,6 +44,7 @@ void setup() {
         fieldPreferences = mock(FieldPreferences.class);
         when(fieldPreferences.getNonWrappableFields()).thenReturn(FXCollections.observableArrayList());
         when(preferences.getFieldPreferences()).thenReturn(fieldPreferences);
+        when(preferences.getDefaults()).thenReturn(Map.of(JabRefCliPreferences.NON_WRAPPABLE_FIELDS, "pdf;ps;url;doi;file;isbn;issn"));
```
Comment (calixtus) [inline jabgui/src/test/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModelTest.java]: This should be part of defaults in a PreferencesObject

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java (hunk 2 above)
Comment (pluto-han) [reply jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java]: > Conversion to new preferences must be continued in JabRefCliPreferences following the example for JabRefGuiPreferences (see [#14400](https://github.com/JabRef/jabref/issues/14400) ).

Hi @calixtus , do you mean that `getDefaultValue()` should be done in a specific preference class(in this case `FieldPreference`), instead of directly accessing `JabRefCliPreference.getDefaults()`?

And according to #14400, I think we should also reset `FieldPreference`? For example, remove default values from `JabRefCliPreference` and add get/set default methods in `FieldPreference`.

**Comment by pluto-han** [comment]
Hi devs, I made some resettings to `FieldPreference` according to the examples in #14400. Now default value can only be retrieved from `FieldPreference`.

Moreover, I found that "reset to default" button works as expected, but "reset preference" would not reset multiline property. I fixed that issue by adding `resetMultilineFieldsToDefault()` in `CustomEntryTypesTabViewModel#setValue()`

File: jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java [hunk 4]
```diff
@@ -623,9 +623,6 @@ public JabRefCliPreferences() {
         defaults.put(OPEN_FILE_EXPLORER_IN_LAST_USED_DIRECTORY, Boolean.FALSE);
         defaults.put(DEFAULT_CITATION_KEY_PATTERN, "[auth][year]");
         defaults.put(UNWANTED_CITATION_KEY_CHARACTERS, "-`ʹ:!;?^$");
-        defaults.put(RESOLVE_STRINGS_FOR_FIELDS, "author;booktitle;editor;editora;editorb;editorc;institution;issuetitle;journal;journalsubtitle;journaltitle;mainsubtitle;month;monthfiled;publisher;shortauthor;shorteditor;subtitle;titleaddon");
```
Comment (Siedlerchr) [inline jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java:631]: Shouldn't these defaults be kept @calixtus

Comment (calixtus) [reply jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java:631]: Moved to FieldPreferences#getDefaults

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java [hunk 5]
```diff
@@ -25,6 +26,24 @@ public FieldPreferences(boolean resolveStrings,
         this.nonWrappableFields = FXCollections.observableArrayList(nonWrappableFields);
     }
 
+    private FieldPreferences() {
+        this(
+                true,
+                List.copyOf(FieldFactory.parseFieldList("author;booktitle;editor;editora;editorb;editorc;institution;issuetitle;journal;journalsubtitle;journaltitle;mainsubtitle;month;monthfiled;publisher;shortauthor;shorteditor;subtitle;titleaddon")),
+                List.copyOf(FieldFactory.parseFieldList("pdf;ps;url;doi;file;isbn;issn"))
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java]: Comments missing

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java [hunk 6]
```diff
@@ -25,6 +26,24 @@ public FieldPreferences(boolean resolveStrings,
         this.nonWrappableFields = FXCollections.observableArrayList(nonWrappableFields);
     }
 
+    private FieldPreferences() {
+        this(
+                true,
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java:34]: I believe this was false...

Image

Comment (calixtus) [reply jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java:34]: Just saw the comment.

Comment (calixtus) [reply jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java:34]: Image

File: jablib/src/main/java/org/jabref/model/entry/field/StandardField.java [hunk 7]
```diff
@@ -149,6 +149,11 @@ public enum StandardField implements Field {
     // endregion
 
     public static final Set<Field> AUTOMATIC_FIELDS = Set.of(OWNER, TIMESTAMP, CREATIONDATE, MODIFICATIONDATE);
+    public static final Set<StandardField> DEFAULT_MULTILINE_FIELDS = Set.of(
+            ABSTRACT,
+            COMMENT,
+            REVIEW
+    );
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/model/entry/field/StandardField.java]: Maybe better built in instead of default?

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java [hunk 8]
```diff
@@ -218,4 +221,22 @@ public ValidationStatus entryTypeValidationStatus() {
...
+
+    private void resetStandardFieldMultilineToDefaults() {
+        for (StandardField field : StandardField.values()) {
+            if (StandardField.DEFAULT_MULTILINE_FIELDS.contains(field)) {
+                field.getProperties().add(FieldProperty.MULTILINE_TEXT);
+            } else {
+                field.getProperties().remove(FieldProperty.MULTILINE_TEXT);
+            }
+        }
+    }
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java:241]: Will this also happen if all the preferences are reset? (CliPreferences#reset)

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java (hunk 5 above)
Comment (pluto-han) [reply jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java]: comments updated

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java (hunk 8 above)
Comment (pluto-han) [reply jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java:241]: Yes, reset will call `CustomEntryTypesTabViewModel#setVaule` -> `this.resetMultilineFieldsToDefault();`

File: jablib/src/main/java/org/jabref/model/entry/field/StandardField.java (hunk 7 above)
Comment (pluto-han) [reply jablib/src/main/java/org/jabref/model/entry/field/StandardField.java]: Do you mean put these to `CustomEntryTypesTabViewModel` instead of `StandardField`? 
I think put in `StandardField` as default could be more extensible and adaptable.

Comment (calixtus) [reply jablib/src/main/java/org/jabref/model/entry/field/StandardField.java]: No, I meant just rename the constant to avoid confusion with default values in preferences

Comment (pluto-han) [reply jablib/src/main/java/org/jabref/model/entry/field/StandardField.java]: Yes, this sounds better!

Comment (pluto-han) [reply jablib/src/main/java/org/jabref/model/entry/field/StandardField.java]: Variable name updated.

File: jablib/src/main/java/org/jabref/model/entry/field/StandardField.java [hunk 9]
```diff
@@ -149,6 +149,11 @@ public enum StandardField implements Field {
     // endregion
 
     public static final Set<Field> AUTOMATIC_FIELDS = Set.of(OWNER, TIMESTAMP, CREATIONDATE, MODIFICATIONDATE);
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/model/entry/field/StandardField.java:151]: This would be the extra mile.

File: jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java [hunk 10]
```diff
@@ -1128,6 +1126,7 @@ public void importPreferences(Path path) throws JabRefException {
 
         // in case of incomplete or corrupt xml fall back to current preferences
         getProxyPreferences().setAll(ProxyPreferences.getDefault());
+        getFieldPreferences().setAll(FieldPreferences.getDefault());
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java]: ProxyPreferences line is also buggy.
```suggestion
        getProxyPreferences().setAll(getProxyPreferencesFromBackingStore(ProxyPreferences.getDefault()));
        getFieldPreferences().setAll(getFieldPreferencesFromBackingStore(FieldPreferences.getDefault()));
```

Comment (pluto-han) [reply jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java]: > getProxyPreferences().setAll(getProxyProxyPreferencesFromBackingStore(ProxyPreferences.getDefault()));

Should be `getProxyPreferencesFromBackingStore` right :-)?

Comment (calixtus) [reply jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java]: Fixed

File: jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java [hunk 11]
```diff
@@ -1642,6 +1634,20 @@ public FieldPreferences getFieldPreferences() {
...
+                List.copyOf(FieldFactory.parseFieldList(get(RESOLVE_STRINGS_FOR_FIELDS,
+                        FieldFactory.serializeFieldsList(defaults.getResolvableFields())))),
+                List.copyOf(FieldFactory.parseFieldList(get(NON_WRAPPABLE_FIELDS,
+                        FieldFactory.serializeFieldsList(defaults.getNonWrappableFields()))))
+        );
+    }
+
+    //*************************************************************************************************************
+    // Linked files preferences
+    //*************************************************************************************************************
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java]: These divider comments should be left out

Comment (pluto-han) [reply jablib/src/main/java/org/jabref/logic/preferences/JabRefCliPreferences.java]: updated

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java [hunk 12]
```diff
@@ -25,6 +26,27 @@ public FieldPreferences(boolean resolveStrings,
...
     }
 
+    private FieldPreferences() {
+        this(
+                // Default resolve string setting
+                true,
+                // Default resolvable field
+                List.copyOf(FieldFactory.parseFieldList("author;booktitle;editor;editora;editorb;editorc;institution;issuetitle;journal;journalsubtitle;journaltitle;mainsubtitle;month;monthfiled;publisher;shortauthor;shorteditor;subtitle;titleaddon")),
+                // Default non wrappable field
+                List.copyOf(FieldFactory.parseFieldList("pdf;ps;url;doi;file;isbn;issn"))
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java]: Please extract these two strings as constants and use.

Comment (pluto-han) [reply jablib/src/main/java/org/jabref/logic/bibtex/FieldPreferences.java]: updated

**Comment by pluto-han** [comment]
Resolved conflicts with #15395

File: jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java (hunk 2 above)
Comment (calixtus) [reply jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java]: JabRefPreferences.getDefaults is to be removed. Follow the many example prs that were already made.

Comment (pluto-han) [reply jabgui/src/main/java/org/jabref/gui/preferences/customentrytypes/CustomEntryTypesTabViewModel.java]: Yeah I have removed `getDefaults` in `FieldPreference`, is there anything I should do?

**Comment by calixtus** [comment]
LGTM, lets move forward
