### PR TITLE
Fix reset and import for PreviewPreferences

### LINKED ISSUE #14400: Implement resetting for one preference
For resetting preferences, the handling of the preference objects needs to be changed.

This issue describes the steps to do.

> [!NOTE]
> We created sub issues for each prefernce

PR showing the changes for `WorkspacePreferences`: https://github.com/JabRef/jabref/pull/13894 

In JabRefGui/CliPreferences remove (but keep the values in mind)
grafik

In XXXPreferences class
- Add private default constructor (use the values from the step before)
grafik

- Add getDefault method
grafik

- Add setAll method
grafik

In JabRefGui/CliPreferences class
- Add fromBackingStore method
grafik

- Modify getXXXPreferences method
grafik

- Add to clear / importPreferences method
grafik

---

- [ ] **Internal note** As soon as this issue is solved, we need to create sub issues for `JabRefCliPreferences`.

**Pick one preference from https://github.com/JabRef/jabref/blob/92cc09d5a299b137fc48dfd8c3b26817d1dccb2e/jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java#L227-L246** and handle it.

### PR DESCRIPTION
**Pull request by calixtus**
### Related issues and pull requests

Closes #14400
Follow-up #14959

### PR Description

- Enables reset and import
- Some cleanups and architectural fixes (single source of truth, code placement in packages)
- Moved BstPreviewLayout, TextBasedPreviewLayout and CitationStylePreviewLayout to preview Layout for correct JBang compilation
- Cleanups and IDE suggestions along the way

ToDo:
- [x] ~Add default styles after reset~

### Steps to test

Preferences > Reset / Import

### Checklist

   

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [.] I added JUnit tests for changes (if applicable)
- [.] I added screenshots in the PR description (if change is visible to the user)
- [.] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [.] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/preferences/preview/PreviewTabViewModel.java [hunk 1]
```diff
@@ -79,7 +81,8 @@ public class PreviewTabViewModel implements PreferenceTabViewModel {
     private final StringProperty sourceTextProperty = new SimpleStringProperty("");
 
     private final DialogService dialogService;
-    private final PreviewPreferences previewPreferences;
+    private final JournalAbbreviationRepository abbreviationRepository;
+    @org.jetbrains.annotations.NotNull private final GuiPreferences preferences;
```
Comment (Siedlerchr) [inline jabgui/src/main/java/org/jabref/gui/preferences/preview/PreviewTabViewModel.java]: wrong non null

Comment (calixtus) [reply jabgui/src/main/java/org/jabref/gui/preferences/preview/PreviewTabViewModel.java]: slipped through, but still draft

File: jabgui/src/main/java/org/jabref/gui/preview/PreviewPreferences.java [hunk 2]
```diff
@@ -5,46 +5,68 @@
...
+    }
+
+    public void setAll(PreviewPreferences previewPreferences) {
+        this.layoutCycle.setAll(previewPreferences.layoutCycle);
+        this.layoutCyclePosition.setValue(previewPreferences.layoutCyclePosition.getValue());
+        this.showPreviewAsExtraTab.setValue(previewPreferences.showPreviewAsExtraTab.getValue());
+        this.showPreviewEntryTableTooltip.setValue(previewPreferences.showPreviewEntryTableTooltip.getValue());
+        this.bstPreviewLayoutPaths.setAll(previewPreferences.bstPreviewLayoutPaths);
+        this.shouldDownloadCovers.setValue(previewPreferences.shouldDownloadCovers.getValue());
     }
```
[the remark this answers is not in the document]
Comment (calixtus) [reply jabgui/src/main/java/org/jabref/gui/preview/PreviewPreferences.java:90]: grafik
