### PR TITLE
Fix for MathSciNet search

### LINKED ISSUE #8170: MathSciNet import per ID and search does not work (anymore)
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 20.04

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. (a) Search in MathSciNet using the web search interface OR (b) enter a MathSciNet ID to add a new bibentry via "+"
2. You get (a) an exception OR (b) a network error

Tested it with: 
JabRef 5.4--2021-10-19--f328363
Linux 5.11.0-38-generic amd64 
Java 16.0.2 
JavaFX 17.0.0.1+1

### Appendix

```
org.jabref.logic.importer.FetcherException: A network error occurred while fetching from https://mathscinet.ams.org/mathscinet/search/publications.html?pg7=ALLF&s7=test&r=1&extend=1&fmt=bibtex
	at org.jabref@5.4.329/org.jabref.logic.importer.SearchBasedParserFetcher.getBibEntries(Unknown Source)
	at org.jabref@5.4.329/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref@5.4.329/org.jabref.logic.importer.SearchBasedFetcher.performSearch(Unknown Source)
	at org.jabref@5.4.329/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$3(Unknown Source)
	at org.jabref@5.4.329/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.4.329/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.4.329/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://mathscinet.ams.org/mathscinet/search/publications.html?pg7=ALLF&s7=test&r=1&extend=1&fmt=bibtex
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref@5.4.329/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	... 13 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://mathscinet.ams.org/mathscinet/search/publications.html?pg7=ALLF&s7=test&r=1&extend=1&fmt=bibtex
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref@5.4.329/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	... 14 more
```

### LINKED ISSUE #10996: Mathscinet search is not working
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

_No response_

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Was #10499 closed because it was fixed, or because work is not planned? 

Active subscription to Mathscinet confirmed in browser

Perform Web search Mathscinet  in Jabref

### Appendix

...
<details>

<summary>Log File</summary>

Error:
org.jabref.logic.importer.FetcherException: An internal parser error occurred while fetching from https://mathscinet.ams.org/mathscinet/api/publications/search?query=algebraic+geometric+codes+basic+notions&currentPage=1&pageSize=100
	at org.jabref@5.12.60000/org.jabref.logic.importer.SearchBasedParserFetcher.getBibEntries(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.logic.importer.SearchBasedFetcher.performSearch(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$2(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.12.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jabref.logic.importer.ParseException: Error when parsing entry
	at org.jabref@5.12.60000/org.jabref.logic.importer.fetcher.MathSciNet.lambda$getParser$0(Unknown Source)
	... 13 more
Caused by: kong.unirest.json.JSONException: JSONObject["all"] not found.
	at org.jabref.merged.module@5.12.60000/kong.unirest.json.JSONObject.getProperty(Unknown Source)
	at org.jabref.merged.module@5.12.60000/kong.unirest.json.JSONObject.getJSONObject(Unknown Source)
	... 14 more 

</details>

### PR DESCRIPTION
**Pull request by subhramit**
Closes #10996 - the issue exposed a bug where MathSciNet search gives the following parsing error:

Screenshot 2024-03-19 181336
(Replicated locally)

To fix the issue, a new parser has been built for MathSciNet which parses the retrieved JSON results correctly. A test has been added as well.
Files modified:
[jabref/src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java](https://github.com/JabRef/jabref/blob/2a7fc1aa0e2bc3edad3291e96a40087cded4da03/src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java)
[jabref/src/test/java/org/jabref/logic/importer/fetcher/MathSciNet.java](https://github.com/JabRef/jabref/blob/2a7fc1aa0e2bc3edad3291e96a40087cded4da03/src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java)
The search now works fine:
Screenshot 2024-03-19 235840

Edit: This pull also closes #8170 
### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 1]
```diff
@@ -102,34 +100,141 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
     }
 
+    private BibEntry jsonItemToBibEntry(JSONObject item) throws ParseException {
+        try {
+            BibEntry entry = new BibEntry();
+            entry.setType(StandardEntryType.Article);
+
+            // Define the field mappings
+            Map<StandardField, String[]> fieldMappings = Map.ofEntries(
+                    Map.entry(StandardField.TITLE, new String[]{"titles", "title"}),
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:150]: To be honest, I don't really don't get this, what is the purpose of the String array and why are there some fields duplicated?

**Comment by calixtus** [comment]
Hi, thanks for your pull request, on first look, your changes are promising. Thanks especially for providing a test with your changes. However, there are some small issues with your codestyle and the MathSciNetTest is failing. Don't worry about the other fetchertests for now.
You can read about setting up your workspace, so it automatically cares about the codestyle here:
grafik
You can also fix the OpenRewrite test by running `gradle rewriteRun` from the terminal/console.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 1 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:153]: Hi, following is a snippet from the "results" JSON that we had in the issue page. I've used a [JSON Formatter](https://jsonformatter.org/json-pretty-print) to visualize it better.
image
To retrieve the journal value, we need to navigate through the issue object twice, then the journal object, and finally access the shortTitle value. Here, the String array {"issue", "issue", "journal", "shortTitle"} represents the path to reach the journal value in the JSON response. 
In a nutshell, the String array associated with each StandardField represents the path to reach the desired value in the JSON response, if I get your question correctly.

Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:153]: Okay, thanks for the explanation. Was not directly obvious. I will try to think if this can be made a bit better. I try to check back tomorrow.

**Comment by subhramit** [comment]
> Hi, thanks for your pull request, on first look, your changes are promising. Thanks especially for providing a test with your changes. However, there are some small issues with your codestyle and the MathSciNetTest is failing. Don't worry about the other fetchertests for now. You can read about setting up your workspace, so it automatically cares about the codestyle here: https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html You can also fix the OpenRewrite test by running `gradle rewriteRun` from the terminal/console.

Hey, thanks! I missed the codestyle extension. I'll also have a look at the test and get back.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 1 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:153]: Sure, please let me know!

**Comment by subhramit** [comment]
Done! @calixtus

File: CHANGELOG.md [hunk 2]
```diff
@@ -73,7 +73,7 @@ Note that this project **does not** adhere to [Semantic Versioning](https://semv
 - Clicking on the crossref and related tags in the entry editor jumps to the linked entry. [#5484](https://github.com/JabRef/jabref/issues/5484) [#9369](https://github.com/JabRef/jabref/issues/9369)
 - We fixed an issue where JabRef could not parse absolute file paths from Zotero exports. [#10959](https://github.com/JabRef/jabref/issues/10959)
 - We fixed an issue where an exception occured when toggling between "Live" or "Locked" in the internal Document Viewer. [#10935](https://github.com/JabRef/jabref/issues/10935)
-- Fixed an issue on Windows where the browser extension reported failure to send an entry to JabRef even though it was sent properly. [JabRef-Browser-Extension#493](https://github.com/JabRef/JabRef-Browser-Extension/issues/493)
```
Comment (koppor) [inline CHANGELOG.md:76]: Do not change existing CHANGELOG.md entries.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 3]
```diff
@@ -102,34 +104,140 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
                 throw new ParseException("Error when parsing entry", e);
             }
             return entries;
         };
     }
 
+    private BibEntry jsonItemToBibEntry(JSONObject item) throws ParseException {
+        try {
+            BibEntry entry = new BibEntry();
+            entry.setType(StandardEntryType.Article);
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:150]:
```suggestion
            BibEntry entry = new BibEntry(StandardEntryType.Article);
```

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 4]
```diff
@@ -102,34 +104,140 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+
+            // Define the field mappings
+            Map<StandardField, String[]> fieldMappings = Map.ofEntries(
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:153]: Make this a constant in the class -- `private final`

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 5]
```diff
@@ -102,34 +104,140 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                    Map.entry(StandardField.TITLE, new String[]{"titles", "title"}),
+                    Map.entry(StandardField.AUTHOR, new String[]{"authors"}),
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:155]: Java has more advanced data types. Use `List.of(...)` instead of `String[]{...}`-

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 6]
```diff
@@ -102,34 +104,140 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                entry.setField(StandardField.MR_NUMBER, mrNumber);
+            }
+
+            return entry;
+        } catch (JSONException exception) {
+            throw new ParseException("MathSciNet API JSON format has changed", exception);
+        }
+    }
+
+    private String getOrNull(JSONObject item, String... keys) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:201]: Java has `Optional`. Return `Optional<String>`.

File: src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java [hunk 7]
```diff
@@ -84,4 +86,29 @@ void searchByIdFindsEntry() throws Exception {
...
...},\"translatedIssue\":null},\"book\":null,\"reviewer\":{\"public\":true,\"reviewers\":[{\"authId\":889610,\"rvrCode\":85231,\"name\":\"Jitman, Somphong\"}]},\"paging\":{\"paging\":{\"text\":\"5414--5418\"},\"translatedPaging\":null},\"counts\":{\"cited\":2},\"itemType\":\"Reviewed\",\"articleUrl\":\"https://doi.org/10.1109/TIT.2020.2977319\",\"openURL\":{\"imageLink\":\"http://www.lib.unb.ca/img/asin/res20x150.gif\",\"targetLink\":\"https://unb.on.worldcat.org/atoztitles/link?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&rfr_id=info:sid/ams.org:MathSciNet&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft_id=info:doi/10.1109%2FTIT.2020.2977319&rft.aufirst=Tim&rft.auinit=TL&rft.auinit1=T&rft.auinitm=L&rft.aulast=Alderson&rft.genre=article&rft.issn=00189448&rft.title=Institute of Electrical and Electronics Engineers  Transactions on Information Theory&rft.atitle=On the weights of general MDS codes&rft.stitle=IEEE Trans  Inform  Theory&rft.volume=66&rft.date=2020&rft.spage=5414&rft.epage=5418&rft.pages=5414-5418&rft.issue=9&rft.jtitle=Institute of Electrical and Electronics Engineers  Transactions on Information Theory\",\"textLink\":\"\"},\"prePubl\":null,\"public\":true}],\"total\":31}";
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java:92]: Java has multiline string constants. Please use

```java
  String json= """...the json
     content
     ....
     """
```

File: src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java [hunk 8]
```diff
@@ -84,4 +86,29 @@ void searchByIdFindsEntry() throws Exception {
...
+
+        InputStream inputStream = new ByteArrayInputStream(json.getBytes(StandardCharsets.UTF_8));
+        List<BibEntry> entries = fetcher.getParser().parseEntries(inputStream);
+
+        assertNotNull(entries);
+        assertFalse(entries.isEmpty());
+        assertEquals(1, entries.size());
```
Comment (koppor) [inline src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java:99]: Please read at other test cases how it works.

It should be something like

```java
    assertEquals(List.of(new BibEntry()
   .withField(...)
...
```

**Review by koppor — CHANGES_REQUESTED** [review]

File: src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java (hunk 8 above)
Comment (subhramit) [reply src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java]: Hi, @koppor , I've made changes according to your reviews. Could you take a look again and let me know if anything else is needed to be done?

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 9]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+            return entry;
+        } catch (JSONException exception) {
+            throw new ParseException("MathSciNet API JSON format has changed", exception);
+        }
+    }
+
+    private Optional<String> getOrNull(JSONObject item, List<String> keys) {
+        Object value = item;
+        for (String key : keys) {
+            if (value instanceof JSONObject) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:198]:
```suggestion
            if (value instanceof JSONObject obj) {
             ....
```

You can use the new instance of pattern matching syntax,  which makes the extra casting step necessary
https://docs.oracle.com/en/java/javase/17/language/pattern-matching-instanceof-operator.html#GUID-843060B5-240C-4F47-A7B0-95C42E5B08A7

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 1 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java]: Please add a Java comment to explain.

File: CHANGELOG.md (hunk 2 above)
Comment (koppor) [reply CHANGELOG.md:76]: No need to force push..

Use `gitk` to get to know about the status. See https://lostechies.com/joshuaflanagan/2010/09/03/use-gitk-to-understand-git/ for details.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 10]
```diff
@@ -46,7 +48,18 @@
 public class MathSciNet implements SearchBasedParserFetcher, EntryBasedParserFetcher, IdBasedParserFetcher {
     private static final Logger LOGGER = LoggerFactory.getLogger(MathSciNet.class);
     private final ImportFormatPreferences preferences;
-
+    // Define the field mappings
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:51]: Remove the comment, because the code `fieldMappings = Map` already says it.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 11]
```diff
@@ -46,7 +48,18 @@
...
+    private final Map<StandardField, List<String>> fieldMappings = Map.ofEntries(
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:52]: Please do `private static final`. The variable then needs to be named `FIELD_MAPPINGS`.

I think, you can simply to

```java
   Map.of(
     StandardField.TITLE, List.of("titles", "title"),
     StandardField.AUTHOR, List.of("authors")
...
```

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 12]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
 
+    private BibEntry jsonItemToBibEntry(JSONObject item) throws ParseException {
+        try {
+            BibEntry entry = new BibEntry(StandardEntryType.Article);
+            // Set fields based on the mappings
+            for (Map.Entry<StandardField, List<String>> mapEntry : fieldMappings.entrySet()) {
+                StandardField field = mapEntry.getKey();
+                List<String> path = mapEntry.getValue();
+
+                String value;
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:166]:
```suggestion
                Optional<String> value;
```

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 13]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                if (field == StandardField.AUTHOR) {
+                    value = toAuthors(item.optJSONArray(path.getFirst()));
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:168]:
```suggestion
                    value = Optional.of(toAuthors(item.optJSONArray(path.getFirst())));
```

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 14]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                } else if (field == StandardField.KEYWORDS) {
+                    value = getKeywords(item.optJSONObject(path.getFirst()));
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:170]:
```suggestion
                    value = Optional.of(getKeywords(item.optJSONObject(path.getFirst())));
```

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 15]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                } else {
+                    value = getOrNull(item, path).orElse(null);
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:172]: Just name the method `getOther`, because it is not author or keywords

```suggestion
                    value = getOthers(item, path);
```

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 16]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
             }
             return entries;
         };
     }
 
+    private BibEntry jsonItemToBibEntry(JSONObject item) throws ParseException {
+        try {
+            BibEntry entry = new BibEntry(StandardEntryType.Article);
+            // Set fields based on the mappings
+            for (Map.Entry<StandardField, List<String>> mapEntry : fieldMappings.entrySet()) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:162]: Even if I commented below to use the fieldmappings, I would handle author and keyword separatetly. You are explicitly handling these two cases below. Why not

```java
entry.put(StandardField.AUTHOR, toAuthors(item.optJSONArray("authors"));
entry.put(StandardField.KEYWORDS, toAuthors(item.optJSONArray("primaryClass"));
```

and then the foreach for the other field mappings?

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 17]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                    value = toAuthors(item.optJSONArray(path.getFirst()));
+                } else if (field == StandardField.KEYWORDS) {
+                    value = getKeywords(item.optJSONObject(path.getFirst()));
+                } else {
+                    value = getOrNull(item, path).orElse(null);
+                }
+
+                if (value != null) {
+                    entry.setField(field, value);
+                }
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:177]:
```suggestion
  value.ifPresent(v -> entry.setField(field, v));
```

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 18]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+            }
+            // Handle articleUrl and mrnumber fields separately
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:179]: Can you say "why" here?

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 19]
```diff
@@ -102,34 +115,123 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                value = ((JSONObject) value).opt(key);
+            } else if (value instanceof JSONArray) {
+                value = ((JSONArray) value).opt(Integer.parseInt(key));
+            } else {
+                break;
+            }
+        }
+
+        if (value instanceof String stringValue) {
+            return Optional.of(new String(stringValue.getBytes(StandardCharsets.ISO_8859_1), StandardCharsets.UTF_8));
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:208]: Can you explain this necessity of charset conversion? Why can't the string be used directly?

**Review by koppor — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 19 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:208]: Yes, if used directly, I was getting these characters, for example:
Screenshot 2024-03-20 004828

Whereas the expected was Alonso-Morón, M. /Gómez, A.González. And many more.

Comment (koppor) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:208]: Please add a comment to a new method. That code appears twice: move it to a method `fixStringEncoding`

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 18 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:179]: So if we take a look at the general json structure, for example:
image
We can see that mrnumber and articleurl are direct key:value mappings, so the strings could be obtained directly. Whereas for the rest of the fields, such as title or authors, we had to navigate their respective nested structures.
We could've handled them uniformly as well, should I change it?

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 19 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:208]: Will do. Thank you for putting so much effort reviewing. I'll make all these changes an put another review request.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 18 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:177]: Just add a Java comment (maybe a bit shorter than your text)

File: src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java [hunk 20]
```diff
@@ -84,4 +85,1347 @@ void searchByIdFindsEntry() throws Exception {
         Optional<BibEntry> fetchedEntry = fetcher.performSearchById("3537908");
         assertEquals(Optional.of(ratiuEntry), fetchedEntry);
     }
+
+    @Test
+    void getParser() throws Exception {
+        String json = """
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java:91]: I would suggest simply storing it as json file in the 
appropriate resources folder src/test/resources/importer/fetcher/ 
Otherwise the class is so very long... 

  `try (InputStream is = MathSciNetTest.class.getResourceAsStream(fileName)) { `

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 9 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:196]: Hi, I went through the docs. If I'm not wrong, did you mean that it would make the extra casting step "unnecessary"?

Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java]: I removed the casts and followed the new syntax. It is odd that IntelliJ is giving me red squiggly lines and a suggestion to cast it back. Will ignore for now.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 13 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:168]: Hi @koppor , I think this is not required, as it will change the type to ```Optional<Optional<String>>``` whereas we must assign an ```Optional<String>```. Please confirm.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 16 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:162]: Good point, will change this.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 9 above)
Comment (subhramit) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java]: Okay nope, I added the obj syntax but seems like the cast is necessary, else I'm getting this compilation error:
error: cannot find symbol
                value = value.opt(key);
                             ^
  symbol:   method opt(String)
  location: variable value of type Object

**Comment by subhramit** [comment]
I've made these new set of changes (wherever feasible, otherwise I've commented on your suggestions) and re-requested for review. I have learnt more from this single pull request regarding production-level code than I ever have from my three years of CS degree. Thank you so much for your valuable inputs and patience. @koppor @Siedlerchr

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 9 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java]: See the examples in the linked docs, you need to use value = obj.get... After the if

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 11 above)
Comment (calixtus) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java]: *The constant 😉

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java (hunk 13 above)
Comment (koppor) [reply src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java]: In case you changed `toAuthors` to return an Optional<String>, then no need to use another `Optional.of` wrapper. The answer was only in the context where `toAuthors` returned a `String` and `String value;` was asked to be converted to `Optional<String>`

File: src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java [hunk 21]
```diff
@@ -79,9 +76,25 @@ void searchByQueryFindsEntry() throws Exception {
     }
 
     @Test
-    @DisabledOnCIServer("CI server has no subscription to MathSciNet and thus gets 401 response")
-    void searchByIdFindsEntry() throws Exception {
-        Optional<BibEntry> fetchedEntry = fetcher.performSearchById("3537908");
-        assertEquals(Optional.of(ratiuEntry), fetchedEntry);
+    void getParser() throws Exception {
+        String fileName = "/importer/fetcher/jsonTest.json";
```
Comment (Siedlerchr) [inline src/test/java/org/jabref/logic/importer/fetcher/MathSciNetTest.java:80]: Java has a special folder for resources src/main/resoures and for test `src/test/resources` See the other importer test files there

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 22]
```diff
@@ -102,34 +117,137 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+                                        .map(author -> {
+                                            String name = author.optString("name", "");
+                                            return fixStringEncoding(name);
+                                        })
+                                        .collect(Collectors.joining(" and "));
+
+        return Optional.of(authorsString);
+    }
+
+    private String getKeywords(JSONObject primaryClass) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:218]: Please also use the `Optional<String>` thing you did at `toAuhtors`. Because of consistency.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 23]
```diff
@@ -102,34 +117,137 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+
+            // Set the rest of the fields based on the mappings
+            for (Map.Entry<StandardField, List<String>> mapEntry : FIELD_MAPPINGS.entrySet()) {
+                StandardField field = mapEntry.getKey();
+                List<String> path = mapEntry.getValue();
+
+                // Skip author and keywords fields as they are already set
+                if (field == StandardField.AUTHOR || field == StandardField.KEYWORDS) {
+                    continue;
+                }
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:179]: Just remove `StandardField.AUTHOR` and `StandardField.KEYWORDS` from `FIELD_MAPPING`. Think, this is the only "use" in the code, which savely can be removed.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 24]
```diff
@@ -102,34 +117,137 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+
+                Optional<String> value = getOthers(item, path);
+                value.ifPresent(v -> entry.setField(field, v));
+            }
+
+            // Handle articleUrl and mrnumber fields separately, as they are non-nested properties in the JSON and can be retrieved as Strings directly
+            String doi = item.optString("articleUrl", "");
+            if (!doi.isEmpty()) {
+                entry.setField(StandardField.DOI, doi);
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:188]: Try to route through `DOI#parse`. If that optional is present, use `doi.getNormalized()`, otherwise use the `doi` variable. In That way, the http prefix is removed if it is a valid doi, but the full string is kept in case of a DOI parsing error.

File: src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java [hunk 25]
```diff
@@ -102,34 +117,137 @@ public URL getUrlForIdentifier(String identifier) throws URISyntaxException, Mal
...
+        if (value instanceof String stringValue) {
+            return Optional.of(fixStringEncoding(stringValue));
+        } else if (value instanceof Integer intValue) {
+            return Optional.of(intValue.toString());
+        }
+
+        return Optional.empty();
+    }
+
+    // Method to change character set, to fix output string encoding
```
Comment (koppor) [inline src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java:246]: Convert to full JavaDoc:

```
/**
 * ... text ...
 */
```

**Review by koppor — DISMISSED** [review]
Some small code comments

**Comment by subhramit** [comment]
Made the third round of changes. @koppor @Siedlerchr 
Awaiting more comments if any!

**Comment by Siedlerchr** [comment]
I took the opportunity to fix some issues:

1. You probably accidentally removed the BibTex Parser. Some json resutls already deliver  
2. I renamed the resource file
3. Checked the test and found that the search by id returns a json  which contains bibtex that we can direclty throw at our parser

**Review by Siedlerchr — APPROVED** [review]

**Comment by subhramit** [comment]
> I took the opportunity to fix some issues:
> 
> 1. You probably accidentally removed the BibTex Parser. Some json resutls already deliver
> 2. I renamed the resource file
> 3. Checked the test and found that the search by id returns a json  which contains bibtex that we can direclty throw at our parser

Thank you so much. (1) is a huge one, don't know if this was because of sleepless coding or a slip of keyboard. (2) will remember this convention. (3) nice catch!
