### PR TITLE
Fix not on fx thread error for custom entry types

### LINKED ISSUE #5469: Uncaught exception on startup with a database
JabRef version
 
JabRef 5.0.0-dev--2019-10-17----26a1d29a3
Linux 5.0.0-31-generic amd64 
Java 12.0.2

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Start the program with a couple of databases open from the last session.  The exception box pops up immediately.

The problem might be connected with having custom entry types in the database:

1. close all databases
2. open database with three custom entry types:
```
@Comment{jabref-meta: saveOrderConfig:specified;author;false;date;false;title;true;}

@Comment{jabref-entrytype: manuscript: req[collection;library;location;shelfmark;shortcollection;shorthand;shortlibrary] opt[pagetotal;pagination;origin;catalog;columns;bookpagination;keywords;scribe;layer;annotation;contents;owner;dating;support;pages]}

@Comment{jabref-entrytype: review: req[author;date;journal;number;pages;related;relatedtype;volume] opt[url;urldate;doi]}

@Comment{jabref-entrytype: audio: req[author;date;editor;editortype;number;publisher;series;title;type] opt[url;urldate]}

```
And then I get a blank popup:

Screenshot from 2019-10-17 10-15-41

<details>
  <summary>Log File</summary>
  
  ```
  java.lang.IllegalStateException: Not on FX application thread; currentThread = JabRef CachedThreadPool
	at org.jabref.merged.module/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Stage.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Stage.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.HeavyweightDialog$1.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.HeavyweightDialog.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Dialog.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.util.BaseDialog.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.importer.ImportCustomEntryTypesDialog.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.importer.actions.CheckForNewEntryTypesAction.performAction(Unknown Source)
	at org.jabref/org.jabref.gui.importer.actions.OpenDatabaseAction.performPostOpenActions(Unknown Source)
	at org.jabref/org.jabref.JabRefGUI.openDatabases(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


  ```
</details>

Screenshot from 2019-10-17 10-08-18

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #5469 

Revert change done in  #5423 because the actual code just opens the already loaded databases.
At this point the databases are already loaded in a background thread

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [x] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/JabRefGUI.java [hunk 1]
```diff
@@ -89,8 +87,7 @@ private void openWindow(Stage mainStage) {
                 event.consume();
             }
         });
-
-        executorService.execute(this::openDatabases);
+        this.openDatabases();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/JabRefGUI.java]: This should still run later on the javafx (Platform.runLater)

Comment (Siedlerchr) [reply src/main/java/org/jabref/JabRefGUI.java]: But why? It's already on the FX thread or do you mean it should be quueed?

Comment (tobiasdiez) [reply src/main/java/org/jabref/JabRefGUI.java]: Yes, it should happen after the UI is created so that the user get's a quicker feedback that JabRef started.
