### PR TITLE
Log message after checking if the optional contains a value

### LINKED ISSUE #7933: Error when creating a new library
1. Run the application
2. Click in the "New Library" icon

<details>
  <summary>Log File</summary>
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.jabref/org.jabref.model.database.BibDatabaseContext.getFulltextIndexPath(BibDatabaseContext.java:223)
	at org.jabref/org.jabref.logic.pdf.search.indexing.PdfIndexer.of(PdfIndexer.java:55)
	at org.jabref/org.jabref.gui.LibraryTab$IndexUpdateListener.<init>(LibraryTab.java:866)
	at org.jabref/org.jabref.gui.LibraryTab.<init>(LibraryTab.java:137)
	at org.jabref/org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1057)
	at org.jabref/org.jabref.gui.importer.NewDatabaseAction.execute(NewDatabaseAction.java:31)
	at org.jabref/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.controlsfx.controls/org.controlsfx.control.action.Action.handle(Action.java:419)
	at org.controlsfx.controls/org.controlsfx.control.action.Action.handle(Action.java:64)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8889)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:831)
</details>

It seams we are executing the `get` method of an `Optional` before checking if it is present.

BibDatabaseContext:221

```java
public Path getFulltextIndexPath() {
    Path appData = getFulltextIndexBasePath();

    // This line should be inside the if statement
    LOGGER.info("Index path for {} is {}", getDatabasePath().get(), appData.toString());

    if (getDatabasePath().isPresent()) {
        return appData.resolve(String.valueOf(this.getDatabasePath().get().hashCode()));
    }

    return appData.resolve("unsaved");
}
```

### PR DESCRIPTION
**Pull request by C0lliNN**
Fixes #7933 

Hello folks! I discovered this project yesterday and I downloaded the repo and started to play around with UI when I found this unexpected behavior when trying to create a new library. After checking the stack trace, I found a log statement that tries to get a value from an `Optional` before checking if it is present. So, I change the position of the statement. Additionally, I refactored the path attribute, unwrapping it from the `Optional`. Ideally, the `Optional` should only be used as return type of methods, as advocated by [Brain Goetz](https://stackoverflow.com/questions/26327957/should-java-8-getters-return-optional-type/26328555#26328555) (Java Language Architect at Oracle).

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/model/database/BibDatabaseContext.java [hunk 1]
```diff
@@ -220,10 +219,12 @@ public static Path getFulltextIndexBasePath() {
...
         Path appData = getFulltextIndexBasePath();
-        LOGGER.info("Index path for {} is {}", getDatabasePath().get(), appData.toString());
+
         if (getDatabasePath().isPresent()) {
+            LOGGER.info("Index path for {} is {}", getDatabasePath().get(), appData.toString());
             return appData.resolve(String.valueOf(this.getDatabasePath().get().hashCode()));
         }
+
         return appData.resolve("unsaved");
     }
```
Comment (calixtus) [inline src/main/java/org/jabref/model/database/BibDatabaseContext.java:229]: I wonder if not that method should return the optional instead of 'unsaved', but this would probably be a bigger refactoring - if it makes any sense...

**Review by calixtus — COMMENTED** [review]
Hi @C0lliNN thanks for your interest in JabRef and your PR. Yes, you are probably right about the internal use of the optional in the class. On first sight a quick comment / something to think about.

**Comment by calixtus** [comment]
I just saw this fixes a bug, which prevents empty databases from being created, so this should be merged very quickly. @JabRef/developers

**Review by calixtus — APPROVED** [review]

File: src/main/java/org/jabref/model/database/BibDatabaseContext.java (hunk 1 above)
Comment (C0lliNN) [reply src/main/java/org/jabref/model/database/BibDatabaseContext.java:229]: I think it makes a lot of sense. Return an empty optional to represent an invalid path seems a better approach to me.

**Comment by C0lliNN** [comment]
> I just saw this fixes a bug, which prevents empty databases from being created, so this should be merged very quickly. @JabRef/developers

Sure! We can refactor this method later.

**Review by Siedlerchr — APPROVED** [review]
