### PR TITLE
Provides download option in context menu and fixes #3614

### LINKED ISSUE #3614: Download no longer shows progress
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

recent master

Steps to reproduce:

1. Create entry and go to General tab
2. Click "Download from URL" button and insert a link to a relatively large PDF. Click ok.
3. When the download starts an empty progress bar is displayed. However, the progress is not updated and the progress indicator is hidden immediately.

### PR DESCRIPTION
**Pull request by tobiasdiez**
Inspired by the discussion in #3818, I added a "Download file" option in the context menu of a linked file (if it is an online link). Moreover, the bug #3614 is fixed.

This PR was brought to you with the support of coffee from the JabRef cup!

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java [hunk 1]
```diff
@@ -345,4 +352,113 @@ public void writeXMPMetadata() {
...
+    private Path constructSuggestedPath(Optional<ExternalFileType> suggestedType, List<Path> fileDirectories) {
+        String suffix = suggestedType.map(ExternalFileType::getExtension).orElse("");
+        String suggestedName = getSuggestedFileName(suffix);
+        Path directory;
+        if (fileDirectories.isEmpty()) {
+            directory = null;
+        } else {
+            directory = fileDirectories.get(0);
+        }
+        final Path suggestDir = directory == null ? Paths.get(System.getProperty("user.home")) : directory;
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: There is a method which always returns a file dir: getfirstExistingFileDir

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java [hunk 2]
```diff
@@ -345,4 +352,113 @@ public void writeXMPMetadata() {
...
+        * [ 1548875 ] download pdf produces unsupported filename
+        *
+        * http://sourceforge.net/tracker/index.php?func=detail&aid=1548875&group_id=92314&atid=600306
+        * FIXME: rework this! just allow alphanumeric stuff or so?
+        * https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions
+        * http://superuser.com/questions/358855/what-characters-are-safe-in-cross-platform-file-names-for-linux-windows-and-os
+        * https://support.apple.com/en-us/HT202808
+        */
+        if (OS.WINDOWS) {
+            plannedName = plannedName.replaceAll("\\?|\\*|\\<|\\>|\\||\\\"|\\:|\\.$|\\[|\\]", "");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: extract to a matcher?

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java [hunk 3]
```diff
@@ -44,25 +39,23 @@
...
-
     private final ListProperty<LinkedFileViewModel> files = new SimpleListProperty<>(FXCollections.observableArrayList(LinkedFileViewModel::getObservables));
     private final BooleanProperty fulltextLookupInProgress = new SimpleBooleanProperty(false);
     private final DialogService dialogService;
     private final BibDatabaseContext databaseContext;
     private final TaskExecutor taskExecutor;
+    private final JabRefPreferences preferences;
 
-    public LinkedFilesEditorViewModel(String fieldName, AutoCompleteSuggestionProvider<?> suggestionProvider, DialogService dialogService, BibDatabaseContext databaseContext, TaskExecutor taskExecutor, FieldCheckers fieldCheckers) {
+    public LinkedFilesEditorViewModel(String fieldName, AutoCompleteSuggestionProvider<?> suggestionProvider, DialogService dialogService, BibDatabaseContext databaseContext, TaskExecutor taskExecutor, FieldCheckers fieldCheckers, JabRefPreferences preferences) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java]: I know that's its not taht good style to have methods with long params, but why not directly use the FileDirectoryPreferences and ImportFormatPrefernces as args?

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java (hunk 2 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: It turns out that this code is not needed since the `FileUtil` class already handles cleanup of file names

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java (hunk 3 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java]: Mhhh, I tried to collect all the preferences accesses and even for the LinkedFileViewModel it were 5 different settings that are needed. Thus I prefer to keep the general preferences class as dependency.

**Comment by Siedlerchr** [comment]
If you fix checkstyle we can merge

File: src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java [hunk 4]
```diff
@@ -51,7 +51,7 @@ public static FieldEditorFX getForField(String fieldName, TaskExecutor taskExecu
         } else if (fieldExtras.contains(FieldProperty.OWNER)) {
             return new OwnerEditor(fieldName, preferences, suggestionProvider, fieldCheckers);
         } else if (fieldExtras.contains(FieldProperty.FILE_EDITOR)) {
-            return new LinkedFilesEditor(fieldName, dialogService, databaseContext, taskExecutor, suggestionProvider, fieldCheckers);
+            return new LinkedFilesEditor(fieldName, dialogService, databaseContext, taskExecutor, suggestionProvider, fieldCheckers, preferences);
```
Comment (koppor) [inline src/main/java/org/jabref/gui/fieldeditors/FieldEditors.java]: Do really the **whole** preferences need to be passed? Didn't we want to implement information hiding here? 😇

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java [hunk 5]
```diff
@@ -60,20 +70,32 @@
     private final DialogService dialogService;
     private final BibEntry entry;
     private final TaskExecutor taskExecutor;
+    private final FileDirectoryPreferences fileDirectoryPreferences;
+    private final CleanupPreferences cleanupPreferences;
+    private final LayoutFormatterPreferences layoutFormatterPreferences;
+    private final XmpPreferences xmpPreferences;
+    private final String fileNamePattern;
 
+    @Deprecated
```
Comment (koppor) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: Please add a JavaDoc pointing to the method one should use from now on.

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java [hunk 6]
```diff
@@ -60,20 +70,32 @@
...
     public LinkedFileViewModel(LinkedFile linkedFile, BibEntry entry, BibDatabaseContext databaseContext, TaskExecutor taskExecutor) {
-        this(linkedFile, entry, databaseContext, taskExecutor, new FXDialogService());
+        this(linkedFile, entry, databaseContext, taskExecutor, new FXDialogService(), Globals.prefs, Globals.journalAbbreviationLoader);
     }
 
-    protected LinkedFileViewModel(LinkedFile linkedFile, BibEntry entry, BibDatabaseContext databaseContext,
-                                  TaskExecutor taskExecutor, DialogService dialogService) {
+    public LinkedFileViewModel(LinkedFile linkedFile, BibEntry entry, BibDatabaseContext databaseContext,
```
Comment (koppor) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: I think, only the `IMPORT_FILENAMEPATTERN` and `preferences.getFileDirectoryPreferences()` are needed. Why not pass them both (as quick fix regarding the information hiding). OK, a new preference object would even be better, but that costs more time.

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java [hunk 7]
```diff
@@ -177,21 +199,21 @@ public void rename() {
...
-        Optional<Path> file = linkedFile.findIn(databaseContext, Globals.prefs.getFileDirectoryPreferences());
+        Optional<Path> file = linkedFile.findIn(databaseContext, fileDirectoryPreferences);
         if ((file.isPresent()) && Files.exists(file.get())) {
             RenamePdfCleanup pdfCleanup = new RenamePdfCleanup(false,
                     databaseContext,
-                    Globals.prefs.getCleanupPreferences(Globals.journalAbbreviationLoader).getFileNamePattern(),
-                    Globals.prefs.getLayoutFormatterPreferences(Globals.journalAbbreviationLoader),
-                    Globals.prefs.getFileDirectoryPreferences(), linkedFile);
+                    cleanupPreferences.getFileNamePattern(),
+                    layoutFormatterPreferences,
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: Actually layoutFormatterPrefernces can be removed from all cleanup ops (did this the maintable beta), but out of scope for this pr

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java (hunk 6 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: Also the auto-link preferences as well as the import preferences are needed. You are definitely right, a custom preference object unifying them all would be nice. To be honest, I don't have the motivation right now to create one (especially since the focus of this PR is a different one).

File: src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java (hunk 5 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java]: Good observation. Fixed.
