### PR TITLE
Fix issue no warning message for moving attached files

### LINKED ISSUE #10121: Warning Message for Moving Attached Open Files
Suppose that you attach a file to an entry. Then, using a cleanup you want to move that file to the General File Directory of the library. If the attached file is open, the file is not moved but no warning message is shown. It would be nice to have such a message to let the user know what just happened.

### PR DESCRIPTION
**Pull request by juliusalberto**
Supersedes PR #11904 

Closes #10121 

Based on the feedback given on the above PR, I have introduced these changes:

1. In the `org.jabref.logic.cleanup.MoveFilesCleanup`, I collected a list of exceptions for each entry. These list of exceptions will then be stored by` CleanupWorker`. The CleanupAction will store every exceptions caused by IO errors, and will show it using`org.jabref.gui.DialogService#showErrorDialogAndWait`

image

Additional question: Should I create the tests as well?

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by juliusalberto** [comment]
Hi @koppor (sorry if I mentioned you in the wrong place) - do you think this is already in line with the suggestion you wrote here: https://github.com/JabRef/jabref/pull/11904#pullrequestreview-2361518123 ?

File: src/main/java/org/jabref/gui/cleanup/CleanupAction.java [hunk 1]
```diff
@@ -105,7 +105,7 @@ private void doCleanup(BibDatabaseContext databaseContext, CleanupPreferences pr
         CleanupWorker cleaner = new CleanupWorker(
                 databaseContext,
                 preferences.getFilePreferences(),
-                preferences.getTimestampPreferences());
+                preferences.getTimestampPreferences(), dialogService);
```
Comment (koppor) [inline src/main/java/org/jabref/gui/cleanup/CleanupAction.java:108]: Try to follow some code style around: one parameter for each line.

I know that IntelliJ formats differently, but you should review the generated code and adapt it. Nearly all diff tools show the lines around.

File: src/main/java/org/jabref/gui/cleanup/CleanupSingleAction.java [hunk 2]
```diff
@@ -81,7 +81,7 @@ private void doCleanup(BibDatabaseContext databaseContext, CleanupPreferences pr
         CleanupWorker cleaner = new CleanupWorker(
                 databaseContext,
                 preferences.getFilePreferences(),
-                preferences.getTimestampPreferences());
+                preferences.getTimestampPreferences(), dialogService);
```
Comment (koppor) [inline src/main/java/org/jabref/gui/cleanup/CleanupSingleAction.java:84]: Also on a new line.

File: src/main/java/org/jabref/logic/cleanup/CleanupWorker.java [hunk 3]
```diff
@@ -31,6 +40,14 @@ public List<FieldChange> cleanup(CleanupPreferences preset, BibEntry entry) {
         List<FieldChange> changes = new ArrayList<>();
         for (CleanupJob job : jobs) {
             changes.addAll(job.cleanup(entry));
+
```
Comment (koppor) [inline src/main/java/org/jabref/logic/cleanup/CleanupWorker.java:43]: No empty line

File: src/main/java/org/jabref/logic/cleanup/CleanupWorker.java [hunk 4]
```diff
@@ -86,4 +103,17 @@ private CleanupJob toJob(CleanupPreferences.CleanupStep action) {
                     throw new UnsupportedOperationException(action.name());
         };
     }
+
+    private void showFileMoveExceptions(BibEntry entry) {
+        StringBuilder sb = new StringBuilder();
+        String title = entry.getTitle().orElse(Localization.lang("Unknown Title"));
```
Comment (koppor) [inline src/main/java/org/jabref/logic/cleanup/CleanupWorker.java:109]: Normally we use the citaton key. You can use `org.jabref.model.entry.BibEntry#getAuthorTitleYear(int)` with `40` as `maxCharacters` as fallbeack.

File: src/main/java/org/jabref/logic/cleanup/CleanupWorker.java [hunk 5]
```diff
@@ -86,4 +103,17 @@ private CleanupJob toJob(CleanupPreferences.CleanupStep action) {
                     throw new UnsupportedOperationException(action.name());
         };
     }
+
+    private void showFileMoveExceptions(BibEntry entry) {
```
Comment (koppor) [inline src/main/java/org/jabref/logic/cleanup/CleanupWorker.java:107]: This is too early.

Do following:

1. Add method `resetCleanUpFailures()` to `CleanupWorker`
2. Add field `List<JabRefExceptions> failures to CleanupWorker
3. Add method `getFailures()` to CleanupWorker
4. Modify `org.jabref.gui.cleanup.CleanupAction#cleanup` to first `resetCleanUpFailures`, then iterate through the entries and then show the errors

While you are in `resetCleanUpFailures`, move the `NamedCompund` generation and ending outside of the loop - the cleanup of entries is a batch and should not be split.

**Review by koppor — CHANGES_REQUESTED** [review]

**Comment by koppor** [comment]
> Hi @koppor (sorry if I mentioned you in the wrong place) - do you think this is already in line with the suggestion you wrote here: [#11904 (review)](https://github.com/JabRef/jabref/pull/11904#pullrequestreview-2361518123) ?

Thank you for asking! We usually look into WIP PRs only if we are asked for. If you want to have reviews, ping us (as you did),  change the PR state to "ready for review", or request review from someone using GitHubs functionality on the top right.

File: src/main/java/org/jabref/logic/cleanup/CleanupWorker.java (hunk 4 above)
Comment (juliusalberto) [reply src/main/java/org/jabref/logic/cleanup/CleanupWorker.java]: I deleted the citation key part as I think it'd be difficult passing both the entry and the exceptions from `org.jabref.logic.cleanup.CleanupWorker` to `org.jabref.gui.cleanup.CleanupAction` (I will have to create a wrapper to put the entry and its corresponding exceptions)

File: src/main/java/org/jabref/gui/cleanup/CleanupAction.java [hunk 6]
```diff
@@ -135,17 +144,41 @@ private void showResults() {
...
+            // Show errors to user through dialog service
+            showFailures(failures);
+        }
+    }
+
+    private void showFailures(List<JabRefException> failures) {
+        StringBuilder sb = new StringBuilder();
+        for (JabRefException exception : failures) {
+            sb.append("- ").append(exception.getLocalizedMessage()).append("\n");
+        }
```
Comment (koppor) [inline src/main/java/org/jabref/gui/cleanup/CleanupAction.java:175]: Instead of `StringBuilder`, `StringJoinger` is the more modern Java approach. Even more modern is to use `.stream().collect(Collectors.joining(...)`. Please try out this.

File: src/main/java/org/jabref/gui/cleanup/CleanupAction.java [hunk 7]
```diff
@@ -135,17 +144,41 @@ private void showResults() {
...
+        Platform.runLater(() ->
+                dialogService.showErrorDialogAndWait(Localization.lang("File Move Errors"), sb.toString())
+        );
+    }
+
+    public void resetCleanUpFailures() {
```
Comment (koppor) [inline src/main/java/org/jabref/gui/cleanup/CleanupAction.java:181]: This can be private? And even inlined?

**Review by koppor — CHANGES_REQUESTED** [review]

**Review by koppor — APPROVED** [review]
