### PR TITLE
Fix author parsing of ACM

### LINKED ISSUE #10107: ACM Portal websearch bug
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to search on the web: ACM Portal
2. Enter the test string "dd"
3. See the error message below

afbeelding

### Appendix

...
<details>

<summary>Log File</summary>

Not updating theme because it hasn't changed
Theme set to Theme{type=EMBEDDED, name='Dark.css'} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
No open database detected
Aan het openen: 'F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Boek.bib'
Aan het openen: 'F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Paper\Dinosaurus Paper.bib'
Index path for F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Paper\Dinosaurus Paper.bib is C:\Users\gebruiker\AppData\Local\org.jabref\JabRef\lucene94
Index path for F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Boek.bib is C:\Users\gebruiker\AppData\Local\org.jabref\JabRef\lucene94
Error importing
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.ACMPortalParser.parseBibEntry(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.ACMPortalParser.getBibEntriesFromDoiList(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.ACMPortalParser.parseEntries(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.SearchBasedParserFetcher.getBibEntries(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.SearchBasedFetcher.performSearch(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$3(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Import canceled

</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fix cli debug log option

Fixes #10107
Follow up from #10137

### Mandatory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by HoussemNasri — DISMISSED** [review]

File: src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java [hunk 1]
```diff
@@ -227,4 +222,24 @@ public BibEntry parseBibEntry(String jsonStr) {
...
+                given = authorJsonObject.get("given").getAsString();
+            }
+            if (authorJsonObject.has("family")) {
+                family = authorJsonObject.get("family").getAsString();
+            }
+            Author jabrefAuthor = new Author(given, null, null, family, null);
+            jabrefAuthors.add(jabrefAuthor);
+        }
+        return jabrefAuthors;
+    }
```
Comment (calixtus) [inline src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java:244]: Wouldn't it be more comprehensible, if the return type of this method would be already AuthorList instead of List<Author>, since in the only place you use this method, you create an Authorlist of this List of Authors...?
