### PR TITLE
Fixes making paths of linked files relative (web urls will not be touched anymore)

### LINKED ISSUE #5861: Making paths of linked files relative breaks urls
I am using the latest JabRef 5 master build:
JabRef-5.0-portable_linux.tar.gz
JabRef 5.0-beta.360--2020-01-21--7ddfd9f
Linux 4.4.0-171-generic amd64
Java 13.0.2
on Ubuntu 16.04
biblatexmode enabled

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists.

**Steps to reproduce the behavior:**

1. Create a reference which contains, among others, the following line:

```
file = {Full Text PDF:https\://www.jair.org/index.php/jair/article/download/11675/26513:application/pdf;Snapshot:https\://www.jair.org/index.php/jair/article/view/11675:text/html},
```

2. Save library.
3. Select the newly created reference.
4. Click on "Quality" > "Clean up entries", only tick "Make paths of linked files relative (if possible)" and click "OK".
5. Now the value of the "file" field has changed to the following:

```
file = {Full Text PDF:https\:/www.jair.org/index.php/jair/article/download/11675/26513:application/pdf;Snapshot:https\:/www.jair.org/index.php/jair/article/view/11675:text/html},
```

So both urls are broken now and cannot be used any more.

### PR DESCRIPTION
**Pull request by systemoperator**
Fixes #5861
Description:
- Cleaning up entries with "Make paths of linked files relative (if possible)" broke web URLs and resulted in various other issues subsequently. This PR fixes this issue.
It has been tested for local files and web urls.

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not: Issue created at <https://github.com/JabRef/user-documentation/issues>.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thank you very much for your contribution!
fix looks good!

**Comment by systemoperator** [comment]
Is there still something I need to do or is everything fine, because one check failed?

**Comment by Siedlerchr** [comment]
you can ignore the failing check. It's just the upload of the binaries which sometimes fails.
Our Code Quality Policy requires a review from a second reviewer for external developers before it can be merged.

File: src/main/java/org/jabref/logic/cleanup/RelativePathsCleanup.java [hunk 1]
```diff
@@ -57,4 +64,21 @@ public RelativePathsCleanup(BibDatabaseContext databaseContext, FilePreferences
         return Collections.emptyList();
     }
 
+    /**
+     * Checks, if the given file path is a well-formed web url
+     *
+     * @param filePath file path to check
+     * @return <code>true</code>, if the given file path is a web url, <code>false</code> otherwise
+     */
+    private static boolean isWebUrl(String filePath)
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/cleanup/RelativePathsCleanup.java]: The class `LinkedFile` already contains a method that does this job:
https://github.com/JabRef/jabref/blob/8520833e684aa9e305dd8745e45696ffd6d984fb/src/main/java/org/jabref/model/entry/LinkedFile.java#L162-L164
Can you please use it. I would also suggest to add the normalization `trim().toLowerCase()` there, which I find a nice addition.

Comment (systemoperator) [reply src/main/java/org/jabref/logic/cleanup/RelativePathsCleanup.java]: Concerning isOnlineLink(): I would recommend removing "toCheck.contains("www.")", because a path to a local file might contain this pattern coincidentally. What do you say?

**Comment by calixtus** [comment]
Would a proper implementation of rfc 3986 be an overkill? Maybe this could be achieved with a proper regex?
https://tools.ietf.org/html/rfc3986

**Comment by systemoperator** [comment]
@calixtus Checking a path as follows could be simple alternative https://www.geeksforgeeks.org/check-if-url-is-valid-or-not-in-java/ But nevertheless, I also see advantages with the current approach, since it also detects urls as web urls, even if they are potentially broken in some way. This was the reason, why I created it like that. I think the main goal is to identify a web url rather than identify its validity.

**Comment by Siedlerchr** [comment]
@systemoperator  That should work using new URL() in practice and I think should be sufficient for most cases as an indicator

**Comment by systemoperator** [comment]
I e.g. think about the following scenario: Given are broken web urls like:

- https://www. google.at/ <- mind the unintended space character
- https://www..google.at/ <- mind the unintended second period
- ...

I think, in this screnario, it is more important to identify whether it is web url or not, rather than making it more strict, saying checking whether it is a VALID web url, because in the case, that it would be a invalid web url (as e.g. shown above) then in this scenario the url would again get cleaned up and thus it will become even more "destoryed", as it would be interpreted as a local file url again.

On the other hand, if a broken url gets identified as a web url, then it will be processed properly and everything will work out, but when opening the url, it just cannot be loaded.

**Comment by calixtus** [comment]
Somewhere I think, you're some kind of right too. 

On the other hand, where do we want to decide, what's still a acceptable and what not? What about "file://". We also had a few months ago someone here using JabRef as database for genetics stuff and not for books (proofing the mutability of JabRef).
Please don't misunderstand me, I get your point and I don't exactly know the right answer...

**Comment by systemoperator** [comment]
Before implementing it, I thought about many of those things. With the current implementation a file link starting with "file://" will not be interpreted as a web url anyway, so this would be fine as well.

**Comment by calixtus** [comment]
At least the javadoc should then be adapted... ;-)

**Comment by systemoperator** [comment]
Of course. I would like to hear @tobiasdiez's recommendation about that as well. Then I will implement it as desired. :)

**Comment by tobiasdiez** [comment]
I think the current implementation is a good compromise. In the ideal world, the URL is valid and a proper validation as @calixtus would be preferable. However, the data quality we get from some fetchers is suboptimal so that it is a good idea to error on the save side (e.g. better identify to many paths as web urls). I suggest to merge now and come back to it later if users complain / provide problematic use cases.
