### PR TITLE
Fix closing of library not handling backup and autosave manager shutdown

### LINKED ISSUE #4789: Closing a library but not JabRef, the .sav file is not deleted, causing a "Backup found" message at the next opening
JabRef 5.0-dev--snapshot--2019-03-19--master--90376f40f
Windows 7 6.1 amd64 
Java 1.8.0_201

- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Once I close a library clicking the +-symbol in the "Reiter", and reopened it, I get the message "Backup found" ...
1. Close a library by pressing the +-symbol
2. Open the same library again
3. "Backup found"

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by CaptainDaVinci**
Fixes #4789

The issue was when the tab is closed by clicking 'x' it did not call
the method `closeTab()` which handles the closing of backup and
autosave manager.

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/JabRefFrame.java [hunk 1]
```diff
@@ -1154,6 +1154,7 @@ public void addTab(BasePanel basePanel, boolean raisePanel) {
             // add tab
             Tab newTab = new Tab(basePanel.getTabTitle(), basePanel);
             tabbedPane.getTabs().add(newTab);
+            newTab.setOnCloseRequest(event -> closeTab((BasePanel) newTab.getContent()));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/JabRefFrame.java]: That's a very good observation. 

As of now the user can close the tab even if there are unsaved changes. Thus, we should improve the functionality here a bit by calling `confirmClose` and consuming the `event` in case the user canceled the close operation.

**Comment by CaptainDaVinci** [comment]
Thank you for those kind words! :smile:

File: src/main/java/org/jabref/gui/JabRefFrame.java (hunk 1 above)
Comment (CaptainDaVinci) [reply src/main/java/org/jabref/gui/JabRefFrame.java]: The method `closeTab()` makes a call to `confirmClose` when the panel is modified. However, it does not consume the `event` in case of cancelling. Since, the logic for removing tab is already handled I think it should be enough to consume the event in the `closeRequest` Itself.

Comment (CaptainDaVinci) [reply src/main/java/org/jabref/gui/JabRefFrame.java]: The `confirmClose` shows a dialog with 3 option *Save changes*, *Discard changes* and *Return to JabRef*. The `confirmClose` method returns false only if the user clicks *Return to JabRef* in this case, the tab isn't closed however the autosave and backup managers are shutdown any way. 
I don't think they should be shutdown in this case, we can return from `closeTab()` in case `confirmClose` returns false.

**Comment by LinusDietz** [comment]
Thank you very much for this fix. Can you please write a Changelog entry, before we merge this?
