### PR TITLE
Fix Preferences Search

### LINKED ISSUE #6866: Preferences: Search: Many items are not found
JabRef 5.2--2020-09-03--1283f9f
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In the preferences window, the search feature misses many (existing) items.

1.Options -> Preferences
2. In the search field, type in *mark*.
-> "Mark new entries with addition date" is found.
But "Mark new entries with owner name" (two lines above) is not.

Many other items cannot be found (Language; special fields; fit; filename; etc.), without any apparent logic between the found/not found items.

PS: I have just discovered the Preferences search. Great feature!

### PR DESCRIPTION
**Pull request by fabiojavamarcos**
Updated fxml files from the preferences package to appear in preference search.

The preferences search was unable to find some visual components because they are not a direct child from one of the preferences tab. 
So, the method getPrefsTabLabelMap in PreferencesSearchHandler cannot find them. I moved some components that were inside  <HBox> tags to let them "visible" to their parents in the mentioned method. It does not change the UI. Most of the components could be moved. Some could not because they have many parents until the tab and it could impact the UI. 

Fixes #6866

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

image

### CODE REVIEW

**Comment by calixtus** [comment]
Hi @fabiojavamarcos ,
thanks for your efforts, but I believe this won't fix the underlying problem.

I think a different approach would be to design a tree walker in `PreferencesSearchHandler::getPrefsTabLabelMap`, which collects all `Labeled` nodes in each node and it's subnodes.
Maybe this example of walking through a directory tree can help?
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree

**Comment by Siedlerchr** [comment]
Agree with  @calixtus , a simple recursive appraoch  https://stackoverflow.com/a/13011616 should work

**Comment by fabiojavamarcos** [comment]
Ok. I am going to take a look!

**Comment by fabiojavamarcos** [comment]
Now I think it is better! Thanks for the suggestion.

**Comment by calixtus** [comment]
With this recursive approach you should be able to put all the Labeled nodes in the fxml files back into the hboxes.

**Comment by fabiojavamarcos** [comment]
Ok. Doing that! 

Here the indexing was fast. But... you know... I am fixing the HBox and you decide if is better to finish or not. Maybe finish it and open another issue can be ok. And I can start looking at the new one as well. Thanks!

File: src/main/java/org/jabref/gui/preferences/PreferencesSearchHandler.java [hunk 1]
```diff
@@ -89,7 +89,7 @@ private void clearSearch() {
         return filteredPreferenceTabs;
     }
 
-    private void scanInputControls(Parent parent, ArrayListMultimap<PreferencesTab, Labeled> prefsTabLabelMap, PreferencesTab preferencesTab) {
+    private static void scanInputControls(Parent parent, ArrayListMultimap<PreferencesTab, Labeled> prefsTabLabelMap, PreferencesTab preferencesTab) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/preferences/PreferencesSearchHandler.java:92]: Please give ths method a more meaningful name. You are scanning for label controls.

Comment (fabiojavamarcos) [reply src/main/java/org/jabref/gui/preferences/PreferencesSearchHandler.java]: Done!

File: src/main/java/org/jabref/gui/preferences/GroupsTab.fxml [hunk 2]
```diff
@@ -24,7 +24,7 @@
     <CheckBox fx:id="displayGroupCount" text="%Display count of items in group"/>
 
     <HBox spacing="4" alignment="CENTER_LEFT">
-        <Label text="%Keyword separator"/>
+        <Label text="%Keyword seperator"/>
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/GroupsTab.fxml:27]: Typo

**Review by calixtus — CHANGES_REQUESTED** [review]

File: src/main/java/org/jabref/gui/preferences/GroupsTab.fxml (hunk 2 above)
Comment (fabiojavamarcos) [reply src/main/java/org/jabref/gui/preferences/GroupsTab.fxml]: Done.

File: src/main/java/org/jabref/gui/preferences/FileTab.fxml [hunk 3]
```diff
@@ -1,15 +1,16 @@
...
-<?import javafx.scene.control.CheckBox?>
-<?import javafx.scene.control.ComboBox?>
 <?import javafx.scene.control.Label?>
-<?import javafx.scene.control.RadioButton?>
-<?import javafx.scene.control.TextField?>
-<?import javafx.scene.control.ToggleGroup?>
-<?import javafx.scene.layout.HBox?>
 <?import javafx.scene.layout.VBox?>
 <?import org.jabref.gui.commonfxcontrols.SaveOrderConfigPanel?>
+<?import javafx.scene.control.ToggleGroup?>
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/preferences/FileTab.fxml:6]: Is there any system in reordering the imports in the fxmls? If not, why not leave it alphabetically like every other import in the .Java files...

**Review by calixtus — COMMENTED** [review]
One question left, rest lgtm

File: src/main/java/org/jabref/gui/preferences/FileTab.fxml (hunk 3 above)
Comment (fabiojavamarcos) [reply src/main/java/org/jabref/gui/preferences/FileTab.fxml]: Got it!

**Review by calixtus — COMMENTED** [review]
Im afraid the code style issues are still remaining. See:
https://github.com/JabRef/jabref/pull/6946/files

But don't mind, we can fix this before merging it.
Changes to PreferencesSearchHandler look good to me.

**Comment by fabiojavamarcos** [comment]
I have no idea why they changed their positions because I did not change them! Anyway, I checked again and manually put it in alphabetical order.

**Review by Siedlerchr — APPROVED** [review]

**Review by calixtus — APPROVED** [review]
Looks very good to me. Since @Siedlerchr already approved it, I think I'm going to merge it.
Thank you very much for this PR. We are happy to welcome you to the contributors of JabRef. Even if our remarks sometimes sound a bit lit nitpicking, it's because we try to lift the code style standards in JabRef for some months now. But open source is always about learning something new and working together for something good. We hope you liked working on JabRef an you consider to return for another issue to fix or feature to implement!
So thanks again!

**Comment by fabiojavamarcos** [comment]
I am really having fun, learning with the process, with your experience, and happy! I am going to check more issues. Thanks for your orientation and patience!
