### PR TITLE
OpenOffice Refactor subtasks

### LINKED ISSUE #11829: Refactor and unify JabRef OO components
## Project: Refactor JabRef-OpenOffice components
There is a lot of scope for improvement in code quality in JabRef's OpenOffice/LibreOffice integration components to make it much more maintainable. These include, but are not limited to:
- [ ] Unification of error handling mechanism for JabRef-OOdoc interaction: Currently there exists a mix of returning Optional, throwing exceptions, and using `OOResult`/`OOVoidResult`. We can standardize the error handling approaches  for consistency.
- [ ] Use of Dependency Injection
- [ ] Break down large methods like `guiActionInsertEntry()`
- [ ] Use more constants instead of magic strings e.g. as used in the error messages
- [ ] Use of built-in functional interfaces: for methods that take `Supplier<OOError>` as parameters - will improve code clarity
- [ ] Use of modern Java features like streams and optional chaining
- [ ] Separation of concerns: classes such as `OOBibBase` handle both business logic and UI interactions. We can consider extracting UI-related code into a separate class or layer.
- [ ] Inner classes like `ComparableMark` can be converted to record classes.
- [ ] Unification of backend for CSL and JStyles (Optional, and a big project - I am fine with all the CSL logic being separate due to the difference in code philosophy and time required for unification).

I will be working on this, so will be using this issue to track the state/progress.
The list is not yet complete, so will be updated from time to time as I come across more scopes for improvements.

### PR DESCRIPTION
**Pull request by anuv-bit**
### Related issues and pull requests

Closes https://github.com/JabRef/jabref/issues/11829

### PR Description

This PR focuses on several subtasks, such as:

**Break down large methods like guiActionInsertEntry()** - the refactoring technique ‘extract method’ was used on long methods or repeated blocks of code in ‘OOBibBase’, ‘EditMerge’, ‘OOFrontend’, and ‘CSLCitationOOAdapter’ in order to increase readability and modifiability.

**Using more constants instead of magic strings** - this task focused on replacing repeated magic strings with named constants across OOBibBase.java, OpenOfficePanel.java, and EditMerge.java to improve readability and reduce duplicated elements. 

**Using modern Java features(streams and Optional chaining)** - this task focused on replacing for loops with stream pipelines using flatMap(), filter(), and anyMatch(). Additionally, getBaseList() was refactored to use streams while preserving mutability.

**Unification of error handling methods** - Instead of throwing runtime exceptions, we standardized the use of logging combined with OOError dialogs, minimizing the use of throwing exceptions without being caught by some other area of code.

Additionally, this PR includes some minor refactorings such as removing unused parameters and duplicate methods. 

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [/] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [/] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 1]
```diff
@@ -94,19 +94,19 @@ private void initializeCitationAdapter(XTextDocument doc) throws WrappedTargetEx
     }
 
     public void guiActionSelectDocument(boolean autoSelectForSingle) throws WrappedTargetException, NoSuchElementException {
-        final String errorTitle = Localization.lang("Problem connecting");
+        final String connectionError = Localization.lang("Problem connecting");
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Please revert these renamings - since they are function-local, they needn't be more specific

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 2]
```diff
@@ -581,82 +562,150 @@ public void guiActionInsertEntry(List<BibEntry> entries,
...
+    /// Helper method for guiActionInsertEntry. Handles CSL citation insertion
+    /// Throws CreationException, com.sun.star.uno.Exception
+    /// Caught by guiActionInsertEntry
+    ///
+    /// @param entries            The entries to cite.
+    /// @param bibDatabaseContext The database the entries belong to (all of them). Used when creating the citation mark.
+    /// @param citationType       Indicates whether it is an in-text citation, a citation in parenthesis or an invisible citation.
+    /// @param citationStyle      Indicates style, name and path of citation
+    /// @param syncOptions        Indicates whether in-text citations should be refreshed in the document. Optional.empty() indicates no refresh. Otherwise, provides options for refreshing the reference list.
+    public void guiActionCSLCitationHandler(List<BibEntry> entries, XTextDocument doc, CitationType citationType, CitationStyle citationStyle,
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: These are more like class names - please use names denoting actions for methods

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java (hunk 1 above)
Comment (amanda-d-e) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Understood, I reverted them. Are there more magic strings that you would like replaced with constants (that I have not already replaced)? My understanding was that not every single string needed to be replaced with a constant, especially in cases where the string is unique and is only used once. 

Thank you!

Comment (subhramit) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: These above were not magic strings. They were already constants.
Yes, ideally we extract constants for strings used more than once.
But there is one other case - when the string reduces readability of the code, or is long.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 3]
```diff
@@ -633,13 +579,116 @@ public void guiActionInsertEntry(List<BibEntry> entries,
             LOGGER.warn("Could not insert entry", ex);
             OOError.fromMisc(ex).setTitle(errorTitle).showErrorDialog(dialogService);
         } catch (com.sun.star.uno.Exception e) {
-            LOGGER.error("Could not insert entry", e);
-            OOError.fromMisc(e).setTitle(errorTitle).showErrorDialog(dialogService);
+            throw new RuntimeException(e);
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Shouldn't this still use `OOError.fromMisc`?

**Comment by pluto-han** [comment]
Could you please also extract methods for JStyle and CSL in `guiActionUpdateDocument` like the way you did in `guiActionInsertEntry`?

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java (hunk 1 above)
Comment (amanda-d-e) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Thank you for the confirmation! To clarify: I was referring to changes made in a previous commit in which I did replace magic strings with constants, not this commit which was just renaming the existing constants.

**Comment by amanda-d-e** [comment]
> Could you please also extract methods for JStyle and CSL in `guiActionUpdateDocument` like the way you did in `guiActionInsertEntry`?

Thank you for the guidance @pluto-han. I extracted a 'performPreUpdateChecks()' method similar to the 'performPreInsertionChecks()' method extracted from `guiActionInsertEntry`. Is this what you were looking for, or would you like me to also restructure the try/catch blocks inside `guiActionUpdateDocument` to match `guiActionInsertEntry`?

**Comment by subhramit** [comment]
> Could you please also extract methods for JStyle and CSL in `guiActionUpdateDocument` like the way you did in `guiActionInsertEntry`?

Thank you for helping in reviews @pluto-han!

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java (hunk 3 above)
Comment (subhramit) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Yes
@anuv-bit why was this changed?

**Comment by pluto-han** [comment]
> would you like me to also restructure the try/catch blocks inside `guiActionUpdateDocument` to match `guiActionInsertEntry`?

For me, I would prefer include try-catch as well for more readability, but I am not maintainer cannot simply decide it.
@subhramit Should try-catch be included in the extracted method?

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java (hunk 3 above)
Comment (sam-r914) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Honestly no clue when or why that happened. Might have been a IDE suggestion change in another area that affected this. I can assure you it was not intentional.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 4]
```diff
@@ -555,7 +554,7 @@ public void guiActionInsertEntry(List<BibEntry> entries,
             }
         }
 
-        syncOptions.map(e -> e.setAlwaysAddCitedOnPages(openOfficePreferences.getAlwaysAddCitedOnPages()));
+        syncOptions.ifPresent(e -> e.setAlwaysAddCitedOnPages(openOfficePreferences.getAlwaysAddCitedOnPages()));
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Since `syncOptions` has already been checked in `if`, you can move `syncOptions.ifPresent(e -> e.setAlwaysAddCitedOnPages(openOfficePreferences.getAlwaysAddCitedOnPages()));` into `if` block

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 5]
```diff
@@ -988,14 +987,10 @@ private void updateCSLBibliography(List<BibDatabase> databases, CitationStyle ci
...
-                for (BibEntry entry : database.getEntries()) {
-                    if (cslCitationOOAdapter.isCitedEntry(entry)) {
-                        citedEntries.add(entry);
-                    }
-                }
-            }
+            List<BibEntry> citedEntries = databases.stream()
+                                                   .flatMap(database -> database.getEntries().stream())
+                                                   .filter(cslCitationOOAdapter::isCitedEntry)
+                                                   .toList();
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: This makes `citedEntries` an immutable list. Modifying (e.g. `CSLCitationOOAdapter#L206`: `entries.sort()`) the list throws an exception.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java [hunk 6]
```diff
@@ -599,14 +596,10 @@ private void pushEntries(CitationType citationType, boolean addPageInfo) {
...
-        for (BibEntry entry : entries) {
-            if (entry.getCitationKey().isEmpty()) {
-                // Found one, no need to look further for now
-                emptyKeys = true;
-                break;
-            }
-        }
+        // Found one, no need to look further for now
+
+        boolean emptyKeys = entries.stream()
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OpenOfficePanel.java:603]: No empty lines please

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java (hunk 5 above)
Comment (anuv-bit) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Thank you for the review. I have replaced .toList() with .collect(Collectors.toCollection(ArrayList::new)) to ensure the list is mutable.

**Comment by amanda-d-e** [comment]
@subhramit, I was wondering if you think it would be reasonable to perform the "replace type code with subclasses" and then "replace conditional with polymorphism" refactorings for OOBibBase.java. 

This is motivated by the 'if (style instanceof _____)' statements in several of the OOBibBase.java methods.

This could entail either creating sub classes for CSLBib and JStyleBib as well as an abstract class StyleBib within the jabgui open office folder, or extracting and moving methods to the existing JStyle.java and CitationStyle.java classes in the jablib logic folder. 

I wanted to get your approval before attempting any of this because it may be unnecessary/overkill, and I wasn't sure if it aligned with your goals for this issue.

**Comment by pluto-han** [comment]
Hi @amanda-d-e, @subhramit is a bit busy until the weekend.

I would recommend refactor `OOBibBase` as an abstract class. Specifically, keep the logic shared by JStyle and CSL, extract and implement "style-specific" methods/logic to new subclasses.

Let's wait for @subhramit's thoughts.

**Comment by amanda-d-e** [comment]
> Hi @amanda-d-e, @subhramit is a bit busy until the weekend.
> 
> I would recommend refactor `OOBibBase` as an abstract class. Specifically, keep the logic shared by JStyle and CSL, extract and implement "style-specific" methods/logic to new subclasses.
> 
> Let's wait for @subhramit's thoughts.

Hello @pluto-han, thank you for the reply. Unfortunately since the project is due tomorrow, I will have to implement any changes (that I would like to be counted towards the assignment grade) before this weekend. Of course, if any of my changes are deemed unsatisfactory due to not receiving approval first, I completely understand. I think I will give this a try in a separate branch so it can be removed easily later on.

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 7]
```diff
@@ -320,34 +320,7 @@ private void updateAllCitationsWithNewStyle(CitationStyle style, CSLCitationType
...
-                        formattedCitation = CSLFormatUtils.changeToInText(formattedCitation);
-                    }
-
-                    finalText.append(formattedCitation);
-
-                    if (iterator.hasNext()) {
-                        finalText.append(",");
-                    }
-                }
+                updateCitations(style, iterator, unifiedBibDatabaseContext, finalText);
```
Comment (pluto-han) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: I'm not sure about this, `updateCitations` is called only once. 
My idea: `insertCitation`, `insertInTextCitation` and `updateAllCitationsWithNewStyle` share a bit of logic, you can extract those lines into a new method.

File: jablib/src/main/java/org/jabref/logic/openoffice/backend/NamedRangeReferenceMark.java [hunk 8]
```diff
@@ -247,6 +247,13 @@ public XTextCursor getFillCursor(XTextDocument doc)
         if (fullText.length() < 2) {
             throw new IllegalStateException("getFillCursor: fullText.length() < 2 (after loop)'%n");
         }
+
+        // NamedRangeReferenceMark.checkFillCursor(beta);
+        return getStringForFillCursor(full, fullText, debugThisFun);
```
Comment (pluto-han) [inline jablib/src/main/java/org/jabref/logic/openoffice/backend/NamedRangeReferenceMark.java]: What's the point of this comment?

Comment (pluto-han) [inline jablib/src/main/java/org/jabref/logic/openoffice/backend/NamedRangeReferenceMark.java]: Do we really need this refactoring?

Reasons:
1. This method is called only once.

2. New method name is misleading. "getString" but return `XTextCursor`?

3. Meaningless comment.

This feels like a refactoring for the sake of refactoring.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBaseConnect.java [hunk 9]
```diff
@@ -218,19 +218,10 @@ public boolean isDocumentConnectionMissing() {
...
-            throw new NoDocumentException("Not connected to document");
-        }
-        return this.xTextDocument;
-    }
-
+    /// Returns either a valid XTextDocument in OOResult or a NoDocumentException error
     public OOResult<XTextDocument, OOError> getXTextDocument() {
         if (isDocumentConnectionMissing()) {
-            return OOResult.error(OOError.from(new NoDocumentException()));
+            return OOResult.error(OOError.from(new NoDocumentException("Not connected to document")));
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBaseConnect.java]: No need to add error message.  `OOError.from()` already handles it.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 10]
```diff
@@ -369,20 +361,20 @@ private OOVoidResult<OOError> checkStyleExistsInTheDocument(String familyName,
                             + pathToStyleFile;
             return OOVoidResult.error(new OOError("StyleIsNotKnown", msg));
         }
-
-        if (!internalName.get().equals(styleName)) {
+        String actualName = internalName.get();
+        if (!actualName.equals(styleName)) {
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: I don't see the point here. `internalName.get()` is used twice here.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 11]
```diff
@@ -435,33 +427,32 @@ public OOVoidResult<OOError> checkStylesExistInTheDocument(JStyle jStyle, XTextD
      *
      * ******************************************************/
     public Optional<List<CitationEntry>> guiActionGetCitationEntries() {
-        final Optional<List<CitationEntry>> FAIL = Optional.empty();
         final String errorTitle = Localization.lang("Problem collecting citations");
 
         OOResult<XTextDocument, OOError> odoc = getXTextDocument();
         if (testDialog(errorTitle, odoc.asVoidResult())) {
-            return FAIL;
+            return Optional.empty();
```
Comment (pluto-han) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: We can keep `FAIL` for more readability

**Review by pluto-han — COMMENTED** [review]
Some refactorings are good, but some IMHO are pointless, either not improving readability or even making it worse.

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java (hunk 7 above)
Comment (amanda-d-e) [reply jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Hello, thank you for the suggestion. I have reverted the initial refactoring and extracted duplicate logic from those three methods in 'CSLCitationOOAdapter'.

**Comment by amanda-d-e** [comment]
Hello @pluto-han, I attempted the refactoring we discussed yesterday: 

> Hi @amanda-d-e, @subhramit is a bit busy until the weekend.
> 
> I would recommend refactor `OOBibBase` as an abstract class. Specifically, keep the logic shared by JStyle and CSL, extract and implement "style-specific" methods/logic to new subclasses.
> 
> Let's wait for @subhramit's thoughts.

and found that the disadvantages seemed to outweigh the advantages due to the added overhead required in 'OpenOfficePanel', including potential issues with style changes during runtime. I plan to not include these changes because I feel that the original structure is superior. However, if you would like to take a look at them regardless please let me know.

File: jablib/src/main/java/org/jabref/logic/openoffice/backend/NamedRangeReferenceMark.java (hunk 8 above)
Comment (sam-r914) [reply jablib/src/main/java/org/jabref/logic/openoffice/backend/NamedRangeReferenceMark.java]: it looks like its a statement that i happened to miss when extracting

Comment (sam-r914) [reply jablib/src/main/java/org/jabref/logic/openoffice/backend/NamedRangeReferenceMark.java]: fair enough. i am really bad at naming methods honestly. ill work on reverting this change

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java (hunk 10 above)
Comment (anuv-bit) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Thank you for the feedback! internalName.get() is actually called three times. I thought of extracting it into actualName to avoid multiple .get() calls on the Optional and keep the value consistent. However, I have reverted the changes.

**Comment by subhramit** [comment]
> @subhramit, I was wondering if you think it would be reasonable to perform the "replace type code with subclasses" and then "replace conditional with polymorphism" refactorings for OOBibBase.java.
> 
> This is motivated by the 'if (style instanceof _____)' statements in several of the OOBibBase.java methods.
> 
> This could entail either creating sub classes for CSLBib and JStyleBib as well as an abstract class StyleBib within the jabgui open office folder, or extracting and moving methods to the existing JStyle.java and CitationStyle.java classes in the jablib logic folder.

I see where you are coming from, and theoretically that makes sense - but for the scope of this subtask it seems a bit overkill and needs to be well-thought to carefully separate the exclusive code. It will be a larger task.
Furthermore, `JStyle` and `CitationStyle` ought not be touched with respect to GUI stuff, as these classes are intended to model the respective style files and define actions on them.

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 12]
```diff
@@ -111,7 +112,8 @@ public void insertCitation(XTextCursor cursor, CitationStyle selectedStyle, List
         if (isAlphanumericStyle) {
             citation = CSLFormatUtils.generateAlphanumericCitation(entries, bibDatabaseContext);
         } else {
-            citation = CitationStyleGenerator.generateCitation(entries, style, HTML_OUTPUT_FORMAT, bibDatabaseContext, bibEntryTypesManager);
+            citation = CitationStyleGenerator.generateCitation(entries, style,
+                    HTML_OUTPUT_FORMAT, bibDatabaseContext, bibEntryTypesManager);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Revert formatting

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 13]
```diff
@@ -369,7 +361,6 @@ private OOVoidResult<OOError> checkStyleExistsInTheDocument(String familyName,
                             + pathToStyleFile;
             return OOVoidResult.error(new OOError("StyleIsNotKnown", msg));
         }
-
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java:372]: Newline removed

**Comment by subhramit** [comment]
@anuv-bit @amanda-d-e can you tick "Allow maintainers to edit this pull request" on the right hand side?
We wish to finish the remaining changes and get this in.

File: jablib/src/main/java/org/jabref/logic/openoffice/action/EditMerge.java [hunk 14]
```diff
@@ -187,14 +189,20 @@ private static boolean checkAddToGroup(ScanState state, CitationGroup group, XTe
...
-            LOGGER.warn("MergeCitationGroups: cursorBetween.end != currentGroupCursor.end");
-            throw new IllegalStateException("MergeCitationGroups failed");
+            LOGGER.warn(loggerMessage);
+            return false;
         }
 
-        /*
-         * Try to expand state.currentGroupCursor and state.cursorBetween by going right to reach
-         * rangeStart.
-         */
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/action/EditMerge.java:197]: This comment should not be lost

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 15]
```diff
@@ -640,26 +594,84 @@ public void guiActionInsertEntry(List<BibEntry> entries,
...
+
             XTextDocument doc = odoc.get();
 
             OOResult<FunctionalTextViewCursor, OOError> fcursor = getFunctionalTextViewCursor(doc, errorTitle);
 
-            if (testDialog(errorTitle,
-                    fcursor.asVoidResult(),
-                    checkStylesExistInTheDocument(jStyle, doc),
-                    checkIfOpenOfficeIsRecordingChanges(doc))) {
+            if (!performPreMergeSeparateChecks(databases, errorTitle, odoc, jStyle, fcursor, doc)) {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: This changes semantics (the order of returning if checks at a particular stage fail)

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 16]
```diff
@@ -700,20 +712,12 @@ public void guiActionSeparateCitations(List<BibDatabase> databases, OOStyle styl
...
 
             XTextDocument doc = odoc.get();
+
             OOResult<FunctionalTextViewCursor, OOError> fcursor = getFunctionalTextViewCursor(doc, errorTitle);
 
-            if (testDialog(errorTitle,
-                    fcursor.asVoidResult(),
-                    checkStylesExistInTheDocument(jStyle, doc),
-                    checkIfOpenOfficeIsRecordingChanges(doc))) {
+            if (!performPreMergeSeparateChecks(databases, errorTitle, odoc, jStyle, fcursor, doc)) {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Same here

**Review by subhramit — CHANGES_REQUESTED** [review]
Some refactoring has changed semantics - need to double check

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 17]
```diff
@@ -568,58 +558,22 @@ public void guiActionInsertEntry(List<BibEntry> entries,
...
-
-                    // If "Automatically sync bibliography when inserting citations" is enabled
-                    if (citationStyle.hasBibliography()) {
-                        syncOptions.ifPresent(options -> guiActionUpdateDocument(options.databases, citationStyle));
-                    }
-                } finally {
-                    // Release controller lock
-                    doc.unlockControllers();
-                }
+                insertCSLCitation(entries, doc, citationType, citationStyle, bibDatabaseContext, bibEntryTypesManager, cursor, syncOptions);
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: For >=4 arguments, each should go into a new line for readability

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 18]
```diff
@@ -640,26 +594,84 @@ public void guiActionInsertEntry(List<BibEntry> entries,
...
+    /// Caught by guiActionInsertEntry
+    ///
+    /// @param entries            The entries to cite.
+    /// @param bibDatabaseContext The database the entries belong to (all of them). Used when creating the citation mark.
+    /// @param citationType       Indicates whether it is an in-text citation, a citation in parenthesis or an invisible citation.
+    /// @param citationStyle      Indicates style, name and path of citation
+    /// @param syncOptions        Indicates whether in-text citations should be refreshed in the document. Optional.empty() indicates no refresh. Otherwise, provides options for refreshing the reference list.
+    public void insertCSLCitation(List<BibEntry> entries, XTextDocument doc, CitationType citationType, CitationStyle citationStyle,
+                                  BibDatabaseContext bibDatabaseContext, BibEntryTypesManager bibEntryTypesManager, OOResult<XTextCursor, OOError> cursor,
+                                  Optional<Update.SyncOptions> syncOptions) throws CreationException, com.sun.star.uno.Exception {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Each parameter in new line

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 19]
```diff
@@ -640,26 +594,84 @@ public void guiActionInsertEntry(List<BibEntry> entries,
...
+    ///
+    /// @param entries            The entries to cite.
+    /// @param citationType       Indicates whether it is an in-text citation, a citation in parentheses or an invisible citation.
+    /// @param jStyle             Indicates citation formating in JStyle
+    /// @param bibDatabaseContext The database the entries belong to (all of them). Used when creating the citation mark.
+    /// @param syncOptions        Indicates whether in-text citations should be refreshed in the document. Optional.empty() indicates no refresh. Otherwise, provides options for refreshing the reference list.
+    /// @param pageInfo           A single page-info for these entries. Attributed to the last entry.
+    public void insertJStyleCitation(List<BibEntry> entries, XTextDocument doc, CitationType citationType, JStyle jStyle, OOResult<OOFrontend, OOError> frontend,
+                                     OOResult<XTextCursor, OOError> cursor, BibDatabaseContext bibDatabaseContext, Optional<Update.SyncOptions> syncOptions,
+                                     String pageInfo, OOResult<FunctionalTextViewCursor, OOError> fcursor)
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Same as above

**Review by subhramit — COMMENTED** [review]
Other cosmetic comments

**Comment by amanda-d-e** [comment]
> @anuv-bit @amanda-d-e can you tick "Allow maintainers to edit this pull request" on the right hand side? We wish to finish the remaining changes and get this in.

Hello @subhramit, I think that @anuv-bit has to allow maintainers to edit the pull request since she is the one who made it, so I will try to get in contact with her as soon as possible. Apologies for the inconvenience, and thank you for all of the feedback and guidance.

**Comment by anuv-bit** [comment]
> @anuv-bit @amanda-d-e can you tick "Allow maintainers to edit this pull request" on the right hand side? We wish to finish the remaining changes and get this in.

Hey @subhramit, I clicked it.

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 20]
```diff
@@ -112,8 +112,7 @@ public void insertCitation(XTextCursor cursor, CitationStyle selectedStyle, List
         if (isAlphanumericStyle) {
             citation = CSLFormatUtils.generateAlphanumericCitation(entries, bibDatabaseContext);
         } else {
-            citation = CitationStyleGenerator.generateCitation(entries, style,
-                    HTML_OUTPUT_FORMAT, bibDatabaseContext, bibEntryTypesManager);
+            citation = CitationStyleGenerator.generateCitation(entries, style, HTML_OUTPUT_FORMAT, bibDatabaseContext, bibEntryTypesManager);
```
Comment (pluto-han) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java:115]: I‘m not sure about this. I would think the original format is better.

Plus: `createCitation` and `createInTextCitation` also contain this line, why didn't you change them as well?

Comment (anuv-bit) [reply jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java:115]: Hi, thanks for the comment. The original file contained the single-line format, which was changed to multi-line in this PR. As per subhramit's comment (https://github.com/JabRef/jabref/pull/15380#discussion_r3035541308), we were asked to revert it back to the original single-line format. I have also updated createCitation and createInTextCitation to use the same single line format for consistency.

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 21]
```diff
@@ -324,23 +305,7 @@ private void updateAllCitationsWithNewStyle(CitationStyle style, CSLCitationType
...
-                    String formattedCitation = CSLFormatUtils.transformHTML(newCitation);
-
-                    if (isNumericStyle) {
-                        formattedCitation = updateSingleOrMultipleCitationNumbers(formattedCitation, List.of(currentEntry));
-                        String prefix = CSLFormatUtils.generateAuthorPrefix(currentEntry, unifiedBibDatabaseContext);
-                        formattedCitation = prefix + formattedCitation;
-                    } else if (!isAlphaNumericStyle) {
-                        formattedCitation = CSLFormatUtils.changeToInText(formattedCitation);
-                    }
+                    String formattedCitation = createInTextCitation(style, isAlphaNumericStyle, isNumericStyle, currentEntry, unifiedBibDatabaseContext);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: This name can now just be citation, as "citation vs formattedCitation" now got abstracted in your helper method

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 22]
```diff
@@ -361,22 +326,49 @@ private void updateAllCitationsWithNewStyle(CitationStyle style, CSLCitationType
...
-
-                if (isAlphaNumericStyle) {
-                    newCitation = CSLFormatUtils.generateAlphanumericCitation(entries, unifiedBibDatabaseContext);
-                } else {
-                    newCitation = CitationStyleGenerator.generateCitation(entries, style.getSource(),
-                            HTML_OUTPUT_FORMAT, unifiedBibDatabaseContext, bibEntryTypesManager);
-                }
-
-                String formattedCitation = CSLFormatUtils.transformHTML(newCitation);
+                String formattedCitation = createCitation(style, isAlphaNumericStyle, entries, unifiedBibDatabaseContext);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Same here

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 23]
```diff
@@ -132,40 +133,20 @@ public void insertInTextCitation(XTextCursor cursor, CitationStyle selectedStyle
...
-            if (isNumericStyle) {
-                formattedCitation = updateSingleOrMultipleCitationNumbers(formattedCitation, List.of(currentEntry));
-                String prefix = CSLFormatUtils.generateAuthorPrefix(currentEntry, bibDatabaseContext);
-                finalText = prefix + formattedCitation;
-            } else if (isAlphanumericStyle) {
-                finalText = formattedCitation;
-            } else {
-                finalText = CSLFormatUtils.changeToInText(formattedCitation);
-            }
+            String formattedCitation = createInTextCitation(selectedStyle, isAlphanumericStyle, isNumericStyle, currentEntry, bibDatabaseContext);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Here as well.
In fact, I'd say after this line create another String finalText = citation; then let the commas be added to finalText and then use it in ootext (as per the original code).

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 24]
```diff
@@ -361,22 +326,49 @@ private void updateAllCitationsWithNewStyle(CitationStyle style, CSLCitationType
...
+        if (isAlphaNumericStyle) {
+            citation = CSLFormatUtils.generateAlphanumericCitation(entries, unifiedBibDatabaseContext);
+        } else {
+            citation = CitationStyleGenerator.generateCitation(entries, style.getSource(), HTML_OUTPUT_FORMAT, unifiedBibDatabaseContext, bibEntryTypesManager);
+        }
+
+        return CSLFormatUtils.transformHTML(citation);
+    }
+
+    ///  Helper method for updateAllCitationsWithNewStyle and insertInTextCitation.
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Since we are using markdown javadoc
```suggestion
    ///  Helper method for creating in-text citations for `updateAllCitationsWithNewStyle` and `insertInTextCitation`.
```

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 25]
```diff
@@ -361,22 +326,49 @@ private void updateAllCitationsWithNewStyle(CitationStyle style, CSLCitationType
...
-
-                String formattedCitation = CSLFormatUtils.transformHTML(newCitation);
+                String formattedCitation = createCitation(style, isAlphaNumericStyle, entries, unifiedBibDatabaseContext);
 
                 markManager.updateMarkAndTextWithNewStyle(mark, formattedCitation, CSLCitationType.NORMAL);
             }
         }
     }
 
+    /// Helper method for updateAllCitationsWithNewStyle and insertCitation.
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]:
```suggestion
    /// Helper method for creating citations for `updateAllCitationsWithNewStyle` and `insertCitation`.
```

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 26]
```diff
@@ -361,22 +326,49 @@ private void updateAllCitationsWithNewStyle(CitationStyle style, CSLCitationType
...
+    private @NonNull String createCitation(CitationStyle style, boolean isAlphaNumericStyle, List<BibEntry> entries, BibDatabaseContext unifiedBibDatabaseContext) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Maybe rename to `createCitationText` to avoid confusion with `generateCitation`.

File: jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java [hunk 27]
```diff
@@ -361,22 +326,49 @@ private void updateAllCitationsWithNewStyle(CitationStyle style, CSLCitationType
...
+            citation = CSLFormatUtils.generateAlphanumericCitation(entries, unifiedBibDatabaseContext);
+        } else {
+            citation = CitationStyleGenerator.generateCitation(entries, style.getSource(), HTML_OUTPUT_FORMAT, unifiedBibDatabaseContext, bibEntryTypesManager);
+        }
+
+        return CSLFormatUtils.transformHTML(citation);
+    }
+
+    ///  Helper method for updateAllCitationsWithNewStyle and insertInTextCitation.
+    private @NonNull String createInTextCitation(CitationStyle style, boolean isAlphaNumericStyle, boolean isNumericStyle, BibEntry currentEntry, BibDatabaseContext bibDatabaseContext) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/oocsltext/CSLCitationOOAdapter.java]: Maybe rename to `createInTextCitationText`

File: jablib/src/main/java/org/jabref/logic/openoffice/frontend/OOFrontend.java [hunk 28]
```diff
@@ -325,7 +325,7 @@ public List<RangeForOverlapCheck<CitationGroupId>> viewCursorRanges(XTextDocumen
     ///
     /// Note: Here we directly communicate to the document, not through the backend. This is because mapping ranges to footnote marks does not depend on how do we mark or structure those ranges.
     public List<RangeForOverlapCheck<CitationGroupId>>
-    footnoteMarkRanges(XTextDocument doc, List<RangeForOverlapCheck<CitationGroupId>> citationRanges) {
+    footnoteMarkRanges(List<RangeForOverlapCheck<CitationGroupId>> citationRanges) {
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/openoffice/frontend/OOFrontend.java:328]: Good catch!

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBaseConnect.java [hunk 29]
```diff
@@ -218,16 +218,7 @@ public boolean isDocumentConnectionMissing() {
...
 
-    /// Either return a valid XTextDocument or throw NoDocumentException.
-    public XTextDocument getXTextDocumentOrThrow()
-            throws
-            NoDocumentException {
-        if (isDocumentConnectionMissing()) {
-            throw new NoDocumentException("Not connected to document");
-        }
-        return this.xTextDocument;
-    }
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBaseConnect.java:229]: Thanks for cleaning this up as well

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java [hunk 30]
```diff
@@ -819,54 +879,20 @@ public Optional<BibDatabase> exportCitedHelper(List<BibDatabase> databases, bool
...
-                }
+        OOResult<XTextDocument, OOError> odoc = getXTextDocument();
+        XTextDocument doc = odoc.get();
+        OOResult<FunctionalTextViewCursor, OOError> fcursor = getFunctionalTextViewCursor(doc, errorTitle);
+        OOResult<OOFrontend, OOError> frontend = getFrontend(doc);
 
-                List<String> unresolvedKeys;
-                try {
-                    UnoUndo.enterUndoContext(doc, "Refresh bibliography");
+        if (!performPreUpdateChecks(errorTitle, odoc, style, getFrontend(doc), fcursor, doc)) {
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: As mentioned in an earlier comment, this changes semantics - for example, fcursor was earlier being fetched only if doc, odoc passed the earlier checks, etc.

Please revert.

**Review by subhramit — CHANGES_REQUESTED** [review]
One more iteration of comments. Thanks for keeping patience and following up so far.

File: jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java (hunk 30 above)
Comment (amanda-d-e) [reply jabgui/src/main/java/org/jabref/gui/openoffice/OOBibBase.java]: Hello @subhramit, I have reverted the extracted method. I think that should be the last of the requested fixes, but please let me know if we are missing anything or if you would like anything else changed. 

Thank you for your guidance. This has been a very valuable learning experience for my group and I, and we appreciate the opportunity to work on this issue.

**Review by subhramit — APPROVED** [review]
LGTM
Would wait for @pluto-han for a second final look.

Thanks a lot team @anuv-bit @amanda-d-e @sam-r914 for your patience.

**Comment by subhramit** [comment]
Letting this in.

**Comment by pluto-han** [comment]
Sorry for the late comment, I missed https://github.com/JabRef/jabref/pull/15380#pullrequestreview-4135067436.

Appreciate for your great work and quick follow-ups! @anuv-bit @amanda-d-e @sam-r914
