### PR TITLE
Fix parser exception when loading tex-groups with non-existing file

### LINKED ISSUE #4735: Non-existing aux file in group throws IOException
JabRef dev version  on Windows 10 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Create a group based on aux file
2. Close and save library
3. Remove aux file
4. Open library again -> get error message because of IOException, group tree is empty

Solution:
Catch exception (and log warning) here https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/model/groups/TexGroup.java#L31

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes #4735. 
Catch file not found exception and handle non existing aux files gracefully.

----

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/groups/GroupDialog.java [hunk 1]
```diff
@@ -466,7 +466,7 @@ private VBox createOptionsTexGroup() {
         texGroupBrowseButton.setOnAction((ActionEvent e) -> openBrowseDialog());
         texGroupHBox.getChildren().add(texGroupFilePath);
         texGroupHBox.getChildren().add(texGroupBrowseButton);
-        texGroupHBox.setHgrow(texGroupFilePath, Priority.ALWAYS);
+        HBox.setHgrow(texGroupFilePath, Priority.ALWAYS);
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/groups/GroupDialog.java]: What's this making for a difference?

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/groups/GroupDialog.java]: It's a static method, so there is no reason to call it from an instance variable (btw: automatic change by Intellj)
