### PR TITLE
Fix #2775: Hyphens in last names are properly parsed

### LINKED ISSUE #2775: Losing hyphens between prefix and last name
JabRef version JabRef 3.8.2
mac os x 10.11.6 x86_64 
Java 1.8.0_121

JabRef normalizes "ul-Somewhere, Someone" to "ul Somewhere, Someone" (undesirable). This is presumably a side-effect of the (desirable) behaviour of  normalizing "Someone-ul-Somewhere" to "ul-Somewhere, Someone". IOW, the hyphen between first name and prefix should be lost on normalization, but hyphens between prefix and last name should be preserved.

Obviously, there are more prosaic examples. "Someone le-GrandAuthor" should normalize to "le-GrandAuthor, Someone" not "le GrandAuthor, Someone".

[If there is already a bug report on this then I will need guidance on how to use the search field!]

### PR DESCRIPTION
**Pull request by tobiasdiez**
I missed JabRef so much, that I even dared to touch the name parsing algorithm.  
The only real changed consists in the few added lines https://github.com/JabRef/jabref/compare/fix3142?expand=1#diff-b8249d741d31352dd2bcafcab07d9457R147, the rest is only code formatting/renaming of variables. The added tests come from [biblatex](https://github.com/plk/biber/blob/f418da9b1975847461fad884fedf910aed73c13b/t/names.t).

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [ ] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

File: src/test/java/org/jabref/model/entry/AuthorListTest.java [hunk 1]
```diff
@@ -626,6 +626,25 @@ public void parseNameWithHyphenInLastName() throws Exception {
...
+
+    @Test
+    public void parseNameWithHyphenInLastNameWithEscaped() throws Exception {
+        Author expected = new Author("E. S.", "E. S.", null, "{K}ent-{B}oswell", null);
+        Assert.assertEquals(new AuthorList(expected), AuthorList.parse("E. S. {K}ent-{B}oswell"));
+    }
+
+    @Test
+    public void parseNameWithHyphenInLastNameWhenLastNameGivenFirst() throws Exception {
+        // TODO: Fix abbreviation to be "A."
```
Comment (stefan-kolb) [inline src/test/java/org/jabref/model/entry/AuthorListTest.java]: Can you get this working too?

Comment (tobiasdiez) [reply src/test/java/org/jabref/model/entry/AuthorListTest.java]: Sadly no. I tried to fix it but the extraction of the abbreviation from the text is hidden in the whole tokenizing process and thus not easy to change.
