### PR TITLE
Fix: Reset External File Type to default

### LINKED ISSUE #15117: Resetting of Preferences clears External File Type and does not reset them to default
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

_No response_

### Checked with the [latest development build](https://builds.jabref.org/main/) (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to File -> Preferences
2. Click "Reset preferences" 

Image

3. Go to the External File type tab and see that it is empty
4. => They should be reset to their default 
Current workaround is to click "Reset to default" in External File Type as well to make them re-appear

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by pluto-han**
### Related issues and pull requests

Closes #15117 

### PR Description
This PR fixes the issue where resetting preference does not reset External File Type to default. This is fixed by adding `getDefaultExternalFileTypes()` in `ExternalApplicationsPreferences() .ExternalApplicationsPreferences()`.

**Required vefirication screenshot:**
image

### Steps to test
1. Open File -> Preferences. Click reset preferences.

2. Note that it does not clear External File Type but reset it to default.
image
image

### Checklist
- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [x] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/frame/ExternalApplicationsPreferences.java [hunk 1]
```diff
@@ -50,7 +51,7 @@ private ExternalApplicationsPreferences() {
         this(
                 Localization.lang("References"),                                             // eMailSubject
                 OS.WINDOWS,                                                                  // shouldAutoOpenEmailAttachmentsFolder
-                Set.of(),                                                                    // externalFileTypes
+                Set.copyOf(ExternalFileTypes.getDefaultExternalFileTypes()),                                                                    // externalFileTypes
```
Comment (subhramit) [inline jabgui/src/main/java/org/jabref/gui/frame/ExternalApplicationsPreferences.java]: Why copyOf?
Also please adjust the comment alignment with the others in the column

Comment (pluto-han) [reply jabgui/src/main/java/org/jabref/gui/frame/ExternalApplicationsPreferences.java]: Because `Set.copyOf` can unpack elements in the list, but `Set.of` cannot.

Comments are aligned now.

**Comment by aniruddhkorde9-dot** [comment]
Hello! I am a new contributor looking to get involved. I would love to work on this issue. Could you please assign it to me?

**Comment by subhramit** [comment]
> Hello! I am a new contributor looking to get involved. I would love to work on this issue. Could you please assign it to me?

You'll be blocked if you have no idea about GitHub and spam assignment requests on PRs this way. Please have the minimum courtesy of looking through how Open Source projects are worked on, and go through a project's contributing guidelines.

**Review by calixtus — APPROVED** [review]
Looks good to me
