### PR TITLE
Fix cleanup Field formatters not working when enabled

### LINKED ISSUE #6787: Settings in "Enable field formatter" in "Cleanup entries" do not work
JabRef version jabref_5.1-1_amd64.deb (build 2020-08-22)  on Linux (Ubuntu 20.04) 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Settings in "Enable field formatter" in "Cleanup entries" do not work at all. 

1. create new entrytype book with the following info.
    + title: test for title case
    + url: any url address
2. In "Enable field formatter" in "Cleanup entries", set the following:
    + title: Title case
    + url: Clear 
3. When click the cleanup entry button (or from Quality menu), title should be formatted as Title case (change to: Test for Title Case) and url field should be empty. However, nothing is changed: title is still in all lower case and url is still there.

My actual setting is much more complicated with much more fields and other settings but none of them works. 

I like the new version with filter group on top since I have several thousands of entries in my database and the list of group is very long. Hpefully it would be an easy fix otherwise I'll be forced to install the stable version since I use the "cleanup entry" tool very frequently.  

Is there anything you can do to help?  Thanks.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #6787

The problem orginally comes from here:
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/gui/commonfxcontrols/FieldFormatterCleanupsPanel.java#L109

Unfortuantely it's not possible to add a not() there directly
The method bindBidirectional(Property<Boolean>) in the type BooleanProperty is not applicable for the arguments (BooleanBinding)

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/commonfxcontrols/FieldFormatterCleanupsPanel.java [hunk 1]
```diff
@@ -106,7 +106,13 @@ private void setupCombos() {
     }
 
     private void setupBindings() {
-        cleanupsEnabled.selectedProperty().bindBidirectional(cleanupsDisableProperty());
+        // cannot bindBidirectional, because viewModel.cleanupsDisableProperty().not() provides a read only
+        // BooleanBinding, but bindBidirectional requires a simple BooleanProperty
+        cleanupsEnabled.selectedProperty().addListener((observableValue, oldValue, newValue) ->
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/commonfxcontrols/FieldFormatterCleanupsPanel.java:111]: Please replace this custom binding with https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/util/BindingsHelper.java#L62

The manual listeners may result in a race condition, where the update of cleanupsDisableProperty results in an update of cleanupsEnabled which then again updates cleanupsDisableProperty  etc. To prevent this, a locked update mechanism is used in the above `bindBidirection`: https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/util/BindingsHelper.java#L227

**Review by tobiasdiez — COMMENTED** [review]
I don't think that's a stopper for 5.1, but it would be good to improve the fix to reduce the danger of a continuous loop.

**Comment by calixtus** [comment]
done
