### PR TITLE
Fixed Url column

### LINKED ISSUE #3860: The `URL` column missed in the maintable beta version
Look at the screenshot:

image

### PR DESCRIPTION
**Pull request by florian-beetz**
This fixes #3860 

URL Column now shows URL or DOI correctly and opens on click.

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java [hunk 1]
```diff
@@ -269,20 +277,50 @@ private ContextMenu createFileMenu(BibEntryTableViewModel entry, List<LinkedFile
...
+     * The {@code firstField} is preferred to be shown over {@code secondField}.
      */
-    private TableColumn<BibEntryTableViewModel, String> createIconColumn(JabRefIcon icon, String firstField, String secondField) {
+    private TableColumn<BibEntryTableViewModel, String> createUrlOrDoiColumn(JabRefIcon icon, String firstField, String secondField) {
         TableColumn<BibEntryTableViewModel, String> column = new TableColumn<>();
         column.setGraphic(icon.getGraphicNode());
         column.getStyleClass().add(ICON_COLUMN);
         setExactWidth(column, GUIGlobals.WIDTH_ICON_COL);
-        column.setCellValueFactory(cellData -> EasyBind.monadic(cellData.getValue().getField(firstField)).orElse(cellData.getValue().getField(secondField)));
+        column.setCellValueFactory(cellData -> EasyBind.monadic(cellData.getValue().getField(firstField)).map(x -> firstField).orElse(EasyBind.monadic(cellData.getValue().getField(secondField)).map(x -> secondField)));
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: whats the purpose of the added `map` calls? They seem to always replace the cell value by `firstField` and `secondField`, respectively.

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java [hunk 2]
```diff
@@ -269,20 +277,50 @@ private ContextMenu createFileMenu(BibEntryTableViewModel entry, List<LinkedFile
...
+                field = firstField;
+            } else if (entry.getEntry().hasField(secondField)) {
+                field = secondField;
+            } else {
+                // nothing to open
+                LOGGER.debug("Requested opening DOI or URL, but none present.");
+                return;
+            }
+
+            entry.getEntry().getField(field).ifPresent(url -> {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: I think this needs to be
````java
entry.getEntry()
   .getField(field)
   .map(value -> IdentifierParser.parse(field, value))
   .flatMap(Identifier::getExternalURI)
   .ifPresent(
                url -> {
                    try {
                        JabRefDesktop.openBrowser(url);
                    } catch (IOException ex) {
                        dialogService.showErrorDialogAndWait(Localization.lang("Unable to open link."), ex);
                    }
                }
    );
````
because the doi may not be present as a url but only in short form. Or this automatically handled by `openExternalViewer`? @JabRef/developers whats the preferred way to open dois/url ?

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 1 above)
Comment (florian-beetz) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: Yes, that's exactly what's happening. The reason here is that `CellFactory` is expecting the field name to choose the icon.
I thought about trying to identify if the column contains a DOI or an URL, but I think this is the better approach, as here this information is already there. 
I'm open for different approaches though.

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 2 above)
Comment (florian-beetz) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: `openExternalViewer` can handle DOIs directly. I did not know about `IdentifierParser`, but I can change it, if that's better.

**Comment by LinusDietz** [comment]
Hi @florian-beetz, since you have been involved in the maintable migrations do you want to join tomorrow's Devcall at 11 am? Drop me a note by mail (linus@lynyus.de). Cheers, Linus

**Comment by stefan-kolb** [comment]
It looks like `MainTableSelectionListener` uses `JabRefDesktop.openExternalViewer(panel.getBibDatabaseContext(), link, fieldName);` Line 259.

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 2 above)
Comment (stefan-kolb) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: It looks like MainTableSelectionListener uses JabRefDesktop.openExternalViewer(panel.getBibDatabaseContext(), link, fieldName); Line 259.

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 1 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: ok, makes sense. The code looks a bit strange but I'm not able to find a more readable solution. Could you please add a short comment explaining the construction. Thanks!

File: src/main/java/org/jabref/gui/maintable/CellFactory.java [hunk 3]
```diff
@@ -10,96 +10,98 @@
...
-        TABLE_ICONS.put(SpecialField.PRINTED.getFieldName(), label);
+        icon = printedViewModel.getIcon();
+        //icon.setToolTipText(printedViewModel.getLocalization());
+        TABLE_ICONS.put(SpecialField.PRINTED.getFieldName(), icon);
     }
 
     public Node getTableIcon(String fieldType) {
-        Node label = TABLE_ICONS.get(fieldType);
-        if (label == null) {
+        JabRefIcon icon = TABLE_ICONS.get(fieldType);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/CellFactory.java]: If I understand the code below correctly, then this method is hit quite often with an empty (or null) string. In these cases (checked using `StringUtil.isBlank`), we can simply return null before looking in the `Map` for a suitable icon.

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java [hunk 4]
```diff
@@ -269,20 +277,50 @@ private ContextMenu createFileMenu(BibEntryTableViewModel entry, List<LinkedFile
...
+    private TableColumn<BibEntryTableViewModel, String> createUrlOrDoiColumn(JabRefIcon icon, String firstField, String secondField) {
         TableColumn<BibEntryTableViewModel, String> column = new TableColumn<>();
         column.setGraphic(icon.getGraphicNode());
         column.getStyleClass().add(ICON_COLUMN);
         setExactWidth(column, GUIGlobals.WIDTH_ICON_COL);
-        column.setCellValueFactory(cellData -> EasyBind.monadic(cellData.getValue().getField(firstField)).orElse(cellData.getValue().getField(secondField)));
+        column.setCellValueFactory(cellData -> EasyBind.monadic(cellData.getValue().getField(firstField)).map(x -> firstField).orElse(EasyBind.monadic(cellData.getValue().getField(secondField)).map(x -> secondField)));
                 new ValueTableCellFactory<BibEntryTableViewModel, String>()
                         .withGraphic(cellFactory::getTableIcon)
+                        .withOnMouseClickedEvent((entry, content) -> createOpenUrlOrDoiHandler(entry, firstField, secondField))
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: I hope a construction like `(entry, content) -> event -> openurlOrDoi(event, entry, content)` with method `openUrlOrDoi(MouseEvent event, BibentryTableViewmodel entry, String field)` should work and is a bit easier to parse.

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java [hunk 5]
```diff
@@ -269,20 +277,50 @@ private ContextMenu createFileMenu(BibEntryTableViewModel entry, List<LinkedFile
...
+                    JabRefDesktop.openExternalViewer(database, url, field);
+                } catch (IOException e) {
+                    LOGGER.error("Failed to open external viewer for '{}'", url, e);
+                }
+            });
+            event.consume();
+        };
+    }
+
     private TableColumn<BibEntryTableViewModel, String> createIconColumn(JabRefIcon icon, String field) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: Could you please fix this method for the `eprint` column as well. Thanks!

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 2 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: ok, then simply ignore my remark and keep the `openExternalViewer` call.

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 5 above)
Comment (florian-beetz) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: Done!

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 4 above)
Comment (florian-beetz) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: Done!

File: src/main/java/org/jabref/gui/maintable/CellFactory.java (hunk 3 above)
Comment (florian-beetz) [reply src/main/java/org/jabref/gui/maintable/CellFactory.java]: Done!

File: src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java (hunk 1 above)
Comment (florian-beetz) [reply src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java]: I used `EasyBind.map()` directly, this makes this line somewhat more readable. Additionally to the comment you suggested.

File: src/main/java/org/jabref/gui/maintable/CellFactory.java [hunk 6]
```diff
@@ -10,96 +10,103 @@
...
+    private final Map<String, JabRefIcon> TABLE_ICONS = new HashMap<>();
 
     public CellFactory(ExternalFileTypes externalFileTypes, UndoManager undoManager) {
-        Node label;
-        label = IconTheme.JabRefIcons.PDF_FILE.getGraphicNode();
-        //label.setToo(Localization.lang("Open") + " PDF");
-        TABLE_ICONS.put(FieldName.PDF, label);
+        JabRefIcon icon;
+        icon = IconTheme.JabRefIcons.PDF_FILE;
+        //icon.setToo(Localization.lang("Open") + " PDF");
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/maintable/CellFactory.java]: What about the tooltips @tobiasdiez ? I think we should have them

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/maintable/CellFactory.java]: Tooltips should indeed be reimplemented. However, I don't think that these old generic ones are really helpful. Instead of "Open PDF" I would prefer a tooltip that really explains what will happen if you click on the icon, i.e "Open filename.pdf".

Not sure if this should be part of this PR or a follow-up.

Comment (stefan-kolb) [reply src/main/java/org/jabref/gui/maintable/CellFactory.java]: Lets do it as a follow up?

**Comment by LinusDietz** [comment]
Okay, merging this in order to move on. I have created another issue to track the tooltips. https://github.com/JabRef/jabref/issues/3973
