### PR TITLE
Fix biblatex cleanup for date field

### LINKED ISSUE #2335: Biblatex Cleanup for moving year+ month to Date field not working
Version 3.7, I think it dit not work in 3.6, too.
According to the code, the Biblatex Cleanup should cleanup/move the fields year + months etc to date

However, it currently gives always "No Entry needed a cleanup".
'Tested with different entrytypes and both year and month were set.

```
@Article{Orlowski;2011,
  author        = {Adam Czarnecki; Cezary Orłowski;},
  title         = {Application of Ontology In the ITIL Domain},
  year          = {2011},
  month         = jan,
}
```

https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java

### PR DESCRIPTION
**Pull request by Siedlerchr**
This fixes #2335 
Moved biblatex Cleanup to new test
- [X] Change in CHANGELOG.md described
- [X] Tests created for changes
- [X] Manually tested changed features in running JabRef
- [X] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Failing test is something from Medline, not related

File: src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java [hunk 1]
```diff
@@ -35,22 +35,26 @@
...
-                    changes.add(new FieldChange(entry, FieldName.MONTH, oldMonth.orElse(null), null));
-                });
-            }
-        });
+        // If there already exists a value for the field date, it is not overwritten
+        String date = "";
+        if (entry.getField(FieldName.DATE).isPresent()) {
+            date = entry.getField(FieldName.DATE).get();
+        }
+        if (date.isEmpty()) {
```
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java]: I think `if (StringUtils.isBlank (entry.getField(FieldName.DATE)))` is cleaner (not sure about the naming)

File: src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java [hunk 2]
```diff
@@ -35,22 +35,26 @@
...
+            entry.getFieldOrAlias(FieldName.DATE).ifPresent(newDate -> {
+                Optional<String> oldYear = entry.getField(FieldName.YEAR);
+                Optional<String> oldMonth = entry.getField(FieldName.MONTH);
+
+                entry.setField(FieldName.DATE, newDate);
```
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java]: If I remember correctly, then set/clearField already return the right FieldChange

File: src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+public class BiblatexCleanupTest {
+
+    @Rule
+    public TemporaryFolder bibFolder = new TemporaryFolder();
+
+    private CleanupWorker worker;
+
+    @Before
+    public void setUp() throws IOException {
+
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java]: Remove empty line

File: src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+        MetaData metaData = new MetaData();
+        BibDatabaseContext context = new BibDatabaseContext(new BibDatabase(), metaData, bibFolder.newFile("test.bib"));
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java]: Do we really need a create a file?

File: src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+                        JabRefPreferences.getInstance().getFileDirectoryPreferences()));
+    }
+
+    @Test
+    public void convertToBiblatexMovesJournalToJournalTitle() {
+        CleanupPreset preset = new CleanupPreset(CleanupPreset.CleanupStep.CONVERT_TO_BIBLATEX);
+        BibEntry entry = new BibEntry();
+        entry.setField(FieldName.JOURNAL, "test");
+
+        worker.cleanup(preset, entry);
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java]: directly use the BiblatexCleanup.cleanup method instead of using the worker (makes tests and initialization more transparent)

File: src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java [hunk 6]
```diff
@@ -308,17 +308,6 @@ public void cleanupLatexMergesTwoLatexMathEnvironments() {
     }
 
     @Test
-    public void convertToBiblatexMovesJournalToJournalTitle() {
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java]: I would leave this test here to make sure that the CleanupWorker works correctly wrt to the "Convert to BibLatex" option; the other test class for the BibLatexCleanupJob then only tests this class directly.

File: src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java (hunk 2 above)
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java]: That was part of the code I didn't touch

File: src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java (hunk 1 above)
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java]: I used this approach, because it captures 2 purposes and checks the optonal
a) If the field is not present the date is empty
b) if the field is present, we assign the value, however, it still might be empty

File: src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java [hunk 7]
```diff
@@ -25,33 +26,22 @@
             entry.getField(oldFieldName).ifPresent(oldValue -> {
                 if (!oldValue.isEmpty() && (!entry.getField(newFieldName).isPresent())) {
                     // There is content in the old field and no value in the new, so just copy
-                    entry.setField(newFieldName, oldValue);
-                    changes.add(new FieldChange(entry, newFieldName, null, oldValue));
-
-                    entry.clearField(oldFieldName);
-                    changes.add(new FieldChange(entry, oldFieldName, oldValue, null));
+                    changes.add(entry.setField(newFieldName, oldValue).orElse(null));
```
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java]: entry.setField(...).ifPresent(changes::add), otherwise you add null values to the list which is not so nice.

File: src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java [hunk 8]
```diff
@@ -25,33 +26,22 @@
...
         }
-
         // Dates: create date out of year and month, save it and delete old fields
         // If there already exists a value for the field date, it is not overwritten
         String date = "";
         if (entry.getField(FieldName.DATE).isPresent()) {
             date = entry.getField(FieldName.DATE).get();
         }
-        if (date.isEmpty()) {
+        if (StringUtils.isBlank(date)) {
```
Comment (tobiasdiez) [inline src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java]: isBlank also accepts an optional I think (if not, please add a corresponding overload), hence `Optional<String> date = entry.getField(FieldName.DATE)` should work.

**Comment by Siedlerchr** [comment]
However  in  this  case  that  would  result  in  the  original  bug
 again, when checked for ifPresent !

If the field is not yet in the biblatex entry (which is obviously the case
when you only have year), it returns an EmtyOptional and thus you would
have the same situation as in the original code.
This is why I splitted it.




Am 05.12.2016 4:21 nachm. schrieb "Tobias Diez" <notifications@github.com>:

*@tobiasdiez* commented on this pull request.
------------------------------

In src/main/java/net/sf/jabref/logic/cleanup/BiblatexCleanup.java
<https://github.com/JabRef/jabref/pull/2339#pullrequestreview-11398588>:

>          // Dates: create date out of year and month, save it and delete old fields
         // If there already exists a value for the field date, it is
not overwritten
         String date = "";
         if (entry.getField(FieldName.DATE).isPresent()) {
             date = entry.getField(FieldName.DATE).get();
         }
-        if (date.isEmpty()) {
+        if (StringUtils.isBlank(date)) {

isBlank also accepts an optional I think (if not, please add a
corresponding overload), hence Optional<String> date =
entry.getField(FieldName.DATE) should work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/pull/2339#pullrequestreview-11398588>,
or mute
the thread

**Comment by Siedlerchr** [comment]
Failing Snap CI is due to HTTP error 502 in AstrophysicsDataSystemTest

**Comment by koppor** [comment]
Could you please merge master again - I merged https://github.com/JabRef/jabref/pull/2333 and thus SnapCI only does the basic tests as described at https://github.com/JabRef/jabref/wiki/CI#snapci 😇

**Comment by tobiasdiez** [comment]
@Siedlerchr: sorry I don't understand you comment.
Let go through this case by case with the following code:
````
Optional<String> date = entry.getField(FieldName.DATE);
Boolean isBlank = StringUtils.isNotBlank(date);
````

case | date | isBlank |
---- | --- | --- |
no date at all | Optional.empty | true
empty string | Optional.of("") | true
something else | Optional.of("something") | false

You want to move year and month to the date field exactly in the first two cases, i.e., if and only if `isBlank == true`. What do I miss?

**Comment by Siedlerchr** [comment]
Ah now I understand your comment, the first case was not obvious for me, that an empty should return true.

**Comment by Siedlerchr** [comment]
@tobiasdiez The confusion came from the naming stuff. I previously had the apache.commons StringUtil class and not the jabref specific one. Changed that.

File: src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+import org.junit.Assert;
+import org.junit.Before;
+import org.junit.Rule;
+import org.junit.Test;
+import org.junit.rules.TemporaryFolder;
+
+public class BiblatexCleanupTest {
+
+    @Rule
+    public TemporaryFolder bibFolder = new TemporaryFolder();
```
Comment (koppor) [inline src/test/java/net/sf/jabref/logic/cleanup/BiblatexCleanupTest.java]: Is this variable ever used?

**Comment by koppor** [comment]
Besides the micro comment: LGTM :+1:

File: src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java [hunk 10]
```diff
@@ -307,11 +308,11 @@ public void cleanupLatexMergesTwoLatexMathEnvironments() {
     public void convertToBiblatexMovesJournalToJournalTitle() {
         CleanupPreset preset = new CleanupPreset(CleanupPreset.CleanupStep.CONVERT_TO_BIBLATEX);
         BibEntry entry = new BibEntry();
-        entry.setField("journal", "test");
+        entry.setField(FieldName.JOURNAL, "test");
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/logic/cleanup/CleanupWorkerTest.java]: Please revert these changes, as hard-coded strings in tests are actually desirable. The logic for the conversation moves FieldName.JOURNAL to FieldName,JOURNALTITLE. Hence if somebody changes `FieldName.JOURNAL = "stupid"` the test still passes but the functionality is broken.
