### PR TITLE
Fix: Disable AI Export button when chat history is empty

### LINKED ISSUE #14640: Disable Export button if no AI Chat is there
Follow-up to https://github.com/JabRef/jabref/pull/14486

1. Enable AI in JabRef - https://docs.jabref.org/ai/preferences
2. Open a library with a PDF attached - e.g., https://github.com/JabRef/jabref-demonstration-libraries/tree/main/chocolate
3. Select the PDF
4. Go to tab "AI Chat"
5. See that "Export" is enabled\
    Image
6. Expected: The button should only be enabled if there is some chat message

This issue requires a diving into JavaFX bindings.

---

Also implement if for "Chat with groups"

Image

### PR DESCRIPTION
**Pull request by TimeTriggerx**
Closes #14640

This PR ensures that the AI **Export** button is dynamically disabled when the chat history is empty.  
A JavaFX binding was implemented in the `AiChatComponent` controller to bind the `MenuButton.disableProperty()` to the empty state of the chat history observable list.  
This guarantees consistent behavior across both the **Entry Editor AI tab** and the **"Chat with groups"** window, as they share the same underlying component.

### Steps to test

1. **Initial State**
   - Open JabRef and navigate to an entry with an attached PDF.
   - Open the **AI chat** tab.
   - Verify that the **Export** button is disabled by default when no chat messages are present.

2. **Enabled State**
   - Send a message in the AI chat.
   - Once the message appears in the chat history, verify that the **Export** button becomes enabled immediately.

3. **Reset State**
   - Click the **Clear chat history** (trash icon) at the bottom of the chat.
   - Confirm the action.
   - Verify that the **Export** button returns to a disabled state.

4. **Group Chat**
   - Right-click a group and select **Chat with group**.
   - Verify that the **Export** button behavior matches the entry editor AI tab:
     - Disabled when the chat is empty
     - Enabled after sending a message
     - Disabled again after clearing the chat
  
### Screenshots of the issue being fixed

- **AI Tab View (Empty Chat)**
entry ai chat

- **Group Chat Window (Empty Chat)**
group

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [x] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java [hunk 1]
```diff
@@ -429,11 +432,6 @@ private Optional<UserMessage> getLastUserMessage() {
 
     @FXML
     private void exportMarkdown() {
-        if (aiChatLogic.getChatHistory().isEmpty()) {
-            dialogService.notify(Localization.lang("No chat history to export"));
-            return;
-        }
-
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java:436]: replace by "assert"

File: jabgui/src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java [hunk 2]
```diff
@@ -456,11 +454,6 @@ private void exportMarkdown() {
 
     @FXML
     private void exportJson() {
-        if (aiChatLogic.getChatHistory().isEmpty()) {
-            dialogService.notify(Localization.lang("No chat history to export"));
-            return;
-        }
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java:462]: replace by "assert"
