### PR TITLE
Fix #3994 Duplicate unmodifiable list for sorting

### LINKED ISSUE #3994: Copy to clipboard
JabRef version 4.2 on  Windows 7

1. Select item(s)
2. Contextual menu : copy -> export to clipboard 

Nothing happens (tried different items without success). Normally, it appears a windows with all export formats. 
```

runCommand error: null
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableList.sort(Unknown Source)
	at org.jabref.gui.exporter.ExportToClipboardAction.run(ExportToClipboardAction.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by stefan-kolb**
Fix #3994 
```
runCommand error: null
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableList.sort(Unknown Source)
	at org.jabref.gui.exporter.ExportToClipboardAction.run(ExportToClipboardAction.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)
```

### CODE REVIEW

File: src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java [hunk 1]
```diff
@@ -55,9 +51,8 @@ public void run() {
             return;
         }
 
-        List<Exporter> exporters = Globals.exportFactory.getExporters();
-        exporters.sort(Comparator.comparing(Exporter::getDisplayName));
-        List<String> exportFormatDisplayNames = exporters.stream().map(Exporter::getDisplayName).collect(Collectors.toList());
+        List<Exporter> sortedExporters = Globals.exportFactory.getExporters().stream().sorted(Comparator.comparing(Exporter::getDisplayName)).collect(Collectors.toList());
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/exporter/ExportToClipboardAction.java]: I think you can improve this a bit, if you return here only the stream, and reuse it for the displayName. Is more efficent then adding it to a list and iterating that list again.
