### PR TITLE
Fix: Auto-detect identifier type when typing in identifier field

### LINKED ISSUE #14660: Typing in identifier field should change type
1. Copy `https://arxiv.org/html/2503.08641v1#bib.bib5` to the clipboard
2. Go to JabRef and select "New Entry..."
3. See that identifier is not known\
    Image

Now adapt the field content to `2503.08641v1`.

Expectation: "arXiv" is selected.

Actual: Nothing happens.

### PR DESCRIPTION
**Pull request by atul-raman**
Closes #14660

This PR fixes issue #14660 by implementing automatic identifier type detection when a user types in the identifier field of the "New Entry" dialog. The identifier type dropdown now automatically updates to reflect the detected type (arXiv, DOI, ISBN, etc.) as the user types, but only when "Automatically determine identifier type" is selected.

### Steps to test

1. Open JabRef and create/open a library
2. Go to Entry → New Entry...
3. Click the "Enter Identifier" tab
4. Ensure "Automatically determine identifier type" is selected
5. Type `2503.08641v1` in the identifier field
6. The "Identifier type" dropdown should automatically change to "arXiv"
7. Test with other identifiers:
   - Type `10.1234/example` → should detect "DOI"
   - Type an ISBN → should detect "ISBN"
8. Test mode switching: Switch to "Identifier type" mode, then back to "Automatically determine" → should detect identifier from current text

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [x] I described the change in `CHANGELOG.md` in a way that is understandable for the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request updating file(s) in <https://github.com/JabRef/user-documentation/tree/main/en>.

## Changes

- Added `ChangeListener` to identifier input field (`idText`) to detect identifier type on input
- Automatically updates `idFetcher` ComboBox when valid identifier is detected
- Only updates when "Automatically determine identifier type" is selected
- Also detects identifier type when switching to auto-detect mode
- Handles arXiv, DOI, ISBN, RFC, and SSRN identifier types
- Extracted identifier validation logic into `isValidIdentifier()` method to avoid code duplication
- Validates DOI and ISBN identifiers before updating fetcher

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java [hunk 1]
```diff
@@ -320,7 +320,24 @@ private void initializeLookupIdentifier() {
...
+                    boolean isValid = switch (id) {
+                        case DOI doi -> DOI.isValid(doi.asString());
+                        case ISBN isbn -> isbn.isValid();
+                        default -> true;
+                    };
+                    if (isValid) {
+                        fetcherForIdentifier(id).ifPresent(idFetcher::setValue);
+                    }
+                }
+            }
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java]: Try to reduce code duplication

File: jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java [hunk 2]
```diff
@@ -89,44 +89,73 @@ public class NewEntryView extends BaseDialog<BibEntry> {
...
+    @FXML
+    private TitledPane entryOtherTitle;
+    @FXML
+    private TilePane entryOther;
+    @FXML
+    private TitledPane entryCustomTitle;
+    @FXML
+    private TilePane entryCustom;
+    @FXML
+    private TitledPane entryNonStandardTitle;
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java]: NO, PLEASE NOT

DO  NOT  REFORMAT. TELL YOUR AI!!!!!!

**Comment by atul-raman** [comment]
Hi @koppor,

I see the format check is failing, but you said not to reformat the entire file. 
The code I added looks like it's correctly formatted. Could you please let me know what you'd like me to do? I want to make sure I follow the project's guidelines correctly. Thanks!

**Comment by koppor** [comment]
> I see the format check is failing, but you said not to reformat the entire file. The code I added looks like it's correctly formatted. Could you please let me know what you'd like me to do? I want to make sure I follow the project's guidelines correctly. Thanks!

Check the output

image

Reformat that part

You can mark the lines and then press Ctrl+Shift+F

File: jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java [hunk 3]
```diff
@@ -320,7 +320,16 @@ private void initializeLookupIdentifier() {
             Platform.runLater(() -> idLookupGuess.setSelected(true));
         }
 
-        idLookupGuess.selectedProperty().addListener((_, _, newValue) -> preferences.setIdLookupGuessing(newValue));
+        idLookupGuess.selectedProperty().addListener((_, _, newValue) -> {
+            preferences.setIdLookupGuessing(newValue);
+            // When switching to auto-detect mode, detect identifier type from current text
+            if (newValue && idText.getText() != null && !idText.getText().trim().isEmpty()) {
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java]: null checks are from AI

did you check if this really happens????

You can use LOGGER for that

File: jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java [hunk 4]
```diff
@@ -334,6 +343,17 @@ private void initializeLookupIdentifier() {
         idFetcher.setValue(initialFetcher);
         idFetcher.setOnAction(_ -> preferences.setLatestIdFetcher(idFetcher.getValue().getName()));
 
+        // Auto-detect identifier type when typing in the identifier field
+        // Only works when "Automatically determine identifier type" is selected
+        idText.textProperty().addListener((observable, oldValue, newValue) -> {
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java]: ai, ai, ai

Open in IntelliJ and see that `observable` is never used.

**Comment by palukku** [comment]
image
Idk if its supposed to work but when trying with the link that is written in the issue (`https://arxiv.org/html/2503.08641v1#bib.bib5`) it is not switching to the correct identifier type.

Only when typing `2503.08641v1` it works

**Comment by koppor** [comment]
> when trying with the link that is written in the issue (`https://arxiv.org/html/2503.08641v1#bib.bib5`) it is not switching to the correct identifier typ

This is OK - https://github.com/JabRef/jabref/issues/14659 is not yet implemented.

This issue at hand was more a work-around for that issue - I was adapting the string in the box to form a valid Id -and it did not change the identifier.

File: jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java [hunk 5]
```diff
@@ -320,7 +320,17 @@ private void initializeLookupIdentifier() {
...
-        idLookupGuess.selectedProperty().addListener((_, _, newValue) -> preferences.setIdLookupGuessing(newValue));
+        idLookupGuess.selectedProperty().addListener((_, _, newValue) -> {
+            preferences.setIdLookupGuessing(newValue);
+            // When switching to auto-detect mode, detect identifier type from current text
+            if (newValue && !idText.getText().trim().isEmpty()) {
+                String cleanedText = cleanIdentifierText(idText.getText().trim());
+                Optional<Identifier> identifier = Identifier.from(cleanedText);
+                if (identifier.isPresent() && isValidIdentifier(identifier.get())) {
+                    fetcherForIdentifier(identifier.get()).ifPresent(idFetcher::setValue);
+                }
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java]: Code duplication - has to be avoided.

File: jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java [hunk 6]
```diff
@@ -654,22 +676,55 @@ private static IdBasedFetcher fetcherFromName(String fetcherName, List<IdBasedFe
...
+        if (fragmentIndex >= 0) {
+            text = text.substring(0, fragmentIndex);
+        }
+        // Remove query parameters (everything after ?)
+        int queryIndex = text.indexOf('?');
+        if (queryIndex >= 0) {
+            text = text.substring(0, queryIndex);
+        }
+        return text.trim();
+    }
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/newentry/NewEntryView.java:678]: Wrong approach. Just use existing fetcherForIdentifier - which uses org.jabref.model.entry.identifier.Identifier#from

**Review by koppor — CHANGES_REQUESTED** [review]

**Comment by koppor** [comment]
@atul-raman Thank you for updating. I am following the [Boy Scout Rule](https://iamjosephmj.medium.com/the-boy-scout-rule-leaving-code-better-than-you-found-it-fc21857ef8a1) to improve the whole dialog. Will take some more time.

Do not delete TODOs by me - even if code does not compile.

**Comment by koppor** [comment]
@atul-raman if you fix something, please fix it and do not introduce new errors (your last commit introduced a wrong space)

I will merge as is and finish in a separte PR.

Thank you for your efforts so far.

**Review by koppor — APPROVED** [review]
