### PR TITLE
Fixes broken serialization of bibentries containing an @

### LINKED ISSUE #1716: Parsing/Writing of Entry fields containing an @ broken
JabRef version 3.6dev

Steps to reproduce:

1. Use the character "@" in a field of an entry
2. Save the file; Entry looks like this:

```
@Article{asda,
  author = {böser Tit@l},
  title  = {change...},
}
```
3. Change the entry
4. Save again - file is broken:

```
@Article{asda,
  author = {böser Tit

@Article{asda,
  author = {böser Tit@l},
  title  = {change...},
}
```

I don't have any clue why this is happening. But this is clearly a blocker for a 3.6 release. @lenhard You want to waste some of your valuable vacation time? :wink:

### PR DESCRIPTION
**Pull request by matthiasgeiger**
Fixes #1716.

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- ~~Screenshots added (for bigger UI changes)~~
- [x] Manually tested changed features in running JabRef
- ~~Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)~~

As this is rather crucial it would be great if someone else checks what I have done ;-)

To explain: 
```
-                // get the text before the entry
-                String prolog = parsedSerialization.substring(0, parsedSerialization.lastIndexOf('@'));
``` 
... did not work properly if an `@` is used within an entry.

However, determining from the complete parsed serialization where the entry begins and what are comments before the entry is not so trivial. Thus, I added another attribute in the bibentry `commentsBeforeEntry` in which the serialized form of the comments stored in front of the entry is directly saved during parsing the entry.

### CODE REVIEW

File: src/main/java/net/sf/jabref/model/entry/BibEntry.java [hunk 1]
```diff
@@ -573,6 +575,11 @@ public String getParsedSerialization() {
         return parsedSerialization;
     }
 
+    public void setCommentsBeforeEntry(String parsedComments) {
+        this.commentsBeforeEntry = parsedComments;
+    }
+
+
```
Comment (stefan-kolb) [inline src/main/java/net/sf/jabref/model/entry/BibEntry.java]: Please remove this unecessary space.

File: src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java [hunk 2]
```diff
@@ -1631,4 +1631,25 @@ public void parseCommentContainingEntries() throws IOException {
...
+                "  Number                   = {1}" + OS.NEWLINE +
+                "}";
+        // @formatter:on
+
+        ParserResult result = BibtexParser.parse(new StringReader(bibtexEntry));
+        Collection<BibEntry> entries = result.getDatabase().getEntries();
+        BibEntry entry = entries.iterator().next();
+
+        assertEquals(bibtexEntry, entry.getParsedSerialization());
+    }
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java]: Besides checking the parsed serialization, could you please also add another test which checks that an entry containing an at symbol is parsed correctly, i.e. has the correct field values.

**Comment by tobiasdiez** [comment]
LGTM :+1:

File: src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java [hunk 3]
```diff
@@ -224,10 +224,14 @@ private void parseAndAddEntry(String type) {
          * for the user.
          */
         try {
+            String commentsAndEntryTypeDefinitionString = dumpTextReadSoFarToString();
+
             BibEntry entry = parseEntry(type);
 
+            entry.setParsedSerialization(commentsAndEntryTypeDefinitionString+dumpTextReadSoFarToString());
+            entry.setCommentsBeforeEntry(commentsAndEntryTypeDefinitionString.substring(0,commentsAndEntryTypeDefinitionString.lastIndexOf('@')));
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java]: I would extract the `@` symbol as a constant, to make it clear. e.g.  private final `COMMENT_SYMBOL = '@'`

File: src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java [hunk 4]
```diff
@@ -224,10 +224,14 @@ private void parseAndAddEntry(String type) {
          * for the user.
          */
         try {
+            String commentsAndEntryTypeDefinitionString = dumpTextReadSoFarToString();
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java]: Remove the "string" suffix from the variable.

File: src/main/java/net/sf/jabref/model/entry/BibEntry.java [hunk 5]
```diff
@@ -679,25 +686,8 @@ public BibEntry withField(String field, String value) {
...
-                if (prolog.length() > 0) {
-                    return prolog;
-                }
-            } catch (StringIndexOutOfBoundsException ignore) {
-                // if this occurs a broken parsed serialization has been set, so just do nothing
-            }
-        }
-        return "";
+        // delete trailing whitespaces (between entry and text) from stored serialization
+        return commentsBeforeEntry.replaceFirst("\\s+$", "");
```
Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/model/entry/BibEntry.java]: Would a simple trim() work, too?
https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#trim--

**Comment by Siedlerchr** [comment]
Just some minor remarks, LGTM :+1:

File: src/main/java/net/sf/jabref/model/entry/BibEntry.java (hunk 5 above)
Comment (matthiasgeiger) [inline src/main/java/net/sf/jabref/model/entry/BibEntry.java]: Nope. Whitespace in front of the comment should not be removed.

Comment (Siedlerchr) [inline src/main/java/net/sf/jabref/model/entry/BibEntry.java]: Okay. Then I would suggest extracting the Pattern with Pattern.compile and use Matcher.replaceF'irst...
Discussion about it on SO: http://stackoverflow.com/questions/1466959/string-replaceall-vs-matcher-replaceall-performance-differences
https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#replaceFirst(java.lang.String)

File: src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java (hunk 3 above)
Comment (matthiasgeiger) [inline src/main/java/net/sf/jabref/importer/fileformat/BibtexParser.java]: It is not the `COMMENT_SYMBOL` but the general "start of bibtex entry/string/preamble/comment" symbol.
`@` as `char` is used in various places in the parser. However, a) I can't find a good name for the final field and b) I prefer touching this code as little as possible -> I stick to the `'@'` here :)

File: src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java [hunk 6]
```diff
@@ -310,6 +310,40 @@ public void parseRecognizesEntryWhereLastFieldIsFinishedWithComma() throws IOExc
     }
 
     @Test
+    public void parseRecognizesEntryWithAtInField() throws IOException {
+        ParserResult result = BibtexParser.parse(new StringReader("@article{test,author={Ed von T@st}}"));
+
+        List<BibEntry> parsed = result.getDatabase().getEntries();
+        assertEquals(1, parsed.size());
```
Comment (tobiasdiez) [inline src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java]: It is a bit better to compare the parsed list to an expected entry list, i.e.
````
BibEntry expected = new BibEntry("article", "test").withField("author", "bla");
assertEquals(expected as list, parsed);
````

Comment (matthiasgeiger) [inline src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java]: ... which leads to the question whether comments prior the entry are significant to determine "equality" of two entries ;-)

I tend to say "no", thus not modifying the `equals()` method. Other opinions?

Comment (matthiasgeiger) [inline src/test/java/net/sf/jabref/importer/fileformat/BibtexParserTest.java]: > (How that effects @tobiasdiez comment I have no clue about though.)

If `equals()` does not include the pre-entry comments, it is not sufficient in this test to state `assertEquals(expectedList, parsedList)` - because the purpose of the test is to check for the correct parsing of these comments.

**Comment by oscargus** [comment]
We are discussing the failing/unstable GUI tests at #1700

**Comment by lenhard** [comment]
Just my two cents regarding this PR (by looking at the code): Should be fine! I was thinking about implementing something similar (separate comment field in BibEntry) before, but had avoided it so far. There are a lot of tests regarding parsing, so I am confident that we should not meet unexpected NullPointerExceptions and the like.

Good to see that we have a new person who is responsible for implementing the parsing logic ;-)

**Comment by matthiasgeiger** [comment]
Forget it... This parsing stuff is still some black magic for me ;)

**Comment by koppor** [comment]
Refs #123
