### PR TITLE
Fix encoding strings

### LINKED ISSUE #155: [WIP] Consistent encoding strings
JabRef's [current encoding list](https://github.com/JabRef/jabref/blob/be4b2aa2d7744b8b4e28c4662b2145a76470e4be/src/main/java/net/sf/jabref/logic/l10n/Encodings.java) lists possible encodings. 

The strings have flaws:

* `UTF8` and `UTF-16` are possible encodings. I really dislike the inconsistency between them: `UTF8` has no `-`, but `UTF-16` has: Both should have a dash resulting in `UTF-8`. (see https://de.wikipedia.org/wiki/UTF-8)
*  `Cp1251` should be `CP1251` (see http://man7.org/linux/man-pages/man7/cp1251.7.html for example). Similar for all other code pages
*  `ISO8859_15` should be `ISO8859-15` (see https://de.wikipedia.org/wiki/ISO_8859-15). Similar for all other encodings

On the one hand, I am very well aware that a change here results in a large compatibility code where the old strings have to be mapped to the new strings. On the other hand, I would like to see JabRef having strings not causing confusion.

Related: #118, #131

### PR DESCRIPTION
**Pull request by lenhard**
Fixes #155

### CODE REVIEW

File: src/main/java/net/sf/jabref/migrations/PreferencesMigrations.java [hunk 1]
```diff
@@ -28,8 +28,135 @@ public static void performCompatibilityUpdate() {
...
+     */
+    public static void upgradeFaultyEncodingStrings(){
+        JabRefPreferences prefs = Globals.prefs;
+        String defaultEncoding = prefs.get(prefs.DEFAULT_ENCODING);
+
+        if(defaultEncoding == null){
+            return;
+        }
+
+        switch(defaultEncoding){
```
Comment (simonharrer) [inline src/main/java/net/sf/jabref/migrations/PreferencesMigrations.java]: Maybe putting the upgrade mapping in a Map<String, String> would make the code a little bit more readable as the upgrade mapping is clearer to see.

**Comment by simonharrer** [comment]
Nice idea with the preference migration class. 

What about the encoding that is put on the first line of the bib file?

File: src/main/java/net/sf/jabref/migrations/PreferencesMigrations.java (hunk 1 above)
Comment (lenhard) [inline src/main/java/net/sf/jabref/migrations/PreferencesMigrations.java]: Good idea! I'll rewrite that part.

**Comment by lenhard** [comment]
The preference migration class was Stefan's idea :)

The encoding that is put on the first line of the bib file is the value that is stored in `JabRefPreferences.DEFAULT_ENCODING`. Thus, this PR performs the automatic upgrade.

File: src/main/java/net/sf/jabref/logic/l10n/Encodings.java [hunk 2]
```diff
@@ -9,12 +9,12 @@
...
-                    "KOI8_R", // Cyrillic
-                    "EUC_JP", // Added Japanese encodings
-                    "Big5", "Big5_HKSCS", "GBK", "ISO8859_2", "ISO8859_3", "ISO8859_4", "ISO8859_5",
-                    "ISO8859_6", "ISO8859_7", "ISO8859_8", "ISO8859_9", "ISO8859_13", "ISO8859_15"};
+            new String[] {"ISO8859-1", "UTF-8", "UTF-16", "ASCII", "CP1250", "CP1251", "CP1252",
+                    "CP1253", "CP1254", "CP1257", "SJIS",
+                    "KOI8-R", // Cyrillic
+                    "EUC-JP", // Added Japanese encodings
+                    "Big5", "Big5-HKSCS", "GBK", "ISO8859-2", "ISO8859-3", "ISO8859-4", "ISO8859-5",
+                    "ISO8859-6", "ISO8859-7", "ISO8859-8", "ISO8859-9", "ISO8859-13", "ISO8859-15"};
```
Comment (simonharrer) [inline src/main/java/net/sf/jabref/logic/l10n/Encodings.java]: Hm, maybe use an enum here? But this requires more work.

File: src/main/java/net/sf/jabref/importer/ImportFormatReader.java [hunk 3]
```diff
@@ -345,7 +345,7 @@ public static void setIfNecessary(BibtexEntry be, String field, String content)
     }
 
     public static Reader getUTF8Reader(File f) throws IOException {
-        return getReader(f, "UTF8");
+        return getReader(f, "UTF-8");
```
Comment (simonharrer) [inline src/main/java/net/sf/jabref/importer/ImportFormatReader.java]: This should reference a constant from the Encodings class.

**Comment by simonharrer** [comment]
What just came into my mind: the URLDownload class also uses encodings, I think. It would be interesting to search for "utf" in the source code to see if there are any usages of encoding also in other places.

File: src/main/java/net/sf/jabref/logic/l10n/Encodings.java (hunk 2 above)
Comment (lenhard) [inline src/main/java/net/sf/jabref/logic/l10n/Encodings.java]: Yes, this requires major changes, since all of the code relies on strings. I'd rather do this in a second issue / PR.

File: src/main/java/net/sf/jabref/importer/ImportFormatReader.java (hunk 3 above)
Comment (lenhard) [inline src/main/java/net/sf/jabref/importer/ImportFormatReader.java]: There are no constants in the Encodings class so far.

**Comment by simonharrer** [comment]
What about reading a file that uses the old "utf8" encoding. Can this break the functionality as this encoding cannot be resolved anymore?

**Comment by lenhard** [comment]
Searching for "utf": 562 hits. Have fun wading through that ;-) There are also quite some usages of "UTF-8".

Actual encodings are resolved via `ENCODING_NAMES_LOOKUP` in [the Encodings class](https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/l10n/Encodings.java). The old "UTF8" is still in there, as well as "UTF-8", for compatibility. That way it can still be resolved.

**Comment by simonharrer** [comment]
:+1: 

So the migration mapping is a subset of the actual encoding mappings, as far as I understand this. So this is at the moment duplicated. But I am not sure whether we should just leave the duplication as it is.
