### PR TITLE
New fix/new entry preferences

### LINKED ISSUE #14416: Enable resetting of NewEntryPreferences
See #14400 for the steps to do.

### PR DESCRIPTION
**Pull request by rahulkarru**
Closes #14416 
I have extracted the `NewEntryPreferences` logic from the main `JabRefPreferences` class into its own dedicated class. This reduces the size of the main preferences class and groups related settings together.

Specific implementation details:
- Created `NewEntryPreferences` with a private constructor for hardcoded defaults.
- Updated `JabRefPreferences` to read/write from this new object.
- **Imports & Types:** In the new class constructor, I switched to using `StandardEntryType` objects directly (instead of parsing Strings) to ensure better type safety for the default values. This required adding the necessary imports for `EntryType` and `NewEntryDialogTab`.

### Steps to test

1. Run JabRef.
2. Go to **Options > Preferences**.
3. Check the **Entry** or **New Entry** settings (e.g., change "Generate key on import" or "Default entry type").
4. Save and Close JabRef.
5. Reopen JabRef and verify that the settings were remembered.
6. Try resetting the preferences to default to ensure the hardcoded defaults work correctly.

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (not applicable, pure refactoring)
- [/] I added screenshots in the PR description (UI did not change)
- [/] I described the change in `CHANGELOG.md` (Internal refactoring, not visible to user)
- [/] I checked the [user documentation](https://docs.jabref.org/) (No behavior change)

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/newentry/NewEntryPreferences.java [hunk 1]
```diff
@@ -19,6 +22,26 @@ public class NewEntryPreferences {
...
+
+                true,
+
+                StandardEntryType.Article,
+
+                true,
+
+                DoiFetcher.NAME,
+
+                PlainCitationParserChoice.RULE_BASED_GENERAL.getLocalizedName()
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/newentry/NewEntryPreferences.java]: Fix empty lines - and add comments - as outlined in the issue description

**Review by koppor — CHANGES_REQUESTED** [review]
Why is so much code moved? Is this AI-generated?

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 2]
```diff
@@ -686,6 +700,30 @@ private WorkspacePreferences getWorkspacePreferencesFromBackingStore(WorkspacePr
                 getStringList(SELECTED_SLR_CATALOGS));
     }
 
+    private NewEntryPreferences getNewEntryPreferencesFromLowLevelApi(NewEntryPreferences defaults) {
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Rename ti XXXFromBackingStore

Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Please move below getNewEntryPreferences

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 3]
```diff
@@ -393,6 +381,30 @@ public static JabRefGuiPreferences getInstance() {
...
+                                .map(column -> column.sortTypeProperty().getValue().toString())
+                                .toList();
+    }
+
+    private static List<String> getColumnSortOrderAsStringList(ColumnPreferences columnPreferences) {
+        return columnPreferences.getColumnSortOrder().stream()
+                                .map(MainTableColumnModel::getName)
+                                .collect(Collectors.toList());
+    }
+
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Please move back to original position in code. Reason: Keep together what belongs together in code. Makes understanding easier.

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 4]
```diff
@@ -994,10 +1036,6 @@ private NameDisplayPreferences.DisplayStyle getNameDisplayStyle() {
         return displayStyle;
     }
 
-    // endregion
-
-    // region: Main table, main table column, and search dialog column preferences
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java:996]: Please keep region comments

**Comment by calixtus** [comment]
You forgot to add to clear and import methods

**Comment by rahulkarru** [comment]
> rgot to add to clear and import methods

I guess I had added right could you specify that?

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 5]
```diff
@@ -1212,6 +1194,30 @@ public NewEntryPreferences getNewEntryPreferences() {
...
+        return new NewEntryPreferences(
+                approach,
+                getBoolean("createEntryExpandRecommended", defaults.getTypesRecommendedExpanded()),
+                getBoolean("createEntryExpandOther", defaults.getTypesOtherExpanded()),
+                getBoolean("createEntryExpandCustom", defaults.getTypesCustomExpanded()),
+                immediateType,
+                getBoolean("createEntryIdLookupGuessing", defaults.getIdLookupGuessing()),
+                get("createEntryIdFetcherName", defaults.getLatestIdFetcher()),
+                get("createEntryInterpretParserName", defaults.getLatestInterpretParser())
+        );
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java:1203]: Please use the constants

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 6]
```diff
@@ -1212,6 +1194,30 @@ public NewEntryPreferences getNewEntryPreferences() {
...
     }
 
+    private NewEntryPreferences getNewEntryPreferencesFromBackingStore(NewEntryPreferences defaults) {
+        int approachIndex = getInt("createEntryApproach", defaults.getLatestApproach().ordinal());
+        NewEntryDialogTab approach;
+        if (approachIndex >= 0 && approachIndex < NewEntryDialogTab.values().length) {
+            approach = NewEntryDialogTab.values()[approachIndex];
+        } else {
+            approach = defaults.getLatestApproach();
+        }
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Why not the original logic? (which is btw now dead code in the getNewEntryPreferences() method)

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 7]
```diff
@@ -1212,6 +1194,30 @@ public NewEntryPreferences getNewEntryPreferences() {
...
+
+        String typeName = get("createEntryImmediateType", defaults.getLatestImmediateType().getDisplayName());
+        EntryType immediateType = EntryTypeFactory.parse(typeName);
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: In the original logic, this was testing only for StandardTypes. Please provide at least some reasoning why this should also be tested for other types.

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 8]
```diff
@@ -1190,15 +1180,7 @@ public NewEntryPreferences getNewEntryPreferences() {
             }
         }
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Now dead code.

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 9]
```diff
@@ -1212,6 +1194,30 @@ public NewEntryPreferences getNewEntryPreferences() {
...
+    private NewEntryPreferences getNewEntryPreferencesFromBackingStore(NewEntryPreferences defaults) {
+        int approachIndex = getInt("createEntryApproach", defaults.getLatestApproach().ordinal());
+        NewEntryDialogTab approach;
+        if (approachIndex >= 0 && approachIndex < NewEntryDialogTab.values().length) {
+            approach = NewEntryDialogTab.values()[approachIndex];
+        } else {
+            approach = defaults.getLatestApproach();
+        }
+
+        String typeName = get("createEntryImmediateType", defaults.getLatestImmediateType().getDisplayName());
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Please use the constants

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 10]
```diff
@@ -1212,6 +1194,30 @@ public NewEntryPreferences getNewEntryPreferences() {
         return newEntryPreferences;
     }
 
+    private NewEntryPreferences getNewEntryPreferencesFromBackingStore(NewEntryPreferences defaults) {
+        int approachIndex = getInt("createEntryApproach", defaults.getLatestApproach().ordinal());
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Please use the constants

**Comment by calixtus** [comment]
> > rgot to add to clear and import methods
> 
> I guess I had added right could you specify that?

i overlooked that change. my fault.

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 11]
```diff
@@ -363,6 +363,10 @@ private JabRefGuiPreferences() {
         defaults.put(ASK_FOR_INCLUDING_CROSS_REFERENCES, Boolean.TRUE);
         defaults.put(INCLUDE_CROSS_REFERENCES, Boolean.FALSE);
 
+        // region donation defaults
+        defaults.put(DONATION_NEVER_SHOW, Boolean.FALSE);
+        defaults.put(DONATION_LAST_SHOWN_EPOCH_DAY, -1);
+        // endregion
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Something is broken here -- this PR does not touch donations.

**Review by koppor — CHANGES_REQUESTED** [review]
There is no removal of `defaults.put` things  - and some strange donation changes are in... Maybe, wrong PR conflict resolution

image

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java (hunk 11 above)
Comment (koppor) [reply jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: Donations were handled at https://github.com/JabRef/jabref/pull/14439

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 12]
```diff
@@ -1173,6 +1162,22 @@ public NewEntryPreferences getNewEntryPreferences() {
...
+        EasyBind.listen(newEntryPreferences.idLookupGuessingProperty(), (_, _, newValue) -> putBoolean(CREATE_ENTRY_ID_LOOKUP_GUESSING, newValue));
+        EasyBind.listen(newEntryPreferences.latestIdFetcherProperty(), (_, _, newValue) -> put(CREATE_ENTRY_ID_FETCHER_NAME, newValue));
+        EasyBind.listen(newEntryPreferences.latestInterpretParserProperty(), (_, _, newValue) -> put(CREATE_ENTRY_INTERPRET_PARSER_NAME, newValue));
+
+        return newEntryPreferences;
+    }
+
+    private NewEntryPreferences getNewEntryPreferencesFromBackingStore(NewEntryPreferences defaults) {
+        // moved the same snippet form public to private
         final int approachIndex = getInt(CREATE_ENTRY_APPROACH);
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: What about the default value?

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: What about the default value?

**Review by calixtus — CHANGES_REQUESTED** [review]

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 13]
```diff
@@ -1173,40 +1162,49 @@ public NewEntryPreferences getNewEntryPreferences() {
...
+        EasyBind.listen(newEntryPreferences.latestImmediateTypeProperty(), (_, _, newValue) -> put(CREATE_ENTRY_IMMEDIATE_TYPE, newValue.getDisplayName()));
+        EasyBind.listen(newEntryPreferences.idLookupGuessingProperty(), (_, _, newValue) -> putBoolean(CREATE_ENTRY_ID_LOOKUP_GUESSING, newValue));
+        EasyBind.listen(newEntryPreferences.latestIdFetcherProperty(), (_, _, newValue) -> put(CREATE_ENTRY_ID_FETCHER_NAME, newValue));
+        EasyBind.listen(newEntryPreferences.latestInterpretParserProperty(), (_, _, newValue) -> put(CREATE_ENTRY_INTERPRET_PARSER_NAME, newValue));
+
+        return newEntryPreferences;
+    }
+
+    private NewEntryPreferences getNewEntryPreferencesFromBackingStore(NewEntryPreferences defaults) {
+        // moved the same snippet form public to private
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: ai comments?

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 14]
```diff
@@ -1173,40 +1162,49 @@ public NewEntryPreferences getNewEntryPreferences() {
...
+        final int approachIndex = getInt(CREATE_ENTRY_APPROACH, List.of(NewEntryDialogTab.values()).indexOf(defaults.getLatestApproach()));
         NewEntryDialogTab approach = NewEntryDialogTab.values().length > approachIndex
                                      ? NewEntryDialogTab.values()[approachIndex]
-                                     : NewEntryDialogTab.values()[0];
+                                     // if any values not match it assign this value
+                                     : defaults.getLatestApproach();
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: why change this?

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java [hunk 15]
```diff
@@ -1173,40 +1162,49 @@ public NewEntryPreferences getNewEntryPreferences() {
...
+
+        final String immediateTypeName = get(CREATE_ENTRY_IMMEDIATE_TYPE, defaults.getLatestImmediateType().getDisplayName());
+        // logic change to assign default values at the start
```
Comment (calixtus) [inline jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: another ai comment

**Review by calixtus — CHANGES_REQUESTED** [review]
Remove ai comments, reason for logic change

File: jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java (hunk 13 above)
Comment (rahulkarru) [reply jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: it' wasn't extremely an ai comment it was the comment written by myself to under stand for reviewer

Comment (calixtus) [reply jabgui/src/main/java/org/jabref/gui/preferences/JabRefGuiPreferences.java]: but why would you put a comment like this into the production code. nobody would understand it, who does not know how the code looked previously.
