### PR TITLE
fixed 4365 put html in clipboard

### LINKED ISSUE #4365: "copy preview" included unwanted HTML codes
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 
JabRef 5.0-dev--snapshot--2018-10-09--master--29838ee59
Linux 4.15.0-36-generic amd64 
Java 1.8.0_181

Steps to reproduce:

1. select an entry
2. display preview (alt+2)
3. copy preview (ctrl+shft+C)
4. paste preview

The result is tagged with HTML tags.  In most situations, like pasting to a word-processor or editor, I don't want these.  
Also, it's not possible to just select the previewed entry and copy it using the OS cut-n-paste system.

Please stop the "copy preview" command that putting HTML into the output.  Just plain text into the paste buffer.  
Another command which behaves as the present "copy preview" may be retained if there's user-demand.

Thanks!

### PR DESCRIPTION
**Pull request by Ali96kz**
Fix #4365 .
I get all tag value and put it in a string.

### CODE REVIEW

File: src/main/java/org/jabref/gui/PreviewPanel.java [hunk 1]
```diff
@@ -351,7 +354,14 @@ public void close() {
     }
 
     private void copyPreviewToClipBoard() {
-        String previewContent = (String) previewView.getEngine().executeScript("document.documentElement.outerHTML");
-        clipBoardManager.setContent(previewContent);
-    }
+        StringBuilder previewContent = new StringBuilder();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/PreviewPanel.java]: So the [java documentation](https://docs.oracle.com/javafx/2/api/javafx/scene/input/Clipboard.html) tells us
> Because multiple representations of the same data may exist on the clipboard, and because different applications have different capabilities for handling different content types, it is important to place as many data representations on the clipboard as is practical to facilitate external applications.

Thus, I would propose to add the html as well as the cleaned text to the clipboard:
````java
     ClipboardContent content = new ClipboardContent();
     content.putString(previewContent.toString());
     content.putHtml(the html content as it was before);
     clipBoardManager.setContent(content);
````
