### PR TITLE
Always sanitize braces on save and remove InvalidFieldValueException

### LINKED ISSUE #8730: Saving bug after import - braces don't match
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

_No response_

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Jabref Version: latest (main) dev build (today) but this bug exists in previous versions as well.

Saving throws an exception after importing PDF Files.
Probably has to do with OCR reading some special characters like { } \n etc.
Trying to save them then leads to a Situation where Jabref can't decide where the entry ends or something like that

To reproduce:
1. Import some PDF
2. click on save
3. get an exception

Exception in the appendix

### Appendix

...
<details>

```
org.jabref.logic.exporter.SaveException: Problems saving: java.io.IOException: Error in field 'AUTHOR of entry SINGLEFINandBUFFETINGALLEVIATION0656': Braces don't match. Field value: FOR SINGLE{FIN and BUFFETING ALLEVIATION
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveAction.execute(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.7.4/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.7.4/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$2(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.Scene$KeyHandler.process(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.Scene.processKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.View.notifyKey(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error in field 'AUTHOR of entry SINGLEFINandBUFFETINGALLEVIATION0656': Braces don't match. Field value: FOR SINGLE{FIN and BUFFETING ALLEVIATION
	at org.jabref@5.7.4/org.jabref.logic.bibtex.BibEntryWriter.writeField(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.BibEntryWriter.writeRequiredFieldsFirstRemainingFieldsSecond(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.BibEntryWriter.write(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.exporter.BibtexDatabaseWriter.writeEntry(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(Unknown Source)
	... 42 more
Caused by: org.jabref.logic.bibtex.InvalidFieldValueException: Braces don't match. Field value: FOR SINGLE{FIN and BUFFETING ALLEVIATION
	at org.jabref@5.7.4/org.jabref.logic.bibtex.FieldWriter.checkBraces(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.FieldWriter.formatAndResolveStrings(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.FieldWriter.write(Unknown Source)
	... 48 more

```

</details>

### PR DESCRIPTION
**Pull request by calixtus**
### Related issues and pull requests

Fixes #8730
Refs #9833

### PR Description

See qodo

Bonus: Replaced proper StringUtil repeat method with new JDK repeat method

### Steps to test

- Insert unbalanced brace in entry field

grafik

- Run integrity check

grafik

- Save and read with text editor

grafik

- Bonus: Notice little warning sign is also shown. JabRef automatically adapts. How nice.

grafik

### Checklist

   

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [x] I added JUnit tests for changes (if applicable)
- [x] I added screenshots in the PR description (if change is visible to the user)
- [.] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [.] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [.] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

**Comment by koppor** [comment]
JBang works locally on branch `braces`. Thus, just ignore the jbang errors.

"Issue" https://github.com/gradlex-org/extra-java-module-info/issues/237

Longer story: The modified classes are using `@ADR`, which is loaded for compile time only, not for runtime (in our gradle build configuration - https://github.com/JabRef/jabref/pull/15194). Since it is a dependency required by jablib  - and not by the JBang scripts themselves-

**I updated the scripts in this PR** at f7b15d3bce

File: jablib-examples/jbang/doi_to_bibtex.java [hunk 1]
```diff
@@ -1,4 +1,4 @@
-///usr/bin/env jbang "$0" "$@" ; exit $?
+/// usr/bin/env jbang "$0" "$@" ; exit $?
```
Comment (Siedlerchr) [inline jablib-examples/jbang/doi_to_bibtex.java]: this looks wrong

File: jablib-examples/jbang/ieee_pdf_references_to_bibtex.java [hunk 2]
```diff
@@ -1,4 +1,4 @@
-///usr/bin/env jbang "$0" "$@" ; exit $?
+/// usr/bin/env jbang "$0" "$@" ; exit $?
```
Comment (Siedlerchr) [inline jablib-examples/jbang/ieee_pdf_references_to_bibtex.java]: I don't think this is right

**Comment by Siedlerchr** [comment]
Tested with
```
@Article{1,
  author  = {1},
  journal = {1},
  title   = {1},
  year    = {1},
  pages   = {
  volume  = {1},
}

``` 
in source code editor, when pressing cmd + s to save I get two poups after each other

```
Error occurred when parsing entry: 'Error in line 9: EOF in mid-string'. 

JabRef skipped the entry
```

**Comment by calixtus** [comment]
The latter is a separate issue with the source code editor, who is responsible for parsing its contents.
This pr is only concerned with the inner string entered in the field editors.
Fixing the latter issue would escalate this pr way beyond scope.

File: jablib-examples/jbang/doi_to_bibtex.java (hunk 1 above)
Comment (calixtus) [reply jablib-examples/jbang/doi_to_bibtex.java]: Strange, this must have happened by auto formatter when saving the fix to jbang. Thanks

**Comment by calixtus** [comment]
Sanitizing source editor source is actually covered by https://github.com/JabRef/jabref/pull/15521 imho

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java [hunk 3]
```diff
@@ -53,31 +52,79 @@ private static void checkBraces(String text) throws InvalidFieldValueException {
...
+                        openBraces.pop();
+                    }
+                }
+            }
+        }
+
+        while (!openBraces.isEmpty()) {
+            FieldWriter.BracePosition lastOpenBrace = openBraces.pop();
+            errors.add(Localization.lang("Unbalanced '{' at line %0, column %1 (index %2): in '%3'.",
+                    lastOpenBrace.index(),
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java]:
```suggestion
                    lastOpenBrace.line() + 1,
```

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java [hunk 4]
```diff
@@ -53,31 +52,79 @@ private static void checkBraces(String text) throws InvalidFieldValueException {
...
+    /// @param text the text to sanitize
+    /// @return sanitized text
+    public static String sanitizeUnbalancedBraces(String text) {
+        int length = text.length();
+        Deque<Integer> lastOpenBrace = new ArrayDeque<>(length);
+        boolean[] toEscape = new boolean[length];
+
+        // Find all braces
+        for (int i = 0; i < length; i++) {
+            char currentChat = text.charAt(i);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java]: currentChar

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java [hunk 5]
```diff
@@ -53,31 +52,79 @@ private static void checkBraces(String text) throws InvalidFieldValueException {
...
+        return errors;
+    }
+
+    /// Escapes the last unbalanced curly brace in the given text.
+    ///
+    /// @param text the text to sanitize
+    /// @return sanitized text
+    public static String sanitizeUnbalancedBraces(String text) {
+        int length = text.length();
+        Deque<Integer> lastOpenBrace = new ArrayDeque<>(length);
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java:88]: Nit - I think the default constructor is fine here, since the deque will grow as needed?

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java [hunk 6]
```diff
@@ -53,31 +52,79 @@ private static void checkBraces(String text) throws InvalidFieldValueException {
...
+        boolean[] toEscape = new boolean[length];
+
+        // Find all braces
```
Comment (subhramit) [inline jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java]: Maybe more precise:
```suggestion
        // Match braces, mark orphan '}'
```

File: jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java (hunk 5 above)
Comment (calixtus) [reply jablib/src/main/java/org/jabref/logic/bibtex/FieldWriter.java:88]: Basically yes, that's true, but field writer is used for every field in an entry on saving. Thus it's speed matters. As I know there won't ever be more elements in this deque, I remove the calculation for growing the deque dynamically.

**Comment by calixtus** [comment]
Thx for review

**Review by subhramit — APPROVED** [review]
Lgtm!
