### PR TITLE
Fixes problems with managing external file types (issue 5846)

### LINKED ISSUE #5846: Changing settings in "Options" > "Manage external file types" has no effect
I'm using JabRef 5 master build (JabRef-5.0-portable_linux.tar.gz, JabRef 5.0-beta.342--2020-01-15--58709e7, Linux 4.4.0-171-generic amd64 Java 13.0.2) on Ubuntu 16.04.

1. Click "Options"
2. Click "Manage external file types"
3. Click pencil edit icon
4. change some values
5. Click "OK"
6. Result: The changed settings are lost.

Whenever changing some settings in step 4 and clicking "OK", the settings will not be stored: The shown table is not being updated and when clicking the same pencil edit icon once again, the original, unchanged settings appear once again.

In my case, I especially wanted to assign a specific pdf reader/editor solely for JabRef (which should be different to the default pdf reader on my system), but setting a different one could not be accomplished.

At this point I would like to reference an already mentioned issue, which is related to setting a different pdf reader/editor: "Open PDF options" #5529 Nevertheless, this referenced issue is about a different dialog in JabRef.

In my opinion, it should really be possible to assign user-specific programs to given file types and not relying on the system's settings. This allows important program-specific personalization.

### PR DESCRIPTION
**Pull request by systemoperator**
Fixes #5846

**Changed:**
- edit/customize external file types: radio button for "default program"/"custom program" fixed: They now get updated and set properly (binding added and setting values).
- "Edit file type" dialog: correct value gets loaded now for the input field "Name"
- when updating an external file type entry: no differentiation will be made anymore whether the program runs on Windows or somewhere else
- Everything concerning the type `CustomExternalFileType` is now working properly as well.
  - Settings will also be saved to JabRef's `config.xml` file.
- Editing an entry with type `ExternalFileType` works now as well. (changes are not lost anymore)
  - Settings will also be saved to JabRef's `config.xml` file.

**Remarks:**
- Table in "Manage external file types" dialog is "lazily" updated when a table entry has been updated. (But this seems to be a Linux issue anyway, since other tables behave the same way.)

**Tasks:**
- [x] Change in CHANGELOG.md described
- [x] Manually tested changed features in running JabRef (always required)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date?

### CODE REVIEW

**Comment by systemoperator** [comment]
The last commit is a quick fix and could be improved, since the old table entry gets replaced by a new one, even if the user would then cancel the process of editing the entry. Even if the user cancelled the edit process, everything is still fine and valid. Editing external file types is now fully functional. No problems are known. Suggestions are welcome.

The line `fileTypesTable.refresh();` has no effect, since the "lazy" update of the table does not change by using it. But this could be a Linux issue anyway, since other tables behave the same way. Thus, I could remove the line.

**Comment by calixtus** [comment]
Thanks for the fix @systemoperator.
I took a quick peek into the code, there seems to be something wrong with the branch head. Git wants to merge a lot of additions to the csl-styles. I'm not really into git, but maybe a rebase on the current upstream/master can clear that. Just a wild guess.

**Comment by systemoperator** [comment]
Yes, I have noticed this as well. github actions "did" that. It's the first time, that I have seen that, but I am new here anyway, so I don't know whether this occurs sometimes and it is fine or not.

**Comment by calixtus** [comment]
Hey @systemoperator, got a hint by @koppor. This might help solving the branch issue with your PR:

https://lostechies.com/joshuaflanagan/2010/09/03/use-gitk-to-understand-git/

**Comment by koppor** [comment]
You can create one single commit containing your changes with following commands:

1. `git checkout fix-for-issue-5846`
1. `git fetch --all`
1. `git merge upstream/master` (and commit the merge!)
1. `git reset upstream/master`
1. Commit as usual

Assumption: `git remote add upstream https://github.com/JabRef/jabref.git` was done sometime ago. You can check with `git remote -v`.

File: src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java [hunk 1]
```diff
@@ -62,6 +62,7 @@ public void initialize() {
         icon.setGraphic(viewModel.getIcon());
 
         defaultApplication.selectedProperty().bindBidirectional(viewModel.defaultApplicationSelectedProperty());
+        customApplication.selectedProperty().bindBidirectional(viewModel.customApplicationSelectedProperty());
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java]: Custom application selected is always the opposite of default application, right?
I guess the problem is that the toggle group is defined locally
https://github.com/JabRef/jabref/blob/d0393b59b96c09bdf53cfc053845764764815a44/src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.fxml#L38
and not globally as in
https://github.com/JabRef/jabref/blob/d0393b59b96c09bdf53cfc053845764764815a44/src/main/java/org/jabref/gui/preferences/EntryEditorTab.fxml#L14-L17

If this does not work, then you can also try
```
customApplication.selectedProperty().bind(viewModel.defaultApplicationSelectedProperty().not());
```

File: src/main/java/org/jabref/gui/externalfiletype/CustomizeExternalFileTypesDialog.java [hunk 2]
```diff
@@ -40,6 +40,7 @@ public CustomizeExternalFileTypesDialog() {
         this.setResultConverter(button -> {
             if (button == ButtonType.OK) {
                 viewModel.storeSettings();
+                fileTypesTable.refresh();
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/externalfiletype/CustomizeExternalFileTypesDialog.java]: If it does not work, then you can delete this indeed.

File: src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java (hunk 1 above)
Comment (systemoperator) [reply src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java]: Yes, the radio button group should toggle and only one radio button should be active. First I tried `customApplication.selectedProperty().bindBidirectional(defaultApplicationSelectedProperty().not());` which is of course not possible. On the other hand, I needed a bidirectional binding, because the radio button can be changed from both directions (program or user), thus I implemented it this way. (Which works.)

Now I have tried your suggestion with `customApplication.selectedProperty().bind(viewModel.defaultApplicationSelectedProperty().not());` (so a onedirectional binding) out of curiosity, but, as expected, issues resulted. In this case, when I try to switch to the "custom" radio button, then an exception is thrown, stating `java.lang.RuntimeException: RadioButton.selected : A bound value cannot be set.`, since now the value can only be set by the program but not by the user.

In the end, I looked how it was done in

```
 <fx:define> 
     <ToggleGroup fx:id="nameFormat"/> 
     <ToggleGroup fx:id="firstNames"/> 
 </fx:define> 
```

Here, also a bidirectional mapping for all radio buttons gets declared:

        autoCompleteFirstLast.selectedProperty().bindBidirectional(viewModel.autoCompleteFirstLastProperty());
        autoCompleteLastFirst.selectedProperty().bindBidirectional(viewModel.autoCompleteLastFirstProperty());
        autoCompleteBoth.selectedProperty().bindBidirectional(viewModel.autoCompleteBothProperty());

But only the `true` value is getting set, which is of course sufficient:

        if (autoCompletePreferences.getOnlyCompleteFirstLast()) {
            autoCompleteFirstLastProperty.setValue(true);
        } else if (autoCompletePreferences.getOnlyCompleteLastFirst()) {
            autoCompleteLastFirstProperty.setValue(true);
        } else {
            autoCompleteBothProperty.setValue(true);
        }

And so did I now.

File: src/main/java/org/jabref/gui/externalfiletype/CustomizeExternalFileTypesDialog.java (hunk 2 above)
Comment (systemoperator) [reply src/main/java/org/jabref/gui/externalfiletype/CustomizeExternalFileTypesDialog.java]: done

File: src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java]: Radio button in a toggle group dont support bidirectional binding.
I stumbled across this problem already.
You always need to work around that. 
Just look how it's done in the settings dialog

Comment (systemoperator) [reply src/main/java/org/jabref/gui/externalfiletype/EditExternalFileTypeEntryDialog.java]: I made it as described above and it is coded this way in the settings dialogue as well (see above) and it works. Is this ok now?

**Comment by systemoperator** [comment]
For testing purposes, I made some changes in `EditExternalFileTypeEntryDialog.fxml` (in the `src/main.../gui/...` directory) but when I built and ran the project with the changes, then those changes did not show up in the corresponding dialogue.

My questions are:
- What needs to be done, so that changes in those files will update the corresponding GUI element?
- Do you use some graphical tool to change these files?

**Comment by calixtus** [comment]
Are the multiple changes to authors.md really intended?

**Comment by systemoperator** [comment]
Yes, I simply ran the script `scripts/generate-authors.sh,` to pull in new authors.

**Comment by calixtus** [comment]
Theres something odd: Igor Steinmacher appears in full name as well in concatenaded form (also Oscar Gustafsson )

**Comment by Siedlerchr** [comment]
You don't need to run the script manually. We will do this from time to time or at least in preparation for a release

**Comment by systemoperator** [comment]
> Theres something odd: Igor Steinmacher appears in full name as well in concatenaded form (also Oscar Gustafsson )

Maybe he commited with his username first and later on with his real name. Nevertheless, this will always reappear by running the script. But I could now remove the entry with his username?

I did it, because it is mentioned in the docs, that one can do it. And I wanted to try it. :)

**Comment by tobiasdiez** [comment]
@koppor what is our policy concerning this? (which then should be clarified in the docs)

As these changes are not directly related to the main theme of this PR, can you please remove these changes for now so that we can merge? Thanks

**Comment by koppor** [comment]
We maintain the `.mailmap` to always map to the full name. I don't get, why is Oscar and Igor appear with their short names at your system. Have to try it here locally

Typically, we update the AUTHORS file now and then. Especially before a release. (See https://github.com/JabRef/jabref/wiki/Releasing-a-new-Version)

I also thought to setup a GitHub action to comment at the PR with the new entry in the AUTHORS file. Should be doable...

**Comment by calixtus** [comment]
Maybe a quick fix to get this PR mergable: leave your name in authors.md and remove the other additions, they will be put in before release.

**Comment by systemoperator** [comment]
done

**Comment by tobiasdiez** [comment]
Thanks again for contribution, and sorry for the confusion caused. I hope the additional effort on your side wasn't too great. Your next PR should go more smoothly 😄
