### PR TITLE
Fix for issue: right click menu 6601

### LINKED ISSUE #6601: Add right click menu for main table header
It would be nice if right-clicking on the main table header (where the column names are), provided a menu which either allowed to edit the viewed columns/fields directly or provided a link to the preferences. 

Maybe a list of the currently and most commonly used fields would show up to be activated/deactivated in the right click menu and for more detailed adjustments a reference to the settings would be displayed.

### PR DESCRIPTION
**Pull request by ethantr**
Fixes #6601 **[WIP]**

**The user is able to right-click on the header of a maintable, to toggle the each column(field) visibility. This is also updated in the Entry Table in preferences. This is intended to improve the efficiency of using the program/UI as it will give users one less step from toggling the visibility of fields, instead of clicking through the preferences menus.**

Inspired from #7729, #8762

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

**Demonstration (Screenshots):**

1. When the user right clicks on the Main Table header, a context menu appears with the most commonly used fields based on the default preferences), and the other currently used fields. A tick next to the item shows whether the column is visible in the table. The seperator in the table distinguishes between commonly and currently used fields. 
screenshotA

2. When an item is clicked, its visibility gets toggled. This process either removes the column from the MainTable, or adds it back into view, which is reflected in the preferences. In this scenario, I have clicked the Author/Editor and the Chapter fields, both are now removed from the MainTable, and their ticks show they are not visible.
screenShotB

3. After clicking on "Author/Editor" it is placed back into the table, and its tick is present, showing that is indeed back in the table with its original contents.
screenShotC

**TO-DO:**

- Currently considering adding the Show Preferences button, but thought I would push this draft pull request to get some feedback to make sure this is going in the right direction.
- Aware that checking the column is present in the current maintable is inefficient, beleive a boolean property within the MainTableColumn could be added to make it constant, and only have to check once.

### CODE REVIEW

**Comment by ThiloteE** [comment]
I have had a look at this pr and tried it with `./gradlew run` on my Linux Mint machine.

Contrary to screenshots, explanation and expectations, i was **not** able to simply rightclick to trigger the menu. I needed to **hold** right click. During this hold neither using left- nor right-click would allow me to remove from or add a column to the main table.

This pr needs changes before it can be merged.

**Comment by ethantr** [comment]
@ThiloteE I've made some changes and tested it on a Linux machine, should work as intended now.

**Comment by ThiloteE** [comment]
Awesome! I can confirm it works now! Thank you!

File: src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+
+    /**
+     * Constructs the items for the list and places them in the menu.
+     */
+    private void constructItems(MainTable mainTable) {
+        // Reset the right-click menu
+        this.getItems().clear();
+
+        // Populate the menu with the commonly used fields
+        for (TableColumn<BibEntryTableViewModel, ?> tableColumn:commonColumns()) {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java:54]: If the user reorders the columns differently than what is in "commonColumns", then it might get confusing since the column order then differs from the order in the context menu.

For this reason, I would swap the logic here: first display all currently shown columns in the display order, and then after the separator list common column that are not yet displayed.

This also plays well with the "addColumn" function, which adds the columns at the end.

File: src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+    }
+
+    /**
+     * Adds the column into the MainTable for display.
+     */
+    @SuppressWarnings("rawtypes")
+    private void addColumn(MainTableColumn tableColumn) {
+        // Do not add duplicate if table column is already within the table.
+        if (!isInMainTable(tableColumn)) {
+            mainTable.getColumns().add(tableColumn);
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java:107]: What happens if the user first removes a column, and then immediately readds it (e.g. he realizes removing it was a mistake). In this case, the column order should be the same as it was before. If I read the code correctly, then currently the column would be appended at the end instead of at its original position.

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
This is a really nice addition, thanks a lot for your work!

I've only a few smallish suggestions about the order of the menu entries. Otherwise it looks good to me.

File: src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java (hunk 2 above)
Comment (ethantr) [reply src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java:114]: I've made some more changes here. When the user goes to click to remove the column, it obtains the current index in the MainTable and stores that number inside the Menu Item. If he wants to immediately place it back, it will be placed back in that exact position using that index.
If the items next to it are removed, it will still be placed in the position of the given index - not sure if that will be confusing to the end user or not, happy to hear your thoughts.

File: src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java (hunk 1 above)
Comment (ethantr) [reply src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java]: Switched this logic around :)

File: src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java [hunk 3]
```diff
@@ -0,0 +1,228 @@
...
+        commonColumns.add(new MainTableColumnModel(MainTableColumnModel.Type.NORMALFIELD, yearQualifier));
+        commonColumns.add(new MainTableColumnModel(MainTableColumnModel.Type.NORMALFIELD, journalBookQualifier));
+        commonColumns.add(new MainTableColumnModel(MainTableColumnModel.Type.SPECIALFIELD, rankQualifier));
+        commonColumns.add(new MainTableColumnModel(MainTableColumnModel.Type.SPECIALFIELD, readStatusQualifier));
+        commonColumns.add(new MainTableColumnModel(MainTableColumnModel.Type.SPECIALFIELD, priorityQualifier));
+
+        // Create the Table Columns from the models using factory methods.
+        List<TableColumn<BibEntryTableViewModel, ?>> commonTableColumns = new ArrayList<>();
+        for (MainTableColumnModel columnModel: commonColumns
+             ) {
```
Comment (calixtus) [inline src/main/java/org/jabref/gui/maintable/MainTableHeaderContextMenu.java:180]:
```suggestion
        for (MainTableColumnModel columnModel: commonColumns) {
```

**Comment by koppor** [comment]
DevCall: We merge as is.

However, eventually, there should be a follow-up PR:

We take Windows Explorer as reference (see https://github.com/JabRef/jabref/issues/6601#issuecomment-724932377)

We tried it:

grafik

Only columns enabled in the preferences are shown:

grafik

How to enable addition of new columns (as shown at the screenshot at https://github.com/JabRef/jabref/issues/6601#issuecomment-724932377)?

We think "More..." ("Mehr..." in German) is missing:

grafik

After a click, a new popup opens 

grafik

Would be nice if that was added here, too. Would that be possible?

This list should be filled with all fields known to JabRef. In case a user wants to add more fields, they must go to the preferences and add the custom field there.
