### PR TITLE
Mark OOSTyle as invalid if no defaultStyle

### LINKED ISSUE #5452: Error in importing jstyles
JabRef 5.0.0-dev--2019-10-15----2a5507fd3
Linux 5.2.0-0.bpo.3-amd64 amd64 (Debian 10 Buster)
Java 12.0.2

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. add jstyle file for OpenOffice/LibreOffice from GUI
2. click OK
3. :sob: 

<details>
  <summary>Log File</summary>
  
  ```
java.lang.NullPointerException
	at org.jabref/org.jabref.gui.openoffice.StyleSelectDialogView.lambda$new$0(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Dialog.setResultAndClose(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.DialogPane.lambda$createButton$3(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$4(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
  ```
</details>

Here is one of my jstyles. All of my styles give me the above error, but I tested other styles, without success (I used already them in previous JabRef versions).
```
# This file is licensed under the terms of the GPL version 2 (or later).

NAME
Literatura - Eng

JOURNALS
Literatura

PROPERTIES
Title="References"
IsSortByPosition="false"
IsNumberEntries="false"
ReferenceParagraphFormat="List 1"
ReferenceHeaderParagraphFormat="Heading 1"
# Configurare Heading1: Italics not capitalized, left justified

CITATION
AuthorField="author/editor"
YearField="year"
MaxAuthors="3"
MaxAuthorsFirst="3"
AuthorSeparator=", "
AuthorLastSeparator=" & "
AuthorLastSeparatorInText=" & "
EtAlString=" and oth."
ItalicEtAl="false"
YearSeparator=" "
InTextYearSeparator=" "
BracketBefore=
BracketAfter=
BracketBeforeInList="["
BracketAfterInList="]"
CitationSeparator="; "
UniquefierSeparator=", "
GroupedNumbersSeparator="-"
MinimumGroupingCount="3"
FormatCitations="false"
CitationCharacterFormat="Default"
MultiCiteChronological="false"
PageInfoSeparator=", "

LAYOUT
article=\format[AuthorLastFirst]{\author}. \year. \format[HTMLChars,FormatPagesForXML]{\title}. <i>\journal</i>\begin{volume} \volume\end{volume}\begin{number}(\number)\end{number}, \format[FormatPagesForHTML]{\pages}

book=\begin{author}\format[Authors(FullName,LastFirstFirstFirst,Amp)]{\author}. \end{author}\begin{editor}\format[AuthorLastFirstFirstFirst,AuthorAndsReplacer]{\editor}, \format[IfPlural(eds,ed)]{\editor}. \end{editor}\year. <i>\format[HTMLChars,FormatPagesForHTML]{\title}.</i>\begin{subtitle} \format[HTMLChars,FormatPagesForHTML]{\subtitle}.\end{subtitle}\begin{series&&number} \series \number.\end{series&&number}\begin{volume} \format[HTMLChars,FormatPagesForHTML]{\volume}.\end{volume}\begin{volumes} \volumes vol.\end{volumes}\begin{location} \format[HTMLChars,FormatPagesForHTML]{\location}: \end{location}\begin{place}\format[HTMLChars]{\place}: \end{place}\begin{edition}<sup>\edition</sup>\end{edition}\publisher

inbook=\format[Authors(FullName,LastFirstFirstFirst,Amp)]{\author}. \format[FormatPagesForHTML]{\year}: \format[HTMLChars,FormatPagesForHTML]{\title}. <i>\format[HTMLChars,FormatPagesForHTML]{\booktitle}. \begin{booksubtitle} \format[HTMLChars,FormatPagesForHTML]{\booksubtitle}. \end{booksubtitle}</i>\format[HTMLChars,Authors(FullName,FirstFirst,Amp)]{\editor}, \format[IfPlural(eds,ed)]{\editor}.\begin{location} \format[HTMLChars,FormatPagesForHTML]{\location}: \end{location}\begin{place}\format[HTMLChars]{\place}: \end{place}\begin{edition}<sup>\edition</sup>\end{edition}\publisher\begin{pages}, \format[FormatPagesForHTML]{\pages}\end{pages}

inproceedings=\format[Authors(FullName,LastFirstFirstFirst,Amp)]{\author}. \format[FormatPagesForHTML]{\year}: \format[HTMLChars,FormatPagesForHTML]{\title}. <i>\format[HTMLChars,FormatPagesForHTML]{\eventtitle}.</i> \begin{eventtitleaddon}\format[HTMLChars,FormatPagesForHTML]{\eventtitleaddon}. \end{eventtitleaddon}\format[HTMLChars,Authors(FullName,FirstFirst,Amp)]{\editor}, \format[IfPlural(eds,ed)]{\editor}.\begin{location} \format[HTMLChars,FormatPagesForHTML]{\location}: \end{location}\begin{place}\format[HTMLChars]{\place}: \end{place}\begin{edition}<sup>\edition</sup>\end{edition}\publisher\begin{pages}, \format[FormatPagesForHTML]{\pages}\end{pages}

incollection=\format[Authors(FullName,LastFirstFirstFirst,Amp)]{\author}. \format[FormatPagesForHTML]{\year}: \format[HTMLChars,FormatPagesForHTML]{\title}. <i>\format[HTMLChars,FormatPagesForHTML]{\booktitle}. \begin{booksubtitle} \format[HTMLChars,FormatPagesForHTML]{\booksubtitle}. \end{booksubtitle}</i>\format[HTMLChars,Authors(FullName,FirstFirst,Amp)]{\editor}, \format[IfPlural(eds,ed)]{\editor}.\begin{location} \format[HTMLChars,FormatPagesForHTML]{\location}: \end{location}\begin{place}\format[HTMLChars]{\place}: \end{place}\begin{edition}<sup>\edition</sup>\end{edition}\publisher\begin{pages}, \format[FormatPagesForHTML]{\pages}\end{pages}

#####
phdthesis=\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\author}
(<b>\year\uniq</b>). <i>\title</i>, \school.

default=\format[AuthorLastFirst]{\author}. \year. \format[HTMLChars,FormatPagesForXML]{\title}. <i>\journal</i>\begin{volume} \volume\end{volume}\begin{number}(\number)\end{number}, \format[FormatPagesForHTML]{\pages}
```

### PR DESCRIPTION
**Pull request by Siedlerchr**
In addtion, dsplay correct layout for article and book

Fixes  #5452 

TODO: Add documentation issue

----

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Manually tested changed features in running JabRef
- [ ] Screenshots added in PR description (for bigger UI changes)
- [ ] Ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)

### CODE REVIEW

File: src/main/java/org/jabref/logic/openoffice/OOBibStyle.java [hunk 1]
```diff
@@ -272,7 +273,7 @@ private void readFormatFile(Reader in) throws IOException {
             if (!line.isEmpty() && (line.charAt(line.length() - 1) == '\r')) {
                 line = line.substring(0, line.length() - 1);
             }
-            // Check for empty line or comment:
+            // Check for empty lin  e or comment:
```
Comment (koppor) [inline src/main/java/org/jabref/logic/openoffice/OOBibStyle.java]: Please revert this change

File: src/main/java/org/jabref/logic/openoffice/OOBibStyle.java [hunk 2]
```diff
@@ -122,6 +122,7 @@
     private File styleFile;
     private long styleFileModificationTime = Long.MIN_VALUE;
     private String localCopy;
+    private boolean setDefault;
```
Comment (koppor) [inline src/main/java/org/jabref/logic/openoffice/OOBibStyle.java]: Could you rename the variable to `setDefaultLayout` or smething?

Currently, the name is not that readable.

File: src/main/java/org/jabref/logic/openoffice/OOBibStyle.java [hunk 3]
```diff
@@ -143,7 +144,7 @@ public OOBibStyle(String resourcePath, LayoutFormatterPreferences prefs) throws
     }
 
     public Layout getDefaultBibLayout() {
-        return defaultBibLayout;
+        return defaultBibLayout ;
```
Comment (koppor) [inline src/main/java/org/jabref/logic/openoffice/OOBibStyle.java]: Please remove the added space

File: src/main/java/org/jabref/logic/openoffice/OOBibStyle.java [hunk 4]
```diff
@@ -350,7 +349,7 @@ private void handleStructureLine(String line) {
         int index = line.indexOf('=');
         if ((index > 0) && (index < (line.length() - 1))) {
             String formatString = line.substring(index + 1);
-            boolean setDefault = line.substring(0, index).equals(OOBibStyle.DEFAULT_MARK);
+             setDefault = line.substring(0, index).equals(OOBibStyle.DEFAULT_MARK);
```
Comment (koppor) [inline src/main/java/org/jabref/logic/openoffice/OOBibStyle.java]: Please fix the ident

File: src/main/java/org/jabref/logic/openoffice/OOBibStyle.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/logic/openoffice/OOBibStyle.java]: Yes yes yes, I knew it. In the pipeline

File: CHANGELOG.md [hunk 5]
```diff
@@ -43,6 +44,7 @@ We refer to [GitHub issues](https://github.com/JabRef/jabref/issues) by using `#
 - We fixed some display errors in the preferences dialog and replaced some of the controls [#5033](https://github.com/JabRef/jabref/pull/5033) [#5047](https://github.com/JabRef/jabref/pull/5047) [#5062](https://github.com/JabRef/jabref/pull/5062) [#5141](https://github.com/JabRef/jabref/pull/5141) [#5185](https://github.com/JabRef/jabref/pull/5185) [#5265](https://github.com/JabRef/jabref/pull/5265) [#5315](https://github.com/JabRef/jabref/pull/5315) [#5360](https://github.com/JabRef/jabref/pull/5360)
 - We fixed an exception which occurred when trying to import entries without an open library. [#5447](https://github.com/JabRef/jabref/issues/5447) 
 - After successful import of one or multiple bib entries the main table scrolls to the first imported entry [#5383](https://github.com/JabRef/jabref/issues/5383)
+- We fixed an exception which occurred when an invalid jstyle was loaded [#5452](https://github.com/JabRef/jabref/issues/5452)
```
Comment (tobiasdiez) [inline CHANGELOG.md]:
```suggestion
- We fixed an exception which occurred when an invalid jstyle was loaded. [#5452](https://github.com/JabRef/jabref/issues/5452)
```

File: src/main/java/org/jabref/logic/openoffice/OOBibStyle.java (hunk 1 above)
Comment (tobiasdiez) [inline src/main/java/org/jabref/logic/openoffice/OOBibStyle.java]:
```suggestion
            // Check for empty line or comment:
```
