### PR TITLE
Fix #8390 by allowing multiple group deletion for Remove groups > Kee…

### LINKED ISSUE #8390: Removing several groups deletes only one of them
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.5--2022-01-03--c94bb1b Linux 4.19.0-18-amd64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create several groups
2. Select them
3. Right click on the selection and choose `Remove groups > Also remove subgroups` in the drop-down menu

You are prompted to confirm the deletion of one group. After accepting, this group is deleted, but you are not prompted to delete the other groups.
So, while it seems that several can be removed at the same time, groups can be removed only one by one.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

### PR DESCRIPTION
**Pull request by LIM0000**
Indeed, this solves the issue for `Remove groups > Also remove subgroups`.
However, a similar issue remains for `Remove groups > Keep subgroups`.
Please, could you look at this closely-related issue?

## Proposed solution:
Fixes https://github.com/JabRef/jabref/issues/8390

- When removeGroupKeepSubgroups() is called, iterate through all selected groups instead of the group that triggers the event handler.
- Popup a confirmation dialog and confirm if user decides to delete:
  - single group
  - multiple groups (if multiple groups selection)
- All subgroups are assigned to their corresponding grandparents if there are any. Otherwise, they are assigned to `All entries`.

### Multiple groups deletion

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]

File: src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java [hunk 1]
```diff
@@ -260,20 +260,38 @@ public void removeSubgroups(GroupNodeViewModel group) {
...
             // TODO: Add undo
             // final UndoableAddOrRemoveGroup undo = new UndoableAddOrRemoveGroup(groupsRoot, node, UndoableAddOrRemoveGroup.REMOVE_NODE_KEEP_CHILDREN);
             // panel.getUndoManager().addEdit(undo);
-            GroupTreeNode groupNode = group.getGroupNode();
-            groupNode.getParent()
-                     .ifPresent(parent -> groupNode.moveAllChildrenTo(parent, parent.getIndexOfChild(groupNode).get()));
-            groupNode.removeFromParent();
 
-            dialogService.notify(Localization.lang("Removed group \"%0\".", group.getDisplayName()));
+            ArrayList<GroupNodeViewModel> selectedGroupNodes = new ArrayList<>(selectedGroups);
```
Comment (koppor) [inline src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java:281]:
```suggestion
            List<GroupNodeViewModel> selectedGroupNodes = new ArrayList<>(selectedGroups);
```

**Review by koppor — APPROVED** [review]
looks gut - just a nitpick

**Comment by Siedlerchr** [comment]
thanks for the quick follow up!
