### PR TITLE
Fix directory path validation checks

### LINKED ISSUE #13017: Directory check should respect relative paths
Setting:

1. `C:\TEMP\JabRef\test\demo` contains `demo.bib` and sub directory `lib`\
    Image
2. In library properties, the check says, the path `lib` does not exist\
    Image

The path exists.

One needs to `resolve` (from the `Path` object) of the path of the `bib` file to check.

See also `org.jabref.model.database.BibDatabaseContext#getFileDirectories`. The method cannot be directly used, because it call `getFileDirectoryPath`, which makes the path absolute.

(Follow-up to https://github.com/JabRef/jabref/pull/12867)

### PR DESCRIPTION
**Pull request by paudelritij**
Closes #13017  
Follow-up to #12867 

1.`validateDirectory()` method was not handling relative path correctly.
2. While assigning 'valid relative path' then pressing folder icon, `getBrowseDirectory()` method was not checking the 'valid provided directory path' properly.

Fix: paths now will be resolve against library working directory. 

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [/] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [/] Screenshots added in PR description (if change is visible to the user)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

File: jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java [hunk 1]
```diff
@@ -196,23 +195,24 @@ public StringProperty laTexFileDirectoryProperty() {
     }
 
     private Path getBrowseDirectory(String configuredDir) {
+        Path libPath = preferences.getFilePreferences().getWorkingDirectory();
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java:198]: Strange.

I think, this really should be `org.jabref.model.database.BibDatabaseContext#getDatabasePath`

Reason: If having 10 library files opened, the working directory is not the one of the current file.

**Review by koppor — CHANGES_REQUESTED** [review]

File: jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java [hunk 2]
```diff
@@ -199,21 +199,31 @@ private Path getBrowseDirectory(String configuredDir) {
...
     private ValidationMessage validateDirectory(String directoryPath, String messageKey) {
         try {
-            Path path = Path.of(directoryPath);
-            if (!Files.isDirectory(path)) {
+            Optional<Path> libPath = this.databaseContext.getDatabasePath();
+
+            if (libPath.isEmpty() || !Files.isDirectory(libPath.get()
+                                   .getParent()
+                                   .resolve(directoryPath)
+                                   .normalize())) {
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java:226]: Use the power of optionals wisely:

```suggestion
if (!libPath.map(p -> p.getParent().resolve(directoryPath).normalize())
           .map(Files::isDirectory)
           .orElse(false)) {
```

**Review by koppor — CHANGES_REQUESTED** [review]

File: jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java [hunk 3]
```diff
@@ -199,21 +199,31 @@ private Path getBrowseDirectory(String configuredDir) {
...
-        Optional<Path> foundPath = this.databaseContext.getFileDirectories(preferences.getFilePreferences()).stream()
-                                                       .filter(path -> path.toString().endsWith(configuredDir))
-                                                       .filter(Files::exists).findFirst();
 
-        if (foundPath.isEmpty()) {
+        Optional<Path> libPath = this.databaseContext.getDatabasePath();
+
+        if (libPath.isEmpty()) {
             dialogService.notify(Localization.lang("Path %0 could not be resolved. Using working dir.", configuredDir));
             return preferences.getFilePreferences().getWorkingDirectory();
```
[the remark this answers is not in the document]
Comment (paudelritij) [reply jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java:207]: currently method is called always e.g. when user types any(valid/invalid) (relative/absolute path) and then press folder icon `configureDir` is checked for it's existence

File: jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java [hunk 4]
```diff
@@ -199,21 +199,31 @@ private Path getBrowseDirectory(String configuredDir) {
...
         }
-        return foundPath.get();
+
+        Path path = libPath.get().getParent().resolve(configuredDir).normalize();
+
+        if (!Files.isDirectory(path)) {
```
[the remark this answers is not in the document]
Comment (paudelritij) [reply jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java:212]: In current scenario, `configureDir` can be invalid and may not exist; mentioned in PR description # 2

**Comment by paudelritij** [comment]
@koppor I found I had not added proper validation message for unsaved library while working on #11840. Shall I add it to current PR (msg like 'Save the library to perform this action') since few lines of code ? or need new PR if we want to disable the field with dir icon since lib not saved.

**Comment by koppor** [comment]
> @koppor I found I had not added proper validation message for unsaved library while working on #11840.

Oh, this is unfortunate.

I think, I commented. But I have no time to search.

If libPath is empty, use configDir. No need for an error message. Only making the configDir path relative to the bib path won't work.

Maybe, we need a UML state chart to visualize. I remember, I commented somehow about the global setting to store PDFs relative to the bib file, but I don't know if in the context of this.

> 
 Shall I add it to current PR (msg like 'Save the library to perform this action') since few lines of code ? or need new PR if we want to disable the field with dir icon since lib not saved.

Both is wrong IMHO. Absolute paths always work.

File: jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java [hunk 5]
```diff
@@ -196,24 +196,40 @@ public StringProperty laTexFileDirectoryProperty() {
     }
 
     private Path getBrowseDirectory(String configuredDir) {
+        Optional<Path> libPath = this.databaseContext.getDatabasePath();
+        Path workingDir = preferences.getFilePreferences().getWorkingDirectory();
+
+        if (libPath.isEmpty()) {
+            Path potetialAbsolutePath = Path.of(configuredDir);
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java:203]: Typo - "potential" is written with "n"

File: jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java [hunk 6]
```diff
@@ -196,24 +196,40 @@ public StringProperty laTexFileDirectoryProperty() {
...
-        Optional<Path> foundPath = this.databaseContext.getFileDirectories(preferences.getFilePreferences()).stream()
-                                                       .filter(path -> path.toString().endsWith(configuredDir))
-                                                       .filter(Files::exists).findFirst();
 
-        if (foundPath.isEmpty()) {
-            dialogService.notify(Localization.lang("Path %0 could not be resolved. Using working dir.", configuredDir));
-            return preferences.getFilePreferences().getWorkingDirectory();
+        Path configuredPath = libPath.get().getParent().resolve(configuredDir).normalize();
+
+        // As the user types, the configureDir may become invalid.
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java:212]: The comment is a bit misleading - I think you mean "configDir can be input manually and thus be invalid"

File: jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java [hunk 7]
```diff
@@ -196,24 +196,40 @@ public StringProperty laTexFileDirectoryProperty() {
...
+            return workingDir;
         }
-        return foundPath.get();
+
+        return configuredPath;
     }
 
     private ValidationMessage validateDirectory(String directoryPath, String messageKey) {
+        Optional<Path> libPath = this.databaseContext.getDatabasePath();
+        Path potetialAbsolutePath = Path.of(directoryPath);
```
Comment (koppor) [inline jabgui/src/main/java/org/jabref/gui/libraryproperties/general/GeneralPropertiesViewModel.java:223]: Typo - potential with n

**Review by koppor — CHANGES_REQUESTED** [review]
Small typos in the code.

Need to try out later.

**Comment by koppor** [comment]
Tried it out - works.

File: jablib/src/main/resources/l10n/JabRef_en.properties [hunk 8]
```diff
@@ -1090,7 +1090,7 @@ Expected\ syntax\ for\ --fetch\='<name\ of\ fetcher>\:<query>'=Expected syntax f
 Library-specific\ file\ directory=Library-specific file directory
 User-specific\ file\ directory=User-specific file directory
 LaTeX\ file\ directory=LaTeX file directory
-Path\ %0\ could\ not\ be\ resolved.\ Using\ working\ dir.=Path %0 could not be resolved. Using working dir.
+Path\ %0\ could\ not\ be\ resolved.\ Using\ working\ directory=Path %0 could not be resolved. Using working directory
```
Comment (koppor) [inline jablib/src/main/resources/l10n/JabRef_en.properties:1093]: The dot at the end is lost. 

Sentence DOT second sentence DOT

The second dot is lost.

@paudelritij Are you able to add it or should I do it?

**Review by koppor — CHANGES_REQUESTED** [review]

**Review by koppor — APPROVED** [review]

File: jablib/src/main/resources/l10n/JabRef_en.properties (hunk 8 above)
Comment (paudelritij) [reply jablib/src/main/resources/l10n/JabRef_en.properties]: sry, was on another imp. thing
