### PR TITLE
Fix postgres daemon uses 100% CPU

### LINKED ISSUE #12190: Postgres daemon uses 100% of CPU for several minutes despite indexing deactivated
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-13--5f1dd59 Linux 6.1.0-26-amd64 amd64  Java 23.0.1  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I can't exactly replicate this issue, it occurs a few times a day. The following steps might increase the likelihood to stimulate the issue:
1. I've generally deactivated "fulltext search" or background features in the preference pane.
2. Use (global) search and leave search term in the search field (might be an optional step).
3. Add a new entry to a large DB OR edit the comments field and other field of an existing entry.
4. Save file.

I'm using `top` to see that there is a postgre instance spun off and to check its CPU load. This issue has not occurred under JR5.x.

### Appendix

<details>

<summary>Log File</summary>

```
78754 xxx     25   5  235792  56520  50536 R  99.7   0.4   7:35.39 postgres
```

</details>

### PR DESCRIPTION
**Pull request by LoayTarek5**
### Related issues and pull requests

Closes https://github.com/JabRef/jabref/issues/12190

### PR Description
Added debouncing to IndexManager.updateEntry() using the existing DelayTaskThrottler (200ms delay), previously, every keystroke in the entry editor triggered an immediate index update plus a search requery for each active search group. 
Updates are now applied after the user stops typing.

### Steps to test

- Generate a large library using scripts/bib-file-generator.py
- Open the library and create multiple search groups 
- Select any entry, go to the Comments tab, and type continuously.
- Verify that the index still updates correctly after you stop typing.
- Ensure search groups and global search return correct results without regressions.

Note: I was unable to fully reproduce the 100% CPU usage reported in the issue, but the code path confirms that each keystroke triggers 1 index update + N search group queries without any debouncing. This fix debounces rapid keystrokes into a single update using the DelayTaskThrottler.

### Checklist

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] I manually tested my changes in running JabRef (always required)
- [/] I added JUnit tests for changes (if applicable)
- [/] I added screenshots in the PR description (if change is visible to the user)
- [ ] I added a screenshot in the PR description showing a library with a single entry with me as author and as title the issue number
- [x] I described the change in `CHANGELOG.md` in a way that can be understood by the average user (if change is visible to the user)
- [/] I checked the [user documentation](https://docs.jabref.org/) for up to dateness and submitted a pull request to our [user documentation repository](https://github.com/JabRef/user-documentation/tree/main/en)

### CODE REVIEW

**Comment by LoayTarek5** [comment]
@ytzemih, please, could you test the PR build to see if it resolves the issue?

**Comment by subhramit** [comment]
> @ytzemih, please, could you test the PR build to see if it resolves the issue?

https://blog.jabref.org/2025/05/31/run-pr/

**Comment by ThiloteE** [comment]
@ilippert this PR potentially also fixes issue https://github.com/JabRef/jabref/issues/8977.
It's possible to try the PR with https://blog.jabref.org/2025/05/31/run-pr/

**Comment by Siedlerchr** [comment]
please take a look at the qodo suggestions, I think some of them are actually good hints

**Comment by Siedlerchr** [comment]
Please add a changelog entry, aka we improved the performance...

File: jablib/src/main/java/org/jabref/logic/search/IndexManager.java [hunk 1]
```diff
@@ -157,24 +165,62 @@ public Object call() {
...
+                    existing[1] = event.getNewValue();
+                    return existing;
                 }
-            }.executeWith(taskExecutor);
+            });
         }
+
+        indexUpdateThrottler.schedule(() -> {
+            /// Snapshot and clear pending state atomically
+            List<BibEntry> updatedEntries = new ArrayList<>();
```
Comment (Siedlerchr) [inline jablib/src/main/java/org/jabref/logic/search/IndexManager.java]: This is currently unused, e.g. it's updated but not read

File: jablib/src/main/java/org/jabref/logic/search/IndexManager.java [hunk 2]
```diff
@@ -157,24 +165,62 @@ public Object call() {
...
+                                bibFieldsIndexer.updateEntry(pendingEntry, f);
+                            }
+                            return null;
+                        }
+                    }.onFinished(() -> this.databaseContext.getDatabase()
+                                                           .postEvent(new IndexAddedOrUpdatedEvent(List.of(pendingEntry))))
+                     .executeWith(taskExecutor);
+
+                    if (shouldIndexLinkedFiles.get() && fieldsSnapshot.contains(StandardField.FILE)) {
+                        String[] fileValues = pendingFileValuesByEntry.remove(pendingEntry);
```
Comment (Siedlerchr) [inline jablib/src/main/java/org/jabref/logic/search/IndexManager.java]: Better a create a small record private record FileDelta(String oldValue, String newValue) {} 
to have a clear distinction and better immutabilty

File: jablib/src/main/java/org/jabref/logic/search/IndexManager.java [hunk 3]
```diff
@@ -75,6 +82,7 @@ public IndexManager(BibDatabaseContext databaseContext,
 
         this.bibFieldsSearcher = new BibFieldsSearcher(postgreServer.getConnection(), bibFieldsIndexer.getTable());
         this.linkedFilesSearcher = new LinkedFilesSearcher(databaseContext, linkedFilesIndexer, preferences.getFilePreferences());
+        this.indexUpdateThrottler = new DelayTaskThrottler(200);
```
Comment (Siedlerchr) [inline jablib/src/main/java/org/jabref/logic/search/IndexManager.java]: Use taskExecutor.createThrottler(200), this ensures that the threads are properly shut down

File: jablib/src/main/java/org/jabref/logic/search/IndexManager.java [hunk 4]
```diff
@@ -157,24 +168,56 @@ public Object call() {
...
-            new BackgroundTask<>() {
-                @Override
-                public Object call() {
-                    linkedFilesIndexer.updateEntry(event.getBibEntry(), event.getOldValue(), event.getNewValue(), this);
-                    return null;
+        /// Accumulate which fields need updating for this entry
+        pendingFieldsByEntry.computeIfAbsent(entry, _ -> ConcurrentHashMap.newKeySet()).add(field);
+
+        /// For FILE field: track baseline old value and latest new value
+        if (field.equals(StandardField.FILE)) {
```
Comment (koppor) [inline jablib/src/main/java/org/jabref/logic/search/IndexManager.java]: "Why" is missing here - it just summarizes what the code does, but not WHY

**Review by koppor — DISMISSED** [review]

File: jablib/src/main/java/org/jabref/logic/search/IndexManager.java [hunk 5]
```diff
@@ -157,24 +168,58 @@ public Object call() {
...
+        indexUpdateThrottler.schedule(() -> {
+            /// Snapshot and clear pending state atomically
+            pendingFieldsByEntry.forEach((pendingEntry, fields) -> {
+                if (pendingFieldsByEntry.remove(pendingEntry, fields)) {
+                    Set<Field> fieldsSnapshot = Set.copyOf(fields);
+
+                    new BackgroundTask<>() {
+                        @Override
+                        public Object call() {
+                            for (Field f : fieldsSnapshot) {
```
Comment (calixtus) [inline jablib/src/main/java/org/jabref/logic/search/IndexManager.java]: no abbreviations

**Review by calixtus — APPROVED** [review]

**Comment by calixtus** [comment]
To keep things moving.

File: jablib/src/main/java/org/jabref/logic/search/IndexManager.java [hunk 6]
```diff
@@ -75,6 +85,7 @@ public IndexManager(BibDatabaseContext databaseContext,
 
         this.bibFieldsSearcher = new BibFieldsSearcher(postgreServer.getConnection(), bibFieldsIndexer.getTable());
         this.linkedFilesSearcher = new LinkedFilesSearcher(databaseContext, linkedFilesIndexer, preferences.getFilePreferences());
+        this.indexUpdateThrottler = taskExecutor.createThrottler(200);
```
Comment (ThiloteE) [inline jablib/src/main/java/org/jabref/logic/search/IndexManager.java:88]:
```suggestion
        this.indexUpdateThrottler = taskExecutor.createThrottler(700);
```
If this is comparable to a 200 ms delay, then I would suggest at least 700 ms.

200ms would require a typing speed of 300 characters per minute to not trigger an indexing, which is what I personally can do when I type really fast, but I know from experience that the average persons typing speed is much slower (Once upon a time, I taught some kids and after half a year the fastest was only able to exceed 100 characters per minute).

60 seconds divided by 300 characters = 0.2 seconds per character
60 seconds divided by 100 characters = 0.6 seconds per character

**Comment by ytzemih** [comment]
> > @ytzemih, please, could you test the PR build to see if it resolves the issue?
> 
> https://blog.jabref.org/2025/05/31/run-pr/

Hello all, sorry for the huge delay. I finally found time to update my 5 year old machine to LMDE 7 (Linux Mint) and sway/Wayland:
> JabRef 6.0-alpha.141--2026-06-06--e9b1d76
> Linux 6.12.90+deb13.1-amd64 amd64 
> Java 25.0.3 
> JavaFX 26.0.1+0

*The positive side:* The performance issue seems to have gone. (Sway is cool, and JavaFX issues I had with i3 seem to have gone as well.) I am using my previous set of 4-6 bib files, with around 1000 to 5000 entries, with 5-10 of JR5 regexp-based search groups in each file. I have used the interface (with global search) now for about a week, and my observation is that this issue seems to have gone. 

*The negative side* (I'll make additional reports creating new issues): My impression is that JR6 is slower than JR5 and now consumes more memory than before.

**Comment by Siedlerchr** [comment]
@ytzemih  Thanks a lot for your feedback. Would it be possible to share your bib files (privately) with us so we can use them for analysis?  You can send them to web @ jabref.org 
You can also use the new Pseudonymize feature.

**Comment by ytzemih** [comment]
Hi @Siedlerchr, I can try to prepare a randomised bibfile that resembles a bit my setting.
