### PR TITLE
Fix for issue 6966: open all files of multiple entries

### LINKED ISSUE #6966: Bulk Copy/Open files
I would find it very helpful if it were possible to copy/open multiple attached files at once (after having selected multiple entries and having right-clicked and having selected from the context menu: "copy/open all files attached to the selected entries").

### PR DESCRIPTION
**Pull request by XDZhelheim**
Fixes #6966 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

Added a new function to "Open file" option in the right-click menu.

Now we can open all linked files of the selected entries.

Test videos:

**Single entry selected: the behavior remains unchanged**

  

https://user-images.githubusercontent.com/57553691/117459616-2b2c5d80-af7e-11eb-8539-a4a7006711bf.mp4

**Multiple entries selected**

* All of them have linked files: open them all

    

https://user-images.githubusercontent.com/57553691/117459658-3a131000-af7e-11eb-8596-4f956ca09648.mp4

* Some have and some not: ~~pop out a dialog to ask the user whether to continue, if yes,~~ only open the former and skip the latter

    

https://user-images.githubusercontent.com/57553691/117459682-426b4b00-af7e-11eb-825e-de25510069a6.mp4

* None of them have any linked file: option will be disabled

    

https://user-images.githubusercontent.com/57553691/117459705-48612c00-af7e-11eb-8d47-99d72ed75a38.mp4

To implement these functions, I modified `OpenExternalFileAction` and added a new method `hasPresentFileForSelectedEntries` to check if at least one of the selected entries has linked files in `ActionHelper`.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Idea for usabilty:   As a user I expect to open the file using "open all files" also when I select one entry.  So if I only select one entry => same beahviour as now

**Comment by tobiasdiez** [comment]
In line with @Siedlerchr comment above, what do you think about adding the functionality to the "open file" action? So if a user has only a single entry selected, then the linked file of this entry is opened; but if multiple files are selected, then all linked files are opened.

**Comment by tobiasdiez** [comment]
Yes, please!

**Comment by XDZhelheim** [comment]
Done.

I will update detailed description later.

**Comment by XDZhelheim** [comment]
I noticed that the tests are fixed.

So, is there still anything more I need to change in my code?

**Comment by Siedlerchr** [comment]
You need to push the commit after merging as well, because the tests are still failing

File: src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java [hunk 1]
```diff
@@ -24,32 +25,53 @@ public OpenExternalFileAction(DialogService dialogService, StateManager stateMan
...
-                return;
+            List<LinkedFileViewModel> linkedFileViewModelList = new LinkedList<>();
+            LinkedFileViewModel linkedFileViewModel;
+
+            boolean asked = false;
+
+            for (BibEntry entry:selectedEntries) {
+                if (entry.getFiles().isEmpty()) {
+                    if (!asked) {
+                        boolean continu = dialogService.showConfirmationDialogAndWait(Localization.lang("Missing file"),
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java:51]: I, personally, don't think it's necessary to present a dialog here to the user. To me it seems obvious that only the files will open from entries that have associated files 
So just ignore them.

**Review by Siedlerchr — CHANGES_REQUESTED** [review]

**Comment by XDZhelheim** [comment]
Done.

Removed dialog and resolved a conflict in `CHANGELOG.md`

File: src/main/java/org/jabref/gui/actions/ActionHelper.java [hunk 2]
```diff
@@ -81,6 +81,39 @@ public static BooleanExpression isFilePresentForSelectedEntry(StateManager state
...
+     */
+    public static BooleanExpression hasPresentFileForSelectedEntries(StateManager stateManager, PreferencesService preferencesService) {
+        return Bindings.createBooleanBinding(() -> {
+            ObservableList<BibEntry> selectedEntries = stateManager.getSelectedEntries();
+            List<LinkedFile> files;
+            for (BibEntry entry:selectedEntries) {
+                files = entry.getFiles();
+
+                if ((entry.getFiles().size() > 0) && stateManager.getActiveDatabase().isPresent()) {
+                    if (files.get(0).isOnlineLink()) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/actions/ActionHelper.java:100]: I would exclude online file links. Otherwise you will suddenly have 300 Tabs open if you select 300 entries and they have at least one link

File: src/main/java/org/jabref/gui/actions/ActionHelper.java [hunk 3]
```diff
@@ -81,6 +81,39 @@ public static BooleanExpression isFilePresentForSelectedEntry(StateManager state
...
+                        return true;
+                    }
+
+                    Optional<Path> filename = FileHelper.find(
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/actions/ActionHelper.java:104]: No need to check the filename for presence here, just later on try to open the file. Either it works or not.

File: src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java [hunk 4]
```diff
@@ -24,32 +24,41 @@ public OpenExternalFileAction(DialogService dialogService, StateManager stateMan
...
             final List<BibEntry> selectedEntries = stateManager.getSelectedEntries();
 
-            if (selectedEntries.size() != 1) {
-                dialogService.notify(Localization.lang("This operation requires exactly one item to be selected."));
-                return;
+            List<LinkedFileViewModel> linkedFileViewModelList = new LinkedList<>();
+            LinkedFileViewModel linkedFileViewModel;
+
+            for (BibEntry entry:selectedEntries) {
+                if (!entry.getFiles().isEmpty()) {
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java:46]: An entry can have multiple files linked. I would suggest you open all

**Review by Siedlerchr — CHANGES_REQUESTED** [review]
some improvements necessary

**Comment by XDZhelheim** [comment]
OK. I will fix it.

File: src/main/java/org/jabref/gui/actions/ActionHelper.java (hunk 2 above)
Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/actions/ActionHelper.java:100]: What's the difference to selecting 300 entries that have pdf attached?

Comment (XDZhelheim) [reply src/main/java/org/jabref/gui/actions/ActionHelper.java:100]: Should we set a limit?
For example, if a user is trying to open 100 files, pop out a dialog to ask the user whether to continue or cancel.
But how to determine the limit.

**Comment by XDZhelheim** [comment]
Two changes:
1. open all linked files of an entry
2. modify boolean binding

Under discussion: how to handle opening a large number of files?

File: src/main/java/org/jabref/gui/actions/ActionHelper.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/actions/ActionHelper.java]: Yep, that's a good idea. "You are about to open more than 10 files". Continue?
I would simply create a constant with 10. I think that's appropriate.
  - Continue /  Cancel

Comment (XDZhelheim) [reply src/main/java/org/jabref/gui/actions/ActionHelper.java]: OK.

**Comment by XDZhelheim** [comment]
> Yep, that's a good idea. "You are about to open more than 10 files". Continue?
> I would simply create a constant with 10. I think that's appropriate.
> 
> * Continue /  Cancel

Done.

P.S. Online links are included.

Test video:

https://user-images.githubusercontent.com/57553691/118133561-915c2900-b433-11eb-91b7-5d6561d50014.mp4

File: src/main/java/org/jabref/gui/actions/ActionHelper.java [hunk 5]
```diff
@@ -81,6 +81,26 @@ public static BooleanExpression isFilePresentForSelectedEntry(StateManager state
...
+    /**
+     * Check if at least one of the selected entries has linked files
+     * <br>
+     * Used in {@link org.jabref.gui.maintable.OpenExternalFileAction} when multiple entries selected
+     * @param stateManager manager for the state of the GUI
+     * @param preferencesService services of preferences
+     * @return a boolean binding
+     */
+    public static BooleanExpression hasLinkedFileForSelectedEntries(StateManager stateManager, PreferencesService preferencesService) {
+        return Bindings.createBooleanBinding(() -> {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/actions/ActionHelper.java:93]: This will result in a constant binding, i.e. changing the selected entries will not update the binding. For this to work, you need to specify `selectedEntries` also as a second parameter. Or even better use `EasyBind.reduce(statemanager.getSelectedEntries(), entries -> entries.anyMatch(entry -> !entry.getFiles().isEmpty())`

File: src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java [hunk 6]
```diff
@@ -24,32 +28,51 @@ public OpenExternalFileAction(DialogService dialogService, StateManager stateMan
...
+                            preferencesService.getFilePreferences(),
+                            ExternalFileTypes.getInstance());
+
+                    linkedFileViewModelList.add(linkedFileViewModel);
+                }
+            }
+
+            // ask the user when detecting # of files > FILES_LIMIT
+            if (linkedFileViewModelList.size() > FILES_LIMIT) {
+                boolean continu = dialogService.showConfirmationDialogAndWait(Localization.lang("Opening large number of files"),
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java:67]: rename variable to `continue`

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
Thanks, changle look good to me. Two smaller suggestions

File: src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java (hunk 6 above)
Comment (XDZhelheim) [reply src/main/java/org/jabref/gui/maintable/OpenExternalFileAction.java:67]: `continue` is a keyword of Java. I will change to another meaningful name.

File: src/main/java/org/jabref/gui/actions/ActionHelper.java (hunk 5 above)
Comment (XDZhelheim) [reply src/main/java/org/jabref/gui/actions/ActionHelper.java]: Frankly I did not see any wrong behavior of the binding. See the video `6966-4` above: first I selected three entries with no linked file, the option is disabled. And then I selected another entry which has, then the option is enabled. Maybe I misunderstood your explanation.

Anyway, I modified the boolean binding as you suggested. Now the code is much conciser, and the behavior remains normal. Besides, I'm not so sure about the usage of `EasyBind`, are my codes correct?

Thanks again for your advice!

Comment (tobiasdiez) [reply src/main/java/org/jabref/gui/actions/ActionHelper.java]: To be honest, I also didn't understood why it worked before. Maybe the binding was re-created every time? Not sure.

Anyway, the new code looks good. Thanks for the update.

**Review by tobiasdiez — APPROVED** [review]

**Review by Siedlerchr — APPROVED** [review]
