### PR TITLE
Fix/use format conversion for all imports

### LINKED ISSUE #6532: New entry from DOI, entries always for bibtex not biblatex
JabRef 5.1--2020-05-23--03e3663
Windows 10 10.0 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

At least importing an entry from a DOI fills the Bibtex fields and not, as the library is defined, the biblatex ones.

1. Set the Default bibliographic mode to biblatex
2. Library > New entry for DOI 10.1126/science.1188363
3. Fields Date and Journaltitle are empty and Year (month) and Journal are filled

### PR DESCRIPTION
**Pull request by DominikVoigt**
This PR adds conversion of entries into the desired format for all imports.
Fixes #6532. 

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please fix the l10n errors:
```
This\ query\ uses\ an\ unsupported\ syntax.
This\ search\ contains\ entries\ that\ match\ all\ specified\ terms.
1. CHECK IF THE KEY IS REALLY NOT USED ANYMORE
2. REMOVE THESE FROM THE ENGLISH LANGUAGE FILE
 ==> expected: <[]> but was: <[This\ query\ uses\ an\ unsupported\ syntax., This\ search\ contains\ entries\ that\ match\ all\ specified\ terms.]> org.opentest4j.AssertionFailedError
org.opentest4j.AssertionFailedError: Obsolete keys found in language properties file: 
This\ query\ uses\ an\ unsupported\ syntax.
This\ search\ contains\ entries\ that\ match\ all\ specified\ terms.
```

**Comment by koppor** [comment]
Can you add a test for https://github.com/koppor/jabref/issues/330, too?

File: src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java [hunk 1]
```diff
@@ -64,6 +67,8 @@ public void fetchAndMerge(BibEntry entry, List<Field> fields) {
                 if (fetcher.isPresent()) {
                     BackgroundTask.wrap(() -> fetcher.get().performSearchById(fieldContent.get()))
                                   .onSuccess(fetchedEntry -> {
+                                      ImportCleanup cleanup = new ImportCleanup(BibDatabaseModeDetection.inferMode(new BibDatabase(List.of(entry))));
```
Comment (koppor) [inline src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java:70]: Doesn't the BasePanel (`panel`) know the mode? Shouldn't that mode be used instead of guessing?

File: src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java [hunk 2]
```diff
@@ -147,6 +152,8 @@ public void fetchAndMerge(BibEntry entry, EntryBasedFetcher fetcher) {
         BackgroundTask.wrap(() -> fetcher.performSearch(entry).stream().findFirst())
                       .onSuccess(fetchedEntry -> {
                           if (fetchedEntry.isPresent()) {
+                              ImportCleanup cleanup = new ImportCleanup(BibDatabaseModeDetection.inferMode(new BibDatabase(List.of(entry))));
```
Comment (koppor) [inline src/main/java/org/jabref/gui/mergeentries/FetchAndMergeEntry.java:155]: See above

**Review by koppor — CHANGES_REQUESTED** [review]
Codewise, it looks good
