### PR TITLE
Fixed error when specifying general fields by correcting unwanted characters list

### LINKED ISSUE #6604: Can't edit "Set up general fields"
JabRef version  on 

JabRef 5.1--2020-06-08--b810356
Linux 5.3.0-53-generic amd64 
Java 14.0.1

1. Options/Set up general fields
2. Don't change anything.   (Or do.)
3. Hit OK
4. Error popup.

image

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

### PR DESCRIPTION
**Pull request by alex-petrov-vt**
Fixes #6604 by correcting the list of unwanted characters 

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java [hunk 1]
```diff
@@ -58,8 +58,9 @@ public void saveFields() {
                 return;
             }
 
-            String testString = CitationKeyGenerator.cleanKey(parts[1], preferences.getUnwantedCharacters());
-            if (!testString.equals(parts[1]) || (parts[1].indexOf('&') >= 0)) {
+            String unwantedChars = "#{}()~,^&-\"'`ʹ\\";
```
Comment (Siedlerchr) [inline src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java:61]: Please use the unwanted chars from the preferences

Comment (alex-petrov-vt) [reply src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java:61]: I thought the problem was that the list of unwanted chars from the preferences did not correspond to the unwanted characters for this particular case. I.e. the characters in the log message below are not the same that are stored in preferences. For example, ';' character is fine in this case because it's used to separate fields, but it is on the list of unwanted characters in preferences

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java:61]: Ah okay, thanks for clarifying this.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java:61]: Please also add a changelog entry and fix the checkstyle issue

Comment (alex-petrov-vt) [reply src/main/java/org/jabref/gui/customizefields/CustomizeGeneralFieldsDialogViewModel.java:61]: Okay, I'll do later on tonight

**Comment by calixtus** [comment]
Would be nice, if you could also add a short clearifying comment, so the next time someone works on this, one won't reintroduce the bug here, and we don't have to dig into the git history.

**Comment by calixtus** [comment]
The markdown linter still produces errors:
```
CHANGELOG.md:12 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Added"]
CHANGELOG.md:13 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- We improved responsiveness o..."]
docs/adr.md:5:26 MD042/no-empty-links No empty links [Context: "[template.md]()"]
docs/getting-into-the-code/code-howtos.md:32 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
docs/getting-into-the-code/code-howtos.md:48 MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "TODO: Usage of status bar and ..."]
```

**Comment by alex-petrov-vt** [comment]
Sorrry about that, accidentally deleted empty line after section header. Hope this fixed it
