### PR TITLE
Fixes exception in preview using regexp search and regexp search without specified field

### LINKED ISSUE #6777: regexp search throws exception when entering slash
JabRef 5.1--2020-08-22--dc55a76
Linux 5.4.19-050419-generic amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open bib file
2. Switch to regexp search
3. Enter something with a "/" in it, e.g. bla/bla
4. For each matching entry you get an exception (see details below) thrown. I had once about 50 results, so 50 windows with an exception trace opened.  

Maybe the regular expression could be checked and an exclamation mark icon shown as long as it is incomplete or not escaped before it's executed. Or, one could employ some automatic escaping. 

<details>
  <summary>Log File</summary>
  
 netscape.javascript.JSException: SyntaxError: Invalid regular expression: missing )
	at org.jabref.merged.module@5.1.876/com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at org.jabref.merged.module@5.1.876/com.sun.webkit.WebPage.executeScript(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.scene.web.WebEngine.executeScript(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.preview.PreviewViewer.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.1.876/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.1.876/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
</details>

### PR DESCRIPTION
**Pull request by k3KAW8Pnf7mkmdSMPHz27**
Fixes #6777 . The issue originates in how the JavaScript regexp is created in `PreviewViewer#highlightSearchPattern`.

1. Fixes the use of regexp while searching for one term (e.g., `Liu.*`)
2. Fixes exception in the preview when forward slash is used in the regexp

- [x] ~Change in CHANGELOG.md described (if applicable)~
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] ~Screenshots added in PR description (for UI changes)~
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

File: src/main/java/org/jabref/gui/preview/PreviewViewer.java [hunk 1]
```diff
@@ -144,7 +144,7 @@ private void highlightSearchPattern() {
                     "var markInstance = new Mark(document.getElementById(\"content\"));" +
                             "markInstance.unmark({" +
                             "  done: function(){" +
-                            "    markInstance.markRegExp(/" + pattern + "/gmi);" +
+                            "    markInstance.markRegExp(/" + pattern.replaceAll("/", "\\\\/") + "/gmi);" +
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline src/main/java/org/jabref/gui/preview/PreviewViewer.java:147]: Since `/` terminates the JavaScript regexp, it should be escaped. The issue with using `new RegExp` is that you will have to escape the string terminator instead, so it is more code without any benefit that I am aware of.

File: src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java [hunk 2]
```diff
@@ -232,7 +232,7 @@ public Boolean visitComparison(SearchParser.ComparisonContext context) {
             if (fieldDescriptor.isPresent()) {
                 return comparison(fieldDescriptor.get().getText(), ComparisonOperator.build(context.operator.getText()), right);
             } else {
-                return new ContainBasedSearchRule(caseSensitive).applyRule(right, entry);
+                return SearchRules.getSearchRule(caseSensitive, regex).applyRule(right, entry);
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java:235]: @Siedlerchr perhaps the `if` solution is better here? This might be too frivolous application of the DRY principle.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Is there a good spot to put test cases for this issue?

File: src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java (hunk 2 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java:235]: Doesn't really matter in this case, think it's okay. Didn't think about this way.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
This PR can be made better by some larger reformatting but there might not be a point to doing it given that the code should be completely replaced by Lucene.

**Comment by Siedlerchr** [comment]
I think it's not too important to have the highlighting that accurate for each complicated regex and yeah in the longterm we plan to use/convert to lucence. And thanks for finding the issue with the grammar based search + the regex!

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
As you are at the search code and as you also worked on the unicode normalization, can you maybe check that issue here as well? https://github.com/JabRef/jabref/issues/6815

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> As you are at the search code and as you also worked on the unicode normalization, can you maybe check that issue here as well? #6815

Sure, will do !

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> I think it's not too important to have the highlighting that accurate for each complicated regex and yeah in the longterm we plan to use/convert to lucence.

I agree, and I haven't really looked into this in enough detail to contribute. There are definitively still going to be other issues after this PR. It just aims to address the most obvious cases of the `/` exception.

> And thanks for finding the issue with the grammar based search + the regex!

Thank you for the sanity check and help, it is both appreciated and saves me time ^^

File: src/main/java/org/jabref/gui/preview/PreviewViewer.java [hunk 3]
```diff
@@ -144,7 +144,7 @@ private void highlightSearchPattern() {
                     "var markInstance = new Mark(document.getElementById(\"content\"));" +
                             "markInstance.unmark({" +
                             "  done: function(){" +
-                            "    markInstance.markRegExp(/" + pattern + "/gmi);" +
+                            "    markInstance.markRegExp(/" + pattern.replaceAll("(?<!\\\\)/", "\\\\/") + "/gmi);" +
```
Comment (koppor) [inline src/main/java/org/jabref/gui/preview/PreviewViewer.java:147]: Would it be possible to extract this as constant (and thus documenting why this replacement is done)?

**Review by koppor — CHANGES_REQUESTED** [review]
At first, LGTM.

Minor issue with a magic string replacmenet 😇 

May I ask whether its possible to add a test case for the fixed functionality?

File: src/main/java/org/jabref/gui/preview/PreviewViewer.java (hunk 3 above)
Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/preview/PreviewViewer.java:147]: Sure. I just need to get JDK 15 going for those text blocks X)
I keep getting some errors with my setup.

Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/preview/PreviewViewer.java:147]: @k3KAW8Pnf7mkmdSMPHz27 Source level is still jdk14, the textblock function is still preview. We only use jdk15  for compiling the jpackage stuff. (except for windows, where jdk14 is still required due to a jdk jpackage bug)

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/preview/PreviewViewer.java:147]: That explains 😁

File: src/main/java/org/jabref/gui/preview/PreviewViewer.java [hunk 4]
```diff
@@ -137,23 +145,26 @@ public void setTheme(Theme theme) {
...
+     * Returns the String representation of a JavaScript regex object. The method does not take into account differences between the regex implementations in Java and JavaScript.
+     *
+     * @param regex Java regex to print as a JavaScript regex
+     * @return JavaScript regex object
+     */
+    private static String createJavaScriptRegex(Pattern regex) {
+        String pattern = regex.pattern();
+        // Create a JavaScript regex using the forward slash pattern
+        pattern = UNESCAPED_FORWARD_SLASH.matcher(pattern).replaceAll("\\\\/");
+        return "/" + pattern + "/gmi";
```
Comment (k3KAW8Pnf7mkmdSMPHz27) [inline src/main/java/org/jabref/gui/preview/PreviewViewer.java:167]: @koppor 
> Would it be possible to extract this as constant (and thus documenting why this replacement is done)?

I noticed that I misunderstood you. I have extracted the String constants (as well) and hopefully improved readability. I don't think I should be more explicit regarding the forward replacements, unless I also link to how to use a JavaScript regex literal (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions). Perhaps I should add this link?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> May I ask whether its possible to add a test case for the fixed functionality?

I'll look into it tomorrow. I don't have any experience writing tests for this type of code but there should be some "template" I can use elsewhere.

**Comment by Siedlerchr** [comment]
Regarding tests, you are lucky, as there is already one: https://github.com/JabRef/jabref/blob/master/src/test/java/org/jabref/model/search/rules/ContainBasedSearchRuleTest.java
(Please also refactor the BibEntry to "withField" )

File: src/main/java/org/jabref/gui/preview/PreviewViewer.java (hunk 4 above)
Comment (koppor) [reply src/main/java/org/jabref/gui/preview/PreviewViewer.java:167]: Yes, I like links in the code. Even if there are opinions that they might oudate. Neverthless, 1 good link is better than 0 links

Comment (k3KAW8Pnf7mkmdSMPHz27) [reply src/main/java/org/jabref/gui/preview/PreviewViewer.java]: Well, I compromised and added the link I believe is the least likely to get outdated 😛

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I keep running into the same issue with creating a `PreviewViewerTest`.

```java
BibDatabaseContext databaseContext = new BibDatabaseContext();
StateManager stateManager = new StateManager();
stateManager.setSearchQuery(new SearchQuery("test", false, false));

PreviewViewer pw = new PreviewViewer(databaseContext, null, stateManager);
```

As soon as I call the constructor I get a java.lang.ExceptionInInitializerError

**Comment by Siedlerchr** [comment]
If you want to test something on the javafx thread, you need to use the testfx extensions and declare it as GUI test:
See as an example the SourceTabTest under gui.entryeditor.

**Review by Siedlerchr — APPROVED** [review]

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr @koppor thank you both for your reviews! They are very appreciated!

---

> If you want to test something on the javafx thread, you need to use the testfx extensions and declare it as GUI test:
> See as an example the SourceTabTest under gui.entryeditor.
> But that is complicated. I would rather merge this one as it is now. Feel free to create another PR with a gui test

Great! In that case, I'll put adding a test case for this issue on my todo-list for later.
Thank you for linking SourceTabTest, now I know where to start digging 😃 
I suspect I'll have opportunities to practice writing GUI tests soon X)
