### PR TITLE
Fixes the issue "Non valid number as font size results in an uncaught exception."

### LINKED ISSUE #7415: Non valid number as font size results in an uncaught exception.
Latest JabRef version build on Ubuntu 20.04.1 LTS.

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

If you enter a non valid value such as a character to the font size spinner under the appearances tab in the preference dialog and press enter, 2 exception dialogs will appear.
1. Open JabRef.
2. Click on Options
3. Click on Preferences
4. Click on Appearance.
5. In the "size" box, enter a char such as `a`.
6. Press the <kbd>Enter</kbd> key. Two uncaught exception dialogs will appear.
7. Pressing on the preferences dialog after pressing ok to the two exception dialogs, a third exception dialog will appear.

<details>
  <summary>Log File</summary>
  
  ```
  java.lang.NumberFormatException: For input string: "a"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at javafx.base/javafx.util.converter.IntegerStringConverter.fromString(IntegerStringConverter.java:49)
	at javafx.base/javafx.util.converter.IntegerStringConverter.fromString(IntegerStringConverter.java:35)
	at javafx.controls/javafx.scene.control.Spinner.commitValue(Spinner.java:460)
	at javafx.controls/javafx.scene.control.Spinner.lambda$new$3(Spinner.java:168)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.graphics/javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:8155)
	at javafx.graphics/javafx.scene.Node.setFocused(Node.java:8208)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.setWindowFocused(Scene.java:4032)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.lambda$new$0(Scene.java:4054)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setFocused(Window.java:674)
	at javafx.graphics/javafx.stage.Window$1.setFocused(Window.java:149)
	at javafx.graphics/com.sun.javafx.stage.WindowHelper.setFocused(WindowHelper.java:112)
	at javafx.graphics/com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:64)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
	at javafx.graphics/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1351)
	at javafx.graphics/com.sun.glass.ui.Window.notifyFocus(Window.java:1330)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:347)
	at javafx.graphics/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:509)
	at javafx.graphics/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:635)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Stage.java:465)
	at javafx.controls/javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.controls/javafx.scene.control.Dialog.showAndWait(Dialog.java:346)
	at org.jabref@100.0.0/org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:192)
	at org.jabref@100.0.0/org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(FallbackExceptionHandler.java:26)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:832)

  ```
</details>

### PR DESCRIPTION
**Pull request by Landi29**
Fixes  #7415

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Please fix the checkstyle issues, otherwise lgtm!

**Review by calixtus — CHANGES_REQUESTED** [review]
Please use org.jabref.gui.util.OnlyIntegerFormatter

**Comment by Siedlerchr** [comment]
@calixtus  The problem is that the OnlyIntegerFormatter returns null for no value and this will throw an exception in the spinner IntegerConverter (was my first attempt either)

**Comment by Landi29** [comment]
Just to comment on that @Siedlerchr, the `Textformatter<Integer>` also returns null on no input, at least when I did a manual test.

**Comment by calixtus** [comment]
Isn't it possible to pass a default value as an argument to the constructor?

**Comment by Landi29** [comment]
@calixtus  Are you referring to the `OnlyIntegerFormatter` or the null reference exception? In either case, a default value is passed to the `TextFormatter`, but a null reference exception can still happen.

**Comment by Landi29** [comment]
The Database tests fail. Can someone elaborate on this.

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
The database test sometimes fail for no reason, not related to you changes

**Comment by calixtus** [comment]
> @calixtus Are you referring to the `OnlyIntegerFormatter` or the null reference exception? In either case, a default value is passed to the `TextFormatter`, but a null reference exception can still happen.

I was referring to the OnlyIntegerFormatter. But I am satisfied. Thank you for your work here.

**Comment by Landi29** [comment]
@calixtus you are welcome.

**Comment by Landi29** [comment]
@calixtus I think you need to approve before we can merge, since you requested changes.

File: src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java [hunk 1]
```diff
@@ -27,6 +31,16 @@
 
     private final ControlsFxVisualizer validationVisualizer = new ControlsFxVisualizer();
 
+    // The fontSizeFormatter formats the input given to the fontSize spinner so that non valid values cannot be entered.
+    private TextFormatter<Integer> fontSizeFormatter = new TextFormatter<Integer>(new IntegerStringConverter(), 9,
+            c -> {
+                if (Pattern.matches("\\d*", c.getText())) {
+                    return c;
+                }
+                c.setText("0");
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java:40]: I think returning `null` here is slightly better, at least according to the documentation "Returning null rejects the change." https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TextFormatter.html#getFilter--

File: src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java [hunk 2]
```diff
@@ -27,6 +31,16 @@
 
     private final ControlsFxVisualizer validationVisualizer = new ControlsFxVisualizer();
 
+    // The fontSizeFormatter formats the input given to the fontSize spinner so that non valid values cannot be entered.
+    private TextFormatter<Integer> fontSizeFormatter = new TextFormatter<Integer>(new IntegerStringConverter(), 9,
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java:35]: As this might be handy also in other places, I would propose to extract this to a static method in the a helper class `gui.util.TextFormatter`

File: src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java [hunk 3]
```diff
@@ -27,6 +31,16 @@
...
+            c -> {
```
Comment (tobiasdiez) [inline src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java:36]: please don't use abbreviations as variable names. Here `change` would be good.

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
Thanks! A few very minor remarks from my side. Apart from this, +1 for merge.

File: src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java (hunk 1 above)
Comment (Siedlerchr) [reply src/main/java/org/jabref/gui/preferences/appearance/AppearanceTab.java:40]: See the comments in this thread. Returning null will produce an exception in the spinner
